cloudflare/workers-sdk

- packages/wrangler/src/index.tsx
- packages/wrangler/src/user.tsx
This is a very simple PR that adds support for `CF_ACCOUNT_ID` and `CF_ACCOUNT_TOKEN` to be passed in. I tested this with `kv:namespace list` but looking at the code it should work for all just commands fine.
(Thanks for making Wrangler v2 in TS 🧡)
> Add support for CF_ACCOUNT_ID and CF_API_TOKEN

- packages/wrangler/bin/wrangler.js
[Related Issue](https://github.com/cloudflare/wrangler2/issues/33)
Adds `process.versions.node` to the *Invalid Node.js version error*, to allow people to see if something may be interfering with them using the recommended Node version for wrangler.
> Add Current Node Version to Error

- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
* `wrangler publish` is faster
* First, script upload is attempted.
* If that succeeds, all routes/schedules are applied in parallel.
* If `workers.dev` subdomain is _new_, add 5 second delay to prevent negative cache-hits.
* `--triggers` renamed to `--schedules`
* We have already rebranded "triggers" to not just be cron, but also routes. For now, `--triggers` are still supported as an alias. 
* `wrangler publish` supports multi-zone routes:
* e.g. `wrangler publish --route=example.com --route=anotherdomain.com`
* Notice you don't need a `zone` or `zone_id` for any of them!
* Experimental flag for services, which is currently hidden.
```sh
$ npm run start -- \
publish index.js --name=test12345 \
--route=test.example.com \
--route=test.anotherdomain.com \
--schedule="5 4 * * *"
```
```txt …
```
> Make publish faster, support multi-zone routes

- packages/wrangler/package.json
So that when wrangler2 is installed along @cloudflare/wrangler, they can each be referenced in npm run scripts.
See https://github.com/cloudflare/wrangler/pull/2139
> Add `wrangler2` as an alias

- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This commit lets you bind a worker to durable objects defined on external scripts. The configuration is the same as wrangler v1:
```
[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter", script_name = "counter-durable"}]
```
> Durable Objects 1: bind to external scripts

- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
When you start your project with `npx wrangler@beta dev src/index.ts --env staging` it would fail with this error:
```
/Users/luzanne/Projects/my-worker/node_modules/wrangler/wrangler-dist/cli.js:27069
throw ex;
^
TypeError: Cannot read properties of undefined (reading 'jsxFactory')
```
After debugging some stuff I found out that the `envRootObj` was not set correctly.`config['env.staging']` does not work, accessing properties goes only 1 deep.
This PR will fix that issue and use the correct config provided by the env variable.
Might be better to also add an extra check here. When an env variable is provided in the arguments, it must be available in the config as well? Thats up to you :)
Config object:
```
{
_: [ 'dev' ],
env: 'staging',
local: false,
ip: '127.0.0.1',
port: 8787, …
```
> Pick correct config object when passing env argument

- package.json
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/sites.tsx
- packages/wrangler/src/tail.tsx
This PR sends forward `migrations` (as defined in https://developers.cloudflare.com/workers/learning/using-durable-objects#durable-object-migrations-in-wranglertoml) when publishing. 
- When publishing, this tries to check existing migration tag, and send migrations only after those from `wrangler.toml`
- However, this in't working as expected. While the migrations get executed, the previous tag is not showing when fetching script details, so it's not possible to figure out which migrations to execute. I think I need to send forward the current migration tag when publishing, but I'm not certain where I'm supposed to do so, and my experiments haven't been fruitful yet. Landing this regardless for now.
- Further `wrangler dev` doesn't appear to 'just work', even though I've been told it's …
> Durable Objects 1.5: Tagged migrations (partial)

- packages/example-worker-app/wrangler.toml
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This PR does proper tagged migrations, fixing some of the issues from #67.  So now you can publish durable objects. Nice.
Next up, we should have better validation and suggestions on how to make migrations (what I'm calling 'guided migrations'). Also, I have to fix `wrangler dev` for durable objects.
> Durable Objects 1.6: actual Tagged Migrations

- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This commit adds `--polyfill-node` as a cli argument and `polyfill_node` as a config field. It uses https://github.com/remorses/esbuild-plugins / https://github.com/ionic-team/rollup-plugin-node-polyfills/ for the polyfills. I also added a warning for the tradeoffs whenever this config is used. We may want better polyfills in the future, and maybe even better messaging if we can recognise popular libraries and suggest replacements.
> Implement `--polyfill-node`/ `config.polyfill_node`

- packages/wrangler/src/dev.tsx
This commit adds durable object bindings when in local mode for `wrangler dev`. (We still have to make durable object bindings work for 'remote' mode, that'll happen soo.)
> bind durable objects in local mode

- packages/wrangler/src/pages.tsx
Brings behavior parity with `wrangler dev` by persisting KV, DO & Cache to disk when developing locally.
> Persist KV, DO & Cache locally when `wrangler pages dev`-ing

- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
This PR separates the idea of a worker's name from the main module/script's file name. This is part of an upcoming fix to get wrangler dev for Durable Objects working.
> A Worker name is not the main module's name.

- .github/workflows/pages-ci.yml
This adds a GitHub Action to deploy the `pages` branch to `wrangler@pages`. We'll be able to use this to more quickly iterate on Pages specific features.
> Add Pages CI to publish wrangler@pages

- .changeset/swift-lamps-shop.md
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/preview.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
When proxying to the preview endpoint, we need to pass the named host as the target header. This PR fixes the host name generation in `preview.ts`. I also took this opportunity to remove some variable aliases.
> make `wrangler dev` work with durable objects

- .github/workflows/prereleases.yml
This change ensures that the prerelease workflow does not run on non-source forks of the repository.
> Only run prelease workflow on cloudflare repository

- .changeset/pretty-monkeys-invent.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/module-collection.ts
- packages/wrangler/src/publish.ts
This is the first of what I think will be a few PRs for supporting non-js modules in workers. When esbuild scans the module graph, we collect references to some well known file types, mark them as `external`, and instead add them directly to the worker form upload. This prevents the need to configure this in `wrangler.toml` or whatever.
In the next PR, I'll do `.wasm` support in a similar vein.
Once we have that in place, I'll probably work on a `--loader` flag to define custom types.
> import text file types into bundles

- .changeset/thin-terms-walk.md
- packages/wrangler/src/module-collection.ts
Following up from https://github.com/cloudflare/wrangler2/pull/107, this PR adds support for importing `.wasm` files. Specifically, it works directly on the output of [`workers-rs`](https://github.com/cloudflare/workers-rs). I'll test with other wasm outputs (like assemblyscript etc) later.
> support importing `.wasm` files / `workers-rs` support

- packages/wrangler/package.json
- packages/wrangler/src/__tests__/mock-cfetch.js
Not sure how, but some shenanigans with #105 broke how we resolve `path-to-regexp` (and I think it's actually accurate now?) and broke our tests. This PR fixes the tests. Also a stray package.json fix.
No changeset for this fix.
> pass tests from #105

- .changeset/clever-toys-retire.md
- packages/wrangler/src/index.tsx
There are a couple of reasons we don't want to log the contents; it could be secret, or it could just be very long. This commit changes the messaging to instead just say which file is being uploaded. I also took this opportunity to add a log when we're deleting a key with `kv:key delete <key>`.
> don't log file contents when writing via `kv:key put <key> --path <path>`

- .prettierignore
- packages/example-worker-app/public/404.html
- packages/example-worker-app/public/index.html
- packages/wrangler/CHANGELOG.md
This commit adds a `.prettierignore` config, and runs prettier on the whole codebase, catching some files we'd missed out on.
There's no changeset required for this commit.
> add `.prettierignore`, run it on the whole codebase

- .changeset/three-cooks-type.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
> prefer `worker` package export conditionals if available

- .changeset/long-ligers-study.md
- packages/wrangler/src/pages.tsx
Somehow introduced a small bug with #105 . Miniflare doesn't seem to like using undici's Request type directly. Not quite sure why, and I don't have time to completely figure it out this week.
But here's a quick fix.
Also adds fallback 404 behavior which I also missed in #105.
> Fix proxy request typing bug and fallback 404 behavior in pages

- .changeset/strong-penguins-report.md
- .github/workflows/tests-typecheck.yml
- package-lock.json
- package.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/api/inspect.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dialogs.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/pages.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/user.tsx
- tsconfig.json
Enabling that lint rule exposed a bunch of places where we weren't logging errors, and also caught at least 3 bugs. Glad I did this.
I also disabled prettier as an eslint error,  and added it to the `check` script instead.
I added `ioredis` as a root dependency. We don't use it, but we can't pass typecheck without it installed (because miniflare uses it, even tho it's an optional dep, and there's no good way to disable a third party's type errors in this fashion)
I also added `react-error-boundary` so we don't blow up completely, and have an option to handle errors from `dev` gracefully.
> enable `@typescript-eslint/no-floating-promises`, pass lint+type check

- .changeset/cold-fireants-provide.md
- .github/workflows/prereleases.yml
- .github/workflows/release.yml
To be sure that Tests, Linting and type checking is occurring on code before it is merged and released/pre-released other workflows have the Testing workflow as a trigger. For example the Tests need to complete and be successful before the prerelease will run.
Tested the full contribution -> changeset -> PR -> merge -> prerelease and release flow on a fork, to as closely test the GitHub Workflows are properly running in a realistic situation. 
Whenever the a PR is closed/merged the Workflow will trigger for checking for a changeset and adding it to the changeset "Version" PR, when the "Version" PR is closed/merged it will trigger a release.
> CI/CD: Release trigger

- .vscode/settings.json
Update VSCode settings for the default formatter to be set to Prettier
Removed the ESLint format setting and language specific formatting as well.
> VSCode Settings: Prettier

- .changeset/forty-cooks-flash.md
- .changeset/short-humans-repeat.md
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/dialogs.tsx
- packages/wrangler/src/index.tsx
See the individual commits...
- Simplify log capturing in tests 
- test: align init error message with wrangler 1
- test: always restore jest mocks after each test
- test: move confirm() and prompt() into an object for easier mocking
- fix: error and exit if init --type is used
- test: ensure fixture clean up is resilient to missing files
- fix: allow the user to exit init if there is already a toml file
> Further wrangler `init` tests (and refactorings)

- .changeset/purple-rice-fail.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/dialogs.tsx
- packages/wrangler/src/index.tsx
As mentioned in https://github.com/cloudflare/wrangler2/pull/124#discussion_r770953444, it's possible to use regular exports from a module, but still be able to mock their implementations in jest. This PR does so, and passes tests.
> export functions from dialogs.tsx, pass tests

- .changeset/swift-beers-mix.md
- .github/workflows/tests-typecheck.yml
Removed the build step from tests, which should speed up the Tests Workflow.
Added a branch specific trigger for `Release`, now the workflow for `Release` should only work on PRs closed to main
Removed the `Changeset PR` Workflow. Now the `Release` workflow will handle everything needed for Changesets
> Removing Tests Build & Adding Release Trigger constraints

- .github/workflows/tests-typecheck.yml
Old Workflow had a job dependency for the tests to run the previous job had to finish. Removed that so the tests can run and the YAML would be valid.
> Removed Job Dependency

- .github/workflows/release.yml
Doing so before causes a problem when the changesets release action
tries to change the branch it fails.
> Copy the README during the changesets release action

- .changeset/eighty-books-chew.md
- .changeset/warm-moles-march.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/pages.tsx
Hey! 👋 This PR upgrades `miniflare` to version `2.0.0-rc.4`: https://github.com/cloudflare/miniflare/releases/tag/v2.0.0-rc.4.
This version includes support for logging unhandled rejections instead of crashing, which is automatically enabled when using the CLI, and also available as the `logUnhandledRejections` option. Whilst adding this, I thought I'd make a couple other tiny changes to `pages dev`, which have been approved by @GregBrimble in conversation.
- Enabled source map support for nicer stack traces (requires adding `sourcemap: true` to the esbuild options in `@cloudflare/pages-functions-compiler` `buildWorker` function)
- Enabled incoming HTTP request logging
- Added colours and prefixes to Miniflare logs (this also dims internal lines in stack traces for easier debugging) …
> Upgrade `miniflare` to `2.0.0-rc.4` & `pages dev` quick wins

- .github/workflows/release.yml
The `release.yml` script had bad syntax, the `publish` field doesn't accept arrays, it has to be a single command. This was breaking our changesets flow (and we may have lost some changelogs). This PR fixes the script. I'll probably merge this directly right now.
> fix: `release.yml`'s changeset publish script should be a single command

- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mock-cfetch.js
Tests that rely on the results of other tests can be difficult to debug
and make maintenance more complex.
> test: ensure that kv:namespace tests are independent of each other

- .github/workflows/pages-ci.yml
- .github/workflows/prereleases.yml
- .github/workflows/release.yml
- .github/workflows/tests-typecheck.yml
Previously the caching was occurring on the `~/.npm` the cache is now directly caching `node_modules` 
caching node_modules at any directory level. 
To prevent restoring `node_modules` when the cache changed, the cache action is given no `restore-keys` in the cache Action. The `id` is added to the cache Action which is used at the NPM install step the cache is checked using `id` and skips install if the cache exists.
> Caching node_modules in Workflows

- .github/workflows/prereleases.yml
- README.md
The CI/CD would try to checkout to another branch for creating the Changesets PR or adding to it. When it attempted to checkout after the README was copied from the root of the monorepo to the Wrangler package it would have an unstaged file, then abort the checkout and fallback to creating a new branch to handle the new file.
Solution:
- Moved Wrangler README to Wrangler package
- Created Monorepo README in root of repo
- Removed the script for copying README from root into Wrangler package
> README relocation

- .changeset/flat-wombats-sneeze.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/pages.tsx
Fixes #137 .
The file extension of the asset is used to guess at the mime-type of the file and is attached to the `Content-Type` header before serving.
> Add Content-Type header to `wrangler pages dev`'s static assets

- .changeset/silly-rockets-rescue.md
- .gitignore
- package-lock.json
- packages/wrangler/src/kv.tsx
> TL;DR; Function `getNamespaceId` in `packages/wrangler/src/kv.tsx` was completely broken and not working.
> And I added `packages/wrangler/wrangler.toml` to `.gitignore`, useful for testing manually ^^
- If we pass no preview or preview set to false, we will get: `No preview ID found for ${binding}. Add one to your wrangler config file to use a separate namespace for previewing your worker.` error
- If we pass preview set to true we will get: `${binding} has both a namespace ID and a preview ID. Specify "--preview" or "--preview false" to avoid writing data to the wrong namespace.` error
- If we delete id from config and leave preview_id we will get `No namespace ID found for ${binding}. Add one to your wrangler config file to use a separate namespace for previewing your worker.` error …
> Fixed KV getNamespaceId

- .changeset/young-buses-try.md
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
There are 3 types of 'bindings' that we upload with a worker definition: `vars`, `kv_namespaces`, and `durable_objects`. These are configured in `wrangler.toml`, and get passed through to the api that uploads a worker definition (in `form_data.ts`), when using `dev` and `publish` commands.
We currently serialise it as a big `variables` object, where the key of the objects defines the binding "name", and the value contains information to be bound. (https://github.com/cloudflare/wrangler2/blob/0330ecf1b54c92dfe86cb3f38394f453ed418381/packages/wrangler/src/index.tsx#L507-L530) This code sucks for many reasons: it loses some type information, hard to read/grok, hard to add new types of bindings, and mostly it's unnecessary.
This PR refactors this code to instead mostly preserve the …
> Refactor how we pass bindings from config to the worker upload api.

- .changeset/shiny-crews-warn.md
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
Adds support for experimental worker-to-worker bindings, letting you call a worker from another worker. The Wrangler config field looks like follows:
```toml
services = [{ name = "foo", script_name = "foo-service", environment = "production" }]
```
Where:
- `name` is the name of the binding in your worker code
- `script_name` is the script to reference
- `environment` is the environment of the script to reference (e.g. `production`, `staging`, etc)
- The API still doesn't support worker-to-worker bindings for previews, so `wrangler dev` will fail for now
This PR is based in #156, with a few changes -
- the configuration field `env` is renamed to `environment` (we want to move away from short forms like `env`)
- the configuration field `environment` is not an optional field (because we …
> Experimental worker-to-worker bindings support

- .changeset/early-games-buy.md
- packages/wrangler/src/index.tsx
Fixes issue #147 
The `filename` from args didn't handle relative paths passed in from users with scripts in subfolders.
To handle the subfolder pathing a `path.relative` using `cwd()` to user input `filepath` to the `filepath` variable passed into `Dev`
> Subfolder Relative Pathing Fix

- .github/workflows/tests-typecheck.yml
- package.json
By adding the build step to this test workflow, we can ensure that we don't ever merge anything that breaks the main branch and its auto release workflow.
> Add built to tests

- .changeset/sharp-humans-reply.md
- packages/wrangler/src/dev.tsx
When calling miniflare in `dev,` the bindings are incorrectly passed into the process that's spawned; each arg needs to be a separate element in the args array to the spawn call. This PR fixes that. It also enables logs on the miniflare process. (They're a bit noisy, but we can make that better separately.)
I'm personally annoyed because I can swear this was working previously, but without tests that's just my word against... my own word, lol.
fixes #172
> pass bindings correctly to miniflare in `dev`

- .github/version-script.js
We now check for lint fails before we publish to npm (via https://github.com/cloudflare/wrangler2/pull/175). The script that rewrites `pacakges/wrangler/package.json` doesn't add a newline to the end oft he generated file, which makes `prettier --check` fail. This PR adds that newline, and should make the script pass.
> Add a new line to the generated package.json in the prerelease script

- .changeset/large-guests-retire.md
- package.json
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dialogs.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.tsx
- packages/wrangler/src/pages.tsx
- packages/wrangler/src/proxy.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/src/user.tsx
This PR enables eslint's `no-shadow` rule. I started a refactor of a couple of pieces and found myself getting confused with vars that claimed to be defined without it being so. The `no-shadow` rule prevents vars from being defined in inner scopes if they've already been defined in an outer scope.
This PR is mostly clean. It did lead to some wordy vars in `index.tsx`, but that's fine, it only made them more obvious.
I didn't bother doing this in `pages.tsx`, I'll leave that up to the pages team. Instead, I've just disabled the rule for that file.
> enable eslint's `no-shadow` rule

- .changeset/new-candles-collect.md
- packages/wrangler/src/dev.tsx
In https://github.com/cloudflare/wrangler2/pull/164/, we added `token` to `useWorker`'s `useEffect` array that detects when to start the server process. However, the effect itself sets `token`, so the build would inifinitely restart on every run.
We could potentially fix this by using `useMemo` or something, but that's overkill for the reason we use `token` - to detect whether it's the first or subsequent time we've started the server, and what message to log to the terminal. So we introduce a ref `startedRef` to play that role, and mark it as true when we log the message the first time. This fixes the infinite loop.
This bug shows how urgent it is to write tests for everything else. We'll get there.
> fix: prevent `dev` from infinitely restarting

- .changeset/selfish-eagles-drop.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/pages.tsx
Hey! 👋 This PR upgrades `miniflare` to version `2.0.0-rc.5`: https://github.com/cloudflare/miniflare/releases/tag/v2.0.0-rc.5.
This version implements service bindings and matches some other core behaviour of the Workers runtime, like blocking asynchronous I/O outside request handlers, and limiting request recursion depth. It also doesn't proxy primitive classes like `Object` by default, fixing #91. The old behaviour can be enabled with `--proxy-primitive` for Rust workers. See [this comment](https://github.com/cloudflare/miniflare/blob/720794accee7582b01e849182244a65ce60c9d60/packages/core/src/plugins/core.ts#L487-L555) for more details.
---
Local service bindings are not yet implemented in this PR. We need to have a discussion about how best to do these.
Normally, you'd just need to set …
> Upgrade `miniflare` to `2.0.0-rc.5`

- .changeset/modern-hounds-fold.md
- packages/wrangler/pages/functions/filepath-routing.ts
- packages/wrangler/pages/functions/routes.ts
- packages/wrangler/pages/functions/template-worker.ts
This PR disables the `@typescript-lint/no-explicit-any` eslint rule in pages code. The Pages team should fix this, since it's causing noise in our PRs. I've also filed an issue to fix this at https://github.com/cloudflare/wrangler2/issues/201.
> Disable `@typescript-lint/no-explicit-any` eslint rule in pages code

- .changeset/config.json
This PR changes the format in which changelogs are generated. We use the `@changesets/changelog-github` package, which is a better default than we have now. It includes the PR number and author id. and has links to commit/PR/author.
Example changelog - https://github.com/changesets/changesets/blob/main/packages/cli/CHANGELOG.md
> modify changelog format

- .changeset/metal-ties-invent.md
- packages/wrangler/src/pages.tsx
Fixes #204.
Silently fail to auto-open the browser in `wrangler pages dev` command when that errors out.
The user can manually open their browser, and everything else still works.
> Silently fail to auto-open browser in

- .changeset/purple-planets-join.md
- packages/wrangler/src/pages.tsx
Adds a new `wrangler pages functions build` command which takes the `functions` folder and compiles it into a single Worker. This was already done in `wrangler pages dev`, so this PR just exposes this build command for use in our build image, or for people who want to do it themselves.
> Add-pages-functions-build-command

- .github/changeset-version.js
- .github/workflows/release.yml
Workaround a problem in changesets where it does not update the package-lock.json
after the version has been bumped in package.json.
See https://github.com/changesets/changesets/issues/421
Fixes #198
> Ensure package-lock.json is updated on release

- .changeset/new-carrots-relax.md
- packages/wrangler/src/index.tsx
This PR is a breaking change. We'll keep it as a patch release tho.
We want to change the behaviour of `--public` to closer match Pages behaviour, and only really expose it in v2.1 (maybe even after that).
This PR renames the field as `experimental-public`, and adds warnings. In a future PR we'll actually change the behaviour.
> rename `--public` as `--experimental-public`

- .changeset/fuzzy-ads-rush.md
- packages/wrangler/pages/functions/filepath-routing.test.ts
- packages/wrangler/pages/functions/filepath-routing.ts
- packages/wrangler/pages/functions/template-worker.ts
Fixes #110
Reverses the execution order of Pages Functions middlewares.
Now, a directory like
```txt
- functions
- _middleware.ts     // a
- api
- _middleware.ts   // b
- todo
- _middleware.ts // c
- d.ts
```
will execute with the order, a -> b -> c -> d, for requests to `/api/todo/d`
> Reverse execution order of Pages Functions middlewares

- .changeset/fluffy-insects-clap.md
- packages/wrangler/pages/functions/filepath-routing.ts
Fixes #75
More strictly check file extensions when crawling the `/functions` directory to ensure we're only trying to include JS files.
> Ignore non-JS files when compiling Pages Functions

- .changeset/unlucky-sloths-lay.md
- packages/wrangler/src/pages.tsx
Fixes #219 
Adds a `--live-reload` option to `wrangler pages dev` which automatically reloads HTML pages when a change is detected
> Add live reload to wrangler pages dev

- .changeset/brown-planes-sip.md
- packages/wrangler/src/pages.tsx
I had forgotten to actually connect it up, so it was entirely ineffective.
> Fix the `--watch` option of `wrangler pages functions build`

- .changeset/grumpy-knives-bathe.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/pages/functions/buildWorker.ts
- packages/wrangler/pages/functions/template-worker.ts
- packages/wrangler/src/pages.tsx
Hey! 👋 This PR upgrades `miniflare` to version `2.0.0`. There were only a couple changes since `2.0.0-rc.5`, mostly around making `fetch` behave more like Cloudflare's. See the [bottom of the changelog](https://github.com/cloudflare/miniflare/releases/tag/v2.0.0).
I've also made another few minor tweaks to `pages dev`:
1. **Remove redundant immediate pages dev rebuilds/reloads:** watching `all` events without `ignoreInitial` set to `true` means `chokidar` calls the callback immediately. This caused functions to be built twice, and Miniflare to be `reload`ed immediately after startup.
2. **Wait for esbuild to finish before starting Miniflare:** instead of using a `scriptReady` boolean, this now uses a deferred `Promise`, so the event loop isn't blocked. This is now `await`ed before …
> Upgrade `miniflare` to `2.0.0` 🎉

- .changeset/pretty-starfishes-judge.md
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
Closes https://github.com/cloudflare/wrangler2/issues/193.
This PR adds cli fields for 2 existing configuration fields: `--compatibility-date`, `--compatibility-flags` matching `compatibility_date` and `compatibility_flags` respectively. It also adds a cli arg `--latest` which is shorthand for `--compatibility_date <today>`. It follows the rules from the linked issue -
- A cli arg for adding a compatibility data, e.g  `--compatibility_date 2022-01-05`
- A shorthand `--latest` that sets `compatibility_date` to today's date. Usage of this flag logs a warning.
- `latest` is NOT a config field in `wrangler.toml`.
- In `dev`, when a compatibility date is not available in either `wrangler.toml` or as a cli arg, then we default to `--latest`.
- In `publish` we error if a compatibility date is …
> Add `--compatibility-date`, `--compatibility-flags`, `--latest` cli arguments to `dev` and `publish`

- CONTRIBUTING.md
- package.json
- packages/create-workers-app/package.json
- packages/example-worker-app/package.json
Also ensure that the package.json scripts are consistent.
---
By the way, I looked into blocking the use of `npm install` directly in packages and could find no nice way to do it. Any `install` or `preinstall` scripts in package.json do not run until after the node_modules directory has been filled; and also these scripts will run even if you do the `npm install` from the top level, so you would need a way to flag to the script not to run in this case. And moreover, these scripts would be included in the distributable of wrangler, which would mean they would run when you installed wrangler as a user.
> docs: add more detail to the CONTRIBUTING docs

- .changeset/angry-schools-walk.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/proxy.ts
Closes #205.
This PR refactors how we setup the proxy server between the developer and the edge preview service during `wrangler dev`. Of note, we start the server immediately. We also buffers requests/streams and hold on to them when starting/refreshing the token. This means a developer should never see `ERR_CONNECTION_REFUSED` error page, or have an older worker respond after making a change to the code. And when the token does get refreshed, we flush said streams/requests with the newer values, making the iteration process a lot smoother and predictable.
> refactor: proxy/preview server

- .changeset/loud-dolls-pay.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
While using `wrangler dev ./index` I get
```
TypeError: Cannot read properties of undefined (reading '0')
at null.build (/home/jgentes/workers/wrangler2/packages/wrangler/src/dev.tsx:411:15)
```
This is caused due to the `entry` value being verbatim what was used as a command line argument, ie. `./index`, whereas the `entryPoint` value in `result.metafile.outputs` has the extension added to the file, ie `./index.js`.
I'm going to submit a PR that uses what esBuild recognizes as the input value in `result.metafile.inputs` instead of the `entry` value:
```
const chunks = Object.entries(result.metafile.outputs).find(
([_path, { entryPoint }]) =>
entryPoint === Object.keys(result.metafile.inputs)[0]
) // assumedly only one entry point
```
> allow specifying only "index" without extension or nothing at all to launch "wrangler dev"

- .changeset/good-rats-shave.md
- packages/wrangler/src/config.ts
This PR cleans up the type definition for the configuration object, as well as commenting the hell out of it. There are no duplicate definitions, and I annotated what I could.
- `@optional` means providing a value isn't mandatory
- `@deprecated` means the field itself isn't necessary anymore in `wrangler.toml`
- `@breaking` means the deprecation/optionality is a breaking change from wrangler 1
- `@todo` means there's more work to be done (with details attached)
- `@inherited` means the field is copied to all environments
I also added a stub for the validation function that will be applied to config objects. In the next PR, I will flesh that function out.
You should review this with split view, since the unified view doesn't really make sense here.
> refactor: simplify and document `config.ts`

- .changeset/early-seahorses-impress.md
- package-lock.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.1.0`. This is mostly just bug fixes from the `2.0.0` release. See the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.1.0).
> Upgrade `miniflare` to `2.1.0`

- package-lock.json
Primarily the new `run-all` dependency was being tracked in package-lock as a devDep.
> Fix out of date package-lock.json file

- .changeset/ten-cooks-warn.md
- packages/wrangler/src/inspect.ts
Some simple strict-null fixes but also a refactor to use react memo hooks in inspector code.
Previously the proxy server and websocket server were created in ref hooks.
But this prevented TypeScript from understanding that they were always defined when needed.
By using memo hooks we get this typing for free; and also can lean on react to handle recreating them as needed.
> Refactor `inspector` code to pass strict-null checks

- .changeset/serious-coins-provide.md
- packages/wrangler/src/index.tsx
The description for the `kv:bulk delete` command was wrong, it was probably copied earlier from the `kv:bulk put` command. This PR fixes the mistake.
> fix: description for `kv:bulk delete <filename>`

- .changeset/strong-flies-add.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
We introduced some bugs in recent PRs:
- In https://github.com/cloudflare/wrangler2/pull/196, we broke being able to pass an entrypoint directly to the cli. In this PR, I just reverted that fix. I'll reopen https://github.com/cloudflare/wrangler2/issues/78 and we'll tackle it again later. (cc @jgentes)
- In https://github.com/cloudflare/wrangler2/pull/215, we broke being able to publish a script by just passing `--latest` or `--compatibility-data` in the cli. This PR fixes that by reading the correct argument when choosing whether to publish.
- In https://github.com/cloudflare/wrangler2/pull/247, we broke how we made requests by passing headers to requests. This PR reverts the changes made in `cfetch/internal.ts`. (cc @petebacondarwin)
- In …
> fix: fix `dev` and `publish`

- .changeset/cyan-fireants-study.md
- package-lock.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.2.0`. This contains some new `HTMLRewriter` stuff and a few more bug fixes. See the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.2.0).
> chore: upgrade `miniflare` to `2.2.0`

- .changeset/tricky-lemons-warn.md
- packages/wrangler/src/pages.tsx
The solution in #211 doesn't work, because the error is thrown by the child process returned by the `open` function, not by the `open` itself.
Tested with GitHub Codespaces.
> Fix silent failure when browser open doesn't work

- .changeset/clever-turtles-shake.md
- packages/wrangler/src/dev.tsx
In #262 some of the strict null fixes were removed to resolve a regression.
This refactor re-applies these fixes in a way that avoids that problem.
> refactor: tidy up the typings of the build result in dev

- .changeset/big-steaks-design.md
- packages/wrangler/pages/functions/filepath-routing.ts
- packages/wrangler/pages/functions/routes.ts
- packages/wrangler/pages/functions/template-worker.ts
- packages/wrangler/src/pages.tsx
Sits on top of https://github.com/cloudflare/wrangler2/pull/240
> Strict null checks for `pages` code

- .changeset/heavy-paws-relate.md
- .changeset/young-horses-jam.md
- CONTRIBUTING.md
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
The `publish` command was failing when the entry-point was specified in the wrangler.toml file and the entry-point imported another file.
This was because we were using the `metafile.inputs` to guess the entry-point file path. But the order in which the source-files were added to this object was not well defined, and so we could end up failing to find a match.
This fix avoids this by using the fact that the `metadata.outputs` object will only contain one element that has the `entrypoint` property - and then using that as the entry-point path. For runtime safety, we now assert that there cannot be zero or multiple such elements.
Fixes #252
> fix: correctly handle entry-point path when publishing 

- .changeset/orange-cycles-rule.md
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
This actually slightly changes the processing of the environment configuration.
Previously there were corner cases where the configuration might just crash.
These are now handled more cleanly with more appropriate warnings.
The yargs commands have been refactored slightly to be more consistent.
Now each command that can be either in local or remote mode is structured the same way.
The `config` is extracted from the args, then there is an `if-then-else` statement that handles the local and remote cases.
This ensures that the `account_id` has the correct typings in remote mode as needed.
> Refactor `index.tsx` (and `config.ts`) to pass strict-null checks

- package.json
Because project are valid in node version over `16.7.0`, so changed engine version in package file.
> Bump up engine version to valid one

- .changeset/quiet-pianos-try.md
- packages/wrangler/pages/functions/filepath-routing.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/inspect.ts
- packages/wrangler/src/publish.ts
- tsconfig.json
The codebase is now strict-null compliant and the CI checks will fail if a PR tries to introduce code that is not.
> refactor: enable TypeScript strict-null checks

- .changeset/modern-beers-repair.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
When a (non-yargs) error surfaces to the top level,
we know also show a link to Github to encourage the developer to report an issue.
> feat: add a link to create a github issue when there is an error.

- .changeset/quiet-steaks-smoke.md
- .vscode/settings.json
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
Builds on top of #270.
- Use the same hashing strategy for asset keys (xxhash64)
- Include the full path (from cwd) in the asset key
- Match include and exclude patterns against full path (from cwd)
- Validate that the asset key is not over 512 bytes long
> fix: align publishing sites asset keys with Wrangler 1 

- .changeset/cyan-comics-sneeze.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/user.tsx
- packages/wrangler/src/whoami.tsx
> Feature: add whoami

- .changeset/tall-cheetahs-juggle.md
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
Any errors embedded in the response from the Cloudflare API were being lost, because `fetchInternal()` would throw on a non-200 response. This PR fixes that behaviour:
- It doesn't throw on non-200 responses
- It first gets the response text with `.text()` and converts it to an object with `JSON.parse`, so in case the api returns a non json response, we don't lose response we were sent.
Unfortunately, because of the nature of this abstraction, we do lose the response `status` code and `statusText`, but maybe that's acceptable since we have richer error information in the payload. I considered logging the code and text to the terminal, but that may make it noisy.
Before: (note the generic http error message)
After: (note the cloudflare error code and message)
> fix: propagate api errors to the terminal correctly.

- .changeset/popular-weeks-march.md
- packages/wrangler/src/publish.ts
When we pass a non-js file as entry to esbuild, it generates a `.js` file. (which, that's the whole job of esbuild, haha). So, given `<source>/index.ts`, it'll generate `<destination>/index.js`. However, when we try to 'find' the matching file to pass on as an input to creating the actual worker, we try to use the original file name inside the destination directory. At this point, the extension has changed, so it doesn't find the file, and hence we get the error that looks like `ENOENT: no such file or directory, open '/var/folders/3f/fwp6mt7n13bfnkd5vl3jmh1w0000gp/T/tmp-61545-4Y5kwyNI8DGU/src/worker.ts'`
The actual path to the destination file is actually the key of the block in `metafile.outputs` that matches the given `output.entryPoint`, so this PR simply rewrites the logic to use …
> fix: use entrypoint specified in esbuild's metafile as source for building the worker

- packages/wrangler/src/__tests__/mock-cfetch.ts
- packages/wrangler/src/__tests__/publish.test.ts
> test: add test for incorrect entry-point path computation

- .changeset/lovely-elephants-reflect.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
Is it enough to log a warning? Or should we throw a `new DeprecationError()`?
Fixes #282
> fix: warn if the `site.entry-point` configuration is found during publishing

- .changeset/strange-melons-provide.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/inspect.ts
This PR adds more special logic for some data types that get logged via `console` methods. Types like `Promise`, `Date`, `WeakMaps`, and some more, now get logged correctly (or at least, better than they used to).
This PR also fixes a sinister bug - the `type` of the `ConsoleAPICalled` events don't match 1:1 with actual console methods (eg: `console.warn` message type is `warning`). This PR adds a mapping between those types and method names. Some methods don't seem to have a message type, I'm not sure why, but we'll get to them later.
> feature: add more types that get logged via `console` methods

- .changeset/sour-toys-heal.md
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/mock-console.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/run-wrangler.ts
- packages/wrangler/src/index.tsx
This PR adds some enhancements/fixes to the `wrangler init` command.
- doesn't overwrite `wrangler.toml` if it already exists
- installs `wrangler` when creating `package.json`
- offers to install `wrangler` into `package.json` even if `package.json` already exists
- offers to install `@cloudflare/workers-types` even if `tsconfig.json` already exists
- pipes stdio back to the terminal so there's feedback when it's installing npm packages
This does have the side effect of making our tests a _little_ slower. I added `--prefer-offline` to the `npm install` calls to make this a shade quicker, but I can't figure out a good way of mocking these. I'll think about it some more later. We should work on making the installs themselves quicker (re: https://github.com/cloudflare/wrangler2/issues/66) …
> feat: enhance `wrangler init`

- packages/wrangler/src/__tests__/run-in-tmp.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
Since we would only want to mock out the home directory when we are also running in a tmp directory, it makes sense to combine these. This also makes this behaviour available for other tests outside the `whoami.test.ts` file.
> test: move home directory mocking into the `runInTempDir()` helper

- .changeset/twelve-bears-yell.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
This PR adds an assertion error for making sure a `[site]` definition always has a `bucket` field.As a cleanup, I made some small fixes to the `Config` type definition, and modified the tests in `publish.test.ts` to use the config format when creating a `wrangler.toml` file.
> feat: error if a site definition doesn't have a `bucket` field

- .changeset/shaggy-suns-warn.md
- packages/wrangler/src/index.tsx
We were using `--prefer-offline` when running `npm install` during `wrangler init`. The behaviour is odd, it doesn't seem to fetch from the remote when the cache isn't hit, which is not what I'm expecting. So we remove `--prefer-offline`.
> fix: remove `--prefer-offline` when running `npm install`

- .changeset/ten-fireants-camp.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
We were running custom builds as a regular command with `execa`. This would fail whenever we tried to run compound commands like `cargo install -q worker-build && worker-build --release` (via https://github.com/cloudflare/wrangler2/issues/236). The fix is to use `shell: true`, so that the command is run in a shell and can thus use bash-y syntax like `&&`, and so on. I also switched to using `execaCommand` which splits a command string into parts correctly by itself.
Fixes https://github.com/cloudflare/wrangler2/issues/236
> fix: custom builds should allow multiple commands

- .changeset/quick-colts-smash.md
- packages/wrangler/src/inspect.ts
- packages/wrangler/src/proxy.ts
When we run `wrangler dev`, the session that we setup with the preview endpoint doesn't last forever, it dies after ignoring it for 5-15 minutes or so. The fix for this is to simply reconnect the server. So we use a state hook as a sigil, and add it to the dependency array of the effect that sets up the server, and simply change it every time the server closes.
Fixes https://github.com/cloudflare/wrangler2/issues/197
(In wrangler1, we used to restart the whole process, including uploading the worker again, making a new preview token, and so on. It looks like that they may not have been necessary.)
> fix: restart the `dev` proxy server whenever it closes

- .changeset/poor-actors-join.md
- packages/wrangler/src/pages.tsx
With https://github.com/cloudflare/wrangler2/commit/8ff55376ffb8f9db24d56fef6ee2c6bd5cc0527d, we introduced a ready promise to ensure Miniflare had a script to run with `wrangler pages dev`.
This PR resolves that promise when providing a static script (in the case of no functions folder or Worker script being provided).
> Fix wrangler pages dev failing to start for just static assets

- .changeset/two-coins-compare.md
- .prettierrc
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
Thought it was time to pull my finger out and send a PR, now that I don't have the "but I don't know Rust" defence to lean back on...
> Disable persistence by default (unless --enable-persistence passed)

- .changeset/bright-needles-dance.md
- packages/wrangler/src/dev.tsx
This fix passes the correct worker name to `syncAssets` during `wrangler dev`. This function uses the name to create the backing kv store for a Workers Sites definition, so it's important we get the name right.
I also fixed the lint warning introduced in https://github.com/cloudflare/wrangler2/pull/321, to pass `props.enableLocalPersistence` as a dependency in the `useEffect` call that starts the "local" mode dev server.
> fix: pass worker name to syncAssets in `dev`

- .changeset/calm-bananas-obey.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/proxy.ts
When we run `wrangler dev`, we start a server on a port (defaulting to 8787). We do this separately for both local and edge modes. However, when switching between the two with the `l` hotkey, we don't 'wait' for the previous server to stop before starting the next one. This can crash the process, and we don't want that (of course). So we introduce a helper function `waitForPortToBeAvailable()` that waits for a port to be available before returning. This is used in both the local and edge modes, and prevents the bug right now, where switching between edge - local - edge crashes the process.
(This isn't a complete fix, and we can still cause errors by very rapidly switching between the two modes. A proper long term fix for the future would probably be to hoist the proxy server hook above …
> fix: wait for port to be available before creating a dev server

- .changeset/brown-chefs-own.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/cfetch/index.ts
When fetching a list of results from cloudflare APIs (e.g. when fetching a list of keys in a kv namespace), the api returns a `cursor` that a consumer should use to get the next 'page' of results. It appears this cursor can also be a blank string (while we'd only account for it to be `undefined`). By only accounting for it to be `undefined`, we were infinitely looping through the same page of results and never terminating. This PR fixes it by letting it be a blank string (and `null`, for good measure)
> fix: prevent infinite loop when fetching a list of results

- .changeset/dry-panthers-lie.md
- packages/wrangler/src/pages.tsx
This hides `wrangler pages functions` in the main help menu, since it's only intended for internal usage right now. It still "works", so nothing changes in that regard. We will bring this back when we have a broader story in wrangler for functions.
> fix: hide `wrangler pages functions` in the main help menu

- .changeset/khaki-peas-divide.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/dev.tsx
Update esbuild to 0.14.14. Also had to change `import esbuild from "esbuild";` to `import * as esbuild from "esbuild";` in `dev.tsx`.
> chore: update esbuild

- .changeset/green-timers-eat.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/sites.tsx
Based on https://github.com/cloudflare/wrangler2/pull/336
This adds environments support for Workers Sites. Very simply, it uses a separate kv namespace that's indexed by the environment name. This PR also changes the name of the kv namespace generated to match wrangler 1's implementation.
> feat: environments for Worker Sites

- .changeset/rare-eggs-bathe.md
- package-lock.json
- package.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/mock-cfetch.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/preview.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/inspect.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/src/user.tsx
- tsconfig.json
There are several reasons to replace `node-fetch` with `undici`:
- `undici`'s `fetch()` implementation is set to become node's standard `fetch()` implementation, which means we can just remove the dependency in the future (or optionally load it depending on which version of node is being used)
- `node-fetch` pollutes the global type space with a number of standard types
- we already bundle `undici` via `miniflare`/pages, so this means our bundle size could ostensibly become smaller.
This replaces `node-fetch` with `undici`.
- All instances of `import fetch from "node-fetch"` are replaced with `import {fetch} from "undici"`
- `undici` also comes with spec compliant forms of `FormData` and `File`, so we could also remove `formdata-node` in `form_data.ts`
- All the global types that were …
> chore: replace `node-fetch` with `undici`

- .github/ISSUE_TEMPLATE/bug-template.yaml
- .github/ISSUE_TEMPLATE/config.yml
Improved ergonomics for OSS contributing to the project. The `config.yml` will allow for blank issues to still be created.
If in the future the CI/CD needs to help with maintenance or other bottlenecks, templates can be used to help constrain the Workflow trigger events in Actions. 
Besides the Bug Report template there is a additional field created in the `config.yml` that will offer people join the community by clicking on the link. This can encourage community growth as well as Support like questions being moved towards Discord rather than Issues.
> Issue Template: Bug 

- .changeset/fluffy-poems-tell.md
- packages/wrangler/src/dev.tsx
Just a quick fix to accept uppercase hotkeys during `dev`.
> fix: support uppercase hotkeys in `wrangler dev`

- .changeset/friendly-melons-laugh.md
- packages/wrangler/pages/functions/filepath-routing.test.ts
- packages/wrangler/pages/functions/filepath-routing.ts
- packages/wrangler/pages/functions/routes.ts
- packages/wrangler/src/pages.tsx
- packages/wrangler/src/paths.ts
Previously route paths were manipulated by file-system path utilities.
On Windows this resulted in URLs that had backslashes, which are invalid for such URLs.
Fixes cloudflare#51
Closes cloudflare#235
Closes cloudflare#330
Closes cloudflare#327
> fix: generate valid URL route paths for pages on Windows

- .changeset/many-eggs-deny.md
- packages/wrangler/src/pages.tsx
When setting up a project using pages in advanced mode (using a `_worker.js` file), wrangler 2 just quits with no error.
This is because `await scriptReadyPromise;` on line 866 only ever resolves when there are functions in a functions directory.
This PR fix's the issue by calling `scriptReadyResolve()` outside of the `if (existsSync(scriptPath))` condition.
> fix: pages advanced mode usage

- .changeset/early-lies-sniff.md
- packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.tsx
The api for fetching a kv value, unlike every other cloudflare api, returns just the raw value as a string (as opposed to the `FetchResult`-style json). However, our fetch utility tries to convert every api response to json before parsing it further. This leads to bugs like https://github.com/cloudflare/wrangler2/issues/359. The fix is to special case for `kv:key get`.
Fixes https://github.com/cloudflare/wrangler2/issues/359.
> fix: `kv:key get`

- .changeset/olive-glasses-camp.md
- packages/wrangler/src/index.tsx
Followup from https://github.com/cloudflare/wrangler2/pull/372#discussion_r798854509, just removing some unnecessary calls to `process.cwd()`/`path.join()`, since they're already relative to where they're called from.
> fix: remove redundant process.cwd() calls in `wrangler init`

- .changeset/sixty-fishes-doubt.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/sites.tsx
The previous xxhash package we were using required a build step, which relied upon tooling that was not always available on Window.
This version is a portable WASM package.
> refactor: use xxhash-wasm for better compatibility with Windows

- .prettierignore
To avoid `npm run check` from failing locally.
> fix: add `example-remix-pages-app` artifacts to `.prettierignore`

- .changeset/nine-toes-impress.md
- package-lock.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.3.0`. See the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.3.0). Closes https://github.com/cloudflare/wrangler2/issues/394.
> chore: upgrade `miniflare` to `2.3.0`

- .changeset/big-dodos-float.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/publish.ts
Although, `build.upload.dir` is deprecated, we should still support using it when the entry-point is being defined by the `build.upload.main` and the format is `modules`.
Fixes #413
> fix: support `build.upload.dir` when using `build.upload.main`

- .changeset/healthy-monkeys-count.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/open-in-brower.ts
- packages/wrangler/src/pages.tsx
- packages/wrangler/src/user.tsx
We open browser windows for a few things; during `wrangler dev`, and logging in. There are environments where this doesn't work as expected (like codespaces, stackblitz, etc). This fix simply logs an error instead of breaking the flow. This is the same fix as https://github.com/cloudflare/wrangler2/pull/263, now applied to the rest of wrangler.
> fix: don't crash when browser windows don't open

- .changeset/silly-students-add.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
Added additional fields to get projects ready to publish as soon as possible.
- The name will check if the Worker is named if not defaults to the parent directory name.
- The workers_dev field is now initialized default true
partial #399
> polish: Added Wrangler TOML fields

- .changeset/orange-hats-yell.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
To get wrangler init projects up and running with good ergonomics for deploying and development,
added default scripts "start" & "deploy" with assumed TS or JS files in generated ./src/index.
The name property is now derived from user input on `init <name>` or parent directory if no input is provided. 
partial #399
> polish: `package.json` tweaks

- .github/workflows/release.yml
In the Release GH Workflow the old filename was still used for sourcemap URL remapping.
> fix: incorrect script name

- .github/workflows/experimental-wasm-release.yml
This adds a github workflow that publishes every commit to the `experimental-wasm` branch directly to npm, tagged as `@wasm`. This is based on the same workflow we were doing for `@pages` builds.
> Add a github workflow to publish `wrangler@wasm` builds.

- .github/workflows/experimental-wasm-release.yml
I missed a configuration field, this should fix it.
> fix: publishes from `experimental-wasm` branch

- .github/workflows/prereleases.yml
- .github/workflows/release.yml
Adding additional uploads of artifacts to Sentry in prerelease workflow and experimental WASM release.
> Additional Sentry Uploads

- .changeset/healthy-cooks-perform.md
- .vscode/settings.json
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
Implements support for raw bindings as described in #358 
Raw bindings can be defined in the `unsafe.bindings` table array in wrangler.toml as -
[[unsafe.bindings]]
name = "my-binding"
type = "binding-type"
The TOML table will then be directly inserted into the metadata upload for a Worker in JSON format as though it were a binding made by wrangler itself. Note, these bindings cannot be detected by tools like miniflare, so support for specific binding types is sparse and limited.
> feat: support for raw "unsafe bindings"

- .changeset/green-carrots-scream.md
- .vscode/settings.json
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
We've had support for "json" bindings for a long time, but never added them to wrangler1.. oops! This is nice because you can include complex values, and you don't need to use things like `parseInteger(env.variable)` in your code.
```toml
[vars]
text = "plain ol' string"
count = 1
complex = { enabled = true, id = 123 }
```
/cc @mrbbot Since you probably didn't know this existed! 😅
> feat: Add support for "json" bindings

- .changeset/ten-moons-develop.md
- packages/example-wasm-app/README.md
- packages/example-wasm-app/worker/service-worker-module/export_wasm.js
- packages/example-wasm-app/worker/service-worker-module/index.js
- packages/example-wasm-app/worker/service-worker-module/index_bg.js
- packages/wrangler/src/__tests__/guess-worker-format.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/guess-worker-format.ts
- packages/wrangler/src/module-collection.ts
- packages/wrangler/src/publish.ts
This allows importing `.wasm` modules in service worker format workers. We do this by hijacking imports to `.wasm` modules, and instead registering them under `[wasm_modules]` (building on the work from https://github.com/cloudflare/wrangler2/pull/409).
> feat: import `.wasm` modules in service worker format workers

- .vscode/settings.json
- packages/wrangler/src/__tests__/helpers/mock-console.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/user.tsx
Previously the snapshots were capturing blank lines that only contained whitespace,
which was conflicting with VS Code settings that wanted to remove trailing whitespace.
Now we strip this whitespace before checking snapshots so it does not appear in our
test files, and we can safely turn on `trimTrailingWhitespace` in the VS Code settings.
See https://github.com/cloudflare/wrangler2/pull/411/files#r802597313
> chore: remove trailing whitespace from snapshot tests

- .changeset/olive-maps-promise.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
Add `--yes` with alias `--y` flag as automatic answer to all prompts and run `wrangler init` non-interactively.
generated during setup:
- package.json
- TypeScript, which includes tsconfig.json & @cloudflare/workers-types
- Template "hello world" Worker at src/index.ts
resolves #446
> add `--yes` flag to `wrangler init`

- .changeset/long-penguins-guess.md
- package-lock.json
- packages/wrangler/src/api/form_data.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
Now that we have `[[unsafe.bindings]]` (as of https://github.com/cloudflare/wrangler2/pull/411), we should use that for experimental features. This removes support for `[experimental_services]`, and adds a helpful message for how to rewrite their configuration.
This error is temporary, until the internal teams that were using this rewrite their configs. We'll remove it before GA.
What the error looks like -
```
Error: The "experimental_services" field is no longer supported. Instead, use [[unsafe.bindings]] to enable experimental features. Add this to your wrangler.toml:
[[unsafe.bindings]]
name = "SomeService"
type = "service"
service = "some-service"
environment = "staging"
[[unsafe.bindings]]
name = "SomeOtherService"
type = "service"
service = "some-other-service"
environment = "qa" …
```
> chore: remove `experimental_services` from configuration

- .changeset/small-rules-invite.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/publish.ts
This changes moves the code that does the esbuild bundling into a shared file
and updates the `publish` and `dev` to use it, rather than duplicating the
behaviour.
See #396
Resolves #401
> refactor: share worker bundling between both `publish` and `dev` commands

- package.json
We were accidentally not running any typechecking in CI, this fixes that by calling the right command for all workspaces.
> chore: run typechecks in CI

- .changeset/calm-numbers-shout.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.tsx
During `dev` and `publish`, we should resolve `wrangler.toml` starting from the entrypoint, and then working up from there. Currently, we start from the directory from which we call `wrangler`, this changes that behaviour to start from the entrypoint instead.
(To implement this, I made one big change: Inside commands, we now have to explicitly read configuration from a path, instead of expecting it to 'arrive' coerced into a configuration object.)
Fixes #440.
> fix: Config should be resolved relative to the entrypoint

- .changeset/rich-fans-shake.md
- .changeset/sour-eagles-confess.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
Previously we always published to the workers.dev subdomain, ignoring the `workers_dev` setting in the `wrangler.toml` configuration.
Now we respect this configuration setting, and also disable an current workers.dev subdomain worker when we publish and `workers_dev` is `false`.
Fixes https://github.com/cloudflare/wrangler2/issues/410
> fix: do not publish to workers.dev if workers_dev is false

- .changeset/silent-bananas-compete.md
- packages/wrangler/src/index.tsx
- packages/wrangler/src/reporting.ts
We shouldn't be reporting intentional errors, only exceptions. This removes reporting for all caought errors for now, until we filter all known errors, and then bring back reporting for unknown errors. We also remove a stray `console.warn()`.
> fix: don't report intentional errors

- packages/wrangler/src/__tests__/publish.test.ts
This mocks `setTimeout` for `publish.test.ts` so we don't pay the price of the 3 second artificial delay in tests. Further, we actually restore it for custom builds so they don't timeout automatically.
> chore: mock timers in `publish.test.ts`

- packages/wrangler/src/index.tsx
- packages/wrangler/src/tail.tsx
Fixed some lint warnings introduced in https://github.com/cloudflare/wrangler2/pull/462
Some followups we should do -
- CI should fail on lint warnings
- we should swap the import-order plugin for a prettier based one, so it happens on save instead of having to manually do so
> chore: fix lint warnings

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/release.yml
- package.json
- packages/wrangler/package.json
Some modifications to our builds/workflows -
- The scripts `prebuild-and-test` and `build-and-test` weren't named well, so I removed them and inlined their usage.
- Added a `prepublish` script to `packages/wrangler`, so that a build is always run before we publish
- Removed `npm run build` from some workflows before publishes, since we have `prepublish` to  run that build
- Modified the prerelease message to include an `npx` invocation
> chore: tweak build scripts

- packages/wrangler/package.json
Apparently prepublish does _not_ run on publish, and we should use prepublishOnly. This is documented, so fooey on me for assuming something does what it says 😡
> fix: s/prepublish/prepublishOnly

- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/guess-worker-format.ts
- packages/wrangler/src/wasi.ts
Allow wrangler to work with simple with WebAssembly programs that
operate on stdin/stdout by generating a js shim that uses
'@cloudflare/wasi'
Example:
cargo new hello_wasm
cd ./hello_wasm
cargo build --target wasm32-wasi --release
wrangler dev target/wasm32-wasi/release/hello_wasm.wasm
curl http://localhost:8787
Hello, world!
> Add experimental support for wrangler dev/publish file.wasm

- package-lock.json
- packages/workers-chat-demo/LICENSE
- packages/workers-chat-demo/README.md
- packages/workers-chat-demo/package.json
- packages/workers-chat-demo/src/chat.html
- packages/workers-chat-demo/src/chat.mjs
- packages/workers-chat-demo/wrangler.toml
This adds the `workers-chat-demo` from https://github.com/cloudflare/workers-chat-demo as an example app into our monorepo. It has some modifications, documted at the top of its `README.md`.
Of note, you'll note that this _doesn't_ work with wrangler. Landing this so we can debug and have a shared reference that we need to get to work.
> chore: add workers-chat-demo

- .changeset/few-cherries-compare.md
- packages/wrangler/src/proxy.ts
Replace `.destroy()` on `faye-websockets` with `.close()`
Added interface to give faye same types as compliant ws with additional `pipe()` implementation
resolves #463
> Fix: TypeError localWebsocket.destroy is not a function

- packages/workers-chat-demo/README.md
- packages/workers-chat-demo/src/chat.html
This required a couple more changes in `chat.html`.
Closes https://github.com/cloudflare/wrangler2/issues/477
(A proper fix would be to automatically choose the right protocol, and we should also probably default `wrangler dev` to https.)
> fix: make `workers-chat-demo` work

- .changeset/funny-cycles-smile.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/templates/new-worker.js
- packages/wrangler/templates/new-worker.ts
We should be consistent with the word that describes how we get a worker to the edge. The command is `publish`, so let's use that everywhere.
> fix: replace the word "deploy" with "publish" everywhere.

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/write-prerelease-comment.yml
We store the wrangler build artifacts and then comment on the PR to tell users how to access them.
But the way that GH actions work, it is not possible to write a comment if the PR is from another fork.
This change uses a `workflow_run` GH action, which does have permission, to do the commenting.
We must pass the PR number to it via another artifact.
> ci: enable artifact comments in PR from forks

- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/index.ts
This adds a slightly better type for the `RequestEvent` used in `wrangler tail`. It's a "standard" type that `undici` uses, that's closer to the standard type we have in the Workers runtime.
I also deleted an unused function, I assume we'll bring that back when we write a test for tailing scheduled events.
Skipping a changeset here since there's no functional change.
> chore: better RequestEvent type for tail

- .changeset/orange-vans-lay.md
cc @jahands - FYI the front-matter of a changeset specifies the packages that were changed and the type of version bump required. In this case `patch`.
> chore: fix the syntax in the most recent changeset

- package-lock.json
- package.json
- packages/wrangler/src/dev.tsx
This should save maintainers time when reviewing PRs by throwing an error when there are unused imports.
- Adds a new dependency, [eslint-plugin-unused-imports](https://www.npmjs.com/package/eslint-plugin-unused-imports)
- Upgrades eslint from `7.32.0` to `8.9.0`, required by the above plugin.
This upgrade to eslint includes breaking changes and adds new rules to `eslint:recommended`. After reviewing the [ESLint Migration Guide](https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0), I don't believe this change affects any of our rules (except for adding new recommended rules.)
Note: It didn't look like I'm supposed to add a changeset if I'm not modifying any packages, please correct me if I'm wrong.
> Upgrade eslint to 8.9.0 and add unused-imports rule

- .changeset/selfish-dogs-do.md
- packages/wrangler/src/pages.tsx
It is common to pass additional commands to `pages dev` to generate the input source.
For example:
```bash
npx wrangler@beta pages dev -- npm run dev
```
Previously the args after `--` were being dropped.
This change ensures that these are captured and used correctly.
Fixes #482
> fix(pages): ensure remaining args passed to `pages dev` command are captured

- .changeset/selfish-days-reply.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/helpers/faye-websocket.d.ts
- packages/wrangler/src/__tests__/helpers/mock-web-socket.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/proxy.ts
- refact: consolidate on ws websocket library
- test: simplify the mock websocket helper
- refact: shorten the polling period waiting for the tail to connect
> Some minor websocket updates

- .changeset/proud-jars-protect.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
The `preview` command is deprecated and not supported in this version of Wrangler.
Instead, one should use the `dev` command for most `preview` use-cases.
This change attempts to delegate any use of `preview` to `dev` failing if the command line contains positional arguments that are not compatible with `dev`.
Resolves #9
> Deprecate `preview` command

- .github/workflows/prereleases.yml
DEPENDANT ON https://github.com/cloudflare/wrangler2/pull/437#discussion_r811047171
On merging to `main`, this will automatically deploy the prerelease registry.
In the future, we could get smart and only do it if we detect changes to the directory.
I tried pulling `wrangler@alpha` directly from npm in a number of different ways, but unfortunately, I can't escape the npm workspace which seems to always prefer the local `wrangler` project.
These didn't work:
```sh
npx  wrangler
npx  wrangler@alpha
npx  npm:wrangler@alpha
npx $(npm view wrangler@alpha dist.tarball)
```
We could try something like `cd /some-other-dir; npx wrangler@alpha pages functions build /home/runner/work/packages/prerelease-registry/..`, but that seemed more convoluted than it was worth; rather just rebuild wrangler …
> Automatically deploy prerelease registry

- packages/prerelease-registry/functions/utils/getArtifactForWorkflowRun.ts
Previously, they would only have been cached for [two hours](https://developers.cloudflare.com/cache/how-to/configure-cache-status-code#edge-ttl).
We're using [`s-maxage`](https://developers.cloudflare.com/cache/about/cache-control#cache-control-directives) because we want to cache the artifact in Cloudflare's cache relative to the workflow number for a decent amount of time, but don't want to cache client-side for any duration because we might be getting it by PR number. Not that `npm` will respect the cache headers anyway...
> Cache prerelease artifacts for one week

- .changeset/short-dancers-mix.md
- packages/prerelease-registry/functions/routes/prs/[[path]].ts
- packages/prerelease-registry/functions/routes/runs/[[path]].ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/sites.tsx
This is the first of a few changes to codify how we do environments in wrangler2, both older legacy style environments, and newer service environments. Here, we add a cli arg and a config field for specifying whether to enable/disable legacy style environments, and pass it on to dev/publish commands. We also fix how we were generating kv namespaces for Workers Sites, among other smaller fixes.
> feat: `--legacy-env` cli arg / `legacy_env` config

- .changeset/brown-spies-deliver.md
- packages/wrangler/src/__tests__/helpers/write-wrangler-toml.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This adds some tests for publishing routes, and fixes a couple of bugs with the flow.
- fixes publishing environment specific routes, closes https://github.com/cloudflare/wrangler2/issues/513
- default `workers_dev` to `false` if there are any routes specified
- catches a hanging promise when we were toggling off a `workers.dev` subdomain (which should have been caught by the `no-floating-promises` lint rule, so that's concerning)
- this also fixes publishing environment specific crons, but I'll write tests for that when I'm doing that feature in depth
I expect to send some followup PRs for routes, but this should make it a little more stable right now
> fix: publish environment specific routes

- .changeset/empty-trains-mix.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/helpers/faye-websocket.d.ts
- packages/wrangler/src/proxy.ts
This fixes websockets in `wrangler dev`. It looks like we broke it in https://github.com/cloudflare/wrangler2/pull/503. I've reverted the specific changes made to `proxy.ts`.
Test plan -
```
cd packages/wrangler
npm run build
cd ../workers-chat-demo
npx wrangler dev
```
> fix: websockets in `wrangler dev`

- .changeset/angry-badgers-beam.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This implements environment support for `wrangler secret` (both legacy and services). We now consistently generate the right script name across commands with the `getScriptName()` helper.
> feat: secrets + environments

- .changeset/dull-llamas-drive.md
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/tail/index.ts
This implements service environment support for `wrangler tail`. Fairly simple, we just generate the right URLs. wrangler tail already works for legacy envs, so there's nothing to do there.
> feat: tail+envs

- .changeset/chatty-berries-divide.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This implements a top level `main` field for `wrangler.toml` to define an entry point for the worker , and adds a deprecation warning for `build.upload.main`. The deprecation warning is detailed enough to give the exact line to copy-paste into your config file. Example -
```
The `build.upload` field is deprecated. Delete the `build.upload` field, and add this to your configuration file:
main = "src/chat.mjs"
```
This also makes `./dist` a default for `build.upload.dir`, to match wrangler 1's behaviour.
Closes https://github.com/cloudflare/wrangler2/issues/488
> feat: top level `main` config field

- .changeset/poor-beers-deny.md
- packages/wrangler/src/__tests__/parse.test.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/parse.ts
This is the beginning of more standard error messages in wrangler. For now, it outputs these errors for TOML and JSON parsing errors.
> refactor: use esbuild's message formatting for cleaner error messages

- .changeset/kind-hairs-sneeze.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/index.tsx
While implementing support for service environments, we unearthed a small number of usage issues. While we work those out, we should default to using regular "legacy" environments.
> feat: default to legacy environments

- .changeset/kind-masks-jump.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
Currently, attempting to use `wrangler dev` multiple times won't allow you to use devtools on each worker, because they all want the same "9229" port.
This PR fixes that issue by
1. Allowing the user to pass in a custom port if they'd like to use it
2. Randomly choosing a port, starting by trying 9229, if you don't specify
I haven't tested it out myself yet, but it seems like the test suite is passing so I figured I'd go ahead and push so I can get some early feedback.
closes #21
> Allow alternative ports for devtools connection in `wrangler dev`

- .changeset/healthy-bugs-reply.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/api/preview.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
This implements service environments + `wrangler dev`. Fairly simple, it just needed the right url when creating the edge preview token.
I tested this by publishing a service under one env, adding secrets under it in the dashboard, and then trying to dev under another env, and verifying that the secrets didn't leak.
(This uncovered an issue where we can't set the right host incl. the env prefix, but it's not critical right now, following up internally.)
> feat: dev+envs

- .changeset/soft-eagles-taste.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/package-manager.ts
- packages/wrangler/src/parse.ts
(I got bored on my flight so... I made a PR as a place for discussion of this, and also to generate the prerelease builds so we could actually try it out.)
Currently, when creating a new project, we usually first have to create a directory before running `wrangler init`, since it defaults to creating the `wrangler.toml`, `package.json`, etc in the current working directory. This fix introduces an enhancement, where using the `wrangler init [name]` form creates a directory named `[name]` and initialises the project files inside it. This matches the usage pattern a little better, and still preserves the older behaviour when we're creating a worker inside existing projects.
> rfc: with `wrangler init`, create a new directory for named workers

- .changeset/gentle-islands-complain.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/index.tsx
We'd originally planned for `--local` mode to be a thing across all wrangler commands. In hindsight, that didn't make much sense, since every command other than `wrangler dev` assumes some interaction with cloudflare and their API. The only command other than dev where this "worked" was `kv`, but even that didn't make sense because wrangler dev wouldn't even read from it. We also have `--experimental-enable-local-persistence` there anyway.
So this moves the `--local` flag to only apply for `wrangler dev` and removes any trace from other commands.
> feat: `--local` mode only applies in `wrangler dev`

- .changeset/silver-doors-cough.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.tsx
- packages/wrangler/src/sites.tsx
The body passed to `kv:bulk delete` and `kv:bulk put` must be JSON encoded.
This change fixes that and adds some tests to prove it.
Fixes #547
> fix: kv:bulk should JSON encode its contents

- .changeset/large-vans-mix.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/api/preview.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
This implements support for zoned workers in `wrangler dev`. Of note, since we're deprecating `zone_id`, we instead use the domain provided via `--host`/`config.dev.host`/`--routes`/`--route`/`config.routes`/`config.route` and infer the zone id from it.
Fixes https://github.com/cloudflare/wrangler2/issues/544
> feat: zoned worker support for `wrangler dev`

- .changeset/eleven-bananas-bow.md
- packages/wrangler/src/dev.tsx
Disables sharing local development server on the internet. We will bring this back after it's more polished/ready.
Fixes https://github.com/cloudflare/wrangler2/issues/550
> feat: disable tunnel in `wrangler dev`

- .changeset/heavy-hounds-talk.md
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
Added the following:
- When the deletion completes, we get `Success!` logged to the console.
- Before deleting, the user is now asked to confirm is that is desired.
- A new flag `--force` to avoid the confirmation check.
> feat: add confirmation and success messages to `kv:bulk delete` command

- .changeset/rare-starfishes-deliver.md
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/user.tsx
There was a common chunk of code across most commands that ensures a user is logged in, and retrieves an account ID. I'd resisted making this into an abstraction for a while. Now that the codebase is stable, and https://github.com/cloudflare/wrangler2/pull/537 removes some surrounding code there, I made an abstraction for this common code as `requireAuth()`. This gets a mention in the changelog simply because it touches a bunch of code, although it's mostly mechanical deletion/replacement.
> chore: refactor some common code into `requireAuth()`

- .changeset/angry-countries-matter.md
- .changeset/smooth-tables-admire.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.tsx
- packages/wrangler/src/sites.tsx
The `kv:bulk delete` and `kv:bulk put` commands now batch up requests in groups of 5,000,
displaying progress for each request.
> fix: limit bulk API requests to batches of 5,000

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/release.yml
- .vscode/settings.json
- package-lock.json
- package.json
- packages/wrangler/package.json
- tsconfig.json
Some cleanups on our infra packages
- updated typescript ([some great new features](https://devblogs.microsoft.com/typescript/announcing-typescript-4-6/)), typescript-eslint-*
- updated jest, types/jest
- deleted `@types/estree`/`@babel/types` since we don't use them anymore
- setup `tsconfig.json` to explicitly include the `@types/jest` package (so we don't check every `@types/*` package by default
- setup githubs actions to fail on lint warnings
> chore: update some codebase infrastructure

- .changeset/great-cats-lie.md
- packages/wrangler/src/api/preview.ts
- packages/wrangler/src/api/worker.ts
- packages/wrangler/src/dev.tsx
With unnamed workers, we use the filename as the name of the worker, which isn't a valid name for workers because of the `.` (This break was introduced in https://github.com/cloudflare/wrangler2/pull/545). The preview service accepts unnamed workers and generates a hash anyway, so the fix is to simply not send it, and use the host that the service provides.
(Yes, I broke the build 😔)
> fix: wrangler dev on unnamed workers in remote mode

- .changeset/famous-pets-complain.md
- packages/wrangler/src/__tests__/helpers/mock-account-id.ts
- packages/wrangler/src/__tests__/helpers/mock-stdin.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/user.tsx
Now the user can pipe in the secret value to the `wrangler secret put` command.
For example:
```
cat my-secret.txt | wrangler secret put secret-key --name worker-name
```
This requires that the user is logged in, and has only one account, or that the `account_id` has been set in `wrangler.toml`.
Fixes #170
> feat: support adding secrets in non-interactive mode

- .changeset/nice-jars-teach.md
- packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
Show an actionable error message when publishing to a workers.dev subdomain that hasn't been created yet.
When publishing a worker to workers.dev, you need to first have registered your workers.dev subdomain
(e.g. my-subdomain.workers.dev). We now check to ensure that the user has created their subdomain before
uploading a worker to workers.dev, and if they haven't, we provide a link to where they can go through
the workers onboarding flow and create one.
Closes #318
> Add a nicer error when there's no workers.dev subdomain

- .changeset/giant-sloths-fail.md
- packages/wrangler/src/user.tsx
Not ready quite yet (still waiting for some internal stuff first).
This adds the `pages:write` scope to the requests that wrangler makes when a user `npx wrangler login`. We should get this merged in as soon as we can, so that anyone who logs in gets these scopes, ready for when we can start doing Pages things inside of wrangler.
For those who are already logged in and don't have the `pages:write` scope, they'll currently see a generic:
```json
{"success":false,"errors":[{"code":10000,"message":"Authentication error"}]}
```
We could improve special-case handle this in the Pages commands we introduce and suggest re-consenting.
> Request Pages API scopes when logging in

- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/guess-worker-format.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/module-collection.ts
- packages/wrangler/src/proxy.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/src/worker.ts
This is a small reorganisation, it renames and moves some files under `src/preview` to `src`. There are no functional changes.
--- 
I didn't add a changeset because it seemed like overkill, but happy to do so if y'all think differently.
> chore: rename files under wrangler/src/api

- .changeset/stale-coats-joke.md
- packages/wrangler/src/reporting.ts
In some scenarios (CI/CD, docker, etc), we won't have write access to `~/.wrangler`. We already don't write a configuration file there if one passes a `CF_API_TOKEN`/`CLOUDFLARE_API_TOKEN` env var. This also adds a guard when writing the error reporting configuration file.
> fix: gracefully fail if we can't create `~/.wrangler/reporting.toml`

- .changeset/small-jokes-lay.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This makes configuring `site.entry-point` in config as a breaking deprecation, and throws an error. We do this because existing apps with `site.entry-point` _won't_ work in v2.
--- 
I would recommend turning off whitespace when reviewing this PR.
> fix: `config.site.entry-point` as a breaking deprecation

- .changeset/itchy-bobcats-hug.md
- packages/wrangler/src/reporting.ts
Sentry's SDK automatically tracks "breadcrumbs", which are pieces of information
that get tracked leading up to an exception. This can be useful for debugging
errors because it gives better insight into what happens before an error occurs,
so you can more easily understand and recreate exactly what happened before an
error occurred.
Unfortunately, Sentry automatically includes all `console` statements. And since
we use the console a lot (e.g. logging every request received in `wrangler dev`),
this is mostly useless. Additionally, since developers frequently use the console
to debug their workers we end up with a bunch of data that is not only irrelevant
to the reported error, but also contains data that could be potentially sensitive.
For now, we're turning off breadcrumbs entirely. …
> Stop reporting breadcrumbs to sentry

- .changeset/fluffy-cameras-greet.md
- packages/wrangler/src/__tests__/route.test.ts
- packages/wrangler/src/index.tsx
Users should instead modify their wrangler.toml or use the `--routes` flag when publishing
to manage routes.
closes #542
> deprecate wrangler route

- packages/wrangler/src/__tests__/route.test.ts
This mocks the console methods in `route.test.ts` so the terminal isn't as noisy.
> chore: silence logs in `route.test.ts`

- .changeset/dull-fishes-lay.md
- packages/workers-chat-demo/src/chat.mjs
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/module-collection.ts
This implements wrangler 1.x style module specifiers, but also logs a deprecation warning for every usage.
Consider a project like so:
```
project
├── index.js
└── some-dependency.js
```
where the content of `index.js` is:
```jsx
import SomeDependency from "some-dependency.js";
addEventListener("fetch", (event) => {
// ...
});
```
`wrangler` 1.x would resolve `import SomeDependency from "some-dependency.js";` to the file `some-dependency.js`. This will work in `wrangler` v2, but it will log a deprecation warning. Instead, you should rewrite the import to specify that it's a relative path, like so:
```diff
- import SomeDependency from "some-dependency.js";
+ import SomeDependency from "./some-dependency.js";
```
In a near future version, this will become a breaking deprecation and throw an …
> feat: support wrangler 1.x module specifiers with a deprecation warning

- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
Previously using deprecated `generate` and `build` caused a message with "TODO://some/path" in the warning message.
Now links to deprecation documentation. 
resolves #345
> Add links to documentation for deprecated commands

- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/dev2.test.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/module-collection.ts
This adds a basic test harness for the `<Dev/>` component. We'll add more tests and flesh out the harness a little more later, but figured we could land this and iterate on it.
> chore: add a test harness for `<Dev/>`

- packages/wrangler/src/pages.tsx
For example
```shell
npx wrangler pages dev public/ -b "AAA=foo=bar; foo2=bar2" # actually i want to pass a cookie
```
It will be parsed to
```javascript
{
AAA: 'foo' // all remaining arguments are lost!
}
```
But it should be parsed to
```javascript
{
AAA: 'foo=bar; foo2=bar2' 
}
```
> Fix incorrect parse for env binding

- .changeset/pink-apricots-fix.md
- packages/example-pages-functions-app/functions/blog/[slug].ts
- packages/example-pages-functions-app/functions/date.ts
- packages/example-pages-functions-app/functions/intercept.ts
- packages/example-pages-functions-app/package.json
- packages/example-pages-functions-app/public/index.html
- packages/example-pages-functions-app/tests/index.test.ts
- packages/example-pages-functions-app/tsconfig.json
A simple Functions test project which confirms that:
- we serve static files
- we can intercept static files
- we can SSR responses
- we can use parameters
> Add Pages Functions example test project

- .changeset/silver-poems-brush.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
I found that the env specific overwrite did not work for `workers_dev`.
Also fixed some others.
> Use inherited config in `publish`

- package-lock.json
- packages/example-pages-functions-app/package.json
Looks like we forgot to run `npm install` at the root in https://github.com/cloudflare/wrangler2/pull/617. Also removed an unnecessary `typescript` dependency.
> chore: update `package-lock.json`

- .changeset/thick-keys-worry.md
- packages/wrangler/src/__tests__/helpers/mock-kv.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/kv.ts
- packages/wrangler/src/sites.tsx
This expires any previously uploaded assets when using a Sites / `[site]` configuration. Because we currently do a full iteration of a namespace's keys when publishing, for rapidly changing sites this means that uploads get slower and slower. We can't just delete unused assets because it leads to occasional 404s on older publishes while we're publishing. So we expire previous assets while uploading new ones. The implementation/constraints of the kv api means that uploads may become slower, but should hopefully be faster overall. These optimisations also only matter for rapidly changing sites, so common usecases still have the same perf characteristics.
--- 
I've started this PR as a discussion point, to discuss tradeoffs of the approach, and to make the constraints apparent before we move …
> feat: expire unused assets in `[site]` uploads

- .changeset/clever-beers-poke.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
> check if both `route` and `routes` are specified in wrangler.toml

- .changeset/gold-readers-grin.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/index.tsx
This adds a small banner for most commands. Specifically, we avoid any commands that maybe used as a parse input (like json into jq). The banner itself simply says "⛅️ wrangler" with an orange underline.
--- 
Some screenshots of what it looks like:
> polish: add a small banner for commands

- .changeset/large-pillows-clap.md
- packages/wrangler/src/__tests__/logout.test.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/user.tsx
- If a user has previously logged in via Wrangler 1 with an API token, we now display a helpful warning.
- When logging in and out, we no longer display the path to the internal user auh config file.
- When logging in, we now display an initial message to indicate the authentication flow is starting.
Fixes [#526](https://github.com/cloudflare/wrangler2/issues/526)
> fix: improve authentication logging and warnings

- .changeset/blue-nails-unite.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
This switches how we expire static assets with `[site]` uploads to use `expiration_ttl` instead of `expiration`. This is because we can't trust the time that a deploy target may provide (like in https://github.com/cloudflare/wrangler/issues/2224).
> fix: use `expiration_ttl` to expire assets with `[site]`

- .changeset/perfect-cars-leave.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/validation.ts
Via wrangler 1, when using custom builds in `wrangler dev`, `watch_dir` should default to `src` of the "project directory" (i.e - wherever the `wrangler.toml` is defined if it exists, else in the cwd.
Fixes https://github.com/cloudflare/wrangler2/issues/631
> fix: default `watch_dir` to `src` of project directory

- .changeset/shaggy-pumas-search.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/dev2.test.tsx
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/proxy.ts
Resolves [#584](https://github.com/cloudflare/wrangler2/issues/584)
> feat: add support for `--ip` and `config.dev.ip` in the dev command

- docs/compare-v1-v2.md
- package.json
This should prevent failed builds when we do releases (like what happened with .20 and .21)
> chore: run prettier on `.changeset`/`docs` folder

- .changeset/thick-bees-yell.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/module-collection.ts
When implementing legacy module specifiers, we didn't throughly test the interaction when there weren't any other files next to the entry worker, and importing npm modules. It would create a Regex that matched _every_ import, and fail because a file of that name wasn't present in the source directory. This fix constructs a better regex, applies it only when there are more files next to the worker, and increases test coverage for that scenario.
Fixes https://github.com/cloudflare/wrangler2/issues/655
--- 
(ignore whitespace when reviewing this)
> fix: resolve npm modules correctly

- .changeset/strange-tools-heal.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
When migrating a legacy Worker that was using many scripts for managing various environments, Wrangler 2 was missing aliases which were utilized in the Wrangler 1 scripts; this will allow for parity for environment flags.  
resolves #660
> bugfix: add `-e` alias to all `--env` flag options

- .changeset/tender-planes-tie.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/entry.ts
I think...this...is good..?
Continuation of https://github.com/cloudflare/wrangler2/pull/634
Closes https://github.com/cloudflare/wrangler2/issues/635
> Error if the user is trying to implement DO's in a service worker

- .prettierignore
changesets currently relies on on older version of prettier when generating changelogs, which then makes our `prettier --check` run fail during releases, which breaks our releases (.20. .21, .22). ref: https://github.com/changesets/changesets/issues/616. The fix for now is to simply ignore the changelog when generating the check.
> chore: prevent `prettier --check` on CHANGELOG

- .changeset/hot-kiwis-lie.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/README.md
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/entry.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
- packages/wrangler/src/publish.ts
Now, when we normalize and validate the raw config, we pass in the currently
active environment name, and the config that is returned contains all the
environment fields correctly normalized (including inheritance) at the top
level of the config object. This avoids other commands from having to check
both the current named environment and the top-level config for such fields.
Also, now, handle the case where the active environment name passed in via the
`--env` command line argument does not match any of the named environments
in the configuration:
- This is an error if there are named environments configured;
- or only a warning if there are no named environments configured.
> fix: tighten up the named environment configuration

- .changeset/hungry-chairs-return.md
- .changeset/long-cameras-nail.md
- .gitignore
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/miniflare-cli/README.md
- packages/wrangler/src/miniflare-cli/enum-keys.ts
- packages/wrangler/src/miniflare-cli/index.ts
- packages/wrangler/src/sites.tsx
Previously, Miniflare CLI was being ran for local through a child process which made passing options into it complicated for more complex inputs. 
Solution: **Create a custom CLI wrapper around Miniflare API**
This allows us to tightly control the options that are passed to Miniflare.
- Miniflare API config is more ergonomic and allows for far more complex inputs to be easily passed in.
- Instantiation, server startup, and cleanup with the API is far more explicit and manageable.
Bugfix: Likely pathing to the current working directory only worked if ran in the directory with a Worker, the base directory is now an absolute path to the directory with a `wrangler.toml`
The current CLI is setup to be more compatible with how Wrangler 1 works, which is not optimal for Wrangler 2.
> Custom Miniflare CLI

- .changeset/ten-llamas-boil.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
We discovered critical issues with the way we expire unused assets with `[site]` (https://github.com/cloudflare/wrangler2/issues/666, https://github.com/cloudflare/wrangler/issues/2224), that we're going back to the legacy manner of handling unused assets, i.e- deleting unused assets.
Fixes https://github.com/cloudflare/wrangler2/issues/666
> fix: delete unused `[site]` assets

- packages/example-pages-functions-app/tests/index.test.ts
- packages/example-remix-pages-app/tests/index.test.ts
> Kill hanging process after integration tests complete

- .changeset/mean-goats-hang.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
Now the `build` field can be specified within a named environment, overriding whatever
may appear at the top level.
Resolves https://github.com/cloudflare/wrangler2/issues/588
> fix: allow the `build` field to be inherited/overridden in a named environment

- .changeset/tame-timers-brake.md
- packages/wrangler/src/pages.tsx
Fixes #543
Previously, we'd exit the `wrangler pages dev` process if we couldn't immediately compile a Worker from the `functions` directory. We now log the error, but don't exit the process. This means that proxy processes can be cleaned up cleanly on SIGINT and SIGTERM, and it matches the behavior of if a compilation error is introduced once already running (we don't exit then either).
> Don't immediately exit on Pages Functions compilation error

- .changeset/gold-forks-retire.md
- .prettierignore
- packages/wrangler/src/dev/local.tsx
In https://github.com/cloudflare/wrangler2/pull/633, we missed passing a cwd to the process that runs the miniflare cli. This broke how miniflare resolves modules, and led back to the dreaded "path should be a `path.relative()`d string" error. The fix is to simply pass the cwd to the `spawn` call.
Test plan
```
cd packages/wrangler 
npm run build
cd ../workers-chat-demo 
npx wrangler dev --local
```
> fix: resolve non-js modules correctly in local mode

- .changeset/young-boats-dance.md
- packages/example-pages-functions-app/package.json
- packages/example-pages-functions-app/tests/index.test.ts
- packages/example-pages-functions-app/tsconfig.json
- packages/example-remix-pages-app/package.json
- packages/example-remix-pages-app/tests/index.test.ts
- packages/wrangler/bin/wrangler.js
- packages/wrangler/src/pages.tsx
We weren't killing the process started by wrangler whenever its parent was killed. This fix is to listen on SIGINT/SIGTERM and kill that process. I also did some minor configuration cleanups.
Fixes https://github.com/cloudflare/wrangler2/issues/397
Fixes https://github.com/cloudflare/wrangler2/issues/618
--- 
(fyi this does NOT cleanup the occasional flake with the remix test where the text doesn't render)
> fix: cleanup after `pages dev` tests

- .changeset/swift-apes-battle.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
1. When in Legacy environment mode we should not compute name field if specified in an environment.
2. Throw an Error when `--env` and `--name` are used together in Legacy Environment, except for Secrets & Tail which are using a special case `getLegacyScriptName` for parity with Wrangler1
3. Started the refactor for args being utilized at the Config level, currently checking for Legacy Environment only.
Fixes https://github.com/cloudflare/wrangler2/issues/672
> Support backwards compatibility with environment names and related CLI flags

- .changeset/strange-dingos-listen.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/intl-polyfill.d.ts
> validate binding names don't conflict

- .changeset/two-lions-teach.md
- packages/example-pages-functions-app/functions/variables.ts
- packages/example-pages-functions-app/package.json
- packages/example-pages-functions-app/tests/index.test.ts
- packages/wrangler/src/pages.tsx
Fixes #674.
Fixes #648.
We'd broken this with #581. This reverts that PR, and fixes it slightly differently. Also added an integration test to ensure we don't regress in the future.
> Fix --binding for wrangler pages dev

- .changeset/four-bags-admire.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/entry.ts
Durable Objects that are being bound by `script_name` will not be isolated from the
live data during development with `wrangler dev`.
This change simply warns the developer about this, so that they can back out before
accidentally changing live data.
Fixes #319
> fix: add warning about `wrangler dev` with remote Durable Objects

- .changeset/happy-trainers-teach.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/pages.tsx
Adding "Beta" messaging around the CLI command for Pages.
Explicitly specifying the command is Beta, not to be confused with Pages itself which is production ready, the messaging could need additional tweaking to prevent any confusion between `Pages` and `npx wrangler pages <command>`
@nevikashah
resolves #642
> Add messaging for CLI pages command being in Beta

- .changeset/fluffy-ghosts-jam.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/publish.ts
When `workers_dev` is not configured, we had a bug where it would default to true inside an environment even when there were routes defined, thus publishing both to a `workers.dev` subdomain as well as the defined routes. The fix is to default `workers_dev` to `undefined`, and check when publishing whether or not to publish to `workers.dev`/defined routes.
Fixes https://github.com/cloudflare/wrangler2/issues/690
> fix: do not deploy to workers.dev when routes are defined in an environment

- .changeset/breezy-ladybugs-shout.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/index.tsx
This enables strict mode in our command line parser (yargs), so that unexpected commands and options uniformly throw errors.
Fixes https://github.com/cloudflare/wrangler2/issues/706
> fix: unexpected commands and arguments should throw

- .changeset/neat-points-punch.md
- packages/wrangler/src/__tests__/guess-worker-format.test.ts
- packages/wrangler/src/entry.ts
- We consider jsx to be regular js, and have setup our esbuild process to process js/mjs/cjs files as jsx.
- We use a separate esbuild run on an entry point file when trying to guess the worker format, but hadn't setup the loaders there.
- So if just the entrypoint file has any jsx in it, then we error because it can't parse the code.
The fix is to add the same loaders to the esbuild run that guesses the worker format.
Reported in https://github.com/cloudflare/wrangler2/issues/701
> fix: setup jsx loaders when guessing worker format

- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
As we refactor and improve on the configuration/validation framework, it will be more necessary to have access to Args for all possible user inputs with flags that override TOML configs.
Args itself needs work on how we will define it, rather than unknown from inputs to casting at the point of usage.
> Pass in args to normalize and validate function

- .changeset/late-mayflies-joke.md
- packages/wrangler/src/user.tsx
If the auth refresh token isn't valid, then we should trigger the login flow. Reported in https://github.com/cloudflare/wrangler2/issues/316
--- 
We don't have any test coverage on this complicated login machinery 😓 We should fix that soon. I wish there was a good npm package for this, but there just isn't (that I could find).
> fix: trigger login flow if refreshtoken isn't valid

- .changeset/calm-laws-explain.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/index.tsx
We shouldn't try to resolve a domain/route to a zone id when starting in local mode (since there may not even be network connectivity).
> fix: don't fetch zone id for `wrangler dev --local`

- .changeset/beige-olives-doubt.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
When a developer uses `--env` to specify an environment name, the Worker name should
be computed from the top-level Worker name and the environment name.
When the given environment name does not match those in the wrangler.toml, we error.
But if no environments have been specified in the wrangler.toml, at all, then we only
log a warning and continue.
In this second case, we were reusing the top-level environment, which did not have the
correct legacy environment fields set, such as the name. Now we ensure that such an
environment is created as needed.
See https://github.com/cloudflare/wrangler2/pull/680#issuecomment-1080407556
> fix: ensure the correct worker name is published in legacy environments

- .changeset/spotty-needles-brake.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/entry.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This adds a config field and a command line arg `tsconfig` for passing a path to a custom typescript configuration file. We don't do any typechecking, but we do pass it along to our build process so things like `compilerOptions.paths` get resolved correctly.
> feat: path to a custom `tsconfig`

- .changeset/strange-icons-search.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
An extremely common pattern in the js ecosystem is to add additional behaviour gated by the value of `process.env.NODE_ENV`. For example, React leverages it heavily to add dev-time checks and warnings/errors, and to load dev/production versions of code. By doing this substitution ourselves, we can get a significant runtime boost in libraries/code that leverage this.
This does NOT tackle the additional features of either minification, or proper node compatibility, or injecting wrangler's own environment name, which we will tackle in future PRs.
--- 
I bumped into this need myself recently when hacking on some react code, and had to define a whole custom build script for this single feature, which is arguably super common already. Thoughts?
> RFC feat: inject `process.env.NODE_ENV` into scripts

- README.md
The links to the roadmap point to a closed issue which has been superseded by the milestone(s)
https://github.com/cloudflare/wrangler2/issues/12#issuecomment-1027253829
Could also choose to point the link to the project view instead?
https://github.com/orgs/cloudflare/projects/1/views/1
Feel free to push changes to this branch 🙃
> Fix roadmap/milestone links

- packages/prerelease-registry/package.json
I broke this in https://github.com/cloudflare/wrangler2/pull/715, reverting this single change.
> fix: publish prerelease worker correctly

- .changeset/chilly-bears-invent.md
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/index.ts
- packages/wrangler/src/tail/printing.ts
Logged messages (via console, etc) would previously be logged as an array of values. This spreads it when logging to match what is expected.
> fix: spread tail messages when logging

- .changeset/sharp-owls-dance.md
- packages/wrangler/src/__tests__/guess-worker-format.test.ts
- packages/wrangler/src/entry.ts
This tweaks the logic that guesses worker formats to check whether a `default` export is defined on an entry point before assuming it's a module worker.
> fix: assume a worker is a module worker only if it has a `default` export

- .changeset/forty-kiwis-explode.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
Currently `groups()` on yargs does not work with Commands. However, bringing logout and login into the help message will still keep continuity between documentation and the CLI.
> Added logout, login to help message

- packages/wrangler/src/__tests__/pages.test.ts
In https://github.com/cloudflare/wrangler2/pull/661, we wrote a test, but didn't actually test if the error gets thrown. Being explicit about the thrown error shows that the  error doesn't get thrown, and the warning doesn't get logged.
--- 
@JacobMGEvans Feel free to add commits to this branch and make the test pass.
> bug: `wrangler pages functions` does not log a beta warning

- .changeset/itchy-cheetahs-sit.md
- packages/wrangler/src/dev/use-esbuild.ts
Because of https://github.com/evanw/esbuild/issues/1037, we can't recover dev if esbuild fails on first run. The workaround is to end the process if it does so, until we have a better fix.
Reported in https://github.com/cloudflare/wrangler2/issues/731
> fix: exit dev if build fails on first run

- .changeset/short-cougars-approve.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/entry.ts
- packages/wrangler/src/module-collection.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/src/worker.ts
- packages/wrangler/templates/static-asset-facade.js
This adds support for `text_blobs`/Text module support in local mode. Now that https://github.com/cloudflare/miniflare/pull/228 has landed in miniflare (thanks @caass!), we can use that in wrangler as well.
Fixes https://github.com/cloudflare/wrangler2/issues/416
--- 
We can land this before miniflare does a release, but it won't work until we update miniflare. // cc @mrbbot
> `text_blobs`/Text module support for service worker format in local mode

- .changeset/forty-poets-invite.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
We had a bug where even if you'd published a script with migrations, we would still send a blank set of migrations on the next round. The api doesn't accept this, so the fix is to not do so. I also expanded test coverage for migrations.
Fixes https://github.com/cloudflare/wrangler2/issues/705
--- 
This is the first in a set of a few PRs I'll send for durable objects. Next, more validations based on exports.
> fix: only send durable object migrations when required

- .changeset/tricky-crabs-search.md
- packages/example-worker-app/src/index.js
- packages/example-worker-app/wrangler.toml
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/miniflare-cli/index.ts
Currently, I don't know if there is support for doing this in "remote" dev mode.
Resolves #737
> fix: add support for cron triggers in `dev --local` mode

- .changeset/thin-buckets-cross.md
- packages/wrangler/src/dev/local.tsx
This simple change results in:
```
npx wrangler -c packages/example-worker-app/wrangler.toml dev --local
⛅️ wrangler 0.0.24 
⎔ Starting a local server...
[mf:inf] Worker reloaded! (470B)
[mf:inf] Listening on localhost:8787
[mf:inf] - http://localhost:8787
[mf:inf] Updated Request cf object cache!
╭──────────────────────────────────────────────────────────────────────────────╮
│ B to open a browser, D to open Devtools, L to turn off local mode, X to exit │
╰──────────────────────────────────────────────────────────────────────────────╯
```
which removes the debugger messages and is an improvement.
Note that messages containing build errors, runtime errors and request/response values are not affected.
Closes #387
> fix: remove superfluous debugger log messages from local dev

- .changeset/polite-lemons-shop.md
- .vscode/settings.json
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/__tests__/route.test.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/errors.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/pages.tsx
This enables simpler testing, as we do not have to spawn new child processes
to avoid the `process.exit()` from killing the jest process.
> refactor: remove `process.exit()` from the pages code

- .changeset/grumpy-chairs-itch.md
- package-lock.json
- packages/jest-environment-wrangler/package.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.4.0`. See the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.4.0).
> chore: upgrade `miniflare` to `2.4.0`

- .changeset/bright-numbers-develop.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.tsx
Fixes https://github.com/cloudflare/wrangler2/issues/741
> fix: add a warning if `dev` is defaulting to the latest compatibility-date

- .changeset/flat-ads-flash.md
- examples/local-mode-tests/package.json
- examples/local-mode-tests/some-data.bin
- examples/local-mode-tests/some-text.txt
- examples/local-mode-tests/src/index.ts
- examples/local-mode-tests/src/module.ts
- examples/local-mode-tests/src/sw.ts
- examples/local-mode-tests/src/wrangler.module.toml
- examples/local-mode-tests/src/wrangler.sw.toml
- examples/local-mode-tests/tests/module.test.ts
- examples/local-mode-tests/tests/sw.test.ts
- examples/local-mode-tests/tsconfig.json
- package-lock.json
- packages/wrangler/src/dev/local.tsx
For `wasm_modules`/`text_blobs`/`data_blobs` in local mode, we need to rewrite the paths as absolute so that they're resolved correctly by miniflare. This also expands some coverage for local mode `wrangler dev`.
Fixes https://github.com/cloudflare/wrangler2/issues/740
Fixes https://github.com/cloudflare/wrangler2/issues/416
> fix: resolve raw file bindings correctly in `wrangler dev` local mode

- .changeset/wet-tables-pretend.md
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/inspect.ts
- packages/wrangler/src/proxy.ts
fix: abort async operations in the `Remote` component to avoid unwanted side-effects
When the `Remote` component is unmounted, we now signal outstanding `fetch()` requests, and
`waitForPortToBeAvailable()` tasks to cancel them. This prevents unexpected requests from appearing
after the component has been unmounted, and also allows the process to exit cleanly without a delay.
fixes #375
> Abort signalling

- .github/ISSUE_TEMPLATE/config.yml
The current invite in the issue template is invalid - updating to the vanity invite link.
> chore: update CloudflareDev Discord link

- .changeset/chatty-plants-pump.md
- packages/wrangler/src/dev/local.tsx
This sets up `--experiment-enable-local-persistence` to explicitly use `process.cwd() + wrangler-local-state` as a path to store values. Without it, local mode uses the temp dir that we use to bundle the worker, which gets wiped out on ending wrangler dev. In the future, based on usage, we may want to make the path configurable as well.
Fixes https://github.com/cloudflare/wrangler2/issues/766
> fix: use cwd for `--experiment-enable-local-persistence`

- packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
fix: Mocked version of `mockFetchKVGetValue` types were inconsistent with the real function being mocked `fetchKVGetValue`
> Inconsistent mock types `fetchKVGetValue`

- packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
When creating some files and rewriting others in the temp directory, the test crashed and was unable to complete cleanup. The crash prevented all subsequent tests to fail until I manually tracked the temp directory down and deleted it which looked something like this `/var/<tempDir>/<hash>/brokenFile`. 
The fix checks for the `tempDir` at test start and removes it before creating tempDir and running tests.
> Jest cleanup fix

- .changeset/dull-jobs-return.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This enables optionally passing a route as `{pattern: string, zone_id: string}`. There are scenarios where we need to explicitly pass a zone_id to the api, so this is enables that.
Some nuance: The errors from the api aren't super useful when invalid values are passed, but that's something to further work on.
This also fixes some types in our cli parsing.
Fixes https://github.com/cloudflare/wrangler2/issues/774
> feat: optionally send zone_id with a route

- .changeset/breezy-steaks-visit.md
- packages/wrangler/src/reporting.ts
fix: We want to prevent any user created code from sending Events to Sentry,
which can be captured by `uncaughtExceptionMonitor` listener.
Miniflare code can run user code on the same process as Wrangler, so we want to return `null`
if "@miniflare" is present in the Event frames.
> Improve Sentry Error Filtering

- packages/wrangler/src/__tests__/helpers/mock-http-server.ts
- packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/user.test.ts
This should allow tests to run when there is no network connection, and should
also speed up the execution of the tests that rely upon the OAuth flow.
Fixes #755
> test: refactor the mock OAuth flow so not to rely upon a real HttpServer

- .changeset/gentle-cats-destroy.md
- packages/wrangler/src/user.tsx
This removes a couple of logs we had for literally every error in our oauth flow. We throw the error and handle it separately anyway, so this is a safe cleanup.
Fixes https://github.com/cloudflare/wrangler2/issues/788
> polish: don't log all errors when logging in

- packages/wranglerjs-compat-webpack-plugin/package.json
we have an issue where we're getting rate limited by github when trying to run the tests for the webpack plugin, probably because we're not caching artifacts correctly. This disables those tests from running on CI till we figure out a fix.
> disable webpack plugin's tests from running in CI

- .changeset/khaki-mice-decide.md
- packages/wrangler/src/update-check.ts
This makes the update checker run on the channel that the version being used runs on.
> fix: check for updates on the right channel

- .changeset/fast-news-dress.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
A followup to https://github.com/cloudflare/wrangler2/pull/778, this lets you send an optional `zone_name` with routes. This is particularly useful when using ssl for saas (https://developers.cloudflare.com/ssl/ssl-for-saas/).
Fixes https://github.com/cloudflare/wrangler2/issues/793
> feat: optionally send `zone_name` with routes

- .changeset/silver-dolls-mate.md
- packages/wrangler/src/index.tsx
This fixes the signature for `isLegacyEnv()` since it doesn't use args, and we fix reading legacy_env correctly when creating a draft worker when creating a secret.
> fix: read `isLegacyEnv` correctly

- .changeset/unlucky-terms-film.md
- packages/wrangler/src/__tests__/helpers/mock-istty.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/index.tsx
Make `wrangler tail` TTY-aware, and stop printing non-JSON in JSON mode
Closes #493
2 quick fixes:
- Check `process.stdout.isTTY` at runtime to determine whether to default to "pretty" or "json" output for tailing.
- Only print messages like "Connected to {worker}" if in "pretty" mode (errors still throw strings)
> wrangler tail tty-awareness and json-respecting

- .changeset/flat-emus-share.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
Service environments are not ready for widespread usage, and their behaviour is going to change. This adds a warning if anyone uses them.
Closes https://github.com/cloudflare/wrangler2/issues/809
> add a warning if service environments are being used.

- .changeset/young-bulldogs-sell.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
feat: Added `minify` as a configuration option and a cli arg, which will minify code for `dev` and `publish`
resolves #785
> `--minify`/`config.minify` for scripts 

- .changeset/little-roses-invite.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
Much like https://github.com/cloudflare/wrangler2/pull/641, we don't want to allow setting account_id with named service environments. This is so that we use the same account_id for multiple environments, and have them group together in the dashboard.
> fix: disallow setting account_id in named service environments

- .changeset/large-beans-accept.md
- examples/pages-functions-app/functions/_middleware.ts
- examples/pages-functions-app/tests/index.test.ts
- packages/wrangler/pages/functions/template-worker.ts
Previously, `next()` would return an unlocked Response with locked headers. With this PR, we now also return unlocked (mutable) headers.
> Mutable headers for next() responses in Pages Functions

- .changeset/nice-dingos-fix.md
- packages/wrangler/src/dev/remote.tsx
We currently log an `AbortError` with a stack if we exit `wrangler dev`'s startup process before it's done. This fix skips logging that error (since it's not an exception).
Test plan:
```
cd packages/wrangler
npm run build
cd ../../examples/workers-chat-demo
npx wrangler dev
```
> fix: don't log an error when `wrangler dev` is cancelled early

- .changeset/early-ducks-travel.md
- packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/user.tsx
Error messaging from failed login would dump a `JSON.parse` error in some situations. Added a fallback if `.json` fails to parse it will attempt `.text()` then throw result. If both attempts to parse fail it will throw an `UnknownError` with a message showing where it originated.
resolves #539
> Improve login error handling

- .changeset/cuddly-ears-collect.md
- .changeset/spicy-knives-rush.md
- CODEOWNERS
- examples/pages-functions-app/CHANGELOG.md
- examples/pages-functions-app/functions/mounted-plugin/_middleware.ts
- examples/pages-functions-app/public/index.html
- examples/pages-functions-app/public/some-asset.html
- examples/pages-functions-app/tests/index.test.ts
- examples/pages-plugin-example/.gitignore
- examples/pages-plugin-example/functions/_middleware.ts
- examples/pages-plugin-example/functions/fixed.ts
- examples/pages-plugin-example/package.json
- package.json
- packages/wrangler/pages/functions/buildPlugin.ts
- packages/wrangler/pages/functions/filepath-routing.test.ts
- packages/wrangler/pages/functions/filepath-routing.ts
- packages/wrangler/pages/functions/routes.ts
- packages/wrangler/pages/functions/template-plugin.ts
- packages/wrangler/pages/functions/template-worker.ts
- packages/wrangler/src/pages.tsx
- packages/wrangler/tsconfig.json
This allows people to compile Plugins for Pages Functions. A compiled plugin is a factory for something incredibly similar to a compiled Pages Functions worker, but with just a couple of [minor tweaks](https://github.com/gregbrimble/pages-plugins#changes).
> Pages Plugins

- .changeset/wet-shirts-vanish.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/route.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/errors.ts
I got some feedback that the construction worker jacket (?) icon for deprecations is confusing, especially because it's an uncommon icon and not very big in the terminal. This patch replaces it with a more familiar warning symbol.
> polish: replace 🦺 with ⚠️

- .changeset/calm-bottles-talk.md
- packages/wrangler/src/entry.ts
This removes the timeout we have for custom builds. We shouldn't be applying this timeout anyway, since it doesn't block wrangler, just the user themselves. Further, in https://github.com/cloudflare/wrangler2/pull/759, we changed the custom build's process stdout/stderr config to "pipe" to pass tests, however that meant we wouldn't see logs in the terminal anymore. This patch removes the timeout, and brings back proper logging for custom builds.
> fix: remove timeout on custom builds, and make sure logs are visible

- .changeset/dirty-pandas-bake.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
This fix -
- passes the correct query param to check whether a workers.dev subdomain has already been published/enabled
- thus enabling it only when it's not been enabled
- it also disables it only when it's explicitly knows it's already been enabled
The effect of this is that publishes are much faster.
> fix: toggle `workers.dev` subdomains only when required

- .changeset/fast-cougars-thank.md
- .changeset/wise-candles-unite.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/sites.tsx
It can be useful to introspect built assets. A leading usecase is to upload the sourcemap that we generate to services like sentry etc, so that errors from the worker can be mapped against actual sourcce code. We introduce a `--outdir` cli arg to specify a path to generate built assets at, which doesn't get cleaned up after publishing. We are _not_ adding this to `wrangler.toml` just yet, but could in the future if it looks appropriate there.
It can be useful to do a dry run of publishing. Developers want peace of mind that a project will compile before actually publishing to live servers. Combined with `--outdir`, this is also useful for testing the output of `publish`. Further, it gives developers a chance to upload our generated sourcemap to a service like sentry etc, so that errors …
> feat: `publish --outdir <path>` and `publish --dry-run`

- .changeset/five-spies-study.md
- packages/wrangler/src/dev/local.tsx
With `--experimental-enable-local-persistence` in `dev`, we were clobbering a single folder with data from kv/do/cache. This patch gives individual folders for them. It also enables persistence even when this is not true, but that stays only for the length of a session, and cleans itself up when the dev session ends.
Fixes https://github.com/cloudflare/wrangler2/issues/830
> fix: persist dev experimental storage state in feature specific dirs

- .changeset/eleven-cheetahs-clean.md
- packages/wrangler/bin/wrangler.js
There's some interference between our data fetching library `undici` and node 18's new `fetch` and co. (powered by `undici` internally) which replaces the filename of `File`s attached to `FormData`s with a generic `blob` (likely this code - https://github.com/nodejs/undici/blob/615f6170f4bd39630224c038d1ea5bf505d292af/lib/fetch/formdata.js#L246-L250). It's still not clear why it does so, and it's hard to make an isolated example of this.
Regardless, disabling the new `fetch` functionality makes `undici` use its own base classes, avoiding the problem for now, and unblocking our release. We'll keep investigating and look for a proper fix.
Unblocks https://github.com/cloudflare/wrangler2/issues/834
> fix: make wrangler work on node v18

- examples/local-mode-tests/tests/module.test.ts
- examples/local-mode-tests/tests/sw.test.ts
Something about the local mode tests makes it occasionally break in windows on CI. Specifically, the inspector fails to connect to the miniflare process, and ends up spamming "waiting for connection" in the logs. I'm disabling these tests since they're for sanity only right now, and we have a fuller suite of tests for windows in the main package anyway.
Fixes https://github.com/cloudflare/wrangler2/issues/776
> chore: disable local-mode-tests on windows

- .changeset/early-timers-camp.md
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/user.tsx
We handle the error anyway (by doing a fresh login) which has its own logging and messaging. In the future we should add a DEBUG mode that logs all requests/errors/warnings, but that's for later.
> polish: do not log the error object when refreshing a token fails

- .changeset/mean-owls-own.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
The validation will warn users that the field can only be "type string,
alphanumeric and lowercase with dashes only" using the same RegEx as the backend
resolves #795 #775
> Add validation to the `name` field in configuration.

- .changeset/many-numbers-cheer.md
- packages/wrangler/src/miniflare-cli/index.ts
- packages/wrangler/src/miniflare-cli/request-context.ts
- packages/wrangler/src/pages.tsx
Certain runtime APIs are only available to workers during the "request context", which is any code that returns after receiving a request and before returning a response.
Miniflare emulates this behavior by using an [`AsyncLocalStorage`](https://nodejs.org/api/async_context.html#class-asynclocalstorage) and [checking at runtime](https://github.com/cloudflare/miniflare/blob/master/packages/shared/src/context.ts#L21-L36) to see if you're using those APIs during the request context.
In certain environments `AsyncLocalStorage` is unavailable, such as in a [webcontainer](https://github.com/stackblitz/webcontainer-core). This function figures out if we're able to run those "request context" checks and returns [a set of options](https://miniflare.dev/core/standards#global-functionality-limits) …
> check for an implementation of AsyncLocalStorage

- .changeset/fifty-drinks-hear.md
- examples/remix-pages-app/package.json
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wranglerjs-compat-webpack-plugin/package.json
This adds an experimental node.js compatibility mode. It can be enabled by adding `node_compat = true` in `wrangler.toml`, or by passing `--node-compat` as a command line arg for `dev`/`publish` commands. This is currently powered by `@esbuild-plugins/node-globals-polyfill` (which in itself is powered by `rollup-plugin-node-polyfills`).
We'd previously added this, and then removed it because the quality of the polyfills isn't great. We're reintroducing it regardless so we can start getting feedback on its usage, and it sets up a foundation for replacing it with our own, hopefully better maintained polyfills.
Of particular note, this means that what we promised in https://blog.cloudflare.com/announcing-stripe-support-in-workers/ now actually works.
This patch also addresses some dependency …
> feat: experimental `--node-compat` / `config.node_compat`

- .changeset/nasty-teachers-drop.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/publish.ts
Now that the APIs for getting migrations tags of services works as expected, this lands support for publishing durable objects to service environments, including migrations. It also removes the error we used to throw when attempting to use service envs + durable objects.
Fixes https://github.com/cloudflare/wrangler2/issues/739
> feat: implement service environments + durable objects

- .github/workflows/prereleases.yml
- .github/workflows/release.yml
- README.md
- packages/wrangler/CHANGELOG.md
- packages/wrangler/README.md
- packages/wrangler/src/update-check.ts
This modifies how we do releases -
- The changesets flow will now publish to latest
- Every commit will now be published as beta instead of alpha
> chore: setup releases for GA

- .changeset/bright-olives-wonder.md
- packages/wrangler/pages/functions/template-plugin.ts
- packages/wrangler/pages/functions/template-worker.ts
Replaces #872 .
Previously, `set-cookie` mulitple headers would be combined because of unexpected behavior in [the spec](https://github.com/whatwg/fetch/pull/1346).
See previous PR for details.
Unfortunately, not easily testable because of https://github.com/cloudflare/miniflare/issues/183.
> Stop unnecessarily amalgamating duplicate headers in Functions

- packages/wrangler/src/__tests__/config-cache.test.ts
- packages/wrangler/src/config-cache.ts
@threepointone , can you confirm if this is the sort of thing you had in your mind?
Might be a bit overzealous to log those messages on every read/write, but this introduces a `node_modules/.cache/wrangler/config-cache.json` that we can all just write to with whatever we want to, to persist things that we either:
- don't want to add to config, or
- don't yet know _how_ to add to config
For an example, if a user is running `wrangler dev index.ts` without a `wrangler.toml`, and they have multiple accounts for your user, we could store the `account_id` that they select in the prompt here, saving them from having to select it again the next time they want to run it.
If the user blows away their `node_modules` or switches machines, they'll need to select it again, but this is about …
> Add config cache mechanism

- .changeset/tasty-pets-divide.md
- packages/wrangler/src/dialogs.tsx
Instead of logging "Unrecognised input" when hitting return/enter in a confirm dialog, we should accept it as a confirmation. This patch also makes the default choice "y" bold in the dialog.
> polish: accept Enter as a valid key in confirm dialogs

- .changeset/tiny-beds-hope.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/route.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/errors.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/module-collection.ts
This removes the scary uppercase from DEPRECATION warnings. It also moves the service environment usage warning into `diagnostics` instead of logging it directly.
> polish: s/DEPRECATION/Deprecation

- .changeset/ten-rules-destroy.md
- packages/wrangler/src/__tests__/config-cache.test.ts
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/config-cache.ts
- packages/wrangler/src/dialogs.tsx
- packages/wrangler/src/pages.tsx
- packages/wrangler/src/user.tsx
Adds interactive prompts for the 'wrangler pages publish' and related commands.
Additionally, those commands now read from `node_modules/.cache/wrangler/pages.json` to persist users' account IDs and project names (#854). Fixes #874.
> Interactive pages publish prompts

- .changeset/spotty-waves-think.md
- examples/local-mode-tests/.env
- examples/local-mode-tests/src/wrangler.dotenv.toml
- examples/local-mode-tests/tests/dotenv.test.ts
- examples/local-mode-tests/tests/helpers.ts
- examples/local-mode-tests/tests/module.test.ts
- examples/local-mode-tests/tests/sw.test.ts
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/cli.ts
This change will automatically load up a `.env` file, if found, and apply its
values to the current environment. An example would be to provide a specific
CLOUDFLARE_ACCOUNT_ID value.
Related to cloudflare#190
> feat: add support for reading build time env variables from a `.env` file

- .changeset/curly-experts-end.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages.tsx
This adds the leading slash to a Pages deployment manifest that the API expects, and also fixes manifest generation on Windows: classic backslash vs. forwardslash problems.
> Add leading slashes to Pages manifest

- .changeset/little-colts-ring.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation.ts
Followup to https://github.com/cloudflare/wrangler2/pull/888, this replaces some more scary capitals with a more chill word.
--- 
I'm purposely leaving the message for service environments because I want to to be scary. It shouldn't be used rn.
> polish: s/DO NOT USE THIS/ Ignored

- .changeset/brave-pens-march.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev/dev-vars.ts
This tweaks the mssage when a `.dev.vars` file is used so that it doesn't imply that the user has to copy the values from it into their `wrangler.toml`.
> polish: tweak the message when `.dev.vars` is used

- .changeset/eighty-yaks-jump.md
- packages/wrangler/src/__tests__/helpers/mock-istty.ts
- packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/sentry.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/pages.tsx
- packages/wrangler/src/reporting.ts
- packages/wrangler/src/user.tsx
Added a check in non-TTY environments for `account_id`, `CLOUDFLARE_ACCOUNT_ID` and `CLOUDFLARE_API_TOKEN`. If `account_id` exists in `wrangler.toml`
then `CLOUDFLARE_ACCOUNT_ID` is not needed in non-TTY scope. The `CLOUDFLARE_API_TOKEN` is necessary in non-TTY scope and will always error if missing.
resolves #827
> non-TTY required variables checks

- .changeset/itchy-windows-attack.md
- .changeset/ninety-ducks-glow.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/helpers/mock-console.ts
- packages/wrangler/src/__tests__/https-options.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/logger.ts
Previously, when a warning or error was logged, the entire message
was formatted in bold font. This change makes only the first line of
the message bold, and the rest is formatted with a normal font.
Before
After
> fix: remove bold font from additional lines of warnings and errors

- .changeset/cold-pianos-bow.md
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
We haven't found much use for sourcemaps in production, and we should probably minify the bundle anyway. This will also remove an dev only warnings react used to log.
--- 
My initial testing shows a 10 mb reduction in bundle size, but I'm letting CI run so I can do accurate before - after comparisons with dependencies included. 
Added a changeset because this needs to be visible in case it causes a problem.
> chore: minify bundle, don't ship sourcemaps

- .changeset/eighty-islands-serve.md
- packages/wrangler/src/create-worker-preview.ts
When calling `wrangler dev`, we make a request to a special URL that "prewarms" the isolate running our Worker so that we can attach devtools etc to it before actually making a request. We'd implemented it wrongly, and because we'd silenced its errors, we weren't catching it. This patch fixes the logic (based on wrangler 1.x's implementation) and enables logging errors when the prewarm request fails.
As a result, profiling starts working again as expected. Fixes https://github.com/cloudflare/wrangler2/issues/907
> fix: fix isolate prewarm logic for `wrangler dev`

- .changeset/swift-bees-share.md
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
Allows wrangler2 to perform preview & dev sessions with a different
bucket than the published worker's binding.
This matches kv's preview_id behavior, and brings the wrangler2
implementation in sync with wrangler1.
> fix: support preview buckets for r2 bindings

- packages/wrangler/src/pages.tsx
Temporarily limit 'wrangler pages publish' to max 1k files while we optimize things behind the scenes.
> Temporarily limit 'pages publish' to 1k files

- .changeset/loud-wombats-vanish.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/index.tsx
We have a blogposts and docs that says you need to pass `--inspect` to use devtools and/or profile your Worker. In wrangler v2, we don't need to pass the flag anymore. Using it right now will throw an error, so this patch makes it a simple warning instead.
> polish: add a deprecation warning to `--inspect` on `dev`

- .changeset/silly-squids-attend.md
- packages/wrangler/src/pages.tsx
> fix: Ensure getting git branch doesn't fail on Windows

- .changeset/khaki-starfishes-draw.md
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/index.ts
- packages/wrangler/src/tail/printing.ts
Sometime the "event" on a tail can be null. This patch makes sure we don't crash when that happens. Fixes https://github.com/cloudflare/wrangler2/issues/918
> fix: don't crash when tail event is null

- .changeset/popular-ants-walk.md
- packages/wrangler/scripts/bundle.ts
When errors in wrangler happen, it's hard to tell where the error is coming from in a minified bundle. This patch removes the minification. We still set `process.env.NODE_ENV = 'production'` in the bundle so we don't run dev-only paths in things like React.
This adds about 2 mb to the bundle, but imo it's worth it.
> chore: don't minify bundles

- .changeset/fresh-dots-explode.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
When running `wrangler.init`, we look for the existence of `package.json`, / `tsconfig.json` / `.git` when deciding whether we should create them ourselves or not. Because `name` can be a relative path, we had a bug where we don't starting look from the right directory. We also had a bug where we weren't even testing for the existence of the `.git` directory correctly. This patch fixes that initial starting location, tests for `.git` as a directory, and correctly decides when to create those files.
> fix: with`wrangler init`, test for existence of `package.json`/ `tsconfig.json` / `.git` in the right locations

- .changeset/twenty-seahorses-switch.md
- packages/wrangler/src/__tests__/helpers/mock-dialogs.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
This patch modifies the terminal when running `wrangler init`, to show the proper paths of files created during it (like `package.json`, `tsconfig.json`, etc etc). It also fixes a bug where we weren't detecting the existence of `src/index.js` for a named worker before asking to create it.
--- 
This PR looks like a lot, but it's mostly additions and updates of inline snapshots.
> polish: show paths of created files with `wrangler init`

- .changeset/mighty-hats-sleep.md
- packages/wrangler/src/proxy.ts
During `dev` we log the method/url/statuscode for every req+res. This fix logs the correct details for every request.
Fixes https://github.com/cloudflare/wrangler2/issues/931
> fix: log proper response status codes in `dev`

- .changeset/weak-mangos-admire.md
- packages/wrangler/src/pages.tsx
We've had a couple of people flagging this as weird to show up in our official prod build image logs. This PR suppresses those warnings for the `wrangler build functions` command that we run to generate their Functions Worker.
Fixes #855
> Suppress beta warning when operating in Pages' CI environment

- .changeset/wise-lies-visit.md
- packages/wrangler/src/__tests__/parse.test.ts
- packages/wrangler/src/parse.ts
The TOML parser that Wrangler uses crashes if there is a Windows line-ending in a comment.
See https://github.com/iarna/iarna-toml/issues/33.
According to the TOML spec, we should be able to normalize line-endings as we see fit.
See https://toml.io/en/v1.0.0#:~:text=normalize%20newline%20to%20whatever%20makes%20sense.
This change normalizes line-endings of TOML strings before parsing to avoid hitting this bug.
Fixes https://github.com/cloudflare/wrangler2/issues/915
> fix: support Windows line-endings in TOML files

- .changeset/beige-carpets-return.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages.tsx
We're backing out of cloudflare/wrangler2#940. Bulk upload proves slower than the previous single-file upload, so until we work out how to improve this, we'll stick with the 1k file limit and single-file uploading.
> Revert "Use bulk upload api for 'pages publish'"

- .changeset/good-geese-matter.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
We detect whether a worker is a "modules" format worker by the presence of a `default` export. This is a pretty good heuristic overall, but sometimes folks can make mistakes. One situation that's popped up a few times, is people writing exports, but still writing it in "service worker" format. We detect this fine, and log a warning about the exports, but send it up with the exports included. Unfortunately, our runtime throws when we mark a worker as a service worker, but still has exports. This patch fixes it so that the exports are not included in a service-worker worker.
Note that if you're missing an event listener, it'll still error with "No event handlers were registered. This script does nothing." but that's a better error than the SyntaxError _even when the listener was there_. …
> fix: bundle worker as iife if detected as a service worker

- .changeset/chatty-wolves-bathe.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages.tsx
Thanks @isaac-mcfadyen !
This makes the directory required for `wrangler pages publish` and also improves the help messaging of the CLI args.
> Fix 'pages publish' defaults

- .changeset/nice-mangos-matter.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/user.tsx
To allow OAuth to work on environments such as WebContainer we have to generate a host-specific callback URL. This PR uses `@webcontainer/env` to generate such URL only for running in WebContainer. Otherwise the callback URL stays unmodified.
> feat: use host specific callback url

- .changeset/ninety-donkeys-reflect.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/index.tsx
Previously, we were only calling `getPort()` if the configured port was undefined.
But since we were setting the default for this during validation, it was never undefined.
Fixes [#949](https://github.com/cloudflare/wrangler2/issues/949)
> fix: look for an alternate port in the dev command if the configured one is in use

- .changeset/afraid-cows-count.md
- packages/wrangler/src/index.tsx
When a command isn't available on a system, calling `execa()` on it throws an error, and not just a non zero exitCode. This patches fixes the flow so we don't crash the whole process when that happens on testing the presence of `git` when calling `wrangler init`.
Fixes https://github.com/cloudflare/wrangler2/issues/950
--- 
I still dunno a good way of testing this without hacks... mocking `execa` is painful. I did test this locally as well as I could, by replacing `git` with `gi` (which I'm certain doesn't exist on my machine ha)
> fix: don't crash during `init` if `git` is not installed

- .changeset/hungry-bugs-marry.md
- package-lock.json
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/index.tsx
The `--legacy-env` flag was in global scope, which only certain commands
utilize the flag for functionality, and doesnt do anything for the other commands.
resolves #933
> refactor: Moving `--legacy-env` out of global

- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
I noticed the link to `deprecations.md` was 404ing since it got moved to the cloudflare-docs repo.
> chore: update link to deprecations.md

- .changeset/honest-pants-move.md
- examples/pages-functions-app/tests/index.test.ts
- examples/pages-plugin-example/functions/static.ts
- examples/pages-plugin-example/functions/static/_middleware.ts
- examples/pages-plugin-example/public/dir/bar.html
- examples/pages-plugin-example/public/foo.html
- packages/wrangler/pages/functions/buildWorker.ts
- packages/wrangler/pages/functions/template-plugin.ts
- packages/wrangler/src/pages.tsx
Fixes Pages Plugins and static asset routing.
There was previously a bug where a relative pathname would be missing the leading slash which would result in routing errors.
> Fix Pages Plugins and static asset routing

- .changeset/few-cherries-shave.md
- packages/wrangler/bin/wrangler.js
When we start up the CLI, we check what the minimum version of supported node is, and throw an error if it isn't at least 16.7. However, the script that runs this, imports `node:child_process` and `node:path`, which was only introduced in 16.7. It was backported to older versions of node, but only in last updates to majors. So for example, if someone used 14.15.4, the script would throw because it wouldn't be able to find `node:child_process` (but it _would_ work on v14.19.2).
The fix here is to not use the prefixed versions of these built-ins in the bootstrap script. Fixes https://github.com/cloudflare/wrangler2/issues/979
> fix: throw appropriate error when we detect an unsupported version of node

- README.md
The prod docs link is _wrangler:dos_ ready, and it was mildly confusing to find myself in the parallel preview docs world.
> docs: point wrangler docs link to canon

- .changeset/chatty-penguins-help.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
- packages/wrangler/src/sites.tsx
This cleans up some logic from https://github.com/cloudflare/wrangler2/pull/964.
- we shouldn't be encoding the id when deleting a namespace, since that'll already be an alphanumeric id
- we should be encoding the key when we call `kv:key get`, or we get a similar issue as in https://github.com/cloudflare/wrangler2/issues/961
- adds `KV` to all the KV-related function names
- moves the api calls to `kv:namespace delete` and `kv:key delete` inside `kv.ts` helpers.
> fix: encode key when calling `kv:ket get`, don't encode when deleting a namespace

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/release.yml
Added caching of `node_modules` which will skip `npm ci` when nothing has changed in any `package.json`
also using the `setup-node` built-in cache of `~/.npm` which will speed up `npm ci` when it has to run.
Converted `npm install` to `npm ci` there are deterministic advantages, `node_modules` gets blown away when it runs, when lockfile exists it will be quicker and adhere to the lockfile completely (no unintended upgrades in CI)
> chore: setup the workflows to cache

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/release.yml
fix: Windows symlinks are lost during caching, resolution is always running `npm ci` for Windows GitHub Workflows
> Windows caching fix in GH Workflows

- .changeset/violet-poems-wait.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
This adds client side validation for the paylod for `kv:bulk put`, importantly ensuring we're uploading only string key/value pairs (as well as validation for the other fields).
Fixes https://github.com/cloudflare/wrangler2/issues/571
> polish: validate payload for `kv:bulk put` on client side

- .changeset/forty-mice-travel.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/index.tsx
When given routes, we use the host name from the route to deduce a zone id to pass along with the host to set with dev `session`. Route patterns can include leading `*`/`*.`, which we don't account for when deducing said zone id, resulting in subtle errors for the session. This fix strips those leading characters as appropriate.
Fixes https://github.com/cloudflare/wrangler2/issues/1002
> fix: strip leading `*`/`*.` from routes when deducing a host for `dev`

- .changeset/metal-bees-shop.md
- packages/wrangler/src/index.tsx
We check for the presence of Git by trying to run `git --version`.
On non-Windows we get an Error with `code` set to "ENOENT".
One Windows we get a different error:
```
{
"shortMessage":"Command failed with exit code 1: git --version",
"command":"git --version",
"escapedCommand":"git --version",
"exitCode":1,
"stdout":"",
"stderr":"'git' is not recognized as an internal or external command,\r\noperable program or batch file.",
"failed":true,
"timedOut":false,
"isCanceled":false,
"killed":false
}
```
Since we don't really care what the error is, now we just assume that Git
is not available if an error is thrown.
Fixes #1022
> fix: `wrangler init` should not crash if Git is not available on Windows

- .changeset/polite-buses-prove.md
Looks like we haven't published the webpack plugin yet, bumping it to include it in the next one. 
Fixes https://github.com/cloudflare/wrangler2/issues/1020
> chore: Bumping wranglerjs-compat-webpack-plugin to do a release

- .changeset/hot-insects-cry.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/worker.ts
This adds experimental support for service bindings, aka worker-to-worker bindings. It's lets you "call" a worker from another worker, without incurring any network cost, and (ideally) with much less latency. To use it, define a `[services]` field in `wrangler.toml`, which is a map of bindings to worker names (and environment). Let's say you already have a worker named "my-worker" deployed. In another worker's configuration, you can create a service binding to it like so:
```toml
[[services]]
binding = "MYWORKER"
service = "my-worker"
environment = "production" # optional, defaults to the worker's `default_environment` for now  
```
And in your worker, you can call it like so:
```js
fetch(req, env, ctx) {
return env.MYWORKER.fetch(new Request("./some-path"));
},
};
```
- …
> feat: implement support for service bindings

- .changeset/lazy-sheep-rest.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
Fixes https://github.com/cloudflare/wrangler2/issues/1038
> fix: don't fetch migrations when in `--dry-run` mode

- .changeset/shy-eels-march.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/publish.ts
With the release of Custom Domains for workers, users can publish directly to a custom domain on a route, rather than creating a dummy DNS record first and manually pointing the worker over - this adds the same support to wrangler.
Users declare routes as normal, but to indicate that a route should be treated as a custom domain, a user simply uses the object format in the toml file, but with a new key: custom_domain (i.e. `routes = [{ pattern = "api.example.com", custom_domain = true }]`)
When wrangler sees a route like this, it peels them off from the rest of the routes and publishes them separately, using the /domains api. This api is very defensive, erroring eagerly if there are conflicts in existing Custom Domains or managed DNS records. In the case of conflicts, wrangler prompts for …
> Add support for publishing to Custom domains

- .changeset/heavy-rabbits-accept.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/index.tsx
Previously, when an invalid subcommand was used, such as `wrangler r2 foo`,
the help that was displayed showed the top-level commands prefixed by the command in used.
E.g.
```
wrangler r2 init [name]       📥 Create a wrangler.toml configuration file
wrangler r2 dev [script]      👂 Start a local server for developing your worker
wrangler r2 publish [script]  🆙 Publish your Worker to Cloudflare.
...
```
Now the correct command help is displayed:
```
$ wrangler r2 foo
✘ [ERROR] Unknown argument: foo
wrangler r2
📦 Interact with an R2 store
Commands:
wrangler r2 bucket  Manage R2 buckets
Flags:
-c, --config   Path to .toml configuration file  [string]
-h, --help     Show help  [boolean]
-v, --version  Show version number  [boolean]
```
Fixes #871
> fix: display the correct help information when a subcommand is invalid

- .changeset/grumpy-dolphins-explain.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/index.tsx
Added `trimTrailingWhitespace()` to secretValue being sent in PUT request
Matching Wrangler legacy behavior with handling inputs
resolves #993
> fix: secret input trailing spaces

- .changeset/large-pets-cheer.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages.tsx
Fixes #1029
Our extension extraction logic was taking into account folder names, which can include periods. The logic would incorrectly identify a file path of `.well-known/foo` as having the extension of `well-known/foo` when in reality it should be an empty string.
> Fix incorrect extension extraction from file paths

- .changeset/tame-tigers-impress.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages.tsx
On Windows, the following command `wrangler pages dev -- foo bar` would error
saying that `bar` was not a known argument. This is because `foo` and `bar` are
passed to Yargs as separate arguments.
A workaround is to put the command in quotes: `wrangler pages dev -- "foo bar"`.
But this fix makes the `command` argument variadic, which also solves the problem.
Fixes [#965](https://github.com/cloudflare/wrangler2/issues/965)
> fix: pages "command" can consist of multiple words

- CODEOWNERS
We've just created the @cloudflare/pages team so everyone can stay on top of our open-sourced work.
Adds the team as codeowners for Pages stuff. We don't yet have a `src/pages/` folder, but I figure it's probably inevitable when we refactor the `src/pages.tsx` a bit.
> Adds Pages team as codeowners

- .changeset/empty-oranges-attack.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
It can be helpful for a user to know exactly what resources a worker will have access to and where they can access them, so we now log the bindings available to a worker during `wrangler dev` and `wrangler publish`.
Will rendering the `<Dev />` component interfere with the logged output during `wrangler dev`?
Closes #509
> Print the bindings a worker has access to during `dev` and `publish`

- .changeset/gold-books-beam.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/durable.ts
- packages/wrangler/src/publish.ts
This refactors some logic around durable objects -
- During publish, we were checking whether `[migrations]` were defined in the presence of `[durable_objects]`, and warning if not. This moves it into the config validation step, which means it'll check for all commands (but notably `dev`)
- It moves the code to determine current migration tag/migrations to upload into a helper. We'll be reusing this soon when we upload migrations to `dev`.
---
For additional context, I have a PR in flight that adds migrations to dev, blocked on some api changes, and it's been hard to rebase that over code that's been landing. This will make it easier to land that, and the additional validation is welcome.
> refactor: detect missing `[migrations]` during config validation

- .changeset/nine-crabs-raise.md
- packages/wrangler/src/dev/remote.tsx
Could use tips on how to test this change 👀 
Closes #1068
> fix: friendlier error for when a subdomain hasn't been configured in dev mode

- .changeset/lazy-cows-press.md
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
- packages/wrangler/src/parse.ts
This "quick-win" refactors some of the code to avoid the use of `any` where possible.
Using `any` can cause type-checking to be disabled across the code in unexpectedly wide-impact ways.
There is one other use of `any` not touched here because it is fixed by #1088 separately.
> refactor: remove use of `any`

- .changeset/nasty-cobras-remember.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/abort.d.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/proxy.ts
When running `wrangler dev` we create a proxy to the actual remote Worker.
After creating a connection to this proxy by a browser request the proxy did not shutdown.
Now we use a `HttpTerminator` helper library to force the proxy to close open connections and shutdown correctly.
Fixes https://github.com/cloudflare/wrangler2/issues/958
> fix: ensure that the proxy server shuts down to prevent `wrangler dev` from hanging

- .changeset/forty-dolphins-heal.md
- packages/wrangler/src/__tests__/parse.test.ts
- packages/wrangler/src/parse.ts
Only the last line-ending was being normalized not all of them.
Fixes https://github.com/cloudflare/wrangler2/issues/1094
> fix: ensure all line endings are normalized before parsing as TOML

- .changeset/calm-worms-bake.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
> feat: batch installs for npm packages

- .changeset/beige-cobras-train.md
- packages/wrangler/src/index.tsx
Before:
```
⛅️ wrangler 0.0.0-3c7a216
---------------------------------------------------------------------
Using npm as package manager.
✨ Created quick-wins-init-1-1/wrangler.toml
Would you like to use git to manage this Worker? (y/n)
✨ Initialized git repository at quick-wins-init-1-1
No package.json found. Would you like to create one? (y/n)
✨ Created quick-wins-init-1-1/package.json
Would you like to use TypeScript? (y/n)
✨ Created quick-wins-init-1-1/tsconfig.json
Would you like to create a Worker at quick-wins-init-1-1/src/index.ts? (y/n)
✨ Created quick-wins-init-1-1/src/index.ts
npm ERR! code ETARGET
npm ERR! notarget No matching version found for wrangler@0.0.0-3c7a216.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package …
```
> fix: print instructions even if installPackages fails

- .changeset/giant-trees-mix.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
polish: Default branch when choosing to initialize a git repository will now be `main`.
This is inline with current common industry ethical practices.
See:
- https://sfconservancy.org/news/2020/jun/23/gitbranchname/
- https://github.com/github/renaming
- https://sfconservancy.org/news/2020/jun/23/gitbranchname/
> Git default `main` branch

- .changeset/neat-frogs-smash.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
Since `wrangler publish --dry-run --outdir=dist` is basically the same result
as what Wrangler 1 did with `wrangler build` let's run that for the user if
they try to run `wrangler build`.
> fix: delegate `wrangler build` to `wrangler publish`

- .changeset/tough-flies-dream.md
- packages/wrangler/templates/new-worker.ts
closes #1112 
The current prettier `printWidth` setting forces the function parameters onto multiple lines.  If that's an issue, bumping `printWidth` from 80 to 90 fixes it.
> New worker improvements

- .changeset/pink-plums-turn.md
- .changeset/wise-panthers-glow.md
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/index.tsx
I find the current message confusing. The response is not bad it is a valid response saying that the request failed.
> fix: improve error message when CF API responds with an error

- .changeset/ten-countries-kiss.md
- package-lock.json
- packages/jest-environment-wrangler/package.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.5.0`. See the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.5.0).
> chore: upgrade `miniflare` to `2.5.0`

- packages/wrangler/src/__tests__/helpers/run-wrangler.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
Static assets manifest keys contain backslash on the Windows platform causing different manifests on different platforms.
This PR makes sure manifest keys are the same on Windows.
> fix: manifest keys contains backslash (windows)

- .vscode/settings.json
- ISSUE_TRIAGE.md
Having spent some time this week triaging issues, I feel it would be valuable to add priority to the issues using P0-P5 rating.
This will make it much easier to decide what to work on.
This PR describes these priority levels and how the team can apply them, along with general triaging steps.
> chore: add issue triage docs

- .changeset/stale-frogs-talk.md
- README.md
- packages/wrangler/README.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
> fix: rename "publish" package.json script to "deploy"

- .changeset/rare-chicken-cross.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
This gives a slightly better message when migrations are missing for declared durable objcts. Specifically, it gives a copy-pastable section to add to wrangler.toml, and doesn't show the warning at all for invalid class names anymore.
Partially makes https://github.com/cloudflare/wrangler2/issues/1076 better.
> polish: Give a copy-paste config when `[migrations]` are missing

- .changeset/few-cars-heal.md
- packages/wrangler/bin/wrangler.js
With package managers like yarn, the cloudflare cert won't be available on the filesystem as expected (since the module is inside a .zip file). This fix instead extracts the file out of the module, copies it to a temporary directory, and directs node to use that as the cert instead, preventing warnings like https://github.com/cloudflare/wrangler2/issues/1136.
Fixes https://github.com/cloudflare/wrangler2/issues/1136
> fix: extract Cloudflare_CA.pem to temp dir before using it

- .changeset/empty-news-jog.md
- packages/wrangler/src/pages.tsx
> fix: Ignore .git dir during pages publish

- .changeset/cyan-guests-grin.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/index.tsx
Because we were calling `printBindings` during the render phase of `<Dev/>`, we were logging the bindings multiple times (render can be called multiple times, and the interaction of Ink's stdout output intermingled with console is a bit weird). We could have put it into an effect, but I think a better solution here is to simply log it before we even start rendering `<Dev/>` (so we could see the bindings even if Dev fails to load, for example).
This also adds a fix that masks any overriden values so that we don't accidentally log potential secrets into the terminal.
> fix: only log available bindings once in `dev`

- .changeset/fast-mangos-protect.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/index.tsx
Previously, when an error occurs, wrangler says:
> If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new.
Now, it links through to the issue template chooser which is more helpful.
Fixes [#1169](https://github.com/cloudflare/wrangler2/issues/1169)
> fix: link to the issue chooser in GitHub

- .changeset/late-suits-vanish.md
- packages/wrangler/src/__tests__/package-manager.test.ts
- packages/wrangler/src/package-manager.ts
Adds support for `pnpm` projects - if `pnpm-lock.yaml` is found, it will use `pnpm` to install the packages.
If `npm` and `yarn` isn't found, it defaults to `pnpm` even without `pnpm-lock.yaml`.
(I'd personally argue that it should try `yarn` and `pnpm` before `npm`, as it's installed by default with node, but I tried to respect the current behaviour)
> feat: add pnpm support

- .changeset/eleven-games-mate.md
- packages/wrangler/src/create-worker-preview.ts
When generating a preview session on the edge with `wrangler dev`, for a zoned worker we were using a random id as the script ID. This would make the backend not associate the dev session with any resources that were otherwise assigned to the script (specifically for secrets, but other stuff as well) The fix is simply to use the worker name (when available) as the script ID.
Fixes https://github.com/cloudflare/wrangler2/issues/1003
Fixes https://github.com/cloudflare/wrangler2/issues/1172
--- 
This is a good fix, but there are some followup items we should do. Tracking here - https://github.com/cloudflare/wrangler2/issues/1191
> fix: use worker name as a script ID when generating a preview session

- .changeset/tender-chefs-provide.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
Rather than using the recently added `--initial-branch` option, we now just renamed the initial branch using `git branch -m main`.
Fixes https://github.com/cloudflare/wrangler2/issues/1168
> fix: ensure wrangler init works with older versions of git

- .changeset/honest-cobras-relate.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/worker.ts
- packages/wrangler/src/zones.ts
It could be worth reviewing this commit by commit, given that quite a few lines changed.
Fixes #651
> fix: route deployment fallback for restricted permission API tokens

- .changeset/poor-houses-warn.md
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/user.tsx
- packages/wrangler/src/whoami.tsx
Instead of:
```
rozenmd@QRVX0PWXHR ~ % wrangler logout
⛅️ wrangler 2.0.8
-------------------
Not logged in, exiting...
rozenmd@QRVX0PWXHR ~ % CLOUDFLARE_API_TOKEN=xxx wrangler whoami
⛅️ wrangler 2.0.8
-------------------
Getting User settings...
👋 You are logged in with an OAuth Token, associated with the email 'xxxxxxxx+cf@gmail.com'!
┌───────────────────────────────────┬──────────────────────────────────┐
│ Account Name                      │ Account ID                       │
├───────────────────────────────────┼──────────────────────────────────┤
│ xxxxxxxx+cf@gmail.com's Account   │ xxx                              │
└───────────────────────────────────┴──────────────────────────────────┘
```
Folks will now see:
```
rozenmd@QRVX0PWXHR ~ % CLOUDFLARE_API_TOKEN=xxx wrangler whoami
⛅️ …
```
> fix: differentiate between API and OAuth in whoami

- .changeset/funny-crabs-add.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/user.tsx
Previously, if you are not logged in when running `wrangler dev` it will only try to log you in
if you start in "remote" mode. In "local" mode there is no need to be logged in, so it doesn't
bother to try to login, and then will crash if you switch to "remote" mode interactively.
The problem was that we were only attempting to login once before creating the `<Remote>` component.
Now this logic has been moved into a `useEffect()` inside `<Remote>` so that it will be run whether
starting in "remote" or transitioning to "remote" from "local".
The fact that the check is no longer done before creating the components is proven by removing the
`mockAccountId()` and `mockApiToken()` calls from the `dev.test.ts` files.
Fixes [#18](https://github.com/cloudflare/wrangler2/issues/18)
> fix: do not crash when not logged in and switching to remote dev mode

- .changeset/clean-jokes-travel.md
- packages/wrangler/src/pages.tsx
~Waiting on an internal thing to be released, but once that's out, this PR will be ready to go.~ It's out!
feat: Upload the delta for `wrangler pages publish`
We now keep track of the files that make up each deployment and intelligently only upload the files that we haven't seen. This means that similar subsequent deployments should only need to upload a minority of files and this will hopefully make uploads even faster.
The only bit that has changed is this: https://github.com/cloudflare/wrangler2/pull/1210/files#diff-671053f3ecffd0e36229ae8b3c6090a2becd125b2c3247a41de85836dca29884R1063-R1078
The rest is just pulling out the upload logic for future re-use.
> Deltas for 'wrangler pages publish'

- .changeset/late-carrots-push.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
This adds a warning when we find unexpected fields on the `triggers` config (and any future fields that use the `isObjectWith()` validation helper)
> fix: warn on unexpected fields on `config.triggers`

- .changeset/rich-pants-sleep.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
As reported in https://github.com/cloudflare/wrangler2/issues/1189, we're including the name of the folder in the keys of the KV store that stores the assets. This doesn't match v1 behaviour. It makes sense not to include these since, we should be able to move around the folder and not have to reupload the entire folder again.
Fixes https://github.com/cloudflare/wrangler2/issues/1189
> polish: don't include folder name in Sites kv asset keys

- .changeset/quiet-pots-kiss.md
- packages/wrangler/src/index.tsx
- packages/wrangler/src/proxy.ts
When making changes to the configuration file, the development server will restart. Currently `bindings` is passed into the server to be refreshed.
#439
> Reload server on config changes

- .changeset/odd-trains-bake.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
We had a bug where we were generating asset manifest keys incorrectly if we ran wrangler from a different path to `wrangler.toml`. This fixes the generation of said keys, and adds a test for it.
Fixes https://github.com/cloudflare/wrangler2/issues/1235
> fix: generate site assets manifest relative to `site.bucket`

- .changeset/stupid-dots-beam.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/dev.tsx
In projects where:
- all the source code isn't in one folder (like a monorepo, or even where the worker has non-standard imports across folders),
- we use a custom build, so it's hard to statically determine folders to watch for changes
...we'd like to be able to specify multiple paths for custom builds, (the config `build.watch_dir` config). This patch enables such behaviour. It now accepts a single path as before, or optionally an array of strings/paths.
Fixes https://github.com/cloudflare/wrangler2/issues/1095
--- 
Disable whitespace changes for this review (?w=1)
> feat: `build.watch_dir` can be an array of paths

- .changeset/curvy-donuts-knock.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
When we upload a script bundle, we get the actual content of the script back in the response. Sometimes that script can be large (depending on whether the upload was large), and currently it may even be a badly escaped string. We can pass a queryparam `excludeScript` that, as it implies, exclude the script content in the response. This fix does that.
Will eventually fix https://github.com/cloudflare/wrangler2/issues/1222
--- 
This fix working is dependent on the internal api rolling out support for this query param, which is imminent.
> fix: instruct api to exclude script content on worker upload

- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
The `watch_dir` does not need to be explicitly typed with `undefined` as it has a default value of `./src`.
By initializing the default when reading from the raw config,
we can avoid the `let` and related statements.
(I was a little late to review #1231 so I thought I would just send this instead)
> refactor: simplify `watch_dir` validation

- .changeset/curly-lizards-rescue.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
- packages/wrangler/src/parse.ts
> fix: kv:key put upload binary files fix

- .changeset/loud-meals-visit.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/index.tsx
`--experimental-public` is an abstraction over Workers Sites, and we can leverage miniflare's inbuilt support for Sites to serve assets in local mode.
> feat: support `--experimental-public` in local mode

- .changeset/tender-tables-fetch.md
- packages/wrangler/templates/static-asset-facade.js
> fix: pass env and ctx to request handler when using `--experimental-public`

- .changeset/good-mugs-tease.md
- package-lock.json
- packages/wrangler/package.json
Bumping for this security release https://github.com/nodejs/undici/releases/tag/v5.5.1
Manually tested:
> fix: bump undici to latest 

- .changeset/slow-bananas-protect.md
- packages/wrangler/src/__tests__/logger.test.ts
- packages/wrangler/src/logger.ts
As discussed in https://github.com/cloudflare/wrangler2/issues/1266
This allows the user to set the logging level via an environment variable.
$ WRANGLER_LOG=debug wrangler publish
> Allow setting debug level via env variable

- .changeset/quiet-pigs-care.md
- packages/wrangler/src/__tests__/helpers/mock-dialogs.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/index.tsx
When initializing a new project (via `wrangler init`) we attempt to reuse files in the current
directory, or in an ancestor directory. In particular we look up the directory tree for
package.json and tsconfig.json and use those instead of creating new ones.
Now we only do this if you do not specify a name for the new Worker. If you do specify a name,
we now only consider files in the directory where the Worker will be initialized.
Fixes https://github.com/cloudflare/wrangler2/issues/859
> fix: do not consider ancestor files when initializing a project with a specified name

- .changeset/curly-lizards-rescue.md
- packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
- packages/wrangler/src/__tests__/helpers/mock-process.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
- packages/wrangler/src/parse.ts
> fix: kv:key binary puts/gets

- .changeset/wise-steaks-end.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/proxy.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/src/sites.tsx
This adds support for defining `assets` in `wrangler.toml`. You can configure it with a string path, or a `{bucket, include, exclude}` object (much like `[site]`). This also renames the `--experimental-public` arg as `--assets`.
Via https://github.com/cloudflare/wrangler2/issues/1162
--- 
Followup tasks (I'll make issues for each of these later, but logging here for visibility)
> feat: `--assets` / `config.assets` to serve a folder of static assets

- .changeset/pretty-lemons-move.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/entry.ts
- packages/wrangler/templates/no-op-worker.js
Since we use a facade worker with `--assets`, an entry point is not strictly necessary. This makes a common usecase of "deploy a bunch of static assets" extremely easy to start, as a one liner `npx wrangler dev --assets path/to/folder` (and same with `publish`).
> feat: entry point is not mandatory if `--assets` is passed

- .changeset/tasty-ravens-double.md
- packages/wrangler/src/dev/dev.tsx
A quick bugfix to make sure --assets/config.assets gets served correctly in `dev --local`.
> fix: serve `--assets` in dev + local mode

- .changeset/afraid-fishes-retire.md
- package-lock.json
- packages/jest-environment-wrangler/package.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.5.1`, addressing security issues in `undici`, `node-forge` and `minimist`. See the [full changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.5.1).
> chore: upgrade `miniflare` to `2.5.1`

- .changeset/eighty-bags-destroy.md
- packages/wrangler/src/git-client.ts
- packages/wrangler/src/index.tsx
If `git` does not support the `--initial-branch` argument then just fallback to the default initial branch name.
We tried to be more clever about this but there are two many weird corner cases with different git versions on different architectures.
Now we do our best, with recent versions of git, to ensure that the branch is called `main` but otherwise just make sure we don't crash.
Fixes https://github.com/cloudflare/wrangler2/issues/1228
> fix: support all git versions for wrangler init

- .changeset/lovely-toys-happen.md
- packages/wrangler/bin/wrangler.js
- packages/wrangler/package.json
Delegate to a local install of `wrangler` if one exists.
Users will frequently install `wrangler` globally to run commands like `wrangler init`, but we also recommend pinning a specific version of `wrangler` in a project's `package.json`. Now, when a user invokes a global install of `wrangler`, we'll check to see if they also have a local installation. If they do, we'll delegate to that version.
Closes #955
Here's a recording of this in action, with a couple `console.log`s indicating if a global or local installation is running:
[![asciicast](https://asciinema.org/a/qfw9PNGP2BHGiYd0UVjandH9p.svg)](https://asciinema.org/a/qfw9PNGP2BHGiYd0UVjandH9p)
> Delegate to local installs of wrangler when possible

- .changeset/large-lizards-enjoy.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
Before we were resolving the Site directory relative to the location of  at all times.
Now the  is resolved relative to current working directory. Additionally, we added logging of where
the configuration is being read from.
resolves #1243
> feat:  working directory pathing

- .changeset/lemon-olives-sip.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
Before we were resolving the Asset directory relative to the location of  at all times.
Now the  cli arg is resolved relative to current working directory.
resolves #1333
> feat: resolve  cli arg relative to current working directory

- .changeset/shiny-avocados-smoke.md
- packages/wrangler/src/dev/local.tsx
> fix: show console error/warn logs when using `dev --local`

- .changeset/forty-doors-argue.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
The reporter is now called before the publish API call, printing every time.
Additionally added a test that handles a `publish` failure indicating "script exceeding size limits" and the bundle size is still printed. 
resolves #1328
> polish: bundle reporter was not printing during publish errors

- .changeset/loud-cheetahs-tan.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
This change will allow us to do many awesome things in the future 😏 
The first in a series of PRs where I intend to clean up `index.tsx` to only be a series of:
```js
// dev
wrangler.command(
"dev [script]",
"👂 Start a local server for developing your worker",
devOptions,
devHandler
);
```
So that identifying the blast radius of a PR can be a simple as glancing at the files changed
> patch: split dev function out of index.tsx

- .changeset/rude-radios-buy.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
We already have a warning when `config.assets` is used, this adds it for the cli argument as well.
> polish: add an experimental warning if `--assets` is used

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/release.yml
Updating to `actions/checkout@v3` which uses Node 16 runtime.
Additionally there are other internal NPM packages updated in the v3
> Updating `actions/checkout`

- .changeset/thick-meals-itch.md
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/user/env-vars.ts
- packages/wrangler/src/user/user.tsx
- packages/wrangler/src/whoami.tsx
- packages/wrangler/src/worker.ts
Closes #1072 
* A user _must_ supply _both_ an Global API Key and Email for this to work.
* Can use `CLOUDFLARE_API_KEY` and `CLOUDFLARE_EMAIL` or the deprecated `CF_API_KEY` and `CF_EMAIL` keys.
* Takes precedence over `CLOUDFLARE_API_TOKEN` and oAuth.
Refactored the assumption that an `apiToken` was a string and have replaced that with an `ApiCredentials` type:
```ts
export type ApiCredentials =
| {
apiToken: string;
}
| {
authKey: string;
authEmail: string;
};
```
This flowed _fairly_ easily through the code, picked up inside `addAuthorizationHeaderIfUnspecified`:
```ts
function addAuthorizationHeaderIfUnspecified(
headers: Record<string, string>,
auth: ApiCredentials
): void {
if (!("Authorization" in headers)) {
if ("apiToken" in auth) {
headers["Authorization"] = `Bearer …
```
> Added Global API Key (X-Auth-Key) support to Wrangler

- .changeset/swift-bobcats-joke.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/preview.tsx
- packages/wrangler/src/publish.ts
This implements `config.define`. This lets the user define a map of keys to strings that will be substituted in the worker's source. This is particularly useful when combined with environments. A common usecase is for values that are sent along with metrics events; environment name, public keys, version numbers, etc. It's also sometimes a runaround for module env vars, which otherwise have to be threaded through request function stacks.
> feat: implement `config.define`

- .changeset/big-tables-judge.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/templates/checked-fetch.js
In Workers published to the Edge (rather than previews) there is a bug where a custom port on a downstream fetch request is ignored, defaulting to the standard port.
For example, `https://my.example.com:668` will actually send the request to `https://my.example.com:443`.
This does not happen when using `wrangler dev` (both in remote and local mode), but to ensure that developers are aware of it this change displays a runtime warning in the console when the bug is hit.
Closes #1320
> fix: add warning to `fetch()` calls that will change the requested port

- .changeset/curly-bulldogs-shake.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/preview.tsx
- packages/wrangler/src/worker.ts
We can pass routes when creating a `dev` session. The effect of this is when you visit a path that _doesn't_ match the given routes, then it instead does a fetch from the deployed worker on that path (if any). We were previously passing `*/*`, i.e, matching _all_ routes in dev; this fix now passes configured routes instead. Based on https://github.com/cloudflare/wrangler2/pull/1055
> fix: pass `routes` to `dev` session

- .changeset/slow-pianos-impress.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
Disable whitespace for this review!
--- 
In older templates, (i.e made for wrangler 1.x), `account_id =''` is considered as a valid input, but then ignored. With wrangler 2, when running wrangler dev, we log an error, but it fixes itself after we get an account id. Much like https://github.com/cloudflare/wrangler2/issues/1329, the fix here is to normalise that value when we see it, and replace it with `undefined` while logging a warning.
This fix also tweaks the messaging for a blank route value to suggest some user action.
> fix: normalise `account_id = ''` to `account_id: undefined`

- .changeset/small-needles-wash.md
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/whoami.tsx
Display email from process env in whoami and display better error when lacking permissions.
> fix: email from env & error messaging 

- .changeset/small-doors-invite.md
- package-lock.json
- packages/wrangler/package.json
- tsconfig.json
Hi
I wanted to use the relatively new typescript feature "extends constraints on infer type variables". 
This is supported since esbuild version [v0.14.46](https://github.com/evanw/esbuild/releases/tag/v0.14.46).
Current workaround to use locally 
package.json:
```json
"devDependencies": {
"esbuild": "0.14.47",
"wrangler": "2.0.15"
},
"overrides": {
"wrangler": {
"esbuild": "$esbuild"
}
},
```
> Updated esbuild to version 0.14.47 in wrangler package

- .github/workflows/d1.yml
This github action runs on all pushes to the d1 branch, and publishes a tagged version og wrangler to npm (`wrangler@d1`). We're using this for closed beta testing of D1, the new Workers database.
> Github action to publish `wrangler@d1` releases

- .changeset/little-horses-perform.md
- fixtures/wrangler-dev-api-app/package.json
- fixtures/wrangler-dev-api-app/src/index.js
- fixtures/wrangler-dev-api-app/src/wrangler-dev.mjs
- fixtures/wrangler-dev-api-app/wrangler.toml
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/miniflare-cli/index.ts
Added a warning: 
Things for follow-up releases:
- `unstable_dev` should return an object so you can just do:
```js
const worker = await wrangler.unstable_dev(...)
const resp =  await worker.fetch()
```
-  we should make miniflare notify wrangler that it's ready for requests (the remote dev worker supports this already)
- (for future us to deal with): split wrangler into `@wrangler/core` and `@wrangler/renderer` (or something) so prop-drilling to reach the core isn't necessary
> feat: export a dev function that folks can use in their own scripts to invoke wrangler dev

- .changeset/strange-cameras-hammer.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/sites.tsx
The maximum _request_ size for a batch upload is 100 MB. We were previously calculating the upload key value to be under _100 MiB_. Further, with a few bytes here and there, the size of the request can exceed 100 MiB. So this fix calculate using Mb instead of MiB, but also brings down our own limit to 98 MB so there's some wiggle room for uploads.
Fixes https://github.com/cloudflare/wrangler2/issues/1367
> fix: keep site upload batches under 98 mb

- .changeset/khaki-clocks-shop.md
- packages/wrangler/bin/wrangler.js
We'd previously had some funny behaviour with undici clashing with node's own fetch supporting classes, and had turned off node's fetch implementation. Recent updates to undici appear to have fixed the issue, so let's turn it back on.
Closes https://github.com/cloudflare/wrangler2/issues/834
> chore: enable node's experimental fetch flag

- .changeset/rude-queens-listen.md
- packages/wrangler/src/__tests__/pubsub.test.ts
- packages/wrangler/src/pubsub/pubsub-commands.tsx
This adds support for managing pubsub namespaces and brokers (https://developers.cloudflare.com/pub-sub/)
---
This PR is just to add the missing changeset, and renames the commands for some consistency. Will land after CI passes
> Added support for pubsub namespace (via @elithrar in https://github.com/cloudflare/wrangler2/pull/1314)

- .changeset/eighty-otters-hide.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/worker-namespace.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/worker-namespace.ts
Hide whitespace changes for this review!
---
This adds commands to create, delete, list, and get info for "worker namespaces" (name to be bikeshed-ed). This is based on work by @aaronlisman in https://github.com/cloudflare/wrangler2/pull/1310.
> feat: commands to manage worker namespaces

- .changeset/silver-elephants-complain.md
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/dev/remote.tsx
Previously, we would be creating a fresh session for every script change during remote dev. While this _worked_, it makes iterating slower, and unnecessarily discards state. This fix makes it so we create only a single session for remote dev, and reuses that session on every script change. This also means we can use a single script id for every worker in a session (when a name isn't already given). Further, we also make the prewarming call of the preview space be non-blocking.
Fixes https://github.com/cloudflare/wrangler2/issues/1191
> fix: create a single session during remote dev

- .changeset/rotten-candles-visit.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
This fix renames the `--no-build` cli arg to `--no-bundle`. `no-build` wasn't a great name because it would imply that we don't run custom builds specified under `[build]` which isn't true. So we rename closer to what wrangler actually does, which is bundling the input. This also makes it clearer that it's a single file upload.
> fix: rename `--no-build` to `--no-bundle`

- .changeset/quiet-olives-fry.md
- fixtures/local-mode-tests/package.json
- fixtures/local-mode-tests/src/basicModule.ts
- fixtures/local-mode-tests/tests/unstableDev.test.ts
- fixtures/local-mode-tests/wrangler.d.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/local.tsx
Disable whitespaces for this change
Closes #1383
Closes #1384
Closes #1385
> feat: implement fetch, and write our first integration test

- .changeset/silent-ears-jam.md
- packages/wrangler/src/__tests__/config-cache-without-cache-dir.test.ts
- packages/wrangler/src/config-cache.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/is-interactive.ts
- packages/wrangler/src/user/choose-account.tsx
- packages/wrangler/src/user/user.tsx
This adds caching for account id fetch/selection for all wrangler commands.
Currently, if we have an api/oauth token, but haven't provided an account id, we fetch account information from cloudflare. If a user has just one account id, we automatically choose that. If there are more than one, then we show a dropdown and ask the user to pick one. This is convenient, and lets the user not have to specify their account id when starting a project.
However, if does make startup slow, since it has to do that fetch every time. It's also annoying for folks with multiple account ids because they have to pick their account id every time.
So we now cache the account details into `node_modules/.cache/wrangler` (much like pages already does with account id and project name).
This patch also refactors …
> feat: cache account id selection

- .changeset/sweet-wasps-clean.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/worker.ts
This feature les you bind a worker to a dynamic dispatch namespaces, which may have other workers bound inside it. (See https://blog.cloudflare.com/workers-for-platforms/). Inside your `wrangler.toml`, you would add
```toml
[[worker_namespaces]]
binding = 'dispatcher' # available as env.dispatcher in your worker
namespace = 'namespace-name' # the name of the namespace being bound
```
Based on work by @aaronlisman in https://github.com/cloudflare/wrangler2/pull/1310
> feat: bind a worker with `[worker_namespaces]`

- .changeset/curly-ladybugs-repeat.md
- packages/wrangler/bin/wrangler.js
I accidentally left in a message that would print "Delegating to locally-installed wrangler@{version}".
This was for debugging, and really wrangler should just do this without confusing the user.
> Remove delegation message

- .changeset/odd-cats-turn.md
- packages/wrangler/src/entry.ts
Allow specifying `[assets]` in a wrangler.toml file.
> Check for assets in config file as well as CLI arg

- package-lock.json
- package.json
- packages/create-workers-app/package.json
- packages/jest-environment-wrangler/package.json
- packages/prerelease-registry/package.json
- packages/wrangler/package.json
- packages/wranglerjs-compat-webpack-plugin/package.json
Using [prettier-plugin-packagejson](https://github.com/matzkoh/prettier-plugin-packagejson),
we can keep package.json files organized. I've kind of had a headache
sometimes trying to find stuff in wrangler's package.json, so I thought
this might help.
> Sort package.json files during prettier runs

- packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
- packages/wrangler/src/__tests__/https-options.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/https-options.ts
- packages/wrangler/src/user/user.tsx
- packages/wranglerjs-compat-webpack-plugin/src/__tests__/helpers/mock-config-dir.ts
- packages/wranglerjs-compat-webpack-plugin/src/__tests__/index.spec.ts
When mocking out `homedir` we were leaking data between tests.
This results in tests that were passing when they shouldn't and vice versa.
Now we always mock `homedir` and do so in a way that is contained to the test being run.
Affected tests have been cleaned up as necessary.
> test: fix leakage between tests

- packages/wrangler/package.json
We have a problem where types aren't being emitted correctly, and it's breaking the build on some machines, blocking folks from iterating on wrangler. This fix removes that step from the build right now while we can fix it.
No changeset here for the moment.
--- 
cc @caass
> fix: disable emitting types to fix the build

- .changeset/strong-bulldogs-check.md
- packages/wrangler/src/package-manager.ts
The environment variable `npm_config_user_agent` can be used to guess the package manager
that was used to execute wrangler. It's imperfect (just like regular user agent sniffing!)
but the package managers we support all set this property:
- [npm](https://github.com/npm/cli/blob/1415b4bdeeaabb6e0ba12b6b1b0cc56502bd64ab/lib/utils/config/definitions.js#L1945-L1979)
- [pnpm](https://github.com/pnpm/pnpm/blob/cd4f9341e966eb8b411462b48ff0c0612e0a51a7/packages/plugin-commands-script-runners/src/makeEnv.ts#L14)
- [yarn](https://yarnpkg.com/advanced/lifecycle-scripts#environment-variables)
- [yarn classic](https://github.com/yarnpkg/yarn/pull/4330)
Closes #1202
> Check `npm_config_user_agent` to guess a user's package manager

- .changeset/forty-chefs-reflect.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/kv.ts
It's now possible to express metadata inline without a need to use the `kv:bulk put` with single entry
Closes #1441
> Implementation of support for `--metadata` in `kv:key put`

- .changeset/silly-flowers-yawn.md
- packages/wrangler/templates/static-asset-facade.js
This prevents the abundance of NotFoundErrors being unnecessaryily logged.
> polish: tweak static assets facade to log only real errors

- .changeset/clean-dolls-breathe.md
- packages/wrangler/src/pages/upload.tsx
We ran out of memory while walking and uploading the files due to us loading all the files content into memory. This PR moves it so that we _only_ load the content during the upload.
This is slower but will prevent anymore OOMing. We can make this more efficient later.
> Fixed Wrangler OOMing during Pages upload

- .changeset/pretty-taxis-study.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
Log some metadata about the worker after it has been published.  This is only printed if you request a log level of `log` or lower.
Not all workers will get all three of these fields returned, so only print the ones that are part of the response.
> Log additional information about the worker after publishing

- packages/wrangler/src/__tests__/pages.test.ts
The upload requests are run in parallel, so under some circumstances they can end up being completed in a different order.
The tests now are not affected by the order of the requests.
The page upload functionality uses `setTimeout()` with a 1 sec (or more) delay. This is now mocked to use `setImmediate()` to speed up these tests.
> test: improve speed and resilience of pages upload tests

- .changeset/spicy-flowers-itch.md
- packages/wrangler/src/pages/upload.tsx
Currently we have a linear backoff when retrying HTTP calls to our upload endpoint. We're seeing some instances of rate limits that users are hitting. An exponential backoff here should tame that for the moment.
> fix: Exponentially backoff when retrying a call to /upload

- .changeset/heavy-comics-sell.md
- .github/workflows/test-old-node-error.yml
- fixtures/local-mode-tests/package.json
- package-lock.json
- packages/wrangler/bin/wrangler.js
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/test-old-node-version.js
Our entrypoint for wrangler (`bin/wrangler.js`) needs to run in older versions of node and log a message to the user that they need to upgrade their version of node. Sometimes we use synatx in this entrypoint that doesn't run in older versions of node. crashing the script and failing to log the message. This fix adds a test in CI to make sure we don't regress on that behaviour (as well as fixing the current newer syntax usage)
Fixes https://github.com/cloudflare/wrangler2/issues/1443
> fix: Fail intentionally on older versions of node.

- .changeset/twenty-spiders-itch.md
- .github/workflows/prereleases.yml
- .github/workflows/release.yml
Previously, we were including the key in the "build" step of the release job.
But this is only there to check that the build doesn't fail.
The build is re-run inside the publish step, which is part of the "changeset" step.
Now, we include the key in the "changeset" step to ensure it is there in the build that is published.
> ci: ensure that the SPARROW_SOURCE_KEY is included in release builds

- .changeset/khaki-tigers-raise.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/metrics/metrics-config.ts
- packages/wrangler/src/metrics/metrics-dispatcher.ts
- packages/wrangler/src/metrics/send-event.ts
- packages/wrangler/src/pages/build.tsx
- packages/wrangler/src/pages/deployments.tsx
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/src/pages/projects.tsx
- packages/wrangler/src/pages/publish.tsx
- packages/wrangler/src/pubsub/pubsub-commands.tsx
- packages/wrangler/src/user/user.tsx
- packages/wrangler/src/whoami.tsx
- packages/wrangler/src/worker-namespace.ts
The new metrics usage capture may interact with the user if they have not yet set their metrics permission.
Sending metrics was being done concurrently with other commands, so there was a chance that the metrics UI broke the other command's UI.
Now we ensure that metrics UI will happen synchronously.
> fix: ensure that metrics user interactions do not break other UI

- .changeset/giant-roses-tan.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/remote.tsx
During a refactor, we missed enabling the inspector by default in local mode. We also broke the logic that detects the inspector url exposed by the local server. This patch passes the argument correctly, fixes the detection logic. Further, it also lets you disable the inspector altogether with `--inspect false`, if required (for both remote and local mode).
Fixes https://github.com/cloudflare/wrangler2/issues/1436
> fix: enable debugger in local mode

- .changeset/slow-news-tease.md
- packages/wrangler/src/bundle.ts
In https://github.com/cloudflare/wrangler2/pull/992, we added a dev-only helper that would warn when using `fetch()` in a manner that wouldn't work as expected (because of a bug we currently have in the runtime). We did this by injecting a file that would override usages of `fetch()`. When using pnp style package managers like yarn, this file can't be resolved correctly. So to fix that, we extract it into the temporary destination directory that we use to build the worker (much like a similar fix we did in https://github.com/cloudflare/wrangler2/pull/1154)
Reported at https://github.com/cloudflare/wrangler2/issues/1320#issuecomment-1188804668
> fix: add `fetch()` dev helper correctly for pnp style package managers

- .changeset/lucky-poems-smile.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/index.tsx
Fixes https://github.com/cloudflare/wrangler2/issues/1494
Implemented feedback similar to `wrangler r2 bucket create`
> fix: no feedback on `wrangler kv:namespace delete`

- .changeset/hip-swans-melt.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/user/choose-account.tsx
When using an api token, sometimes the call to get a user's membership details fails with a 9109 error. In this scenario, a workaround to skip the membership check is to provide an account_id in wrangler.toml or via CLOUDFLARE_ACCOUNT_ID. This bit of polish adds this helpful tip into the error message.
Reported in https://github.com/cloudflare/wrangler2/issues/1422
> polish: recommend using an account id when user details aren't available

- packages/wrangler/package.json
We use `npm run dev` inside `packages/wrangler` to continuously build wrangler on any code change. This is useful when we're testing wrangler in any of the fixtures. However, it ends whenever we make a type error, which is common when experimenting, and interrupts the flow. It's better instead to log the error and carry on building as usual. This fix adds the flag to the concurrently task runner that enables this behaviour.
> chore: don't kill `npm run dev` if any subtask fails

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/d1.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/release.yml
We shouldn't restore an older cache if we don't find a matching one (for node_modules in github actions). We're also having issues with caches in general. Disabling all node_modules caching til lwe figure out a proper solution.
> chore: disable caching node_modules in github actions

- packages/wrangler/scripts/bundle.ts
Missed adding this in https://github.com/cloudflare/wrangler2/pull/1479, it makes sure we read process.env.NODE_ENV when we're doing a build of wrangler itself.
--- 
Skipping a changeset for this one.
> chore: read NODE_ENV when making a wrangler build

- .changeset/cuddly-rocks-pump.md
- packages/wrangler/src/index.tsx
Currently in tests, we see a bunch of logspam from yargs about "version" being a reserved word, this patch removes that spam.
> fix: don't log version spam in tests

- .changeset/shy-tips-decide.md
- packages/wrangler/src/create-worker-preview.ts
When we quit wrangler dev, any inflight requests are cancelled. Any error handlers for those requests are ignored if the request was cancelled purposely. The check for this was missing for the prewarm request for a dev session, and this patch adds it so it dorsn't get logged to the terminal.
> polish: don't log an error message if wrangler dev startup is interrupted

- .changeset/good-clouds-help.md
- packages/wrangler/src/bundle.ts
In dev, we inject a patch for `fetch()` to detect bad usages. This patch is copied into the destination directory before it's used. esbuild appears to have a bug where it thinks a dependency has changed so it restarts once in local mode. The fix here is to copy the file to inject into a separate temporary dir.
Fixes https://github.com/cloudflare/wrangler2/issues/1515
> fix: prevent local mode restart

- .changeset/thick-pens-cheat.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/pages/dev.tsx
feat: Adds the `--experimental-enable-local-persistence` option to `wrangler pages dev`
Previously, this was implicitly enabled and stored things in a `.mf` directory. Now we move to be in line with what `wrangler dev` does, defaults disabled, and stores in a `wrangler-local-state` directory.
> '--experimental-enable-local-persistence' for 'wrangler pages dev'

- .changeset/fifty-paws-cry.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
feat: publish full url on `wrangler publish` for workers.dev workers
When the url is printed out on `wrangler publish`, the full url is printed out so that it can be accessed from the terminal easily by doing cmd+click. Implemented only for workers.dev workers.
Resolves https://github.com/cloudflare/wrangler2/issues/1530
> feat: publish full url on wrangler publish for workers.dev workers

- .changeset/new-poems-tan.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/templates/static-asset-facade.js
The facade for static assets doesn't export any exports from the entry point, meaning Durable Objects will fail. This fix adds all exports to the facade's exports.
> fix: export durable objects correctly when using `--assets`

- .github/workflows/pullrequests.yml
- fixtures/local-mode-tests/package.json
- fixtures/node-app-pages/package.json
- fixtures/pages-functions-app/package.json
- fixtures/remix-pages-app/package.json
- package.json
- packages/wrangler/package.json
Test coverage was setup in the package manifest which caused it to run anytime Jest ran
inside of that workspace. The config is now removed and replaced with a custom script "test:ci" that is
also checked for at the monorepo package manifest level.
> chore: test coverage

- .github/workflows/codecov-context.yml
CodeCov requires the context to be kept up to date for a reference with current branches. This change adds
a workflow that runs on PR's that are closed and merged to main then uploads test coverage from main, so that subsequent PR's have the latest test context for comparison.
> chore: CodeCov Main branch context

- .changeset/loud-shoes-heal.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/templates/format-dev-errors.ts
- packages/wrangler/templates/serve-static-assets.ts
This adds an internal mechanism for applying multiple "middleware"/facades on to workers. This lets us add functionality during dev and/or publish, where we can modify requests or env, or other ideas. (See https://github.com/cloudflare/wrangler2/issues/1466 for actual usecases)
As part of this, I implemented a simple facade that formats errors in dev. To enable it you need to set an environment variable `FORMAT_WRANGLER_ERRORS=true`. This _isn't_ a new feature we're shipping with wrangler, it's simply to demonstrate how to write middleware. We'll probably remove it in the future.
> internal: middleware for modifying worker behaviour

- codecov.yml
moved informational "true"  into the coverage context of config for codecov.
This according to their docs should be non-blocking
See: https://docs.codecov.com/docs/commit-status\#informational
Tested this on a fork, branch context was strange with using a PR from the original repo. Seemed to have resolved the issue.
> chore: CodeCov non-blocking

- .changeset/thirty-pianos-leave.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
Couple things cleaned up here:
Originally the usage of the /domains api (for publishing to custom
domains) was a bit clumsy: we would attempt to optimistically publish,
but the api would eagerly fail with specific error codes on why it
occurred. This made for some weird control flow for retries with
override flags, as well as fragile extraction of error messages.
Now we use the new /domains/changeset api to generate a changeset of
actions required to get to a new state of custom domains, which informs
us up front of which domains would need to be updated and overridden,
and we can pass flags as needed. I do make an extra hop back to the api
to lookup what the custom domains requiring updates are already attached
to, but given how helpful I imagine that to be, I'm for it.
I also updated …
> Touch up publishing to custom domains

- .changeset/healthy-elephants-vanish.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/templates/serve-static-assets.ts
This adds cache control options to `config.assets`. This is already supported by the backing library (`@cloudflare/kv-asset-handler`) so we simply pass on the options at its callsite.
Additionally, this adds a configuration field to serve an app in "single page app" mode, where a root index.html is served for all html/404 requests (also powered by the same library).
--- 
This seems to work, but using the preview builds to take it through the paces as well. Open for review!
> feat: add cache control options to `config.assets`

- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
I noticed this is unused locally, only used in remote.tsx
> chore: remove unused var

- .changeset/four-onions-divide.md
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/__tests__/whoami.test.tsx
- packages/wrangler/src/user/user.tsx
- packages/wrangler/src/whoami.tsx
Often users experience issues due to tokens not having the correct permissions associated with them (often due to new scopes being created for new products). With this, we print out a list of permissions associated with OAuth tokens with the `wrangler whoami` command to help them debug for OAuth tokens. We cannot access the permissions on an API key, so we direct the user to the location in the dashboard to achieve this.
We also cache the scopes of OAuth tokens alongside the access and refresh tokens in the .wrangler/config file to achieve this.
Currently unable to implement https://github.com/cloudflare/wrangler2/issues/1371 - instead directs the user to the dashboard.
Resolves https://github.com/cloudflare/wrangler2/issues/1540
> feat: describe current permissions in `wrangler whoami`

- .changeset/quick-monkeys-exercise.md
- packages/wrangler/README.md
Updated wrangler readme providing additional context on configuration, deep link to `init` and fixing old link to beta docs.
> chore: Documentation Links in README.md

- .changeset/slimy-yaks-think.md
- packages/wrangler/src/pages/dev.tsx
If both `directory` and `command` are specified for `wrangler
pages dev`, throw an error.
The previous behavior was to silently ignore the `command` argument.
Closes #1543.
> fix: Throw error if both `directory` and `command` are specified for `pages dev`

- fixtures/node-app-pages/tests/index.test.ts
We have a test that flakes a lot, so I'm disabling it. Filed https://github.com/cloudflare/wrangler2/issues/1571 for fixing/re-enabling it
> chore: disabling a flaky test

- .changeset/thin-avocados-trade.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/templates/service-bindings-module-facade.js
A similar fix to https://github.com/cloudflare/wrangler2/pull/1539, this exports correctly when using service bindings in dev.
> fix: export durable object bindings when using service bindings in dev

- .changeset/young-buckets-provide.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/inspect.ts
feat: source maps support in `wrangler dev` remote mode
Previously stack traces from runtime errors in `wrangler dev` remote mode, would give unhelpful stack traces from the bundled build that was sent to the server. Here, we use source maps generated as part of bundling to provide better stack traces for errors, referencing the unbundled files.
Resolves https://github.com/cloudflare/wrangler2/issues/1509
> feat: support source maps in wrangler dev remote mode

- .changeset/sixty-pots-heal.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/templates/first-party-worker-module-facade.ts
This introduces configuration for marking a worker as a "first party" worker, to be used inside cloudflare to develop workers. It also adds a facade that's applied for first party workers in dev.
> feat: `config.first_party_worker` + dev facade

- .changeset/green-queens-fry.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
In previous Wrangler 1, there was a legacy configuration that was considered a bug and removed.
Before it was removed, tutorials, templates, blogs, etc... had utlized that configuration property
to handle this in Wrangler 2 we will throw a blocking error that tell the user to utilize kv_namespaces
resolves #1421
> feat: legacy kv-namespace not supported

- .changeset/heavy-plants-jump.md
- packages/wrangler/src/inspect.ts
Following on from https://github.com/cloudflare/wrangler2/pull/1535, using new functionality from esbuild v0.14.50 of generation of `names` field in generated source maps, we output the original function name in the stack trace.
> feat: source-map function names in stack trace

- .changeset/serious-deers-applaud.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/templates/service-bindings-module-facade.js
This fix makes sure the multiworker dev facade is applied to the input worker only where there are other wrangler dev instances running that are bound to the input worker. We also make sure we don't apply it when we already have a binding (like in remote mode).
> fix: apply multiworker dev facade only when required

- .changeset/flat-foxes-dress.md
- .changeset/flat-keys-teach.md
- .changeset/shy-walls-sparkle.md
- .changeset/tricky-rules-thank.md
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/metrics/index.ts
- packages/wrangler/src/metrics/metrics-dispatcher.ts
- packages/wrangler/src/metrics/metrics-usage-headers.ts
- packages/wrangler/src/metrics/send-event.ts
- packages/wrangler/src/pages/deployments.tsx
- packages/wrangler/src/pages/publish.tsx
- packages/wrangler/src/publish.ts
- packages/wrangler/src/worker.ts
- feat: add platform/os to usage metrics events
- feat: send whether a Worker is using TypeScript or not in usage events
- fix: rename pages metrics events to align better with the dashboard
- feat: add metricsEnabled header when deploying a worker
> Sparrow events extras

- .changeset/soft-seahorses-cough.md
- packages/wrangler/src/pages/constants.ts
- packages/wrangler/src/pages/upload.tsx
`wrangler pages publish` sometimes fails because /check-missing fails (usually with 5XX errors.)
This will retry it with the same logic as upload calls do.
> fix: Retry check-missing call to make wrangler pages publish more reliable

- .changeset/fifty-schools-check.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/module-collection.ts
Ref: https://github.com/cloudflare/wrangler2/issues/1504#issuecomment-1194301983
`wrangler pages dev` uses the tmp directory to build functions, which can contain files with a '+' character in their name, which is a key character in regular expressions. This issue was also reported in the cloudflare developers server, at [this message](https://discord.com/channels/595317990191398933/799437470004412476/1001176224443412600)
May be worth escaping all regex characters?
> fix: Invalid regular expression error

- .changeset/lovely-pets-tie.md
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/index.ts
- packages/wrangler/src/tail/printing.ts
`wrangler tail --format pretty` now supports receiving events from [Durable Object Alarms](https://developers.cloudflare.com/workers/learning/using-durable-objects/#alarms-in-durable-objects), and will display the time the alarm was triggered.
Additionally, any future unknown events will simply print "Unknown Event" instead of crashing the `wrangler` process.
Closes #1519
> Add support for Alarm Events in `wrangler tail`

- .changeset/old-jobs-drum.md
- package.json
Currently, on a pull request, prettier will test changesets, and ensure they match the desired formatting. It will not, however, fix these changesets when you run `prettify`. This PR now includes changesets in the prettify command to ensure that they are correct
This issue can be seen in PRs like [#2649](https://github.com/cloudflare/wrangler2/pull/2649) , where checks failed based on the changeset file
> chore: make prettify also fix changesets

- .changeset/four-bags-train.md
- packages/wrangler/src/pages/build.tsx
- packages/wrangler/src/pages/constants.ts
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/src/pages/functions/routes-consolidation.test.ts
- packages/wrangler/src/pages/functions/routes-consolidation.ts
- packages/wrangler/src/pages/functions/routes-transformation.test.ts
- packages/wrangler/src/pages/functions/routes-transformation.ts
Example: `["/foo/:name", "/foo/bar"] => ["/foo/*"]`
Also fixed buildFunctions in a few places where we weren't passing `directory`
> patch: Consolidate redundant routes when generating _routes.generated.json

- .changeset/beige-mirrors-clap.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/inspect.ts
Passing `sourceRoot` as `entryDirectory` allows us to reference the original directory when outputting errors in remote dev mode, but unfortunately it breaks source resolution when using a debugger in local mode, since the `source` paths are resolved relative to `sourceRoot`—but `source` paths are set relative to the temporary directory we build in, not the original source root.
We can fix the latter without breaking the former by setting `sourceRoot` to `destination` (the temporary build directory). When logging errors, we rely on `source-map` to properly resolve the source file’s absolute path, rather than trying to rebuild the pathname ourselves by removing `sourceRoot` from `source`, which maintains the original desired behaviour.
I tested this locally with the following file:
```js …
```
> Set `sourceRoot` to `destination` in local dev mode

- .changeset/witty-planets-refuse.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/pages/dev.tsx
- Add a new argument `--ip` for `wrangler pages dev`, defaults to `0.0.0.0`
- Change default IP of `wrangler dev` to `0.0.0.0` instead of `localhost`
```
> wrangler pages dev --help
wrangler pages dev [directory] [-- command..]
Develop your full-stack Pages application locally
Positionals:
directory  The directory of static assets to serve  [string]
command    The proxy command to run  [string]
Flags:
-h, --help     Show help  [boolean]
-v, --version  Show version number  [boolean]
Options:
--local                                  Run on my machine  [boolean] [default: true]
--ip                                     The IP address to listen on  [string] [default: "0.0.0.0"]
--port                                   The port to listen on (serve from)  [number] [default: 8788]
--proxy …
```
> feat: add --ip argument for `wrangler pages dev` & set default IP to `0.0.0.0`

- .changeset/olive-needles-whisper.md
- fixtures/external-durable-objects-app/a/index.ts
- fixtures/external-durable-objects-app/a/wrangler.toml
- fixtures/external-durable-objects-app/b/index.ts
- fixtures/external-durable-objects-app/b/wrangler.toml
- fixtures/external-durable-objects-app/c/index.ts
- fixtures/external-durable-objects-app/c/wrangler.toml
- fixtures/external-durable-objects-app/package.json
- fixtures/external-durable-objects-app/tests/index.test.ts
- fixtures/external-durable-objects-app/tsconfig.json
- package-lock.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/dev-registry.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/miniflare-cli/index.ts
feat: Durable Object multi-worker bindings in local dev.
Building on [the recent work for multi-worker Service bindings in local dev](https://github.com/cloudflare/wrangler2/pull/1503), this now adds support for direct Durable Object namespace bindings.
A parent (calling) Worker will look for child Workers (where the Durable Object has been defined) by matching the `script_name` configuration option with the child's Service name. For example, if you have a Worker A which defines a Durable Object, `MyDurableObject`, and Worker B which references A's Durable Object:
```toml
name = "A"
[durable_objects]
bindings = [
{ name = "MY_DO", class_name = "MyDurableObject" }
]
```
```toml
name = "B"
[durable_objects]
bindings = [
{ name = "REFERENCED_DO", class_name = "MyDurableObject", script_name = …
```
> Durable Object multi-worker bindings

- .changeset/nine-ladybugs-confess.md
- .prettierignore
- fixtures/pages-functions-app/.gitignore
- fixtures/remix-pages-app/.gitignore
- packages/wrangler/src/pages/build.tsx
- packages/wrangler/src/pages/constants.ts
- packages/wrangler/src/pages/deployments.tsx
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/src/pages/functions/routes-transformation.test.ts
- packages/wrangler/src/pages/functions/routes-transformation.ts
- packages/wrangler/src/pages/publish.tsx
- packages/wrangler/src/pages/types.ts
- packages/wrangler/src/pages/upload.tsx
This controls the output path of the _routes.json file. Also moves _routes.json generation to tmp directory during functions build + publish
Also removes the concept of `_routes.generated.json` and instead moves the generated routes to a temporary file
> Add output-routes-path to functions build

- .changeset/thick-weeks-pump.md
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/filters.ts
- packages/wrangler/src/tail/printing.ts
While the exception for 'Worker exceeded memory limits' gets logged
correctly when tailing, the actual status wasn't being counted as an
error, and was falling through a switch case to 'unknown'
This ensures filtering and logging reflects that status correctly
> Support 'exceededMemory' error status

- .changeset/curly-eagles-vanish.md
- packages/wrangler/templates/service-bindings-module-facade.js
Added pathname to the constructed URL.
resolves #1598
> fix: service bindings + wrangler dev ignores pathname when making a request

- .changeset/sharp-ligers-try.md
- fixtures/service-bindings-app/package.json
- fixtures/service-bindings-app/tests/index.test.ts
- package-lock.json
- packages/wrangler/src/miniflare-cli/index.ts
- packages/wrangler/templates/service-bindings-module-facade.js
- packages/wrangler/templates/service-bindings-sw-facade.js
> Fix SW and Durable Object request URLs made over the service registry

- package-lock.json
- package.json
Upgrading Jest to latest major version. 
See for details: https://jestjs.io/blog/2022/04/25/jest-28
> chore: Jest upgrade to 28

- .changeset/heavy-timers-matter.md
- packages/wrangler/src/pages/constants.ts
- packages/wrangler/src/pages/functions/routes-consolidation.test.ts
- packages/wrangler/src/pages/functions/routes-consolidation.ts
Rather than failing a deployment because a route is too long (>100 characters), it will now be shortened to the next available level. Eg. `/foo/aaaaaaa...` -> `/foo/*`
> fix: Consolidate routes that are over the limit to prevent failed deployments

- .changeset/blue-ladybugs-attend.md
- packages/wrangler/src/pages/dev.tsx
> fix: [windows] unable to find netstat

- .changeset/shaggy-spies-scream.md
- packages/wrangler/src/pages/build.tsx
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/src/pages/errors.ts
- packages/wrangler/src/pages/publish.tsx
Building pages functions with no valid handlers would result in a Functions script containing no routes, often because the user is using the functions directory for something unrelated.
This will now warn when no routes are found, and skip adding an empty Functions worker to the deployment.
Internal-use only: `pages functions build` will exit with code `156` if no routes are found.
**Example** with `wrangler pages dev` with empty `functions` dir:
**Example** with `wrangler pages publish` with empty `functions` dir:
> fix: Warn when Pages Functions have no routes

- .changeset/six-needles-begin.md
- packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/init.ts
Workaround for handling multipart/form-data slicing off top and bottom boundaries.
multipart/formdata not supported currently in Undici https://github.com/nodejs/undici/issues/974
> 🚀 feat: download of Worker script `--from-dash`

- .changeset/khaki-ants-shave.md
- packages/wrangler/src/dev/dev.tsx
> fix: Open browser button on windows

- .changeset/perfect-balloons-invite.md
- fixtures/external-durable-objects-app/tests/index.test.ts
- fixtures/service-bindings-app/tests/index.test.ts
- packages/wrangler/src/pages/publish.tsx
Closes #1599
Assigning Natalie as she suggested the message. 
Had to skip 2 flaky DO tests that were causing it to repetitively fail
> feat: pages publish - log special files being uploaded

- .changeset/spicy-candles-warn.md
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/pages/dev.tsx
Fixes #495
---
feat: Adds `--compatibility-date` and `--compatibility-flags` to `wrangler pages dev`
Soon to follow in production.
> `wrangler pages dev` compat date and flags

- .changeset/quiet-readers-smell.md
- package-lock.json
- package.json
- packages/wrangler/package.json
Related: #1674 
Not sure if a changeset is needed for this? Happy to remove if not desired
> chore: switch to rimraf & cross-env for windows support

- .changeset/cool-peaches-boil.md
- fixtures/pages-functions-app/functions/regex_chars/my-file.ts
- fixtures/pages-functions-app/tests/index.test.ts
- packages/wrangler/templates/pages-template-plugin.ts
- packages/wrangler/templates/pages-template-worker.ts
Closes #1685
Currently, if you have a file such as `functions/*.ts`, pages attempts to run path-to-regex on this, and this will fail, as it assumes it's a regex character (it shouldn't be). This results in an `Unexpected MODIFIER at 1, expected END.` error. This PR correctly escapes these characters to solve the issue (confirmed fix from Alastair)
> fix: escape function path regex chars

- .changeset/sour-tables-lay.md
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/proxy.ts
You can now see more detailed information about HTTP requests that Wrangler is making by setting the `WRANGLER_LOG` environment variable to `debug`. E.g. `WRANGLER_LOG=debug npx wrangler dev`.
> feat: add debug logging to CF API requests and remote dev worker requests

- .changeset/nasty-apricots-wash.md
- packages/wrangler/src/pages/dev.tsx
Currently, if the process pages dev is proxying exists or crashes, pages dev does not clean it up, and attempts to continue proxying requests to it, resulting in it throwing 502 errors. This fixes that behaviour to make wrangler exit with the code the child_process exits with.
Possibly actually fixes #1544
> fix: pages dev process exit when proxied process exits

- .changeset/twelve-peaches-punch.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2.ts
The old PUT endpoint was removed in favour of POST `{ "name": "<bucket>" }`
> Fix R2 create bucket endpoint

- .changeset/gold-sheep-repeat.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
Close #1660
In `packages/wrangler/src/config/validation.ts` I originally tried to get `isRequiredProperty` to type narrow `object`. This may be impossible https://github.com/microsoft/TypeScript/issues/31755#issuecomment-498669080 so I casted it manually.
> fix: check for nonempty kv id and r2 bucket_name

- .changeset/late-laws-applaud.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
Because we'd used a default for 0.0.0.0 for the `--ip` flag, `wrangler dev` was overriding the value specified in `wrangler.toml` under `dev.ip`. This fix removes the default value (since it's being set when normalising config anyway).
Fixes https://github.com/cloudflare/wrangler2/issues/1714
> fix: use `config.dev.ip` when provided

- .changeset/ninety-books-hope.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/zones.ts
An initial stab at https://github.com/cloudflare/wrangler2/issues/492, following the approach outlined there:
> 1. Checking if the positional argument passed to wrangler tail <url | name> resembles a URL
> 1. Determining the zone ID from the URL (e.g. via [getZoneForRoute](https://github.com/cloudflare/wrangler2/blob/main/packages/wrangler/src/zones.ts#L29))
> 1. Calling [GET zone/:zone_id/workers/routes](https://api.cloudflare.com/#worker-routes-list-routes)
> 1. Finding the given URL in the returned routes
> 1. Using the worker name associated with that route to plug in to the existing tail infrastructure
Some notes:
- Distinguishing between a route and a worker name is done by checking for the presence of a `.` character, following confirmation that that will suffice.
- I've defined a …
> Support passing routes as well as worker names to `wrangler tail`

- .changeset/spicy-icons-eat.md
- package-lock.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.7.1`, fixing a couple issues @vlovich found. See the [changelog here](https://github.com/cloudflare/miniflare/releases/tag/v2.7.1). The changeset also mentions the [upgrade to `2.7.0`](https://github.com/cloudflare/miniflare/releases/tag/v2.7.0) merged in as part of #1691.
> chore: upgrade `miniflare` to `2.7.1`

- .changeset/hungry-lemons-exercise.md
- packages/wrangler/src/bundle.ts
Thanks Dario for the report!
---
fix: Multiworker and static asset dev bug preventing both from being used
There was previously a collision on the generated filenames which resulted in the generated scripts looping and crashing in Miniflare with error code 7. By renaming one of the generated files, this is avoided.
> Fix multiworker and assets bug

- .changeset/mean-actors-beam.md
- packages/wrangler/src/dev/remote.tsx
What it looks like when this kicks in:
```
⎔ Detected changes, restarted server.
Total Upload: 0.19 KiB / gzip: 0.16 KiB
Preview token expired, fetching a new one
⎔ Detected changes, restarted server.
Total Upload: 0.19 KiB / gzip: 0.16 KiB
Script modified; context reset.
16:29:38 GET / 200
16:29:38 GET /favicon.ico 200
```
Closes #1446
> fix: rerun useEffect when we detect error code 10049

- .prettierignore
- packages/wrangler/src/__tests__/helpers/mock-get-zone-from-host.ts
- packages/wrangler/src/__tests__/helpers/mock-known-routes.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
The tail.test suite was importing a helper from publish.test, which was also declaring all the tests in that suite. This fix extracts those helpers so they can be imported and used cleanly. Shaves a few seconds off when running all tests too.
--- 
No changeset here because it doesn't affect any code.
> chore: dedupe running publish.test tests twice

- .github/workflows/queues.yml
Like it says, for some internal work we have.
> chore: publish `queues` branch to `wrangler@queues`

- .changeset/good-ads-exercise.md
- package.json
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/paths.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/entry.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/paths.ts
Use `getBasePath()` when trying to specify paths to files relative to the
base of the Wrangler package directory rather than trying to compute the
path from Node.js constants like `__dirname` and `__filename`. This is
because the act of bundling the source code can move the file that contains
these constants around potentially breaking the relative path to the desired files.
Fixes #1755
> refactor: implement `getBasePath()` as a replacement for `__dirname`

- .changeset/empty-baboons-happen.md
- packages/wrangler/src/index.tsx
At the moment, it isn't clear if wrangler correctly picks up the user's proxy from environment variables.
This PR lets them know which proxy they're using, when one is configured.
> fix: let users know when we'll use their proxy for requests

- .changeset/long-kangaroos-invent.md
- package-lock.json
- packages/wrangler/package.json
Hey! 👋 This PR upgrades `miniflare` to version `2.8.1` See the [changelog for `2.8.0` here](https://github.com/cloudflare/miniflare/releases/tag/v2.8.0) and [`2.8.1` here](https://github.com/cloudflare/miniflare/releases/tag/v2.8.1). Big things in this update are queues, populated Workers Sites manifests (closing #1632), improved Web Streams runtime compatibility, and lots of other small fixes.
> chore: upgrade `miniflare` to `2.8.1`

- .changeset/tender-pianos-kick.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dialogs.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/publish.ts
Adding messaging around 'publish' informing the user
of the last Worker publish occured on dash, and how publishing from the CLI
will override that.
Messaging around 'init --from-dash' informing the user that the Worker
initialized from the dash cannot be synced from the dash again.
resolves #1737
> feat: Publish Origin Messaging

- packages/wranglerjs-compat-webpack-plugin/.npmrc
The Changeset GitHub Action expects the npmrc with the Publish token is needed for Changesets to work effectively in CI.  
Part of working on #1746
> chore: add npmrc to webpack-plugin

- .changeset/tough-beers-return.md
- packages/wrangler/src/__tests__/helpers/mock-console.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/publish.ts
- packages/wrangler/templates/middleware/common.ts
- packages/wrangler/templates/middleware/loader-modules.ts
- packages/wrangler/templates/middleware/loader-sw.ts
- packages/wrangler/templates/middleware/middleware-pretty-error.ts
- packages/wrangler/templates/middleware/middleware-scheduled.ts
A new way of registering middleware that gets bundled and executed on the edge.
Notable features:
- the same middleware functions can be used for both modules workers and service workers
- only requires running esbuild a fixed number of times, rather than for each middleware added
- exposes a way for users to add their own middlewares (potentially opening up plugins in the future)
Two example middlewares have been included and enabled:
- `middleware-scheduled.ts`: allows for triggering scheduled events from a fetch event at `/__scheduled`
- `middleware-pretty-error.ts`: replaces cloudflare 1xxx error page with a pretty error page with stack trace
**Adding middleware:**
Middleware can be added in two places:
- within wrangler allowing toggling on and off dynamically based on build settings …
> feat: new internal middleware

- .changeset/neat-queens-repair.md
- package-lock.json
- packages/pages-shared/package.json
- packages/pages-shared/src/asset-server/handler.ts
- packages/pages-shared/src/asset-server/responses.ts
- packages/pages-shared/src/asset-server/rulesEngine.ts
- packages/pages-shared/src/environment-polyfills/index.ts
- packages/pages-shared/src/environment-polyfills/miniflare.ts
- packages/pages-shared/src/environment-polyfills/types.ts
- packages/pages-shared/tsconfig.json
- packages/wrangler/src/miniflare-cli/assets.ts
- packages/wrangler/src/pages/hash.tsx
- packages/wrangler/src/pages/upload.tsx
Fixes #1001 
~Blocked by~ ~https://github.com/cloudflare/miniflare/pull/358~ ~https://github.com/cloudflare/wrangler2/pull/1795~ Ready to go! 🎉
> pages-shared 'wrangler pages dev'

- .changeset/cyan-cherries-stare.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish.ts
The check for last deployed was breaking when no available Worker was upstream to check.
fixes #1824
> fix: Publish error when no upstream Worker existed

- .changeset/slimy-scissors-study.md
- fixtures/pages-functions-app/public/_headers
- fixtures/pages-functions-app/public/_redirects
- fixtures/pages-functions-app/tests/index.test.ts
- packages/wrangler/src/miniflare-cli/assets.ts
We recently broke parsing `_headers` and `_redirects` in 2.1.0 because the logger wasn't getting it's `this` context overridden. This fixes it so we correctly log parsing messages now (and stops the Miniflare process from crashing on start-up).
> Fix _headers and _redirects

- .changeset/shaggy-chicken-peel.md
- packages/wrangler/src/create-worker-preview.ts
Adds debug logs to the exchange request which was not caught in the initial debug PR (https://github.com/cloudflare/wrangler2/pull/1712 - since it's not an internal fetch but to a users zone)
This allows us to fully debug previews :)
> Debug exchange

- .changeset/famous-chicken-design.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/index.tsx
When `wrangler secret:bulk <json>` is run, a summary is outputted at the end with the number of secrets successfully / unsuccessfully created.
Old console output:
```
🌀 Creating the secrets for the Worker "script-name"
✨ Successfully created secret for key: secret-name-1
...
🚨 Error uploading secret for key: secret-name-8
✨ Successfully created secret for key: secret-name-9
✨ Finished processing secrets JSON file
```
New console output:
```
🌀 Creating the secrets for the Worker "script-name"
✨ Successfully created secret for key: secret-name-1
...
🚨 Error uploading secret for key: secret-name-8
✨ Successfully created secret for key: secret-name-9
Finished processing secrets JSON file:
✨ 7 secrets successfully uploaded
🚨 2 secrets failed to upload
```
Closes …
> feat: summary output for `secret:bulk`

- .changeset/fair-chairs-rhyme.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/middleware.scheduled.test.ts
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/templates/middleware/middleware-scheduled.ts
Using the new middleware (https://github.com/cloudflare/wrangler2/pull/1735), we implement a way of testing scheduled workers from a fetch using `wrangler dev` in remote mode, by passing a new command line flag `--test-scheduled`. This exposes a route `/__scheduled` which will trigger the scheduled event.
```sh
$ npx wrangler dev index.js --test-scheduled
$ curl http://localhost:8787/__scheduled
```
Closes https://github.com/cloudflare/wrangler2/issues/570
> feat: testing scheduled events with `wrangler dev` remote mode

- .changeset/lemon-wolves-cover.md
- CODEOWNERS
- packages/pages-shared/package.json
- packages/pages-shared/src/asset-server/patchUrl.ts
- packages/wrangler/src/miniflare-cli/assets.ts
Missed a `URL` -> `globalURL` when refactoring this patch. Results in a recursion call stack size exceeded error on the runtime (but not Miniflare, seemingly).
> Fix patchUrl and add charset to 'Content-Type' on pages dev

- .changeset/gorgeous-moose-whisper.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/pages/dev.tsx
Added a '--log-level' flag that allows the user to specify between 'debug', 'info', 'log', 'warning', 'error', 'none' Currently 'none' will turn off all outputs in Miniflare (local mode), however, Wrangler will still output Errors.
resolves #185
> polish: loglevel flag

- .changeset/selfish-dogs-accept.md
- packages/wrangler/src/dev.tsx
Get the `path.dirname()` of `wrangler.toml` before using it as a base for `.wrangler/state`
Closes #1872
> bugfix: Closes #1872

- .changeset/lucky-fishes-invent.md
- packages/wrangler/src/__tests__/api-dev.test.ts
- packages/wrangler/src/api/dev.ts
when using `unstable_dev()`, I think we want to expose the port/address that the server has started on. The usecase is when trying to connect to the server _without_ calling `.fetch()` (example: when making a websocket connection).
> feat: expose port and address on (Unstable)DevWorker

- .changeset/witty-rice-pull.md
- packages/wrangler/templates/d1-beta-facade.js
You cannot currently use D1 in cron triggers since the scheduled function isn't exported. Cron triggers also don't fire at all since the function isn't exported
> Make sure cron triggers work with D1

- .changeset/forty-files-smoke.md
- packages/wrangler/src/proxy.ts
Closes #1652 
Uses borrowed logic from miniflare
> Log all accessible ports on remote mode dev

- .changeset/silly-birds-work.md
- .changeset/six-trees-return.md
- packages/pages-shared/src/asset-server/handler.ts
We're moving the logic of the auto-generated `Link` header above the `_headers` handling so that there is a way to forcibly unset these with
```txt
/*
! Link
```
Unfortunately, testing isn't easy as we aren't set up to properly emulate `caches` and `waitUntil`.
> Allow unsetting of Link headers using _headers

- .changeset/curvy-laws-develop.md
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/module-collection.ts
Previously, Miniflare 3 was automatically collecting modules. These collected modules were given names relative to the current working directory. Because Wrangler puts scripts in a temporary directory, these names started with `..`, which `workerd` was not happy with.
This change avoids the redundant automatic collection in Miniflare, and ensures module names are resolved relative to the temporary directory.
> Allow `--experimental-local` to be used with module workers

- .changeset/tall-radios-report.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/faye-websocket.d.ts
- packages/wrangler/src/proxy.ts
Closes #1767 
Closes https://github.com/cloudflare/wrangler2/issues/1812
Closes https://github.com/cloudflare/wrangler2/issues/1813
> fix: use node http instead of faye-websocket in proxy server

- .changeset/proud-cheetahs-kick.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/index.ts
> fix: respect variable binding type when printing

- .changeset/brave-ties-obey.md
- packages/wrangler/templates/new-worker.js
Just like in the typescript templates, and the javascript template for scheduled workers, we include `env` and `ctx` as parameters to the `fetch` export. This makes it clearer where environment variables live.
Closes https://github.com/cloudflare/wrangler2/issues/1942
> chore: add `env` and `ctx` params to `fetch` in javascript example template

- fixtures/local-mode-tests/package.json
- fixtures/local-mode-tests/tests/unstableDev.test.ts
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
This PR adds a new `experimentalLocal` option to `unstable_dev`. If enabled, this uses Miniflare 3 and the `workerd` runtime, as opposed to Miniflare 2.
> Add `--experimental-local` support to `unstable_dev`

- .changeset/blue-pots-thank.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
The Durable Objects migrations will no longer show in the auto generated config file.
> fix: fails to publish due to empty migrations

- .changeset/silly-beans-film.md
Ooops! I forgot to add a changeset for https://github.com/cloudflare/wrangler2/pull/1940. Here's one! 🙂
> Add `--experimental-local` support to `unstable_dev` changeset

- .changeset/kind-crews-sing.md
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/publish.ts
While in beta, you cannot use D1 bindings without bundling your worker as these are added in through a facade which gets bypassed when using the `no-bundle` option.
This will be removed once the bindings are no longer needing to be added using a shim.
Closes https://github.com/cloudflare/wrangler2/issues/1954
> chore: error if d1 bindings used with `no-bundle`

- packages/wrangler/src/__tests__/configuration.test.ts
Previously incorrect syntax was being used for tests in `configuration.test.ts`, and we had a set of tests that were not properly written `expect.anything` was called instead of `expect.anything()`. 
The functionality that this was testing was the `normalizeAndValidateConfig()` function, which was not behaving as the tests wanted them to by not stripping out incorrect config.
There are two obvious solutions here:
1. Make `normalizeAndValidateConfig` strip incorrect config
2. Fix the tests and make them not expect stripped config
This pr implements **(2)**. This is because we throw an error if we detect an invalid configuration, and hence never use the output of this function in that case, hence there is no need to alter or fix the configuration in the case that it is incorrect.
Closes …
> chore: remove testing config against .anything()

- .changeset/strange-clouds-judge.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.tsx
Added a space between the Emoji and description for the secret:bulk command.
> chore: Emoji space in help description

- .changeset/wet-pens-watch.md
- .github/workflows/pullrequests.yml
- fixtures/local-mode-tests/tests/unstableDev.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/proxy.ts
How to review this PR:
- Start in `fixtures/local-mode-tests/tests/unstableDev.test.ts`, where we call `unstable_dev` with `local: false`
- We then modify `packages/wrangler/src/api/dev.ts`, and make it possible to configure the `local` setting in `unstable_dev`
- We then pass that down to `packages/wrangler/src/dev.tsx`, in `startApiDev`
- We then move to `packages/wrangler/src/dev/start-server.ts`, where we pass `local` to `startDevServer`, which uses it to decide whether to start a local, or remote server
- Remote server is implemented in `packages/wrangler/src/dev/remote.tsx`
- Finally, we define a proxy server here: `packages/wrangler/src/proxy.ts`, which gets called by `startRemoteServer` above
Closes #1780
> feat: teach unstable_dev about the internet (remote mode)

- .changeset/silent-swans-relax.md
- fixtures/pages-workerjs-and-functions-app/README.md
- fixtures/pages-workerjs-and-functions-app/functions/date.ts
- fixtures/pages-workerjs-and-functions-app/functions/greeting/hello.ts
- fixtures/pages-workerjs-and-functions-app/package.json
- fixtures/pages-workerjs-and-functions-app/public/_worker.js
- fixtures/pages-workerjs-and-functions-app/public/index.html
- fixtures/pages-workerjs-and-functions-app/tests/index.test.ts
- fixtures/pages-workerjs-and-functions-app/tsconfig.json
- packages/wrangler/src/pages/dev.tsx
When using a _worker.js file, the entire `/functions` directory should be ignored – this includes its routing and middleware characteristics. Currently `wrangler pages dev` does the reverse, by prioritizing `/functions` over `_worker.js`. This commit fixes that.
> fix(pages): `wrangler pages dev` should prioritize `_worker.js`

- .changeset/nervous-boats-invent.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages/publish.tsx
When using a `_worker.js` file, the entire `/functions` directory should be ignored – this
includes its routing and middleware characteristics. Currently `wrangler pages publish` 
does the reverse, by prioritizing `/functions` over `_worker.js`. This commit fixes that.
> fix(pages): `wrangler pages publish` should prioritize `_worker.js`

- .changeset/wet-deers-bow.md
- packages/wrangler/src/init.ts
The --from-dash can now be used with the dashboard features to support moving Worker developmment to a local machine.
resolves #1783
> chore: remove hidden on --from-dash

- package.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
- packages/wranglerjs-compat-webpack-plugin/package.json
Helps computers associate the repo on GitHub with the package on npm.
> Add `repository` field to `package.json`s

- .changeset/empty-vans-sneeze.md
- packages/pages-shared/asset-server/handler.ts
Slightly relax the selectors for generating `Link` headers from `<link>` elements in Pages Early Hints feature
Previously, we'd only generate `Link` headers if the `rel="preload"` or `rel="preconnect"` matched exactly. Now, this change will generate `Link` headers if `preload` or `preconnect` appears as a whitespace-separated value in the `rel` attribute. For example, `rel="stylesheet preconnect"` is now valid.
For more info, check out [this GitHub issue on the Cloudflare Developer Docs repo](https://github.com/cloudflare/cloudflare-docs/pull/6183#issuecomment-1272007522).
---
Fixes #1999
> Slightly relax the selectors for `Link` header generation in Pages Early Hints

- .changeset/wicked-pears-train.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/zones.ts
For routes defined with `zone_name` (instead of just for routes defined with `zone_id`)
> Closes #1814: Support subdomains with `wrangler dev` 

- .changeset/gold-ghosts-give.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/routes.ts
Offer to create a workers.dev subdomain if a user needs one
Previously, when a user wanted to publish a worker to https://workers.dev by setting `workers_dev = true` in their `wrangler.toml`,
but their account didn't have a subdomain registered, we would error out.
Now, we offer to create one for them. It's not implemented for `wrangler dev`, which also expects you to have registered a
workers.dev subdomain, but we now error correctly and tell them what the problem is.
Closes #535
> Offer to create a workers.dev subdomain on `wrangler publish` if necessary

- .changeset/few-donuts-own.md
- packages/wrangler/src/publish/publish.ts
Display a more helpful error when trying to publish to a route in use by another worker.
Previously, when trying to publish a worker to a route that was in use by another worker,
there would be a really unhelpful message about a failed API call. Now, there's a much
nicer message that tells you what worker is running on that route, and gives you a link
to the workers overview page so you can unassign it if you want.
```text
⛅️ wrangler 2.1.11
Total Upload: 0.20 KiB / gzip: 0.17 KiB
✘ [ERROR] Can't publish a worker to routes that are assigned to another worker.
"test-custom-routes-redeploy" is already assigned to route
test-custom-worker.swag.lgbt
Unassign other workers from the routes you want to publish to, and then try again.
Visit …
```
> Display a more helpful error when publishing to a route in use by another worker

- .changeset/tidy-lobsters-sip.md
- packages/wrangler/src/index.tsx
Catch unsupported terminal errors and provide a nicer error message.
Wrangler depends on terminals supporting [raw mode](https://en.wikipedia.org/wiki/Terminal_mode). Previously, attempting to run wrangler from a terminal that didn't support raw mode would result in
an Ink error, which was both an exposure of an internal implementation detail to the user and also not actionable:
```text
ERROR Raw mode is not supported on the current process.stdin, which Ink uses
as input stream by default.
Read about how to prevent this error on
https://github.com/vadimdemedes/ink/#israwmodesupported
```
Now, we provide a much nicer error, which provides an easy next step for th user:
```text
ERROR: This terminal doesn't support raw mode.
Wrangler uses raw mode to read user input and write output to the …
```
> Error politely when the user is using an unsupported terminal

- .changeset/lovely-chairs-taste.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/pages/dev.tsx
Like `wrangler dev` proper, `wrangler pages dev` now defaults to using today's compatibility date. It can be overriden with `--compatibility-date=YYYY-MM-DD`.
https://developers.cloudflare.com/workers/platform/compatibility-dates/
> Default to today's compatibility date in `wrangler pages dev`

- .changeset/rare-eels-pay.md
- packages/wrangler/src/__tests__/delete.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/delete.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/metrics/send-event.ts
This PR adds a simple (but useful!) implementation for `wrangler delete`. Of note, it'll delete a given service, including all it's bindings. It uses the same api as the dashboard.
> feat: implement a basic `wrangler delete`

- .changeset/new-maps-share.md
- fixtures/pages-functions-with-routes-app/functions/bye.ts
- fixtures/pages-functions-with-routes-app/functions/date.ts
- fixtures/pages-functions-with-routes-app/functions/greeting/bye.ts
- fixtures/pages-functions-with-routes-app/functions/greeting/goodbye.ts
- fixtures/pages-functions-with-routes-app/functions/greeting/hello.ts
- fixtures/pages-functions-with-routes-app/functions/greeting/index.ts
- fixtures/pages-functions-with-routes-app/functions/greetings.ts
- fixtures/pages-functions-with-routes-app/functions/index.ts
- fixtures/pages-functions-with-routes-app/public/_routes.json
- fixtures/pages-functions-with-routes-app/tests/index.test.ts
- fixtures/pages-workerjs-with-routes-app/public/_routes.json
- fixtures/pages-workerjs-with-routes-app/public/_worker.js
- fixtures/pages-workerjs-with-routes-app/tests/index.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/templates/__tests__/pages-dev-util.test.ts
- packages/wrangler/templates/pages-dev-pipeline.ts
- packages/wrangler/templates/pages-dev-util.ts
- packages/wrangler/templates/tsconfig.json
Currently, the logic by which we transform routing rules in `_routes.json` to
regular expressions, so we can perform `pathname` matching & routing when we
run `wrangler pages dev`, is too permissive, and leads to serving incorrect
assets for certain url paths.
For example, a routing rule such as `/foo` will incorrectly match pathname
`/bar/foo`. Similarly, pathname `/foo` will be incorrectly matched by the
`/` routing rule.
This commit fixes our routing rule to pathname matching logic and brings
`wrangler pages dev` on par with routing in deployed Pages projects.
> fix(pages): `wrangler pages dev` matches routing rules in `_routes.json too loosely

- .changeset/tough-rules-wonder.md
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/logger.ts
- packages/wrangler/src/miniflare-cli/index.ts
Previously, Miniflare's `Log` was being constructed with an incorrectly typed log level (TypeScript enum issues :upside_down_face:). Miniflare's package for coloured `console` output was unable to detect whether the current terminal supported colours. This PR fixes the log level issues, and sets the `FORCE_COLOR` environment variable when starting the Miniflare CLI process if the terminal supports colour.
Ref: #2036
> Fix `--local` mode logging and enable colours

- .changeset/poor-cycles-grow.md
- packages/wrangler/src/__tests__/delete.test.ts
- packages/wrangler/src/delete.ts
- packages/wrangler/src/sites.tsx
This patch deletes any site/asset kv namespaces associated with a worker when `wrangler delete` is used. It finds the namespace associated with a worker by using the names it would have otherwise used, and deletes it. It also does the same for the preview namespace that's used with `wrangler dev`.
> feat: delete site/assets namespace when a worker is deleted

- .changeset/dirty-gifts-breathe.md
- fixtures/pages-functions-app/functions/passThroughOnException/_middleware.ts
- fixtures/pages-functions-app/functions/passThroughOnException/nested.ts
- fixtures/pages-functions-app/functions/passThroughOnExceptionClosed.ts
- fixtures/pages-functions-app/functions/passThroughOnExceptionOpen.ts
- fixtures/pages-functions-app/functions/passThroughOnExceptionWithCapture/_middleware.ts
- fixtures/pages-functions-app/functions/passThroughOnExceptionWithCapture/nested.ts
- fixtures/pages-functions-app/tests/index.test.ts
- packages/wrangler/templates/pages-template-plugin.ts
- packages/wrangler/templates/pages-template-worker.ts
Workers Types PR: https://github.com/cloudflare/workers-types/pull/314
feat: Add a `passThroughOnException()` handler in Pages Functions
This `passThroughOnException()` handler is not as good as the built-in for Workers. We're just adding it now as a stop-gap until we can do the behind-the-scenes plumbing required to make the built-in function work properly.
We wrap your Pages Functions code in a `try/catch` and on failure, if you call `passThroughOnException()` we defer to the static assets of your project.
For example:
```ts
export const onRequest = ({ passThroughOnException }) => {
passThroughOnException();
x; // Would ordinarily throw an error, but instead, static assets are served.
};
```
> Add a `passThroughOnException()` handler to Pages Functions

- .changeset/cool-nails-marry.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/is-interactive.ts
- packages/wrangler/src/pages/constants.ts
- packages/wrangler/src/pages/upload.tsx
Don't upload `functions/` directory as part of `wrangler pages publish`
If the root directory of a project was the same as the build output directory, we were previously uploading the `functions/` directory as static assets. This PR now ensures that the `functions/` files are only used to create Pages Functions and are no longer uploaded as static assets.
Additionally, we also now _do_ upload `_worker.js`, `_headers`, `_redirects` and `_routes.json` if they aren't immediate children of the build output directory. Previously, we'd ignore all files with this name regardless of location. For example, if you have a `public/blog/how-to-use-pages/_headers` file (where `public` is your build output directory), we will now upload the `_headers` file as a static asset.
> Avoid uploading the `functions/` directory as part of `wrangler pages publish`

- .changeset/green-icons-end.md
- packages/wrangler/src/pages/upload.tsx
Log error when we exhaust retries for Pages upload. This is to support better troubleshooting with publishing issues.
> Log pages upload error

- .changeset/d1-execute.perf.md
- packages/wrangler/src/d1/backups.tsx
- packages/wrangler/src/d1/execute.tsx
- Better and faster handling when importing big SQL files using execute --file
- Increased visibility during imports, sends output with each batch API call
- Backups are now downloaded to the directory where wrangler was initiated from
> fix: D1 execute and backup commands improvements

- packages/wrangler/src/pages/upload.tsx
This is changing the way JWT Expiration errors are checked during the pages direct upload process. Previously the error was being checked for a specific error code that does not exist on the `ParseError` being thrown in the case the JWT has expired while uploading. This adds a second condition that decodes the current JWT and validates that token has not expired.
> fix(upload): add helper to check for expired JWT

- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/helpers/msw/handlers/zones.ts
- packages/wrangler/src/__tests__/helpers/msw/index.ts
- packages/wrangler/src/zones.ts
Closes #2094 and #2095
Falls back to `zone_name` when the hostname can't be inferred from a route pattern (essentially only for the wildcard pattern `*/*`
> Fallback to `zone_name` on invalid URL error

- .changeset/tidy-lobsters-agree.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
computing the name from binding response, now the `vars` will be computed, example:
`[var.binding.name]: var.binding.text`
this will resolve the issue that was occurring with generating a TOML with incorrect fields for the `vars` key/value pair.
resolves #2048
> fix: `--from-dash` `vars` incorrect fields

- .changeset/tiny-gifts-own.md
- packages/wrangler/src/__tests__/access.test.ts
- packages/wrangler/src/__tests__/helpers/msw/handlers/access.ts
- packages/wrangler/src/__tests__/helpers/msw/index.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/create-worker-preview.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/inspect.ts
- packages/wrangler/src/proxy.ts
- packages/wrangler/src/user/access.ts
Enable support for `wrangler dev` on Workers behind Cloudflare Access, utilising `cloudflared`. If you don't have `cloudflared` installed, Wrangler will prompt you to install it. If you _do_, then the first time you start developing using `wrangler dev` your default browser will open with a Cloudflare Access prompt.
> Support Cloudflare Access for `wrangler dev`

- .changeset/large-dingos-try.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Added the fromDashName provided as a fallback when no name is provided in the `wrangler init` command. Additionally added a checks to the `std.out` to ensure that the name is provided.
resolves #1853
> Fix: Missing Worker name using `--from-dash`

- .changeset/modern-carrots-relate.md
- fixtures/local-mode-tests/package.json
- fixtures/local-mode-tests/src/nodeBuiltinPackage.ts
- fixtures/local-mode-tests/tests/nodeBuiltinPackage.test.ts
- package-lock.json
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/logger.ts
Previously, if `node_compat` was disabled, and the user had an npm package with the same name as a Node built-in module installed (e.g. `buffer`), esbuild would always throw instead of resolving it. This PR fixes the issue by relying on esbuild's resolver, and instead rewriting the error message on failure to suggest enabling `node_compat` instead of `platform: "node"`.
Closes #2038
> Fix importing npm packages with same name of Node built-ins

- .changeset/lazy-teachers-melt.md
- packages/wrangler/src/__tests__/d1.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/__tests__/pubsub.test.ts
- packages/wrangler/src/__tests__/queues.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/worker-namespace.test.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/d1/index.ts
- packages/wrangler/src/delete.ts
- packages/wrangler/src/deprecated/index.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev-vars.ts
- packages/wrangler/src/dispatch-namespace.ts
- packages/wrangler/src/index.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/kv/index.ts
- packages/wrangler/src/publish/index.ts
- packages/wrangler/src/pubsub/pubsub-commands.tsx
- packages/wrangler/src/queues/cli/commands/consumer/add.ts
- packages/wrangler/src/queues/cli/commands/consumer/index.ts
- packages/wrangler/src/queues/cli/commands/consumer/remove.ts
- packages/wrangler/src/queues/cli/commands/index.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/tail/index.ts
- packages/wrangler/src/yargs-types.ts
If `--env <env>` is specified, we'll now check `.env.<env>`/`.dev.vars.<env>` first. If they don't exist, we'll fallback to `.env`/`.dev.vars`.
`--env` is now a flag in every command, like `--config`.
Closes #1305.
> Load `.env`/`.dev.vars` file based on `--env`

- .changeset/metal-news-tap.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle-reporter.tsx
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/publish/publish.ts
Uses the esbuild-generated metafile to see which dependencies are heaviest and points out the top 5, as well as a message encouraging a smaller script
> Warn for scripts larger than 1MB compressed

- packages/wrangler/src/d1/create.tsx
Before:
```
✘ [ERROR] A request to the Cloudflare API (/accounts/f7f78ebb28c2a224a9a46a3007350b7a/d1/database) failed.
Internal error [code: 7502]
If you think this is a bug, please open an issue at:
https://github.com/cloudflare/wrangler2/issues/new/choose
```
After:
```
✘ [ERROR] A database with that name already exists
If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
```
> Make a better error message when creating a d1 db fails

- .changeset/pretty-lemons-prove.md
- packages/pages-shared/asset-server/metadata.ts
- packages/pages-shared/metadata-generator/createMetadataObject.ts
- packages/pages-shared/metadata-generator/types.ts
feat: Add a `failOpen` prop to the deployment metadata
> Add `failOpen` property to the deployment metadata

- packages/wrangler/src/publish/publish.ts
We're currently throwing this error to everyone while versions isn't fully rolled out - this PR suppresses the error.
```
✘ [ERROR] A request to the Cloudflare API (/accounts/xxx/workers/versions/by-script/xxx) failed.
  workers.api.error.unauthorized [code: 10023]
  
  If you think this is a bug, please open an issue at: https://github.com/cloudflare/wrangler2/issues/new/choose
```
> fix: don't throw if versions isn't available

- .changeset/violet-dancers-fix.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/publish/publish.ts
The API error codes for queues are being updated.
This PR updates the error code for handling missing queues.
> Update error code for queue_not_found

- .changeset/yellow-files-argue.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation.ts
The type was not being coerced to a string, so TypeScript considered it a unresolved type.
> [Fix] `vars` string type

- .changeset/old-doors-enjoy.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/constants.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
Closes https://github.com/cloudflare/wrangler2/issues/2171
Uses the `key` provided since there won't always be a `file` name, in the event it's using piped data.
Before:
```sh
➜  ~ npx wrangler r2 object put sdk-example/test.tmp -f ./test.tmp
⛅️ wrangler 2.2.1
-------------------
Creating object "test.tmp" in bucket "sdk-example".
✘ [ERROR] Failed to fetch /accounts/134a5a2c0ba47b38eada4b9c8ead10b6/r2/buckets/sdk-example/objects/test.tmp - 413: Request Entity Too Large);
If you think this is a bug then please create an issue at https://github.com/cloudflare/wrangler2/issues/new/choose
```
After:
```sh
> node -r esbuild-register scripts/bundle.ts
⛅️ wrangler 2.2.1 
-------------------
✘ [ERROR] Error: Wrangler only supports uploading files up to 315 MB in size
test.tmp is 316 MB in size
If …
```
> Validate object size for wrangler r2 put

- .github/workflows/codecov-context.yml
- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/d1.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/queues.yml
- .github/workflows/release.yml
This is required by `workerd` at runtime. It also looks like this is indirectly required by `workerd`'s install script, so we need to install this any time we call `npm ci`.
> Install `libc++1` in GitHub actions jobs

- .github/workflows/codecov-context.yml
- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/d1.yml
- .github/workflows/experimental-wasm-release.yml
- .github/workflows/issues.yml
- .github/workflows/prereleases.yml
- .github/workflows/pullrequests.yml
- .github/workflows/queues.yml
- .github/workflows/release.yml
- .github/workflows/test-old-node-error.yml
- .github/workflows/write-prerelease-comment.yml
Due to changes in `workerd`, and issues with `libc++` in ubuntu 20, use `ubuntu-22.04` instead of `ubuntu-latest` in CI
> Use latest ubuntu for all tests

- .changeset/friendly-adults-rush.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
Rather than recreating `Miniflare` instances on each reload, this PR switches to using `Miniflare#setOptions` on the existing instance if it exists. This retains internal Miniflare state, like the loopback server, which makes reloads much more efficient. This is also required for live-reload to work properly.
> Switch to using `Miniflare#setOptions` for experimental local

- .changeset/loud-toys-guess.md
- packages/wrangler/src/d1/execute.tsx
Takes some lines out when the commands fit in a single batch, and gives the user some context about where each batch starts if there are multiple, e.g.
> Tweaking display of d1 execute (for large files in particular)

- .changeset/strange-wolves-pull.md
- package-lock.json
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
Added support for console logging when using miniflare3
resolves #2122
> Local Mode Console Support

- .changeset/wicked-rules-run.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages/publish.tsx
Publishing Pages projects containing a functions directory incorrectly did not upload the filepath-routing config so that the user can view it in Dash. This fixes that, making the generated routes viewable under `Routing configuration` in the `Functions` tab of a deployment.
Testing:
- Added tests that show the file is being uploaded
- e2e tested
> fix: Upload filepath-routing configuration in wrangler pages publish

- .changeset/brown-beers-cheat.md
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/metrics/metrics-config.ts
When metrics was implemented the XDG compliant pathing was done in parrelel, this bring metrics directory into XDG compliance with other Wrangler root config.
resolves #2075
> XDG compliant metrics directory

- .changeset/tall-waves-film.md
- packages/wrangler/src/dev/start-server.ts
> chore: remove d1 local hardcoding

- .changeset/brave-fireants-think.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/templates/middleware/loader-sw.ts
- packages/wrangler/templates/middleware/middleware-miniflare3-json-error.ts
This PR enables Miniflare 3's pretty-error page with middleware. See https://github.com/cloudflare/miniflare/pull/436 for an explanation of why we need to do this in the first place. It also fixes an issue where enabling the middleware loader in service-worker Workers disabled file watching.
> Enable pretty-error page when using `--experimental-local`

- .changeset/yellow-zebras-shave.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/miniflare-cli/index.ts
- packages/wrangler/src/proxy.ts
Dependent on https://github.com/cloudflare/miniflare/pull/382
> Fix `--port=0` option to correctly open on random port

- .changeset/itchy-tigers-jump.md
- packages/wrangler/src/d1/backups.tsx
> Fix: D1 backup download: check response status

- .changeset/gentle-rocks-sneeze.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/git-client.ts
Previously, we would initialize new workers with `main` as the name of the default branch.
Now, we see if the user has a custom setting in .gitconfig for `init.defaultBranch`, and use
that if it exists.
Closes #2112
> Use the user's preferred default branch name if set in .gitconfig

- .changeset/bright-donkeys-pay.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
Previously, we would just error if a user logged out and then ran `wrangler dev`.
Now, we kick them to the OAuth flow and suggest running `wrangler dev --local` if
the login fails.
Closes [#2147](https://github.com/cloudflare/wrangler2/issues/2147)
> Trigger login flow if a user runs `wrangler dev` while logged out

- packages/wrangler/src/type-generation.ts
This PR makes `prettier --check` pass on the generated `worker-configuration.d.ts` file by removing trailing whitespaces and replacing tabs with 4 whitespaces.
```diff
// Generated by Wrangler on Mon Nov 28 2022 09:15:37 GMT-0800 (Pacific Standard Time)
interface Env {
-	DB: D1Database; 
+    DB: D1Database;
}
```
> fix: make generated types prettier

- .changeset/lazy-wolves-sing.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/type-generation.ts
- packages/wrangler/src/worker.ts
I've tried to add support for an `analytics_engine_datasets` section in wrangler.toml. To avoid having to use unsafe bindings.
> Add first class Analytics Engine bindings

- .changeset/eight-ducks-reflect.md
- fixtures/external-durable-objects-app/tests/index.test.ts
- fixtures/local-mode-tests/tests/headers.test.ts
- fixtures/local-mode-tests/tests/module.test.ts
- fixtures/local-mode-tests/tests/nodeBuiltinPackage.test.ts
- fixtures/local-mode-tests/tests/ports.test.ts
- fixtures/local-mode-tests/tests/sw.test.ts
- fixtures/local-mode-tests/tests/unstableDev.test.ts
- fixtures/node-app-pages/tests/index.test.ts
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-functions-with-routes-app/tests/index.test.ts
- fixtures/pages-workerjs-and-functions-app/tests/index.test.ts
- fixtures/pages-workerjs-with-routes-app/tests/index.test.ts
- fixtures/pages-ws-app/tests/index.test.ts
- fixtures/remix-pages-app/tests/index.test.ts
- fixtures/service-bindings-app/tests/index.test.ts
- package-lock.json
- packages/pages-shared/environment-polyfills/miniflare-tre.ts
- packages/wrangler/package.json
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/miniflare-cli/assets.ts
- packages/wrangler/src/miniflare-cli/index.ts
- packages/wrangler/src/pages/dev.tsx
> Enable `--experimental-local` for `wrangler pages dev`

- .changeset/healthy-peaches-drive.md
- .changeset/unlucky-cars-shout.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
Previously, the Wrangler proxy and Node.js/workerd inspector servers were listening on the same port. This somehow worked on macOS, but gives a port already in use error on Linux.
Additionally, the Node.js inspector was configured to listen on `0.0.0.0:<port>`. Aside from the security risk of opening an inspector server on all interfaces, Node.js was logging `0.0.0.0:<port>` to the console. Our RegExp to extract the debugger URL was looking for `127.0.0.1:<port>` though, so we never actually connected to the inspector.
We also had an issue where calling `setOptions()`/`dispose()` on Miniflare 3 instances, wouldn't actually clean-up the previous `workerd` instance. This has been fixed in `@miniflare/tre@3.0.0-next.8`.
> Fix `--(experimental)-local` on Linux

- .changeset/breezy-bears-hang.md
- fixtures/worker-app/package.json
- fixtures/worker-app/tests/index.test.ts
- packages/pages-shared/environment-polyfills/miniflare-tre.ts
- packages/pages-shared/environment-polyfills/miniflare.ts
- packages/wrangler/src/miniflare-cli/assets.ts
The `await import()` of the environment polyfills seemed to break out of the `if (tre) {}` check. This made the`miniflare-cli` dist look like:
```ts
import { ... } from "@miniflare/tre"
```
When the `@miniflare/tre` package was missing, this broke `wrangler dev --local` for users.
By wrapping the polyfill logic in a function like this, we can avoid this top-level import.
> Fix `wrangler dev --local` and its lazy imports of `@miniflare/tre`

- .changeset/lovely-bears-sort.md
- packages/wrangler/src/d1/migrations/apply.tsx
Closes https://github.com/cloudflare/wrangler2/issues/2336
> fix: d1 - don't backup prod db when applying migrations locally

- packages/wrangler/src/config/index.ts
- packages/wrangler/src/index.tsx
This PR removes the:
```
✘ [ERROR] Cannot read properties of undefined (reading 'legacy-env')
```
message that appears
> fix: call readConfig like the rest of the examples

- .changeset/clean-rules-peel.md
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/dev.tsx
With `--local` enabled this now prints:
```
Your worker has access to the following bindings:
- D1 Databases:
- DB: test3 (local)
```
Otherwise:
```
Your worker has access to the following bindings:
- D1 Databases:
- DB: test3 (9bcfcc3b-e25f-4088-8ef3-959ffe5e2665), Preview: (9bcfcc3b-e25f-4088-8ef3-959ffe5e2665)
```
Closes https://github.com/cloudflare/wrangler2/issues/2354
> fix: don't ask for preview_database_id in --local

- .changeset/cyan-rings-clap.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Moves script metadata request earlier in command to fail on unknown worker before asking user questions
Fixes #2241
> Check that worker exists first when using --from-dash

- .changeset/rotten-dragons-notice.md
- packages/wrangler/bin/wrangler.js
Closes #2302.
When a global `wrangler` command is executed in a package directory with `wrangler` installed locally, the command is redirected to the local `wrangler` install. Whilst sometimes useful, this behaviour is contrary to most other `npm` CLI packages (and `npx wrangler ...` should already call the local version if detected). It also makes debugging issues more confusing, as it's not clear which `wrangler` version is being called. This PR replaces a debug log we already had for this with a regular log, so users (and `wrangler` developers 😅) know what's going on.
> Always log when delegating to local `wrangler` install

- .changeset/tasty-toes-drive.md
- packages/wrangler/src/dev.tsx
In the bootstrapper script `bin/wrangler.js`, we open an IPC channel, so IPC messages from the Wrangler process are propagated through the bootstrapper. Normally, Node's SIGINT handler would close this for us, but interactive mode enables raw mode on stdin which disables the built-in handler. This PR calls `process.disconnect()` to close this channel when we press `x` or CTRL-C, ensuring no open handles, and allowing for a clean exit.
This PR can be tested by running `wrangler dev --experimental-local` on a simple Worker script, then pressing, `x`, `q` and/or `CTRL-C`.
N/A
Fixes #2387
> Allow `--experimental-local` to cleanly exit on `x`/`CTRL-C`

- packages/wrangler/src/pubsub/pubsub-commands.tsx
Fixes:
```
➜  wrangler pubsub namespace create hello-namespace                             
Creating Pub/SubNamespace hello-namespace...
Success! Created Pub/Sub Namespace hello-namespace
```
Note the missing space between `Pub/Sub` and `Namespace`.
> pubsub: fix typo in log output

- packages/wrangler/src/__tests__/jest.setup.ts
I ran the tests in my environment, and the tests failed with messages like the following:
This is caused by the setting of the language to Japanese in my environment.
```
$ echo $LC_ALL
ja_JP.UTF-8
```
`Yargs` throws errors in Japanese, not English, since `Yargs` looks up an environment variable to decide which language to use.
There are several ways to fix it. I couldn't decide which way would work best for us, so this PR will propose one of the solutions.
In `jest.setup.ts`, I've set the `LC_ALL` to fix the language as English for the messages thrown by `Yargs`. If there is a better way, let's go with it.
Nothing
> test: set `LC_ALL` to `en` to fix the language thrown by Yargs

- .changeset/beige-snails-complain.md
- packages/wrangler/src/__tests__/d1.test.ts
- packages/wrangler/src/d1/migrations/apply.tsx
When applying D1 migrations to a deployed database, it is important that we are logged in and that we have the database ID from the wrangler.toml. This is not needed for `--local` mode where we are just writing to a local SQLite file.
Unit tests have been added but to manually test this cd into `fixtures/worker-app` and run
```
npx wrangler logout
npx wrangler d1 migrations apply --local DATABASE
```
If Wrangler attempts to log you in, it is broken.
If Wrangler complains that you have not specified any D1 database bindings in wrangler.toml, it is broken.
The expected behaviour is that it complains that there are no migration files.
Fixes a problem …
> fix(wrangler): do not login or read wrangler.toml when applying D1 migrations in local mode.

- CONTRIBUTING.md
The team agreed we should be following semver for wrangler2's versions. See https://github.com/cloudflare/wrangler2/discussions/1820.
If you weren't in that meeting, or had a change of heart, feel free to disagree in the comments below.
This PR updates our CONTRIBUTING.md to reflect this decision.
> Update to CONTRIBUTING.md: we follow semver now

- .changeset/afraid-tigers-lie.md
- fixtures/local-mode-tests/tests/headers.test.ts
- packages/wrangler/src/__tests__/api-dev.test.ts
- packages/wrangler/src/__tests__/api-devregistry.test.js
- packages/wrangler/src/dev/start-server.ts
`unstable_dev` tests seem to flake due to the dev registry not having started in time for the test to run.
An initial approach was to completely disable the dev registry, but I realised we never actually `await` when starting it - which could lead to the flakiness we've seen.
**Associated docs issues/PR:**
N/A
> Add an `await` when starting devRegistry

- packages/wrangler/src/__tests__/helpers/mock-dialogs.ts
`mockPrompt` throws an Error with the message `Unexpected confirmation message`. This message should be `Unexpected prompt message` instead.
> Fix `mockPrompt` error message

- .changeset/warm-phones-knock.md
- fixtures/local-mode-tests/tests/headers.test.ts
- fixtures/local-mode-tests/tests/module.test.ts
- fixtures/local-mode-tests/tests/nodeBuiltinPackage.test.ts
- fixtures/local-mode-tests/tests/ports.test.ts
- fixtures/local-mode-tests/tests/sw.test.ts
- fixtures/local-mode-tests/tests/unstableDev.test.ts
- packages/wrangler/src/__tests__/api-dev.test.ts
- packages/wrangler/src/__tests__/api-devregistry.test.js
- packages/wrangler/src/__tests__/middleware.scheduled.test.ts
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/pages/dev.tsx
- packages/wrangler/templates/init-tests/test-jest-new-worker.js
- packages/wrangler/templates/init-tests/test-vitest-new-worker.js
This PR refactors `unstable_dev` to use a single `options` object, which contains an `experimental` object for things we're still trying out. 
A follow-up PR will want to move more options to `experimental` - I believe @Skye-31 / @GregBrimble  / @WalshyDev would know if there are Pages-only props passed to `unstable_dev` that we might want to put in there
- https://github.com/cloudflare/wrangler2/issues/2344
- https://github.com/cloudflare/cloudflare-docs/pull/7113
> Refactor unstable_dev to have a single `option` object

- .changeset/long-wombats-refuse.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/init.ts
- Remove experimental warning for dispatch namespaces since the [feature is GA](https://developers.cloudflare.com/cloudflare-for-platforms/workers-for-platforms/get-started/configuration/).
- Update `namespace` to `dispatch_namespace` in upload form (the script upload API accepts both).
Tested with [Workers for Platforms Example Project](https://github.com/cloudflare/workers-for-platforms-example).
`npm start -w wrangler publish -- --config /path/to/workers-for-platforms-example-project/wrangler.toml`
> Remove experimental warning for dispatch namespaces

- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/cli.ts
Just exporting DevOptions for easier typing - called it `UnstableDevOptions` to make it clear it'll change
> chore: export devoptions as UnstableDevOptions

- .changeset/rotten-tigers-clean.md
- fixtures/local-mode-tests/tests/ports.test.ts
- packages/wrangler/src/__tests__/middleware.scheduled.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/pages/dev.tsx
This PR closes https://github.com/cloudflare/wrangler2/issues/2344 by finalizing the options we want to support, and what we still consider experimental.
- Follow-up PR to come once 
Closes #2344
> chore: move spicy options under experimental in unstable_dev

- .changeset/real-actors-laugh.md
- packages/wrangler/templates/d1-beta-facade.js
This PR bumps d1js, adding the following functionality to the d1 alpha shim:
- validates supported types
- converts ArrayBuffer to array
- converts typedArray to array
> fix: bump d1js

- .github/changeset-version.js
#2489 broke the `Release` CI with an error that `patch-package` couldn't be found when running `changeset-version.js`.
It looks like the `npm install` script in `changeset-version.js` is only installing production dependencies. Moving `patch-package` to `dependencies` leads to another error that `ink` cannot be found to apply the patch to. 🙃 
However, the only reason we run `npm install` here is to update `package-lock.json`, so we don't need to be running `postinstall` scripts. Therefore, this PR adds the `--package-lock-only` flag. See https://docs.npmjs.com/cli/v9/commands/npm-install.
I've tested this locally using [`act`](https://github.com/nektos/act).
N/A
> Only update `package-lock.json` when running changeset version script

- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/user/choose-account.tsx
`<ChooseAccount>` was only being used by `remote.tsx`, but it was included in `choose-account.tsx`, meaning `ink` needed to be imported here. Unfortunately, `choose-account.tsx` is a transitive dependency of `cfetch`, meaning any file that made Cloudflare API calls ended up importing `ink`. `ink` has a transitive dependency on `yoga-layout` which allocates WebAssembly memory on import. This change moves `<ChooseAccount>` to `remote.tsx`, a file which already uses `ink`, to help alleviate out-of-memory issues.
N/A
> Move `<ChooseAccount>` to `remote.tsx`

- .changeset/silent-ads-pay.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/d1/d1.test.ts
- packages/wrangler/src/__tests__/d1/splitter.test.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/splitter.ts
This fix updates the SQL statement splitting so that it does not split in the middle of compound statements.
Previously we were using a third party splitting library, but this needed fixing and was actually unnecessary for our purposes.
So a new splitter has been implemented and the library dependency removed.
Also the error handling in `d1 migrations apply` has been improved to handle a wider range of error types.
Fixes #2463
To test manually, create a simple migration script `migrations/0000_initial.sql` that contains a compound statement:
```
CREATE TABLE IF NOT EXISTS actors (
id TEXT PRIMARY KEY,
type TEXT NOT NULL,
properties TEXT NOT NULL DEFAULT (json_object())
);
CREATE VIRTUAL TABLE IF NOT EXISTS search_fts USING fts5 (
type,
name,
);
CREATE …
```
> fix(d1): ensure that migrations support compound statements

- .changeset/tame-books-draw.md
- packages/wrangler/src/api/dev.ts
A subtle difference when removing object-spreading of experimental unstable_dev() options caused `wrangler pages dev` interactivity to stop working. This switches back to object-spreading the passed in options on top of the defaults, fixing the issue.
Fixes wrangler pages dev not showing any of the keyboard shortcuts (and none of them working.)
Test with:
```shell
npm run build -w wrangler
cd fixtures/pages-plugin-example
npm run build
cd ../pages-functions-app
npm run dev
```
Before: Interactive dev session did not work
After: Interactive dev session works
Associated docs issues/PR: Raised internally
No issue that I …
> fix: unstable_dev() experimental options incorrectly applying defaults

- .changeset/forty-beds-sort.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages/publish.tsx
`_routes.json` is no longer considered an experimental feature, so let's remove all warnings we have in place for that.
> fix: Remove "experimental _routes.json" warnings

- .changeset/bright-mails-doubt.md
- packages/wrangler/src/docs/index.ts
This PR is blocked until https://github.com/cloudflare/cloudflare-docs/pull/7202 gets merged.
> fix: send `wrangler docs d1` to the right place

- .changeset/tiny-knives-compare.md
- fixtures/external-durable-objects-app/tests/index.test.ts
- fixtures/local-mode-tests/tests/unstableDev.test.ts
- fixtures/node-app-pages/tests/index.test.ts
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-functions-with-routes-app/tests/index.test.ts
- fixtures/pages-workerjs-and-functions-app/tests/index.test.ts
- fixtures/pages-workerjs-app/tests/index.test.ts
- fixtures/pages-workerjs-with-routes-app/tests/index.test.ts
- fixtures/remix-pages-app/.gitignore
- fixtures/remix-pages-app/tests/index.test.ts
- fixtures/service-bindings-app/tests/index.test.ts
- fixtures/shared/src/run-wrangler-long-lived.ts
- fixtures/worker-app/tests/index.test.ts
- package.json
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/pages/publish.tsx
Adds support to `wrangler pages` to pass the raw `_worker.js` file through the normal Wrangler bundler,
which improves support for D1 bindings with web frameworks that generate this file, such as SvelteKit.
You can test whether this is working by creating a Pages project with a `_worker.js` that imports from another
JS file. E.g.
**_worker.js**
```ts
import value from "./dep";
async fetch() {
return new Response(value);
},
};
```
**dep.js**
```ts
export default "TEST";
``` 
- TBD
FIxes https://github.com/cloudflare/wrangler2/issues/2153
> feat: support bundling the raw Pages `_worker.js` before deploying

- .changeset/warm-nails-clap.md
- packages/wrangler/templates/checked-fetch.js
Due to the local fetch check, URL objects are wrongly not accepted by `fetch()` calls,
amend the `checkedFetch` function in order to allow such scenario (which
anyways works after deployment).
resolves #1588
> fix: allow URL object to be passed to local `fetch()` calls

- .changeset/grumpy-pants-relax.md
- packages/wrangler/src/d1/backups.tsx
Running `wrangler d1 backup download <NAME> <ID>` fails with the following output:
```
rozenmd@QRVX0PWXHR d1-local-migrate % wrangler d1 backup download test3 asdf
▲ [WARNING] Processing wrangler.toml configuration:
- D1 Bindings are currently in alpha to allow the API to evolve before general availability.
Please report any issues to https://github.com/cloudflare/wrangler2/issues/new/choose
Note: Run this command with the environment variable NO_D1_WARNING=true to hide this message
For example: `export NO_D1_WARNING=true && wrangler <YOUR COMMAND HERE>`
🚧 D1 is currently in open alpha and is not recommended for production data and traffic.
Please report any bugs to https://github.com/cloudflare/wrangler2/issues/new/choose.
To request features, visit …
```
> fix: path should be optional for `wrangler d1 backup download`

- .changeset/tiny-swans-kick.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
When we bundle a Worker, `esbuild` takes care of writing the results to the output directory. However, if the Worker contains any `external` imports, such as text/wasm/binary module imports, that cannot be inlined into the same bundle file, `bundleWorker` will not copy these files to the output directory. This doesn't affect `wrangler publish` per se, because of how the Worker upload FormData is created. It does however create some inconsistencies when running `wrangler publish --outdir` or `wrangler publish --outdir --dry-run`, in that, `outdir` will not contain those external import files.
This commit addresses this issue by making sure the aforementioned files do get copied over to `outdir` together with `esbuild`'s resulting bundle files. …
> fix: Copy module imports related files to outdir

- .changeset/cuddly-spoons-search.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/entry.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/templates/d1-beta-facade.js
This PR makes it possible to access D1 bindings from Durable Objects.
To test, make a durable object, add D1 bindings to your project, and try query D1 from it.
Fixes #2335
> Pipe through the DO bindings to get shimmed

- .changeset/green-planets-wink.md
- package-lock.json
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/api/pages/index.ts
- packages/wrangler/src/api/pages/publish.tsx
- packages/wrangler/src/cli.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/publish.tsx
This PR refactors the existing Pages publish code into its own exportable function and exports it in the wrangler API under the `unstable_pages` object. This will allow folks to run the `publish` function in a scriptable JS environment and will get the entire deployment response as a variable.
- https://github.com/cloudflare/wrangler2/issues/2437
> feat(api): Adds unstable_pages module to JS API

- package-lock.json
Merging https://github.com/cloudflare/wrangler2/pull/2554 seems to have broken CI
https://github.com/cloudflare/wrangler2/actions/runs/3986649825/jobs/6835473536, so this PR attempts to fix that
> fix: Add missing `pages-functions-wasm-app` deps in `package-lock.json`

- .changeset/perfect-grapes-fold.md
- fixtures/worker-app/src/index.js
- packages/wrangler/templates/checked-fetch.js
This reverts and fixes the changes in https://github.com/cloudflare/wrangler2/pull/1769 which does not support creating requests from requests whose bodies have already been consumed.
Fixes #2562
---
To test you can simply run the `fixtures/worker-app` project:
```
npm run build
cd fixtures/worker-app
npx wrangler dev
```
Without the fix, one or both of the new lines in that fixture (added by this PR) will cause an error.
- N/A
> fix: do not crash in wrangler dev when passing a request object to fetch

- .changeset/lovely-parents-ring.md
- packages/wrangler/src/__tests__/pages.test.ts
- packages/wrangler/src/api/pages/publish.tsx
- packages/wrangler/src/pages/types.ts
> fix: make sure d1Databases are shimmed in _worker.js files on pages publish

- .changeset/rare-laws-sing.md
- packages/wrangler/src/__tests__/d1/d1.test.ts
- packages/wrangler/src/__tests__/d1/migrate.test.ts
- packages/wrangler/src/d1/list.tsx
This PR hides the warning messages, and just returns clean json when running `wrangler d1 list --json`
Before:
```bash
rozenmd@cflaptop test % npx wrangler d1 list
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/wrangler2/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
┌──────────────────────────────┬─────────────────┐
│ uuid                         │ name            │
├──────────────────────────────┼─────────────────┤
│ xxxxxx-xxxx-xxxx-xxxx-xxxxxx │ test            │
├──────────────────────────────┼─────────────────┤
│ …
```
> fix: cleans up `d1 list` output for json

- .changeset/khaki-suns-boil.md
- packages/wrangler/src/d1/execute.tsx
> fix: create d1 dir on wrangler d1 execute command with --yes/-y option

- .changeset/chilly-donuts-fetch.md
- fixtures/isomorphic-random-example/README.md
- fixtures/isomorphic-random-example/package.json
- fixtures/isomorphic-random-example/src/node.js
- fixtures/isomorphic-random-example/src/workerd.mjs
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- package-lock.json
- packages/wrangler/src/bundle.ts
This PR adds support for the `workerd` condition when bundling Worker code. This can be used to implement isomorphic libraries that work with different JavaScript runtimes. `workerd` is the standard key for the Cloudflare Workers runtime: https://runtime-keys.proposal.wintercg.org/#workerd.
To test this PR, run `npx wrangler dev` in the `fixtures/worker-app` directory, and visit http://127.0.0.1:8787/random in your browser. Note that random data appears. We haven't enabled Node.js compatibility so we must be using the `workerd` version of the `isomorphic-random-example` package.
- https://github.com/cloudflare/cloudflare-docs/pull/7424
> Prioritise `workerd` condition when bundling

- .changeset/serious-cats-brake.md
- packages/wrangler/src/publish/publish.ts
When wrangler configuration has queues, wrangler publish dry-run requires the user to be logged in.
This is not the expected behavior.
This originates from wrangler publish ensuring that configured queues actually exists on the user account.
This should not be a concern for dry-run. This commit fixes this.
- #2630 
~~- [ ] Tests~~
~~- [ ] Checked for inclusion of relevant tests~~
~~- [ ] Checked for creation of associated docs updates~~
Fixes #2630 .
> fix wrangler publish --dry-run to not require authentication with queues

- .changeset/shaggy-hornets-drop.md
- package-lock.json
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/__tests__/jest.setup.ts
- packages/pages-shared/asset-server/handler.ts
- packages/pages-shared/environment-polyfills/miniflare-tre.ts
- packages/pages-shared/environment-polyfills/miniflare.ts
- packages/pages-shared/environment-polyfills/types.ts
- packages/pages-shared/package.json
This prevents the Pages Asset Server from performing unnecessary checks for preload/preconnect links. I've reproduced the unintended behavior and wrote an internal integration test to ensure that this change solves the problem.
- N/A
> Only check for <link> elements if response is HTML

- .changeset/quiet-cups-listen.md
- packages/wrangler/src/__tests__/d1/migrate.test.ts
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/migrations/create.tsx
- packages/wrangler/src/d1/migrations/list.tsx
A patch was applied to `wrangler d1 migrations apply` back in December to not require login - this PR adds a similar patch to `wrangler d1 migrations list`
Closes https://github.com/cloudflare/wrangler2/issues/2515
> [D1] Don't require login when running `wrangler d1 migrations list`

- .changeset/silver-peas-push.md
- package-lock.json
- packages/wrangler/package.json
- packages/wranglerjs-compat-webpack-plugin/package.json
Making this PR to see if build even passes
resolves https://github.com/cloudflare/wrangler2/pull/1971
> fix: try bump esbuild to 0.15.0

- .changeset/silver-peas-push.md
- package-lock.json
- packages/wrangler/package.json
- packages/wranglerjs-compat-webpack-plugin/package.json
bump esbuild to 0.16.3 (fixes a bug in esbuild's 0.15.13 release that would cause it to hang)
closes https://github.com/cloudflare/wrangler2/issues/1732
> chore: bump esbuild to 0.16.3

- .changeset/fluffy-beans-hide.md
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
Removes the annoying error when folks don't have a preview_database_id. We should trust users to know what they're doing.
**Associated docs issues/PR:**
N/A
> fix: don't force people to use preview_database_id

- .changeset/clever-doors-sip.md
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/templates/format-dev-errors.ts
- packages/wrangler/templates/serve-static-assets.ts
- packages/wrangler/templates/service-bindings-module-facade.js
(When I say middleware loader here, I mean the thing that powers `--test-scheduled`, not Wrangler's facade mechanism which D1 uses)
For modules mode, the middleware loader is split into two esbuild stages. The first "insertion" stage generates a file that imports the current entrypoint (either the user's worker or output of another facade, e.g. D1) and all the selected middleware. The second "loader" stage re-exports this output using
https://github.com/cloudflare/workers-sdk/blob/ff35b9d1f589e2d07e0d1935a1c53b90de01588a/packages/wrangler/templates/middleware/loader-modules.ts. Note all imports are marked as external in these stages, so no bundling occurs. Once all Wrangler facades are applied (not just the middleware loader), we run esbuild a final time to produce a Worker bundle.
Prior …
> Remove circular dependency when applying modules middleware loader

- packages/wrangler/templates/new-worker.ts
with the release of service bindings, it's helpful to have an immediate idea of how service bindings work.  especially in typescript land, where the type is useful info.  in my case, i found `Fetcher` to be the most accurate type, but feel free to correct me if this is invalid.
> docs(templates): add a service binding example to new-worker.ts

- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/migrations/helpers.ts
- packages/wrangler/src/d1/types.ts
- packages/wrangler/src/d1/utils.ts
- Added `previewDatabaseUuid` to our types
- the executeSql API now takes an object so it's less annoying to use
- Intentionally no changeset, just a quick refactor
> [D1] refactor migrations for preview

- .changeset/beige-bikes-perform.md
- packages/wrangler/src/__tests__/pages/publish.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/api/pages/publish.tsx
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/publish.tsx
**What this PR solves:**
Currently it is not possible to import `wasm` modules in either Pages
Functions or Pages Advanced Mode projects.
This commit caries out work to address the aforementioned issue by
enabling `wasm` module imports in `wrangler pages publish`. As a result,
Pages users can now import their `wasm` modules withing their Functions
or `_worker.js` files, and `wrangler pages publish` will correctly
bundle everything and serve these "external" modules.
```
import hello from "./hello.wasm"
export async function onRequest() {
const module = await WebAssembly.instantiate(hello);
return new Response(module.exports.hello);
}
```
**How to test:**
Use the fixtures projects provided in this PR
- `pages-functions-wasm-app`
```
npm run build
cd fixtures/pages-functions-wasm-app
npx …
```
> feat: Add wasm support in `wrangler pages publish`

- .changeset/clean-jokes-tan.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/api/mtls-certificate.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.ts
- packages/wrangler/src/mtls-certificate/cli.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/user/user.ts
- packages/wrangler/src/worker.ts
This pr does three things:
- adds an api for interacting with the SSL mTLS API (requires a new OAuth scope)
- uses the api for a new sub-command ('mtls-certificate') that allows uploading, listing, and deleting mTLS certificates
- supports new bindings (type: 'mtls_certificate') for worker uploads
NOTE: we are still waiting on the OAuth scope to be granted for Wrangler, so this shouldn't go just yet.
Associated docs issues/PR: https://github.com/cloudflare/cloudflare-docs/pull/7371
> Add api, commands, and binding support for mTLS certificates

- .changeset/thirty-hornets-behave.md
- fixtures/pages-functions-wasm-app/tests/index.test.ts
- packages/wrangler/src/__tests__/helpers/string-dynamic-values-matcher.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/pages/build.ts
**What this PR solves**
Currently it is not possible to import `wasm` modules in either Pages
Functions or Pages Advanced Mode projects.
This commit caries out work to address the aforementioned issue by
enabling `wasm` module imports in `wrangler pages functions build`.
As a result, Pages users can now import their `wasm` modules withing
their Functions or `_worker.js` files, and `wrangler pages functions
build` will correctly bundle everything and output the expected result
file.
```
import hello from "./hello.wasm"
export async function onRequest() {
const module = await WebAssembly.instantiate(hello);
return new Response(module.exports.hello);
}
```
**How to test**
This feature is behind the `[--experimental-worker-bundle]` flag
`npx wrangler pages functions build <options> …
> feat: Add wasm support for `pages functions build`

- .changeset/plenty-clouds-dance.md
- packages/wrangler/src/__tests__/d1/execute.test.ts
- packages/wrangler/src/__tests__/d1/migrate.test.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/migrations/create.tsx
- packages/wrangler/src/d1/migrations/helpers.ts
- packages/wrangler/src/d1/migrations/list.tsx
- packages/wrangler/src/d1/migrations/options.ts
- `npx wrangler init test-db`
- `npx wrangler d1 create test1`
- `npx wrangler d1 create test2`
- add the db named test2 to test1's definition as `preview_database_id`
- run `wrangler d1 execute test1 --preview --command "SELECT * from Customers"` or add migrations and run them
We don't know if we actually want to go down this path long-term with preview databases. It could be easier to clone&delete off a prod db instead, but we've already got people with preview dbs, so may as well support them properly.
- TODO once we decide whether we'll be taking preview databases down this path long term
Closes …
> fix: make it possible to run SQL against preview databases

- templates/worker-d1/README.md
Some PR's were not merged before moving over the templates, this handles the https://github.com/cloudflare/templates/pull/160 which removes the Beta message from the D1 template
> [Templates] Remove Beta Message D1

- .changeset/moody-bats-repair.md
- fixtures/pages-functions-app/public/_redirects
- fixtures/pages-functions-app/public/users/[id].html
- fixtures/pages-functions-app/tests/index.test.ts
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/__tests__/metadata-generator/parseRedirects.invalid.test.ts
- packages/pages-shared/__tests__/metadata-generator/parseRedirects.valid.test.ts
- packages/pages-shared/asset-server/handler.ts
- packages/pages-shared/metadata-generator/constants.ts
- packages/pages-shared/metadata-generator/parseRedirects.ts
- packages/pages-shared/package.json
This PR enables Pages _redirects to support proxying to files on a different url, for example pointing `/users/123` to `/users/id.html`, to enable a more dynamic functionality for static sites.
- https://github.com/cloudflare/cloudflare-docs/pull/7613
> feat (pages): Proxying (200) in _redirects

- packages/wrangler-devtools/patches/0001-Add-README-detailing-the-setup-process.patch
- packages/wrangler-devtools/patches/0002-Support-viewing-files-over-the-network.patch
- packages/wrangler-devtools/patches/0003-Show-fallback-image-on-Safari.patch
- packages/wrangler-devtools/patches/0004-Support-previewing-subrequest-responses.patch
- packages/wrangler-devtools/patches/0005-Better-Firefox-support-for-network-tab.patch
- packages/wrangler-devtools/patches/0006-DEVX-292-Remove-unsupported-network-UI.patch
- packages/wrangler-devtools/patches/0007-Remove-unsupported-profiler-UI.patch
- packages/wrangler-devtools/patches/0008-Show-an-overlay-on-the-memory-tab-in-Firefox.patch
- packages/wrangler-devtools/patches/0009-Support-theme-url-parameter-for-forcing-the-theme-fr.patch
- packages/wrangler-devtools/patches/0010-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
- packages/wrangler-devtools/patches/0011-Fallback-to-location-for-domain.patch
- packages/wrangler-devtools/patches/0012-Hide-unsupported-settings-UI.patch
- packages/wrangler-devtools/patches/0013-DEVX-380-Hide-debugger-sidebar-and-disable-breakpoin.patch
Adds a patch to DevTools that hides the breakpoint debugging panel, since it's not supported by the runtime.
- [Internal ticket](https://jira.cfdata.org/browse/DEVX-380)
- ~[ ] Tests~
- Manually tested
> Update devtools patches

- packages/wrangler/src/inspect.ts
Since Wrangler proxies the inspector, reloading the page open to Chrome DevTools won't trigger debugger initialisation events (because it's connecting to an extant session). This PR sends a `Debugger.disable` message to the remote when a new WebSocket connection is initialised, with the assumption that the new connection will shortly send a `Debugger.enable` event and trigger re-initialisation. The key initialisation messages that are needed are the `Debugger.scriptParsed` events, which I've verified are sent.
**How to test:**
- Run `wrangler dev` on a test worker
- Press `[d]`, which will open the inspector
- Replace the inspector domain with `devtools.devprod.cloudflare.dev`
- Verify that the Sources/Network/console tabs work after reloading the page
- …
> Allow Sources reload

- .changeset/happy-grapes-check.md
- packages/wrangler/src/create-worker-preview.ts
URLs from the Cloudflare API are usually relative to the zone. Sometimes the base zone will be grey-clouded, and so the host must be swapped out for the worker route host, which is more likely to be orange-clouded.
- Bugfix, so no docs changes needed
Fixes #2018, #2602, #2581
> Use correct host in exchange

- .changeset/nervous-scissors-roll.md
- packages/wrangler/src/__tests__/guess-worker-format.test.ts
- packages/wrangler/src/entry.ts
Wrangler automatically detects whether your code is a `modules` or `service-worker` format Worker based on the presence of a `default` `export`. This check currently works by building your entrypoint with `esbuild` and looking at the output metafile.
Previously, we were passing `format: "esm"` to `esbuild` when performing this check, which enables *format conversion*. This may introduce `export default` into the built code, even if it wasn't there to start with, resulting in incorrect format detections.
This change removes `format: "esm"` which disables format conversion when bundling is disabled: https://esbuild.github.io/api/#format.
We may want to use a package like [`es-module-lexer`](https://npmjs.com/package/es-module-lexer) in the future, but this issue is affecting users, and this …
> Disable format conversion when detecting format

- .changeset/new-news-drive.md
- packages/wrangler/scripts/bundle.ts
> Don't mangle constructor names with esbuild bundle

- packages/wrangler/src/inspect.ts
This updates Wrangler to point to our new fork of Chrome DevTools.
How to test:
- Run `wrangler dev` on a worker
- Press D
- Verify debugging functionality works as expected
- ~[ ] Tests~
- ~[ ] Changeset~
> Switch to new Devtools

- .eslintrc.js
- package-lock.json
- package.json
To prevent .only in tests from getting into main, added an ESLint rule that will error on them, CI will no longer pass if .only is present in any tests
> [Wrangler] Add ESLint no .only

- .changeset/strong-stingrays-relate.md
- fixtures/pages-functions-app/public/here.html
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-plugin-example/functions/proxy-me-somewhere-else.ts
- packages/wrangler/templates/pages-template-plugin.ts
> Fix `next(param)` in Pages Plugins

- packages/wrangler/src/r2/helpers.ts
Adds `duplex: half` to r2 object put to workaround an undici change.
Fixes #2784
> Add duplex to r2 put

- .changeset/rare-houses-rest.md
- .github/workflows/test-old-node-error.yml
- packages/wrangler/bin/wrangler.js
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/test-old-node-version.js
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/pages/publish.tsx
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/dev/validate-dev-props.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/paths.ts
- packages/wrangler/src/publish/index.ts
- packages/wrangler/src/publish/publish.ts
This PR does two things:
1. Renames the `--node-compat` CLI/config option _internally_ to `legacyNodeCompat`. Nothing changes externally. You still invoke it with `--node-compat` or `node_compat`. We maybe want to think about moving this to `experimental` as we stabilize the`dev()` API, but that discussion can happen elsewhere.
2. Marks any imports prefixed with `node:` as external when bundling with the `nodejs_compat` compatibility flag.
- https://github.com/cloudflare/workerd/pull/208
- https://github.com/cloudflare/miniflare/issues/473
> Add support for `node:*` imports with the `nodejs_compat` compatibility flag

- .changeset/grumpy-pillows-cheat.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/templates/d1-beta-facade.js
- packages/wrangler/templates/middleware/middleware-miniflare3-json-error.ts
This PR upgrades `@miniflare/tre` (Miniflare 3) to [`3.0.0-next.12`](https://github.com/cloudflare/miniflare/releases/tag/v3.0.0-next.12), incorporating changes from [`3.0.0-next.11`](https://github.com/cloudflare/miniflare/releases/tag/v3.0.0-next.11).
Notably, this brings the following improvements to `wrangler dev --experimental-local`:
- **Adds support for Durable Objects:** technically `workerd`/Miniflare 3 already supported Durable Objects, but Miniflare 3 didn't implement the `durableObjectsPersist` option required by Wrangler (#2403, #2458)
- **Adds support for D1:** this requires a few minor changes to the D1 facade, as `workerd` requires full URLs when `fetch`ing with service bindings (#2667)
- **Fixes an issue blocking clean exits and script reloads:** using `SIGINT` instead of …
> chore: upgrade to `@miniflare/tre@3.0.0-next.12`

- .changeset/selfish-files-pump.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/type-generation.ts
- packages/wrangler/src/worker.ts
This allows you to add arbitary fields to the metadata uploaded with a worker.
[unsafe.metadata]
some_key = some_value
> wrangler: add metadata to the unsafe binding

- .changeset/mean-bananas-bake.md
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/miniflare-cli/index.ts
- packages/wrangler/src/pages/dev.ts
> Bring `pages dev` logging in line with `dev` proper's

- packages/wrangler/src/__tests__/middleware.test.ts
Super simple fix. Otherwise, you'll notice, that an `index.js` appears in the wrangler package every time you run tests.
> test(wrangler): ensure that middleware test does not write to the source directory

- .changeset/spicy-mangos-sip.md
- packages/wrangler/src/__tests__/d1/execute.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/user/user.ts
The previous link for Creating an API token in a non-interactive environment 404'd, and didn't show the user any useful information. This points the link to the correct one in the docs
- N/A
> fix API token guide link

- .changeset/brown-wasps-fail.md
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/deployments.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/init.ts
Have new view for `wrangler deployment view` command
Example output
```
⛅️ wrangler 2.12.0
🚧`wrangler deployments` is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
Deployment ID: 07d7143d-0284-427e-ba22-2d5e6e91b479
Created on:    2023-03-02T21:05:15.622446Z
Author:        jspspike@gmail.com
Source:        Upload from Wrangler 🤠
------------------------------------------------------------
Author ID:          e5a3ca86e08fb0940d3a05691310bb42
Usage Model:        bundled
Handlers:           fetch
Compatibility Date: 2022-10-03
--------------------------bindings--------------------------
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "testr2"
[[kv_namespaces]]
id = "79300c6d17eb4180a07270f450efe53f"
binding = …
```
> Have deployment view output in table

- .changeset/gold-laws-sleep.md
- packages/wrangler/templates/gitignore
Add the `.wrangler` directory to the `gitignore` template.
> Include .wrangler directory in gitignore template

- .changeset/shaggy-horses-matter.md
- packages/wrangler/src/dev/local.tsx
`wrangler pages dev --experimental-local` will no longer fail with an error like `local worker: TypeError: generateASSETSBinding2 is not a function`.
> Fix `--experimental-local` with `wrangler pages dev`

- .changeset/fast-mayflies-kick.md
- .changeset/hot-berries-punch.md
- .changeset/lucky-ads-fry.md
- .gitignore
- .prettierignore
- fixtures/pages-functions-wasm-app/package.json
- fixtures/pages-functions-wasm-app/tests/index.test.ts
- fixtures/pages-plugin-example/functions/_middleware.ts
- fixtures/pages-plugin-example/index.d.ts
- fixtures/pages-plugin-example/package.json
- fixtures/pages-plugin-example/tsconfig.json
- fixtures/pages-workerjs-app/tests/index.test.ts
- fixtures/pages-workerjs-wasm-app/package.json
- fixtures/pages-workerjs-wasm-app/tests/index.test.ts
- packages/prerelease-registry/package.json
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/pages/publish.test.ts
- packages/wrangler/src/api/pages/publish.tsx
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/errors.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/pages/publish.tsx
This does two big things (and one little one):
- It removes the `--experimental-worker-bundle` option from Pages Functions. We now just always do this. It was temporarily added for us to test the new `_worker.bundle` upload format.
- It enables `--bundle` by default in `pages dev` and `pages publish`. This means that you're able to use Wasm etc. in `_worker.js` projects.
- Finally, it marks `.wasm` and `.bin` files as external when building a Plugin. We already do this with `assets:`, so there's prior art here, but this is ultimately only a stop-gap until we change the output format to an `--outdir` rather than an `--outfile` for Plugins. We'll follow up soon-ish with that.
- …
> Pages Functions Wasm cleanup

- .changeset/lucky-peas-compete.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
`npx wrangler publish --dry-run --outdir dist --assets public src/foo.ts` should produce a `dist/foo.js` rather than `dist/<internal-facade-name>.js`
- Fixes #2835
> Preserve entrypoint filename when building a Worker with --outdir

- packages/prerelease-registry/functions/routes/index.html
Updating the prerelease registry page to include also next-on-pages and pages-plugins (added in https://github.com/cloudflare/workers-sdk/pull/2731)
@GregBrimble 🙂 
Result:
> Update prerelease registry page

- .changeset/heavy-rockets-destroy.md
- packages/wrangler/src/pages/dev.ts
- Run `npm run dev` in `fixtures/pages-workerjs-app`
- Note the _lack_ of compile loop :)
> [wrangler] Fix compile loop with `_worker.js` and `wrangler pages dev`

- .changeset/spotty-walls-crash.md
- packages/wrangler/templates/d1-beta-facade.js
This PR makes it possible to query D1 from an Email Worker, assuming a binding has been setup.
As D1 is in alpha and not considered "production-ready", this changeset is a patch, rather than a minor bump to wrangler.
**Associated docs issues/PR:**
- N/A
Fixes #2876
> feat: Add D1 binding support to Email Workers

- .changeset/curly-buses-crash.md
- packages/wrangler/src/pages/upload.tsx
Just replaces our `console.debug`s with `logger.debug`. 
N/A
> Fix debug logging for Pages upload

- .github/workflows/pullrequests.yml
Running with an idea from @penalosa - this PR changes the pullrequest.yml GitHub action so that it caches all the node_modules for the project rather than running npm install.
Notably, we cache based on a hash of the package-lock file along with the current OS and node version.
**Are there any other variables that we should incorporate into the key?**
Also, if the cache misses then we run a full `npm ci` to ensure a clean reliable set of node modules.
> Speed up npm

- .changeset/brown-wasps-fail.md
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/helpers/mock-dialogs.ts
- packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/deployments.ts
- packages/wrangler/src/index.ts
> Add message to rollback and restructre rollback commands

- .changeset/afraid-readers-warn.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
Mark cloudflare-specific js module as external so that scripts can be published that reference it.
`import { EmailMessage } from "cloudflare:email";`
- ~~[ ] Checked for creation of associated docs updates~~ : no documentation needed for this just yet. I assume when the first official `cloudflare:..` prefixed modules are announced there will be docs associated with it.
> allow cloudflare-specific js module

- .changeset/many-pens-unite.md
- packages/wrangler/src/d1/migrations/apply.tsx
Previously, if `wrangler d1 migrations apply --local` failed, you'd see something like:
```
❌ Migration 0000_migration.sql failed with following Errors
┌──────────┐
│ Error    │
├──────────┤
│ D1_ERROR │
└──────────┘
```
We'll now show the SQLite error that caused the failure:
```
❌ Migration 0000_migration.sql failed with following Errors
┌───────────────────────────────────────────────┐
│ Error                                         │
├───────────────────────────────────────────────┤
│ Error: SqliteError: unknown database "public" │
└───────────────────────────────────────────────┘
```
N/A
Fixes #2772
> [wrangler] Display cause when local D1 migrations fail to apply

- .changeset/cool-cobras-deliver.md
- packages/wrangler/src/api/dev.ts
Fixes N/A - Found [in the Discord](https://canary.discord.com/channels/595317990191398933/799437470004412476/1087684607698284554)
**What this PR solves / how to test:** Pages dev previously forced people to use local mode, however this got broken somewhere in the past. This pull fixes it, and prevents people from using remote mode once again
TLDR; Force local was incorrectly put in the `startApiDev` version of unstable_dev instead of the one that Pages uses
- N/A
> [wrangler]: Fix local mode force on pages dev

- packages/prerelease-registry/functions/utils/repoAllowlist.ts
This just addes the https://github.com/cloudflare/itty-router-openapi to the prerelease allow list
> Add itty-router-openapi to prerelease allow list

- packages/wrangler-devtools/package.json
In the package.json for wrangler-devtools the private field was set to string rather than a boolean, boolean will be expected for certain tools and systems.
> boolean fixup

- packages/wrangler/src/d1/create.tsx
`wrangler d1 create --help` prints:
```
Create D1 database
Positionals:
name  The name of the new DB  [string] [required]
Flags:
-j, --experimental-json-config  Experimental: Support wrangler.json  [boolean]
-c, --config                    Path to .toml configuration file  [string]
-e, --env                       Environment to use for operations and .env files  [string]
-h, --help                      Show help  [boolean]
-v, --version                   Show version number  [boolean]
Options:
--primary-location-hint  A hint for the main location of the new DB. Options:
weur: Europe (west)
eeur: Europe (east)
apac: Asia Pacific
wnam: North America (west)
enam: North America (east)
[string] [choices: "weur", "eeur", "apac", "wnam", "enam"]
```
> [wrangler] use choices to pick the location hint

- .github/changeset-version.js
This workflow was failing whenever there was a minor release to wrangler and a patch release to a package that depended upon wrangler. It was caused by a bug in npm that was resolved in v8.5.0. See https://github.com/npm/cli/issues/4379 and https://github.com/npm/cli/pull/4371. The error looks like: `No matching version found for wrangler@^2.15.0.`
> ci: fix the release github workflow

- .changeset/unlucky-boats-beg.md
- packages/wrangler/src/miniflare-cli/index.ts
> Fix Durable Object dev registry websockets

- .gitignore
- package-lock.json
- packages/quick-edit-extension/package.json
- packages/quick-edit-extension/scripts/bundle.ts
- packages/quick-edit-extension/scripts/tsconfig.json
- packages/quick-edit-extension/src/cfs.ts
- packages/quick-edit-extension/src/raw.d.ts
- packages/quick-edit-extension/tsconfig.json
- packages/quick-edit/patches/0001-Add-Custom-workbench-for-Cloudflare.patch
- packages/quick-edit/patches/0002-Remove-Themes-from-Setting-SubMenu.patch
- packages/quick-edit/patches/0003-Removed-Menu.patch
- packages/quick-edit/patches/0004-Remove-Profile-from-Setting-SubMenu.patch
- packages/quick-edit/patches/0005-Remove-Account-Extension.patch
- packages/quick-edit/patches/0006-Remove-Debug-Icon-other-default-views.patch
- packages/quick-edit/patches/0007-Remove-Source-Control.patch
- packages/quick-edit/patches/0008-Remove-Custom-Menu-hamburger.patch
- packages/quick-edit/patches/0009-Remove-Extensions-Icon-Quick-Access.patch
- packages/quick-edit/patches/0010-Remove-dead-code.patch
- packages/quick-edit/patches/0011-Support-project-wide-typescript-on-web.patch
- Adds support for Typescript checking, via JSDoc annotations
- In particular, this patches the VSCode typescript extension to work without `SharedArrayBuffer`, and loads two read-only files into Worker workspaces, `jsconfig.json` and `workers-types.d.ts`
> [quick-edit] Typescript support through JSDoc 

- .changeset/orange-plants-flash.md
- packages/wrangler/src/__tests__/d1/migrate.test.ts
- packages/wrangler/src/d1/backups.tsx
- packages/wrangler/src/d1/create.tsx
- packages/wrangler/src/d1/delete.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/list.tsx
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/migrations/helpers.ts
D1 commands don't read from config - this is bad when a user has multiple accounts, and an account_id defined. `wrangler publish` for example handles this properly.
> [wrangler] teach wrangler's D1 commands about config

- .changeset/six-toes-yawn.md
- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/prereleases.yml
- .github/workflows/release.yml
- packages/wrangler/scripts/bundle.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/docs/helpers.ts
- packages/wrangler/src/docs/index.ts
- packages/wrangler/src/index.ts
I basically taught wrangler how to do a "I'm feeling lucky" search
How it works:
- The wrangler user enters `wrangler docs <command>`
- wrangler sends an API request to Algolia's index of https://developers.cloudflare.com/workers/wrangler/
- wrangler sends the user to the first URL in the index that matches the search term
Here's what it looks like in action:
https://user-images.githubusercontent.com/3822106/207370613-eacccce9-ddea-4c9b-82d1-de476ff52fa2.mov
@rita3ko FYI
> [wrangler] teach wrangler to search docs

- .github/workflows/prereleases.yml
Upon merging https://github.com/cloudflare/workers-sdk/pull/3004, I realised our prereleases were missing this bit to inject environment variables into the bundle.
> [wrangler] fix: prereleases don't get vars injected at build time

- .github/workflows/prereleases.yml
Upon merging https://github.com/cloudflare/workers-sdk/pull/3004 and https://github.com/cloudflare/workers-sdk/pull/3076, I realised our prereleases were missing this bit to inject environment variables into the bundle.
> [wrangler] fix: prereleases don't get vars injected at build time pt 2

- .changeset/tame-pumas-happen.md
- packages/pages-shared/__tests__/metadata-generator/parseRedirects.invalid.test.ts
- packages/pages-shared/__tests__/metadata-generator/parseRedirects.valid.test.ts
- packages/pages-shared/metadata-generator/parseRedirects.ts
- packages/pages-shared/metadata-generator/validateURL.ts
This PR implements validation to prevent people from having `/* /index.html 200` as a redirect rule in Pages, as this will cause an infinite amount of redirects when the API starts accepting 200 status codes in _redirects. This prevents breaking a number of projects that migrated from Netlify, etc. that are using this rule (for no reason - pages does the behaviour anyway)
> Feat(pages-shared): Validate `/* /index.html`

- CODEOWNERS
Fixes: N/A
Adds the `@cloudflare/wrangler-admins` team as codeowner to the wrangler CHANGELOG file. The result is that wrangler-admins will be automatically set as requested reviewers for any Version Packages PRs.
> Add wrangler-admins as codeowner

- README.md
Fixes: N/A
**What this PR solves / how to test:** Adds a link to the workers-sdk GH project board to the README.
> Update README with link to GH Project Board

- .changeset/clever-radios-cover.md
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/kv/helpers.ts
- packages/wrangler/src/sites.ts
Fixes #2223
Fixes #2245
This PR aims to improve the reliability of syncing assets to a Workers Sites KV namespace when publishing a Worker. In particular...
- When splitting upload into buckets, just store the file path, not the full content. This means we have to read the contents twice, but avoids buffering all content before uploading, causing OOMs.
- Limit in-flight bulk upload requests to 5, avoiding `Too many bulk operations already in progress.` error.
- Fix logging of upload progress. Previous, progress was logged per upload bucket, which doesn't really make sense to end users. Now, upload progress is across all files in all buckets.
- Only log first 100 changed assets by default. The rest can be shown by setting `WRANGLER_LOG=debug`. This …
> Improve Workers Sites asset sync reliability

- .changeset/funny-spies-melt.md
- packages/wrangler/src/utils/render.ts
Fixes #2907
If the components passed to `renderToString()` resulted in an empty string, we were incorrectly converting that to a warning message. This message should only apply if there is a problem with rendering and it returns `undefined`.
To test run the following commands:
```bash
npx wrangler d1 create TEST_DB 
npx wrangler d1 execute TEST_DB --command "DROP TABLE IF EXISTS test_table"
```
You should not see the "value of stdout.lastframe() is undefined" message.
> fix: do not render "value of stdout.lastframe() is undefined" if the output is an empty string

- .changeset/metal-buckets-fly.md
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/bundle.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
> **Note** continuation of https://github.com/cloudflare/workers-sdk/pull/3100
___
Fixes [cloudflare/next-on-pages#199](https://github.com/cloudflare/next-on-pages/issues/199)
* Fixes passing the `nodejs_compat` flag through to `wrangler pages functions build`
* Also improve the error message so that for pages it doesn't ask to update wrangler.toml
> nodejs compat functions build

- .changeset/short-bottles-smell.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/worker.ts
Allows a `placement` object in the wrangler config with a mode of `off` or `smart` to configure Smart placement.
Allows users to enable [Smart placement](https://developers.cloudflare.com/workers/platform/smart-placement/) via wrangler.
> [wrangler] feat: add support for placement in wrangler config

- .changeset/witty-pumpkins-swim.md
- packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/createTail.ts
- packages/wrangler/src/tail/printing.ts
If a tail enters sampling mode, it will forward a message saying that it's in sampling mode. The tail will send message every time the messages reaches over 100 requests per second. If we feel like that's not enough we could change this to happen periodically every 5 seconds.
One thing to keep in mind is that this will add messages to the tail stream that aren't actual trace events. Not sure if that is a concern, especially since the the non `--pretty` format is structured with event types which has different fields per message.
~~Also for the `--pretty` format we consider using something like ink to pin the sampling mode message? Not sure if that would be too much of a breaking change for users who might pipe the output of `--pretty` format to other tools~~
**Reviewer has performed the …
> Add output for tail being in sampling mode

- .changeset/stale-onions-wait.md
- packages/wrangler/src/d1/constants.ts
- packages/wrangler/src/d1/create.tsx
- packages/wrangler/src/d1/types.ts
The changeset uses `fix` instead of `feat` as this is an experimental feature on top of an alpha product, and not recommended for production data and traffic.
Output:
```
npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/4923592092/npm-package-wrangler-3168 d1 create apac-db --location apac
✔ Select an account › xxxx@gmail.com's Account
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/workers-sdk/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
✅ Successfully created DB 'apac-db' in region APAC
[[d1_databases]]
binding = "DB" # …
```
> [wrangler] teach d1 about location hints

- .changeset/serious-crews-mix.md
- packages/wrangler/src/constellation/deleteProjectModel.ts
- packages/wrangler/src/constellation/index.ts
- packages/wrangler/src/constellation/listModel.tsx
- packages/wrangler/src/constellation/uploadModel.tsx
Improved help for constellation commands and added optional parameter on model upload to specify a model description.
> [wrangler] fix: constellation command help

- .changeset/tough-snails-check.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/constellation.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/constellation/utils.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/type-generation.ts
- packages/wrangler/src/user/user.ts
- packages/wrangler/src/worker.ts
This introduces the Constellation AI bindings. Multiple of them can be added to a worker, each one configured with a project id.
There is also a facade that is inserted in the worker code in order to interact with the internal binding.
-  Checked for inclusion of relevant tests
-  Checked for inclusion of a relevant changeset
-  Checked for creation of associated docs updates
-  Manually pulled down the changes and spot-tested
> [wrangler] feat: Constellation AI bindings

- .changeset/spicy-peaches-worry.md
- packages/wrangler/bin/wrangler.js
Closes #2705
Closes DEVX-623
Previously, if Wrangler was installed globally _and_ locally within a project, running the global Wrangler would instead invoke the local version. This behaviour was contrary to most other JavaScript CLI tools and could be quite confusing.
Not sure if we had docs for the delegation behaviour, so none.
> [wrangler] feature: remove delegation to locally installed versions

- .changeset/grumpy-jobs-change.md
- packages/wrangler/src/index.ts
- packages/wrangler/src/update-check.ts
Closes DEVX-624
This change logs a much more noticeable warning when a new major version is available, with instructions for update.
N/A
> [wrangler] feature: warn when a new major version is available

- .changeset/ninety-worms-beam.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/user/user.ts
Fixes #3177
Wrangler v3 removes Miniflare 2 in favour of Miniflare 3 using `workerd`. Unfortunately, `workerd` doesn't run in the browser _(yet 😉)_, and WebContainers don't support remote mode yet. This change adds a warning when we detect `wrangler dev` running inside a WebContainer, so users know what's going on. Also removes some unused OAuth code.
N/A
> [wrangler] feature: warn when trying to use `wrangler dev` inside a WebContainer

- .changeset/moody-ducks-pull.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/get-local-persistence-path.ts
- packages/wrangler/src/pages/dev.ts
Wrangler will now persist local KV, R2, D1, Cache and Durable Object data in the `.wrangler` folder, by default, between reloads. This persistence directory can be customised with the `--persist-to` flag. The `--persist` flag has been removed, as this is now the default behaviour. To test, run `wrangler dev --(experimental-)local`, 
None yet, but maybe we want one?
> [wrangler] feature: enable persistent storage in local mode by default

- .changeset/polite-beans-own.md
- packages/wrangler/src/__tests__/generate.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/generate/index.ts
- packages/wrangler/src/init.ts
Deprecate the init command and run C3 where we can reliably fallback
~~This should be merged in v3 only~~ No longer a breaking change with —delegate-c3 defaulting to false (thanks 
@penalosa and @petebacondarwin!)
The entire command will be deprecated.
Only part of it's functionality is being delegated to C3 — when the project doesn't exist on disk yet.
If the project does exist (a wrangler.toml is found in the creationDirectory), init's functionality is preserved. We will delegate this functionality to another command within wrangler in the future — before v4 when the init command is removed.
~~Tests still TODO~~
> [wrangler] Deprecate the init command

- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/init.ts
Fixes #2886 
This PR adds support for downloading multi-module scripts from the API. The API endpoint already returns formdata, and the previous implementation in wrangler `throw`s when that formdata contains more than one entry. Therefore, this is not a breaking change requiring a major version bump (maybe a minor?).
Unfortunately, that block of code was not tested. The mocked API response was only ever a text response inferred to be one file with the filename hardcoded.
Regarding tests, since MSW does not support the `Response#formData` method and there's no (easy/understandable) way to hook into MSW's response (it's all functional objects, no class instances), **I've added an `if` statement to the runtime code** which turns the MSW MockedResponse into a undici Response. **This won't …
> [wrangler] Handle multi-module workers when downloading scripts

- packages/quick-edit/functions/_middleware.ts
Adding support for types in Quick Edit (not TS) resulted in some files showing up in everyone's file structure, this excludes them from the VSCode files shown.
Fixes # DEVX-650
> [Editor] Hide type files

- packages/wrangler/src/dev.tsx
This PR fixes a minior issue, a missing space, with the error message we show if it detects it runs in a WebContainer.
> chore: add missing space to webcontainer error message

- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
Previously the preview proxy worker would follow redirects rather than pass them onto the client. This adds `redirect: "manual"` to its fetches.
Note: the test only fails with `experimentalLocal`, but that can be added in v3
- ~[ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))~
> Use manual redirects in the proxy worker

- .changeset/strange-schools-dream.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/publish/publish.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/worker.ts
This reverts commit 521fc8d572819fadddb18d59a26e26067004819c
which reverted commit 0589b48f378d28c06940c09719ee110a07db51e3
Effectively re-enabling the support for tail_consumers, described here https://github.com/cloudflare/workers-sdk/pull/3199
> Revert revert of tail_consumers support

- package-lock.json
- package.json
Very small update to the eslint dependencies.
We have to pin the `eslint-plugin-import` package to 2.26.x because 2.27.0 introduces a nasty regression that re-orders all (but only) `type` imports incorrectly.
> ci: update eslint dependencies

- .changeset/empty-kangaroos-sip.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/publish.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/create-worker-upload-form.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/worker.ts
Adds key "outbound" to the dispatch_namespaces binding section
Additionally, outbounds can declare params (string[]) that will be forwarded from the dispatcher to the outbound worker
Fixes WC-1262
> Support outbounds for dispatch namespace bindings

- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/helpers/interactive.ts
- packages/create-cloudflare/src/pages.ts
Currently, if you specify some arguments via the command line, the interactive prompt pertaining to the argument is omitted from the output entirely, so it's not clear to the user that their input is being used. For example, specifying the `projectName` positional argument wouldn't show in the output. Here's an example of how it looks after this change:
> [C3] Printing dummy questions for values provided via command line

- .changeset/late-boats-tell.md
- packages/create-cloudflare/src/frameworks/versionMap.json
Installing version next of Angular fails during installation because of peer-deps error.
> Update versionMap.json to include angular @16.0.x rather than @next

- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/edge-preview-authenticated-proxy/worker-configuration.d.ts
- packages/edge-preview-authenticated-proxy/wrangler.toml
Sometimes preview tokens can exceed the size limits for cookies. This store only an ID in a cookie, with the actual token stored in an attached KV namespace
- ~[ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))~
> [edge-preview] Support tokens > 4096 bytes by storing in a KV lookup table

- packages/create-cloudflare/package.json
Adds a `prepublishOnly` task that builds before publishing. Also includes the manual version bump to `2.0.4` that was required for a hotfix (due to publishing not working).
> [C3] Build before publishing

- .changeset/mighty-goats-fry.md
- packages/create-cloudflare/src/frameworks/remix/index.ts
**What this PR solves:**
With `create-remix` we're wanting to move away from having built-in templates, so your current usage of the CLI will break in the future.
In the next major version (which I'm currently working on) we're removing the template prompt entirely, and we're removing shorthands like `create-remix --template cloudflare-pages`. Instead, we're wanting to surface more of the community ecosystem, and allow third parties to take more ownership of their templates.
This PR is intended to future-proof the `--template` option so you don't need to worry about updating this when you upgrade in the future. This also helps to further normalise full URLs for Remix templates in the meantime until our next major release goes out.
> [C3] fix: use full Remix template URL
