cloudflare/workers-sdk

- packages/solarflare-theme/themes/cloudflare-light-color-theme.json
Default color was an off-white which was basically invisible with the editors white background. The fallback color for the editor is now a contrasting orange.
Fixes # DEVX-700
In a JavaScript/TypeScript file in the new Quick Editor create a line of code like this 
```ts
RegEx(`\n data:${NAME.length}=(?<group>control|test);`).test(
cookie
);
```
The length is considered a "support variable" token which was not defined and therefore falling back to the "other" & "support" scope. 
> Fix off-white fallback color

- .changeset/real-rockets-argue.md
- packages/create-cloudflare/src/common.ts
C3 would recommend to use `npm run dev` previously instead of `npm run start`, which is what all the templates use. Happy to invert this if preferred.
> fix(create-cloudflare): use correct start command

- .changeset/early-rocks-crash.md
- .github/workflows/test-c3.yml
- .vscode/settings.json
- package-lock.json
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/package.json
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/helpers/__tests__/command.test.ts
- packages/create-cloudflare/src/helpers/cli.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/helpers/interactive.ts
- packages/create-cloudflare/src/helpers/poll.ts
- packages/create-cloudflare/src/pages.ts
- packages/create-cloudflare/src/types.ts
When create-cloudflare deploys to Pages, it can take a while before the website is ready to be viewed.
This change adds back in polling of the site and then opening a browser when the URL is ready.
Test by building create-cloudflare and then generating and deploying a web framework project that will deploy to Pages.
> [C3] better polling for Pages deployments

- packages/wrangler/e2e/deploy.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/vite.config.ts
- packages/wrangler/package.json
This PR updates our manual E2E tests for v3.
- Adds appropriate flags to `wrangler init`
- Replaces `wrangler publish` with `wrangler deploy`
- Increases the test timeout to 1 minute to allow time for `workerd` to install on `init` tests (was also seeing some tests taking about ~15s)
- Use `--single-thread` instead of `--no-threads` with `vitest` upgrade (see https://vitest.dev/config/#singlethread)
- N/A
> fix: update deployment E2E tests for v3

- .changeset/dull-carrots-shout.md
- package-lock.json
- packages/wrangler/src/d1/migrations/apply.tsx
* `create` uses `experimental-backend`
* Blog uses it
* Release notes use it: https://github.com/cloudflare/workers-sdk/releases/tag/wrangler%403.0.0
Fixing to be consistent.
> d1: make experimental-backend flag consistent

- .changeset/lazy-boxes-deny.md
- packages/wrangler/src/__tests__/pages/project-delete.test.ts
- packages/wrangler/src/pages/index.ts
- packages/wrangler/src/pages/projects.tsx
Adds a command to delete Pages projects from the command line 
- https://github.com/cloudflare/cloudflare-docs/pull/8996
> [Pages] feat: add `wrangler pages project delete` command

- .changeset/tasty-pandas-cough.md
- packages/wrangler/src/__tests__/pages/project-create.test.ts
- packages/wrangler/src/pages/projects.tsx
- packages/wrangler/src/pages/types.ts
This PR adds the ability to specify a `--compatability-flags` option to `wrangler pages project create` so that we can support project creation workflows that don't involve visiting the dashboard. In particular we need this for c3 where some of the frameworks we support require the `nodejs_compat` flag. 
This work would [unblock this PR](https://github.com/cloudflare/workers-sdk/pull/3245) which bumps c3 support to the latest version of `nextjs`.
- https://github.com/cloudflare/workers-sdk/pull/3245
- Checked for …
> [wrangler] Add compatibility flags option to pages create command

- packages/create-cloudflare/src/helpers/__tests__/command.test.ts
- packages/create-cloudflare/src/helpers/command.ts
Fixes a regression introduced by [4082cfcb](https://github.com/cloudflare/workers-sdk/commit/4082cfcbdf08740d4a608d3d87df22e51ad0ce4a) that breaks any framework not using compatibility flags. This introduces some code which invokes `runCommand` with trailing whitespace, which it incorrectly interprets as an extra command line argument. This in turn causes `wrangler pages project create` to fail unless compat flags are specified.
- https://github.com/cloudflare/workers-sdk/pull/3245
- 
- Checked for creation of …
> [c3] handle trailing whitespace in runCommand helper

- packages/create-cloudflare/templates/common/ts/wrangler.toml
I have to assume that this section was intended to be about R2? cc @jonesphillip 
- Previously, running create cloudflare gave you a `wrangler.toml` that included Queues, KV, etc., but didn't have R2. Looks like the intent was to include a section, but it didn't quite have the right format. This PR updates the `wrangler.toml` that is used when scaffolding out an example app.
> Fix R2 bucket example in create-cloudflare wrangler.toml

- .changeset/flat-singers-doubt.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/index.ts
Closes #3169
I didn't run wrangler rollback, so the message doesn't seem applicable to me:
```
🚧`wrangler rollback` is a beta command. Please report any issues to https://github.com/cloudflare/workers-sdk/issues/new/choose
```
> fix: wrangler rollback shouldn't print its warning in the global menu

- .changeset/rich-tips-yell.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
This PR prevents uploads that enable smart placement and include cron triggers. Cron triggers are currently unsupported with smart placement. 
> [wrangler] Prevents uploads with both cron triggers and smart placement enabled

- .changeset/cuddly-weeks-behave.md
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/dev.ts
Fixes #3258.
Avoid unnecessary rebuilding pages functions in wrangler pages dev
This was happening as we were using esbuild's watching mechanism + our own custom watcher which was causing high cpu usage and duplicate rebuilds on any file changes.
We have our own custom watcher setup in dev mode so that we can watch for new files that are added, as esbuild's watcher doesn't catch this
> Fix: Avoid unnecessary rebuilding pages functions in wrangler pages dev

- CONTRIBUTING.md
This simply updates the contributing guide to use the new repo name `workers-sdk` instead of `wrangler2`.
> chore: rename repo in contributing guidelines

- .github/workflows/pullrequests.yml
The `matrix.os` was being used to hash which only Linux is running in checks and there is no longer a matrix.
> GH workflow `matrix` replaced with `runner`

- .changeset/seven-houses-end.md
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/frameworks/gatsby/index.ts
- packages/create-cloudflare/src/helpers/interactive.ts
- packages/create-cloudflare/src/pages.ts
- packages/create-cloudflare/src/types.ts
- packages/create-cloudflare/src/workers.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Fixes #3333 #3319 
When `wrangler init … -y` delegates to C3, it now sets a hidden flag `–wrangler-defaults` which will skip all prompts in C3. Fixes #3333
Test by running `wrangler init -y` or `wrangler init --from-dash test -y` and confirm the process exits without user input.
Also, C3 now allows to use an existing directory if it is empty. Fixes #3319
Test by setting the project directory to 1. an empty directory, and 2. a non-empty directory. The former succeeds while the latter will fail
- Checked for inclusion of a …
> [C3 + wrangler] `wrangler init … -y` delegates to C3 without prompts (respects the `-y` flag)

- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/common.ts
* Fix a minor typo (`Typescript` -> `TypeScript`)
* Clarify what `git` is and why that choice is relevant.
> c3: clearer language during init flow

- .changeset/hungry-pigs-refuse.md
- fixtures/pages-functions-app/functions/middleware-data/additional-data.ts
- fixtures/pages-functions-app/functions/middleware-data/bad-data.ts
- fixtures/pages-functions-app/functions/middleware-data/merge-data.ts
- fixtures/pages-functions-app/functions/middleware-data/mutate-data.ts
- fixtures/pages-functions-app/tests/index.test.ts
- packages/wrangler/templates/pages-template-plugin.ts
- packages/wrangler/templates/pages-template-worker.ts
Fixes #2797
Previously, Pages Functions exposed `context.data` like this:
```js
const data = {};
const context = {
...,
data
};
```
Which meant that users could set `context.data.foo = false` and it would work fine, since it's just a reference to the top-level `data` per request, but the second they tried to override `context.data` entirely, such as `context.data = {foo: false}`, the reference to the original `data` is lost, so this data wouldn't actually show up.
This PR fixes that by adding a getter/setter pair to `data`, so that folks can override this without any issues.
- Checked for …
> fix(wrangler): allow direct mutation of context.data with Pages Functions

- packages/wrangler/src/config/index.ts
- packages/wrangler/src/constellation/createProject.tsx
- packages/wrangler/src/constellation/deleteProjectModel.ts
- packages/wrangler/src/constellation/listModel.tsx
- packages/wrangler/src/constellation/uploadModel.tsx
- packages/wrangler/src/constellation/utils.ts
- packages/wrangler/src/d1/backups.tsx
- packages/wrangler/src/d1/create.tsx
- packages/wrangler/src/d1/delete.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/info.tsx
- packages/wrangler/src/d1/list.tsx
- packages/wrangler/src/d1/utils.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/kv/index.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/deploy.tsx
- packages/wrangler/src/pages/deployment-tails.ts
- packages/wrangler/src/pages/deployments.tsx
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/filepath-routing.test.ts
- packages/wrangler/src/pages/functions/filepath-routing.ts
- packages/wrangler/src/pages/projects.tsx
- packages/wrangler/src/pages/upload.tsx
- packages/wrangler/src/tail/index.ts
With new monorepo setup and config updates, the import order is now being enforced and can auto fix. (needed to be run --fix in local package)
> ESLint Import Order

- .changeset/six-horses-punch.md
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/fetch-graphql-result.test.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/d1/info.tsx
- packages/wrangler/src/d1/types.ts
output for experimental dbs:
```
┌───────────────────┬──────────────────────────────────────┐
│                   │ xxxx-xxxx-xxxx-xxxx-xxxx             │
├───────────────────┼──────────────────────────────────────┤
│ name              │ northwind                            │
├───────────────────┼──────────────────────────────────────┤
│ version           │ beta                                 │
├───────────────────┼──────────────────────────────────────┤
│ num_tables        │ 13                                   │
├───────────────────┼──────────────────────────────────────┤
│ file_size         │ 33.1 MB                              │
├───────────────────┼──────────────────────────────────────┤
│ running_in_region │ WEUR                                 │ …
```
> fix: add 24h read/write metrics to d1 info

- .changeset/breezy-coins-tan.md
- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
This PR updates the `edge-preview-authenticated-proxy` Worker to properly handle cross-origin requests with arbitrary headers. The HTTP tab in the Quick Editor allows users to provide headers, but these requests were being blocked due to same-origin policy.
> [quick-edit] Fix CORS headers to allow arbitrary headers in raw HTTP preview requests

- templates/worker-typescript/src/index.test.ts
Worker TypeScript test was failing and type error indicated it was related to the input of the workers.dev
Part of #3441 
> [Templates] Fix Failing Test

- .github/version-script.js
- .github/workflows/prerelease-create-cloudflare.yml
This PR adds a new Github action that will publish the create-cloudflare package to npm using the `beta` dist-tag whenever a commit is merged to `main`.
It is only possible to test this PR by merging the PR 😱 
It is slightly annoying that a new beta release will be published on every merged PR rather than only ones that affect create-cloudflare, but this is also the case for the `wrangler` package right now.
Not applicable
- [N/A] Tests
- [N/A] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
- …
> ci: publish beta releases of create-cloudflare to npm

- packages/wrangler-devtools/Makefile
It looks like we currently fail on tests because a new set of commits in https://chromium.googlesource.com/chromium/tools/depot_tools.git has broken our workflow in the DevTools publish action. We don't need to be on the bleeding edge here so we are pinning it to a commit that works for now.
> Pin chromium/tools/depot_tools to a specific commit

- package.json
Turns back on the fixture tests, except for `local-mode-tests` and `no-bundle-import`. These need a bit more of an investigation into how to make them pass reliably.
> Turn back on fixture tests bar local-mode-tests and no-bundle-import

- packages/wrangler/package.json
Bump e2e tests to a 4 minute timeout to reduce flakiness
> Bump e2e timeout

- packages/create-cloudflare/src/frameworks/angular/index.ts
- packages/create-cloudflare/src/frameworks/versionMap.json
This commit updates the logic that modifies an app config file to add the `provideHttpClient(withFetch())` call, which enables the `fetch` in HttpClient. Since the `withFetch()` feature is available starting from Angular v16.1.0, the framework version was also updated.
// cc @petebacondarwin
> refactor: enable `fetch` in Angular's HttpClient

- .changeset/fuzzy-flowers-kneel.md
- fixtures/pages-simple-assets/tests/index.test.ts
- packages/wrangler/src/miniflare-cli/assets.ts
Fixes https://cflare.co/24935
Ensures only files from within the build output directory can be served in `wrangler pages dev`.
> Prevent `wrangler pages dev` from serving asset files outside of the build output directory

- .changeset/weak-dolphins-carry.md
- fixtures/pages-workerjs-directory/package.json
- fixtures/pages-workerjs-directory/public/_worker.js/index.js
- fixtures/pages-workerjs-directory/tests/index.test.ts
- packages/wrangler/src/pages/dev.ts
Allows setting a D1 database ID when using `wrangler pages dev` by providing an optional `=<ID>` suffix to the argument like `--d1 BINDING_NAME=database-id`.
This is useful when a Worker and a Pages project are sharing local dev state (`--persist-to`) location.
> Allow setting d1 database id in pages dev

- fixtures/routing-app/package.json
- fixtures/shared/package.json
- package-lock.json
We accidentally published these in the last release. This PR marks these packages as private to prevent that from happening in the future.
> Mark fixtures-shared and routing-app as private

- .changeset/lovely-trees-fail.md
- package-lock.json
- packages/create-cloudflare/package.json
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/helpers/cli.ts
- packages/create-cloudflare/src/helpers/interactive.ts
Fixes #3394.
This fixes a couple of things:
1. Formats the project name as a directory and fixes an issue where leading spaces were rendered as `-` in some terminals.
2. Fixes a bug where the default value of a project directory couldn't be selected in interactive mode
3. Displays the default value for text prompts if the user deletes all input
> C3 update name prompt

- .changeset/three-news-sip.md
- packages/create-cloudflare/src/frameworks/angular/index.ts
- packages/create-cloudflare/src/frameworks/astro/index.ts
- packages/create-cloudflare/src/frameworks/docusaurus/index.ts
- packages/create-cloudflare/src/frameworks/gatsby/index.ts
- packages/create-cloudflare/src/frameworks/next/index.ts
- packages/create-cloudflare/src/frameworks/nuxt/index.ts
- packages/create-cloudflare/src/frameworks/react/index.ts
- packages/create-cloudflare/src/frameworks/remix/index.ts
- packages/create-cloudflare/src/frameworks/solid/index.ts
- packages/create-cloudflare/src/frameworks/svelte/index.ts
- packages/create-cloudflare/src/frameworks/vue/index.ts
- packages/create-cloudflare/templates/chatgptPlugin/ts/README.md
- packages/create-cloudflare/templates/chatgptPlugin/ts/package.json
- packages/create-cloudflare/templates/common/js/package.json
- packages/create-cloudflare/templates/common/ts/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
- packages/create-cloudflare/templates/queues/js/package.json
- packages/create-cloudflare/templates/queues/ts/package.json
- packages/create-cloudflare/templates/scheduled/js/package.json
- packages/create-cloudflare/templates/scheduled/ts/package.json
This fixes C3 scripts and READMEs to use the wrangler 3 `deploy` command instead of `publish`.
> fix(create-cloudflare): use wrangler deploy instead of wrangler publish

- .changeset/selfish-files-flow.md
- packages/wrangler/src/bundle.ts
- packages/wrangler/templates/checked-fetch.js
Fixes #3478
This PR makes it possible to locally test Workers where the global `fetch` object is proxied with a Javascript Proxy.
While this won't happen often in regular Workers, things like the [Open Telemetry SDK](https://github.com/evanderkoogh/otel-cf-workers) do need that to intercept and instrument outgoing `fetch` calls.
This does not change any externally observable behaviour, so no tests are needed.
> Refactor checkFetch from a separate method to a proxy around fetch

- packages/create-cloudflare/src/cli.ts
Currently the CLI asks, "Where do you want to create your application?"
This changes the language here to "In which directory do you want to create your application?" to reduce ambiguity with smart placement, region hints, and other potential meanings of "where".
Fixes DEVX-731
> Be more specific in create-cloudflare interactive prompt

- .changeset/small-lies-thank.md
- .vscode/settings.json
- packages/create-cloudflare/src/helpers/__tests__/command.test.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/workers.ts
- packages/create-cloudflare/templates/chatgptPlugin/ts/wrangler.toml
- packages/create-cloudflare/templates/common/js/wrangler.toml
- packages/create-cloudflare/templates/common/ts/wrangler.toml
- packages/create-cloudflare/templates/hello-world/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
- packages/create-cloudflare/templates/queues/js/wrangler.toml
- packages/create-cloudflare/templates/queues/ts/wrangler.toml
- packages/create-cloudflare/templates/scheduled/js/wrangler.toml
Fixes https://github.com/cloudflare/workers-sdk/issues/2385
Previously, we changed wrangler.toml to use the current date for the compatibility_date setting in wrangler.toml when generating workers. But this is almost always going to be new recent and results in a warning.
Now we look up the most recent compatibility date via npm on the workerd package and use that instead.
To test, build the create-cloudflare-package and then use it to build a workers project.
Check that the output displays:
```
├ Retrieving current workerd compatibility date 
│ compatibility date 2023-05-18
```
And that the generated wrangler.toml contains this date:
```toml
compatibility_date = "2023-05-18"
```
- N/A
**Author has included the …
> [C3] fix: use a valid compatibility date for worker templates

- .changeset/stale-meals-yawn.md
- packages/create-cloudflare/src/frameworks/angular/templates/tools/bundle.mjs
Angular employs the Zone.js library to patch potentially async operations so that
it can trigger change detection reliably. But in order to do this, it swaps out
the native `Promise` with a `ZoneAwarePromise` class.
The Cloudflare runtime (i.e. workerd) does runtime checks on the value returned
from the `fetch()` handler, expecting it to be a native `Promise` and fails if not.
This fix ensures that the actual object returned from the `fetch()` is actually a
native `Promise`. We don't need to stop Angular using `ZoneAwarePromises` elsewhere.
**Reviewer is to perform the …
> [c3] fix: ensure the Angular fetch handler returns a "real" promise to Cloudflare

- .changeset/nasty-foxes-sparkle.md
- fixtures/pages-ws-app/package.json
- package-lock.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
Bumps miniflare@3.0.2:
- Fixes `--port=0` reloads, ensuring the randomly selected port is re-used, and we don't instead get a _second_ random (different) port.
- https://github.com/cloudflare/miniflare/issues/608
> Bump miniflare@3.0.2

- fixtures/pages-ws-app/package.json
- package-lock.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
This PR bumps and pins `miniflare` to the latest `beta` version. This allows us to get a `wrangler@beta` version with a bunch of `workerd` fixes, including support for older Linux and macOS versions (https://github.com/cloudflare/workers-sdk/issues/3457), and fixing some memory leaks (#2386).
N/A
> chore: bump `miniflare` to `0.20230628.0`

- .changeset/loud-pugs-end.md
- packages/wrangler/src/dev/miniflare.ts
Fixes #3353.
PR adds support for https in local mode for dev. Adds new options to provide custom key and cert for https server.
[Docs issue](https://github.com/cloudflare/cloudflare-docs/issues/9625)
> Add https support in dev local mode

- .github/workflows/e2e.yml
A sneaky trick I saw at https://www.thisdot.co/blog/how-to-retry-failed-steps-in-github-action-workflows/#approach-2-duplicate-steps
> chore: retry the e2e tests once if they fail

- .changeset/slow-beans-wink.md
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/proxy.ts
Fixes #2610
In remote mode, the `onReady` callback was being incorrectly called with the remote host, rather than the local host of the proxy server. It was also only called with the pre port-assignment port, which is sometimes `0`.
- ~[ ] Tests~
> Report correct IP & port in local mode

- .changeset/slow-beans-wink.md
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/proxy.ts
Reverts cloudflare/workers-sdk#3337, since it's breaking e2e tests
> Revert "Report correct IP & port in local mode"

- .changeset/twelve-pumpkins-crash.md
- packages/wrangler/src/__tests__/delete.test.ts
- packages/wrangler/src/delete.ts
Changes the default ?force param to the delete API call to be false.
Also uses the /scripts/{scriptName}/references and /tails/by-consumer/{scriptName} endpoints to determine what resources depend on the current script. We check for other scripts that use this one as outbound worker (for dynamic dispatch), as a tail worker, as a service binding, or use a durable object implemented by this script. If any other resources rely on this worker, we require another step of confirmation, describing the dependencies, and only then do we allow doing a force delete.
for WC-1308
- Checked for …
> WC-1308 Reduce force-deletes unless explicitly confirmed

- .changeset/lucky-months-judge.md
- packages/create-cloudflare/src/common.ts
Fixes #3476.
Tells the user to `cd` into the application they just created before suggesting other commands
> C3: Prompt user to change directory in summary steps

- .changeset/empty-avocados-promise.md
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/templates/middleware/loader-modules.ts
Fixes #2386
Previously, the middleware loader for module workers would register all middleware on each request. These registrations would be in addition to previous requests' registrations, meaning the middleware chain grew linearly with each request. This eventually lead to a stack overflow, as the middleware dispatcher is recursive. It also significantly slowed down requests over time. Editing code and reloading the dev server would reset the middleware chain.
This change ensures middleware is only registered on the first request.
To test this, follow the reproduction instructions here: https://github.com/BillBrower-Shopify/cf-workerd-crash-minimal
With this change stack overflows and slowdowns shouldn't be observed.
**Associated docs …
> fix: register middleware once for module workers

- .changeset/nine-hounds-nail.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev.tsx
Previously, Wrangler would watch the `wrangler.toml` file then immediately clean-up the watcher. The prevented changes in the configuration (e.g. compatibility dates) reloading the server.
This change only cleans-up the watcher if `startDev()` throws, rather than if it returns normally.
To test, run `wrangler dev` on one of the fixtures, edit the `wrangler.toml` and check the dev server reloads with the new configuration.
-  N/A
- Manually pulled down the changes …
> fix: keep configuration watcher alive

- .changeset/smart-bugs-sleep.md
- fixtures/worker-ts/package.json
- fixtures/worker-ts/tsconfig.json
- package-lock.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/templates/middleware/loader-modules.ts
Fixes #3568 
Ensures middleware preserve the email handler on user workers. Also upgrades worker types to a version which includes the email handler type.
- ~[ ] Tests~
> Include email handler in middleware

- .changeset/sour-numbers-sing.md
- packages/create-cloudflare/templates/common/js/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/queues/js/package.json
- packages/create-cloudflare/templates/scheduled/js/package.json
Fixes #3548 
Typescript and workers/types were included in the package.json of js-only template folders. 
> c3: remove ts dependencies from js templates

- packages/create-cloudflare/src/helpers/command.ts
Fixes #3219
Solves a bug where c3 sometimes incorrectly determines that a user is logged into wrangler when they aren't. Root cause is `wrangler whoami` opening a login url when the token is stale. This fixes the issue by only determining the user is logged in if the `wrangler whoami` output contains a positive confirmation.
> C3: Fix bug with detecting wrangler login

- .changeset/nine-apes-fry.md
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/pages.ts
Fixes #3637.
This fixes an issue where pages project will fail to be created properly if the user has a different default branch name configured other than `main`. That's because the production branch is currently hardcoded. This fixes it by detecting the current branch and passing that along to `wrangler pages project create`.
- Checked for creation of …
> C3: Detect production branch when creating pages project

- .github/extract-pr-and-workflow-id.js
- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/write-prerelease-comment.yml
The changes to [.github/workflows/write-prerelease-comment.yml](https://github.com/cloudflare/workers-sdk/pull/3603/files#diff-14f1093401a0e312fb8ada4cb51580148fbed83e0c479a9ec2fffc81e052643f) will only be testable when this PR lands, as those jobs only run on `main`.
> ci: implement PR previews for C3

- .changeset/happy-glasses-live.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Fixes #3286
When running `wrangler init -y ...`, we will now skip the npx (npm create) prompt to install `create-cloudflare` before running it. Since we own the package, I don't see this as a problem.
The -y flag will not be added to any C3 delegation to framework CLIs – this is only when wrangler delegates to C3.
We are not able to guarantee that any framework CLI will have a non-interactive flow.
- Manually pulled down the …
> pass `-y` flag to npx when delegating to C3 if passed to `wrangler init`

- .changeset/honest-ghosts-switch.md
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/src/frameworks/next/index.ts
- packages/create-cloudflare/src/helpers/files.ts
Add the option to add the eslint-plugin-next-on-pages eslint plugin to developers creating a new Next.js app with eslint enabled
> C3: offer eslint-plugin-next-on-pages

- .github/extract-pr-and-workflow-id.js
- .github/workflows/write-prerelease-comment.yml
We were breaking out of the loop too early so only the first artifact was being added to the environment variables.
> ci: fix prerelease comment job to also run when only pages-shared has changed

- .changeset/tasty-beds-look.md
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/sites.ts
Fixes #3385
When a `wrangler deploy` happens, the old assets are immediately deleted, causing users of previously obtained web applications that expect to find specific resources to no longer have access to them, resulting in users seeing 404 errors rather quickly.
Wrangler 1.x attempted to address this by way of https://github.com/cloudflare/wrangler-legacy/pull/2221, which caused the default behavior to be a delaying of the old asset removal, but, the cache could become large with repeated deploys causing expirations being extended repeatedly (well, that was one issue...), so it was reverted.
Even though this delayed expiration of old assets was removed in subsequent Wrangler 1.x builds, we see this as a needed behavior, and stuck with the version …
> [wrangler] Add deploy --old-asset-ttl option

- .changeset/silver-dolphins-guess.md
- packages/wrangler/src/dev/dev.tsx
Fixes #3564
Sometimes the dev registry gets stuck, and Wrangler fails to connect. There may be underlying issues here we should investigate, but in the meantime this limits the error message generated to being logged once per Wrangler process rather than every 300 milliseconds.
> Limit dev registry logs

- .changeset/twenty-snails-sip.md
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.tsx
This PR fixes a TypeScript issue that cropped up while updating the miniflare dependency following https://github.com/cloudflare/miniflare/pull/635 fixing its exported types. This change refines the type from `unknown` to a more accurate `string | Json` type.
N/A
> Refine typedef for `bindings.vars`

- .github/workflows/test-c3.yml
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/scripts/cleanupPagesProject.mjs
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/frameworks/next/index.ts
- packages/create-cloudflare/src/helpers/interactive.ts
- packages/create-cloudflare/vitest-e2e.config.ts
Adds e2e coverage for the deployment bits of c3
- [ x ] Tests
> C3: Add e2e coverage for deployment

- .changeset/curly-wombats-suffer.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
When 'secret:bulk' has an upload request fail it now sends a exit 1 signal that will allow for error handling in other environments.
https://github.com/cloudflare/wrangler-action/pull/112
> secret:bulk exit 1 on failure

- .changeset/breezy-pants-allow.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
Add `--local` and `--persist-to` options to r2 object commands to interact with local persisted storage
- https://github.com/cloudflare/cloudflare-docs/pull/10184
> Add --local to r2 object commands

- packages/create-cloudflare/templates/queues/js/wrangler.toml
- packages/create-cloudflare/templates/queues/ts/wrangler.toml
- Previously, running `npm create cloudflare` and choosing the `queues` option would copy a `wrangler.toml` file with the `[[queues.producers]]` and `[[queues.consumers]]` lines commented out.
- This resulted in an `Can't redefine existing key` error when running `wrangler dev`.
- This PR uncomments the `[[queues.producers]]` and `[[queues.consumers]]` lines in the template.
- N/A
- ~~Checked for inclusion of relevant tests~~
- ~~Checked for inclusion of a relevant changeset~~
- ~~Checked for creation of associated docs updates~~
- ~~Manually pulled down the changes and spot-tested~~
> [C3] Uncomment Queues config lines in Queues C3 templates

- .changeset/warm-students-provide.md
- packages/edge-preview-authenticated-proxy/src/index.ts
Fixes CUSTESC-31513.
This PR removes the `X-CF-Token` and `X-CF-Remote` headers from the proxied request after they've been consumed. The token is included in the `cf-workers-preview-token` header.
We were previously including the token twice, which can be quite large in some cases. This was causing nginx to reject some requests due to `400 Request Header Or Cookie Too Large` errors.
> [quick-edit] Delete X-CF-Token and X-CF-Remote headers from proxied rawhttp requests

- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/index.ts
Fix #3715, Fix #3716
cc @jspspike feel free to close if you want to diy.
> Unify `kv:key list` output in local vs remote case

- .changeset/chilly-files-think.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation.ts
The `DispatchNamespace` was recently added to `workers-types`, but `wrangler types` command would generate `any`.
> Add DispatchNamespace as binding type

- .changeset/lazy-brooms-live.md
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/frameworks/hono/index.ts
- packages/create-cloudflare/src/pages.ts
- packages/create-cloudflare/src/types.ts
Fixes #3477
Currently, in C3, when you choose "Hono" from "Website or web app", it creates the project using the `create-hono` command with the `--template cloudflare-pages` option:
```
npx create-hono@latest my-app --template cloudflare-pages
```
But as I mentioned in #3477, using the template for *Workers* is more appropriate for Hono. In this PR, I've switched to using the `--template cloudflare-workers` option for the `create-hono` command and implemented the following related changes:
* Added an optional `type?` property to `FrameworkConfig`, which can be either `"pages"` or `"workers"`.
* Set the `type` as "`workers`" for Hono.
* If the `type` is set to `workers`, the project isn't created, and a link to …
> [C3] Use workers template for `create-hono`

- packages/wrangler/src/__tests__/d1/convert-timestamp-to-iso.test.ts
Currently tests assume the operating locale is east of the prime meridian.
> Allow tests to pass in western hemisphere

- .changeset/spicy-cars-smell.md
- fixtures/pages-ws-app/package.json
- package-lock.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
bumping the miniflare version to 3.20230814.1
Note: the miniflare version for pages-shared and pages-ws-app wasn't updated last week
> bump miniflare version to v3.20230814.1

- .changeset/dull-pets-search.md
- CODEOWNERS
- packages/wrangler/src/__tests__/pages/project-validate.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/pages/index.ts
- packages/wrangler/src/pages/upload.tsx
- packages/wrangler/src/pages/validate.tsx
For internal use, we want to validate a static asset directory ahead of actually uploading it.
This PR just pulls out the validation logic we were already doing into its own command and then adds some more tests to cover the failure cases of a file size too large and having too many assets.
n/a
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly …
> Add `wrangler pages project validate [directory]` command

- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/index.ts
- packages/wrangler/src/r2/index.ts
Fixes a typo in the following commands:
* `wrangler r2 object {put,get,delete} --help`
* `wrangler kv:key {put,list,get,delete} --help`
* `wrangler kv:bulk {put,delete} --help`
None
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and …
> [wrangler] Fix typo (persistance -> persistence)

- .github/workflows/test-c3.yml
- package-lock.json
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/package.json
- packages/create-cloudflare/scripts/build.ts
- packages/create-cloudflare/scripts/e2eCleanup.ts
- packages/create-cloudflare/src/helpers/command.ts
Re-enables pnpm e2e tests for c3. Previous attempts were stalled by flakiness, and in an effort to expedite a release we deferred enabling pnpm coverage. This fixes an issue with `create-react-app` that was causing an issue pnpm and improves the reliability of cleanup in between test attempts.
- [ x ] Tests …
> C3 - Re-enable pnpm test and cleanup pages projects between retries

- .changeset/hip-rules-cross.md
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/pages/constants.ts
Occasionally, creating a deployment can fail due to internal errors in the POST /deployments API call. Rather than failing the deployment, this will retry first.
Fixes PAGES-2935
The /deployments endpoint occasionally returns a 5XX error, causing a deployment to fail. This will improve reliability of the `wrangler pages publish` command.
- [x ] Tests
- [ x] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
- Manually pulled down the …
> fix: Retry deployment errors in wrangler pages publish

- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/pages/errors.ts
- packages/wrangler/src/pages/upload.tsx
Currently, Pages specific API request error codes are spread all over the codebase, without any uniform mechanism to handle them. This leads to error codes that are unreadable and difficult to keep track of.
This commit introduces a very simple and straightforward mechanism (by means of a top level `enum`) that handles and makes such API error codes easier to reason about.
We want to celebrate and highlight awesome PR review! …
> pages: Add mechanism to handle API error codes

- .changeset/dirty-roses-appear.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
- packages/wrangler/src/__tests__/helpers/msw/index.ts
- packages/wrangler/src/deploy/deploy.ts
Fixes WC-1559.
This PR simply adds a warning when the user tries to deploy and the last deployment was via the API. The warning is similar to the one that appears when the last warning was via the dashboard.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the …
> WC-1559: Add alert when last deployed via API

- .github/extract-runtime-versions.mjs
- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/write-prerelease-comment.yml
- .gitignore
Closes DEVX-880
Hey! 👋 This PR adds some additional information on the resolved `workerd`/`miniflare` to the pre-release comment. This is a sanity check for releases to ensure constraints are pinned, and the minor versions match.
N/A …
> chore: include `workerd`/`miniflare` versions in pre-release comment

- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/pages/upload.tsx
Fixes a number of lint issues that are popping up with annotations on every PR to workers-sdk.
> [wrangler] Fix lint issues

- .changeset/nervous-insects-happen.md
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/helpers/interactive.ts
- packages/create-cloudflare/src/types.ts
- packages/create-cloudflare/turbo.json
Fixes #3793.
Automatically updates to the latest version of c3 when a newer version is available.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please …
> C3: Automatically use the latest version of c3 if not running latest

- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/pages.test.ts
The e2e tests for the various framework all run in parallel today and vitest isn't doing the best job of labelling output from each respective suite. This change prepends the framework to the output lines so it's easier to decipher which output is coming from which test
We want to celebrate and highlight awesome PR review! If you think this PR …
> C3: Improve readability of framework e2e tests

- packages/wrangler/src/pages/upload.tsx
The `/pages/assets/check-missing` API request erorr handler, should check not only for the `ApiErrorCodes.UNAUTHORIZED` error code, but also for whether the JWT is expired, before fetching another JWT token.
This commit adds the missing `isJwtExpired(jwt)` check. …
> pages: Add missing `isJwtExpired` check

- .github/generate-c3-dependabot-pr-changeset.mjs
Currently the C3 dependabot versioning is set to bump a single package per PR, the current implementation generates a changeset for this change containing a table, such would be nice if multiple packages were bumped but currently it is slightly too verbose
This PR updates the script generating the changeset so that to simplify it in case a single package is bumped, while still maintaining the table implementation in case more than one package is (which might useful in the future if/when we implement grouping)
[Result of the change](https://github.com/dario-piotrowicz/dependabot-testing/pull/25/files)
> simplify dependabot C3 single bump changesets

- .github/dependabot.yml
The label name is "c3" and not "C3".
> C3: fix label name in the dependabot.yml config

- package-lock.json
- packages/quick-edit-extension/scripts/bundle.ts
- packages/wrangler-devtools/Makefile
Quick Edit: `esbuild` options were incorrectly changed to match a future version of `esbuild`
DevTools: Should no longer install dependencies in a specific package, rather than relying on the global monorepo install
We want to celebrate and highlight awesome PR review! If you think this PR received a …
> Fix Quick Edit and Devtools builds

- fixtures/node-app-pages/tests/index.test.ts
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-functions-wasm-app/tests/index.test.ts
- fixtures/pages-functions-with-routes-app/tests/index.test.ts
- fixtures/pages-simple-assets/tests/index.test.ts
- fixtures/pages-workerjs-and-functions-app/tests/index.test.ts
- fixtures/pages-workerjs-app/tests/index.test.ts
- fixtures/pages-workerjs-directory/tests/index.test.ts
- fixtures/pages-workerjs-wasm-app/tests/index.test.ts
- fixtures/pages-workerjs-with-routes-app/tests/index.test.ts
- fixtures/remix-pages-app/tests/index.test.ts
- fixtures/shared/src/run-wrangler-long-lived.ts
- fixtures/worker-app/tests/index.test.ts
Hey! 👋 This PR was part of debugging steps for #3799. We're not merging that PR, but these changes should still help to improve overall reliability and debugability of fixture tests. 🙂 
- Only call `stop()` when `beforeAll()` hooks succeed
- Call `stop()`s in `finally`-blocks to ensure cleanup
- Add timeout to `runLongLivedWrangler()` and log `stdout`/`stderr`
N/A
We want to celebrate and …
> fix: improve fixture test reliability/debugability

- .github/workflows/test-c3.yml
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/frameworkToTest.ts
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/turbo.json
I did test the workflow logic to make sure it gets the correct bumped framework (see [this](https://github.com/dario-piotrowicz/dependabot-testing/actions/runs/5969953686/job/16196728060#step:2:5))
I also did test the e2es with the env variable set locally (`export FRAMEWORK_CLI_TO_TEST=nuxi`):
But I couldn't test how the two work as expected together, hopefully this should all work fine, but I guess we can't be 100% sure until we merge and try it out 😬
> run only a single framework on dependabot PRs

- .changeset/unlucky-apes-film.md
- packages/eslint-config-worker/index.js
This PR changes the `import/order` and `unused-imports/no-unused-vars` eslint rules to raise errors. Currently these rules only raise warnings, which has led to noisy output in PRs since it allows problems to be merged in without being dealt with, potentially confusing future developers as to whether they caused these issues with their own changes. Given we feel these things are important enough to warn about, it's probably worth making the developer address the issue or explicitly ignore it in cases where it's appropriate.
- Checked for creation of …
> Update eslint-config to raise errors instead of warnings

- .github/generate-c3-dependabot-pr-changeset.mjs
The C3 changesets generated on dependabot PRs don't pass our prettier checks ([example](https://github.com/cloudflare/workers-sdk/actions/runs/6005067919/job/16287005472#step:9:388))
this PR is fixing that
(sorry my bad for not having checked this in the first place 🙇 )
> Dependabot prittier fix

- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
This is a straightforward refactoring that removes unused code.
> refactor: remove unused firstPartyWorkerDevFacade property

- CODEOWNERS
This PR adjusts this repo's CODEOWNERS to mark some shared directories as explicitly unowned.
The @cloudflare/wrangler team is the default owner of every file and currently the repo settings require a codeowner approval on any changes to owned files. Other teams are listed as code owners of their respective parts of the codebase. These other teams working in this repo would often get blocked waiting for @cloudflare/wrangler approval when they would make changes to shared top-level directories (e.g. adding a changeset file) as part of their feature work.
To work around that, we added these other teams as owners to these shared directories. While this allowed these teams to move quickly without waiting for outside approval, this caused another problem. Now all teams were being tagged as …
> Mark shared directories as unowned in CODEOWNERS

- .changeset/smooth-lemons-clean.md
- .github/extract-runtime-versions.mjs
- fixtures/pages-ws-app/package.json
- package-lock.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
- packages/wrangler/src/r2/index.ts
Hey! 👋 This PR bumps `miniflare` to [`3.20230904.0`](https://github.com/cloudflare/miniflare/releases/tag/v3.20230904.0). Whilst this won't cause major user facing changes on its own, it's a pre-requisite for #3726 and #3774.
N/A …
> chore: bump `miniflare` to `3.20230904.0`

- .changeset/wild-rockets-bake.md
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/inspect.ts
This PR adds support for breakpoint debugging to local mode. Breakpoints can be set using Wrangler's built-in DevTools, and WebStorm's `Attach to Node.js/Chrome` configurations. VSCode's `attach` configurations connect to `workerd`, but can't find source maps. From reading [VSCode docs](https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_source-map-discovery),  it looks like VSCode ignores `//# sourceMappingURL` comments, and instead looks for source maps itself on disk? I may be misunderstanding this though.
None yet, will definitely want some 👍 
- …
> feat: support breakpoint debugging in local mode

- .changeset/bright-badgers-sit.md
- packages/wrangler/src/dev.tsx
#2462 For R2, I couldn't find a GitHub issue for KV.
Tests still don't run for me locally, so there will probably be a couple rounds of workflow fails -> test fixes.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it …
> Don't throw for missing preview ids in local dev mode

- .changeset/stupid-islands-relax.md
- packages/wrangler/src/user/user.ts
> Ignore cached account id when `CLOUDFLARE_ACCOUNT_ID` is specified

- .changeset/modern-needles-develop.md
- packages/create-cloudflare/src/frameworks/svelte/index.ts
remove NODE_VERSION env variable from sveltekit template - this variable is unused and only creates confusion.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can …
> fix: remove unused env variable from sveltekit template

- .changeset/lazy-beers-return.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
Fixes # R2-1740
This PR adds two things:
1) Allow wrangler r2 commands to specify the jurisdiction where the bucket resides
2) Allow publishing a worker with a binding to an R2 bucket in a jurisdiction
None
- [y] Tests
- [y] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))
We want to celebrate and highlight awesome PR review! …
> [wrangler] R2 jurisdictions support

- .npmrc
- packages/create-cloudflare/.npmrc
- packages/wrangler/.npmrc
This PR attempts to fix pnpm publishing, following up from the first attempt in https://github.com/cloudflare/workers-sdk/pull/3943.
`changesets/action` creates a `.npmrc` file at the root with the auth token pulled from an `$NPM_TOKEN` environment variable. However, if there's already a `.npmrc` at the root it skips this step. We introduced a new `.npmrc` file at the root in https://github.com/cloudflare/workers-sdk/pull/3899/files#diff-e813096d69c49812e40e00be9ac8fa14d77f0ec1f97ab4c45cb096b3bedd35de so our publish job no longer had the proper auth token.
I also suspect the `.npmrc` files within the `wrangler` and `create-cloudflare` workspaces weren't actually being used during publish. Note that the workflow runner environment doesn't have an …
> Add auth token to root .npmrc

- .github/workflows/release.yml
- .npmrc
This PR follows https://github.com/cloudflare/workers-sdk/pull/3945. The change in that PR ended up breaking a bunch of our prerelease workflows that were expecting the `.npmrc` auth token to get populated by `$NPM_PUBLISH_TOKEN`.
We previously were using `NPM_TOKEN` in our `changeset publish` step because that's the name of the env var used in the `.npmrc` file that `changeset/action` [produced for us](https://github.com/changesets/action#with-publishing:~:text=By%20default%20the%20GitHub%20Action%20creates%20a%20.npmrc%20file%20with%20the%20following%20content%3A). Now that we're using our own `.npmrc` file instead of the one it generates for us, we're free to name it whatever. Our prerelease workflows already expect `NPM_PUBLISH_TOKEN`, as well as …
> rename `NPM_TOKEN` to `NPM_PUBLISH_TOKEN`

- .github/workflows/quick-edit.yml
Yarn [throws errors](https://github.com/cloudflare/workers-sdk/actions/runs/6178131477/job/16770757056#step:8:8) if it finds an .npmrc file with a var substitution for an env var that doesn't exist. Now that we have a root-level .npmrc, we need to provide a dummy env var value to prevent this.
Follows https://github.com/cloudflare/workers-sdk/pull/3945 and https://github.com/cloudflare/workers-sdk/pull/3946
> Add dummy NPM_PUBLISH_TOKEN to pacify yarn

- packages/workers-playground/src/QuickEditor/DevtoolsIframe.tsx
- packages/workers-playground/src/QuickEditor/PreviewTab/useRefreshableIframe.tsx
- packages/workers-playground/src/QuickEditor/SplitPane.tsx
- packages/workers-playground/src/QuickEditor/VSCodeEditor.tsx
When dragging around the split pane view, we previously applied `pointer-events: none` to the _parents_ of rendered iframes (because iframes capture the pointer events and cause odd dragging behaviour). However, it turns out this doesn't capture all cases, and so this PR ensure that `pointer-events: none` is always applied to the actual iframes themselves.
- Manually pulled …
> Ensure `pointer-events: none` is applied to iframes

- packages/workers-playground/src/QuickEditor/PreviewTab/PreviewTab.tsx
- packages/workers-playground/src/QuickEditor/PreviewTab/useRefreshableIframe.tsx
- packages/workers-playground/src/QuickEditor/VSCodeEditor.tsx
Fixes DEVX-911
* Use a softer grey as the VSCode loading background
* Show a loading spinner until the preview pane has loaded once
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration and learn …
> Improve loading in Playground

- .changeset/gentle-chefs-smoke.md
- packages/wrangler/src/deployment-bundle/bundle-reporter.ts
Most bundlers, and other tooling that give you size outputs will colorize their the text to indicate if the value is within certain ranges.
Fixes #1312
> Colorize Deployed Bundle Size

- .github/workflows/release.yml
See https://github.com/changesets/action/issues/187
We use Changesets to manage releases in this repo. It creates a PR, which when merged will kick off an NPM release. Unfortunately, when changesets pushed to that PR, checks weren't triggered (since changesets is a bot user). This change makes changesets use a PAT for the repo.
We want to celebrate …
> Use PAT for changesets

- .changeset/shiny-rats-hide.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
Fixes #3732 
Depends on https://github.com/cloudflare/miniflare/pull/650 being merged and released
https://github.com/cloudflare/cloudflare-docs/pull/10320
> Default local dev server to `*`

- .changeset/brave-stingrays-shout.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/init.ts
- packages/wrangler/src/secret/index.ts
Added binding for the AI project.
> wrangler: Add AI binding

- .changeset/pretty-avocados-worry.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
When Secrets are uploaded if there is no Worker in place already it will fail, this allows for the same draft worker logic to retry adding the secrets
Fixes # https://github.com/cloudflare/wrangler-action/issues/162
> Draft Worker for Bulk Secrets

- .changeset/eleven-monkeys-tan.md
- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/__tests__/vectorize/vectorize.upsert.test.ts
- packages/wrangler/src/vectorize/client.ts
- packages/wrangler/src/vectorize/create.tsx
- packages/wrangler/src/vectorize/index.ts
- packages/wrangler/src/vectorize/insert.ts
Extends the Vectorize wrangler support work to allow uploading vectors from a file source.
Comments on the original PR here: https://github.com/cloudflare/workers-sdk/pull/4029
We want to improve the Vector Store onboarding for our customers by allowing them an easy way to source vectors. This vector files may be quite big (100s of MB - GB). This supports a streaming approach to reading and loading these files in an efficient manner.
> Support uploading batches of ndjson vectors from a source file

- packages/workers-playground/src/QuickEditor/PreviewTab/useRefreshableIframe.tsx
- Chrome uses a dark-mode page for non-html content by default, which was showing as white-on-white
> [playground] Fix dark mode in Chrome

- packages/workers-playground/src/QuickEditor/TopBar.tsx
This PR fixes a few things with the Workers Playground top-level toolbar:
- The Deploy button is now disabled when the hash fragment isn't present. (Fixes DEVX-968)
- Editing the worker name now properly updates the state stored in query params. Previously the query param value was lagging behind until another edit interaction was initiated.
- The Copy Link confirmation text no longer causes layout shift.
- Clean up of some unused code.
> [workers-playground] TopBar fixes

- packages/wrangler/src/vectorize/insert.ts
Current the Vectorize API can only accept batches of 1000 vectors at a time.
> Lower Vectorize default batch size

- .changeset/tricky-poems-type.md
- packages/wrangler/src/pages/dev.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/4008, https://github.com/cloudflare/workers-sdk/issues/4017, https://github.com/remix-run/remix/issues/7510
#3951 introduced [a change](https://github.com/cloudflare/workers-sdk/pull/3951/files#diff-f64ec8fc0f101cfe619c859a32a565dbedacc3b95f1e3a1483cb832710dbbfb2R766-R772) that closed the bootstrapper's IPC channel when Wrangler exited. Whenever `wrangler (pages) dev` reloads, an event is sent on this channel to indicate the dev server is ready. Unfortunately, `wrangler pages dev`'s handler didn't wait for the dev session to exit before resolving its returned promise, meaning the channel was closed as soon as the dev server was ready, not when Wrangler exited. This meant that ready events sent …
> [wrangler] fix: allow `wrangler pages dev` sessions to be reloaded

- .changeset/tiny-shrimps-train.md
- packages/create-cloudflare/templates/scheduled/js/wrangler.toml
#3913 
Create a Scheduled Worker via C3, selecting NO to TypeScript. The `main` entry in `wrangler.toml` should be `index.js`, and the project should be able to be deployed.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please …
> [c3] fix c3 js scheduled template to have correct main file reference.

- .changeset/seven-zebras-cross.md
- packages/create-cloudflare/templates/chatgptPlugin/ts/package.json
- packages/create-cloudflare/templates/common/js/package.json
- packages/create-cloudflare/templates/common/ts/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
- packages/create-cloudflare/templates/openapi/ts/package.json
- packages/create-cloudflare/templates/queues/js/package.json
- packages/create-cloudflare/templates/queues/ts/package.json
- packages/create-cloudflare/templates/scheduled/js/package.json
- packages/create-cloudflare/templates/scheduled/ts/package.json
Fixes #3669 .
All Workers templates created via C3 should support `npm run dev` as an alias for `wrangler dev` to match comments in `index` files.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take …
> C3: update templates to have `dev` command as index comments imply

- .changeset/yellow-rules-lay.md
- .github/actions/install-dependencies/action.yml
- .github/workflows/test-c3.yml
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/package.json
- packages/create-cloudflare/src/frameworks/astro/index.ts
- packages/create-cloudflare/src/frameworks/nuxt/index.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/helpers/packages.ts
Fixes #3941.
Adds support for bun along with e2e coverage.
- [ x ] Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight …
> C3: Add bun support

- .changeset/twenty-deers-crash.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/zones.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/zones.ts
Fixes #3635
During local development, the host of `request.url` is inferred from the `routes` in the config.
Previously, route patterns like "*/some/path/name" would infer the host as "some". We now handle this case and determine we cannot infer a host from such patterns.
I have also added tests which enumerate examples of url patterns and the expected host to be inferred.
We want to celebrate and highlight awesome PR review! …
> fix getHostFromUrl to not infer pathnames from the pattern as the host

- packages/wrangler/src/inspect.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/1811
Prevent log duplication when worker is reloaded in remote mode
> Clear worker logs on WebSocket connection

- .changeset/curvy-onions-breathe.md
- packages/wrangler/src/api/dev.ts
Fixes #3526
We now pass down `options.local` into the `StartDevOptions` whereas it was being ignored before
> respect options.local in unstable_dev

- .changeset/orange-berries-relax.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/index.ts
Fixes #1197.
After the API returns an authentication error, log the token info returned by `whoami()`, to help the user diagnose the issue.
- ~[ ] Tests~
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take …
> Log token info after authentication errors

- .changeset/curvy-dryers-bake.md
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/pages/utils.ts
On macOS, `os.tmpdir()` returns a symlink. This causes `esbuild` to generate invalid source maps, as the number of `../` in relative paths changes depending on whether you evaluate symlinks. We previously fixed a similar issues for the middleware loader (https://github.com/cloudflare/workers-sdk/pull/2249/files#diff-17e01c57aa611bb9e0b392a15fd63b5d18602e3a6c9a97c4a34e891bbfdcb7f3R496-R498), and regular `wrangler dev`
(https://github.com/cloudflare/workers-sdk/pull/3951/commits/be30ee4388d8dbf86c96aa6e43ed97e6f289bb8c). Unfortunately, we didn't fix it for `wrangler pages dev`.
To test, run `npm run dev` in `fixtures/pages-functions-app`, wait for the dev server to start, press <kbd>d</kbd>, and check the file paths in the sources panel are correct. …
> [wrangler] fix(pages): use `realpath`ed tmp dirs to generate valid source maps

- .changeset/khaki-experts-reflect.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/helpers/cli.ts
Fixes #3931.
Defaults the C3 project type to `webFramework`. The previous default was the hello-world worker that appeared second in the list, leading to a somewhat awkward user interaction. …
> C3: Defaulting project type to webFramework

- .changeset/eighty-plums-ring.md
- packages/create-cloudflare/src/workers.ts
Fixes #3979.
Fixes an issue in the "Hello World" worker creation workflow where the user is prompted for typescript twice:
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly …
> C3: Fixing double prompt for ts during hello world worker creation

- .changeset/empty-sloths-complain.md
- packages/create-cloudflare/package.json
- packages/create-cloudflare/src/helpers/interactive.ts
- pnpm-lock.yaml
Fixes #3835.
This solves an issue where exiting c3 early via ctrl+c causes the terminal cursor to become hidden.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber …
> C3: Fix disappearing cursor after early exit

- .changeset/smart-hats-hug.md
- fixtures/pages-ws-app/package.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
Hey! 👋 This PR bumps `miniflare` to [`3.20231002.0`](https://github.com/cloudflare/miniflare/releases/tag/v3.20231002.0). 
N/A
> [wrangler] chore: bump `miniflare` to `3.20231002.0`

- packages/create-cloudflare/src/helpers/shell-quote.ts
- packages/wrangler/src/utils/shell-quote.ts
On Windows, paths contain `\` characters as delimiters. Our command parser was interpreting these as backslash escape characters. This is essentially a double encoding bug.
This fixes the issue on Windows by replacing the backslash characters with a double-backslash which will be interpreted as an escaped backslash (i.e. a single backslash).
The double and quadruple backslashes in the `cmd.replace(...)` call are a double-encoding of themselves but I'm sure everyone reviewing this is aware. …
> fix usage of shell-quote.parse on windows

- .changeset/eleven-berries-itch.md
- fixtures/pages-ws-app/package.json
- packages/pages-shared/package.json
- packages/wrangler/package.json
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
- packages/wrangler/src/deployment-bundle/source-url.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/remote.tsx
- pnpm-lock.yaml
Hey! 👋 This PR bumps `miniflare` to [`3.20231002.1`](https://github.com/cloudflare/miniflare/releases/tag/v3.20231002.1). It also fixes source maps/breakpoint debugging when using `find_additional_modules`. See the commit descriptions for more details.
N/A
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it …
> [wrangler] chore: bump `miniflare` to `3.20231002.1` and fix `find_additional_modules` source maps

- fixtures/additional-modules/test/index.test.ts
Use `MF-Disable-Pretty-Error` instead of `MF-Original-URL` for disabling the pretty-error page in the `additional-modules` fixture test. This was changed in cloudflare/miniflare#689.
N/A
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take …
> fix: use correct header for disabling pretty-error page in tests

- packages/workers-playground/src/QuickEditor/QuickEditor.tsx
- packages/workers-playground/src/QuickEditor/TopBar.tsx
- packages/workers-playground/src/QuickEditor/useDraftWorker.ts
Fixes DEVX-969
Uses in-memory state for the deploy button hash
> [playground] Use in-memory state

- .changeset/serious-beans-hug.md
- packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/createTail.ts
- packages/wrangler/src/tail/printing.ts
When tailing a tail worker, messages previously had a null event property. Following https://github.com/cloudflare/workerd/pull/1248, these events have a valid event, specifying which scripts produced events that caused your tail worker to run.
As part of rolling this out, we're filtering out tail events in the internal tail infrastructure, so we control when these new messages are forward to tail sessions, and can merge this freely.
One idiosyncracy to note, however, is that tail workers always report an "OK" status, even if they run out of memory or throw. That is being tracked and worked on separately.
- Checked for inclusion of a …
> Support TailEvent messages in Tail sessions

- .changeset/dull-pans-happen.md
- packages/wrangler/src/pages/upload.tsx
For projects which are slow to upload - either because of client bandwidth or large numbers of files and sizes - It's possible for the JWT to expire multiple times. Since our network request concurrency is set to 3, it's possible that each time the JWT expires we get 3 failed attempts. This can quickly exhaust our upload attempt count (5) and cause the entire process to bail.
This change makes it such that jwt refreshes do not count as a failed upload attempt.
> fix: Pages direct upload failing with expired JWT error

- .changeset/warm-queens-taste.md
- packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/createTail.ts
- packages/wrangler/src/tail/printing.ts
Queue events have an "event" section containing two fields -- "queue" and "batchSize", which contain the queue name and number of messages in the batch. Queue events can be distinguished from other events by the presence of the "queue" field, so that's what I do here.
I've followed the example of RequestEvent more closely than either ScheduledEvent or AlarmEvent here, but am happy to change up the format if there's a reason to do so.
@OilyLime @jbw1991
> Support Queue events in tail

- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/src/frameworks/docusaurus/index.ts
- packages/create-cloudflare/src/helpers/packages.ts
Some frameworks are lacking support with current package managers (namely Gatsby with bun), so to avoid quarantining a framework this change allows us to skip certain package managers on a per-framework basis.
Branched off of https://github.com/cloudflare/workers-sdk/pull/4096 which contains a heavy refactor of c3 e2e tests.
- [ x ] Tests
We want to …
> C3: Allow skipping specific pms in e2e on a per-framework basis

- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
Adds another field to printed output for internal first-party workers.
> wrangler: add mutable id to first_party_worker logs

- .changeset/green-days-bow.md
- packages/create-cloudflare/src/__tests__/common.test.ts
- packages/create-cloudflare/src/common.ts
Fixes #3683.
Skips the prompt offering git to c3 users if they haven't yet configured `user.name` and `user.email`. 
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber …
> C3: Don't offer git if username and email unconfigured

- .changeset/itchy-experts-sniff.md
- packages/wrangler/src/deployment-bundle/apply-middleware.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
Fixes #3575
Fail early with a helpful error message when a configured middleware doesn't support your Worker's script format (i.e. D1 and multiworker only support the modules format).
> Bail early on middleware format mismatch

- .changeset/yellow-cycles-fix.md
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/workers.ts
Fixes #3865.
In an [earlier PR](https://github.com/cloudflare/workers-sdk/pull/3803), we changes c3 so that it would automatically update to the latest minor version of the package when available. Unfortunately, this behavior was accidentally reverted shortly afterwards due to a merge conflict.
This PR turns auto-updates back on and fixes an issue with this functionality when used in conjunction with `wrangler init`. 
- Checked for inclusion …
> C3: Turn auto-update back on

- .changeset/purple-eels-own.md
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/src/__tests__/common.test.ts
- packages/create-cloudflare/src/common.ts
Fixes #3222
This change ensures that project names are also valid pages project names to prevent crashes during the deploy step. 
- [ x ] Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a …
> C3: Validate project name

- .changeset/purple-penguins-tie.md
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/src/frameworks/angular/index.ts
Fixes #4023
This PR adds e2e coverage for angular. 
It also replaces the `predeploy` and `prestart` scripts in angular's package.json scripts as [pnpm doesn't support](https://pnpm.io/cli/run#differences-with-npm-run) `pre` and `post` scripts out of the box. 
This branch is based off of [this PR](https://github.com/cloudflare/workers-sdk/pull/4096) which refactors c3 e2e.
- [ x ] Tests
- Checked for …
> C3: Add angular e2e coverage

- .changeset/tall-dodos-join.md
- packages/wrangler/src/dev/dev.tsx
Support is already in progress (see https://github.com/cloudflare/workerd/pull/1266) and should be coming in the next few weeks, but we've already had at least one user get very confused by this and cause us to spend time on debugging before realizing the problem was that they were talking about problems in wrangler dev rather than at the edge. This is an easy way to attempt to mitigate that for now.
Fixes #4133
> Warn that Hyperdrive bindings do not yet work in local dev

- CODEOWNERS
This PR removes the wrangler team as CODEOWNERS of c3. 
> C3: Remove wrangler team from C3 CODEOWNERS

- .changeset/plenty-colts-breathe.md
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/src/__tests__/common.test.ts
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/helpers/args.ts
In a [previous PR ](https://github.com/cloudflare/workers-sdk/pull/4128) we made project validation a little more strict so that it conforms to the pages project API. However, this could mean that users with existing workers scripts won't be able to retain a name they used previously. This PR relaxes the validation for that one particular use case.
I also found an issue with `processArgument` where we weren't actually crashing on invalid arguments passed via the command line.
- Checked for inclusion of a relevant …
> C3: Relax validation for existing scripts

- .github/workflows/c3-e2e-dependabot.yml
throwing inside the `actions/github-script@v6` script causes the workflow to fail, I've tested it [here](https://github.com/dario-piotrowicz/dependabot-testing/commit/5f8aeaa4afd1c484b73ceb83639e166d67f13878) with this [result](https://github.com/dario-piotrowicz/dependabot-testing/actions/runs/6481838120/job/17600146758?pr=75#step:4:17)
if preferred instead of throwing in the script I can leave the script as is and add a new steps that does the check and fails the workflow more explicitly, something like:
```yml
- name: Check FrameworkCli
if: ${{ steps.detect.outputs.result == '' }}
run: |
echo "Error: Framework Cli not detected"
exit 1
```
I don't have a strong preference so please let me know if you have and I can just quickly update this PR 🙂
> C3: fail e2e dependabot PRs if no framework Cli is detected

- packages/create-cloudflare/e2e-tests/pages.test.ts
Attempts to remove remix from the e2e quarantine by increasing the timeout. Remix seems to eventually succeed but takes a little longer than the other frameworks.
- [ x ] Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so …
> C3: Remove remix from quarantine

- .github/actions/run-c3-e2e/action.yml
- packages/create-cloudflare/.gitignore
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/scripts/common.ts
- packages/create-cloudflare/scripts/e2eCleanup.ts
- packages/create-cloudflare/src/frameworks/angular/index.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/helpers/interactive.ts
This is a long overdue rework of how we handle logging in c3 e2e tests.
The current e2e logging situation is extremely annoying. The test runner pipes output directly to stdout with minimal filtering, and since the output contains interactive cli commands it's usually cluttered with various animations and terminal escape codes. To make matters worse, tests are run in parallel and output to the same stdout, which means that the output of multiple frameworks are interleaved with one another, making almost impossible to discern where the output of the problematic test begins and ends.
This PR changes things by:
- Formatting the output in a simpler way for non-interactive terminals (which happens to be useful outside of testing as well)
- Giving each …
> C3: E2E logging refactor

- fixtures/service-bindings-app/tests/index.test.ts
- packages/wrangler/e2e/dev.test.ts
Make the `service-bindings-app` fixture more resilient by using `unstable_dev`, and add `e2e` tests for service bindings
> Use `unstable_dev` and add e2e tests for service bindings

- .changeset/witty-trainers-battle.md
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/pages.ts
When trying to create a new pages project with C3 that is reusing the same name as an already existing project (for the same account) we retry the project creation multiple times, these add an exit condition to out retry logic so that we don't retry multiple times in such cases.
> C3: don't retry the project creation multiple times when it fails because the project's name is already used

- packages/create-cloudflare/src/common.ts
Addressing [this comment](https://github.com/cloudflare/workers-sdk/pull/4216#discussion_r1364534984)
Follow up to #4216 
A changeset is not needed since the changes made in #4216 haven't yet been released
____
Result:
> use shellquote to make sure the c3 cd summary suggestion is valid for paths with spaces

- .changeset/pink-jokes-double.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/standard-pricing.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/secret/index.ts
User limits provided via script metadata on upload
Example configuration:
```
[limits]
cpu_ms = 20000
```
> Support user CPU time limit

- packages/create-cloudflare/e2e-tests/pages.test.ts
Nuxt e2e runs started failing today and the same error is reproducible with the latest deployed version of c3. We need to look into what upstream change caused this, but in the mean time this PR quarantines nuxt.
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the …
> C3: Quarantine nuxt

- .changeset/cold-parrots-deliver.md
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/helpers/shell-quote.ts
- packages/create-cloudflare/src/pages.ts
- packages/wrangler/src/__tests__/generate.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/utils/shell-quote.ts
Follow-up to #4080, prompted by https://github.com/cloudflare/workers-sdk/pull/4211#issuecomment-1768101260
In my previous PR introducing `shell-quote`, I searched for instances of `split(" ")` and changed them to `shellquote.parse(cmd)`
In this PR, I searched for instances of `join(" ")` and changed them to `shellquote.quote(args) `
We want to celebrate and highlight awesome PR review! If you think this PR received a …
> use `shell-quote.quote(args)` instead of `args.join(" ")`

- .changeset/tasty-teachers-lick.md
- packages/create-cloudflare/src/frameworks/next/index.ts
> fix the generation of invalid/incorrect scripts for Next.js applications

- .changeset/bright-boxes-admire.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/bundle-reporter.ts
Fixes #3269
Suggest using the `--minify` option if the users bundle size is too large
> Callout `--minify` when script size is too large

- packages/wrangler/bin/wrangler.js
In #3951, we added a [`finally` block](https://github.com/cloudflare/workers-sdk/blob/b5e62b931ad6671e4dce9444a279bb3ec8f63991/packages/wrangler/src/index.ts#L796-L802) to ensure that the wrangler CLI child process disconnects from the IPC channel connecting it to the parent process. Since the parent process forwards any messages it receives on the child IPC channel up to any higher-level IPC channel, we should follow suit and also disconnect any higher-level IPC channel as well.
Refs CUSTESC-34125
> Disconnect parent process IPC channel when child process disconnects

- .changeset/three-doors-tickle.md
- packages/cli/index.ts
Warning, Info and Success statuses were printed with a red background.
> CLI: Change the status colors to their appropiate backgrounds

- packages/create-cloudflare/src/frameworks/next/index.ts
fixing the incorrect bun `pages:deploy` script that we generate for Next
(introduced in #4200)
How it is:
How it should be:
> fix Next.js bun pages:deploy script

- .changeset/rich-schools-fry.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/zones.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/zones.ts
Fixes #3662
use `zone_name` to determine a zone when the pattern is a custom hostname
In Cloudflare for SaaS, custom hostnames of third party domain owners can be used in Cloudflare.
Workers are allowed to intercept these requests based on the routes configuration.
Before this change, the same logic used by `wrangler dev` was used in `wrangler deploy`, which caused wrangler to fail with:
✘ [ERROR] Could not find zone for [partner-saas-domain.com]
Example of routes definition that wouldn't work before this PR:
```toml
routes = [
{ pattern = "buy.partner-saas-domain.com/*", zone_name = "mydomain.com" }
]
```
- Checked for inclusion of …
> Use `zone_name` for deployment of custom hostnames

- .changeset/tiny-icons-breathe.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
Fixes #1313
Log the size of additional modules uploaded as part of your worker
> Log size of additional modules

- .changeset/three-carpets-smile.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
Revert "Prevents uploads with both cron triggers and smart placement enabled (#3390)"
This reverts commit b5b46b4a52a309d0b15d1424e35eaae2877c5cb9.
Fixes [WP-591](https://jira.cfdata.org/browse/WP-591).
Lifts a temporary restriction that was put in place because of a bug with smart placement that made it incompatible with cron triggers. That bug has been fixed and users are now free to use smart placement and cron triggers together.
- N/A
- Manually pulled down the …
> [wrangler] Allows uploads with both cron triggers and smart placement enabled

- .changeset/swift-files-care.md
- packages/wrangler/package.json
- packages/wrangler/src/index.ts
- packages/wrangler/src/tail/createTail.ts
- pnpm-lock.yaml
Not sure if there's a better way to go about this without adding a dependency
> Fix proxy not working with wrangler tail

- packages/create-cloudflare/e2e-tests/pages.test.ts
Not ideal but the Cloudflare Astro adapter is currently broken when used with npm.
We're looking into fixing this upstream, in the meantime I am disabling the astro npm e2e test so that we can at least keep using the e2e CI checks in the meantime.
> C3: Disable astro e2e for npm

- packages/create-cloudflare/e2e-tests/pages.test.ts
This reverts commit 47b0b0ef24d128aaf3287298a5cd48fae43e3ce5.
Reverting the commit as the Astro Cloudflare adapter has been fixed
> Revert "C3: Temporarily disable astro npm e2e test (#4290)"

- .changeset/gentle-news-laugh.md
- packages/create-cloudflare/src/__tests__/common.test.ts
- packages/create-cloudflare/src/common.ts
Fixes #4212.
This relaxes the existing directory check to allow files such as `.git`, `.hg`, and `.DS_Store` that are created by IDEs, the OS, or are benign config files. These don't conflict with c3 and the existing check impedes the workflow of users who create folders via their IDE.
- Manually pulled …
> C3: Relax empty directory check

- .changeset/funny-rice-prove.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
Firing PUTs to the secret api in parallel has never been a great solution - each request independently needs to lock the script, so running in parallel is at best just as bad as running serially.
Luckily, we have the script settings PATCH api now, which can update the settings for a script (including secret bindings) at once, which means we don't need any parallelization. However this api doesn't work with a partial list of bindings, so we have to fetch the current bindings and merge in with the new secrets before PATCHing. We can however just omit the value of the binding (i.e. only provide the name and type) which instructs the config service to inherit the existing value, which simplifies this as well. Note that we don't use the bindings in your current wrangler.toml, as you could be …
> Simplify secret:bulk api via script settings

- fixtures/external-service-bindings-app/tests/index.test.ts
This makes the `external-service-bindings-app` fixture work locally. It wasn't working because the Pages dev server doesn't appear to listen on ipv6 by default.
- Tests
> Make external-service-bindings-app work locally

- .changeset/thin-pears-repeat.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/deployment-bundle/worker.ts
Fixes CUSTESC-32212.
We have recently added additional functionality to Tail Workers to allow scripts within a dispatch namespace to be used. This adds support for that optional field to wrangler configuration. 
See the [tail consumers section of the Workers script upload docs](
https://developers.cloudflare.com/api/operations/worker-script-upload-worker-module?schema_url=https%3A%2F%2Fraw.githubusercontent.com%2Fcloudflare%2Fapi-schemas%2Fmain%2Fopenapi.yaml#Responses)
- Checked for creation of associated docs …
> feat(workers): allow namespaced scripts to be used as Worker tail consumers

- .changeset/hot-kiwis-raise.md
- .changeset/olive-queens-retire.md
- packages/create-cloudflare/README.md
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/types.ts
Blocked by https://github.com/cloudflare/cloudflare-docs/pull/11394
___
Fixes #4183
> improve C3 help message

- packages/miniflare/test/plugins/do/index.spec.ts
I've seen this test time out a couple of times in CI. Increasing the timeout to hopefully prevent this happening again. Note, this shouldn't make the tests run any slower, it just means if they do, they won't fail. 👍 
- Tests
> [miniflare] Bump Miniflare Durable Object eviction test timeout

- .changeset/rude-chicken-raise.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/proxy/client.ts
- packages/miniflare/src/workers/shared/sync.ts
- packages/miniflare/test/shared/sync.spec.ts
Previously, Miniflare's `Mutex` implementation would report itself as drained if there were no waiters, regardless of the locked state. This bug meant that if you called but didn't `await` `Miniflare#setOptions()`, future calls to `Miniflare#dispatchFetch()` (or any other asynchronous `Miniflare` method) wouldn't wait for the options update to apply and the runtime to restart before sending requests. This change ensures we wait until the mutex is unlocked before reporting it as drained.
- Tests
We want to celebrate and highlight awesome PR review! If you …
> [miniflare] fix: ensure `Mutex` doesn't report itself as drained if locked

- .changeset/cold-bugs-kick.md
- packages/pages-shared/asset-server/handler.ts
Fixes #2779.
Using regex for filename to check whether it is a directory or not is broken, and current regex logic `/\/.+\.[a-z0-9]+$/i.test(path)` causes troubles for dir filenames like:
- /0.0.1 (#2779)
- /binutils-gdb.git (https://github.com/vercel/next.js/issues/56090)
By removing the extension check, workers could always check whether `${pathname}/index.html` exists.
- N/A
We want to …
> [pages-shared] Remove extension name check when generating response

- .changeset/rotten-keys-occur.md
- packages/wrangler/src/tail/index.ts
This PR adds a `--yes` flag to `wrangler tail` to bypass the confirmation prompt for WebSocket/DO.
* It will still print the warning text
* Includes an alias for `-y`
* Adds a changeset
> tail: add a --yes flag to bypass the DO prompt

- .changeset/cyan-books-act.md
- packages/wrangler/src/__tests__/api-dev.test.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/update-check.ts
Remake of #2982 
Fixes #2956.
Wrangler makes a HTTP request to the NPM registry, checking for updates to inform end users. While this makes sense in regular commands, it (generally) has little place in it's API, particularly when this is primarily used for tests. 
This pull request adds an experimental option which **disables** the update check, and optionally allows users to enable it. (There are cases for this, such as `pages dev`)
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber …
> Feat(unstable_dev): Don't fetch from npm on boot

- .changeset/shiny-worms-prove.md
- packages/create-cloudflare/src/frameworks/angular/templates/tools/alter-polyfills.mjs
- packages/create-cloudflare/src/frameworks/package.json
`performance.mark` and `global` polyfills are no longer needed in a v17 application.
See: https://github.com/angular/angular/pull/52505
> fix: remove unneeded polyfills from the Angular template

- .changeset/silver-goats-tickle.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/miniflare.ts
> wrangler: Hyperdrive dev bindings

- .changeset/rude-eagles-buy.md
- fixtures/durable-objects-app/package.json
- fixtures/durable-objects-app/src/index.js
- fixtures/durable-objects-app/tests/index.test.ts
- fixtures/durable-objects-app/tests/tsconfig.json
- fixtures/durable-objects-app/tsconfig.json
- fixtures/durable-objects-app/wrangler.toml
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- pnpm-lock.yaml
Fixes #3738.
**What this PR solves / how to test:** Improves error message for a worker missing a durable object export
- Tests
> Fix: provide proper error message for missing DOs

- .changeset/dirty-bobcats-eat.md
- .github/workflows/c3-e2e.yml
- packages/create-cloudflare/e2e-tests/pages.test.ts
- packages/create-cloudflare/package.json
- packages/create-cloudflare/src/frameworks/angular/index.ts
- packages/create-cloudflare/src/frameworks/astro/index.ts
- packages/create-cloudflare/src/frameworks/docusaurus/index.ts
- packages/create-cloudflare/src/frameworks/gatsby/index.ts
- packages/create-cloudflare/src/frameworks/hono/index.ts
- packages/create-cloudflare/src/frameworks/next/index.ts
- packages/create-cloudflare/src/frameworks/nuxt/index.ts
- packages/create-cloudflare/src/frameworks/qwik/index.ts
- packages/create-cloudflare/src/frameworks/react/index.ts
- packages/create-cloudflare/src/frameworks/remix/index.ts
- packages/create-cloudflare/src/frameworks/solid/index.ts
- packages/create-cloudflare/src/frameworks/svelte/index.ts
- packages/create-cloudflare/src/frameworks/vue/index.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/pages.ts
Fixes #4230
This fixes a regression that was causing c3 to fail with web frameworks when using yarn. 
Being able to version the framework creators we use is important for c3, but unfortunately `yarn` can't `yarn create some-framework@some-particular-version`. This change modifies the `runFrameworkGenerator` helper to use `npx` and spoof the npm user agent so framework creators treat it like a `yarn create` invocation. 
It also patches the package manager reset logic to make it only run when truly needed (i.e. when there's a mismatch between installed node modules and the type of lockfile used by the desired package manager).
This also adds e2e coverage for yarn to hopefully prevent future regressions.
- Tests
- …
> C3: Fix usage with yarn

- .changeset/forty-rice-smoke.md
- packages/miniflare/src/index.ts
- packages/miniflare/test/index.spec.ts
Fixes #4363.
This PR ensures `Miniflare#ready` is rejected if `Miniflare#dispose()` is called while waiting on the `ready` promise.
- Tests
> [miniflare] fix: reject `Miniflare#ready` promise if `dispose()`ed while waiting

- .changeset/tricky-masks-accept.md
- packages/miniflare/src/index.ts
- packages/miniflare/test/index.spec.ts
Fixes #4362.
Previously, Miniflare would register two exit hooks: one to remove its temporary directory, and one to shutdown `workerd`. These exit hooks are executed synchronously in the order they're registered: https://github.com/sindresorhus/exit-hook/blob/06b9fa48ef2c8245b42c558136d75e52ef833022/index.js#L14-L16. This meant we would try to remove the temporary directory before shutting down `workerd`. On Linux and macOS this is fine, but on Windows, this could lead to `EBUSY` errors as `workerd` still had an open handle on the directory. This change ensures we attempt to shutdown `workerd` before removing the directory. Since we can only clean up on a best effort basis when exiting, it also catches any errors thrown when removing the directory, …
> [miniflare] fix: cleanup temporary directory after shutting down `workerd`

- .github/workflows/c3-e2e-dependabot.yml
Sometimes frameworks are on pre-release versions which were not being matched.
See https://github.com/cloudflare/workers-sdk/actions/runs/6797153737/job/18478682041?pr=4396
> ci: fix semver regex in C3 dependabot CI jobs

- .changeset/shiny-rats-hide.md
- .changeset/small-gifts-smash.md
- packages/miniflare/src/http/helpers.ts
- packages/miniflare/src/index.ts
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/proxy.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/https-options.ts
- pnpm-lock.yaml
This provides support for ipv6 with `wrangler dev`
Fixes #3732 
- Tests
> Change default ip for dev server from `0.0.0.0` to `*`

- .changeset/loud-taxis-drop.md
- packages/miniflare/bootstrap.js
- packages/miniflare/package.json
Fixes #4355
Miniflare 3 doesn't include a CLI anymore, but should log a useful error stating this when running `npx miniflare`. We had a script for this, but it wasn't correctly hooked up. :facepalm: To test this, run `npx miniflare` in the `packages/wrangler` directory.
- Tests
> [miniflare] fix: add `miniflare` `bin` entry

- packages/create-cloudflare/e2e-tests/pages.test.ts
Removing nuxt from the C3 e2e quarantine since it seems like the nitro regression (that made nuxt not work) has been fixed: https://github.com/unjs/nitro/releases/tag/v2.7.2
> unquarantine nuxt

- .changeset/orange-lamps-happen.md
- packages/wrangler/src/__tests__/cfetch-utils.test.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/user/choose-account.tsx
- packages/wrangler/src/whoami.ts
Fixes #4349
The existing `fetchListResult` handler for fetching potentially paginated results doesn't work for endpoints that don't implement `cursor`.
This PR adds a naive handler that uses `page`, assuming `result_info` provided by the endpoint contains `page`, `per_page`, and `total`
FYI @celso
> fix(fetch): use pages for pagination instead of cursor

- .changeset/thin-pears-repeat.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/deployment-bundle/worker.ts
Reverts cloudflare/workers-sdk#3845
> Revert "feat(workers): allow namespaced scripts to be used as Worker tail consumers"

- .changeset/warm-dryers-double.md
- packages/wrangler/src/__tests__/api-devregistry.test.ts
- packages/wrangler/src/__tests__/unstableDev.test.ts
- packages/wrangler/src/dev-registry.ts
- packages/wrangler/src/dev/inspect.ts
Fixes #4430
The dev registry and inspector server listen on all interfaces when running `wrangler dev`, this might not be desired by users who use `--ip` to prevent listening beyond `localhost`. This PR will will make the dev registry and inspector server use `127.0.0.1`
- Tests
> Change dev registry and inspector server to use 127.0.0.1 instead of all interfaces

- .changeset/empty-islands-peel.md
- packages/wrangler/src/sourcemap.ts
When writing some new E2E tests for `wrangler dev (--remote)` I noticed the line/column numbers reported for uncaught errors were different between local and remote modes. It turns out the Chrome DevTools protocol reports line and column numbers 0-indexed, but `source-map-support` expects them to be 1-indexed. This meant https://github.com/cloudflare/workers-sdk/pull/3951/commits/d414ca9f60b29e1be78c4f4d34dd35e818d9a3b9 therefore broke `--remote` source mapping. 🙁 
To test this fix, run `wrangler dev --remote` in `fixtures/worker-app`, and replace the worker's `fetch()` handler with a `throw new Error()`. Make a request, then verify clicking the URL in your editor goes to the `new Error()`.
- Tests
- Changeset …
> [wrangler] fix: report correct line/column numbers source mapping remote errors

- .changeset/proud-readers-cough.md
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
Result:
As you can see anyways we do say "your workerd has access to the following bindings" which is not really correct and might be confusing to people as @pi0 mentioned here: https://github.com/cloudflare/workers-sdk/issues/4360#issuecomment-1813262660
We could change that by tweaking the `printBindings` function:
https://github.com/cloudflare/workers-sdk/blob/46a35e07d103ee21589169f91ee68218e6050246/packages/wrangler/src/config/index.ts#L81
So that it is aware whether is run in invoked in local mode so that we don't even show the bindings or show them with a warning or something like that.
I started looking into it but I was afraid that it could be a bit of a controversial change (also the function [generates a single text message and logs it in one …
> Warn about AI in dev local

- .changeset/fair-emus-jam.md
- packages/miniflare/README.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/miniflare/src/shared/error.ts
- packages/miniflare/src/shared/types.ts
- packages/miniflare/test/index.spec.ts
- packages/miniflare/test/plugins/core/proxy/client.spec.ts
- packages/miniflare/test/shared/types.spec.ts
Fixes cloudflare/workers-sdk#4358
This change adds a new `wrappedBindings` worker option for configuring `workerd`'s wrapped bindings. These allow custom bindings to be written as JavaScript functions accepting an `env` parameter of "inner bindings" and returning the value to bind.
This unblocks internal teams that would like to migrate to Miniflare 3, but depend on internal bindings that the public version of `workerd` doesn't support. Wrapped bindings allow these teams to write mock implementations.
The `wrappedBindings` option maps binding names to designators. The worker defined by the designator is used for the wrapped binding's source and inner bindings. The worker becomes un-routable, and cannot be used for service or Durable Object bindings. …
> [miniflare] feat: add support for wrapped bindings

- CONTRIBUTING.md
Fixes DEVX-999
This adds some docs on the testing setup within `workers-sdk`
- Tests
> Add test docs

- .changeset/heavy-dogs-serve.md
- packages/wrangler/src/dev/dev.tsx
This change ensures Wrangler doesn't try to open `http://*` when `*` is used as the dev server's hostname. Instead, Wrangler will now open `http://127.0.0.1`.
- Tests
> fix: open browser to correct url pressing `b`

- .changeset/itchy-days-greet.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/helpers/cli.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/templateMap.ts
In a [previous change](https://github.com/cloudflare/workers-sdk/pull/4062/files) we changed the default project type from `hello-world` to `webFramework`. We received some feedback from the community that this makes the use case of creating a vanilla worker harder, and that it breaks examples/tutorials in our docs where we suggest using `--accept-defaults` for creating workers.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so …
> C3: Change default project type to hello world worker

- .changeset/itchy-days-greet.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/helpers/cli.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/templateMap.ts
This unreverts the commit reverted in https://github.com/cloudflare/workers-sdk/pull/4493
- Tests
> Unrevert commit reverted in #4493

- packages/wrangler/package.json
- pnpm-lock.yaml
I think that the `npx-import` dependency is not actually used anywhere so I think it's safe to remove it
> remove unused npx-import dependency

- .changeset/serious-toys-repeat.md
- fixtures/dev-env/package.json
- fixtures/dev-env/tests/index.test.ts
- fixtures/worker-ts/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/wrangler/package.json
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/src/api/startDevWorker/events.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts
- packages/wrangler/templates/startDevWorker/ProxyWorker.ts
- pnpm-lock.yaml
This PR is for all changes made since Milestone 1 was first merged in #3960
Notable commits:
- bedbe4eb fix: don't show logs to ProxyWorker(s) unless log level is debug
- fixes #4168 
- 76f90edf fix: show console.log's in remote mode remote inspector websocket upgrade request required auth headers so use `fetch` with `Upgrade: websocket` header instead of `new WebSocket`
- fixes #4165 
- 1271a1ae use miniflare verbose mode only if debug log level
- should reduce "scary logs" noise
- 7198a81b register ProxyWorker with DevRegistry instead of UserWorker
- f09c51dc Revert "register ProxyWorker with DevRegistry"
- this commit has been applied+reverted and will be reapplied in Milestone 2 due to its dependence on the new `bindings` shape
- it is an …
> startDevWorker Milestone 1 - Reboot

- fixtures/additional-modules/test/index.test.ts
- fixtures/external-durable-objects-app/tests/index.test.ts
- fixtures/import-wasm-example/tests/index.test.ts
- fixtures/node-app-pages/tests/index.test.ts
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-functions-wasm-app/tests/index.test.ts
- fixtures/pages-functions-with-routes-app/tests/index.test.ts
- fixtures/pages-plugin-mounted-on-root-app/tests/index.test.ts
- fixtures/pages-simple-assets/tests/index.test.ts
- fixtures/pages-workerjs-and-functions-app/tests/index.test.ts
- fixtures/pages-workerjs-app/tests/index.test.ts
- fixtures/pages-workerjs-directory/tests/index.test.ts
- fixtures/pages-workerjs-wasm-app/tests/index.test.ts
- fixtures/pages-workerjs-with-routes-app/tests/index.test.ts
- fixtures/pages-ws-app/tests/index.test.ts
- fixtures/remix-pages-app/tests/index.test.ts
- fixtures/shared/src/run-wrangler-long-lived.ts
- fixtures/worker-app/tests/index.test.ts
Some fixture tests explicitly set `port: 0` to allow for parallel execution with other tests. This avoided running into a race condition with other tests for the main port. Before startDevWorker Milestone 1, when losing the race for the default inspector port 9229, the inspector proxy server would just fail to start and not cause the proxy server to fail to start. Now the ProxyWorker and InspectorProxyWorker start in the same Miniflare/workerd instance, so if the InspectorProxyWorker tries to bind to a port that is already bound, the ProxyWorker would be blocked from starting also. Considering these tests already make concessions for a random main port, they should also set a random inspector port. Further, these tests don't actually use the inspector at all, so for now there's no need …
> Improve fixture test stability

- .changeset/soft-chairs-share.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/kv/index.ts
- packages/miniflare/src/plugins/kv/sites.ts
- packages/miniflare/test/fixtures/sites/modules.ts
Fixes #4374.
When using Workers Sites with a module worker, the asset manifest must be imported from the `__STATIC_CONTENT_MANIFEST` virtual module. Miniflare provided this module, but also erroneously added `__STATIC_CONTENT_MANIFEST` to the `env` object too. Whilst this didn't break anything locally, it could cause users to develop Workers that ran locally, but not when deployed. This change ensures `env` doesn't contain `__STATIC_CONTENT_MANIFEST`.
To test this, run `wrangler dev` in `fixtures/sites-app` and verify `__STATIC_CONTENT_MANIFEST` doesn't appear in the `env` object.
- Tests
- …
> [miniflare] fix: remove `__STATIC_CONTENT_MANIFEST` from module worker `env`

- .changeset/early-lizards-knock.md
- packages/cli/interactive.ts
- packages/create-cloudflare/src/cli.ts
This PR improves the `wrangler init --from-dash` workflow by:
- Displaying a label for the pre-existing type (currently says `type: undefined`)
- Defaulting the project name to the name of the pre-existing script
- Tests
> More wrangler init --from-dash improvements

- .github/workflows/write-prerelease-comment.yml
The variable name has a dash instead of an underscore
([source](https://github.com/cloudflare/workers-sdk/blob/18a4dd92456f955ccbb35567a88475beafda01c0/.github/workflows/create-pullrequest-prerelease.yml#L110))
([example run](https://github.com/cloudflare/workers-sdk/actions/runs/7035882053/job/19147287700#step:6:28))
> use proper env variable for C3 prerelease comment

- .changeset/heavy-cherries-fetch.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Fixes a bug where users with the standard usage model would have an explicit usage model defined in their `wrangler.toml` when they initialized a Worker from dash. Testing can be done by building and then running `wrangler init --from-dash [worker] -y --no-delegate-c3` on an account that has opted into the new standard pricing and ensuring there is no usage model defined in the config.
- Tests …
> fix: init from dash using explicit usage model for standard accounts

- .changeset/slow-pants-fetch.md
- packages/miniflare/src/workers/shared/keyvalue.worker.ts
- packages/miniflare/test/plugins/cache/index.spec.ts
- packages/miniflare/test/plugins/kv/index.spec.ts
cloudflare/miniflare#656 introduced a bug in the SQL statement used for getting the old blob ID of entries to delete when overriding keys. This meant if a key was overridden, the old blob pointed to by that key was not deleted. This lead to an accumulation of garbage when `kvPersist` and `cachePersist` were enabled. This shouldn't have caused any problems, but could lead to persistence directories growing unnecessarily as they filled up with garbage blobs. This change ensures garbage blobs are deleted, and adds some regression tests to prevent this happening again.
Note existing garbage will not be cleaned up. If you'd like to do this, download this Node script (https://gist.github.com/mrbbot/68787e19dcde511bd99aa94997b39076). If you're using the …
> fix: ensure unused KV and Cache blobs cleaned up

- .changeset/quick-pens-develop.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/pages/dev.ts
Closes DEVX-1076
On Windows, when specifying `localhost` as the socket hostname, `workerd` will only listen on the IPv4 loopback `127.0.0.1`, not the IPv6 `::1`: https://github.com/cloudflare/workerd/issues/1408 On Node 17+, `fetch()` will only try to fetch the IPv6 address. For now, on Windows, this change defaults to listening on IPv4 only and using `127.0.0.1` when sending control requests to `workerd` (e.g. with the `ProxyController`).
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly …
> fix: listen on IPv4 loopback only by default on Windows

- .changeset/wise-seas-press.md
- fixtures/dev-env/tests/index.test.ts
- packages/miniflare/src/workers/core/proxy.worker.ts
- packages/miniflare/test/plugins/core/proxy/client.spec.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts
`Host` and `Origin` headers are now checked when connecting to the inspector and Miniflare's magic proxy. If these don't match what's expected, the request will fail. To test this, host DevTools on a different networked computer, and try to connect to the local `wrangler dev` server from that. The request should fail. Connecting from the hosted devtools and local devtools should succeed. Miniflare's test suite should succeed too.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, …
> fix: validate `Host`/`Origin` headers in magic proxy and `InspectorProxyWorker`

- .changeset/tiny-sloths-kneel.md
- packages/miniflare/src/plugins/core/errors/index.ts
- packages/miniflare/src/workers/core/entry.worker.ts
- packages/miniflare/test/plugins/core/errors/index.spec.ts
This change ensures Miniflare's pretty error page includes the URL and headers of the incoming request, rather than Miniflare's internal request from `workerd` to the loopback server.
The request URL has been incorrect since the pretty error page was introduced into version 3 (cloudflare/miniflare#436). The request headers have been incorrect since (cloudflare/miniflare#681). This change also adds some tests to prevent this regressing again.
To test, run `wrangler dev` with a worker that throws an unhandled exception and visit the page in your browser. The reported request URL should match the browser's URL, and the headers should match headers sent by the browser.
- Tests …
> fix: include request url and headers in pretty error page

- .github/extract-runtime-versions.mjs
Closes DEVX-1049
This PR ensures `miniflare`'s `workerd` version is pinned as part of CI. Specifically, the `Create Pull Request Prerelease` job will fail here...
https://github.com/cloudflare/workers-sdk/blob/70f634c563cc26e94df11d038faa0d4bae576f48/.github/workflows/create-pullrequest-prerelease.yml#L45-L46
...if `workerd` isn't pinned.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take inspiration …
> Assert `workerd` version pinned

- .changeset/warm-dryers-double.md
- .changeset/wise-seas-press.md
- packages/wrangler/src/__tests__/api-devregistry.test.ts
- packages/wrangler/src/dev-registry.ts
- packages/wrangler/src/inspect.ts
This PR backports some changes we recently made to the Wrangler 3's inspector proxy to Wrangler 2. Specifically, the inspector server now listens on local interfaces by default, and validates incoming `Host`/`Origin` headers.
- Tests
> [wrangler] Backport recent inspector proxy server changes to V2

- .changeset/three-horses-talk.md
- packages/create-cloudflare/src/common.ts
Fixing the broken `cd` instruction we get at the end of the build process:
(introduced in https://github.com/cloudflare/workers-sdk/pull/4579)
> amend broken cd instruction

- .github/workflows/c3-e2e-dependabot.yml
The indentation of the `include` field in the c3-e2e-dependabot yml is wrong, making the workflow not take effect:
https://github.com/cloudflare/workers-sdk/actions/runs/7207803909/workflow#L79
(sorry it's my bad, I missed this in https://github.com/cloudflare/workers-sdk/pull/4576 😓 🙇 )
> fix the include section in the c3-e2e-dependabot yml indentation

- .changeset/lazy-gifts-train.md
- fixtures/worker-app/src/index.js
- fixtures/worker-app/src/log.ts
- fixtures/worker-app/tests/index.test.ts
- packages/miniflare/package.json
- packages/miniflare/src/plugins/core/errors/index.ts
- packages/miniflare/src/plugins/core/errors/sourcemap.ts
- packages/miniflare/test/plugins/core/errors/index.spec.ts
- packages/miniflare/test/test-shared/asserts.ts
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/dev/inspect.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/sourcemap.ts
- pnpm-lock.yaml
Fixes #3383 and closes #3739.
Previously, Wrangler would only apply source mapping to uncaught exceptions. This meant if you caught an exception and logged its stack trace, the call sites would reference built JavaScript files as opposed to source files. This change looks for stack traces in logged messages, and tries to source map them.
Note source mapping is only applied when outputting logs. `Error#stack` does not return a source mapped stack trace. This means the actual runtime value of `new Error().stack` and the output from `console.log(new Error().stack)` may be different.
To test this, run the following worker with `wrangler dev`:
```ts
interface Env {
}
export default <ExportedHandler<Env>>{
fetch() {
console.log(new Error("1")); …
```
> [wrangler] feat: source map logged strings

- .changeset/cyan-yaks-rule.md
- fixtures/shared/src/run-wrangler-long-lived.ts
- package-lock.json
- package.json
- packages/wrangler/package.json
- packages/wrangler/src/dev/local.tsx
This PR aims to fix Wrangler 2's tests by pinning the version of `workerd` depended on by Miniflare 3.
- Tests
> [wrangler@2] fix: pin `workerd` to `1.20230404.0`

- .changeset/fresh-rockets-vanish.md
- packages/cli/interactive.ts
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/package.json
- packages/create-cloudflare/src/helpers/files.ts
- packages/create-cloudflare/src/templateMap.ts
- packages/create-cloudflare/src/workers.ts
- pnpm-lock.yaml
Closes #4599 
This fixes a bug introduced in 3.8.2 where the result of `processArgument` for `ts wasn't being used. See https://github.com/cloudflare/workers-sdk/pull/4470/commits/01e2542ba8b3badadebc73547a9e3744de4e2f9c
- Tests
> [C3] Ensure `ts` is defined

- .changeset/four-students-joke.md
- packages/wrangler/src/d1/info.tsx
- packages/wrangler/src/d1/types.ts
This PR adds `rowsRead` and `rowsWritten` to `wrangler d1 info <NAME>` output:
```
npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/7249340037/npm-package-wrangler-4621 d1 info northwind
✔ Select an account › D1
┌───────────────────┬──────────────────────────────────────┐
│                   │ d5b1d127-xxxx-xxxx-xxxx-cbc69f0a9e06 │
├───────────────────┼──────────────────────────────────────┤
│ name              │ northwind                            │
├───────────────────┼──────────────────────────────────────┤
│ created_at        │ 2023-05-23T08:33:54.590Z             │
├───────────────────┼──────────────────────────────────────┤
│ version           │ beta                                 │
├───────────────────┼──────────────────────────────────────┤
│ num_tables …
```
> [D1] add rows read/written to `wrangler d1 info` output

- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/deployment-bundle/build-failures.ts
This updates the error message to point the user that they might be missing `node:` in the module name for the imports, even if they enabled `nodejs_compat` in their project.
I'm open to changing the wording. This I did on a whim after receiving support from @KianNH on Discord which I thought might be worth highlighting in the error message.
It's about this error message from the CLI:
It can still occur when `nodejs_compat` is enabled but the imported package is not in the intended format - `node:{moduleName}`
- Tests
https://developers.cloudflare.com/workers/runtime-apis/nodejs/ …
> Add info about `node:${module}` syntax for nodejs_compat

- .changeset/fluffy-sheep-raise.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
This change adds support for managing [Sippy](https://developers.cloudflare.com/r2/data-migration/sippy/) on an R2 bucket.
The change was tested manually as automated test would require keeping valid S3 and R2 credentials.
Approval ticket: CR-747953
Docs PR: https://github.com/cloudflare/cloudflare-docs/pull/12295
> wrangler R2: Add Sippy support

- .changeset/wet-geckos-turn.md
- packages/create-cloudflare/src/frameworks/package.json
Fixes #4623.
Bumps `create-svelte` to a new major version. This clears up an issue we're seeing where the latest version of `@sveltejs/adapter-cloudflare` expects the latest major version of `sveltekit` and fails to install.
- Tests
- [ x ] Not necessary because: Just a package bump, existing coverage is fine.
> C3: Bump  to 6.0.3

- .changeset/metal-houses-drop.md
- packages/wrangler/src/index.ts
Fixes #4612.
Fixes #4131.
Fixes cloudflare/workers-rs#425.
Previously, running `wrangler dev` would leave behind "zombie" `workerd` processes. These processes prevented the same port being bound if `wrangler dev` was restarted and sometimes consumed lots of CPU time. This PR ensures all `workerd` processes are killed when `wrangler dev` is shutdown.
Massive thank you to @ezg27 for identifying that commenting out `await closeSentry()` fixes the issue. I'm still not quite sure why this is happening. This is what I've observed:
- This issue only occurs in production builds (when the `SENTRY_DSN` environment variable is set during the build)
- Starting `wrangler-dist/cli.js` directly rather than through the `bin/wrangler.js` bootstrapper fixes the issue …
> [wrangler] fix: prevent zombie `workerd` processes

- .github/workflows/playground-preview-worker.yml
Previously we were deploying `playground-preview-worker` every time a PR was merged to `main`. We now instead only trigger this workflow run when that push to `main` includes changes to the `packages/playground-preview-worker` directory.
> Stop deploying playground-preview-worker on every merge

- .github/workflows/edge-preview-authenticated-proxy.yml
Previously we were deploying `edge-preview-authenticated-proxy` every time a PR was merged to `main`. We now instead only trigger this workflow run when that push to main includes changes to the `packages/edge-preview-authenticated-proxy` directory.
> Stop deploying edge-preview-authenticated-proxy on every merge

- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/tests/index.test.ts
Fixes VULN-49261
This PR fixes a vulnerability that allowed Workers Playground preview instances to be accessed from outside of playground contexts.
- Tests
> [playground-preview-worker] Reject /.update-preview-token requests from regular browsing contexts

- .changeset/tasty-experts-protect.md
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
- packages/wrangler/src/deployments.ts
- packages/wrangler/src/index.ts
Fixes #3372.
Previously, Wrangler would fail with a cryptic error if you tried to run `wrangler rollback` outside of a directory containing a Wrangler configuration file with a `name` defined. This change validates that a worker name is defined, and allows you to set it from the command line using the `--name` flag. To test this, try to run `wrangler rollback` in a directory without a `wrangler.toml`. This should fail, but running `wrangler rollback --name <NAME_TO_VALID_WORKER>` should succeed.
- Tests
We want to celebrate and highlight awesome PR …
> [wrangler] fix: require worker name for rollback

- packages/wrangler/src/index.ts
The actual command is `--scopes-list` but the error today says it is `--list-scopes`
> Fix help message for listing scopes

- .changeset/lucky-ghosts-sell.md
- packages/create-cloudflare/src/helpers/__tests__/command.test.ts
- packages/create-cloudflare/src/helpers/command.ts
It seems like the workerd compatibility retrieval can have some issues with different package managers (or at least with `yarn`):
- https://github.com/cloudflare/workers-sdk/actions/runs/7211842007/job/19748508606?pr=4602#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7250601828/job/19751164094?pr=4604#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7246672804/job/19747293009?pr=4617#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7246765792/job/19742158656?pr=4618#step:4:65
- https://github.com/cloudflare/workers-sdk/actions/runs/7260941093/job/19781139701?pr=4629#step:4:65
The changes here make this more stable by always using fetching the date directly from the npm registry instead
> make the workerd compatibility date retrieval more stable by fetching it directly from the npm registry

- .changeset/perfect-students-pull.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/index.ts
Fixes #2721.
Previously, if you tried to use `wrangler r2 object get` with an object name containing a `/` or used the `--file` flag with a path containing a `/`, and the specified directory didn't exist, Wrangler would throw an `ENOENT` error. This change ensures Wrangler automatically creates required parent directories if they don't exist.
To test, run `wrangler r2 object get <bucket-name>/<object-name>` with an `<object-name>` containing a `/`, or run with the `--file <output-file>` flag with `<output-file>` containing a `/`.
- Tests
We want to …
> fix: create required parent directories for `wrangler r2 object get`

- .changeset/strange-eels-search.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/index.ts
Fixes #4078.
The API tokens set with the `CLOUDFLARE_API_TOKEN` environment variable may not include all required permissions for Wrangler. This change ensures the error message for authentication errors includes a suggestion to check token permissions. Ideally, authentication errors would inclusion the name of the required permission that was missing, but they don't. 🙁 
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future …
> [wrangler] fix: check permissions on authentication error with API token set

- .changeset/stupid-frogs-obey.md
- packages/wrangler/src/__tests__/cfetch-utils.test.ts
- packages/wrangler/src/cfetch/index.ts
Fixes #2775.
This PR ensures we display any `messages` returned from the API in our error messages. These might include additional information useful for debugging.
- Tests
> [wrangler] fix: include messages from API in errors

- .changeset/serious-seals-sneeze.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/cfetch/errors.ts
- packages/wrangler/src/cfetch/index.ts
Fixes #4187.
Previously, Wrangler would display the raw API error message and code if email validation was required during `wrangler deploy`. This change ensures a helpful error message is displayed instead, prompting users to check their emails or visit the dashboard for a verification link. To test this, try run `wrangler deploy` using a `workers.dev` subdomain on an account without a verified email. (I assume you've got one of those lying around! 😛)
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a …
> [wrangler] fix: throw helpful error if email validation required

- .changeset/olive-chefs-sleep.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/sourcemap.ts
Fixes #2741.
Previously if a Worker failed validation during `wrangler deploy`, the displayed error would reference locations in built JavaScript files. This made it more difficult to debug validation errors. This change ensures these errors are now source mapped, referencing locations in source files instead. To test this, try to deploy a TypeScript worker referencing a non-existent variable in the global scope. The validation error should include the location in the TypeScript file.
- Tests
We want to celebrate and highlight awesome PR review! If you …
> [wrangler] fix: apply source mapping to deployment validation errors

- templates/experimental/worker-rust/Cargo.toml
- templates/experimental/worker-rust/package.json
- templates/experimental/worker-rust/wrangler.toml
Fixes # [3566].
This PR fixes #3566 by updating the wrangler version for the rust worker template, as there was a package.json script in the template that calls `wrangler deploy` when the version in the package.json dependencies of wrangler doesn't support that command.
(The change is too minor for a changes)
> Update wrangler dep in package.json for rust template

- .changeset/fifty-crabs-flow.md
- packages/wrangler/src/__tests__/cfetch-utils.test.ts
- packages/wrangler/src/cfetch/index.ts
Fixes #4694.
This PR ensures API failures with a `messages` property are logged correctly. Our `FetchResult` type had incorrectly assumed these would always be included in a response.
- Tests
> [wrangler] fix: ensure API failures without `messages` logged correctly

- .changeset/small-fishes-tan.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
Fixes #4663.
If your Worker fails to deploy because it's too large, Wrangler will display of list of your Worker's largest dependencies. Previously, this just included JavaScript dependencies. This change ensures additional module dependencies (e.g. WebAssembly, text blobs, etc.) are included when computing this list. To test this, run `wrangler deploy` on a worker that imports a large dependency (e.g. a massive text file). The logged error should include the path to the text file.
- Tests
We want to celebrate and highlight awesome PR review! If you think …
> [wrangler] fix: include additional modules in `largest dependencies` warning

- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/prereleases.yml
- .github/workflows/release.yml
This PR temporarily disables Sentry error reporting whilst we discuss what errors/metadata we want to be sending. 
- Tests
> chore: temporarily disable sentry error reporting

- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
Currently the following:
```toml
[unsafe.metadata]
myprop = { something = "whatever" }
```
Will print:
```
Your worker has access to the following bindings:
- Unsafe Metadata:
- myprop: [object Object]
```
After this PR it will print:
```
Your worker has access to the following bindings:
- Unsafe Metadata:
- myprop: {"something": "whatever"}
```
Alternatives include:
- just `JSON.stringify` everything, including primitives
- create a more complex formatter that nests nicely, etc (not sure what unsafe bindings do here)
> [wrangler] Add better printing for complex unsafe metadata

- .changeset/gorgeous-turkeys-wait.md
- packages/wrangler/src/api/startDevWorker/events.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/start-server.ts
Fixes #4673.
`wrangler@3.19.0` introduced a bug where starting multiple `wrangler dev` sessions with service bindings to each other resulted in a reload loop. This change ensures Wrangler only reloads when dependent `wrangler dev` sessions start/stop, by registering workers in the dev registry with the URL of the proxy worker, not the user worker.
Using the user worker URL meant that when a dependent service was started, the original service picked up the change and restarted its user worker getting a new port. The original service registered this new port, which was picked up by the dependent service which itself restarted its user worker on a new port. This created a reload loop.
We're planning to slightly change how dev registry registration works …
> [wrangler] fix: prevent repeated reloads with circular service bindings

- .changeset/late-clocks-reply.md
- packages/miniflare/src/workers/d1/database.worker.ts
- packages/miniflare/src/workers/shared/sql.worker.ts
- packages/miniflare/test/plugins/d1/suite.ts
Fixes #4671.
This PR exposes `rows_read`/`rows_written` in the `meta` object of D1 responses. This matches production behaviour. `rows_read`/`rows_written` contain the number of rows read from/written to the database engine when executing a query respectively. These numbers may be greater than the number of rows returned from/inserted by a query. These numbers form billing metrics when your Worker is deployed. See https://developers.cloudflare.com/d1/platform/pricing/#billing-metrics and https://github.com/cloudflare/workerd/pull/979 for more details. To test this, run `wrangler dev` on a Worker using D1 databases. Observe `rows_read` and `rows_written` are now included in `meta`.
- Tests
- Changeset …
> [miniflare] feat: expose `rows_read`/`rows_written` in D1 `meta`

- .changeset/ten-dancers-wonder.md
- fixtures/pages-functions-app/tests/index.test.ts
- packages/wrangler/src/api/dev.ts
Fixes #4210.
Running `wrangler pages dev` would previously log a warning saying `--local is no longer required` even though `--local` was never set. This change removes this warning. To test this, run `wrangler pages dev` and make sure `--local is no longer required` doesn't appear.
- Tests
> fix: remove confusing `--local` messaging from `wrangler pages dev`

- .changeset/funny-otters-sing.md
- packages/wrangler/src/__tests__/helpers/mock-account-id.ts
- packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/r2/index.ts
Previously, Wrangler would ask you to login when reading or writing from local R2 buckets. This change ensures no login prompt is displayed, as authentication isn't required for these operations. To test this, run `wrangler logout`, then `wrangler r2 object put TEST_BUCKET/a.txt --file <local_file> --local` and observe the object is written without a login prompt.
This PR also fixes an issue with `mockApiToken()` and `mockAccountId()` where they weren't correctly unsetting API tokens in `afterEach()` hooks. This was causing some tail tests to erroneously pass.
- Tests
**Note for …
> [wrangler] fix: don't require auth for `wrangler r2 object --local` operations

- .changeset/odd-fans-own.md
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/miniflare/package.json
- packages/miniflare/src/plugins/core/errors/index.ts
- packages/miniflare/src/plugins/core/errors/sourcemap.ts
- packages/miniflare/src/plugins/index.ts
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/sourcemap.ts
- pnpm-lock.yaml
Fixes #4715.
Previously, if in a `wrangler dev` session you called `console.log()` and threw an unhandled error you'd see an error like `[ERR_ASSERTION]: The expression evaluated to a falsy value`. This change ensures you can do both of these things in the same session.
This broke when we switched from `source-map-support` to `@cspotcode/source-map-support` as part of #4423. `@cspotcode/source-map-support` has some additional code to share state between different instances of the module. In particular, if the module was loaded once, future calls to any new instance's `install()` function wouldn't set `Error.prepareStackTrace`, leading to this assertion error in either Miniflare or Wrangler (depending on which one installed support first). We want …
> fix: ensure `miniflare`/`wrangler` can source map in the same process

- .github/workflows/format-errors.yml
Previously, we were re-deploying the `format-errors` worker on every merge to `main`, even if no changes were made to it. This is probably fine, but our other workers (`edge-preview-authenticated-proxy` and `playground-preview-worker`) have `paths` filters to only deploy when their source changes. This PR adds a `paths` filter for `format-errors` so we only deploy it when we've made changes.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight …
> fix: only deploy `format-errors` worker when files change

- .changeset/sharp-rivers-carry.md
- fixtures/worker-app/src/log.ts
- fixtures/worker-app/tests/index.test.ts
- packages/wrangler/src/sourcemap.ts
Fixes #4668.
Previously, logs containing `at ` were always treated as stack trace call sites requiring source mapping. This change updates the call site detection to avoid false positives, by requiring an indent of 4 spaces and a valid file name. We aren't able to rely on newlines here, as we support source mapping with `console.log({ stack: new Error("oopps").stack })`. In this case, the `value` passed to `getSourceMappedString()` contains ANSI colour codes and looks something like...
```
{
value: '{\n' +
"  stack: \x1B[32m'Error: oopps\\n'\x1B[39m +\n" +
"    \x1B[32m'    at Object.fetch (file:///Users/bcoll/.wrangler/tmp/dev-Bzz87I/index.js:53:26)\\n'\x1B[39m +\n" +
"    \x1B[32m'    at __facade_modules_fetch__ …
```
> fix: ensure logs containing `at ` not truncated to `at [object Object]`

- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
I've observed the `worker-app` tests flaking quite a bit recently. I think this is because logs aren't being flushed fast enough. This PR waits for up to 5s for a log logged at the end of the request to appear, ensuring all assertions run once all request logs have been flushed.
- Tests
> fix: make `worker-app` test more reliable

- packages/edge-preview-authenticated-proxy/package.json
- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/worker-configuration.d.ts
- packages/format-errors/package.json
- packages/format-errors/src/index.ts
- packages/playground-preview-worker/package.json
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/worker-configuration.d.ts
- pnpm-lock.yaml
Fixes [DEVX-1090](https://jira.cfdata.org/browse/DEVX-1090), [DEVX-1091](https://jira.cfdata.org/browse/DEVX-1091), [DEVX-1092](https://jira.cfdata.org/browse/DEVX-1092)
Adds prometheus counter metrics for requests and errors for the `edge-preview-authenticated-proxy`, `format-errors`, `playground-preview-worker` workers
Decisions made during implementation:
- metric name format: `<team-name>_<service-name>_[request|error]_total` where service-name is the original kebab-case (hyphenated) name even amongst a snake_case metric name
- no labels (i.e. for request pathname) have been added – we can choose to do so later
Still TODO:
- Tests …
> Prometheus metrics

- .changeset/eighty-hotels-train.md
- fixtures/pages-dev-proxy-with-script/_worker.js
- fixtures/pages-dev-proxy-with-script/custom/script/path/index.js
- fixtures/pages-dev-proxy-with-script/package.json
- fixtures/pages-dev-proxy-with-script/tests/index.test.ts
- fixtures/pages-dev-proxy-with-script/tests/tsconfig.json
- fixtures/pages-dev-proxy-with-script/tsconfig.json
- fixtures/pages-dev-proxy-with-script/vitest.config.ts
- packages/wrangler/src/pages/dev.ts
- pnpm-lock.yaml
> Make sure that the correct entrypoint file path is applied when bundling Pages applications

- packages/playground-preview-worker/src/index.ts
Previously, we were marking all requests that threw `HttpError`s as "errored". This change ensures only `reportable` errors are included in metrics.
- Tests
> fix: only include reportable playground errors in metrics

- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/rules.ts
Fixes #682
Changes module collection warnings from
```
▲ [WARNING] The module rule at position 1 ({"type":"Text","globs":["**/*.other"]}) has the same type as a previous rule (at position 0, {"type":"Text","globs":["**/*.file"]}). This rule will be ignored. To use the previous rule, add `fallthrough = true` to allow this one to also be used, or `fallthrough = false` to silence this warning.
▲ [WARNING] The default module rule {"type":"Text","globs":["**/*.txt","**/*.html"]} has the same type as a previous rule (at position 0, {"type":"Text","globs":["**/*.file"]}). This rule will be ignored. To use the previous rule, add `fallthrough = true` to allow the default one to also be used, or `fallthrough = false` to silence this warning.
```
to
```
▲ [WARNING] The module rule …
```
> Improve module collection warnings

- packages/create-cloudflare/src/__tests__/workers-types.test.ts
- packages/create-cloudflare/src/frameworks/next/index.ts
- packages/create-cloudflare/src/frameworks/next/templates.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/workers.ts
Updates starter template that running `npm create cloudflare` and selecting Next.js creates, to make use of bindings proxy, as [implemented in `next-on-pages`](https://github.com/dario-piotrowicz/next-on-pages/blob/main/internal-packages/next-dev/README.md).
Provides a starting point that shows how to work with bindings in local dev, even when local dev server is in Node.js.
- the standard Next.js scripts:
- `dev` for local development
- `build` for building the application
- the pages scripts
- `pages:preview` for previewing the pages app locally (basically the current `pages:dev`)
- `pages:deploy` for deploying the pages app
- `pages:build` for building the pages application (run as a pre-set by `pages:preview` and `pages:deploy`)
- and we need to remove:
- `pages:dev` (since users …
> Update Next.js template to support bindings

- .github/get-c3-dependabot-bumped-framework.cjs
- .github/workflows/c3-e2e-dependabot.yml
improve the c3 dependabot testing workflow by
- externalizing js code inlined in yml files
- not relying on dependabot PR descriptions which can potentially create issues and be unreliability
___
This PR should fix the recent issue we've had with the c3 dependabot workflow failing to detect the bumped framework (see: https://github.com/cloudflare/workers-sdk/actions/runs/7385419011/job/20090141538?pr=4678#step:3:324)
> improve the c3 dependabot workflow

- .changeset/green-items-serve.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
Only specifying the name and type of a binding instructs the patch API to copy the existing binding over - but we were including the contents of the binding as well. Normally that's OK, but there are some subtle differences between what you specify to _create_ a binding vs what it looks like once it's _created_, specifically for Durable Objects. So instead, we just use the simpler inheritance.
Note that this depends on a not-yet-released EWC change to fix a separate bug in the patch API, and should hold until that makes it out
Fixes #4496, WC-1774
> Fix usage of patch API in bulk secrets update

- .changeset/serious-lemons-carry.md
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
Fixes #4743.
This PR ensures URLs aren't modified when requests pass through Wrangler's proxy server. Specifically, it ensures this `DurableObjectStub#fetch()`...
https://github.com/cloudflare/workers-sdk/blob/54ea6a53bd1f222308135ed96bbb16a019302382/packages/wrangler/templates/startDevWorker/ProxyWorker.ts#L31
...preserves the URL, by enabling the `durable_object_fetch_requires_full_url` compatibility flag in the proxy workers. This flag disables `workerd`'s legacy behaviour of resolving this URL relative to `http://fake-host` and leaves the URL untouched. To test this, run `wrangler dev` against a worker that logs its incoming URL, e.g.
```js
async fetch(request, env, ctx) {
console.log(request.url);
return new Response("body");
} …
```
> [wrangler] fix: ensure dev server doesn't change request URLs

- fixtures/worker-app/tests/https.test.ts
Fixes #4644.
When triaging #4644, we realised we didn't have integration tests for the `--local-protocol` flag. It looks like this flag is working correctly, but having a test means we shouldn't need to worry about this breaking in the future. 🙂 
- Tests
> test: add test for `--local-protocol=https`

- packages/eslint-config-worker/index.js
- packages/wrangler/src/cloudchamber/cli/deployments.ts
- packages/wrangler/src/cloudchamber/cli/index.ts
- packages/wrangler/src/cloudchamber/cli/locations.ts
- packages/wrangler/src/cloudchamber/ssh/ssh.ts
In all PRs we're getting this no-non-null-assertion warnings from cloudchamber, so I figured I could create a quick PR to clean them up
I'm also changing the rule to error so that we avoid these type of warnings (we already went through something like this with @1000hz, I think I remember we agreed on not using eslint warnings since they can indeed create unnecessary noise) (https://github.com/cloudflare/workers-sdk/pull/3833)
> fix no-non-null-assertion warnings coming the wrangler/src/cloudchamber

- .changeset/dull-jobs-deliver.md
- fixtures/get-bindings-proxy/custom-toml/path/test-toml
- fixtures/get-bindings-proxy/package.json
- fixtures/get-bindings-proxy/tests/index.test.ts
- fixtures/get-bindings-proxy/tsconfig.json
- fixtures/get-bindings-proxy/vitest.config.ts
- fixtures/get-bindings-proxy/workers/do-worker-a/index.ts
- fixtures/get-bindings-proxy/workers/do-worker-a/wrangler.toml
- fixtures/get-bindings-proxy/workers/do-worker-b/index.ts
- fixtures/get-bindings-proxy/workers/do-worker-b/wrangler.toml
- fixtures/get-bindings-proxy/workers/hello-worker-a/index.ts
- fixtures/get-bindings-proxy/workers/hello-worker-a/wrangler.toml
- fixtures/get-bindings-proxy/workers/hello-worker-b/index.ts
- fixtures/get-bindings-proxy/workers/hello-worker-b/wrangler.toml
- fixtures/get-bindings-proxy/wrangler.json
- fixtures/get-bindings-proxy/wrangler.toml
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/api/integrations/bindings/index.ts
- packages/wrangler/src/api/integrations/bindings/services.ts
- packages/wrangler/src/api/integrations/index.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/dev-registry.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/miniflare.ts
- pnpm-lock.yaml
This PR introduces a new `getBindingsProxy` that can be used externally to get a proxy to Miniflare bindings that integrate well with wrangler (e.g. with the toml file and the local registry)
You can see a demo of what this would look like here: [getBindingsProxy-poc-demo](https://github.com/dario-piotrowicz/getBindingsProxy-poc-demo)
> [!NOTE]
> Initially the utility was going to have two alternative argument APIs, one in which it would accept inline bindings (to use for Pages application) and one in which the bindings would instead be read from the `wrangler.toml` file (to use for Workers applications).
>
> We're currently considering if maybe it would be better to have this utility simply always only read the bindings from the `wrangler.toml` file (it would be a simpler API for users …
> implement `getBindingsProxy` utility

- .changeset/five-vans-compete.md
> feat: add "Hello World" example for Durable Objects

- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/tests/index.test.ts
This fixes an issue that caused requests made in the HTTP tab of Quick Editor and Playground to get blocked by CORS errors if they used a method other than GET or POST. We had inadvertently been sending the incorrect CORS header (singular `Access-Control-Allow-Method` instead of [`Access-Control-Allow-Methods`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Methods)).
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label …
> Fix typos in CORS headers for edge-preview workers

- packages/prerelease-registry/functions/routes/[repo]/prs/[[path]].ts
- packages/prerelease-registry/functions/routes/[repo]/runs/[[path]].ts
- packages/prerelease-registry/functions/utils/getArtifactForWorkflowRun.ts
4th and hopefully final time... This time just adding `response.text()` to the data returned but decided to respond with JSON since it was getting a bit long returning strings
Adding extra info to the response body when returning a 404 to aid debugging #4804.
- Tests
> [prerelease-registry]: add failed response.text to response to help diagnose why 403s are returned

- packages/wrangler/src/index.ts
- packages/wrangler/src/metrics/send-event.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/upload.ts
This PR implements the new Gradual Rollouts `versions upload` command for internal-use only. Therefore, it is hidden from the help output.
The command is _essentially_ the same as `deploy` and, for now, has been duplicated so as not to touch the deploy command implementation at all and, while we agree on the differences, the diff should be more readable this way. The PR is marked as draft and will be refactored to abstracted functions of shared implementation at a granular level before being marked as ready for review. This should allow internal use of the prerelease builds before going through that effort.
Please find the prerelease build instructions in a bot comment below. Specifically for this command you can run:
```sh
npx …
```
> Gradual Rollouts `versions upload` (experimental) command

- .changeset/giant-kings-heal.md
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/start-server.ts
**What this PR solves:**
In `wrangler dev` it is possible to set the `upstream_protocol`, which is the protocol under which the User Worker believes it has been requested, as recorded in the `request.url` that can be used for forwarding on requests to the origin.
This setting defaults to `https`. Previously, it was not being passed to `wrangler dev` in local mode. Instead it was always set to `http`.
Note that setting `upstream_protocol` to `http` is not supported in `wrangler dev` remote mode, which is the case since Wrangler v2.0.
Fixes #4539
**How to test:**
Using the build of Wrangler from this PR run `wrangler dev` on a simple worker as follows:
```ts
fetch(request: Request) {
return new Response(request.url);
}
}
```
Note that the response will be a URL that has …
> fix: ensure upstream_protocol is passed to the Worker

- .changeset/selfish-starfishes-cry.md
- fixtures/pages-d1-shim/tests/index.test.ts
- fixtures/pages-workerjs-directory/tests/index.test.ts
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/miniflare/src/workers/core/entry.worker.ts
The `wrangler dev` command puts the Worker under test behind a proxy server. This proxy server should be transparent to the client and the Worker, which means that the `Request` arriving at the Worker with the correct `url` property, and `Host` and `Origin` headers.
Previously we fixed the `Host` header but missed the `Origin` header which is only added to a request under certain circumstances, such as cross-origin requests.
This change fixes the `Origin` header as well, so that it is rewritten, when it exists, to use the `origin` of the `url` property.
A nice way to test this is to simply clone the reproduction from #4761 - https://github.com/Le0Developer/wrangler-host-header-repro, then replace the local Miniflare with the pre-release one from this …
> fix: ensure that Origin header is rewritten as necessary

- .changeset/three-carpets-kick.md
- fixtures/dev-env/tests/index.test.ts
- fixtures/dev-env/vitest.config.ts
- packages/wrangler/templates/startDevWorker/InspectorProxyWorker.ts
Fixes #4640.
Alternative fix to https://github.com/cloudflare/workers-sdk/pull/4331.
I wasn't able to reproduce any of the issues from #4640 on the latest version of `wrangler`. These were reported on `wrangler@3.17.1+` which was before we properly landed WaaL milestone 1. It's possible these regressions were from an earlier version of the WaaL work? In any case, this PR attempts to fix a related issue of caching script contents that could break breakpoint debugging: https://github.com/cloudflare/workers-sdk/pull/4331.
Previously, DevTools would never refresh source contents after opening a file, even if it was updated on-disk. This could cause issues with step-through debugging as breakpoints set in source files would map to incorrect locations in …
> [wrangler] fix: reset inspector execution contexts on reload

- .changeset/tender-owls-wink.md
- .gitignore
- CODEOWNERS
- packages/wrangler/src/cloudchamber/client/core/OpenAPI.ts
- packages/wrangler/src/cloudchamber/client/core/request.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/cloudchamber/index.ts
We like to use wrangler for internal usage of the Cloudchamber API and we would like to have a "dynamic" way of inserting internal CC commands into `wrangler cloudchamber`.
Let us know if this is a good way to do it; I personally like this solution as it adds a way for us to insert internal modules without us patching Wrangler or maintaining a fork.
- Tests
- [] Not necessary because: doesn't affect in any way users.
I'm also adding CODEOWNERS for Cloudchamber and a few nits that we found like adding a https undici Agent in the OpenAPI's fetch.
> cloudchamber: add internal module insertion

- .changeset/strange-bikes-run.md
- packages/create-cloudflare/src/__tests__/common.test.ts
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/helpers/cli.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/helpers/latestPackageVersion.ts
When create-cloudflare starts up, it checks to see if the version being run is the latest available on npm.
Previously this check used `npm info` to look up the version. But was prone to failing if that command returned additional unexpected output such as warnings.
Now we make a fetch request to the npm REST API directly for the latest version, which does not have the problem of unexpected warnings.
Since the same approach is used to compute the latest version of workerd, the function to do this has been put into a helper.
Fixes #4729
- Tests
> fix: correctly find the latest version of create-cloudflare

- .changeset/tame-melons-boil.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
- packages/wrangler/src/r2/sippy.ts
Added support for configuring Sippy with GCS provider in Wrangler. Enabling Sippy now prompts if parameters are not present
- Tests
> Added support for configuring Sippy with GCS provider in Wrangler

- .changeset/giant-sloths-check.md
- .prettierignore
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/templates/solid/c3.ts
- packages/create-cloudflare/templates/solid/js/vite.config.js
- packages/create-cloudflare/templates/solid/ts/vite.config.ts
The creation of solidStart applications is currently broken in C3 after their beta-2 bump (for example see the failing workflows here: https://github.com/cloudflare/workers-sdk/pull/4682)
This PR addresses this making solidStart apps work again
> C3: update the solidStart logic to work with their latest (beta-2) implementation

- packages/playground-preview-worker/package.json
- packages/turbo-r2-archive/package.json
- packages/workers-playground/package.json
- pnpm-lock.yaml
This reverts commit 14e64e97f06d1a0ebdefa8df7bd14f38b7de0ae3.
This bump to the Hono library broke playground-preview-worker tests, which were not run on the PR.
- Tests
> Revert "build(deps): bump hono from 3.5.6 to 3.11.7 (#4608)"

- .changeset/forty-needles-turn.md
- .changeset/four-teachers-push.md
- packages/create-cloudflare/src/common.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/next/c3.ts
- packages/create-cloudflare/templates/solid/c3.ts
- packages/create-cloudflare/templates/svelte/c3.ts
> C3: replace Svelte's `pages:dev` with `pages:preview` and add optional previewScript to the c3 summary

- .changeset/wet-lemons-wash.md
- packages/pages-shared/metadata-generator/createMetadataObject.ts
- packages/pages-shared/metadata-generator/types.ts
- packages/wrangler/src/miniflare-cli/assets.ts
Relates to #4265.
createMetadataObject previously only received a single logging function set to warn. This PR updates it to receive a full Logger object, and updates it to use the various levels correctly.
Previously messages such as `[WARNING] Parsed 2 valid header rules.` were output to the console, whereas with this fix they're no longer warnings, and therefore can be muted with `--log-level=info`.
Additionally, `wrangler/src/miniflare-cli/assets.ts` was defining its own Logger interface but is now loading the interface from the `logger.ts` file.
- Tests
**Note for PR …
> [wranger] fix: createMetadataObject to use logging levels (#4265)

- .github/ISSUE_TEMPLATE/bug-template.yaml
Fixes N/A.
**What this PR solves / how to test:** Adds more detail to the issue template.
- Tests
> Update issue template with more requested detail

- .changeset/eleven-carrots-happen.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
Previously when running `secret:bulk` with a `secret.json` containing a variable with an empty string as value the bulk operation would fail. This was due to the check for a falsy value when merging instead of comparing to `undefined` to make sure all specified values are excluded. The old other check would keep both the current value and the new value in the merged list which would then be rejected by the settings API as it doesn't allow the same key to be present multiple times.
- Tests
We want to celebrate and highlight awesome PR review! If you think …
> [wrangler] Allow empty strings in secret:bulk

- .changeset/happy-pandas-sparkle.md
- fixtures/get-bindings-proxy/package.json
- fixtures/get-bindings-proxy/tests/get-bindings-proxy.test.ts
- packages/wrangler/src/api/integrations/bindings/caches.ts
- packages/wrangler/src/api/integrations/bindings/index.ts
- pnpm-lock.yaml
Usage example: https://github.com/dario-piotrowicz/getBindingsProxy-poc-demo/blob/main/demo/index.ts
> expose no-op `caches` in `getBindingsProxy`

- .github/ISSUE_TEMPLATE/bug-template.yaml
Fixes N/A.
**What this PR solves / how to test:** Fixes previous update to the issue template (https://github.com/cloudflare/workers-sdk/pull/4865) to include the content of the "Describe the bug" field as pre-filled value rather than a placeholder.
- Tests
> Update issue template bug description field

- .github/workflows/worker-deploy-edge-preview-authenticated-proxy.yml
- .github/workflows/worker-format-errors-deploy.yml
- .github/workflows/worker-playground-preview-deploy-production.yml
- .github/workflows/worker-playground-preview-deploy-testing.yml
- packages/edge-preview-authenticated-proxy/package.json
- packages/format-errors/package.json
- packages/playground-preview-worker/package.json
- packages/playground-preview-worker/tests/index.test.ts
Previously every push to `main` that contained changes to a Worker package would cause that Worker to be deploy "to production". This meant that we had to be very careful about merging PRs that touch these Workers files.
Now production deployment is only run for a Worker on a push to its special deployment branch (e.g. `deploy-worker/playground-preview-worker`). This allows us to land PRs to `main` and then collect up changes to release in a single go by updating the special deployment branch in a controlled way. Moreover it is also easy to see what changes will be released by looking at the difference between `main` and the deployment branch for the Worker package directory.
The three workers in this repo now follow this pattern:
- edge-preview-authenticated-proxy
- format-errors
- …
> ci: only deploy Workers when pushing to special branches

- .changeset/odd-kids-notice.md
- packages/wrangler/src/api/integrations/bindings/index.ts
Fixes #4793.
This PR adds support for AI bindings to `getBindingsProxy`. 
A proxy object was already getting added to the miniflare binding options, but as a [service binding](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/dev/miniflare.ts#L352). `getBindingsProxy` was then clobbering that definition with its own service binding definitions. 
- Tests …
> [wrangler] Support ai bindings in getBindingsProxy

- .changeset/twelve-coins-hear.md
- packages/wrangler/src/deploy/index.ts
That way we do not need authentication for dryrun, again.
Fixes #4723
Install wrangler, don't login (or logout) run a dryRun deploy, see that you are asked to login. Install PR, see that you are no longer required to login when doing a dryRun deploy.
- Tests
> Exclude standardPricingWarning from dryrun

- .changeset/smart-owls-jog.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/proxy.ts
- packages/wrangler/src/user/user.ts
The `wrangler dev` port availability check triggers a firewall prompt on macOS while it briefly opens and closes listeners. The OAuth callback server from `wrangler login` has the same issue.
Fix both cases by listening on the loopback address only by default.
Fixed some new test failures by using locally available IP addresses:
wrangler:test:   ● wrangler dev › ip › should use to `ip` from `wrangler.toml`, if available
wrangler:test:     listen EADDRNOTAVAIL: address not available 1.2.3.4:8787
wrangler:test:
wrangler:test:   ● wrangler dev › ip › should use --ip command line arg, if provided
wrangler:test:     listen EADDRNOTAVAIL: address not available 5.6.7.8:8787
Relates to #4430
___
Note: the test suite still has many problems with listening on the wildcard address, for example …
> [wrangler] fix: listen on loopback for wrangler dev port check and login

- templates/stream/webrtc/package.json
- templates/stream/webrtc/src/index.html
- The example we have to kick off WebRTC testing isn't super clear, pull those variables up and label them.
- Starting it up on StackBlitz doesn't work without specifying a port number.
- How to test --- compare these two:
- https://stackblitz.com/fork/github/cloudflare/workers-sdk/tree/main/templates/stream/webrtc?file=src%2Findex.html
- https://stackblitz.com/fork/github/tsmith512/workers-sdk/tree/tsmith/stream-fixes/templates/stream/webrtc?file=src%2Findex.html
- (DM `tsmith` internally if you need a WebRTC live input to test)
- Checked for inclusion of …
> [Stream] WebRTC Template Improvements

- packages/create-cloudflare/e2e-tests/helpers.ts
This is a precursor to updating to latest Vitest.
- Tests
> chore: rename deprecated Vitest `TestContext.meta` properties to `TestContext.task`

- packages/playground-preview-worker/src/middleware/definitions/json.module.template
This PR ensures that if the `format-errors` worker is unavailable or returns a non 200 response, we just return the stack trace unformatted. Note `format-errors` returns a 200 response even though we're technically returning an error page:
https://github.com/cloudflare/workers-sdk/blob/3e7cd6e40816c5c6ab28163508a6ba9729c6de73/packages/format-errors/src/index.ts#L117-L119
This change means the user still sees their error, even if it doesn't look as pretty. We'll want to apply a similar change to the internal Quick Editor middleware.
- Tests
We want to …
> [playground-preview-worker] fix: fallback to returning stack trace if `format-errors` broken

- .changeset/soft-tigers-beg.md
- fixtures/get-bindings-proxy/tests/get-bindings-proxy.bindings.test.ts
- fixtures/get-bindings-proxy/tests/get-bindings-proxy.caches.test.ts
- fixtures/get-bindings-proxy/tests/get-bindings-proxy.ctx.test.ts
- fixtures/get-bindings-proxy/tests/shared.ts
- packages/wrangler/src/api/integrations/bindings/executionContext.ts
- packages/wrangler/src/api/integrations/bindings/index.ts
> Add a `ctx` field to the `getBindingsProxy` result

- packages/format-errors/src/index.ts
Previously, invalid input to the `format-errors` worker was reported as an internal server error. As with #4904, this is a user error that the service can't do anything about. This PR 
- Tests
> fix: don't report invalid `format-errors` input

- .changeset/fair-shoes-melt.md
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/dev/remote.tsx
Fixes #4590.
**What this PR solves / how to test:** Adds a user friendly error message mapping for code 10021, specifically when the database id mapping is invalid.
**Author has addressed the following:** I have also moved out some repeated error mappings in the `remote.ts` file to a shared function.
- Tests
> [D1] Add user friendly D1 validation error messages for `dev --remote` and `deploy`

- .changeset/red-icons-flow.md
- packages/wrangler/src/__tests__/d1/d1.test.ts
- packages/wrangler/src/d1/index.ts
- packages/wrangler/src/d1/info.tsx
- packages/wrangler/src/d1/insights.ts
- packages/wrangler/src/d1/types.ts
> [D1] teach wrangler how to fetch insights about D1's queries

- packages/playground-preview-worker/.eslintrc.js
- packages/playground-preview-worker/package.json
- packages/playground-preview-worker/src/errors.ts
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/src/realish.ts
- packages/playground-preview-worker/src/sentry.ts
- packages/playground-preview-worker/src/user.do.ts
- packages/playground-preview-worker/tests/index.test.ts
- pnpm-lock.yaml
Similar to #4904, the PR validates returns 4xx errors for invalid user input, as opposed to 500's reported to Sentry. In particular, this should prevent the `Parsing a Body as FormData requires a Content-Type header.` errors we've been seeing. There's nothing we can do about these errors as they're caused by the client. This PR also bumps the `hono` version to address the `Cannot read properties of undefined (reading 'split')` errors.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber …
> [playground-preview-worker] fix: don't report invalid upload input

- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
Similar to #4904 and #4937, this PR validates and returns 4xx errors for invalid user input, as opposed to 500's reported to Sentry. I _think_ these URLs are the only user controllable parameters that could result in uncaught errors in this worker. Things like invalid worker syntax/config are handled downstream.
- Tests
> [edge-preview-authenticated-proxy] fix: don't report invalid user-specifiable URLs

- .changeset/orange-jobs-exist.md
- packages/wrangler/src/d1/create.tsx
- packages/wrangler/src/d1/delete.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/info.tsx
- packages/wrangler/src/d1/list.tsx
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/migrations/create.tsx
- packages/wrangler/src/d1/migrations/list.tsx
> [D1] print wrangler banner at the start of every D1 command

- .changeset/breezy-worms-pull.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation.ts
Run `wrangler types` against a `wrangler.toml` file not including a `main` field.
- Tests
> make the entrypoint optional for the `types` command

- .changeset/strong-otters-hope.md
- fixtures/get-bindings-proxy/tests/get-bindings-proxy.cf.test.ts
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/scripts/emit-types.ts
- packages/wrangler/src/api/integrations/bindings/index.ts
- packages/wrangler/tsconfig.json
- pnpm-lock.yaml
> add a `cf` field to the `getBindingsProxy` result

- .changeset/chatty-balloons-impress.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/navigator-user-agent.test.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/navigator-user-agent.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/versions/upload.ts
- pnpm-lock.yaml
Fixes  #4050
Previously, importing `node:*` modules would fail at build time if neither nodejs compat mode was enabled. This PR changes the build time error into a build time warning, which will support writing runtime-agnostic code that conditionally imports NodeJS APIs only in a NodeJS environment.
Additionally, it adds the `navigator.userAgent` constant to esbuild's bundle settings. This means that as long as users are feature detecting with `navigator.userAgent`, `esbuild` will tree-shake away the Node.JS code, and they won't see warnings.
- Tests
We …
> Improve DX with `node:*` modules

- .changeset/five-cooks-share.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/sippy.ts
Before Sippy hits beta, we'd like to change the shape of the request payloads. This updates Wrangler's API calls to Sippy's endpoints to use these new payloads.
- Tests
> improve(r2): Update Sippy endpoint request payloads to match new schema

- .changeset/quick-apricots-punch.md
- fixtures/local-mode-tests/tests/specified-port.test.ts
- packages/wrangler/src/dev/start-server.ts
Fixes #4813.
https://github.com/cloudflare/workers-sdk/pull/4497 introduced a proxy server in front of the user's worker. The proxy worker was configured to start up on the user-specified port (if any), with the user worker starting on a random port:
https://github.com/cloudflare/workers-sdk/blob/0699506d9cab929779d19ec2af9b53ccb70c0e7b/packages/wrangler/src/dev/dev.tsx#L438-L439
Unfortunately, this change wasn't copied over to the "test mode" `unstable_dev()` implementation, meaning `unstable_dev()` tried to start the user worker on the same port as the proxy worker if a non-zero `port` was specified. This PR brings that change over.
To test this, run the `local-mode-tests`, a new `specified-port.test.ts` file has been added. 🙂 
**Author has …
> [wrangler] fix: allow `port` option to be specified with `unstable_dev()`

- .changeset/few-houses-wait.md
- fixtures/dev-env/tests/index.test.ts
- packages/wrangler/src/api/startDevWorker/utils.ts
- packages/wrangler/templates/startDevWorker/ProxyWorker.ts
(Potentially) fixes #4562 
Before, the ProxyWorker had no resolution for errors that occur while requests are proxied and just logged the error to the terminal. This was because we expected inflight requests to be completed before workerd shuts down and therefore requests would only fail for unexpected reasons with no recovery strategy. But it seems, from reported issues, that requests are failing while the UserWorker is reloaded (workerd shuts down and a new workerd starts).
Now, given requests are known to fail during reloads, requests are now requeued (to retry) if they are GET or HEAD requests (because these are the subset of idempotent requests which have no body and _can safely_ be retried).
I managed to simulate the scenario with a worker …
> Extend error handling of proxy request errors in ProxyWorker

- .changeset/cyan-kiwis-return.md
- packages/wrangler/src/__tests__/d1/splitter.test.ts
- packages/wrangler/src/d1/splitter.ts
- packages/wrangler/test.sql
Fixes #4326.
**What this PR solves / how to test:** Before, executing this query:
```sql
CREATE TRIGGER test_after_insert_trigger AFTER
INSERT ON test BEGIN
SELECT CASE
WHEN NOT EXISTS
(SELECT 1
FROM pragma_table_list(new."table")) THEN RAISE (
ABORT,
'Exception, table does not exist')
END ; END ;
```
Would falsely result in two statements, because `CASE` was not considered to be a compound statement. According to https://www.sqlite.org/lang_expr.html, it is, so I've just added it to the RegExp check for compound statement starts and that will solve it.
Before:
```
🌀 Mapping SQL input into an array of statements
🌀 Parsing 2 statements
🌀 Executing on remote database test (f9287979-a9b2-45b9-91a8-b948451a7330):
🌀 To execute on your local development database, pass the --local flag to …
```
> [D1] fix batch splitting to handle CASE as compound statement starts

- .changeset/cuddly-apples-divide.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/__tests__/navigator-user-agent.test.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
- packages/wrangler/src/navigator-user-agent.ts
Fixes #4959.
#4499 introduced a bug which prevented reloads when importing `node:*` modules. The internal per-build `seen` cache was not cleared between builds, resulting in this branch being hit...
https://github.com/cloudflare/workers-sdk/blob/1c4f1635165d98abc0558dcf148fe1d3ce9a2ca1/packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts#L28-L30
...and the resolution failing. This change wraps that in an `onStart()`, so it's called at the start of each build, and also moves the caches inside the plugin, so multiple instances of the plugin can be created.
To test this, follow the reproduction instructions in #4959, no errors should be reported.
- Tests …
> fix: ensure worker reloads when importing `node:*` modules

- .github/workflows/c3-e2e-project-cleanup.yml
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/scripts/common.ts
- packages/create-cloudflare/scripts/e2eCleanup.ts
- packages/wrangler/e2e/c3-integration.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/pages-dev.test.ts
In a number of places, we run e2e tests against Cloudflare APIs that result in Workers and/or Pages projects being created. This included:
- C3 E2E tests
- Wrangler E2E tests
- Internal E2E tests
These tests all include cleanup as part of their logic (in an `afterEach` or similar), but sometimes fail to properly clean up the created projects (whether through tests crashing, CI timeouts, or random chance). Because of that, we have a CI job which cleans up created e2e projects after some period of time. Previously, it only cleanup up projects created by the C3 E2E tests—this PR ensures that the cleanup action cleans up projects created from the Wrangler, C3, or internal E2E tests. It also updates the Wrangler tests to include a clearer well-known …
> Update prefixes for e2e tests to cleanup all e2e workers

- .changeset/red-frogs-glow.md
- packages/wrangler/src/__tests__/custom-build.test.ts
- packages/wrangler/src/deployment-bundle/run-custom-build.ts
Ensure custom build failures are marked as `UserError`s, and don't offer to report them to Sentry.
- Tests
> Ensure custom build failures are marked as user errors

- .changeset/orange-avocados-fail.md
- packages/wrangler/src/dev/use-esbuild.ts
In PRs we're getting this eslint warning:
(I think this was introduced in #4499)
This PR adds the missing `defineNavigatorUserAgent` dependency removing the warning
> chore: add missing `defineNavigatorUserAgent` dependency to useEsbuild hook

- fixtures/additional-modules/test/index.test.ts
- fixtures/interactive-dev-tests/vitest.config.ts
- fixtures/local-mode-tests/tests/module.test.ts
- fixtures/local-mode-tests/tests/sw.test.ts
- package.json
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/pages-shared/__tests__/asset-server/responses.test.ts
- packages/workers.new/tests/__snapshots__/index.test.ts.snap
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/package.json
- pnpm-lock.yaml
- vitest.shared.ts
Closes #4798 
In attempting to update Vitest in a dependabot PR, we noticed that there were a mix of versions of Vitest and that there would be some tricky parts to bumping the version. Moreover updating to the latest Vitest requires updating Vite as a transitive dependency, and we have a direct dependency on this too.
This work here brings everything to the latest versions and aligns it across the repository.
The update to Vitest had some breaking changes to a number of tests and configuration files have been fixed accordingly.
- Tests
> chore: bump vite and vitest to latest versions

- .changeset/slimy-apples-reply.md
- .changeset/spotty-suns-learn.md
- packages/create-cloudflare/e2e-tests/fixtures/nuxt/server/routes/test.ts
- packages/create-cloudflare/e2e-tests/fixtures/nuxt/wrangler.toml
- packages/create-cloudflare/e2e-tests/fixtures/qwik/src/routes/test/index.ts
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/src/workers.ts
- packages/create-cloudflare/templates/nuxt/c3.ts
- packages/create-cloudflare/templates/nuxt/templates/wrangler.toml
- packages/create-cloudflare/templates/qwik/c3.ts
- packages/create-cloudflare/templates/qwik/templates/wrangler.toml
Updates the nuxt template to use the `nitro-cloudflare-dev` nitro module (which leverages `getBindingsProxy`) to enable users to run the native nuxt dev command instead of using `wrangler paves dev` on build output.
Also adds empty `wrangler.toml` files to the nuxt template, as well as the qwik template which was recently changed in a similar way: https://github.com/cloudflare/workers-sdk/pull/4927/files
- Tests
- [ x ] Issue(s)/PR(s): https://github.com/cloudflare/cloudflare-docs/pull/12953
We want to celebrate and …
> C3: Nuxt template dev improvements

- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/tests/index.test.ts
- packages/workers-playground/.env.development
- packages/workers-playground/README.md
- packages/workers-playground/src/QuickEditor/HTTPTab/HTTPTab.tsx
- packages/workers-playground/src/QuickEditor/ToolsPane.tsx
- packages/workers-playground/vite.config.ts
Partially fixes [DEVX-1156](https://jira.cfdata.org/browse/DEVX-1156). There will be a followup PR to address the same issue in `edge-preview-authenticated-proxy`
This PR ensures that the Workers Playground uses partitioned cookies for it's preview system, to address the [upcoming deprecation of third party cookies in Chrome](https://developers.google.com/privacy-sandbox/3pcd/chips).
This PR can be tested by following the steps in `packages/workers-playground/README.md` to build a local copy of the playground, and then running it in a version of chrome with the cookie phaseout flag enabled (`chrome://flags#test-third-party-cookie-phaseout`)
- Tests …
> Use partitioned cookies

- .changeset/gentle-mayflies-shout.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/core/modules.ts
- packages/miniflare/test/plugins/core/modules.spec.ts
- packages/miniflare/test/test-shared/storage.ts
Fixes #4721.
Previously, Miniflare would resolve relative `scriptPath`s against `moduleRoot` multiple times resulting in incorrect paths and module names. This would lead to `can't use ".." to break out of starting directory` `workerd` errors. This change ensures Miniflare uses `scriptPath` as is, and only resolves it relative to `modulesRoot` when computing module names. Note this bug didn't affect service workers. This allows you to reference a modules `scriptPath` outside the working directory with something like:
```js
const mf = new Miniflare({
modules: true,
modulesRoot: "..",
scriptPath: "../worker.mjs",
});
```
Notably, this wasn't a problem if `modulesRoot` and `scriptPath` were absolute paths.
- Tests …
> [miniflare] fix: allow relative modules `scriptPath` outside of CWD

- .changeset/warm-weeks-stare.md
- packages/create-cloudflare/templates/qwik/c3.ts
This PR updates the C3 Qwik template to use the `getPlatformProxy` utility instead of the deprecated `getBindingsProxy` one
- Tests
> [C3] chore: update qwik template to use `getPlatformProxy`

- packages/wrangler/e2e/helpers/normalize.ts
- packages/wrangler/src/dev.tsx
* test: ensure that standard pricing warning is removed from normalized output in e2e tests
This normalization relied upon the ACCOUNT ID being a specific value, which is not always valid.
* fix: ensure that Hyperdrive in local dev can use the localConnectionString
Previously if there was no appropriate env var, then Wrangler would exit with an error.
This is checked by the Wrangler e2e tests, which were failing previously - so no need to add additional tests.
Broken in: https://github.com/cloudflare/workers-sdk/pull/4900
- Tests
> fix e2e test failures

- .changeset/cuddly-icons-itch.md
- .changeset/rich-needles-dress.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.caches.test.ts
- packages/wrangler/src/api/integrations/platform/caches.ts
This PR does two things:
- Updates the `caches` object returned from `getPlatformProxy` so that they are more aligned to the actual workerd versions
- Updates the request/response types used by the cache objects to be `any`s, this is to solve a shortcoming we recently noticed in which we saw that by using `unknown`s we make the `CacheStorage` type from `getPlatformProxy` incompatible with the type of the same name from `@cloudflare/workers-types` (forcing users to use ugly castings in order to make this more usable)
- Tests
- the added methods are not to be documented (since …
> Improve `getPlatformProxy`'s (no-op) caches

- package.json
- packages/kv-asset-handler/turbo.json
The `@cloudflare/kv-asset-handler` package was missing a `turbo.json`. This file is required to ensure Turborepo caches the correct stuff, and correctly invalidates caches when needed. We have a linting script to prevent missing `turbo.json` files, but it looks like it wasn't running. I think this is because our `Checks` job runs `pnpm run check`, which calls `turbo check:lint`, but this then doesn't run the root `check:lint` script. I've moved this lint to the `check` script. 👍 
- Tests
We want to celebrate and highlight awesome PR review! If you think …
> chore: add `turbo.json` to `kv-asset-handler`

- .changeset/four-comics-battle.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/__tests__/r2.local.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/sentry.test.ts
- packages/wrangler/src/index.ts
Fixes #3867.
I tried to reproduce #3867 by updating my `.wrangler/config/default.toml` with an access token expiry in the past, and an invalid refresh token, but `wrangler whaomi` just opened a browser and prompted me to login. It's possible this specific issue was fixed in another PR. 🤔 Either way, given the recent work to split out `UserError`s, of which the `Not logged in.` error seen here is one, it seemed like a good idea to hide the bug reporting message in these cases.
- Tests
We want to celebrate and highlight awesome PR review! If you think this …
> [wrangler] fix: don't suggest reporting `UserError`s to GitHub

- packages/wrangler/e2e/r2.test.ts
Follow up to #5030, we missed a couple of snapshots in the E2E tests. 🙃 
- Tests
> fix: fixup E2E test snapshots now that user errors don't prompt GitHub

- packages/wrangler/src/__tests__/standard-pricing.test.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/versions/index.ts
Fixes WP-785
Adds a warning when deploying a Worker with an explicit usage model defined in your `wrangler.toml` as after March 1st all customers will only be able to configure usage model within the dashboard as part of the deprecation of bundled and unbound.
Testing can be done by building Wrangler, setting your system time to be after March 1st, and ensuring you see the warning when deploying a Worker.
- Tests
> Add warning for explicit usage model after bundled/unbound deprecation

- .changeset/khaki-wasps-glow.md
- packages/wrangler/src/dev/dev.tsx
Fixes part of #3907.
When running `wrangler dev --port=0`, Wrangler doesn't know the port the dev server started up on until the `onReady` callback is called. In `--remote` mode, this can take a while meaning there's a significant period of time where pressing <kbd>b</kbd> opens `localhost:0`. This change ensures we wait until the first `onReady` call before opening the browser with the correct port.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label …
> fix: wait for actual port before opening browser with `--port=0`

- .vscode/settings.json
- fixtures/worker-app/package.json
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/edge-preview-authenticated-proxy/package.json
- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/wrangler/templates/startDevWorker/ProxyWorker.ts
- pnpm-lock.yaml
Closes [DEVX-1156](https://jira.cfdata.org/browse/DEVX-1156). 
This PR ensures that the Workers Quick Edit uses partitioned cookies for it's preview system, to address the [upcoming deprecation of third party cookies in Chrome](https://developers.google.com/privacy-sandbox/3pcd/chips).
_Testing instructions TBD_
- Tests
> [quick-edit] Partitioned cookies

- .changeset/happy-tools-approve.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/module-collection.ts
Fixes #4741
preserveFileNames in createModuleCollector
- Tests
> Implemented preserve_file_names config

- .changeset/tame-needles-give.md
- .changeset/tasty-jokes-provide.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/helpers/account-id.ts
- packages/wrangler/e2e/helpers/wrangler-command.ts
- packages/wrangler/e2e/validate-environment.ts
- packages/wrangler/e2e/vitest.config.ts
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/zones.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/create-worker-preview.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/validate-dev-props.ts
- packages/wrangler/src/zones.ts
Fixes #3755
This ensures that switching to remote mode during a dev session (from local mode) will correctly use the right zone. Previously, zone detection happened _before_ the dev session was mounted, and so dev sessions started with local mode would have no zone inferred, and would have failed to start, with an ugly error.
Additionally, it ensures that preview sessions created without a zone don't switch the host on which to start the preview from the one returned by the API.
It also improves messaging across the board for preview errors.
- Tests
We …
> Better messaging in remote mode

- packages/miniflare/src/plugins/index.ts
- packages/miniflare/src/plugins/ratelimit/index.ts
- packages/miniflare/src/workers/ratelimit/ratelimit.worker.ts
- packages/miniflare/test/plugins/ratelimit/index.spec.ts
Fixes # WAFFLE-538.
Add emulated Ratelimit bindings to Miniflare to allow internal development.
- Tests
> WAFFLE-538 Add Miniflare support/tests for Ratelimits emulation

- .changeset/fluffy-yaks-matter.md
- fixtures/local-mode-tests/src/nodejs-compat.ts
- fixtures/local-mode-tests/tests/logging.test.ts
- fixtures/local-mode-tests/wrangler.logging.toml
- packages/wrangler/src/api/dev.ts
Fixes #3362.
When running `unstable_dev()` in its default "test mode", the logging level was set to `none`. This meant any Worker startup errors or helpful warnings wouldn't be shown. This change switches the default to `warn`. For example, this means if you fail to include `nodejs_compat` and try to import `node:buffer`, you'll now see the following output, as opposed to an unclear failure:
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight …
> [wrangler] fix: switch default logging level of `unstable_dev()` to `warn`

- .changeset/silent-geese-leave.md
- .changeset/tender-nails-tickle.md
- packages/miniflare/src/http/server.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/proxy/client.ts
- packages/miniflare/src/plugins/shared/constants.ts
- packages/miniflare/src/runtime/index.ts
- packages/miniflare/test/index.spec.ts
Fixes #4993.
Previously, if Miniflare was configured to start on a `host` that wasn't `127.0.0.1`, `::1`, `*`, `::`, or `0.0.0.0`, calls to `Miniflare` API methods relying on the magic proxy (e.g. `getKVNamespace()`, `getWorker()`, etc.) would fail. This change ensures `workerd` is always accessible to Miniflare's internals, by configuring `workerd` with an additional local-only entry socket in this case. An unrelated issue meant if Miniflare was configured to start on an IPv6 `host`, it could crash. This change also ensures IPv6 addresses are handled correctly.
This means `wrangler dev` can now use local network and IPv6 address such as `192.168.0.10` and `::1` with the `--ip` flag.
To test this, run `wrangler dev --ip ::1` in `fixtures/worker-app`. Use `ifconfig` to find your local …
> [miniflare] fix: ensure magic proxy works when starting on non-local `host`s, and IPv6 addresses can be used as `host`s

- .changeset/kind-ducks-pay.md
- packages/wrangler/src/deployment-bundle/source-url.ts
- packages/wrangler/src/dev/remote.tsx
This PR makes sure that the bundle type is set correctly in remote dev mode when the main module is a Python module. It also ensures that the source URL annotation is written in Python style when the entry point is a Python module. 
- Tests
> Add python support for remote dev

- .changeset/swift-peaches-battle.md
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
After some discussion, the runtime team has decided that we should prevent users from specifying version identifiers altogether within requirements.txt, rather than silently dropping them. This would prevent users from being deluded into thinking that they could specify versions of Python packages in Python workers, then being confused because their code mysteriously breaks. 
Fixes EW-8189.
- Tests
We want to celebrate and highlight awesome PR review! If you think this PR received a particularly high-caliber review, please assign it the label `highlight pr review` so future reviewers can take …
> More strict handling of requirement specifiers in requirements.txt.

- .changeset/yellow-phones-buy.md
- packages/wrangler/src/ai/fetcher.ts
Fixes Workers AI local mode fetcher not returning headers to client worker
- Tests
> Fix Workers AI local mode fetcher not returning headers to client worker

- packages/create-cloudflare/e2e-tests/frameworks.test.ts
The hono C3 e2e tests are currently broken (see [c3 hono e2es failing](https://github.com/cloudflare/workers-sdk/actions/runs/8138824477/job/22240512311?pr=5140)), this PR fixes this
> [!NOTE]
> The dependabot PR that bumped `create-hono` from 0.4.0 to 0.5.0 should have caught this
> but it didn't if you look at the run logs ([here](https://github.com/cloudflare/workers-sdk/actions/runs/8047695795?pr=5097)) you can see that the e2es were run using `create-hono@0.4.0` instead of `create-hono@0.5.0`
>  ![Screenshot 2024-03-04 at 12 40 00](https://github.com/cloudflare/workers-sdk/assets/61631103/8f044d96-59de-483b-bdff-52900e2a3c90)
>
> we need to investigate why that happened!
- Tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#cha …
> C3 - fix hono e2e tests

- templates/experimental/worker-rust/.gitignore
- templates/experimental/worker-rust/Cargo.toml
- templates/experimental/worker-rust/wrangler.toml
Mostly added a minimum gitignore, and updated various versions. Can confirm it runs fine on my local.
Generate a new project and run `npx wrangler dev`
- Tests
> Update Rust example

- .changeset/hungry-cooks-brake.md
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/upload.ts
> pass legacy-env through versions upload

- .changeset/weak-tools-judge.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation.ts
Currently if a config file doesn't define any binding nor module, running
`wrangler types` against such file would not produce a `d.ts` file.
Producing a `d.ts` file can however still be beneficial as it would define a correct
env interface (even if empty) that can be expanded/referenced by user code (this can
be particularly convenient for scaffolding tools that may want to always generate an
env interface).
Example:
Before `wrangler types --env-interface MyEnv` run with an empty `wrangler.toml` file
would not generate any file, after these change it would instead generate a file with
the following content:
```
interface MyEnv {
}
```
- Tests …
> fix: make `wrangler types` always generate a `d.ts` file for module worders

- packages/create-cloudflare/.env.example
Just a simple `.env.example` file to help developers with local debugging
- Tests
> add new .env.example to packages/create-cloudflare project

- .changeset/stale-needles-unite.md
- packages/create-cloudflare/src/__tests__/templates.test.ts
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/helpers/files.ts
- packages/create-cloudflare/src/templates.ts
- packages/wrangler/templates/gitignore
previously only the worker templates included in their `.gitignore` the wrangler files
(those being `.dev.vars` and `.wrangler`), make sure to instead include such files in
the `.gitignore` files of all the templates including the full stack ones
- Tests
> [C3] fix: make sure that all C3 projects include in their `.gitignore` the wrangler files

- .github/pull_request_template.md
To make it clear that the developer has opted for TODO we don't now autocheck these boxes.
- Tests
> chore: remove checks from PR template TODOS

- packages/create-cloudflare/src/__tests__/templates.test.ts
Tests are failing because they shared state between tests.
- Tests
> test: ensure that mocks are setup in isolation on each test

- package.json
Some of the `get-{bindings,platform}-proxy` tests have been flaking in CI recently. I think this is because they're trying to connect to the dev registry, but the dev registry was started by an earlier test that just finished. This leads to socket errors like `other side closed`. The proper solution to this problem is to start a dev registry for each test (file). We could do this by assigning a different dev registry port for each test (file/project). In the meantime, this change disables parallelism for the fixture tests, ensuring if a dev registry is started, it is definitely shut down before another test begins.
- Tests
> ci: disable file parallelism for fixture tests

- CONTRIBUTING.md
Fixes N/A.
This PR adds a section to the contributing guide on what you should do before getting started. 
- Tests
> Add "before getting started" section to contributing guide

- packages/create-cloudflare/src/__tests__/common.test.ts
- packages/create-cloudflare/src/__tests__/templates.test.ts
- packages/create-cloudflare/src/__tests__/workers.test.ts
Removes noisy logs from create-cloudflare tests such as these: https://github.com/cloudflare/workers-sdk/actions/runs/8164300583/job/22332302711?pr=5173#step:8:33
- Tests
> remove create-cloudflare noisy test logs (by mocking `spinner`)

- .changeset/tall-wombats-reply.md
- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/tests/index.test.ts
Fixes #5073
This ensures that multiple `Set-Cookie` headers in the raw HTTP tab within the Playground and Quick Edit are shown. 
- Tests
> Handle multiple set cookie headers

- .github/workflows/c3-e2e-dependabot.yml
- .github/workflows/c3-e2e.yml
Currently our dependabot workflow is flawed and uses outdated version of framework
CLIs as you can see from this PR's description: https://github.com/cloudflare/workers-sdk/pull/5149
This is due to the wrong checkout performed in the `e2e-only-dependabot-bumped-framework` step which uses the version of the package.json file from `main` instead of getting the updated one.
This PR fixes such behavior.
- Tests
> [C3] chore: fix dependabot so that it used the correct package version

- .changeset/tall-planets-pull.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/helpers.ts
- packages/wrangler/src/kv/index.ts
Fixes #
**What this PR solves / how to test:**  Currently the kv:namespace create command differs from other `create` commands where it prefixes the input with `worker-` when using the command in e.g. a pages project without a `wrangler.toml` or with a `wrangler.toml` but without a `name` property. This is a regression to how the dashboard and other products works and can cause confusion for developers.
**Author has addressed the following:** This has been broken into two separate PRs to focus on two different topics, see #5050 for the original change.
- Tests
> [KV] Remove `worker-` prefix from kv:namespace create when using wrangler in a pages project or without a `name` property

- .github/workflows/changesets.yml
- packages/workers.new/package.json
The workers.new Worker is not deployed to the same account as the other Workers in this monorepo.
Therefore it needs its own account id and api token.
These have been added to Github as secrets:
- WORKERS_NEW_CLOUDFLARE_ACCOUNT_ID
- WORKERS_NEW_CLOUDFLARE_API_TOKEN
This PR changes the deploy script of workers.new to use these secrets in the `wrangler deploy` command.
- Tests
> ci: ensure that workers.new is deployed to the correct account

- .changeset/friendly-jobs-serve.md
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/src/helpers/command.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/angular/c3.ts
- packages/create-cloudflare/templates/astro/c3.ts
- packages/create-cloudflare/templates/docusaurus/c3.ts
- packages/create-cloudflare/templates/gatsby/c3.ts
- packages/create-cloudflare/templates/next/c3.ts
- packages/create-cloudflare/templates/nuxt/c3.ts
- packages/create-cloudflare/templates/qwik/c3.ts
- packages/create-cloudflare/templates/react/c3.ts
- packages/create-cloudflare/templates/remix/c3.ts
- packages/create-cloudflare/templates/solid/c3.ts
- packages/create-cloudflare/templates/vue/c3.ts
This updates the remaining `webFramework` templates to use `dev` and `deploy` instead of `pages:dev` and `pages:deploy` in their package scripts.
It also moves the `testFlags` config option for frameworks from their template definitions into the frameworks e2e test config.
- Tests
- [ x ] Not necessary because: Existing coverage sufficient
- [ x ] Not necessary because:
> C3: Update remaining dev and deployment scripts

- .changeset/purple-lemons-yell.md
- packages/miniflare/src/http/fetch.ts
- packages/miniflare/src/http/server.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/shared/constants.ts
- packages/miniflare/src/workers/core/constants.ts
- packages/miniflare/test/index.spec.ts
Fixes #5018.
Previously, if your Worker returned a redirect response, calling `dispatchFetch(url)` would send another request to the original `url` rather than the redirect. This happened because...
1. We always used `this.#runtimeDispatcher` for `fetch()`ing, which only sends request to the runtime. This meant if a Worker returned a redirect to a different origin, that origin would be ignored and the request would still go to the runtime.
2. The `MF-Original-URL` header was not cleared/modified during redirects. This meant if a Worker returned a relative/absolute redirect to the same runtime origin, the path would not be updated in the `request` received by the user.
This change ensures redirects are followed correctly.
- If your Worker returns a relative redirect or an absolute redirect …
> [miniflare] fix: ensure redirects handled correctly with `dispatchFetch()`

- templates/experimental/worker-rust/Cargo.toml
- templates/experimental/worker-rust/package.json
- templates/experimental/worker-rust/wrangler.toml
Add a `dev`-environment to `wrangler.toml` which builds with `worker-build --dev` instead of `worker-build --release`.
This makes build times for local development much faster.
Add `opt-level = "s"` to `Cargo.toml` so release builds are optimized for size.
Remove the deprecated `--local` parameter from the `wrangler` invocation.
Not sure which of these I should do (and how).
- Tests
> perf(worker-rust): Add `dev` env for faster local build times

- .changeset/clean-nails-talk.md
- packages/miniflare/src/index.ts
The `ReadableStream` constructor was being called with an invalid, numerical second argument. Node 21.7.0 now runs stricter checks on that parameter, which was causing construction to fail.
We eliminate the second argument.
Fixes  #5190 
- Tests
> miniflare: fix node 21.7.0 compatibility

- .changeset/hungry-cougars-tie.md
- .changeset/sour-mugs-rule.md
- packages/wrangler/src/__tests__/d1/execute.test.ts
- packages/wrangler/src/__tests__/d1/migrate.test.ts
- packages/wrangler/src/__tests__/d1/utils.test.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/migrations/apply.tsx
- packages/wrangler/src/d1/migrations/create.tsx
- packages/wrangler/src/d1/migrations/helpers.ts
- packages/wrangler/src/d1/migrations/list.tsx
- packages/wrangler/src/d1/migrations/options.ts
This PR defaults both `wrangler d1 execute` and `wrangler d1 migrations apply` to use the local development environment provided by wrangler to match the default behaviour in `wrangler dev`.
BREAKING CHANGE: `wrangler d1 execute` and `wrangler d1 migrations apply` now default `--local` to `true`. When running `wrangler d1 execute` or `wrangler d1 migrations apply` against a remote D1 database, you will need to provide the `--remote` flag.
---
`wrangler dev` used to default to remote preview Workers, and `wrangler d1 execute`/`wrangler d1 migrations apply` followed this practice. With wrangler v3, `wrangler dev` was updated without updating `wrangler d1 execute`/`wrangler d1 migrations apply`. This PR fixes this, and ensures `wrangler dev` and `wrangler d1 execute`/`wrangler d1 migrations …
> [D1] default `wrangler d1 execute` to local mode first.

- .changeset/thick-yaks-cry.md
- packages/wrangler/src/d1/migrations/helpers.ts
Previously, if you wanted to remove a migration (e.g. number 5 out of 10), you had to:
- Comment everything in the migration file and add `SELECT ...` just to have a query in it; or
- Delete it and lower the number of all preceding migrations.
Previously:
```cmd
// 0001_my-cool-migration.sql
// 0003_my-cool-migration.sql
wrangler d1 migrations create my-cool-database my-cool-migration // 0003_my-cool-migration.sql
```
After:
```cmd
// 0001_my-cool-migration.sql
// 0003_my-cool-migration.sql
wrangler d1 migrations create my-cool-database my-cool-migration // 0004_my-cool-migration.sql
```
This PR changes the logic of `getNextMigrationNumber` to actually get the _highest_ migration number plus one, rather than the first missing migration number plus one, which can be an existing migration …
> fix: d1 migrations create to use the highest migration number plus one

- fixtures/local-mode-tests/tests/logging.test.ts
This test is flaking in CI, but we're not sure why. This change adds some additional context to the assertion error, so we can debug the issue.
- Tests
> test: include additional context in startup error test

- fixtures/local-mode-tests/tests/logging.test.ts
Stabilises `local-mode-tests` by ensuring `unstable_dev` has enough time to write to the terminal
- Tests
> Add waiting time

- .changeset/popular-melons-explain.md
- packages/cli/index.ts
- packages/cli/interactive.ts
- packages/cli/streams.ts
- packages/wrangler/e2e/helpers/normalize.ts
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/helpers/msw/handlers/versions.ts
- packages/wrangler/src/__tests__/helpers/msw/index.ts
- packages/wrangler/src/__tests__/jest.setup.ts
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/metrics/send-event.ts
- packages/wrangler/src/versions/deploy.ts
This PR implements the `versions deploy` command as a sibling command to the, already merged, `versions upload` command. Both are still behind the `--experimental-gradual-rollouts` flag.
Note: in the commands below, it is assumed you have followed the install instructions of the prerelease build (from the bot comment in this PR). You can, instead, replace "wrangler" with the prerelease URL from the bot comment.
The most common usage will be without args where the prompts will walk you through selecting Versions and percentages for each and adding a deployment message. A sane default is provided for each percentage, evenly distributing the remaining percentage across the remaining versions.
```sh
$ npx wrangler versions deploy …
```
> Implement `versions deploy` command

- .changeset/spotty-vans-bow.md
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/__tests__/versions/versions.list.test.ts
- packages/wrangler/src/__tests__/versions/versions.view.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/metrics/send-event.ts
- packages/wrangler/src/utils/render-labelled-values.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/list.ts
- packages/wrangler/src/versions/view.ts
This PR implements the `versions list` and `versions view <version-id>` commands. They are very similar so a single PR seemed fine.
- Tests
> Implement `versions list` + `versions view` commands

- .changeset/strong-drinks-burn.md
- .gitguardian.yml
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/hyperdrive/client.ts
- packages/wrangler/src/hyperdrive/create.ts
- packages/wrangler/src/hyperdrive/update.ts
Fixes # SQC-200
This PR adds more options in the `hyperdrive create` and `hyperdrive update` subcommands for users to update all the caching settings of their Hyperdrive configs.
- Tests
> wrangler: Improve hyperdrive create and update to include all current caching settings

- packages/vitest-pool-workers/README.md
This PR adds the missing `README.md` to `vitest-pool-workers`. 👍 
- Tests
> docs: add `README` to `vitest-pool-workers`

- .changeset/sixty-ants-do.md
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/js/test/index.spec.js
- packages/create-cloudflare/templates/hello-world/js/vitest.config.js
- packages/create-cloudflare/templates/hello-world/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world/ts/package.json
- packages/create-cloudflare/templates/hello-world/ts/test/index.spec.ts
- packages/create-cloudflare/templates/hello-world/ts/test/tsconfig.json
- packages/create-cloudflare/templates/hello-world/ts/tsconfig.json
- packages/create-cloudflare/templates/hello-world/ts/vitest.config.ts
- packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
This commit sets the tsconfig  `moduleResolution` config key to `bundler` inside the create-cloudflare "Hello world" template to resolve the /config sub-export of @cloudflare/vitest-config-workers
- Tests
> [create-cloudflare] fix:  `tsconfig` settings for "Hello world" template

- .changeset/tender-kiwis-love.md
- packages/wrangler/src/__tests__/versions/versions.list.test.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/list.ts
- packages/wrangler/src/versions/upload.ts
This fixes annotations in versions upload to match where the api expects to find them
- Tests
> fix: move annotations under metadata in create-worker-upload-form

- .changeset/seven-spies-drive.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
Ability to deploy workers to dispatch namespaces (Workers for Platforms product).
Usage: `wrangler deploy --dispatch-namespace <namespace>`
This is an improvement to PR #2746 because:
- Correct terminology of 'dispatch namespace' used instead of 'platform namespace'.
- Excludes tasks related to routes. custom domains. cron/schedules, and queue consumers when `dispatch-namespace` option used (these features aren't supported in Workers for Platforms)
- Allows for any name to be used for the script when `dispatch-namespace` option used, because Workers for Platforms doesn't check script names
- Tests
> Feature: `dispatch-namespace` option in `wrangler deploy`

- .changeset/twelve-penguins-guess.md
- packages/wrangler/src/__tests__/version.test.ts
- packages/wrangler/src/index.ts
This PR deprecated the `wrangler version` command. It does the same thing as `wrangler --version` which can be used instead. Deprecating because it could cause confusion with the upcoming `wrangler versions ...` commands.
- Tests
> Deprecate `version` command

- .changeset/fair-queens-cheat.md
- .github/ISSUE_TEMPLATE/bug-template.yaml
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/src/pool/config.ts
This PR adds a link to the migration guide when `environment: "miniflare"` is specified in Vitest config, and adds some missing metadata to `package.json`.
- Tests
> [vitest-pool-workers] fix: add link to migration guide in environment error and add missing `package.json` metadata

- .changeset/empty-kids-agree.md
- .prettierignore
- fixtures/additional-modules/test/index.test.ts
- fixtures/worker-app/src/explicit-resource-management.js
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- package.json
- packages/cli/package.json
- packages/miniflare/package.json
- packages/miniflare/scripts/build.mjs
- packages/vitest-pool-workers/package.json
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/deployment-bundle/bundle-reporter.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/templates/symbol-dispose.js
- pnpm-lock.yaml
Fixes #3962. This PR bumps `esbuild` to version `0.18.20` across the monorepo. We can't go any further because of [these](https://github.com/evanw/esbuild/issues/3337) [issues](https://github.com/evanw/esbuild/issues/3317). We investigated what it would take to workaround/fix this. I'll open a separate ticket with our findings, and to track upgrading further. 👍 
- Tests
> feature: bump `esbuild` to `0.18.20`

- .changeset/hungry-ladybugs-smash.md
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- pnpm-lock.yaml
- templates/worker-aws/package.json
- templates/worker-aws/worktop.config.js
I accidentally closed the actual PR for this (https://github.com/cloudflare/workers-sdk/pull/3832)
So this is the same commits reopened.
> refactor: use `esbuild-plugins-node-modules-polyfill`

- .changeset/calm-buses-tan.md
- packages/wrangler/src/__tests__/config-validation-pages.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-pages.ts
- packages/wrangler/src/config/validation.ts
Wrangler proper has a mechanism in place through which it validates a `wrangler.toml` file for Workers projects. As part of adding `wrangler.toml` support for Pages, we need to put a similar mechanism in place, to validate a configuration file against Pages specific requirements.
This PR implements the Pages specific validation logic
- Tests
> feat(wrangler): Add config validation for Pages

- .changeset/poor-tools-impress.md
- fixtures/dev-env/tests/index.test.ts
- fixtures/vitest-pool-workers-examples/package.json
- fixtures/vitest-pool-workers-examples/queues/test/queue-consumer-integration-self.test.ts
- fixtures/vitest-pool-workers-examples/queues/test/queue-consumer-unit.test.ts
- packages/miniflare/package.json
- packages/miniflare/src/workers/queues/broker.worker.ts
- packages/miniflare/test/index.spec.ts
- packages/miniflare/test/plugins/d1/index.with-wrangler-shim.spec.ts
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/src/worker/events.ts
- pnpm-lock.yaml
This PR bumps the `workerd` version to `1.20240314.0`, and fixes some failing tests as a result of this bump. The changes are based off of https://github.com/cloudflare/workers-sdk/pull/5230.
The PR should address the following items:
In the process it also turned out a `workers-types` version bump was necessary in the `vitest-pool-workers` related work, which in turn required updating the code to support the Queue changes
- Tests
> [wrangler] chore: bump `workerd` to `1.20240314.0`

- .changeset/lazy-cherries-build.md
- packages/wrangler/src/__tests__/helpers/mock-web-socket.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/errors.ts
- packages/wrangler/src/tail/index.ts
Previously when the we tail WebSocket disconnected, e.g. because of an Internet failure,
the `wrangler tail` command would just hang and neither exit nor any longer receive tail messages.
Now the process exits with an exit code of 1, and outputs an error message.
The error message is formatted appropriately, if the tail format is set to `json`.
Fixes #3927
Automated tests have been added.
But you can test this manually by building Wrangler locally, tailing any Worker and then manually turning off the Internet connection. After 2 secs Wrangler should exit with a suitable error message.
- Tests
> fix: ensure tail exits when the WebSocket disconnects

- .changeset/hungry-teachers-poke.md
- packages/wrangler/src/__tests__/pages-build-env.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-pages.ts
- packages/wrangler/src/pages/build-env.ts
- packages/wrangler/src/pages/index.ts
This adds a hidden `wrangler pages functions build-env` command, which prints the environment variables for the current environment to the terminal. This is for use by internal tooling, and shouldn't be used directly by end users.
Fixes [DEVX-1179](https://jira.cfdata.org/browse/DEVX-1179)
- Tests
> Support `wrangler pages functions build-env`

- packages/create-cloudflare/src/helpers/__tests__/args.test.ts
This PR is removing some noise I've noticed has been introduced in the C3 unit tests recently: https://github.com/cloudflare/workers-sdk/actions/runs/8335183298/job/22810182117#step:8:49
- Tests
> Remove noise from C3 args tests (by mocking `console.error`)

- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/versions/upload.ts
This PR changes deployments to explicitly 'keep' (inherit from previous Version) secret_text and secret_key bindings. These were implicitly inherited bindings before but we want to explicitly inherit them now because we no longer implicitly inherit plain_text bindings in version uploads so we need to explicitly only inherit the secret bindings. This also opens the possibility of maybe eventually specifying secret bindings (without values, of course) in wrangler.toml in the future.
- Tests
> explicitly 'keep' secret_text and secret_key bindings

- .changeset/tender-buckets-confess.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/pages/dev.ts
Closes #5063 
For monorepos using tools like `turborepo` or `nx` it may be desirable to disable to interactive feature of the `wrangler dev` command.
The flag to disable this exists internally already in package.
This PR exposes this internal flag (that can be passed to `unstable_dev`) as a CLI arg, allowing the interactive session to be disabled.
I maintained consistency with the current variable naming.
- Tests
> feat: cli flag to disable interactive dev session

- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
All tests related to Pages commands should live under the Pages dedicated `src/__tests__/pages` folder. This PR moves a couple of "lost" Pages tests to that folder.
- Tests
> chore(wrangler): Move misplaced tests to dedicated Pages test folder

- .changeset/breezy-badgers-play.md
- packages/wrangler/src/versions/api.ts
This got lost in translation:
https://github.com/cloudflare/workers-sdk/pull/5224#discussion_r1531287879
Fixes `npx wrangler versions deploy --experimental-gradual-rollouts` being rejected by the API, as `triggered_by` can't be set by the client.
- Tests
> fix(wrangler): remove triggered_by annotation from createDeployment

- .changeset/grumpy-apples-draw.md
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/index.ts
Implement `--experimental-versions` flag
+ alias: `--x-versions` (shorthand for convenience)
+ alias: `--experimental-gradual-rollouts` (for backwards compat)
This change is heading in the direction of a more general approach of formalising experimental flags (and potentially allowing alternate enablement like env vars and/or wrangler.toml properties) and having a `--x-foo` shorthand for `--experimental-foo` flags, but this PR implements the convention just for `--experimental-versions` with the more general approach to come in a follow-up.
- Tests
> implement `--experimental-versions` flag + aliases

- .changeset/tidy-dodos-pull.md
- fixtures/pages-dev-proxy-with-script/tests/index.test.ts
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/pages/dev.ts
> Deprecate pages dev's proxy features

- .changeset/quiet-timers-stare.md
- packages/create-cloudflare/templates/next/README.md
- packages/create-cloudflare/templates/next/app/js/app/api/hello/route.js
- packages/create-cloudflare/templates/next/app/ts/app/api/hello/route.ts
- packages/create-cloudflare/templates/next/c3.ts
- packages/create-cloudflare/templates/next/pages/js/pages/api/hello.js
- packages/create-cloudflare/templates/next/pages/ts/pages/api/hello.ts
- packages/create-cloudflare/templates/next/wrangler.toml
the wrangler.toml file for Next.js has an extra `MY_KV` binding that is used for the scaffold example we provide to the user
this can be a bit inconvenient as this is the only toml among all the framework that has such extra binding, this requires us to take extra care of the toml when making modifications while all the other toml template files instead are all the same
fix this by alinging the toml file with that all the other frameworks and adding to it whatever is necessary for the scaffold KV example programmatically
- Tests
> [C3]: align wrangler.toml template file for Next.js with those of the other frameworks

- .github/dependabot.yml
Previously we limited the workerd updates to the miniflare package by setting the `directory` configuration. But it seems that this fails to update the package lockfile because that is higher up in the root of the repo.
Changing the `directory` back to `/` should cover the package lockfile, although it will also update all packages and fixtures that contain potential updates (notably for workers-types). But this is probably a good thing overall.
> chore: ensure that dependabot updates package-lock.json

- .changeset/rude-mice-study.md
- packages/wrangler/src/user/user.ts
This PR backports the fix (for `wrangler login` to work with Chrome v123) to wrangler v2. This patch has already been applied to wrangler v3 in #5324.
Fixes #5328
- Tests
> v2 backport: Ignore OPTIONS requests in Oauth server

- fixtures/vitest-pool-workers-examples/tsc-all.mjs
Should hopefully fix tests on `main`. `fixtures/vitest-pool-workers-examples/tsc-all.mjs` wasn't compatible with Windows, but checks run on Windows on `main`.
- Tests
> fix: ensure `tsc-all.mjs` can run on Windows

- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
Support for emitting notifications based around this type of action will be supported eventually, but not until throughput improvements to supporting infrastructure are completed.
- Tests
> Remove support for LifecycleDeletion action

- .changeset/new-kiwis-press.md
- packages/prerelease-registry/functions/utils/getArtifactForWorkflowRun.ts
Somehow the prerelease registry is sometimes returning empty 404 responses from the Workers Cache. This change fixes that by only returning cached responses with a 200 status code.
- Tests
> Only return successful cached responses

- .github/workflows/e2e.yml
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/__tests__/pages/dev.test.ts
This PR adds some sanity-check unit and e2e tests for `wrangler pages dev`.
- Tests
> chore(wrangler): Add `pages dev` tests

- .changeset/hungry-candles-knock.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/src/templates.ts
All other templates use kebab-case so this sticks out like a sore thumb. `--type webFramework` is still allowed for now, but shows a warning when used.
- Tests
> [C3] Rename 'webFramework' --type argument to 'web-framework'

- .changeset/green-jokes-decide.md
- .changeset/thin-penguins-drum.md
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/helpers/setup.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/dev/use-esbuild.ts
In `--no-bundle` mode watch the entire module root for changes, rather than just the entrypoint file. Additionally, watch the `requirements.txt` file for Python workers.
Fixes [EW-8223](https://jira.cfdata.org/browse/EW-8223)
- Tests
> [wrangler] Watch the entire module root + watch requirements.txt

- .changeset/funny-trees-cross.md
- packages/wrangler/src/__tests__/helpers/msw/handlers/versions.ts
- packages/wrangler/src/__tests__/helpers/msw/index.ts
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/utils/render-labelled-values.ts
- packages/wrangler/src/versions/api.ts
- packages/wrangler/src/versions/deploy.ts
CR: https://jira.cfdata.org/browse/CR-850334
Adds a PATCH call after a `wrangler versions deploy` to save settings which could not be included in `wrangler versions upload` but are specified in wrangler.toml and expected by users to be saved upon regular `wrangler deploy`.
- Tests
> update non-versioned script settings in `versions deploy`

- .changeset/big-hounds-breathe.md
- packages/cli/interactive.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/deployments/list.ts
- packages/wrangler/src/versions/deployments/status.ts
- packages/wrangler/src/versions/rollback/index.ts
- packages/wrangler/src/yargs-types.ts
CR: https://jira.cfdata.org/browse/CR-850334
This PR implements versioned rollbacks via `wrangler rollback [version-id] --experimental-versions`.
Please note, the `experimental-versions` flag is required to use the new behaviour and the original `wrangler rollback` command is unchanged if run without this flag. 
- Tests
> Versions rollback

- .changeset/tough-suns-punch.md
- packages/wrangler/src/__tests__/versions/deployments/deployments.view.test.ts
- packages/wrangler/src/versions/deployments/index.ts
- packages/wrangler/src/versions/deployments/view.ts
Adds a `view` command to the new `deployments` subcommands opted-in via the `--experimental-versions` flag which shows a deprecation message and points the user to either run `wrangler deployments status --experimental-versions` or `wrangler versions view <version-id> --experimental-versions` instead.
- Tests
> Catch erroneous use of `deployments view [deployment-id] --experimental-versions` command

- .changeset/rich-oranges-attack.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
LDW merge exemption under CR-849815
Fixes MQ-586.
- Tests
> Use queue name for event notification config

- .changeset/yellow-wolves-talk.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
LDW merge exemption under CR-850842.
Fixes MQ-597.
- Tests
> Improvements to R2 notification commands

- .changeset/twenty-laws-mix.md
- packages/miniflare/src/plugins/hyperdrive/index.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/hyperdrive/create.ts
- packages/wrangler/src/hyperdrive/update.ts
Fixes SQC-153
LDW CR-851053
- Tests
> wrangler: Try to URL decode hyperdrive connection string components before sending them to API

- .changeset/tame-timers-decide.md
- packages/wrangler/src/__tests__/d1/d1.test.ts
- packages/wrangler/src/d1/create.tsx
- packages/wrangler/src/d1/delete.ts
- packages/wrangler/src/d1/index.ts
- packages/wrangler/src/d1/info.tsx
- packages/wrangler/src/d1/insights.ts
- packages/wrangler/src/d1/list.tsx
- packages/wrangler/src/d1/options.ts
- packages/wrangler/src/d1/utils.ts
This PR removes the beta warning for D1.
LDW CR-851462
> [D1] remove d1BetaWarning and all usages

- .changeset/soft-bees-report.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployments.ts
- packages/wrangler/src/utils/deployment-id-version-id-change.ts
CR: https://jira.cfdata.org/browse/CR-850334
- Tests
> Log note of upcoming change of "Deployment ID" to "Version ID"

- .changeset/bright-planets-unite.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/hyperdrive/client.ts
- packages/wrangler/src/hyperdrive/create.ts
- packages/wrangler/src/hyperdrive/update.ts
Support for configuring hyperdrives for databases that are inside a customer's private network
LDW CR-851053
- Tests
-  [ ] TODO (before merge)
-  [x] Included
-  [ ] Not necessary because:
-  [ ] TODO (before merge)
-  [x] Included
-  [ ] Not necessary because:
-  [ ] TODO (before merge)
-  [x] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/pull/13654
-  [ ] Not necessary because: Does not change the Hyperdrive command or its options.
> Add private host option for private networks support in hyperdrive

- .changeset/angry-brooms-destroy.md
- packages/cli/index.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/deployments.ts
- packages/wrangler/src/versions/rollback/index.ts
- packages/wrangler/src/versions/upload.ts
This PR adds helpful logging to `--experimental-versions` commands.
The changes in packages/cli are a refactor and do not effect the output by default but now there are options to override the default formatting.
CR: https://jira.cfdata.org/browse/CR-850334
- Tests
> add helpful logging to --experimental-versions commands

- .changeset/large-rice-bow.md
- packages/create-cloudflare/templates/astro/c3.ts
- packages/create-cloudflare/templates/astro/snippets/runtimeDeclaration.ts
This PR updates c3 to handle the upcoming Astro v10 cloudflare adapter (https://github.com/withastro/adapters/pull/159)
To test the changes in this PR:
- create a new Astro app using C3 (opting in to typescript to also test the types update)
```
npx https://prerelease-registry.devprod.cloudflare.dev/workers-sdk/runs/8452603565/npm-package-create-cloudflare-5410 --no-auto-update
```
- update the `@astrojs/cloudflare` version to `astrojs/cloudflare@experimental--cf-10`:
```
npm i -D @astrojs/cloudflare@experimental--cf-10
```
- make sure that everything works as expected
> [!NOTE]
> The C3 e2es are currently supposed to fail as the v10 Astro Cloudflare adapter hasn't been released yet, this PR should be merged after the v10 release (and by that time the e2es should pass)
- Tests
- Changeset …
> C3: Adapt Astro c3 flow to their v10 Cloudflare adapter

- .changeset/wicked-balloons-compare.md
- packages/wrangler/src/__tests__/d1/d1.test.ts
- packages/wrangler/src/d1/export.ts
- packages/wrangler/src/d1/index.ts
LDW CR: CR-851796
Docs are on the way.
- Tests
> [D1] initial `wrangler d1 export`

- .changeset/quick-insects-perform.md
- fixtures/vitest-pool-workers-examples/package.json
- fixtures/vitest-pool-workers-examples/queues/test/queue-consumer-integration-self.test.ts
- fixtures/vitest-pool-workers-examples/queues/test/queue-consumer-unit.test.ts
- packages/miniflare/package.json
- packages/miniflare/src/workers/node.d.ts
- packages/miniflare/src/workers/queues/broker.worker.ts
- packages/miniflare/test/index.spec.ts
- packages/miniflare/test/plugins/queues/index.spec.ts
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/src/worker/events.ts
- pnpm-lock.yaml
This PR upgrades `workerd` to [`1.20240329.0`](https://github.com/cloudflare/workerd/releases/tag/v1.20240329.0). This version contains some breaking changes to the experimental `Fetcher#queue()` method. It also introduces an accidental bump in the minimum supported TypeScript version to TypeScript 5.2 for `@cloudflare/workers-types` due to `Symbol.dispose` use. I did consider compatibility with older versions when making those types changes, but I missed a couple uses. 🙁 
- Tests
> chore: bump `workerd` to `1.20240329.0`

- .changeset/hot-geese-deliver.md
- fixtures/ai-app/src/index.js
- fixtures/ai-app/tests/index.test.ts
- packages/wrangler/src/ai/fetcher.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/dev/miniflare.ts
Adds native binding for workers ai.
CR-852557
- Tests
> Add native run binding for Workers AI

- .changeset/small-bees-brush.md
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/pages/build-env.ts
- packages/wrangler/src/pages/build.ts
Handle non-Pages wrangler.toml files better. This PR ensures that `wrangler pages functions build-env` and `wrangler pages functions build` fail fast with the appropriate error message if a non-pages wrangler.toml file is found. This ensure that config validation isn't run, which was inadvertently throwing errors for non-pages wrangler.toml files.
- Tests
> Handle invalid wrangler.toml files

- CODEOWNERS
- packages/wrangler/src/__tests__/d1/export.test.ts
This PR adds tests for `wrangler d1 export`, and gives the D1 team codeownership of its own tests.
Closes [#5442](https://github.com/cloudflare/workers-sdk/issues/5442)
> chore: add tests for d1 export

- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/standard-url.ts
This patches the Node.js polyfills Wrangler uses to export `URL` (which is implemented in Workers on `globalThis`)
- Tests
> [wrangler] Export URL from Node.js polyfills

- .changeset/long-pears-sell.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/hello-world-python/c3.ts
- packages/create-cloudflare/templates/hello-world-python/py/.gitignore
- packages/create-cloudflare/templates/hello-world-python/py/package.json
- packages/create-cloudflare/templates/hello-world-python/py/src/entry.py
- packages/create-cloudflare/templates/hello-world-python/py/wrangler.toml
This is a remake of #5417 now that I have perms to make a branch instead of a fork. This is to allow the CI runner to see the secrets needed for e2e testing. 
- Tests
> Add Hello World Python template to c3

- .changeset/chatty-rats-notice.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/standard-url.ts
Adds tests for exposing URL from url & node:url in node_compat mode, as well as a changeset
- Tests
> [wrangler] Expose URL from url & node:url in node_compat mode

- .changeset/twelve-geckos-melt.md
- packages/miniflare/src/plugins/core/proxy/fetch-sync.ts
- packages/miniflare/test/plugins/core/proxy/client.spec.ts
Currently trying to read multiple R2 streams in parallel (via `Promise.all` for example)
generates a deadlock which prevents any of the target streams to be read, this is caused
by the magic proxy underlying implementation only allowing a single HTTP connection to the
workerd process at a time. 
This PR fixes such issue by instead allowing any number of parallel HTTP connections at the same time.
Fixes #5360
- Tests
> [miniflare] fix: make sure the magic proxy can handle multiple parallel R2 stream reads

- .changeset/young-cameras-repair.md
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/filters.ts
- packages/wrangler/src/tail/index.ts
Adds the ability to filter by version in `wrangler tail`.
Fixes WP-797
- Tests
- [0] TODO (before merge)
> feature: add version-id filter for Worker tailing

- .changeset/chilly-queens-compare.md
- fixtures/pages-functions-with-config-file-app/wrangler.toml
- packages/wrangler/src/__tests__/config-validation-pages.test.ts
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/__tests__/pages/deployment-list.test.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
- packages/wrangler/src/__tests__/pages/project-create.test.ts
- packages/wrangler/src/__tests__/pages/project-delete.test.ts
- packages/wrangler/src/__tests__/pages/project-list.test.ts
- packages/wrangler/src/__tests__/pages/project-upload.test.ts
- packages/wrangler/src/__tests__/pages/project-validate.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-pages.ts
- packages/wrangler/src/pages/deploy.tsx
- packages/wrangler/src/pages/dev.ts
This PR adds `wrangler.toml` support in `pages deploy`
♫♫♫
```
Starlight, star bright
First star I see tonight
Starlight, star bright
Make everything alright
```
♫♫♫
- Tests
Apart from unit/integration/fixtures tests, this PR was manually tested based on the following test plan:
<details>
<summary>
</summary>
```
npx wrangler pages deploy public
```
</details>
<details>
<summary>
</summary>
```
pages_build_output_dir = "./public"
name = "pages-with-config-file-app"
compatibility_date = "2024-01-01"
[vars]
VAR1 = "holiday"
VAR2 = "celebrate"
```
```js
// /functions/celebrate.ts
return new Response(
`[/celebrate]:\n` +
`🎵 🎵 🎵\n` +
`You can turn this …
```
> Add `wrangler.toml` support in `pages deploy`

- .changeset/kind-apples-tap.md
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/config/index.ts
Swallow parsing errors when a pages config file is required. This prevents builds failing with invalid non-pages config files. It also means that invalid config file that were intended for Pages will be ignored, which is slightly unfortunate, but we should err on the side of not breaking existing users.
- Tests
> Swallow parsing errors

- .editorconfig
YAML needs space indentation. We use it for GitHub Actions. This tells IDEs to use spaces by default in yml/yaml files.
- Tests
> Use spaces for yaml

- .changeset/wise-grapes-prove.md
- packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
- packages/wrangler/src/pages/download-config.ts
Adds an interactive prompt to `wrangler pages download config` if downloading the config would overwrite an existing `wrangler.toml` file.
Fixes [DEVX-1243](https://jira.cfdata.org/browse/DEVX-1243)
- Tests
> Add prompt to `wrangler pages download config`

- .changeset/real-students-chew.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/hyperdrive/create.ts
- packages/wrangler/src/hyperdrive/delete.ts
- packages/wrangler/src/hyperdrive/get.ts
- packages/wrangler/src/hyperdrive/index.ts
- packages/wrangler/src/hyperdrive/list.ts
- packages/wrangler/src/hyperdrive/update.ts
- packages/wrangler/src/hyperdrive/utils.ts
- packages/wrangler/src/pages/build-env.ts
This ensures that `wrangler pages functions build-env` outputs to a file, rather than stdout.
Fixes #5525 
- Tests
> Write build-env to file

- .changeset/eighty-peas-clean.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
- Include [user limits](https://developers.cloudflare.com/workers/wrangler/configuration/#limits) in wrangler.toml
- Hide usage model from wrangler.toml in all cases
Fixes WP-868. The `usage_model` config field is always ignored by wrangler and should not be set.
- Tests
> fix(wrangler): Improvements to `--init-from-dash`

- .changeset/proud-fireants-report.md
- packages/wrangler/src/__tests__/d1/timeTravel.test.ts
- packages/wrangler/src/d1/timeTravel/info.ts
- packages/wrangler/src/d1/timeTravel/restore.ts
- packages/wrangler/src/d1/timeTravel/utils.ts
Instead of checking for "beta", we should check for alpha.
- Tests
> chore: refactor time-travel compatibility check

- .changeset/three-bikes-talk.md
- packages/wrangler/src/pages/dev.ts
> fix: pages default local port regression

- pnpm-lock.yaml
There was a bug with our internal NPM registry where packages installed via PNPM failed to resolve. I fixed this, and with a very minor lockfile change, internal contributors to workers-sdk will no longer have to temporarily disable their config for the internal registry to install packages on workers-sdk.
How to test:
- Make sure your internal NPM registry config isn't commented out
- `pnpm store prune`
- `rm **/node_modules`
- `pnpm i` (now works!, before didn't)
- Tests
> Fix lockfile to allow use of internal NPM registry

- .changeset/great-scissors-pretend.md
- .gitignore
- .prettierignore
- fixtures/pages-workerjs-with-config-file-app/wrangler.toml
- packages/create-cloudflare/templates/astro/templates/wrangler.toml
- packages/create-cloudflare/templates/common/js/wrangler.toml
- packages/create-cloudflare/templates/common/ts/wrangler.toml
- packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world-durable-object/ts/wrangler.toml
- packages/create-cloudflare/templates/hello-world-python/py/wrangler.toml
- packages/create-cloudflare/templates/hello-world/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
- packages/create-cloudflare/templates/next/wrangler.toml
- packages/create-cloudflare/templates/nuxt/templates/wrangler.toml
- packages/create-cloudflare/templates/openapi/ts/wrangler.toml
- packages/create-cloudflare/templates/pre-existing/js/wrangler.toml
- packages/create-cloudflare/templates/queues/js/wrangler.toml
- packages/create-cloudflare/templates/queues/ts/wrangler.toml
- packages/create-cloudflare/templates/qwik/templates/wrangler.toml
- packages/create-cloudflare/templates/remix/templates/wrangler.toml
- packages/create-cloudflare/templates/scheduled/js/wrangler.toml
- packages/create-cloudflare/templates/scheduled/ts/wrangler.toml
- packages/create-cloudflare/templates/svelte/js/wrangler.toml
- packages/create-cloudflare/templates/svelte/ts/wrangler.toml
- packages/playground-preview-worker/wrangler.json
- packages/wrangler/package.json
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deprecated/index.ts
- pnpm-lock.yaml
This PR generates a JSON schema for Wrangler, as well as updating C3 templates to add a schema property to generated config file. Once merged and released, we should follow up by merging https://github.com/SchemaStore/schemastore/pull/3692.
Fixes #5057, fixes #5055, fixes #3166, [DEVX-1242](https://jira.cfdata.org/browse/DEVX-1242)
- Tests
> Generate a JSON schema for Wrangler

- .changeset/large-pumpkins-try.md
- packages/create-cloudflare/src/wrangler/accounts.ts
Ref: CUSTESC-39344
Previously, C3 would display `TypeError: Cannot read properties of undefined (reading 'value')` if you were logged in as a user without access to any accounts. This change ensures a more appropriate error message is displayed in this case.
- Tests
> [C3] fix: improve error message when no accounts found during deployment

- .changeset/polite-shirts-obey.md
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/js/test/index.spec.js
- packages/create-cloudflare/templates/hello-world/ts/test/index.spec.ts
- add test command to JS template. update failing test example in js template.
- Tests
> C3: add test command to JS template. update failing test example in js template.

- .changeset/odd-squids-fly.md
- packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
Fixes R2-1963. A small fix to update the `CreateBucket` to include the storage class in the request body. Manually tested creating a bucket with a storage class.
- Tests
> Update R2 CreateBucket to include storage class in request body

- .changeset/pink-camels-hug.md
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/workers/core/entry.worker.ts
- packages/miniflare/test/index.spec.ts
- packages/wrangler/templates/startDevWorker/ProxyWorker.ts
Fixes #5246 (CUSTESC-39344).
This PR updates Miniflare to respect the incoming `Accept-Encoding` header, and set the correct value of `Accept-Encoding`/`request.cf.clientAcceptEncoding` inside the Worker. This is to match the production/documented behaviour here: https://developers.cloudflare.com/fundamentals/reference/http-request-headers/#accept-encoding.
- Tests
> [miniflare] feature: respect incoming `Accept-Encoding` header

- .changeset/silent-days-battle.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/user/user.ts
Adds a Queues-specific OAuth scope (`queues:write`) for managing Queue producers and consumers. 
We'll be decoupling the Queues permissions from the base roles such as `workers_scripts:write`, and this is prep work for a transition period.
Fixes # MQ-566 internally
- Tests
> feat(wrangler): Added bespoke Queues scope to the default scopes list/scope options.

- .changeset/green-rats-serve.md
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/pages/build-env.ts
Currently `pages functions build-env` throws a fatal error if a config file does not exit, or if it is
invalid. This causes issues for the CI system. We
should instead exit with a specific code, if any of those situations arises.
You can test by running `npx wrangler pages function build-env [directory] --outfile=<file-name.json>`
- Tests
- with valid Pages config file
- with non-Pages config file + `WRANGLER_LOG="debug"`
- with invalid Pages config file + `WRANGLER_LOG="debug"`
- with invalid non-Pages config file + `WRANGLER_LOG="debug"`
- with no config file + `WRANGLER_LOG="debug"`
PREVIEW OF CI ERR MESSAGING
> fix(wrangler): fix `build-env` to exit with code rather than throw fatal error

- .changeset/giant-pears-tie.md
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/pages/build-env.ts
> fix(wrangler): `pages functions build-env` should throw if invalid Pages config file

- .changeset/unlucky-kangaroos-brake.md
- fixtures/pages-functions-app/package.json
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-plugin-example/functions/ext.ts
- fixtures/pages-plugin-example/package.json
- fixtures/pages-plugin-mounted-on-root-app/package.json
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- pnpm-lock.yaml
This allows Pages Plugins authors to mark dependencies as external when bundling their plugin. This is useful if you want to declare a module as a peer dependency.
- Tests
> Allow marking externals in Pages Functions

- .changeset/warm-bears-marry.md
- packages/wrangler/src/__tests__/d1/export.test.ts
- packages/wrangler/src/d1/export.ts
Uses the new polling-based D1 exporter which handles larger DBs much more efficiently.
- Tests
> D1: using new polling endpoint for larger exports

- .changeset/rich-jokes-chew.md
- fixtures/vitest-pool-workers-examples/d1/vitest.config.ts
- fixtures/vitest-pool-workers-examples/d1/wrangler.toml
- packages/vitest-pool-workers/src/pool/config.ts
- packages/wrangler/src/api/integrations/platform/index.ts
> Feat(vitest-pool-workers): Support specifying an environment in tests

- .changeset/quick-parents-float.md
- .changeset/wild-shoes-love.md
- .github/workflows/e2e.yml
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/tests/tsconfig.json
- fixtures/get-platform-proxy/tsconfig.json
- fixtures/get-platform-proxy/workers/rpc-worker/index.ts
- fixtures/get-platform-proxy/workers/rpc-worker/wrangler.toml
- fixtures/get-platform-proxy/wrangler.toml
- packages/miniflare/package.json
- packages/miniflare/src/http/request.ts
- packages/miniflare/src/http/response.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/workers/core/proxy.worker.ts
- packages/miniflare/test/index.spec.ts
- packages/wrangler/e2e/c3-integration.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/get-platform-proxy.test.ts
- packages/wrangler/e2e/helpers/wrangler-command.ts
- packages/wrangler/e2e/helpers/wrangler.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/turbo.json
- pnpm-lock.yaml
This fixes a number of issues with the Miniflare magic proxy, including:
- Fixes #5575 
- Fixes #5577 (partial support, not including stubs or calling returned functions)
- Tests
> Add basic support for `wrappedBindings` and RPC entrypoints to Miniflare's Magic Proxy

- .prettierignore
- packages/create-cloudflare/templates/hello-world/js/test/index.spec.js
- packages/create-cloudflare/templates/hello-world/ts/test/index.spec.ts
Applies prettier formatting to vitest examples in c3, to match the formatting for the worker.
- Tests
> chore: apply prettier formatting to create-cloudflare tests

- .changeset/purple-cars-run.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/helpers.ts
Currently, when passing a path to `kv:key put --path`, the contents of the file are read in as a Buffer, which would normally be fine - however, when we *also* have `--metadata` defined, the payload is transformed into `FormData`. `FormData` can take a `string`, `Blob` or `File`, and will fall back to `string` for everything else. Because we loaded the file as a Buffer, the file contents are then transformed into a string by the library being used (`undici`). *Normally* this is okay *unless* you are not uploading a text-based document, e.g an image file.
Fixes #2911.
- Tests
Minor change correcting behaviour to what is expected
> fix(wrangler) wrangler kv:key put does not work as expected

- .changeset/gorgeous-taxis-argue.md
- packages/wrangler/src/d1/migrations/apply.tsx
Prior to this PR, migrations such as:
```
SELECT 1
```
would fail with a nonsensical error about INSERTS: `✘ [ERROR] near "INSERT": syntax error at offset 199 [code: 7500]`
What was happening was that wrangler was injecting a statement at the end of the migration, to update the migrations table saying the query successfully executed.
To avoid this, this PR moves the statement to the start of the migration.
> [D1] fix `wrangler d1 migration apply` to for queries not ending in a semi-colon

- .changeset/quick-cheetahs-attack.md
- packages/create-cloudflare/src/summary.ts
Hi :wave:,
Before getting side-tracked with #5482, I found that when using `.` as the project location, there was nowhere to `cd` to, so the first line in the next steps output summary was skipped. Instead of being properly skipped, `undefined undefined` was printed (see screenshot). This change should skip over these lines where a step is excluded.
- Tests
> [C3] Skip empty summary rows

- .changeset/wise-beds-buy.md
- .github/ISSUE_TEMPLATE/config.yml
- packages/create-cloudflare/src/summary.ts
- packages/format-errors/src/index.ts
- packages/kv-asset-handler/README.md
- packages/miniflare/src/plugins/core/errors/index.ts
- packages/workers-playground/src/QuickEditor/ToolsPane.tsx
- packages/wrangler/README.md
- packages/wrangler/src/__tests__/constellation.test.ts
- packages/wrangler/src/constellation/utils.ts
Hi :wave:,
I was originally reproducing and fixing a completely unrelated bug in c3, but noticed the old url in the summary after creating a project. Since the new URL is preferred, I thought I'd PR it, and a quick search found another 20 or so matches.
The only remaining instances of the old .gg/cloudflaredev one are in changelog entries, which I didn't want to modify.
The changeset for this is a patch to every touched package, not sure if this is worth releasing kv-asset-handler for. Also since Hyperdrive is now GA (🎉), the banner might go away so if this would cause merge conflicts, happy to undo any conflicting ones (also Constellation).
- Tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRI …
> Use new Discord server url

- packages/wrangler/src/config/environment.ts
As part of an ongoing "configuration keys in wrangler" audit, this commit cleans up some of the configuration related comments, annotations, aso, in an attempt to keep things consistent and updated across the board.
- Tests
> chore(wrangler): Configuration keys clean-up

- .github/workflows/e2e.yml
- packages/wrangler/e2e/helpers/wrangler.ts
Fixes problems with packaging up a local Wrangler for use in e2e tests.
Previously we had to manually pack Wrangler and its "workspace" dependencies to make it available as a command in e2e tests.
But pnpm now has a `deploy` command (https://pnpm.io/cli/deploy) that can capture these workspace dependencies into a local directory, which we can then use in e2e tests.
- Tests
> ci: fix deployment of local Wrangler for e2e tests

- .changeset/odd-guests-beam.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- packages/wrangler/src/dev/miniflare.ts
This PR solves the regression of local Durable Object proxies not working (a regression introduced in wrangler 3.46.0, more specifically in https://github.com/cloudflare/workers-sdk/pull/5215)
To test the fix please try out the minimal reproductions of the linked issues 👇 with both the latest wrangler version and this [PR's prerelease](https://github.com/cloudflare/workers-sdk/pull/5669#issuecomment-2067679382) (the former will not work while the latter would work as intended)
Fixes #5620
Fixes #5658
- Tests
> [wrangler] fix: fix local Durable Object proxies not working

- .github/workflows/test-old-node-error.yml
MacOS on Github CI doesn't appear to support Node.js 10 any more.
> ci: only test "old node" error message on Unix

- fixtures/sites-app/package.json
- pnpm-lock.yaml
In the Version Packages PR we saw a weird changelog addition
I believe this is because the sites-app had kv-asset-handler as a runtime dependency rather than a devDependency.
This PR changes that so hopefully this should resolve the changelog weirdness.
- Tests
> chore: move kv-asset-handler to devDependencies in sites-app fixture

- .changeset/shaggy-pugs-switch.md
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/templates/hono/snippets/bindingsType.ts
This fixes an issue introduced with https://github.com/cloudflare/workers-sdk/pull/5675 where the `Bindings` type ends up being too permissive (essentially `Record<string, unknown>`).
Open to suggestions on a better implementation of the new type.
- Tests
> C3: Fix issue with hono Bindings type

- package.json
Limit turbo concurrency to the number of processors available, which will hopefully reduce flakiness
- Tests
> Limit turbo concurrency to the number of processors available

- .changeset/silly-llamas-flow.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/__tests__/asset-server/rulesEngine.test.ts
- packages/pages-shared/asset-server/handler.ts
- packages/pages-shared/environment-polyfills/miniflare.ts
- packages/pages-shared/environment-polyfills/types.ts
- packages/pages-shared/package.json
- packages/pages-shared/vite.setup.ts
- pnpm-lock.yaml
Fixes BANDAOPS-60
This is mostly based off #2574 that was reverted in #2645 due to `wrangler pages dev` failing.
This no longer appears to be causing issues with `wrangler pages dev` in my testing.
Also tested in rc to ensure Link headers still show up when they should
Only applies early hints to html assets
- Tests
> fix: pages-shared: Only apply early hints to html assets

- .changeset/fifty-owls-study.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/asset-server/handler.ts
Fixes # BANDAOPS-41
Stores assetKey in preservation cache rather than the actual asset so that we don't write rarely used bytes to cache. Also now only writes to cache once rather than on every request.
Tested in RC and ensured preservation cache still serves correctly
- Tests
> refactor(pages-shared): Store asset key instead of body in preservation cache

- .changeset/young-chefs-change.md
- packages/wrangler/src/__tests__/worker-namespace.test.ts
- packages/wrangler/src/dispatch-namespace.ts
After noticing #5225 and definitely not renaming a dispatch namespace a few times to see if the team notices it, I found that the banner was being printed twice in that command.
While the linked PR removes the yargs handler, it leaves the function in place, so I thought I'd fix it to aid a potential reintroduction in the future by ensuring the consistency between these functions.
- Tests
> Remove second wrangler banner from namespace rename

- .changeset/stale-parrots-explode.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.ts
Fixes [DEVX-543](https://jira.cfdata.org/browse/DEVX-543)
- Tests
> fix: suggest trying to update Wrangler if there is a newer one available after an unexpected error

- .changeset/silver-cougars-refuse.md
- packages/wrangler/e2e/c3-integration.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployments.ts
- packages/wrangler/src/utils/deployment-id-version-id-change.ts
Fixes WC-2110
We need the version ID in the output so users can migrate before we fully remove it.
- Tests
> Add Version ID to all outputs in addition to the deprecated Deployment ID

- .github/workflows/test-and-check.yml
By splitting the tests into shards we can potentially avoid timeouts and memory issues.
Once merged, we need to:
- Tests
> ci: shard tests by workspace type

- .changeset/old-students-kneel.md
- packages/pages-shared/asset-server/handler.ts
Fixes BANDAOPS-41
Reverts a previous change where we added the HTTP method to the cache key, which caused issues because only GET requests can be written to the cache key.
- Tests
- [ x] Not necessary because:
> fix(pages-shared) Remove request method from cache key

- packages/miniflare/turbo.json
The update to narrow the turbo inputs to miniflare included files that are actually outputs!
- Tests
> chore: miniflare worker-metafiles are outputs not inputs

- .changeset/wet-taxis-share.md
- packages/miniflare/src/workers/core/proxy.worker.ts
- packages/miniflare/test/index.spec.ts
This PR makes it so that "magic" proxy objects can contain functions, something that is not currently possible.
To test the changes in this PR you can try this [minimal reproduction/example](https://github.com/dario-piotrowicz/miniflare-wrappedBindings-getBindings-function-stringification-error-repro) with both the latest version of miniflare and this PR's miniflare prerelease. You can see how the example errors with the former but succeeds with the latter.
> [!NOTE]
> This improves the situation but the magic proxy's handling of functions is not yet perfect, for example functions inside arrays (e.g. `return [() => 'Hello']`) still don't work. Also functions returning functions do not work either.
>
> In any case I believe that the changes here improve the situation and are unlikely to …
> [miniflare] fix: make the magic proxy able to proxy objects containing functions

- .github/pr-add-e2e-label.config.yml
- .github/pull_request_template.md
- .github/workflows/pr-add-e2e-label.yml
Sometimes we review PRs that change snapshot values in unit-tests and e2e tests but we don't notice the e2e snapshots were updated.
This PR makes sure that the 'e2e' label is added to a PR if any files within wrangler's e2e/ directory are touched. If the e2e tests change, we undoubtedly want to run the job to make sure they still pass.
This PR also adds to the PR description a reminder for the author and the reviewers to check whether an e2e test run is required.
- Tests
> Auto add e2e label + PR description reminder for e2e

- .changeset/sixty-pans-nail.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/use-esbuild.ts
now, if esbuild doesn't start bundling within a timeout of the custom build finishing, we assume it has decided to skip bundling and continue with the previous bundle output
This is alternative fix from #5741 but the guarantee of requests using your latest code changes is maintained
- Tests
> fix: custom build noop causes esbuild to skip bundling

- .github/workflows/c3-e2e.yml
Tries to avoid running C3 e2e tests on 3rd party forks, which will never pass.
> ci: don't run c3 checks on non-cloudflare repos

- .changeset/stale-books-greet.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/asset-server/handler.ts
Fixes CUSTESC-40911
- Tests
- [?] Not necessary because: bugfix, though I could see how it may be worth noting?
> skip header rules on asset handler error

- fixtures/ai-app/package.json
- pnpm-lock.yaml
This simply removes the unneeded dev dependency on `@cloudflare/ai`, with this now being a native binding.
- Tests
> chore: remove no longer used ai dependency

- .changeset/purple-terms-tell.md
- packages/wrangler/src/__tests__/config-validation-pages.test.ts
- packages/wrangler/src/config/validation-pages.ts
Support `mtls_certificate` and `browser` bindings for Pages projects with a `wrangler.toml` file. The backend support for this has already landed.
Fixes [DEVX-1270](https://jira.cfdata.org/browse/DEVX-1270)
- Tests
> Support `mtls_certificate` and `browser` bindings for Pages

- .github/workflows/test-and-check.yml
> ci: run tests on macos 13 rather than latest

- .changeset/real-waves-wave.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
Prior to Wrangler 3.4.0 we displayed an error if the user tried to upload a JSON file that contained non-string secrets, since these are not supported by the Cloudflare backend.
This change reintroduces that check to give the user a helpful error message rather than a cryptic `workers.api.error.invalid_script_config` error code.
- Tests
> fix: do not allow non-string values in bulk secret uploads

- package.json
When you run `pnpm fix` the eslint run may make changes to the code that would then fail prettier formatting checks.
Running the eslint step first avoids this.
> chore: run lint then prettier when fixing code

- .changeset/ninety-trainers-attack.md
- packages/create-cloudflare/templates/scheduled/js/package.json
- packages/create-cloudflare/templates/scheduled/js/src/index.js
- packages/create-cloudflare/templates/scheduled/ts/package.json
- packages/create-cloudflare/templates/scheduled/ts/src/index.ts
First time starting to do a scheduled worker locally so I use the template: get all obscure warnings and error messages as per #4720. Really not intuitive to the uninitiated. This doesn't solve that issue completely but should hopefully help.
https://developers.cloudflare.com/workers/runtime-apis/handlers/scheduled/
Fixes #4720, #4560
- Tests
> C3: Improve cron/scheduled template docs

- .prettierrc
- package.json
- packages/create-cloudflare/package.json
- packages/format-errors/package.json
- packages/miniflare/package.json
- packages/prerelease-registry/package.json
- packages/quick-edit-extension/package.json
- packages/vitest-pool-workers/.eslintrc.js
- packages/vitest-pool-workers/src/pool/index.ts
- packages/workers-playground/package.json
- pnpm-lock.yaml
This PR bumps packages to the latest version of TS 5, which means that the entire repo can be checked with one TS version. Previously, Miniflare required a different version, which caused issues when typechecking in VSCode across multiple packages.
- Tests
> Bump to TS 5

- .changeset/quiet-wolves-camp.md
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/__tests__/pages/dev.test.ts
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/pages/deploy.tsx
- packages/wrangler/src/pages/dev.ts
Running `wrangler pages --help` will list, amongst others, the following global flags:
Some of these global flags however, such as `--env`, `--config` or `--experimental-json-config`, are not supported by Pages, and therefore listing them as if they were gets users confused.
This PR ensures we only list the relevant flags when running `wrangler pages --help`
Fixes #5725.
**Before**
`wrangler --help`
`wrangler pages --help`
**After**
`wrangler --help`
`wrangler pages --help`
`wrangler pages dev --help`
- Tests
> fix(wrangler): Display correct global flags in `wrangler pages --help`

- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/__tests__/pages/dev.test.ts
https://github.com/cloudflare/workers-sdk/pull/5814 was merged despite some failing tests. This PR fixes those tests
- Tests
> fix(wrangler): Fix failing tests

- packages/wrangler/package.json
Jest inline snapshots do not work with prettier verision `3`. For more details please refer to
https://github.com/jestjs/jest/issues/14305.
This commit fixes that by applying the recommended fix as per GitHub issue thread above.
- Tests
> fix(wrangler): Make jest inline snapshots work with prettier 3

- .changeset/smart-actors-allow.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation.ts
> Deprecate "deployment" in metadata binding

- .changeset/thirty-kings-serve.md
- packages/wrangler/src/dev/dev.tsx
Hyperdrive is supported locally (see https://github.com/cloudflare/workerd/pull/1266) and this warning is not longer accurate. It was added while the support was in progress to avoid confusion (https://github.com/cloudflare/workers-sdk/commit/54800f6f2dc52b921e7dd1d9a57bb437e2094bb0), but now that local support for Hyperdrive bindings has been added, this log is incorrect and should be removed
- Tests
> Remove Hyperdrive warning log indicating that Hyperdrive local binding does not work

- .changeset/unlucky-radios-fold.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/asset-server/handler.ts
> Don't cache 404s from the asset-server

- .changeset/funny-drinks-destroy.md
- packages/wrangler/src/__tests__/middleware.test.ts
- packages/wrangler/src/deployment-bundle/apply-middleware.ts
- packages/wrangler/templates/facade.d.ts
- packages/wrangler/templates/middleware/loader-modules.ts
Use the named export `__INTERNAL_WRANGLER_MIDDLEWARE__` for listing the middleware to be injected in module-format workers. To inject middleware for testing, use `__INJECT_FOR_TESTING_WRANGLER_MIDDLEWARE__`.
This removes support for adding a `middleware` array to your exported handler.
Fixes #5420.
- Tests
> Check if middleware is an array

- .changeset/funny-frogs-sneeze.md
- packages/vitest-pool-workers/src/worker/events.ts
- packages/vitest-pool-workers/src/worker/index.ts
- packages/vitest-pool-workers/src/worker/lib/cloudflare/test-internal.ts
- packages/vitest-pool-workers/src/worker/lib/cloudflare/test-runner.ts
- packages/vitest-pool-workers/src/worker/wait-until.ts
- packages/vitest-pool-workers/test/console.test.ts
https://github.com/cloudflare/workers-sdk/pull/5508/commits/491f5b0f780e9c58bb93e4ddbc98a5b6801fd0fe#diff-22197b5883e04a7de7c11ce6ed06e43617d41efcd785b3ed54a8bcad4610d89d
Fixes #5385 
- Tests
> fix: ensure `console.log()`s displayed in `SELF` integration tests

- .changeset/little-jars-train.md
- packages/miniflare/src/workers/d1/database.worker.ts
- packages/miniflare/test/plugins/d1/suite.ts
- packages/miniflare/test/plugins/d1/test.ts
TL;DR: Cloudflare D1 has a critical bug in Workers SDK reproducible on the Cloudflare D1 Console and when running D1 through Wrangler. The PR fixes the bug and also improves compatibility with `workerd`.
The essence of the problem is selecting two columns with similar names:
```sql
SELECT
projects.name,
organizations.name
FROM
projects
JOIN organizations ON projects.organization_id = organizations.id;
```
...must return in the row containing both columns (tested on PostgreSQL v16.3):
```
test=# SELECT projects.name, organizations.name
FROM projects
JOIN organizations ON projects.organization_id = organizations.id;
name    |    name    
------------+------------
Cloudflare | Cloudflare
(1 row)
```
SQLite (on a database created by Wrangler) gives a similar result:
```
sqlite> SELECT …
```
> Partially fix #3160 by properly handling resultsFormat query

- .changeset/fluffy-carrots-peel.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/parse.ts
- packages/wrangler/src/secret/index.ts
> Improve error message when updating secret for a non-deployed latest version

- .changeset/silent-jeans-hammer.md
- fixtures/additional-modules/package.json
- fixtures/external-durable-objects-app/package.json
- fixtures/external-service-bindings-app/package.json
- fixtures/get-bindings-proxy/package.json
- fixtures/get-platform-proxy/package.json
- fixtures/local-mode-tests/package.json
- fixtures/node-app-pages/package.json
- fixtures/pages-dev-proxy-with-script/package.json
- fixtures/pages-functions-app/package.json
- fixtures/pages-functions-with-routes-app/package.json
- fixtures/pages-plugin-mounted-on-root-app/package.json
- fixtures/pages-simple-assets/package.json
- fixtures/remix-pages-app/package.json
- fixtures/vitest-pool-workers-examples/package.json
- fixtures/worker-ts/package.json
- package.json
- packages/create-cloudflare/package.json
- packages/edge-preview-authenticated-proxy/package.json
- packages/format-errors/package.json
- packages/kv-asset-handler/package.json
- packages/miniflare/package.json
- packages/pages-shared/package.json
- packages/playground-preview-worker/package.json
- packages/prerelease-registry/package.json
- packages/quick-edit-extension/package.json
- packages/vitest-pool-workers/package.json
- packages/workers.new/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
Manually bumping `workerd` and `workers-types` versions because the `dependabot` version update job seems to be broken (due to https://github.com/dependabot/dependabot-core/issues/9682)
- Tests
> chore: bump workerd and workers-types deps

- .changeset/cold-berries-raise.md
- packages/miniflare/README.md
This PR is simply adding info about the `MINIFLARE_WORKERD_PATH` env variable in the main Miniflare readme
(each time I need to use the env variable I need to dig through the code for it etc... I figured it could be worth to properly document this?)
- Tests
> add configuration section with local workerd linking to Miniflare readme

- .changeset/blue-pets-think.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/config.ts
- pnpm-lock.yaml
The experimental "assets" field can be either a string or an object. However the type definition marks it only as an object. This is a problem because we use this to generate the json schema, which gets picked up by vscode's even better toml extension, and shows it to be an error when used with a string (even though it works fine). The fix is to simply change the type definition to add a string variant.
> fix: let "assets" in wrangler.toml be a string

- .changeset/thick-parrots-rest.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation.ts
This PR updates Wrangler CLI to use `Ai` type for the `AI` binding.
- Tests
> Use proper type for AI binding in wrangler types

- packages/create-cloudflare/e2e-tests/frameworks.test.ts
the docusaurus cli is now asking for the language to use, we are not handling that in the c3 e2es causing the docusaurus ones to time out (like [here](https://github.com/cloudflare/workers-sdk/actions/runs/9309087223/job/25623808631?pr=5944#step:4:327) and [here](https://github.com/cloudflare/workers-sdk/actions/runs/9318210394/job/25651828633?pr=5943#step:4:400)), this PR addresses this issue
- Tests
> add missing promptHandler to C3 docusaurus e2e

- .prettierignore
- packages/create-cloudflare/templates/hello-world/js/vitest.config.js
- packages/create-cloudflare/templates/hello-world/ts/test/tsconfig.json
- packages/create-cloudflare/templates/hello-world/ts/vitest.config.ts
These templates use tabs throughout, so for consistency the vitest config and nested tsconfig.json should also. This way, on new projects, folks don't get a mix of indentation, quotes, etc.
It also makes sure that `packages/create-cloudflare/templates/hello-world/**/*.*` is included in prettier runs. I understand that other templates don't enforce this, but for the hello world one, it ships with best practices (tabs), and it would be ideal if that's maintained in this template moving forward.
- Tests
> chore: use tabs for consistency in C3 templates

- .changeset/silent-spoons-hear.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/workers/rpc-worker/index.ts
- packages/miniflare/src/plugins/core/proxy/client.ts
- packages/miniflare/src/workers/core/devalue.ts
- packages/miniflare/src/workers/core/proxy.worker.ts
- packages/miniflare/test/index.spec.ts
The changes here allow the Miniflare Magic Proxy to handle functions returning functions.
You can usage examples in the tests added to miniflare and the `get-platform-proxy` fixture.
- Tests
> [miniflare] Allow the magic proxy to handle functions returning functions

- packages/wrangler/src/__tests__/configuration.test.ts
Fixup the test added in https://github.com/cloudflare/workers-sdk/pull/5963
- Tests
> chore: wrap WRANGLER_DISABLE_EXPERIMENTAL_WARNING test process.env mutation in try..finally

- .changeset/popular-ravens-add.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
When we added the ability to include additional modules in the deployed bundle of a Worker,
we inadvertently also included some boiler plate code that is only needed at development time.
This fix ensures that this code is only injected if we are running esbuild in watch mode
(e.g. `wrangler dev`) and not when building for deployment.
It is interesting to note that this boilerplate only gets included in the production code
if there is an import of CommonJS code in the Worker, which esbuild needs to convert to an
ESM import.
Fixes [#4269](https://github.com/cloudflare/workers-sdk/issues/4269)
- Tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changes …
> fix: avoid injecting esbuild watch stubs into production Worker code

- .vscode/settings.json
Currently, the VSCode ESLint extension cannot locate the `tsconfig.json` file if it is located in a sub-folder of its `package.json`. E.g.
```
/packages
/vitest-pool-workers
/src
/worker
tsconfig.json <-- not in package root
package.json
```
For example, head to `/packages/vitest-pool-workers/src/worker/index.ts` and you will probably see this error on the first token (`import`):
```
Parsing error: Cannot read file '/path/to/workers-sdk/src/worker/tsconfig.json'.eslint
```
The ESLint extension has the `workingDirectories` setting, which we can use to tell it about these sub-folders. There are probably two options available. The first is to specify all the working directories. The downside of this is that we would have to manually update it when adding or moving folders.
The second option …
> chore: allow VSCode to correctly parse tsconfig.json for ESLint tooling in sub-folders

- packages/create-cloudflare/templates/hello-world-durable-object/ts/wrangler.toml
- templates/worker-typescript/wrangler.toml
This brings it in line with the wrangler.toml defined in most places.
Specifically this brings the 2 touched files in line with the config link at /packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.toml
Old links are broken/not as good.
Didn't open an issue
- Tests
> fix DO migration docs links

- .changeset/old-horses-push.md
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/config/validation-pages.ts
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
- packages/wrangler/src/deployment-bundle/source-maps.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/deploy.tsx
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
Adds the ability for Pages projects to use the new sourcemap support in Workers to get remapped stacktraces in the dashboard's real-time logs.
Fixes WP-959 WP-960 WP-961.
- Tests
> feat: allow for Pages projects to upload sourcemaps

- .vscode/launch.json
- pnpm-lock.yaml
- tools/package.json
- tools/test/run-test-file.ts
This is a quality-of-life improvement for debugging and testing packages locally. If you're using VSCode, and your current buffer is a test file, you can select the debug panel and you will see a "Debug Current Test File" option:
Hit `f5` or click the green triangle and the test will start to run in the VSCode console:
This specific implementation runs as a command attached to the `tools` package, running it with `pnpm` as with any other package.json script in the repo.
- Tests
> chore: add launch.json to debug single (current) test file

- packages/wrangler/src/versions/api.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/list.ts
Updates existing `wrangler versions` API call to fetch deployable versions. It should be a more trust-worthy source of usable / available versions.
> fix: wrangler versions list deployable versions

- packages/miniflare/src/index.ts
The builtin-wasm-modules autogate is no longer required.
Doesn't fix anything. Just a cleanup.
- Tests
> Cleanup: Remove builtin-wasm-modules from autogates passed to workerd

- .changeset/calm-flowers-doubt.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/secret/index.ts
and deprecate `secret:bulk` – command still exists with same functionality but also with a deprecation notice
Fixes #5168
- Tests
> rename `secret:bulk` top-level command to `secret bulk` subcommand

- .changeset/long-planets-provide.md
- packages/pages-shared/metadata-generator/createMetadataObject.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/__tests__/api-dev.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/pages/dev.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/index.ts
- packages/wrangler/src/miniflare-cli/assets.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/update-check.ts
The `wrangler pages dev` terminal output is currently a bit noisy and lacking a clearer, more organised structure. This PR cleans up the `pages dev` `stdout`/`stderr` logs in an attempt to make it more readable and easier to reason about for our users (and ourselves 😉 ) <3
<details>
<summary>After TLDR;</summary>
</details>
As part of this PR, the following issues were addressed:
<details>
<summary>1. `compatibility-date` warnings</summary>
**Before**
`wrangler dev`
`wrangler pages dev`
**After**
`wrangler dev` 
`wrangler pages dev`
</details>
<details>
<summary>2. wrangler logo display</summary>
**Before** 
`wrangler dev`
`wrangler pages dev`
**After**
`wrangler dev`
`wrangler pages dev`
</details>
<details>
<summary>3. `_headers` / `_redirects` parsing warnings</summary>
**Before** …
> fix(wrangler) Clean `pages dev` terminal output

- .changeset/fluffy-bottles-taste.md
- packages/create-cloudflare/src/helpers/__tests__/codemod.test.ts
- packages/create-cloudflare/src/helpers/codemod.ts
- packages/create-cloudflare/templates/nuxt/c3.ts
- packages/create-cloudflare/templates/solid/c3.ts
> [C3] fix: make sure that C3 doesn't delete pre-existing options in Solid's `defineConfig` call

- .github/holopin.yml
- .github/workflows/holopin.yml
Holopin is a recognition and digital badge platform that we will adopt in our cloudflare-docs and workers-sdk repositories to help show appreciation for the excellent open-source contributions that we receive.
Every PR that is merged will be automatically labelled with `contribution` and a holobyte for the evolving Lava Lamp badge will be issued:
Maintainers, if you find a contribution that you feel is truly excellent, you can manually add the `outstanding contribution` label and this will issue a special Global Contribution badge immediately:
This PR adds the necessary configuration, but we still need the `HOLOPIN_LABELER` secret (a PAT — I want to use @workers-devprod) and we also still need to install the GitHub bot (cc. @rita3ko).
> Add Holopin

- .changeset/large-seals-kiss.md
- packages/wrangler/src/__tests__/d1/insights.test.ts
- packages/wrangler/src/d1/insights.ts
This PR teaches `wrangler d1 insights` about more timePeriods. The input can now be of the form`\d+[dmh]`
Fixes #5048 
- Tests
> feat(wrangler-d1): Teach wrangler d1 insights about more timePeriods

- .changeset/thick-items-approve.md
- packages/create-cloudflare/templates/common/ts/src/ab-test.ts
- packages/create-cloudflare/templates/common/ts/src/index.ts
- packages/create-cloudflare/templates/common/ts/src/proxy.ts
- packages/create-cloudflare/templates/common/ts/src/redirect.ts
- packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts
- packages/create-cloudflare/templates/hello-world/ts/src/index.ts
- packages/create-cloudflare/templates/openapi/ts/src/index.ts
- packages/create-cloudflare/templates/queues/ts/src/index.ts
- packages/create-cloudflare/templates/scheduled/ts/src/index.ts
Use `satisfies ExportedHandler` for handlers in templates. This will improve autocompletion in the editor and make the code cleaner.
- Tests
> [C3] Use `satisfies ExportedHandler` for handlers in templates

- .changeset/hot-jokes-watch.md
- packages/vitest-pool-workers/types/cloudflare-test.d.ts
[#5975](https://github.com/cloudflare/workers-sdk/pull/5975) updated the type for `runInDurableObject` to infer the stub's type correctly for RPC methods, however it used the wrong `DurableObjects` type. This PR fixes the type used to properly support RPC methods.
- Tests
cc @RamIdeas
> Improve `runInDurableObject` type

- packages/wrangler/src/__tests__/pages/project-upload.test.ts
Adds a test to avoid accidentally breaking Pages uploads for large numbers of assets.
**This test would have failed after the #5632 change.**
- Tests
> test: add checks of uploads of very large number of Pages assets

- .changeset/twenty-jeans-matter.md
- packages/wrangler/src/__tests__/utils/create-batches.test.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/pages/constants.ts
- packages/wrangler/src/pages/upload.tsx
- packages/wrangler/src/utils/create-batches.ts
Reapplies the batching reverted in https://github.com/cloudflare/workers-sdk/pull/6002 but with a tested helper method to ensure batches are correctly compiled
- Tests
> fix: reduce the number of parallel file reads on Windows to avoid EMFILE type errors

- .changeset/lazy-cycles-pull.md
- fixtures/nodejs-hybrid-app/src/index.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
It turns out that ESBuild paths are case insensitive, which can result in path collisions between polyfills for globalThis.performance and globalThis.Performance.
This change ensures that we encode all global names to lowercase and decode them appropriately.
The version of unenv used at HEAD currently doesn't suffer from this path collision, but if not fixed the change introduced in https://github.com/unjs/unenv/pull/257/files would result in Node.js API coverage regressions. This change prevents those regressions from happening.
- Tests
- …
> fix(wrangler): avoid path collisions between performance and Performance polyfills

- packages/cli/index.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
- packages/wrangler/src/__tests__/helpers/msw/handlers/versions.ts
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/versions/api.ts
- packages/wrangler/src/versions/deploy.ts
Shows a warning to avoid accidental overwrite of a percentage-based deployment.
- Tests
> feat: wrangler deploy prompts warning with deployment

- .github/workflows/pr-add-e2e-label.yml
Actions cannot trigger other actions if they use the same GH account.
The problem here was that the automated adding of e2e label did not trigger the e2e test run.
> ci: use a separate GH token for adding labels

- .github/workflows/c3-e2e-dependabot.yml
- .github/workflows/c3-e2e-quarantine.yml
Avoid running all the C3 quarantined tests for all frameworks in dependabot PRs
> ci: only run C3 quarantined tests in dependabot PRs if targeted

- .changeset/afraid-mails-kneel.md
- fixtures/nodejs-hybrid-app/src/dep.cjs
- fixtures/nodejs-hybrid-app/src/index.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Fixes [#6028](https://github.com/cloudflare/workers-sdk/issues/6028)
There is a change to the nodejs_hybrid_app fixture that demonstrates the problem and the fix.
Without this fix you get:
```
✘ [ERROR] service core:user:nodejs-hybrid-app: Uncaught TypeError: Stream2 is not a constructor
at null.<anonymous> (index.js:8765:14) in src/dep.cjs
at null.<anonymous> (index.js:19:50) in __require2
at null.<anonymous> (index.js:8788:26)
```
- Tests
> fix: hybrid nodejs compat now supports requiring the default export of a CJS module

- .changeset/smooth-pumpkins-breathe.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/pages/functions/tsconfig.json
Allow Durable Object migrations to be overridable in environments. By making the `migrations` key inheritable, users can provide different migrations for each wrangler.toml environment.
Resolves https://github.com/cloudflare/workers-sdk/issues/729
- Tests
> Allow do migrations in environments

- .changeset/rotten-pears-hope.md
- packages/wrangler/src/deployment-bundle/apply-middleware.ts
(Another simpler take on https://github.com/cloudflare/workers-sdk/pull/5999, inspired by https://github.com/cloudflare/workers-sdk/pull/6006)
I've been experimenting with esbuild 0.21.4 with wrangler. It's mostly been fine. But I get this warning every time
```
▲ [WARNING] Import "__INJECT_FOR_TESTING_WRANGLER_MIDDLEWARE__" will always be undefined because there is no matching export in "src/index.ts" [import-is-undefined]
.wrangler/tmp/bundle-Z3YXTd/middleware-insertion-facade.js:8:23:
8 │ .....(OTHER_EXPORTS.__INJECT_FOR_TESTING_WRANGLER_MIDDLEWARE__ ?? []),
╵
```
This is because esbuild@0.18.5 enabled a warning by default whenever an undefined import is accessed on an imports object. However we abuse imports to inject stuff in `middleware.test.ts`. A simple fix is to only inject that …
> fix: avoid esbuild warning when running dev/bundle

- packages/vitest-pool-workers/src/config/index.ts
The type definition of `defineWorkersConfig` doesn't work with `mergeConfig` of `vitest/config` because of type mismatch
This function should be an overload function like [defineConfig](https://github.com/vitest-dev/vitest/blob/f15b4e99da1d8e5531ecc900792e3bb490fe1c7a/packages/vitest/src/config.ts#L23-L29)
- Tests
> fix: define defineWorkersConfig using overload signatures

- .github/actions/install-dependencies/action.yml
- .github/workflows/c3-e2e.yml
- .github/workflows/changesets.yml
- .github/workflows/d1.yml
- .github/workflows/deploy-pages-previews.yml
- .github/workflows/prereleases.yml
- .npmrc
This should remove the `WARN  Issue while reading "/Users/***/dev/cloudflare/workers-sdk/.npmrc". Failed to replace env in config: ${NPM_PUBLISH_TOKEN} ` warning we always
> setup the npm registry url with setup-node config

- .changeset/chatty-candles-smoke.md
- packages/wrangler/src/https-options.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/5964
For `wrangler dev`, we don't have to check whether certificates have expired when they're provided by the user.
> Don't check expiry dates on custom certs

- packages/vitest-pool-workers/test/global-setup.ts
These tests create a fake package that relies upon the local versions of vitest-pool-workers and its dependencies. To make this work we package up all the local dependencies and add them to pnpm overrides.
Unfortunately we missed the transitive `@cloudflare/kv-asset-handler` dependency, so when that got a version bump the tests broke.
This is the simple, naive fix - adding in this package to those being packed. We ought to find a better solution that doesn't require manual dependency tracking.
- Tests
> test: fix vitest-pool-workers tests that rely on local workspace packages

- .changeset/unlucky-hairs-train.md
- packages/wrangler/src/d1/execute.tsx
Fixes typo in `d1 execute`
- Tests
> Fix typo - "Databas" -> "Database"

- packages/wrangler/e2e/README.md
- start by deleting `.tmp`
- add `TEST_PM=npm`
> tweak instructions for running e2e tests

- .changeset/tiny-cameras-tease.md
- packages/create-cloudflare/src/helpers/args.ts
This adds missing info to the C3 help message:
- Tests
> [C3] fix: add missing `pre-existing` type and `--existing-script` to help message

- packages/eslint-config-worker/index.js
- packages/eslint-config-worker/react.js
- packages/workers-playground/.eslintrc.js
- packages/workers-playground/tsconfig.json
- packages/wrangler/.eslintrc.js
Our default eslint config includes react linting, and was applied to every package. However that meant we kept seeing warnings about react not being detected etc. This patch splits out the react part, and applies it only where required.
> run react eslint rules only where needed

- packages/wrangler/src/__tests__/d1/splitter.test.ts
- packages/wrangler/src/d1/splitter.ts
Follows sqlite spec for case insensitive BEGIN and CASE [(discussed in Discord)](https://discord.com/channels/595317990191398933/992060581832032316/1242554524548464650)
Solves not using these operators not in caps leading into a wrangler exception.
```
✘ [ERROR] incomplete input
```
- Tests
> [wrangler] Made D1 BEGIN and CASE regex case insensitive

- packages/eslint-config-worker/react.js
- packages/workers-playground/.eslintrc.js
- packages/wrangler/.eslintrc.js
We don't actually lint this package, so removing it for now. Followup issue: https://github.com/cloudflare/workers-sdk/issues/6074
> chore: remove eslint config from workers-playground

- .changeset/tough-poets-deliver.md
- packages/create-cloudflare/templates/common/js/package.json
- packages/create-cloudflare/templates/common/ts/package.json
- packages/create-cloudflare/templates/hello-world-durable-object/js/package.json
- packages/create-cloudflare/templates/hello-world-durable-object/ts/package.json
- packages/create-cloudflare/templates/hello-world-python/py/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
- packages/create-cloudflare/templates/openapi/ts/package.json
- packages/create-cloudflare/templates/pre-existing/js/package.json
- packages/create-cloudflare/templates/queues/js/package.json
- packages/create-cloudflare/templates/queues/ts/package.json
- packages/create-cloudflare/templates/scheduled/js/package.json
- packages/create-cloudflare/templates/scheduled/ts/package.json
When generating a plain hello world worker, we're picking up older versions of vitest/pool-workers. this updates the package.jsons to pick up newer versions instead. Ideally we should automate this, but we can do that later. I also updated the wrangler deps to the current version so it's clearer for developers what they're using (still not accurate, but better than showing 3.0.0). Again, this should be automated, but we can do that later.
- Tests
> c3: use latest dependencies for hello-world templates

- .changeset/polite-bananas-cross.md
This commit adds a changeset for the changes introduced by https://github.com/cloudflare/workers-sdk/pull/5976
Adds a changeset for the changes introduced by https://github.com/cloudflare/workers-sdk/pull/5976
- Tests
> fix: Add missing changeset for #5976

- .changeset/yellow-coins-serve.md
- fixtures/ai-app/tests/index.test.ts
- fixtures/external-durable-objects-app/a/wrangler.toml
- fixtures/external-durable-objects-app/b/wrangler.toml
- fixtures/external-durable-objects-app/c/wrangler.toml
- fixtures/external-durable-objects-app/tests/index.test.ts
- fixtures/external-service-bindings-app/tests/index.test.ts
- fixtures/get-bindings-proxy/tests/get-bindings-proxy.bindings.test.ts
- fixtures/service-bindings-app/tests/index.test.ts
- packages/wrangler/package.json
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/dev-registry.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/experimental-flags.ts
- packages/wrangler/src/pages/dev.ts
- pnpm-lock.yaml
Fixes https://github.com/cloudflare/workers-sdk/issues/6037
- Tests
> File based dev registry

- packages/create-cloudflare/package.json
- packages/format-errors/package.json
- packages/kv-asset-handler/.eslintrc.js
- packages/kv-asset-handler/src/index.ts
- packages/miniflare/package.json
- packages/playground-preview-worker/package.json
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/src/user.do.ts
- packages/playground-preview-worker/tsconfig.json
- packages/quick-edit-extension/.eslintrc.js
- packages/quick-edit-extension/package.json
- packages/quick-edit-extension/src/cfs.ts
- packages/quick-edit/.eslintrc.js
- packages/quick-edit/functions/_middleware.ts
- packages/quick-edit/package.json
- packages/turbo-r2-archive/package.json
- packages/workers-playground/package.json
- packages/workers-playground/src/QuickEditor/PreviewTab/useRefreshableIframe.tsx
Some of our packages didn't have a lint/typecheck rule setup, so I added it. Also fixed a couple of failures along the way. I _didn't_ enable linting for kv-asset-handler because that looks like a bit more work, which we can do later.
No changeset / tests for this, no functional changes.
> chore: run eslint and tsc in missing packages

- .changeset/healthy-snails-heal.md
- packages/kv-asset-handler/package.json
- packages/kv-asset-handler/src/index.ts
- packages/kv-asset-handler/src/mocks.ts
- packages/kv-asset-handler/src/test/getAssetFromKV-optional.ts
- packages/kv-asset-handler/src/test/getAssetFromKV.ts
- packages/kv-asset-handler/src/test/mapRequestToAsset.ts
- packages/kv-asset-handler/src/test/serveSinglePageApp.ts
- packages/kv-asset-handler/src/types.ts
- packages/kv-asset-handler/tsconfig.json
- packages/wrangler/.eslintrc.js
- packages/wrangler/tsconfig.json
- pnpm-lock.yaml
Followup from https://github.com/cloudflare/workers-sdk/pull/6090, this enables typechecking and linting in kv-asset-handler, and fixes any failures.
> chore: pass lint/typechecks for kv-asset-handler

- .changeset/little-rice-promise.md
- packages/wrangler/src/__tests__/rollback.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
- packages/wrangler/src/__tests__/versions/secrets/list.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/__tests__/versions/secrets/utils.ts
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/pages/secret/index.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/utils/std.ts
- packages/wrangler/src/versions/api.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/rollback/index.ts
- packages/wrangler/src/versions/secrets/bulk.ts
- packages/wrangler/src/versions/secrets/delete.ts
- packages/wrangler/src/versions/secrets/index.ts
- packages/wrangler/src/versions/secrets/list.ts
- packages/wrangler/src/versions/secrets/put.ts
- packages/wrangler/src/versions/types.ts
* Adds new versions secret commands (put, bulk, list and view).
* Adds a --pretty option to `wrangler secret list`
* Handles the new API error in rollback when attempting to rollback to a version with changed secrets from current
- Tests
**Version in dash**
> Version secrets + secret behaviour changes

- packages/wrangler/e2e/versions.test.ts
Fixes `versions` e2e tests that started failing after we merged https://github.com/cloudflare/workers-sdk/pull/5950
- Tests
> fix(wrangler): fix failing `versions` e2e tests

- .prettierrc
- fixtures/dev-env/package.json
- fixtures/external-service-bindings-app/package.json
- fixtures/import-wasm-example/package.json
- fixtures/nodejs-hybrid-app/package.json
- fixtures/pages-functions-app/package.json
- fixtures/pages-plugin-mounted-on-root-app/package.json
- fixtures/worker-app/package.json
- package.json
- packages/cli/package.json
- packages/devprod-status-bot/package.json
- packages/edge-preview-authenticated-proxy/package.json
- packages/eslint-config-worker/package.json
- packages/format-errors/package.json
- packages/kv-asset-handler/package.json
- packages/miniflare/package.json
- packages/pages-shared/package.json
- packages/quick-edit-extension/package.json
- packages/quick-edit/package.json
- packages/turbo-r2-archive/package.json
- packages/vitest-pool-workers/package.json
- packages/workers-playground/package.json
- packages/wrangler-devtools/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
- tools/package.json
Simply turns and fixes up the package.json prettier plugin that we had installed but not running.
- Tests
> chore: turn on prettier for package.json files and fix them

- package.json
The "packageManager" field defines which package manager is expected to be used when working on the current project. It can set to any of the supported package managers, and will ensure that your teams use the exact same package manager versions without having to install anything else than Node.js. See https://nodejs.org/dist/latest-v16.x/docs/api/all.html#all_packages_packagemanager for more information.
This commit sets the expected package manager in `workers-sdk` to `pnpm@9.1.3`. We're also secretly hoping, as per https://github.com/dependabot/dependabot-core/issues/9682#issuecomment-2172950223, that this will fix our dependabot-updater issues 😋 🤞 
- Tests …
> chore: Define expected package manager

- packages/wrangler/src/dev/dev.tsx
Fixes extraneous item in onBundleStart dependency array. Addresses comment [here](https://github.com/cloudflare/workers-sdk/pull/6001/files#r1648173873).
This prop was left in the dependency array after removing a redundant surrounding if-condition using the prop. It was decided the comment was enough but I am putting the redundant if-condition back to be ultra specific for readers of the code – the interim period where we're faking some events, but not when the experimental flag is on, is admittedly a bit confusing.
- Tests
> fix: onBundleStart dependency array

- .changeset/chilled-ties-occur.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/r2/index.ts
> Add `demandCommand()` to R2 Commands

- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
Closes [DEVX-1291](https://jira.cfdata.org/browse/DEVX-1291)
Replaces the `args: Record<string, unknown>` param of `normalizeAndValidateConfig` with a stricter type and threads it through via `readConfig`. This is a precursor to [DEVX-1295](https://jira.cfdata.org/browse/DEVX-1295)
- Tests
> chore: ensure `normalizeAndValidateConfig` args param is typed

- packages/create-cloudflare/e2e-tests/frameworks.test.ts
C3 astro e2e test started failing in CI for no obvious reasons since Mon 24 June 2024. We tried everything, like increasing timeouts, debugging, reproducing locally (which we can't) to no avail. We are quite confident that the test failures are not caused by any changes in wrangler (we verified this by running the tests against a PR where they were consistently green, but did fail on the re-run, without any changes to the branch).
As this is blocking our release, we decided to quarantine these tests, do the release, while continuing to look into why the tests are failing.
- Tests
- Public …
> quarantine C3 astro e2e test

- packages/cli/package.json
- packages/create-cloudflare/package.json
- packages/devprod-status-bot/package.json
- packages/edge-preview-authenticated-proxy/package.json
- packages/format-errors/package.json
- packages/kv-asset-handler/package.json
- packages/pages-shared/package.json
- packages/playground-preview-worker/package.json
- packages/prerelease-registry/package.json
- packages/quick-edit-extension/package.json
- packages/quick-edit/package.json
- packages/turbo-r2-archive/package.json
- packages/vitest-pool-workers/package.json
- packages/workers-playground/package.json
- packages/workers.new/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
- tools/package.json
- turbo/generators/templates/package.json.hbs
Modify all the eslint commands to fail if any warnings are present.
--- 
This should fail, and pass once https://github.com/cloudflare/workers-sdk/pull/6001/files#r1648173873 is resolved
> chore: fail build on eslint warnings

- packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
Some minor internal refactors to the config controller, addressing some comments from a [previous PR](https://github.com/cloudflare/workers-sdk/pull/6124) where the relevant diff was cherry-picked into [another PR](https://github.com/cloudflare/workers-sdk/pull/6136) and merged before the comments had been addressed
- Tests
> ConfigController minor internal renaming

- .markdownlint.json
- packages/wrangler/e2e/README.md
- packages/wrangler/e2e/c3-integration.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/dev-env.test.ts
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/get-platform-proxy.test.ts
- packages/wrangler/e2e/helpers/command.ts
- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- packages/wrangler/e2e/helpers/setup.ts
- packages/wrangler/e2e/helpers/wrangler.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/e2e/tsconfig.json
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/e2e/vitest.config.mts
- packages/wrangler/package.json
- pnpm-lock.yaml
- `child_process.kill()` doesn't really work on Windows. Using `kill-tree` library instead
- `killAllWranglerDev()` helper could mess up parallel tests since it kills all wrangler/workerd processes regardless of whether they are part of the current test
- `shellac` library has issues on Windows when running background tasks. Using simple `execSync` and `spawn` functions instead
- tightened up the timeouts a bit to avoid long running false negatives
- reworked the helpers to use a class `WranglerE2ETestHelper` rather than the `e2eTest` extension.
- Tests
> test: improve Windows reliability of e2e tests

- .changeset/tame-news-sleep.md
- packages/wrangler/src/user/user.ts
May help diagnosing issues like https://github.com/cloudflare/workers-sdk/issues/3672, https://github.com/cloudflare/workers-sdk/issues/5542 and https://jira.cfdata.org/browse/CUSTESC-42645
- Tests
> fix: add extra error logging to auth response errors

- packages/create-cloudflare/e2e-tests/frameworks.test.ts
Nuxt is currently broken - so sending to quarantine. See https://github.com/cloudflare/workers-sdk/issues/6155
> test: quarantine nuxt framework in C3 e2e tests

- packages/wrangler/src/pages/deploy.tsx
Just fixing a typo I noticed when running `wrangler pages deploy`
- Tests
> remove extra quote from pages deploy message

- .changeset/heavy-tomatoes-sing.md
- packages/miniflare/src/workers/d1/database.worker.ts
- packages/miniflare/src/workers/d1/dumpSql.ts
- packages/wrangler/src/__tests__/d1/export.test.ts
- packages/wrangler/src/d1/export.ts
This uses a new miniflare-only debug pragma `PRAGMA miniflare_d1_export` to trigger the dump as D1 provides no in-Worker API (which Miniflare uses) to generate exports.
I'm open to other ways to implement this.
Fixes limitation with the previous iteration of the export functionality. Previously, all `d1 export --local` commands would fail.
- Tests
> Added `d1 export --local` support

- packages/workers.new/package.json
- pnpm-lock.yaml
Making sure we use the same version of typescript in every package
No changesets or tests, just a simple internal update.
> chore: update typescript in workers.new

- .changeset/grumpy-bikes-prove.md
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/rollback.test.ts
- packages/wrangler/src/__tests__/zones.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/tail/index.ts
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/versions/rollback/index.ts
- packages/wrangler/src/zones.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/4944
Trying to fetch `/zones` fails when it spans more than 500 zones. The fix to use an account id when doing so. This patch passes the account id to the zones call, threading it through all the functions that require it.
- Tests
> fix: use account id for listing zones

- .changeset/gorgeous-oranges-brake.md
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/pages/utils.ts
The watch mode in `pages dev` for Pages Functions projects is currently partially broken, as it only watches for file system changes in the `/functions` directory, but not for changes in any of the Functions' dependencies. This means that given a Pages Function `math-is-fun.ts`, defined as follows:
```
import { ADD } from "../math/add";
export async function onRequest() {
return new Response(`${ADD} is fun!`);
}
```
`pages dev` will reload for any changes in `math-is-fun.ts` itself, but not for any changes in `math/add.ts`, which is its dependency.
Similarly, `pages dev` will not reload for any changes in non-JS module imports, such as wasm/html/binary module
imports.
This PR fixes all these things, plus adds some extra polish to the `pages dev` watch mode experience.
Fixes …
> fix(wrangler): Watch for external dependencies changes in `pages dev`

- .changeset/itchy-bags-shake.md
- packages/wrangler/src/api/integrations/platform/index.ts
https://github.com/cloudflare/workers-sdk/pull/5612 added support for selecting the environment of config used, but it missed passing it to the code that reads `.dev.vars.{environment}`
Fixes #5641 
- Tests
> Fix: vitest-pool-workers use env in .dev.vars

- .changeset/few-days-tap.md
- fixtures/interactive-dev-tests/tests/index.test.ts
- packages/miniflare/src/shared/log.ts
- packages/wrangler/src/__tests__/cli-hotkeys.test.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
- packages/wrangler/src/cli-hotkeys.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/create-worker-preview.ts
- packages/wrangler/src/dev/hotkeys.ts
- packages/wrangler/src/dev/inspect.ts
- packages/wrangler/src/dev/proxy.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/dialogs.ts
- packages/wrangler/src/is-interactive.ts
- packages/wrangler/src/logger.ts
- packages/wrangler/src/utils/isAbortError.ts
- packages/wrangler/src/utils/onKeyPress.ts
Implements a React-free hotkeys implementation.
You can see both the implementations below – the React-free version with the `--x-dev-env` flag and the React/ink version with the flag:
I started with a simpler implementation in the [first commit](https://github.com/cloudflare/workers-sdk/commit/87c94c05646da58140563953e8af8098ca2e4622) but felt a higher-level API would allow for most consistency for other commands wanting to use hotkeys. The instructions printing logic has been moved inside the API and provides each handler with a `printInstructions` function if the handler wishes to reprint them.
UPDATE:
The instructions box now floats at the bottom (by making Wrangler's `Logger` and Miniflare's `Log` classes aware of a possible bottom float string). See image below for what it looks …
> React-free hotkeys implementation

- .changeset/poor-ads-poke.md
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/pages/dev.ts
The watch mode in `pages dev` for Advanced Mode projects is currently partially broken, as it only watches for changes in the `_worker.js` file, but not for changes in any of its imported dependencies. This means that given the following `_worker.js` file
```
import { graham } from "./graham-the-dog";
fetch(request, env) {
return new Response(graham)
}
}
```
`pages dev` will reload for any changes in the `_worker.js` file itself, but not for any changes in `graham-the-dog.js`, which is its dependency.
Similarly, `pages dev` will not reload for any changes in non-JS module imports, such as wasm/html/binary module imports.
This commit addresses all the aforementioned issues.
Fixes #4824
Our original solution was implemented using esbuild's `watch` mode (see …
> fix(wrangler): Fix `pages dev` watch mode [_worker.js]

- .changeset/plenty-chicken-study.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.ctx.test.ts
- packages/wrangler/src/api/integrations/platform/executionContext.ts
in workerd detaching the `waitUntil` and `passThroughOnException` methods from the `ExecutionContext`
object results in them throwing `illegal invocation` errors, such as for example:
```js
async fetch(_request, _env, { waitUntil }) {
waitUntil(() => {}); // <-- throws an illegal invocation error
return new Response("Hello World!");
},
};
```
this PR makes sure that the same behavior is applied to the `ctx` object returned by `getPlatformProxy`
To test it simply use the prerelease and try destructuring and calling the methods of the `getPlatformProxy`'s`ctx` object 
- Tests
- …
> [wrangler] fix: make sure `getPlatformProxy`'s `ctx` methods throw illegal invocation errors like workerd

- pnpm-lock.yaml
- templates/examples/qr-code-generator/.editorconfig
- templates/examples/qr-code-generator/.gitignore
- templates/examples/qr-code-generator/.prettierrc
- templates/examples/qr-code-generator/package.json
- templates/examples/qr-code-generator/src/worker.js
- templates/examples/qr-code-generator/src/worker.ts
- templates/examples/qr-code-generator/tsconfig.json
- templates/examples/qr-code-generator/wrangler.toml
Add a QR Code Source code to examples directory
- https://github.com/cloudflare/cloudflare-docs/pull/9414
> [Templates]: Add QR Code Generator to Examples

- .github/ISSUE_TEMPLATE/bug-template.yaml
More clearly spell out `npm create cloudflare` — the command people typed — rather than just referring to this as "C3"
> Clarify what C3 is in bug template

- .changeset/stupid-beans-joke.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/triggers/deploy.ts
When deploying a Worker that has a queue consumer, we make a POST request to set it up that uses the Worker name.
Unfortunately we were not taking into account the command line script-name arg in this request, which causes a problem when there is a mismatch between the wrangler.toml name and command line arg name.
- Tests
> fix: use cli script-name arg when deploying a worker with queue consumers

- .changeset/happy-mirrors-worry.md
- packages/wrangler/src/deployment-bundle/guess-worker-format.ts
Refs https://github.com/cloudflare/python-workers-examples/issues/11.
Added a sentence to the standard Python Workers warning, so that anyone using `wrangler dev` gets a warning about Python Workers with a requirements.txt not being deployable.
- Tests
> Add warning about deploying Python with requirements.txt

- .changeset/fair-actors-appear.md
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
Adds `durationMs` and `sourceMapSize` properties to the `deploy worker script` metrics event as well as sending the event after the deploy request. This PR can be tested by deploying a Worker using wrangler built from this PR and checking internal tools.
Fixes WP-996
- Tests
> chore: add upload duration and sourcemap size to metrics

- .changeset/happy-mirrors-worry.md
- .changeset/honest-bulldogs-mix.md
- .changeset/purple-ligers-own.md
> fix: Fix changesets with incorrect message format

- packages/wrangler/src/__tests__/rollback.test.ts
- packages/wrangler/src/versions/rollback/index.ts
Addressing product copy changes
(FYI: This PR is good to merge if a release is going out - just keeping open if product want further changes)
- Tests
> Minor copy change in rollback

- packages/create-cloudflare/templates/next/README.md
- packages/create-cloudflare/templates/next/c3.ts
Fixes #6094
There are other links with this format mentioned in #6094. But this PR only addresses links to resources I was actively using. These two files would seem to benefit from this update.
- Tests
> Update blob/<commit-hash> links to blob/main.

- packages/wrangler/src/cli-hotkeys.ts
This PR contains two implementations for multiline hotkey instructions which will display when the boxed, single-line hotkey instructions do not fit on the screen without wrapping.
First implementation (checkout commit e138fd3508f13f0805ffeb5048595bec9be3eba2 to test):
Second implementation (use PR prerelease to test):
Multiline unboxed 
- Tests
> Multiline hotkeys

- packages/wrangler/src/generate/index.ts
**Before**
**After**
Fixes #6222
- Tests
> fix(wrangler): Make `wrangler generate` deprecation warning more user-friendly

- .changeset/nervous-eyes-fetch.md
- packages/wrangler/src/__tests__/cloudchamber/create.test.ts
- packages/wrangler/src/cloudchamber/common.ts
`wrangler.js cloudchamber create --image whatever.com --json`
spits
`[object Object]`
With this change it spits:
`{"error":"location is required but it's not passed as an argument"}`
- Tests
> wrangler cloudchamber: fix --json flags when required fields for it to work are not passed

- .changeset/lovely-teachers-breathe.md
- packages/wrangler/src/__tests__/d1/export.test.ts
- packages/wrangler/src/d1/execute.tsx
- packages/wrangler/src/d1/export.ts
- packages/wrangler/src/d1/types.ts
Internal API change for D1 import/export. 
- Tests
> D1 export api change

- .changeset/thick-moons-call.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/templates.ts
At the moment, users are not able to create an application with a GitHub URL if it is inside a subdirectory, e.g. https://github.com/cloudflare/workers-sdk/tree/main/templates/worker-router
This PR fixes it by transforming the URL to the shorthand format. Note: This only address templates on the main branch as a branch name might includes slashes that span multiple segments in the URL.  
- Tests
> fix(create-cloudflare):  support GitHub URL with subdirectory

- .changeset/olive-walls-shake.md
- packages/wrangler/src/user/user.ts
Further debgging for https://github.com/cloudflare/workers-sdk/issues/3672. This PR adds the Ray ID to the error message printed by Wrangler, which can help when diagnosing these kinds of issues.
- Tests
> Add RayID to `wrangler login` debug message

- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev.tsx
This PR changes the copy for `assets` and `legacy-assets` flags & config keys from `We are going to be changing its behavior on August 15th.` to `We are going to be changing its behavior after August 15th.`
- Tests
> fix: Update copy for assets/legacy-assets flag and config key

- .changeset/rare-forks-fly.md
- packages/wrangler/src/__tests__/d1/execute.test.ts
- packages/wrangler/src/__tests__/d1/export.test.ts
- packages/wrangler/src/__tests__/d1/info.test.ts
- packages/wrangler/src/__tests__/d1/migrate.test.ts
- packages/wrangler/src/__tests__/d1/timeTravel.test.ts
- packages/wrangler/src/__tests__/delete.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/__tests__/helpers/write-wrangler-toml.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
- packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
- packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
- packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
- packages/wrangler/src/__tests__/versions/secrets/list.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/__tests__/versions/versions.list.test.ts
- packages/wrangler/src/__tests__/versions/versions.view.test.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/config/index.ts
This PR adds support for `wrangler.jsonc` config file, behind the same `--experimental-json-config` flag as `wrangler.json` support.
Fixes #5437
- Tests
> feat(wrangler): Add support for `wrangler.jsonc`

- packages/wrangler/e2e/c3-integration.test.ts
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/helpers/command.ts
- packages/wrangler/e2e/helpers/read-until.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/e2e/vitest.config.mts
This PR changes e2e/dev-with-resources to use the same workerName for all of the tests in this suite in hopes of reducing flakes.
When creating a new worker, a `<workerName>.devprod-testing7928.workers.dev` subdomain is created. The platform API locks a database table for the zone (`devprod-testing7928.workers.dev`) while doing this.
Creating many workers in the same account/zone in quick succession can run up against the lock. This test suite runs sequentially so does not cause lock issues for itself, but we run into lock issues when multiple PRs have jobs running at the same time (or the same PR has the tests run across multiple OSes).
- Tests …
> Use the same workerName for all of the tests in e2e/dev-with-resources

- .changeset/lemon-items-type.md
- packages/wrangler/src/dev/miniflare.ts
We have some warnings in local mode dev when trying to use ai bindings / vectorize / cron, but they are printed every time the worker is started. This PR changes the warning to only be printed once per worker start.
- Tests
> fix: only warn about miniflare feature support (ai, vectorize, cron) once

- .changeset/gorgeous-readers-move.md
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/user/user.ts
When using any cloudchamber command this adds the cloudchamber scope, if not present, in addition to the existing scopes instead of replacing them.
Before this PR users had to re-auth when switching between cloudchamber/non-cloudchamber commands. This PR makes it so cloudchamber users only have to auth one additional time to add cloudchamber the cloudchamber scopes instead of every time they switch between cloudchamber/non-cloudchamber commands.
If the user isn't logged in and they run a cloudchamber command this also adds the defaultScopes + the cloudchamber scope as part of  that login.
- Tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changeset …
> Add cloudchamber scopes to existing scopes instead of replacing them

- .changeset/dirty-bobcats-tickle.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/experimental-assets.ts
Add an experimental asset config key and flag.
Doesn't really do anything yet but should have appropriate validation.
See [WC-2389](https://jira.cfdata.org/browse/WC-2389)
- Tests
> [wrangler] Add experimental assets config and flag

- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/experimental-assets.ts
This commit adds an extra validation rule for the `experimental_assets` config key, that should prevent `directory` brom being an empty string.
- Tests
> fix(wrangler): Add extra `experimental_assets` validation

- .github/actions/create-c3-docs-pr/action.yml
Attempt two to fix the release script, which keeps breaking the C3 diff PR generation.
(Previously we tried to update the upload action to v4; now we update the download action to v3.
> chore: downgrade the action to v3 for reading artifacts

- .changeset/lazy-pens-approve.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/deploy/deploy.ts
Adds a log for worker startup time as per EW-8590.
- Tests
> Log worker script startup time

- .changeset/proud-chefs-count.md
- fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
- packages/vitest-pool-workers/src/worker/fetch-mock.ts
> fix: ensure that mocked fetch responses have a valid URL property

- .changeset/flat-bears-scream.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/local-mode-tests/tests/module.test.ts
- packages/wrangler/src/dev/start-server.ts
This PR includes changes to fixture tests (notoriously flakey fixtures: `get-platform-proxy`, `local-mode-tests`) to make them more stable, including:
- use `fileBasedRegistry: true` in `get-platform-proxy` (hypothesis: only flakey because of the dev registry)
- use `port: 0` in `local-mode-tests` module.test.ts
- ensure `unstable_dev` cleans up `local-mode-tests` logging.test.ts (which expects it to fail – this may have affected other tests running after)
- Tests
> try improve fixture flakiness due to unstable_dev

- .changeset/polite-dodos-happen.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/workers/rpc-worker/index.ts
- packages/miniflare/src/workers/core/proxy.worker.ts
- packages/miniflare/test/index.spec.ts
Fixes #6285
Fixes the first point of #6235
- Tests
___
As part of https://github.com/cloudflare/workers-sdk/pull/5922 I've removed the code that we had (implemented by @penalosa) that dropped the problematic `dispose` and `asyncDispose` properties from `RpcProperty`s (see [here](https://github.com/cloudflare/workers-sdk/blob/c9f081ab72142060a3cf2e9a7ef4546b8014b210/packages/miniflare/src/workers/core/proxy.worker.ts#L271)), as I thought that such operations were no longer necessary (and there were no tests showing that removing them was breaking something) but it turns …
> fix: allow `getPlatformProxy` to handle RPC calls returning objects

- .github/workflows/prerelease-workflows.yml
This adds a GitHub Action to deploy the (experimental and work in progress) https://github.com/cloudflare/workers-sdk/pull/6372 PR to a named npm release tagged `workflows`
> Push workflows branch to npm

- .changeset/slimy-mangos-punch.md
- packages/create-cloudflare/src/__tests__/git.test.ts
- packages/create-cloudflare/src/git.ts
Currently in C3 if someone has git installed but not properly configured, C3 will simply skip
the git initialization, a more clear workflow would be to actually still offer git but warn (and skip it)
in case they don't have it properly configured, that's what this PR is introducing:
> [!NOTE]
> This is quite an edge case for people not too accustomed with git, and it unlikely to effect most C3 users
- Tests
> fix(C3): make sure to always warn developers trying to use git when their git instance is not properly configured

- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/secrets/index.ts
Updating the copy merged in https://github.com/cloudflare/workers-sdk/pull/6379 which has not been released yet so no ned for a changeset
- Tests
> Update Workers Sites/Legacy Assets error message in versions commands

- .changeset/orange-icons-build.md
- fixtures/workers-with-assets/README.md
- fixtures/workers-with-assets/package.json
- fixtures/workers-with-assets/public/index.html
- fixtures/workers-with-assets/tests/index.test.ts
- fixtures/workers-with-assets/tests/tsconfig.json
- fixtures/workers-with-assets/tsconfig.json
- fixtures/workers-with-assets/wrangler.toml
- packages/workers-shared/README.md
- packages/workers-shared/asset-server-worker/README.md
- packages/workers-shared/asset-server-worker/src/index.ts
- packages/workers-shared/asset-server-worker/wrangler.toml
- packages/workers-shared/package.json
- packages/workers-shared/turbo.json
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/templates/no-op-assets-worker.ts
- pnpm-lock.yaml
**[Workers + Assets]**
This PR includes work needed to add Assets support for Workers 🚀 
**Architecture Diagram**
Based on the above diagram, this PR does the following:
- creates a new package called `workers-shared` that will host the Asset Server Worker and Router Worker
- scaffolds the Asset Server Worker in some very basic form, with basic configuration. Further behaviour implementation will follow in a subsequent PR
- does the ground work of plumbing ASW into miniflare
These changes are supported by both `wrangler dev` and `wrangler dev --x-dev-env` 💅 ...
Fixes WC-2423
🐙 Please review per commit 🐙
- Tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTI …
> feat: Create very basic Asset Worker and plumb it into `wrangler dev`

- tools/deployments/__tests__/validate-changesets.test.ts
It looks like one test in `./tools` start failing because of the new package `@cloudflare/workers-shared` introduced in #6370 recently. This PR should fix the issue.
- Tests
> chore: update package names

- .github/workflows/prereleases.yml
- packages/workers-shared/.eslintrc.js
- packages/workers-shared/asset-server-worker/src/index.ts
- packages/workers-shared/package.json
- packages/workers-shared/tsconfig.json
- pnpm-lock.yaml
This PR properly sets up the `workers-shared` project, by putting the necessary linting, TS compilation, and
`package.json` configuration in place. It also enables `@beta` prereleases for `workers-shared`
- Tests
> chore(workers-shared): Project configuration and beta prereleases

- .changeset/dry-cobras-smash.md
- fixtures/vitest-pool-workers-examples/internal-module-resolution/README.md
- fixtures/vitest-pool-workers-examples/internal-module-resolution/test/index.d.ts
- fixtures/vitest-pool-workers-examples/internal-module-resolution/test/index.spec.ts
- fixtures/vitest-pool-workers-examples/internal-module-resolution/test/tsconfig.json
- fixtures/vitest-pool-workers-examples/internal-module-resolution/tsconfig.json
- fixtures/vitest-pool-workers-examples/internal-module-resolution/vendor/ext-dep/index.js
- fixtures/vitest-pool-workers-examples/internal-module-resolution/vendor/ext-dep/package.json
- fixtures/vitest-pool-workers-examples/internal-module-resolution/vendor/ext-dep/subfolder/index.js
- fixtures/vitest-pool-workers-examples/internal-module-resolution/vitest.config.ts
- fixtures/vitest-pool-workers-examples/internal-module-resolution/wrangler.toml
- fixtures/vitest-pool-workers-examples/package.json
- packages/vitest-pool-workers/src/pool/module-fallback.ts
- pnpm-lock.yaml
Fixes #6406
The build from this PR should fix the reproduction here: https://github.com/hansottowirtz/workers-sdk-index-js-require-repro.
- Tests
> fix: ensure that directory imports in commonjs modules get resolved to their index file

- .github/workflows/c3-e2e.yml
Our release job ("Handle Changesets") always fails on its last step because there are no C3 diffs artifacts to download.
We only want to create those artifacts in a single e2e test run (the pnpm + ubuntu one) so there is a check in that e2e CI job.
Unfortunately the check was wrong, since we converted the `pm` matrix value from a string (e.g. "pnpm") to an object (e.g. `{name: "pnpm", version: "9.1.3"}`).
> ci: [C3] ensure that  is true on the pnpm ubuntu C3 e2e test run

- .github/workflows/changesets.yml
Although we now do upload C3 diffs during e2e tests, those tests only run if there was a change to the c3 package.
So we also should avoid trying to download them if c3 is not being deployed in the release.
- Tests
> ci: only try to download c3 diff artifacts, during the release job, if the C3 package was actually deployed

- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/experimental-assets.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/secrets/index.ts
- packages/wrangler/src/versions/upload.ts
[WC-2460](https://jira.cfdata.org/browse/WC-2460) - handle versions upload in the same way as deploy
- Tests
> feat(wrangler) - add assets to versions upload

- packages/wrangler/e2e/dev-env.test.ts
- packages/wrangler/e2e/startWorker.test.ts
Update e2e tests to use startWorker directly instead of DevEnv.startWorker
startWorker is the public interface whereas DevEnv provides access to internals (controllers) for advanced use-cases with APIs that we will iterate on and do not want to commit to yet.
- Tests
> Update e2e tests to use startWorker directly

- packages/wrangler/e2e/c3-integration.test.ts
We updated the message on c3 in #6412 and break the wrangler init test due to an unnecessary assertion against the output message. 
- Tests
> chore(create-cloudflare): remove unnecessary assertion in wrangler init test

- .changeset/thick-hairs-notice.md
- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/__tests__/vectorize/vectorize.upsert.test.ts
- packages/wrangler/src/vectorize/client.ts
- packages/wrangler/src/vectorize/common.ts
- packages/wrangler/src/vectorize/create.tsx
- packages/wrangler/src/vectorize/createMetadataIndex.ts
- packages/wrangler/src/vectorize/delete.ts
- packages/wrangler/src/vectorize/deleteByIds.ts
- packages/wrangler/src/vectorize/deleteMetadataIndex.ts
- packages/wrangler/src/vectorize/getByIds.ts
- packages/wrangler/src/vectorize/index.ts
- packages/wrangler/src/vectorize/info.ts
- packages/wrangler/src/vectorize/insert.ts
- packages/wrangler/src/vectorize/list.ts
- packages/wrangler/src/vectorize/listMetadataIndex.ts
- packages/wrangler/src/vectorize/query.ts
- packages/wrangler/src/vectorize/types.ts
- packages/wrangler/src/vectorize/upsert.ts
Enables users to operate on Vectorize V2 operations via wrangler.
Fixes #[VS-197].
- Tests
- [] TODO (before merge)
- [x ] Cloudflare docs PR(s): https://github.com/cloudflare/cloudflare-docs/pull/15916
> VS-197: Enable wrangler to interact with Vectorize V2 indexes

- .changeset/serious-walls-laugh.md
- packages/wrangler/src/d1/insights.ts
- packages/wrangler/src/d1/types.ts
This PR adds query efficiency to the `d1 insights` output.
- Tests
> [D1] add queryEfficiency to d1 insights output

- packages/wrangler/e2e/versions.test.ts
This e2e will be unstable while AUS is still being developed. To prevent this from blocking other work, it's been commented out until AUS is complete/stable.
- Tests
> fix(wrangler) - remove e2e for `versions upload --experimental-assets`

- .changeset/spicy-adults-thank.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/startWorker.test.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
Fixes #5297 
TODO:
Regression test can be seen failing here https://github.com/cloudflare/workers-sdk/actions/runs/10324844174/job/28585175390?pr=6424#step:6:322
You can see the test failing and then passing in this screencast:
https://github.com/user-attachments/assets/e718a39c-b506-43d9-9c57-e23aa7cfcab3
- Tests
> add "increase_websocket_message_size" compat flag to `InspectorProxyWorker`

- .changeset/angry-steaks-wait.md
- packages/wrangler/src/d1/insights.ts
BREAKING CHANGE: This PR renames --count to --limit in the `d1 insights` command to improve clarity and conform to naming conventions.
- Tests
> [D1] Rename --count to --limit in wrangler insights

- .changeset/angry-steaks-wait.md
- .changeset/honest-deers-work.md
- .changeset/long-buttons-help.md
- .changeset/shaggy-insects-jam.md
Fix incorrect type of change in changesets, from `patch` to `minor`
- Tests
> Fix incorrect type of change in changesets

- .changeset/tidy-berries-type.md
- packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
> reimplement module aliasing with esbuild plugin

- .changeset/odd-steaks-change.md
- packages/wrangler/src/dev/local.tsx
> fix: add a helpful message on Windows when Miniflare fails to start

- .changeset/eight-terms-beg.md
- fixtures/workers-with-assets/public/about/index.html
- fixtures/workers-with-assets/public/index.html
- fixtures/workers-with-assets/tests/index.test.ts
- packages/miniflare/README.md
- packages/miniflare/src/plugins/kv/assets.ts
- packages/miniflare/src/plugins/kv/index.ts
- packages/miniflare/src/workers/kv/assets.worker.ts
- packages/miniflare/src/workers/kv/constants.ts
- packages/miniflare/test/fixtures/assets/worker-with-custom-assets-bindings.ts
- packages/miniflare/test/fixtures/assets/worker-with-default-assets-bindings.ts
- packages/miniflare/test/plugins/kv/assets.spec.ts
- packages/workers-shared/asset-server-worker/src/assets-manifest-no-op.ts
- packages/workers-shared/asset-server-worker/src/assets-manifest.ts
- packages/workers-shared/asset-server-worker/src/index.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/experimental-assets.ts
This commit extends Miniflare's KV plugin's behaviour to support Workers assets, and therefore enables the emulation of Workers with assets in local development.
Fixes WC-2394
- Tests
> feat(miniflare): Implement KV/Assets plugin and Workers Assets simulator

- packages/vitest-pool-workers/test/global-setup.ts
`vitest-pool-workers` tests are failing on https://github.com/cloudflare/workers-sdk/pull/6490 due to 👇 
This is caused by that fact in that PR, the `workers-shared` version was  bumped to `0.2.0`, and `vitest-pool-workers` is trying to pull that package version from the registry.
This PR fixes the above issue, by having `vitest-pool-workers` use a local tarball of `workers-shared`, just like it does for `miniflare`, `wrangler`, etc.
- Tests
> fix: Add `workers-shared` override in vitest-pool-workers  global setup

- packages/wrangler/src/__tests__/cloudchamber/create.test.ts
- packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/cloudchamber/create.ts
- packages/wrangler/src/cloudchamber/modify.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
This PR adds support for "image", "location", and "ipv4" values in wrangler.toml, so a CLI user does not have to specify these options via an --args flag or interactive CLI command.
- Tests
> Adds image, location, and ipv4 to cloudchamber config

- packages/wrangler/e2e/dev.test.ts
The python remote dev tests consistently flakey due to timeouts. This PR removes those variations but keeps the local dev variations.
- Tests
> skip python remote e2e tests

- packages/wrangler/e2e/startWorker.test.ts
- packages/wrangler/e2e/vitest.config.mts
- packages/wrangler/e2e/vitest.setup.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/templates/startDevWorker/ProxyWorker.ts
This is a follow-up to https://github.com/cloudflare/workers-sdk/pull/6124 and enables the same tests to be run in remote mode as well as local mode.
- Tests
> add remote-mode to startWorker e2e tests

- .changeset/tasty-mayflies-march.md
- .vscode/settings.json
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- pnpm-lock.yaml
Replaces #6471, which was too verbose.
Fixes #6170
- Tests
> fix: move the Windows C++ redistributable warning so it is only shown if there is an actual access violation

- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/vectorize/query.ts
This commit enables yargs `example` support in wrangler (see https://yargs.js.org/docs/#api-reference-examplecmd1-desc1-cmd2-desc2), and adds one for `vectorize query`.
See https://github.com/cloudflare/workers-sdk/pull/6502#discussion_r1719416481 for context
- Tests
> feat(wrangler): Add support for examples in `--help`

- .changeset/smart-tomatoes-sell.md
- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/tests/index.test.ts
Part of https://jira.cfdata.org/browse/DEVX-1312
When sending raw HTTP requests to the playground & quick edit, we'd previously been passing along the headers that the user specified directly in the request to the proxy. This meant that some headers were instead being interpreted by the browser/proxy rather than being passed along to the user-worker (e.g. `Accept`). This change supports optionally prefixing headers with `cf-ew-raw-`, which will be stripped before being passed to the user worker. Followup PRs will add this prefixing to the playground & quick edit UI to take advantage.
- Tests …
> Optionally strip cf-ew-raw prefix

- CODEOWNERS
https://github.com/cloudflare/workers-sdk/pull/4176 removed the wrangler team from the C3 CODEOWNERS. The [reasoning](https://github.com/cloudflare/workers-sdk/pull/4176#pullrequestreview-1677317060) back then was that:
```
Requiring wrangler approvals for C3 changes is unnecessary at this point because the two projects are independent, 
so this requirement is unnecessarily coupling teams and slowing us down. I'm happy to discuss if anyone has a concern
about this change.
```
As per https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners however
so having both `@cloudflare/c3` and  `@cloudflare/wrangler` should not affect C3 team's ability to merge PRs without wrangler approval, but it will unblock the wrangler …
> chore: Add wrangler team to C3 CODEOWNERS

- .changeset/nice-pants-wash.md
- packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Followup to https://github.com/cloudflare/workers-sdk/pull/6458, part of https://jira.cfdata.org/browse/DEVX-1312. See https://github.com/cloudflare/wrangler2/blob/penalosa/shared-editor/packages/workers-playground/README.md for instructions on running the Playground locally to test this—the `Cookie` header is a good one to test with.
- Tests
> Prefix headers sent by the playground with `cf-ew-raw-`

- .changeset/soft-turtles-exercise.md
- packages/workers-playground/package.json
- packages/workers-playground/src/QuickEditor/MigrateToWrangler/DocsLink.tsx
- packages/workers-playground/src/QuickEditor/MigrateToWrangler/MigrateToWrangler.tsx
- packages/workers-playground/src/QuickEditor/MigrateToWrangler/StepNumber.tsx
- packages/workers-playground/src/QuickEditor/TabBar.tsx
- packages/workers-playground/src/QuickEditor/ToolsPane.tsx
- pnpm-lock.yaml
Fixes https://jira.cfdata.org/browse/DEVX-1311
Adds a tab to the workers playground which calls out the C3 flow for creating a worker
- Tests
> Add Wrangler CTA to the playground

- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
Prior to this, when you run the Wrangler tests you would find a directory (versions-upload-test-worker) and a couple of files (index.js and another.js) keep appearing.
> test: run version upload tests in a temp directory, rather than the wrangler package directory

- .changeset/empty-laws-prove.md
- packages/workers-shared/README.md
- packages/workers-shared/package.json
- packages/workers-shared/router-worker/README.md
- packages/workers-shared/router-worker/src/index.ts
- packages/workers-shared/router-worker/wrangler.toml
[WC-2556](https://jira.cfdata.org/browse/WC-2556)
Adds in basic router worker, but does not wire it up to anything (e.g. miniflare)
- Tests
> feat: add router worker to workers-shared

- .changeset/serious-eyes-admire.md
- packages/wrangler-devtools/patches/0015-Basic-support-for-Safari.patch
Potential fix for https://github.com/cloudflare/workers-sdk/issues/4737. Note that I haven't tested this myself, as I don't have an environment set up for wrangler-devtools -- feel free to modify this from draft->ready once tested.
Fixes #4737 
- Tests
> Fix CSP:script-src in 0015-Basic-support-for-Safari.patch (#4737)

- .changeset/three-months-work.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/templates.ts
Fixes [DEVX-1381](https://jira.cfdata.org/browse/DEVX-1381)
This PR renamed the "Demo Application" category to "Application Starter" on c3.
- Tests
> fix(create-cloudflare): rename category

- .changeset/tough-ligers-grab.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/log-build-output.ts
- packages/wrangler/src/dev/use-esbuild.ts
Make sure esbuild warnings are logged when running `wrangler deploy`. 
Fixes #4923
- Tests
> Make sure esbuild warnings are not hidden on deploy

- .changeset/lucky-points-remain.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/index.ts
> Show a clearer user error when trying to use a python worker without the `python_workers` compatibility flag specified

- .changeset/clean-rockets-decide.md
- fixtures/pages-functions-app/tests/index.test.ts
- packages/wrangler/src/dev.tsx
> chore: remove the warning about local mode flag being removed in the future

- .changeset/forty-taxis-live.md
- packages/quick-edit/functions/_middleware.ts
Fixes [DEVX-1306](https://jira.cfdata.org/browse/DEVX-1306).
This PR disables the autosave setting in vscode to avoid context reset without explicit user action.
- Tests
> fix(quick-edit): disable autosave

- .changeset/few-icons-refuse.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
> Prevent spaces in names

- packages/workers-shared/package.json
- packages/workers-shared/scripts/copy-config-file.ts
- packages/wrangler/src/dev/miniflare.ts
Wrangler has a dependency on `workers-shared`, specifically on the bundled Asset Worker [here](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/dev/miniflare.ts#L927), and the Asset Worker config file [here](https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/src/dev/miniflare.ts#L930). Currently the `wrangler.toml` file is not included in the `workers-shared` distribution, which results in that import failing with `Error: Cannot find module '@cloudflare/workers-shared/asset-server-worker/wrangler.toml'`.
This PR copies the config file to the distribution folder `dist`, so that wrangler can properly import it, and folks can test experimental assets with `wrangler dev`.
Note:
- currently this is broken only for `wrangler dev` with experimental …
> fix(workers-shared): Add asset-worker configuration file to `workers-shared` distribution

- .changeset/late-kings-peel.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/output.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/output.ts
- packages/wrangler/src/pages/deploy.tsx
- packages/wrangler/src/triggers/deploy.ts
Wrangler parts of https://github.com/cloudflare/workers-sdk/pull/6569, so that C3 can use the deployed Wrangler version with new features.
- Tests
> Add deployment HTTP targets to wrangler deploy output logs

- .changeset/green-lies-crash.md
- fixtures/nodejs-hybrid-app/wrangler.toml
- fixtures/pages-nodejs-v2-compat/wrangler.toml
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/api/pages/deploy.tsx
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/node-compat.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/type-generation/index.ts
- packages/wrangler/src/versions/upload.ts
- pnpm-lock.yaml
This PR builds on top and supersedes https://github.com/cloudflare/workers-sdk/pull/6545
Changes in this PR are in the[ last commit](https://github.com/cloudflare/workers-sdk/commit/510898e452cc4c68c6ac2369b62d27914e103e34) - the functionality stays the same but the code is re-organized.
```
Rename validateNodeCompat to getNodeCompatMode which is what the function does
Convert the parameters to optional options for better readability.
Added a `validateConfig` to be able to skip validation (used once in the code base).
The former getNodeCompatMode is now parseNodeCompatibilityFlags and is only responsible to return the compat flags and no more exported.
Improve the documentation
```
> fix: remove experimental: prefix requirement for nodejs_compat_v2

- .github/workflows/prereleases.yml
This PR adds a step in `prereleases.yaml` to deploy `miniflare@beta` to npm
- Tests
> chore: Publish miniflare@beta to npm

- .changeset/cool-crews-happen.md
- packages/prerelease-registry/functions/utils/getArtifactForWorkflowRun.ts
Support GH pre-release artifacts with just a `.vsix` file, as well as `.tgz` files
- Tests
> Support `.vsix` artifacts in pre-release registry

- .changeset/hungry-candles-knock.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- packages/wrangler/e2e/helpers/setup.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/dev.tsx
This PR implements watch mode for Workers with assets, more specifically:
- it watches the static assets directory for changes (add/delete files or directories)
- it reacts to config file changes and ensures we're still watching for the relevant asset directory
Fixes WC-2554
Clean commit history is caring 🫶  so pls review per commit
Beside e2e tests, these changes were also manually tested in the following scenarios:
**[`wrangler dev` | `wrangler dev --x-dev-env`]**
- add/remove files & directories in the assets directory
- change the assets folder in `wrangler.toml` + file changes in new assets directory + file changes in old assets directory to ensure it is not watched anymore
**[`wrangler dev --x-assets="dist"` | `wrangler dev --x-dev-env --x-assets="dist"`]**
- add/remove files & …
> feat(wrangler): watch mode for Workers + Assets

- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/versions/deployments/deployments.view.test.ts
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/versions/deployments/view.ts
- packages/wrangler/src/versions/secrets/bulk.ts
- packages/wrangler/src/versions/secrets/delete.ts
- packages/wrangler/src/versions/secrets/put.ts
- packages/wrangler/src/versions/upload.ts
Missed a few --x-versions and also moved the deployment creation in wrangler deploy over to the existing util function
- Tests
> Remove some missed --x-versions and move deploy to existing util function

- .changeset/funny-comics-lick.md
- .changeset/modern-scissors-relax.md
- packages/wrangler/e2e/README.md
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/versions/upload.ts
New feature - log version preview url when previews exist. This feature is currently restricted, but I'm adding wrangler support now to enable internal testing.
- Tests
> [wrangler] log version preview url when previews exist

- .changeset/friendly-brooms-brush.md
- packages/wrangler/src/__tests__/generate.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/environment-variables/misc-variables.ts
When `wrangler init` delegates to C3, it did so via `npm create cloudflare@2.5.0`. C3's v2.5.0 was the first to include auto-update support to avoid `npx`'s potentially stale cache. But this also guaranteed a double install for users who do not have 2.5.0 cached. Now, wrangler delegates via `npm create cloudflare@^2.5.0` which should use the latest version cached on the user's system or install and use the latest v2.x.x.
For more context, see https://github.com/cloudflare/workers-sdk/pull/6415#discussion_r1739312919
- Tests
> avoid potential double-install of create-cloudflare

- .changeset/real-cooks-argue.md
- packages/vitest-pool-workers/src/worker/lib/node/console.ts
- packages/vitest-pool-workers/test/console.test.ts
Fixes #5591.
This solution proxies all methods to a bound version of the same method. Another way to solve this could have been to manually write out each binding.
- Tests
> fix: ensure console methods are bound to instance

- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/worker.ts
> Add new_sqlite_classes migration for Durable Objects

- .changeset/khaki-brooms-matter.md
- packages/miniflare/src/plugins/assets/index.ts
Fixes reporting back just the 20k limit again.
- Tests
> Fix max asset count message

- .changeset/silly-ways-brake.md
- fixtures/nodejs-als-app/package.json
- fixtures/nodejs-als-app/src/index.ts
- fixtures/nodejs-als-app/tests/index.test.ts
- fixtures/nodejs-als-app/tests/tsconfig.json
- fixtures/nodejs-als-app/tsconfig.json
- fixtures/nodejs-als-app/turbo.json
- fixtures/nodejs-als-app/vitest.config.mts
- fixtures/nodejs-als-app/wrangler.toml
- packages/workers-shared/package.json
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts
- packages/wrangler/src/deployment-bundle/node-compat.ts
- pnpm-lock.yaml
> fix: don't warn about `node:async_hooks` if `nodejs_als` is set

- .changeset/new-dragons-bow.md
- packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
- packages/wrangler/src/cloudchamber/curl.ts
- packages/wrangler/src/cloudchamber/index.ts
Adds a cloudchamber curl command. Example usage:
`wrangler cloudchamber curl /ssh-public-keys`
[CC-3877](https://jira.cfdata.org/browse/CC-3877)
- Tests
> Add cloudchamber curl command

- packages/wrangler/src/__tests__/secret.test.ts
There is a difference in the Error message between different Node versions - this PR just tests the part of the error that we control to make it more robust.
Node v18.20.3:
```
[Error: The contents of "./secret.json" is not valid JSON: "ParseError: Unexpected token b"]
```
Node v:
```
[Error: The contents of "./secret.json" is not valid JSON: "SyntaxError: Unexpected token 'b', "bad file content" is not valid JSON"]
```
- Tests
> chore: fix test that fails locally

- package.json
- pnpm-lock.yaml
`capnp-ts` doesn't work with TS 5, so pin it to old an older version (this reverts a more recent change to pin it to TS 5)
- Tests
> Pin TS 4.2.4 for `capnp-ts`

- .changeset/gold-maps-itch.md
- .changeset/slimy-waves-dance.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/wrangler.toml
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/assets/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/d1/index.ts
- packages/miniflare/src/plugins/do/index.ts
- packages/miniflare/src/plugins/hyperdrive/index.ts
- packages/miniflare/src/plugins/kv/index.ts
- packages/miniflare/src/plugins/kv/sites.ts
- packages/miniflare/src/plugins/queues/index.ts
- packages/miniflare/src/plugins/r2/index.ts
- packages/miniflare/src/plugins/ratelimit/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/miniflare/test/plugins/hyperdrive/index.spec.ts
- packages/wrangler/e2e/get-platform-proxy.test.ts
This PR simply adds hyperdrive bindings support to Miniflare's `getBindings` and consequently to `getPlatformProxy`.
The hyperdrive proxies have overrides to make them usable within node.js, since the hyperdrive values can only work inside the workerd process itself.
- Tests
> enable hyperdrive bindings in `getPlatformProxy`

- .changeset/stupid-weeks-cheat.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/experimental-assets.ts
Uploads Workers Assets with multipart/form-data rather than JSON Lines. This is much easier for the asset upload service to deal with, and means we can now properly support large files/a large number of files.
- Tests
> Switch to multipart/form-data for Workers Assets upload

- .changeset/nasty-hats-rhyme.md
- .vscode/settings.json
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/experimental-assets.ts
- packages/wrangler/src/sites.ts
- packages/wrangler/src/utils/filesystem.ts
> feat: experimental workers assets can be ignored by adding a .assetsignore file

- .github/workflows/changesets.yml
- packages/workers-shared/asset-worker/README.md
- packages/workers-shared/asset-worker/wrangler.toml
- packages/workers-shared/package.json
Configure GitHub Actions to deploy Asset Worker
- Tests
> Configure GitHub Actions to deploy Asset Worker

- .changeset/lazy-poems-mate.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/triggers/index.ts
Fixes [WC-2484](https://jira.cfdata.org/browse/WC-2484).
Also now errors if invalid route config is present in `wrangler dev`. 
- Tests
> fix(wrangler): validate routes in dev and deploy

- .changeset/eighty-birds-kiss.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/asset-server/handler.ts
> Fix Pages duplicating hash in redirects

- .changeset/angry-keys-dance.md
- .prettierignore
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/api/startDevWorker/utils.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/versions/upload.ts
Supersedes #6641 from @oliy.
- Tests
> Add pipeline binding to wrangler.toml

- packages/workers-shared/asset-worker/wrangler.toml
- packages/workers-shared/package.json
- packages/workers-shared/router-worker/README.md
- packages/workers-shared/router-worker/wrangler.toml
Will conflict at `packages/workers-shared/package.json#scripts.deploy` with https://github.com/cloudflare/workers-sdk/pull/6542
- Tests
> Configure GitHub Actions to deploy Router Worker

- fixtures/external-durable-objects-app/tests/index.test.ts
> Disable external-durable-objects-app fixture tests

- .changeset/smooth-bananas-obey.md
- packages/wrangler/src/r2/helpers.ts
Updates the fields parsed and displayed in wrangler from the R2 Event Notification PUT payload from the Cloudflare API.
- Tests
> Not including detail id in wrangler output from R2 event notifications

- .changeset/lazy-jeans-kick.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/notification.ts
Updates the R2 Event Notification DELETE payload to the Cloudflare API to be able to specify rules within a config to delete.
- Tests
> Adding argument to specify rule to delete if don't want to delete every rule in config

- .changeset/lovely-pigs-bow.md
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/versions/secrets/index.ts
Persists Workers Assets across `wrangler versions secrets put/bulk`.
- Tests
> Fix wrangler version secrets with Assets

- .changeset/lovely-experts-double.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/do/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/miniflare/src/runtime/config/workerd.capnp
- packages/miniflare/src/runtime/config/workerd.capnp.d.ts
- packages/miniflare/src/runtime/config/workerd.capnp.js
- packages/miniflare/src/runtime/config/workerd.ts
- packages/miniflare/src/shared/error.ts
- packages/miniflare/test/plugins/do/index.spec.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/start-server.ts
- pnpm-lock.yaml
> Inject latest Durable Object migration state into Miniflare

- .github/pull_request_template.md
- .prettierignore
Just getting rid of that tiny bit of friction.
- Tests
> Adds spaces in the GitHub PR template for easier excuse writing

- .changeset/sixty-bottles-care.md
- packages/vitest-pool-workers/src/worker/lib/node/url.ts
This aligns our code with the best practice added to the node.js runtime recently.
See https://github.com/nodejs/node/commit/7196946d7f59652c19dec278186165806b1e28ad
- Tests
> fix: minor performance improvement to the url polyfill used by the vitest integration

- .changeset/bright-radios-fail.md
- .github/workflows/deploy-pages-previews.yml
- packages/quick-edit-extension/scripts/bundle.ts
- packages/quick-edit/README.md
- packages/quick-edit/build.sh
- packages/quick-edit/package.json
- packages/quick-edit/setup.sh
Fixes [DEVX-1404](https://jira.cfdata.org/browse/DEVX-1404)
Our quick editor depends on Vscode with a restriction on installation with yarn only. However, this conflict with our packageManager settings which points to pnpm. This updates both the setup and build script to make sure vscode is happy when we run `pnpm run deploy`.
The `Deploy Pages Previews` job proves that `pnpm run deploy` works now. So it should be safe to say that our deploy script that runs `pnpm run deploy` will work too. 👍🏼 
- Tests
> chore(quick-edit): run setup and custom-build script before deploy

- fixtures/nodejs-hybrid-app/src/index.ts
- pnpm-lock.yaml
Simply adds a test case to the node.js compatibility fixture.
- Tests
> test: add nodejs_compat_v2 test for equivalence of getRandomValues

- fixtures/workers-with-assets-only/wrangler.toml
Super quick followup to https://github.com/cloudflare/workers-sdk/pull/6631 where I forgot to remove some outdated config options from the wrangler.toml in the assets-only fixture.
Fixes #000?
- Tests
> remove outdated config options

- .changeset/soft-beans-explode.md
- fixtures/asset-config/package.json
- fixtures/asset-config/vitest.config.ts
- fixtures/local-mode-tests/tests/logging.test.ts
- fixtures/vitest-pool-workers-examples/package.json
- fixtures/vitest-pool-workers-examples/vitest.workers.config.ts
- package.json
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/miniflare/src/index.ts
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/src/config/index.ts
- packages/vitest-pool-workers/src/pool/config.ts
- packages/vitest-pool-workers/src/pool/index.ts
- packages/vitest-pool-workers/src/pool/module-fallback.ts
- packages/vitest-pool-workers/src/worker/lib/cloudflare/test-runner.ts
- packages/vitest-pool-workers/src/worker/lib/node/fs.ts
- packages/vitest-pool-workers/test/console.test.ts
- packages/vitest-pool-workers/test/global-setup.ts
- packages/workers-shared/package.json
- packages/workers.new/package.json
- packages/workers.new/tests/vitest.config.mts
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/vitest.setup.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
- tools/dependabot/__tests__/generate-dependabot-pr-changesets.test.ts
> Upgrade `@cloudflare/vitest-pool-workers` to Vitest v2+

- package.json
- packages/devprod-status-bot/package.json
- packages/edge-preview-authenticated-proxy/package.json
- packages/format-errors/package.json
- packages/playground-preview-worker/package.json
- packages/prerelease-registry/package.json
- packages/quick-edit/package.json
- packages/turbo-r2-archive/package.json
- packages/workers-playground/package.json
- packages/workers-shared/package.json
- packages/workers.new/package.json
- packages/wrangler-devtools/package.json
- pnpm-lock.yaml
- tools/deployments/__tests__/deploy-non-npm-packages.test.ts
- tools/deployments/deploy-non-npm-packages.ts
workers-shared is the only non-private and deployable package. And it was skipped in the last release because of this check.
- Tests
> Allow CI deploying non-private packages

- .github/actions/install-dependencies/action.yml
- .github/workflows/c3-e2e-dependabot.yml
- .github/workflows/c3-e2e-quarantine.yml
- .github/workflows/c3-e2e.yml
- package.json
Fixes N/A
We added [pnpm catalogs](https://pnpm.io/catalogs) recently, which are only supported in `pnpm@^9.5`. This caused changesets to fail when running `pnpm i --frozen-lockfile`: https://github.com/cloudflare/workers-sdk/actions/runs/10853200996/job/30120963322
- Tests
> Bump `pnpm` 9.1.3 -> 9.10.0 to support catalogs

- .changeset/stupid-dogs-hear.md
- package.json
- packages/workers-shared/asset-worker/wrangler.toml
- packages/workers-shared/router-worker/wrangler.toml
- pnpm-lock.yaml
Fixes router-worker and asset-worker in prod (they expect these config bindings)
- Tests
> Add missing config params to router-worker and asset-worker

- tools/deployments/__tests__/validate-pr-description.test.ts
- tools/deployments/validate-pr-description.ts
> Add `Fixes N/A` as an option to Pr description validation

- .changeset/nervous-days-greet.md
- fixtures/asset-config/vitest.config.ts
- fixtures/vitest-pool-workers-examples/vitest.workers.config.ts
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/src/config/index.ts
- packages/vitest-pool-workers/src/pool/config.ts
- packages/vitest-pool-workers/src/pool/index.ts
- packages/workers.new/tests/vitest.config.mts
- packages/wrangler/src/__tests__/cloudchamber/create.test.ts
- packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Adds support for Vitest 2.1.x, and bumps create-cloudflare templates to pull the new version. No code changes required my testing, so this is primarily just extending the supported version range.
I fixed up a few tests now that Vitest doesn't allow `toMatchInlineSnapshot` being called multiple times, but I'm not sure why the cloudchamber tests are failing.
Fixes #6717
- Tests
> feat: add support for vitest 2.1.x

- .changeset/gorgeous-eagles-matter.md
- packages/wrangler/package.json
- pnpm-lock.yaml
Yesterday, a backport for the fix of a redos in path-to-regexp was published.
PR of path-to-regexp fix: https://github.com/pillarjs/path-to-regexp/pull/324 - the advisory database wasn't updated yet, so it might take a while before warnings go away.
Alternatively, path-to-regexp could be updated to `^8.1.0`, but there are a fair amount of changes between v6 and (v7 and) v8.
Fixes #6720 
- Tests
> Bump path-to-regexp to 6.3.0

- .changeset/blue-bags-walk.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/notification.ts
Updating body for [R2-2457](https://jira.cfdata.org/browse/R2-2457)
Fixes N/A
- Tests
- [] TODO (before merge):
> Making explicit that if a body is sent to delete event notification config rules it is sent with an array of ruleIds

- .changeset/six-buses-matter.md
Fixes #6731.
We need a changeset for quick-edit to deploy the changes made on the quick edit extension.
- Tests
> chore: add missing changeset to deploy quick-edit

- .changeset/cool-beans-applaud.md
- packages/miniflare/src/index.ts
- packages/miniflare/test/plugins/queues/index.spec.ts
PR #5570 introduced a regression in Miniflare, namely that declaring Queue Producers like 
```
queueProducers: { "MY_QUEUE": "my-queue" }
```
no longer works. This PR restores balance in the Miniflare + Queues Universe 🪐 
Possibly addresses  #5908
- Tests
> fix(miniflare): Fix regression introduced in #5570

- .changeset/fresh-ravens-pull.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/experimental-assets.ts
- packages/wrangler/src/versions/index.ts
Tail Workers are currently not supported for Workers with assets. This commit ensures we throw the corresponding error if users are attempting to configure `tail_consumers` via their configuration file, for a Worker with assets. This validation is applied for all `wrangler dev`, `wrangler deploy`, `wrangler versions upload`.
Fixes [WC-2711](https://jira.cfdata.org/browse/WC-2711)
- Tests
> fix: Throw error when attempting to configure Workers with assets and tail consumers

- .changeset/moody-kangaroos-allow.md
- packages/wrangler/src/experimental-assets.ts
- pnpm-lock.yaml
Count globally rather than resetting with the count with each bucket.
- Tests
> Fix assets upload message

- .changeset/few-feet-appear.md
- .changeset/spotty-snails-design.md
- packages/create-cloudflare/src/frameworks/package.json
- packages/create-cloudflare/templates-experimental/qwik/c3.ts
- packages/create-cloudflare/templates/qwik/c3.ts
- packages/create-cloudflare/templates/qwik/templates/wrangler.toml
This PR bumps the create-qwik version to `1.9.0`
It also adds the missing `nodejs_compat` flag needed by the qwik starter template
Fixes N/A
- Tests
> C3: bump qwik to `1.9.0`

- .github/workflows/test-and-check.yml
- packages/workers-shared/package.json
- packages/workers.new/package.json
Fixes N/A.
This stops ci tests from running vitest in watch mode and reduce the github action timeout time to 30mins.
- Tests
> chore: stop ci test from running vitest in watch mode

- .changeset/old-mugs-begin.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/versions/api.ts
Changes the deploy behavior deploys using the new versions API to disable observability if it isn't explicitly defined in the user's `wrangler.toml`. This behaves differently from how `logpush` and `tail_consumers` work, where they must be explicitly removed, but we decided that this PR's behavior matches user expectations better.
Fixes [WO-186](https://jira.cfdata.org/browse/WO-186)
- Tests
> fix: disable observability on deploy if not explicitly defined in config

- .changeset/fresh-worms-knock.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/experimental-assets.ts
Fixes [WC-2726](https://jira.cfdata.org/browse/WC-2726)
- Tests
> fix: error if a user inadvertently uploads a Pages `_workers.js` file or directory as an asset

- .changeset/hot-poems-march.md
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/experimental-assets.ts
Workers + Assets are currently supported only in local mode. We should throw an error if users attempt to use Workers with assets in remote mode.
Fixes [WC-2743](https://jira.cfdata.org/browse/WC-2743)
- Tests
> fix(wrangler): Error if Workers + Assets are run in remote mode

- .changeset/lucky-doors-jam.md
- fixtures/nodejs-hybrid-app/src/index.ts
- fixtures/nodejs-hybrid-app/tests/index.test.ts
- packages/wrangler/package.json
- pnpm-lock.yaml
Fixes https://github.com/cloudflare/workerd/issues/2720
By pulling in https://github.com/unjs/unenv/pull/310
Fixes N/A (the issue is on the worked repo)
- Tests
> chore: update unenv dependency version

- .changeset/serious-houses-film.md
- packages/wrangler/src/__tests__/match-tag.test.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/match-tag.ts
- packages/wrangler/src/versions/index.ts
> Update CI messaging

- .changeset/bright-guests-destroy.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/experimental-assets.ts
This commit fixes the current behaviour of watch mode for Workers with assets, and adds support for switching between static and dynamic Workers within a single `wrangler dev` session.
Fixes [WC-2721](https://jira.cfdata.org/browse/WC-2721)
- Tests
> fix(wrangler): Support switching between static and dynamic Workers

- .changeset/silly-birds-shout.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/experimental-assets.ts
- packages/wrangler/src/versions/index.ts
Fixes [WC-2744](https://jira.cfdata.org/browse/WC-2744)
- Tests
> fix: error when asset binding is provided without user worker

- .changeset/pink-months-promise.md
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Fixes #6735
Adds missing bindings to `init --from-dash`, as well as an `assertNever()` type check to ensure this list doesn't get out of sync in future
- Tests
> Add missing bindings to `init --from-dash`

- .changeset/gentle-goats-greet.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation.ts
Fixes N/A but please refer to https://github.com/cloudflare/workers-sdk/issues/2586 for the wider scope feat request
`wrangler dev`
`wrangler dev --env staging`
`wrangler dev --env production`
- Tests
> fix(wrangler): Validate additional config properties for `[observability]`

- .github/workflows/prereleases.yml
Fixes #6484 
This ensures that we have SPARROW_SOURCE_KEY set when building create-cloudflare for pre-release (beta).
- Tests
> chore(create-cloudflare): enable telemetry on beta

- .changeset/eight-emus-compete.md
- packages/wrangler/src/update-check.ts
Fixes N/A
I noticed that the `package.json` was bundled in `wrangler/wrangler-dist/cli.js`. I found that we can simplify the `package.json` import to prevent that from happening.
The `package.json` is used by the `check-update` dependency, but it only requires the `name` and `version` to detect updates: https://github.com/vercel/update-check/blob/4338e215c9d089f46c6edff45ba41941c070d39f/index.js#L169-L201. So we only need to import the name and version to satisfy it.
- Tests
> refactor: prevent bundling entire `package.json` in built code

- .changeset/many-years-nail.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/index.ts
Removes beta tag from event notifications wrangler commands.
Fixes N/A
- Tests
> Remove beta tag from r2 event notification wrangler commands

- .changeset/witty-eggs-reply.md
- packages/wrangler/CHANGELOG.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/node-compat.ts
- packages/wrangler/src/tail/filters.ts
- pnpm-lock.yaml
Note: This should not be merged until Sept 23, when nodejs_compat includes nodejs_compat_v2 functionality.
Fixes #6759
- Tests
> Improve node_compat warning for v2

- .changeset/brown-shoes-tease.md
- packages/create-cloudflare/templates-experimental/angular/c3.ts
- packages/create-cloudflare/templates-experimental/angular/templates/src/.assetsignore
- packages/create-cloudflare/templates-experimental/angular/templates/tools/alter-polyfills.mjs
- packages/create-cloudflare/templates-experimental/angular/templates/tools/copy-files.mjs
- packages/create-cloudflare/templates-experimental/angular/templates/tools/paths.mjs
- packages/create-cloudflare/templates-experimental/angular/templates/wrangler.toml
> fix: experimental Angular template using Workers with Assets was broken

- .changeset/chilled-clocks-add.md
- packages/create-cloudflare/templates-experimental/angular/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/astro/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/docusaurus/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/gatsby/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/hello-world-assets-only/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/js/wrangler.toml
- packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/ts/wrangler.toml
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/wrangler.toml
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/py/wrangler.toml
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/wrangler.toml
- packages/create-cloudflare/templates-experimental/nuxt/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/qwik/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/remix/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/solid/templates/wrangler.toml
- packages/create-cloudflare/templates-experimental/svelte/js/wrangler.toml
- packages/create-cloudflare/templates-experimental/svelte/ts/wrangler.toml
- packages/create-cloudflare/templates/common/js/wrangler.toml
- packages/create-cloudflare/templates/common/ts/wrangler.toml
- packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world-durable-object/ts/wrangler.toml
- packages/create-cloudflare/templates/hello-world/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world/py/wrangler.toml
- packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
- packages/create-cloudflare/templates/hono/templates/wrangler.toml
- packages/create-cloudflare/templates/openapi/ts/wrangler.toml
- packages/create-cloudflare/templates/queues/js/wrangler.toml
- packages/create-cloudflare/templates/queues/ts/wrangler.toml
- packages/create-cloudflare/templates/scheduled/js/wrangler.toml
- packages/create-cloudflare/templates/scheduled/ts/wrangler.toml
Adds Workers Observability to newly generated `create-cloudflare` projects.
Fixes [WO-198](https://jira.cfdata.org/browse/WO-198)
- Tests
> chore(create-cloudflare): enable observability for Workers templates

- packages/wrangler/e2e/helpers/normalize.ts
- packages/wrangler/e2e/versions.test.ts
Fixes mismatched snapshots
Version Preview URLs are now enabled. Wrangler already has code to print them to stdout if the property is on the api response. This PR simply updates our snapshots with their normalised form
- Tests
> fix version preview url snapshot

- .changeset/friendly-papayas-provide.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev.tsx
Fixes [WC-2757](https://jira.cfdata.org/browse/WC-2757)
- Tests
> fix(wrangler): Validate routes on config file changes

- .changeset/twelve-years-search.md
- packages/create-cloudflare/src/__tests__/metrics.test.ts
- packages/create-cloudflare/src/helpers/sparrow.ts
- packages/create-cloudflare/src/metrics.ts
Fixes N/A
This PR prevents the create-cloudflare cli from crashing by silently ignoring network errors during telemetry collection, (e.g. network error because of certificate issues)
- Tests
> fix(create-cloudflare): ignore network errors during telemetry collection

- .changeset/pretty-birds-scream.md
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/dev/dev.tsx
`wrangler dev --remote` still isn't supported (hopefully soon!), but Queues is not in beta anymore so we should remove that part of the message.
@jbw1991 @sdnts
> Queues is now GA so don't say it's in beta in warning messages

- .changeset/chilled-trainers-switch.md
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/utils/retry.ts
- packages/wrangler/src/versions/upload.ts
This PR adds retries within `wrangler deploy` and `wrangler versions upload` to workaround spotty network connections and service flakes
We need to be careful about retrying the whole multi-step process because of some non-atomic steps.
Users have reported flakes at the upload step so we can safely add retries for that step to address those specific failures.
Fixes #0000
- Tests
> Retry deployments

- .changeset/fuzzy-cows-camp.md
- packages/wrangler/scripts/deps.ts
Fixes N/A
This should resolve the issue presented in https://github.com/cloudflare/workers-sdk/pull/6866#issuecomment-2384484590 with local builds of Wrangler.
- Tests
> Fix local builds of Wrangler

- .changeset/eleven-planes-promise.md
- packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
- packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/dev.test.tsx
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/assets.ts
- packages/wrangler/src/dev-registry.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/create-worker-preview.ts
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/remote.tsx
- packages/wrangler/src/index.ts
Fixes [DEVX-1298](https://jira.cfdata.org/browse/DEVX-1298)
This PR updates the default value for `--x-dev-env` for `wrangler dev` (not yet for `wrangler pages dev`).
It also updates the e2e tests (which assumed the default value was false) to explicitly test with the flag on + off (TODO: need to update the snapshots because this changed the test names)
- Tests
> on by default: –x-dev-env

- .changeset/tasty-bears-behave.md
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/test/index.spec.js
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/test/index.spec.ts
> fix: remove invalid `ctx` import from hello-world experimental templates

- .changeset/perfect-experts-draw.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/cloudflare-internal.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
A common mistake is to forget to export from the entry-point of a Worker, which causes
Wrangler to infer that we are in "Service Worker" mode.
In this mode, imports to external modules are not allowed.
Currently this only fails at runtime, because our esbuild step converts these imports to an internal `__require()` call that throws an error.
The error message is misleading and does not help the user identify the cause of the problem.
This is particularly tricky where the external imports are added by a library or our own node.js polyfills.
Fixes #6648
- Tests
- Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md …
> fix: render a helpful build error if a Service Worker mode Worker has imports

- .changeset/popular-horses-hide.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation/index.ts
Fixes #6730
Handle more rule glob cases when generating `declare module "..." { }` types
- Tests
> Handle more module declaration cases

- .changeset/happy-balloons-work.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
Fixes #6876
Previously, if a `build.custom` command output files into the `assets.directory`, it caused the command to run again in an infinite loop.
This was caused by the assets watcher in the ConfigController to trigger a configUpdate event – with the intention of triggering a runtime reload – which caused the BundleController to trigger a full build.
The assets watcher has now been moved to the BundleController and triggers a bundleCompleted event instead – with the intention of triggering a runtime reload where Miniflare itself reads the new assets from the filesystem.
- Tests
- Public …
> fix assets + custom build = infinite loop

- .changeset/bright-deers-rescue.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/logger.ts
> Include serialised FormData in debug logs

- .github/actions/install-dependencies/action.yml
- .github/workflows/c3-e2e-dependabot.yml
- .github/workflows/c3-e2e-experimental.yml
- .github/workflows/c3-e2e-quarantine.yml
- .github/workflows/c3-e2e.yml
- package.json
Fixes #000.
Upgrades to pnpm 9.12.0
- Tests
> chore: upgrade to pnpm 9.12.0

- packages/wrangler/src/deployment-bundle/esbuild-plugins/cloudflare-internal.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
Fixes #0000
Sometimes caused a snapshot mismatch eg https://github.com/cloudflare/workers-sdk/actions/runs/11161082325/job/31022879309#step:5:1
Simple fix to ensure the order is deterministic
- Tests
> fix not-deterministic log message

- .changeset/grumpy-apples-juggle.md
- packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
While this does fix the problem (it's a one-liner) and I added a test to prevent a regression,
we have a systemic problem here because the types are too loose within the `ConfigController`.
One approach to fixing this is: rather than defining the `StartDevWorkerInput`, where all the props are optional, and then inferring the `StartDevWorkerOptions`, we should flip it round. Make the `StartDevWorkerOptions` tight (i.e. nothing can be optional, but explicitly can be `undefined` if needed). And then infer the `StartDevWorkerInput` from there by "picking" the desired properties and marking the type as `Partial<>`.
This would have created a typings error when the `alias` property was added to the config, and therefore indicate to the developer that it needs to be addressed here.
There may be a …
> fix: ensure that `alias` config gets passed through to the bundler when using new `--x-dev-env`

- .changeset/pretty-cherries-relate.md
- fixtures/vitest-pool-workers-examples/pages-with-config/README.md
- fixtures/vitest-pool-workers-examples/pages-with-config/pages-config.test.ts
- fixtures/vitest-pool-workers-examples/pages-with-config/tsconfig.json
- fixtures/vitest-pool-workers-examples/pages-with-config/vitest.config.ts
- fixtures/vitest-pool-workers-examples/pages-with-config/wrangler.toml
- packages/wrangler/src/api/integrations/platform/index.ts
Fixes #5768 
tl;dr: previously, `experimentalJsonConfig` was always set to `true` in `unstable_getMiniflareWorkerOptions`, which is used by the vitest integration to read config options. However `experimentalJsonConfig` is not supported by Pages, so any Pages + vitest setup that defined a wrangler.toml would trip up an error check for json + Pages.
- Tests
> fix bug with vitest + pages with wrangler.toml

- .changeset/gentle-apricots-kiss.md
- .prettierignore
- fixtures/interactive-dev-tests/src/startup-error.ts
- fixtures/interactive-dev-tests/tests/index.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/deployment-bundle/guess-worker-format.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/hotkeys.ts
- packages/wrangler/src/logger.ts
- packages/wrangler/src/utils/log-file.ts
Fixes N/A
Various fixes for logging in `--x-dev-env`, primarily to ensure the hotkeys don't wipe useful output:
- Ensure all direct console logging is through `logger.console()` so that the hotkeys are correctly rendered
- Ensure esbuild doesn't log directly to the console when guessing the format of a worker
- Ensure hotkeys are unregistered when `DevEnv` is torndown
- Ensure `devEnv.teardown()` is called when `startDev()` encounters a thrown error
- Tests
> Fix dev-env logging

- tools/deployments/__tests__/validate-pr-description.test.ts
- tools/deployments/validate-pr-description.ts
I had the PR description check failed because I typed "Fixes n/a" instead of "Fixes N/A"
It should be ok to make this check case insensitive.
Fixes N/A
- Tests
> chore: Drop the "Fixes" check in CI
