cloudflare/workers-sdk

package-lock.json
packages/wrangler/package.json

Upgrades and pins the version of @cloudflare/pages-functions-compiler to 0.3.4.

Pin @cloudflare/pages-functions-compiler version

---

package-lock.json
packages/wrangler/package.json

Includes the fix for `waitUntil` not being correctly bound to `context`.

Upgrade @cloudflare/pages-functions-compiler to 0.3.5

---

package-lock.json
packages/wrangler/package.json

Installs the latest @cloudflare/pages-functions-compiler@0.3.7 which uses esbuild 0.14.1. Also includes a couple of other wrangler pages dev fixes (sibling middleware and index couldn't co-exist, and makes the request mutable).

@cloudflare/pages-functions-compiler@0.3.7

---

CODEOWNERS

Until we have decent test coverage, and are roughly feature complete, I (Sunil) would like to approve every PR before it lands.
I _don't_ think this would apply to branches, but let me know if it does.

Create CODEOWNERS, add @threepointone for all files

---

package-lock.json
packages/wrangler/package.json

Changelog: https://github.com/cloudflare/miniflare/releases/tag/v2.0.0-rc.3
Closes #59

Upgrade `miniflare` to `2.0.0-rc.3`

---

package-lock.json
packages/wrangler/package.json

Updates @cloudflare/pages-functions-compiler to 0.3.8.
Queue the Bernie Sanders meme.

@cloudflare/pages-functions-compiler@0.3.8

---

.changeset/serious-kangaroos-relax.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/index.tsx

Hi.
Added optional shortcuts.
`--local` is too long, so I wanted to start local mode with `-l`.

Added optional shortcuts

---

.changeset/gentle-rice-study.md
.github/workflows/changeset-pr.yml
.github/workflows/prereleases.yml
.github/workflows/release.yml
.github/workflows/tests-typecheck.yml

- Testing script
- Lint script
- tsc is using skipLibCheck as a current workaround

CI/CD Tests & Type Checking

---

.changeset/neat-timers-search.md
package-lock.json
packages/wrangler/package.json
packages/wrangler/scripts/bundle.ts
packages/wrangler/src/config.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/dialogs.tsx
packages/wrangler/src/index.tsx
packages/wrangler/src/publish.ts

The quality of the polyfills is quite bad, so I'm removing this implementation (introduced in  https://github.com/cloudflare/wrangler2/pull/72)

remove `--polyfill-node` / `config.polyfill_node`

---

.changeset/real-crabs-roll.md
.github/workflows/tests-typecheck.yml
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/mock-cfetch.js
packages/wrangler/src/index.tsx

See individual commits.
Primarily - one small fix, to display an error message when an unknown command is provided.

Initial test related work - 1

---

packages/wrangler/src/__tests__/index.test.ts

test: fix the typings to avoid the need for `ts-expect-error` markers in the code

---

.github/workflows/release.yml

PR trigger changed to push to main. The PR trigger would not get proper permissions when set PR close to main.

Release Trigger Update

---

packages/wrangler/src/__tests__/index.test.ts

This allows us to have more control over the directory structure under test.
For example, currently there is a package.json and a tsconfig.json above the test directory.
We use `findUp()` to check for these, so it is not possible (without mocking findUp) to test cases where these do not exist.

test: use a temporary directory for test files

---

packages/wrangler/src/__tests__/index.test.ts

This commit adds tests to check the package.json and tsconfig.json processing.

test: add final tests for `init` command

---

.github/workflows/tests-typecheck.yml

We're currently only running tests on main and when a PR is opened. This PR runs tests on all branches so we can verify it's okay before opening a PR.

Run tests on all branches

---

package-lock.json
package.json

IN https://github.com/cloudflare/wrangler2/commit/56fa2053e275a58a903dc9ff2f14a6643ac8a612 we updated the package that generates the changelog but did not include the dependency in package.json.

Add missing dependency for the new changelog generator

---

.changeset/brown-hounds-wink.md
CONTRIBUTING.md
packages/wrangler/src/user.tsx

Users are now prompted!
PR for #237 
[![asciicast](https://asciinema.org/a/hXKxLzw8foLcfakNDnWie3snw.svg)](https://asciinema.org/a/hXKxLzw8foLcfakNDnWie3snw)

fix: Account selection is far less confusing

---

.changeset/old-walls-smoke.md
.vscode/settings.json

Add a bunch of common words to the cSpell config.

Ignore common technical words

---

package-lock.json
packages/wrangler/package.json
packages/wrangler/src/__tests__/jest.setup.ts
packages/wrangler/src/__tests__/logout.test.ts
packages/wrangler/src/__tests__/whoami.test.tsx

Adds testing for `wrangler logout`

tests: logout

---

.changeset/chatty-birds-argue.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/npm-installer.ts

- A slightly better `package.json`
- A slightly better `tsconfig.json`
- installing `typescript` as a dev dependency

enhance: small tweaks to `wrangler init`

---

.changeset/tiny-ways-sit.md
package-lock.json
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/cfetch/index.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/r2.ts

See #365
(still TODO: publishing bucket bindings)

Support R2 bucket management commands

---

.changeset/modern-owls-begin.md
packages/wrangler/src/__tests__/helpers/command-exists.d.ts
packages/wrangler/src/__tests__/helpers/faye-websocket.d.ts
packages/wrangler/src/__tests__/helpers/mock-bin.ts
packages/wrangler/src/__tests__/helpers/run-wrangler.ts
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/__tests__/package-manager.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/__tests__/secret.test.ts
packages/wrangler/src/api/worker.ts
packages/wrangler/src/cfetch/internal.ts
packages/wrangler/src/config.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/index.tsx
packages/wrangler/src/inspect.ts
packages/wrangler/src/pages.tsx
packages/wrangler/src/publish.ts
packages/wrangler/src/sites.tsx
packages/wrangler/src/user.tsx
tsconfig.json

In the march towards full strictness, this enables `strict` in `tsconfig.json` and fixes the errors it pops up. A changeset is included because there are some subtle code changes, and we should leave a trail for them.

chore: enable `strict` in `tsconfig.json`

---

.changeset/gentle-dodos-carry.md
package-lock.json
packages/wrangler/package.json
packages/wrangler/src/__tests__/helpers/mock-web-socket.ts
packages/wrangler/src/__tests__/jest.setup.ts
packages/wrangler/src/__tests__/tail.test.ts
packages/wrangler/src/tail.tsx

- ensure the correct API calls are made
- ensure that filters are sent
- ensure that the _correct_ filters are sent
- ensure that JSON gets spat out into the terminal
putting a changeset as well since some code changed in tail.tsx -- since there were errors caught by the tests!

Add tests for wrangler tail

---

CONTRIBUTING.md

Having never used changesets before, I was kind of confused about the format at first (eg. do I change `"wrangler": patch` to `"wrangler": fix` to match the format specified in CONTRIBUTING.md?)
This adds an example to make it easier for new contributors (and myself) to write proper changesets.

Add changeset example to CONTRIBUTING.md

---

.changeset/rude-ties-appear.md
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/__tests__/helpers/mock-console.ts
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/__tests__/secret.test.ts
packages/wrangler/src/index.tsx

There are two commits here. Look at them one at a time 😄

fix: remove unwanted logging from `kv:bulk` operations

---

docs/commands.md
docs/configuration.md
docs/custom-builds.md
docs/eject-webpack.md
docs/getting-started.md
docs/migration.md
docs/module-system.md
docs/projects.md
docs/v1-vs-v2.md

This makes a folder for docs, with outlines for some pages that should probably exist. There's no real content just yet, but this could lay a foundation and a skeleton structure.

docs: outline/stubs

---

.changeset/eighty-worms-thank.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/pages.tsx

When a command with subcommands is ran without subcommands the help message should display.
resolves #487

Render helpstring for incomplete subcommands

---

docs/deprecations.md
docs/environments.md
docs/v1-vs-v2.md
docs/what's-new.md

This adds some content to `docs/deprecations.md`. It's still not complete, but provides details for most of the important deprecations we're making.

docs: fleshed out deprecations.md

---

.changeset/angry-items-serve.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/config/validation.ts

Closes https://github.com/cloudflare/wrangler2/issues/601

fix: do not warn about miniflare in the configuration

---

docs/compare-v1-v2.md

@petebacondarwin this adds @Electroid's doc (https://github.com/cloudflare/wrangler2/issues/594) to the docs folder so we can all edit it outside of the Issue.

Add first draft of comparison doc

---

packages/wrangler/src/index.tsx

Added links to `config` & `subdomain` deprecated commands.

Documentation links

---

.changeset/modern-horses-rest.md
.changeset/spicy-pots-flash.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/config/config.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/validation-helpers.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/entry.ts
packages/wrangler/src/index.tsx

See [#588](https://github.com/cloudflare/wrangler2/issues/588)

feat: make `main` an inheritable environment field

---

.changeset/sharp-ties-suffer.md
packages/wrangler/src/__tests__/tail.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/tail/printing.ts

Fixes https://github.com/cloudflare/wrangler2/issues/707

fix: default `wrangler tail` to pretty print

---

.changeset/nasty-papayas-happen.md
packages/wrangler/src/dev/dev.tsx

feat: add hotkey to clear the console in `wrangler dev`

---

.changeset/swift-mice-attend.md
packages/wrangler/src/dev/dev.tsx

fix: distinguish the command hotkeys in wrangler dev

---

.changeset/afraid-crabs-care.md
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/pages.tsx

We might still add a git branch selector thing, but this is the bulk of a `wrangler pages project create` command.

Create Pages project command

---

packages/wranglerjs-compat-webpack-plugin/package.json

remove path dependency on wrangler and just use workspaces
closes #800

fix prerelease action

---

packages/wrangler/src/__tests__/user.test.ts

trivial typo fix in the test description.

minor typo fix

---

.changeset/tender-tables-yawn.md
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/pages.tsx

Fixes #686 
Adds help messages for `wrangler pages project` and `wrangler pages deployment`

Add Pages commands to help menu

---

README.md

Best practice to install in dev dependencies.

npm save dev

---

.changeset/bright-papayas-reflect.md
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/index.tsx

fix: show error if `--site` is used without a value

---

.changeset/sour-lies-whisper.md
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/pages.tsx

Fix deployment endpoint for wrangler pages publish

---

.changeset/lemon-jars-agree.md

Wrangler 2.0 is a full rewrite. Every feature has been improved, while retaining as much backward compatibility as we could. We hope you love it. It'll only get better.

major: ⛅️ Wrangler 2.0.0

---

.changeset/stupid-wombats-know.md
packages/wrangler/src/pages.tsx

Default to creating a new project when no existing ones are available for 'wrangler pages publish'.

Default to creating new project when no existing available for 'wrangler pages publish'

---

.changeset/beige-carpets-return.md
package-lock.json
packages/wrangler/package.json
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/pages.tsx

Use new bulk upload API for 'wrangler pages publish'.
This will improve upload speed and reliability of 'pages publish'.
Follows on from #912

Use bulk upload api for 'pages publish'

---

.changeset/shy-eels-march.md
CONTRIBUTING.md

(This also changes the changeset for custom domains to be a patch, not a minor)

Update CONTRIBUTING to clarify kinds of changes

---

.changeset/twelve-goats-provide.md
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/kv.ts
packages/wrangler/src/sites.tsx

Improve messaging when bulk deleting or uploading KV Pairs

---

examples/pages-functions-app/tests/index.test.ts

chore: Created closures around testing scenarios and removed reassignment of variables especially async ones.

Pages Functions Tests 

---

packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/pages.tsx

Otherwise this is a performance regression for projects <5k files or <50mb total.
This generates _at least_ 3 buckets (which is the current concurrency limit) and then starts distributing files between them. So even though the limit is 5k per bucket, a project with 3k files will now use 3 uploads of 1k each.

Eagerly using multiple buckets for batch-upload

---

README.md

helpful for those who have been away for a while ;)

+ link to v1/v2 comparison

---

.changeset/violet-apes-lick.md
packages/wrangler/src/index.tsx

fix: don't pin the wrangler version in package.json

---

.changeset/weak-jokes-clap.md
packages/wrangler/src/__tests__/helpers/mock-dialogs.ts
packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/dialogs.tsx
packages/wrangler/src/index.tsx
packages/wrangler/templates/new-worker-scheduled.js
packages/wrangler/templates/new-worker-scheduled.ts

Select handler type

---

.changeset/chilled-buckets-speak.md
packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/templates/new-worker-scheduled.js
packages/wrangler/templates/new-worker-scheduled.ts

Enhances #1113 / relates to #1175

polish: add cron to wrangler.toml when new Scheduled Worker is created

---

.changeset/brave-ghosts-buy.md
packages/wrangler/src/dev/local.tsx

Closes #1226 
If there's a more elegant way of solving this issue please let me know / happy to adjust the PR as required.

fix: parsing of node inspector url

---

packages/wrangler/src/__tests__/publish.test.ts

test: refactor bulk asset upload test to avoid callback hell

---

.changeset/big-toes-obey.md
packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
packages/wrangler/src/__tests__/jest.setup.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/__tests__/user.test.ts
packages/wrangler/src/generate-auth-url.ts
packages/wrangler/src/generate-random-state.ts
packages/wrangler/src/open-in-browser.ts
packages/wrangler/src/user.tsx

Had to pull a bunch of helper functions out of `user.tsx` to make it possible to mock the generated state value, and codeChallenge value
Closes #1259

fix: let folks know the URL we're opening during login

---

.changeset/breezy-scissors-tie.md
packages/wrangler/src/__tests__/helpers/mock-console.ts
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/bundle-reporter.tsx
packages/wrangler/src/dev/remote.tsx
packages/wrangler/src/publish.ts

The [`publish`](https://github.com/cloudflare/wrangler2/issues/405#issuecomment-1156762297) command will output a message of the "total upload"
which includes script + modules showing the original size versus gzip size.

feat: Bundle Reporter

---

.changeset/quick-flowers-help.md
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/publish.ts

polish: include a copy-pastable message when trying to publish without a compatibility date

---

.changeset/hungry-wombats-fail.md
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/index.tsx

Added a flag that will decode the response from KV:get to utf8
resolves #1306

feat: text decoder

---

.changeset/dull-bottles-teach.md
packages/wrangler/templates/pages-template-worker.ts

Fixes https://github.com/cloudflare/wrangler2/issues/1244

fix: Ensure Response is mutable in Pages functions

---

packages/wrangler/src/pages/upload.tsx

Adds the `--output-manifest-path` option to internal command `wrangler pages project upload` so we can then create a deployment from this.
No changeset added as this is currently a private command.

Add `--output-manifest-path` option to internal command `wrangler pages project upload`

---

.changeset/rotten-radios-wink.md
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/pages/dev.tsx
packages/wrangler/src/pages/publish.tsx

throw error if config is specified in pages

---

.changeset/wise-pens-shake.md
fixtures/pages-functions-app/.dev.vars
fixtures/pages-functions-app/tests/index.test.ts
packages/wrangler/src/pages/dev.tsx

loading .dev.vars support for pages

---

packages/wrangler/README.md

Adding badges to `README.md` all of them are up for discussion this is more of just an example of what we can do. Also wanted to add a `webp` looped video of how to get started with the CLI and using some of the commands. 
The "Chat" badge also has a link to the Discord
The "downloads" badge links to NPM

README badges 

---

.changeset/old-timers-smash.md
package-lock.json
packages/wrangler/package.json
packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
packages/wrangler/src/__tests__/https-options.test.ts
packages/wrangler/src/__tests__/jest.setup.ts
packages/wrangler/src/__tests__/user.test.ts
packages/wrangler/src/config-path.ts
packages/wrangler/src/global-wrangler-config-path.ts
packages/wrangler/src/https-options.ts
packages/wrangler/src/user/user.tsx

Wrangler was creating a config file in the home directory of the operating system `~/.wrangler`. The XDG path spec is a
standard for storing files, these changes include XDG pathing compliance for `.wrangler/*` location and backwards compatibility with previous
`~/.wrangler` locations.
resolves #1053

polish: Compliance with the XDG Base Directory Specification

---

.changeset/dirty-pens-drive.md
packages/wrangler/src/dev/local.tsx

fix: add r2Persist key to miniflare options

---

.changeset/clean-spoons-buy.md
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/publish.ts

Fixes https://github.com/cloudflare/wrangler2/issues/1491

fix: warn when using `--no-bundle` with `--minify` or `--node-compat`

---

fixtures/legacy-site-app/package.json
package-lock.json

(Also using this to try and fix the build)

chore: make sure all fixtures have a `package.json`

---

.changeset/neat-suits-prove.md
packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/jest.setup.ts
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/cfetch/internal.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/r2.ts

Commands added for uploading and downloading objects from r2.

R2 fetch helper and commands

---

packages/wrangler/src/__tests__/whoami.test.tsx

Following on from https://github.com/cloudflare/wrangler2/pull/1550 and in particular https://github.com/cloudflare/wrangler2/pull/1550#pullrequestreview-1052270931 , sometimes tests are failing because of tables in ink. This should fix them.

fix: tests sometimes fail with ink tables

---

codecov.yml

Testing extensively[ on a fork](https://github.com/JacobMGEvans/wrangler2/pull/8) running against different configurations and different drastic changes
to the codebase to cause major test coverage issues.
Able to track down the configuration for patch in docs which is identical to project: https://docs.codecov.com/docs/commit-status#patch-status
This shows the patch failing with a lot of code additions, no test coverage improvements, and misconfigured CodCov
This shows the patch failing with a lot of code additions, no test coverage improvements, and with fixed configuration for CodCov

chore: fix patch block CI

---

.changeset/shaggy-poems-talk.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/index.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/create-worker-upload-form.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/index.tsx
packages/wrangler/src/publish.ts
packages/wrangler/src/worker.ts
packages/wranglerjs-compat-webpack-plugin/src/__tests__/index.spec.ts

This implements a new logfwdr binding which will only be usable by accounts with a special permission.

Implemented logfwdr binding

---

.changeset/young-weeks-worry.md
packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/r2.ts

Improving the R2 objects management, added the functionality to delete objects in a bucket.
resolves #1584
Showing the test bucket & object in dashboard:
Showing delete process in action:
https://user-images.githubusercontent.com/27247160/182436974-d945d29e-c18f-40b0-a758-9de1aa492e7f.mov

feat: R2 Object Delete

---

.changeset/yellow-bats-explode.md
fixtures/pages-functions-app/functions/r2/create.ts
fixtures/pages-functions-app/functions/r2/get.ts
fixtures/pages-functions-app/package.json
fixtures/pages-functions-app/tests/index.test.ts
packages/wrangler/src/api/dev.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/pages/dev.tsx

Added R2 support to pages dev

---

.changeset/orange-ads-marry.md
packages/wrangler/src/pages/projects.tsx

Closes #1487 pages project create issue

fix Command failed: git rev-parse --abrev-ref HEAD

---

.prettierignore
fixtures/remix-pages-app/.gitignore

https://github.com/cloudflare/wrangler2/pull/1631
https://github.com/cloudflare/wrangler2/pull/1608
Both changed the files we generate/format. This PR fixes CI.

Add some files to .prettierignore and .gitignore

---

.changeset/thin-schools-remain.md
packages/wrangler/src/api/dev.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/pages/dev.tsx

Add `--inspector-port` argument to `wrangler pages dev`

---

CONTRIBUTING.md
package-lock.json
packages/wrangler/package.json
packages/wrangler/src/__tests__/paths.test.ts
packages/wrangler/src/config/index.ts
packages/wrangler/src/d1/backups.tsx
packages/wrangler/src/d1/create.tsx
packages/wrangler/src/d1/delete.tsx
packages/wrangler/src/d1/execute.tsx
packages/wrangler/src/d1/list.tsx
packages/wrangler/src/d1/options.ts
packages/wrangler/src/d1/utils.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/dev/get-local-persistence-path.tsx
packages/wrangler/src/dialogs.tsx
packages/wrangler/src/pages/dev.tsx
packages/wrangler/src/paths.ts

Making it possible to use the same `.sql` files to bootstrap your local `wrangler dev --local` as production.

D1 `execute --local` support

---

packages/wrangler/src/whoami.tsx

The error was hidden by the use of shortcut fragments. Added the key prop to prevent edge case issues with React rendering.

fix: React Key Prop

---

packages/wrangler/src/whoami.tsx

- rename some variables within a react component inside of whoami to more accurately reflect their use

chore: rename variables in whoami

---

.changeset/six-coins-work.md
packages/wrangler/src/__tests__/generate.test.ts
packages/wrangler/src/generate.ts

fix: generate uses wrong path

---

package-lock.json
packages/wrangler/package.json
packages/wrangler/src/cfetch/internal.ts

Undici does not currently support formData parsing, this ponyfill implementation
handles multipart/formdata so we can properly get the file

fix: implement busboy to handle formData parsing

---

.changeset/heavy-cycles-attack.md
fixtures/local-mode-tests/tests/ports.test.ts
packages/wrangler/src/api/dev.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/dev/dev.tsx
packages/wrangler/src/dev/local.tsx
packages/wrangler/src/dev/remote.tsx
packages/wrangler/src/dev/start-server.ts
packages/wrangler/src/miniflare-cli/index.ts

fix: refactor unstable_dev to avoid race conditions with ports

---

.changeset/rude-seas-impress.md
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/publish.ts

The getMonth() return values 0-11, adding 1 resolves this and added test.
resolves #1766

fix: getMonth compatibility date

---

.changeset/forty-phones-punch.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/secret.test.ts
packages/wrangler/src/index.tsx

Created a flag that allows for passing in a JSON file with key/value's of secrets.
resolve #1610

feat: Bulk Secret Upload

---

ISSUE_TRIAGE.md

Adds information about quick win label to `ISSUE_TRIAGE`

chore: add information about quick win label to `ISSUE_TRIAGE`

---

packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/publish.ts

There's already a changeset for this change, this is just fixing an existing fix

fix: we still want to publish if its the first time

---

package-lock.json
packages/pages-shared/package.json
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/publish.test.ts

Fix snapshots and bump miniflare

---

.changeset/brave-plums-count.md
packages/wrangler/src/__tests__/dialogs.test.tsx
packages/wrangler/src/dialogs.tsx

fix: wrangler publish for CI after a manual deployment

---

packages/wrangler/src/init.ts

Too much stuff inside the initHandler already, don't need additional functions too.
This PR:
- Moves `installPackages`, `getNewWorkerType`, `getNewWorkerTemplate`, `getNewWorkerToml` outside of `initHandler`
- Refactors `writePackageJsonScriptsAndUpdateWranglerToml` to accept an object of options, to make it easier to add additional options later
- Adds dependency-injection for `installPackages` by adding a PackageManager prop

chore: move helper functions outside of initHandler

---

CODEOWNERS

^ Like it says. He doesn't deserve it anymore.

Remove @threepointone from CODEOWNERS

---

package.json

Closes https://github.com/cloudflare/wrangler2/issues/1845

chore: run build when `npm test`

---

.changeset/rude-squids-turn.md
packages/wrangler/src/inspect.ts

Closes https://github.com/cloudflare/wrangler2/issues/1810

fix: handle logging of empty map/set/weak-map/weak-set

---

packages/wrangler/src/dev/remote.tsx

Work in progress for enabling remote mode for `unstable_dev` - need to pull out code that'll be used by both React and non-React versions of wrangler
Intentionally no changeset.

chore: pull common code out of Remote's JSX

---

packages/wrangler/src/proxy.ts

This PR pulls out our common proxy configuration code into a function we can call outside of React
(because the function uses refs, i'm going to have to implement my own react-free ref object)

chore: extract common proxy configuration

---

.changeset/silly-birds-work.md
.changeset/six-trees-return.md
packages/pages-shared/src/asset-server/handler.ts

This reverts commit 43fc1d89bcf2fc21e8083bac0c08de9e1f413f11.
This re-applies #1903 after reverting it in #1926.

Revert "Revert "Allow unsetting of Link headers using _headers (#1903)" (#1926)"

---

.changeset/mean-bats-melt.md
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/dev.tsx
packages/wrangler/src/index.tsx

Hide deprecated commands from --help

---

packages/wrangler/src/__tests__/helpers/mock-kv.ts
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/kv/helpers.ts
packages/wrangler/src/kv/index.ts
packages/wrangler/src/sites.tsx

Just moving kv:* out of index.tsx into its own file.

chore: refactor kv

---

packages/wrangler/package.json
packages/wrangler/scripts/assert-git-version.ts

Check git version before running tests

---

CODEOWNERS

Just me volunteering to get pinged on every PR

add @rozenmd to CODEOWNERS

---

packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/index.tsx

Spacing between emoji's and description was incorrect for some commands.

fix: help message spacing

---

.changeset/cold-years-attend.md
packages/wrangler/src/config/environment.ts
packages/wrangler/src/d1/execute.tsx
packages/wrangler/src/d1/index.ts
packages/wrangler/src/d1/migrations.tsx
packages/wrangler/src/d1/options.ts
packages/wrangler/src/d1/types.tsx
packages/wrangler/src/d1/utils.ts
packages/wrangler/src/dialogs.tsx
packages/wrangler/src/worker.ts

This adds `wrangler d1 migrations` sub command, this is still a WIP
```
wrangler d1 migrations
Interact with D1 Migrations
Commands:
wrangler d1 migrations list <name>    List your D1 migrations
wrangler d1 migrations create <name> <message>  Create a new Migration
wrangler d1 migrations apply <name>   Apply D1 Migrations
Flags:
-c, --config   Path to .toml configuration file  [string]
-h, --help     Show help  [boolean]
-v, --version  Show version number  [boolean]
```

D1 Migrations

---

packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
packages/wrangler/src/index.tsx

Naming conventions are being reworked and will be standardized at Worker Org level this is part of this effort.

chore: Update naming conventions

---

.changeset/old-planes-add.md
packages/wrangler/src/publish/publish.ts

fix: throw only if error code isnt 10023

---

packages/wrangler/src/__tests__/deployments.test.ts
packages/wrangler/src/deployments.ts

Put a space in active message

---

.changeset/pink-lies-dress.md
packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/metrics/send-event.ts
packages/wrangler/src/pages/build.tsx
packages/wrangler/src/pages/deployment-tails.tsx
packages/wrangler/src/pages/deployments.tsx
packages/wrangler/src/pages/dev.tsx
packages/wrangler/src/pages/functions.tsx
packages/wrangler/src/pages/index.tsx
packages/wrangler/src/pages/prompt-select-project.tsx
packages/wrangler/src/pages/publish.tsx
packages/wrangler/src/pages/types.ts
packages/wrangler/src/pages/upload.tsx
packages/wrangler/src/pages/utils.ts
packages/wrangler/src/tail/createTail.ts
packages/wrangler/src/yargs-types.ts

Adds the `wrangler pages deployment tail [deploymentId]` command

feat: Tails for Pages

---

packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/index.tsx

Should not merge after approvals

Unhide deployments command

---

packages/wrangler/src/dev/local.tsx
packages/wrangler/src/dev/start-server.ts

Explicitly name the transformMiniflareOptions function to transformMf2OptionsToMf3Options
resolves #2203

Miniflare options transform rename

---

CONTRIBUTING.md

There is a dependecy on libc++ for workerd currently, and can effect development.

Dependency libc++

---

.changeset/tiny-rockets-serve.md
packages/wrangler/src/index.tsx
packages/wrangler/src/user/user.tsx

Also increases the login timeout (1 minute isn't long enough if you get sent a 2FA email)
Closes [#2250](https://github.com/cloudflare/wrangler2/issues/2250)

Add option to customise browser opening behaviour

---

packages/wrangler/src/d1/backups.tsx
packages/wrangler/src/d1/delete.tsx
packages/wrangler/src/d1/index.ts
packages/wrangler/src/d1/migrations/apply.tsx
packages/wrangler/src/d1/migrations/list.tsx
packages/wrangler/src/d1/migrations/options.ts

chore: clean-up d1 yargs commands

---

fixtures/external-durable-objects-app/tests/index.test.ts
fixtures/local-mode-tests/tests/headers.test.ts
fixtures/local-mode-tests/tests/module.test.ts
fixtures/local-mode-tests/tests/nodeBuiltinPackage.test.ts
fixtures/local-mode-tests/tests/ports.test.ts
fixtures/local-mode-tests/tests/sw.test.ts
fixtures/local-mode-tests/tests/unstableDev.test.ts
fixtures/node-app-pages/tests/index.test.ts
fixtures/pages-d1-shim/tests/index.test.ts
fixtures/pages-functions-app/tests/index.test.ts
fixtures/pages-functions-with-routes-app/tests/index.test.ts
fixtures/pages-workerjs-and-functions-app/tests/index.test.ts
fixtures/pages-workerjs-app/tests/index.test.ts
fixtures/pages-workerjs-with-routes-app/tests/index.test.ts
fixtures/pages-ws-app/package.json
fixtures/pages-ws-app/tests/index.test.ts
fixtures/remix-pages-app/tests/index.test.ts
fixtures/service-bindings-app/tests/index.test.ts
package.json
packages/wrangler/bin/wrangler.js
packages/wrangler/src/dev/dev.tsx

Replaces #1877 which I accidentally closed with git tomfoolery.

Concurrent fixture tests

---

packages/wrangler/src/__tests__/tail.test.ts

Continued effort to convert tests use MSW
task #1874

Convert Tail to MSW

---

packages/wrangler/src/__tests__/delete.test.ts

Continued efforts to convert to Mock Service Workers and remove custom mocking.
related tasks #1874

Convert delete.test.ts to MSW

---

.github/workflows/pullrequests.yml
.github/workflows/write-prerelease-comment.yml
packages/prerelease-registry/functions/utils/getArtifactForWorkflowRun.ts
packages/prerelease-registry/wrangler.toml

Switch the pre-release registry away from @GregBrimble's personal account to use a proper service account (cc @workers-devprod)

Switch to service account

---

.changeset/fuzzy-ducks-impress.md
.github/workflows/pullrequests.yml
packages/wrangler/src/config/index.ts
packages/wrangler/src/dev.tsx

Closes https://github.com/cloudflare/wrangler2/issues/2263

preview_database_id not being picked up

---

packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
packages/wrangler/src/__tests__/tail.test.ts

continued effort to convert tests to MSW
task #1874

Pages Tail MSW conversion

---

packages/wrangler/src/__tests__/metrics.test.ts

Continued effort to convert tests to MSW
task #1874

Metrics test MSW conversion

---

.changeset/honest-grapes-sort.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/config/index.ts
packages/wrangler/src/index.tsx
packages/wrangler/src/metrics/send-event.ts

Intentionally putting this `feat` behind a `patch` because I don't think it's worth bumping a minor over.
Closes #2217

feat: wrangler docs command

---

packages/wrangler/src/__tests__/pages.test.ts
packages/wrangler/src/cfetch/internal.ts
packages/wrangler/src/logger.ts
packages/wrangler/src/pages/publish.tsx
packages/wrangler/src/pages/upload.tsx

Adds some extra debug logging and the ability to skip file upload cache

Extra debug logging and skip caching function

---

.changeset/kind-students-doubt.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/docs/index.ts
packages/wrangler/src/index.tsx

Refactor to allow folks to enter a command to "search" for - I intend to hook this up to a search index later - don't worry too much about the hardcoded command strings

chore: refactor docs command

---

.changeset/rotten-cooks-chew.md
packages/wrangler/src/init.ts

Just making this PR smaller so it's easier to digest.
closes #2375

improve `wrangler init --from-dash` help text and error handling

---

.changeset/tough-carrots-live.md
packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/deprecated/index.ts
packages/wrangler/src/init.ts

This PR makes it clearer what --from-dash wants from you.
closes #2373
closes #2375

fix: refactored types and clarified --from-dash help text

---

packages/wrangler/src/__tests__/dev.test.tsx

continued effort to convert tests to MSW
task #1874

Convert Dev to MSW

---

packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/__tests__/jest.setup.ts

continued effort to convert tests to MSW
task #1874

MSW convert init

---

packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts
packages/wrangler/src/__tests__/secret.test.ts

continued effort to convert tests to MSW
task #1874

Secrets MSW conversion

---

packages/wrangler/src/__tests__/helpers/mock-cfetch.ts
packages/wrangler/src/__tests__/helpers/mock-process.ts
packages/wrangler/src/__tests__/jest.setup.ts
packages/wrangler/src/__tests__/kv.test.ts

continued effort to convert tests to MSW 
task #1874

KV MSW conversion 

---

fixtures/local-mode-tests/tests/headers.test.ts
fixtures/local-mode-tests/tests/module.test.ts
fixtures/local-mode-tests/tests/nodeBuiltinPackage.test.ts
fixtures/local-mode-tests/tests/ports.test.ts
fixtures/local-mode-tests/tests/sw.test.ts
fixtures/local-mode-tests/tests/unstableDev.test.ts
packages/wrangler/src/__tests__/api-dev.test.ts
packages/wrangler/src/__tests__/api-devregistry.test.js
packages/wrangler/src/__tests__/middleware.scheduled.test.ts
packages/wrangler/src/__tests__/middleware.test.ts
packages/wrangler/src/api/dev.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/dev/start-server.ts

Merge this after https://github.com/cloudflare/wrangler2/pull/2455
Resolves https://github.com/cloudflare/wrangler2/issues/2353

Add an experimental option to disable dev registry

---

.changeset/serious-ducks-protect.md
packages/wrangler/src/config/validation.ts

Closes https://github.com/cloudflare/wrangler2/issues/2473

fix: update NO_D1_WARNING to make it clear how to turn it off

---

.github/ISSUE_TEMPLATE/bug-template.yaml

Add catch-all to bug report form

---

packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/init.ts
packages/wrangler/templates/init-tests/test-vitest-new-worker.ts

Fix init --yes 

---

.changeset/sixty-books-share.md
packages/wrangler/src/__tests__/pages-deployment-tail.test.ts
packages/wrangler/src/__tests__/tail.test.ts
packages/wrangler/src/tail/createTail.ts
packages/wrangler/src/tail/printing.ts

Support EmailEvent type when tailing logs of a worker.

expect events of type EmailEvent

---

.changeset/fast-badgers-pump.md
package-lock.json
packages/wrangler/templates/middleware/loader-modules.ts

Also upgrade `@cloudflare/workers-types` for our templates to v4
Closes #2273

Support queue and trace events in module middleware

---

.changeset/nasty-fishes-carry.md
packages/wrangler/src/__tests__/deployments.test.ts
packages/wrangler/src/deployments.ts
packages/wrangler/src/index.ts
packages/wrangler/src/metrics/send-event.ts

Adds a metrics event to the `deployments` command. I'm not sure if this is everything that needs to happen or if there's some internal work as well? I could use some guidance.
- n/a
- I'm not sure if I should slash can add tests for this? Is that something we do?
Fixes #2408.

Add metrics to `wrangler deployments`

---

packages/wrangler/src/__tests__/helpers/msw/handlers/deployments.ts
packages/wrangler/src/__tests__/helpers/msw/handlers/namespaces.ts
packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
packages/wrangler/src/__tests__/helpers/msw/handlers/script.ts
packages/wrangler/src/__tests__/helpers/msw/handlers/user.ts
packages/wrangler/src/__tests__/helpers/msw/handlers/zones.ts
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/__tests__/tail.test.ts
packages/wrangler/src/__tests__/user.test.ts
packages/wrangler/src/__tests__/whoami.test.tsx
packages/wrangler/src/__tests__/worker-namespace.test.ts

- As part of the effort regarding reimplementing abstractions and refactoring the work from MSW migration.
related #2307
~- [ ] Changeset~
~- [ ] Checked for inclusion of a relevant changeset~
~- [ ] Checked for creation of associated docs updates~

MSW fetchResult abstraction

---

.github/workflows/codecov-context.yml
.github/workflows/create-pullrequest-prerelease.yml
.github/workflows/d1.yml
.github/workflows/devtools.yml
.github/workflows/experimental-wasm-release.yml
.github/workflows/issues.yml
.github/workflows/prereleases.yml
.github/workflows/pullrequests.yml
.github/workflows/queues.yml
.github/workflows/release.yml
.github/workflows/test-old-node-error.yml
.github/workflows/write-prerelease-comment.yml

switch to ubuntu-latest

---

packages/wrangler/src/__tests__/pages.test.ts

We weren't sorting correctly because we incorrectly assumed some types.

Fix flakey Pages publish test

---

packages/wrangler/src/__tests__/publish.test.ts

Follow-up for https://github.com/cloudflare/wrangler2/pull/2501

add test to cover d1-do facade

---

packages/wrangler/src/__tests__/d1/d1.test.ts
packages/wrangler/src/d1/utils.ts

Before:
```
🚧 D1 is currently in open alpha and is not recommended for production data and traffic.
Please report any bugs to https://github.com/cloudflare/wrangler2/issues/new/choose.
To request features, visit https://community.cloudflare.com/c/developers/d1.
To give feedback, visit https://discord.gg/cloudflaredev
```
After:
```
-------------------- 
🚧 D1 is currently in open alpha and is not recommended for production data and traffic
🚧 Please report any bugs to https://github.com/cloudflare/wrangler2/issues/new/choose
🚧 To request features, visit https://community.cloudflare.com/c/developers/d1
🚧 To give feedback, visit https://discord.gg/cloudflaredev
```

fix: make d1 warning stand out more

---

packages/wrangler-devtools/patches/0001-Add-README-detailing-the-setup-process.patch
packages/wrangler-devtools/patches/0002-Support-viewing-files-over-the-network.patch
packages/wrangler-devtools/patches/0003-Show-fallback-image-on-Safari.patch
packages/wrangler-devtools/patches/0004-Support-previewing-subrequest-responses.patch
packages/wrangler-devtools/patches/0005-Better-Firefox-support-for-network-tab.patch
packages/wrangler-devtools/patches/0006-Remove-unsupported-network-UI.patch
packages/wrangler-devtools/patches/0007-Remove-unsupported-profiler-UI.patch
packages/wrangler-devtools/patches/0008-Show-an-overlay-on-the-memory-tab-in-Firefox.patch
packages/wrangler-devtools/patches/0009-Support-theme-url-parameter-for-forcing-the-theme-fr.patch
packages/wrangler-devtools/patches/0010-Basic-support-for-text-colour-in-dark-mode-in-browse.patch
packages/wrangler-devtools/patches/0011-Fallback-to-location-for-domain.patch
packages/wrangler-devtools/patches/0012-Hide-unsupported-settings-UI.patch

Update Devtools patches

---

.changeset/shaggy-hornets-drop.md
package-lock.json
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/__tests__/jest.setup.ts
packages/pages-shared/asset-server/handler.ts
packages/pages-shared/environment-polyfills/miniflare-tre.ts
packages/pages-shared/environment-polyfills/miniflare.ts
packages/pages-shared/environment-polyfills/types.ts
packages/pages-shared/package.json

This is somehow preventing the `wrangler pages dev` server from starting up. Reverting until we can get a fix in place.

Revert "Only check for <link> elements if response is HTML"

---

fixtures/local-mode-tests/tests/unstableDev.test.ts
vitest.config.ts

Boost fixture test timeout

---

packages/wrangler/src/d1/execute.tsx

Just fixing a typo I came across 🙂

fix injest typo

---

packages/wrangler/src/__tests__/d1/migrate.test.ts

quick thing I noticed from codecov

chore: add test for custom migration folder

---

packages/wrangler/src/__tests__/generate.test.ts

Skips tests that depend on a remote GitHub repository being reachable.

Skip remote tests

---

CONTRIBUTING.md
packages/wrangler/CHANGELOG.md
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/__tests__/whoami.test.tsx
packages/wrangler/src/config/config.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/index.ts
packages/wrangler/src/sites.ts
packages/wrangler/src/tail/filters.ts
packages/wrangler/src/user/user.ts
packages/wranglerjs-compat-webpack-plugin/CHANGELOG.md
packages/wranglerjs-compat-webpack-plugin/package.json
packages/wranglerjs-compat-webpack-plugin/src/__tests__/helpers/compare-outputs.ts
packages/wranglerjs-compat-webpack-plugin/src/__tests__/helpers/install-wrangler.ts
packages/wranglerjs-compat-webpack-plugin/src/__tests__/helpers/mock-config-dir.ts
packages/wranglerjs-compat-webpack-plugin/src/__tests__/helpers/pipe.ts
packages/wranglerjs-compat-webpack-plugin/src/__tests__/index.spec.ts
packages/wranglerjs-compat-webpack-plugin/src/index.ts

Uses v1/v2 language instead of 1/2 language. See https://github.com/cloudflare/wrangler2/pull/2345/files, which this PR supersedes
- https://jira.cfdata.org/browse/DEVX-80

Use version language

---

packages/wrangler/src/__tests__/publish.test.ts

Mistakenly committed a .only on tests

Remove `.only`

---

CONTRIBUTING.md

Clarify the requirements for PR titles and body text.
Fixes some of #2511.

[admin] Update CONTRIBUTING.md

---

.changeset/modern-clouds-rest.md

Adds a changeset for https://github.com/cloudflare/workers-sdk/pull/2793 🤦

Changeset for #2793

---

.changeset/mean-actors-hammer.md
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/publish/publish.ts

Fix `keep_vars` having no effect in wrangler.toml

---

packages/wrangler/src/d1/execute.tsx

nit: fix typo

---

templates/worker-turso-ts/.gitignore
templates/worker-turso-ts/README.md
templates/worker-turso-ts/package.json
templates/worker-turso-ts/src/index.ts
templates/worker-turso-ts/tsconfig.json
templates/worker-turso-ts/wrangler.toml

As discussed with @elithrar for the Turso tutorial.

Initial version of tutorial code for workers using Turso and TypeScript

---

.github/workflows/edge-preview-authenticated-proxy.yml
.github/workflows/format-errors.yml

Fixes the publish workflows for `format-errors` and `edge-preview-authenticated-proxy`

Fix `format-errors` and `edge-preview-authenticated-proxy` publish

---

templates/worker-turso-rs/.gitignore
templates/worker-turso-rs/Cargo.toml
templates/worker-turso-rs/README.md
templates/worker-turso-rs/src/lib.rs
templates/worker-turso-rs/src/utils.rs
templates/worker-turso-rs/wrangler.toml
templates/worker-turso-ts/src/index.ts

Don't cache the client object - it must be new each request

Turso worker fix

---

templates/worker-turso-ts/README.md

Corrected the URL of the tutorial @elithrar

Updated URL for related Turso tutorial

---

packages/quick-edit-extension/package.json
packages/quick-edit-extension/src/extension.ts
packages/quick-edit/functions/_middleware.ts

Create an extension command and palette command for changing the file entrypoint and sending the event to the frontend through the messagePort. Dynamic Theme for light and dark mode on VSCode setup.

Entrypoint & Theme

---

packages/quick-edit/README.md
packages/quick-edit/functions/_middleware.ts
packages/quick-edit/patches/0001-Add-Custom-workbench-for-Cloudflare.patch
packages/quick-edit/patches/0002-Remove-Themes-from-Setting-SubMenu.patch
packages/quick-edit/patches/0003-Removed-Menu.patch
packages/quick-edit/patches/0004-Remove-Profile-from-Setting-SubMenu.patch
packages/quick-edit/patches/0005-Remove-Account-Extension.patch
packages/quick-edit/patches/0006-Remove-Debug-Icon-other-default-views.patch
packages/quick-edit/patches/0007-Remove-Source-Control.patch
packages/quick-edit/patches/0008-Remove-Custom-Menu-hamburger.patch
packages/quick-edit/patches/0009-Remove-Extensions-Icon-Quick-Access.patch
packages/quick-edit/patches/0010-Remove-dead-code.patch
packages/quick-edit/setup.sh

- Exposes the solarflare theme for VSCode registration
- Removes dead code from VSCode so that the build will succeed
- Renames patches to be in consistent `format-patch` format

Expose Solarflare & remove dead code

---

fixtures/pages-functions-app/public/_redirects
fixtures/pages-functions-app/public/users/[id].html
fixtures/pages-functions-app/tests/index.test.ts
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/__tests__/metadata-generator/parseRedirects.invalid.test.ts
packages/pages-shared/__tests__/metadata-generator/parseRedirects.valid.test.ts
packages/pages-shared/asset-server/handler.ts
packages/pages-shared/metadata-generator/constants.ts
packages/pages-shared/metadata-generator/parseRedirects.ts

Revert 2708 temporary revert proxying

---

.changeset/short-knives-care.md

Add changeset to release pages-shared

---

.changeset/giant-singers-teach.md
.changeset/soft-vans-impress.md
fixtures/pages-simple-assets/index.d.ts
fixtures/pages-simple-assets/package.json
fixtures/pages-simple-assets/public/index.html
fixtures/pages-simple-assets/tests/index.test.ts
fixtures/pages-simple-assets/tests/tsconfig.json
fixtures/pages-simple-assets/tsconfig.json
package-lock.json
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/__tests__/asset-server/responses.test.ts
packages/pages-shared/__tests__/metadata-generator/createMetadataObject.test.ts
packages/pages-shared/asset-server/handler.ts
packages/pages-shared/asset-server/responses.ts
packages/pages-shared/metadata-generator/createMetadataObject.ts

Prevent protocol-less URL redirects

---

.changeset/odd-stingrays-jam.md
fixtures/pages-simple-assets/tests/index.test.ts
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/__tests__/asset-server/responses.test.ts
packages/pages-shared/asset-server/responses.ts

Prevent protocol-less URL redirects (with backslashes)

---

.changeset/dirty-seas-explode.md
fixtures/pages-functions-app/public/_redirects
fixtures/pages-functions-app/public/users/[id].html
fixtures/pages-functions-app/tests/index.test.ts
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/__tests__/metadata-generator/parseRedirects.invalid.test.ts
packages/pages-shared/__tests__/metadata-generator/parseRedirects.valid.test.ts
packages/pages-shared/asset-server/handler.ts
packages/pages-shared/metadata-generator/constants.ts
packages/pages-shared/metadata-generator/parseRedirects.ts

Walshy said I could revert #3038 now

Feat(pages-shared): Bring back proxying

---

CONTRIBUTING.md

Fixes: N/A
**What this PR solves / how to test:** Adds note regarding wrangler release to CONTRIBUTING.

Add release note to CONTRIBUTING

---

.changeset/thirty-fireants-stare.md
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/__tests__/asset-server/responses.test.ts
packages/pages-shared/asset-server/responses.ts

fix(pages-shared): Strip %09 when redirecting

---

.changeset/moody-eyes-sparkle.md
packages/pages-shared/__tests__/asset-server/handler.test.ts
packages/pages-shared/asset-server/responses.ts

pages-shared: Strip spaces in urls

---

.changeset/young-phones-behave.md
fixtures/pages-simple-assets/tests/index.test.ts
packages/pages-shared/__tests__/asset-server/responses.test.ts
packages/pages-shared/asset-server/responses.ts

- [x ] Tests
- [x ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

fix: Remove global flag in pages-shared regex

---

packages/wrangler/src/d1/create.tsx

Passing experimental: true to D1

---

package-lock.json

- Adds fixture added in https://github.com/cloudflare/workers-sdk/pull/2966 to `package-lock.json`

Fix lock file

---

.changeset/gentle-yaks-repeat.md
packages/wrangler/src/__tests__/unstableDev.test.ts
packages/wrangler/src/dev-registry.ts

Fixes #1920 #2959.
Solve dev mode the local registry server be closed and throw error: '[WARNING] Failed to get worker definitions TypeError: fetch failed'

[wrangler] Fix local mode the registry server closed

---

.changeset/sour-timers-grin.md
packages/solarflare-theme/README.md
packages/solarflare-theme/solarflare-quickstart.md
packages/solarflare-theme/themes/cloudflare-light-color-theme.json

Fixes DEVX-649
**Associated docs issue(s)/PR(s):** Follow quickstart steps in `packages/solarflare-theme` 
-  Checked for inclusion of relevant tests
-  Checked for inclusion of a relevant changeset
-  Checked for creation of associated docs updates
-  Manually pulled down the changes and spot-tested

[Solarflare] Color tweaks for in curly brackets

---

.changeset/twenty-donkeys-drum.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/index.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/create-worker-upload-form.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/init.ts
packages/wrangler/src/publish/publish.ts
packages/wrangler/src/secret/index.ts
packages/wrangler/src/worker.ts

Adds support for the browser workers binding.

[wrangler] feat: Support for Browser Workers

---

packages/wrangler/src/generate/index.ts

Deprecate the generate command

[wrangler] Deprecate the `generate` command

---

.changeset/strange-schools-dream.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/__tests__/publish.test.ts
packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/create-worker-upload-form.ts
packages/wrangler/src/dev/remote.tsx
packages/wrangler/src/init.ts
packages/wrangler/src/publish/publish.ts
packages/wrangler/src/secret/index.ts
packages/wrangler/src/worker.ts

Reverts cloudflare/workers-sdk#3199

Revert "Support tail consumers via script metadata"

---

packages/create-cloudflare/src/cli.ts
packages/create-cloudflare/src/common.ts
packages/create-cloudflare/src/frameworks/angular/index.ts
packages/create-cloudflare/src/helpers/command.ts
packages/create-cloudflare/src/workers.ts

Includes a number of design tweaks, mostly copy changes.

[C3] Design tweaks

---

.changeset/early-bags-double.md
packages/pages-shared/asset-server/handler.ts

Add x-deployment-id header

---

.changeset/lazy-goats-rest.md
packages/create-cloudflare/src/helpers/files.ts

Fixes https://github.com/cloudflare/workers-sdk/issues/3240

[C3] fix: compatibility date format

---

.changeset/little-comics-push.md
packages/create-cloudflare/templates/common/js/wrangler.toml

Closes https://github.com/cloudflare/workers-sdk/issues/3252

[C3] Fix Worker path in JavaScript template

---

.changeset/five-rockets-hope.md
package-lock.json
packages/create-cloudflare/package.json
packages/create-cloudflare/src/helpers/command.ts

C3 now works on Windows.
We should include Windows in our CI builds to test this.

[C3] fix: support spawning new processes on Windows

---

.changeset/tall-countries-hide.md
packages/create-cloudflare/package.json

[C3] fix: ensure templates are included in deployed package

---

.github/workflows/test-c3.yml

Adds a workflow to run lint, typechecking, and tests on C3 prs.

Adding a new workflow for running checks on c3 prs

---

.changeset/heavy-points-fold.md
packages/wrangler/src/__tests__/init.test.ts
packages/wrangler/src/init.ts

fix: wrangler c3 args

---

packages/create-cloudflare/README.md

This PR updates the C3 README to include examples and additional arguments that users can use to create new apps via CLI.

[c3] update readme with examples

---

packages/wrangler/src/__tests__/d1/d1.test.ts
packages/wrangler/src/d1/index.ts
packages/wrangler/src/d1/info.tsx

```
> npx wrangler d1 info northwind --json
{
"uuid": "d5b1d127-1d3f-467e-953b-cbc69f0a9e06",
"name": "northwind",
"version": "beta",
"num_tables": 13,
"file_size": 33067008,
"running_in_region": "WEUR"
}
```
```
> npx wrangler d1 info northwind
┌───────────────────┬──────────────────────────────────────┐
│                   │ d5b1d127-1d3f-467e-953b-cbc69f0a9e06 │
├───────────────────┼──────────────────────────────────────┤
│ name              │ northwind                            │
├───────────────────┼──────────────────────────────────────┤
│ version           │ beta                                 │
├───────────────────┼──────────────────────────────────────┤
│ num_tables        │ 13                                   │
├───────────────────┼──────────────────────────────────────┤
│ …
```

Add `d1 info` command for people to check DB size

---

packages/quick-edit/functions/_middleware.ts
packages/quick-edit/patches/0001-Add-Custom-workbench-for-Cloudflare.patch
packages/quick-edit/patches/0002-Remove-Themes-from-Setting-SubMenu.patch
packages/quick-edit/patches/0003-Removed-Menu.patch
packages/quick-edit/patches/0004-Remove-Profile-from-Setting-SubMenu.patch
packages/quick-edit/patches/0005-Remove-Account-Extension.patch
packages/quick-edit/patches/0006-Remove-Debug-Icon-other-default-views.patch
packages/quick-edit/patches/0007-Remove-Source-Control.patch
packages/quick-edit/patches/0008-Remove-Custom-Menu-hamburger.patch
packages/quick-edit/patches/0009-Remove-Extensions-Icon-Quick-Access.patch
packages/quick-edit/patches/0010-Remove-dead-code.patch
packages/quick-edit/patches/0011-Support-project-wide-typescript-on-web.patch
packages/quick-edit/patches/0012-Remove-nls.patch

Fixes [DEVX-703](https://jira.cfdata.org/browse/DEVX-703).
VSCode was failing to load in some locales. This PR removes nls registration from VSCode, which we can evaluate bringing back at a future date once the details of bundling other locales is figured out.
- ~[ ] Tests~
- ~[ ] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))~

[quick-edit] fix locale

---

.changeset/six-bikes-yell.md
packages/wrangler/src/__tests__/d1/splitter.test.ts
packages/wrangler/src/__tests__/d1/trimmer.test.ts
packages/wrangler/src/d1/splitter.ts
packages/wrangler/src/d1/trimmer.ts

fix: trim transactions from SQLite sql dumps

---

packages/create-cloudflare/templates/common/js/wrangler.toml

refs https://github.com/cloudflare/workers-sdk/pull/3369

Fix R2 binding in wrangler.toml template

---

.changeset/itchy-experts-change.md
packages/wrangler/templates/d1-beta-facade.js

`D1_ERROR` becomes `D1_ERROR: error goes here`

[D1] lift error.cause into the error message

---

packages/wrangler/README.md

[wrangler] remove v2 from readme. update init command instructions.

---

.github/workflows/prerelease-create-cloudflare.yml

ci: fix up the C3 prerelease job

---

.github/workflows/quick-edit.yml

Fix Quick Edit build

---

packages/wrangler/e2e/deploy.test.ts
packages/wrangler/e2e/deployments.test.ts

Add e2e fixes for release

---

packages/wrangler/README.md

- Fix a typo in date format
- Capitalize some description to be consistent with existing documentation
- Update documentation url and reference to be consistent with full documentation
- Update sample toml section to be consistent with https://developers.cloudflare.com/workers/wrangler/configuration/ (where name is placed in first row)
- https://github.com/cloudflare/workers-sdk/blob/main/packages/wrangler/README.md

[wrangler] fix typo and minor updates in README.md

---

.changeset/yellow-cameras-swim.md
package-lock.json
package.json
packages/wranglerjs-compat-webpack-plugin/package.json
packages/wranglerjs-compat-webpack-plugin/src/index.ts

The upgrade provides a few performance benefits and reliability in different OS systems. see: https://github.com/isaacs/rimraf\#major-changes

Upgrade rimraf from v3 to v5 

---

.github/workflows/e2e.yml

Trigger e2e tests on the version packages PR automatically

Run e2e automatically on version packages PR

---

packages/edge-preview-authenticated-proxy/src/index.ts

This cleans up the Quick Edit sentry messaging in two ways:
- It no longer reports non-actionable errors to sentry
- It ensures extra info is attached to exceptions via context
It also adds CORS headers to returned error messages from the worker.

Cleanup sentry

---

packages/edge-preview-authenticated-proxy/src/index.ts

When an error is marked as non-reportable, don't report it. Follow on to #3537 

Only report reportable errors

---

fixtures/pages-ws-app/package.json
package-lock.json
packages/pages-shared/package.json
packages/wrangler/package.json

Bump Miniflare to `v3.20230628.0`

Bump Miniflare

---

.changeset/fluffy-steaks-wink.md
packages/wrangler/src/api/pages/deploy.tsx
packages/wrangler/src/deployment-bundle/bundle.ts
packages/wrangler/src/deployment-bundle/traverse-module-graph.ts
packages/wrangler/src/dev/use-esbuild.ts
packages/wrangler/src/module-collection.ts
packages/wrangler/src/pages/functions/buildWorker.ts

Fix issue with local dev not finding imported files on reload

---

.changeset/few-pens-cross.md
fixtures/pages-ws-app/package.json
package-lock.json
packages/pages-shared/package.json
packages/wrangler/package.json

Miniflare v3.20230710.0

---

CODEOWNERS

Fixes: N/A
Adds @cloudflare/wrangler team as reviewer to package changes in codeowners
N/A

Add wrangler team as reviewer to packages

---

.github/ISSUE_TEMPLATE/bug-template.yaml

Fixes: N/A
**What this PR solves / how to test:** This updates the issue template for bug reporting by requesting additional info and clarifying/updating the options in the products dropdown.

Update issue template

---

.changeset/thick-buckets-sip.md
packages/create-cloudflare/src/frameworks/solid/index.ts

C3: remove extra build added by mistake in solid deploy script

---

.github/extract-pr-and-workflow-id.js
.github/workflows/write-prerelease-comment.yml

ci: ensure that `fs` has been imported in the prerelease comment job.

---

.changeset/five-beans-admire.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/mtls-certificates.test.ts
packages/wrangler/src/__tests__/secret.test.ts
packages/wrangler/src/index.ts
packages/wrangler/src/secret/index.ts

Added functionality that allows for files and strings to be piped in, or other means of standard input. This will allow for a broader variety of use cases and improved DX.
This implementation is also fully backward compatible with the previous input method of file path to JSON.
- TODO

Feature: 'stdin' support for 'secret:bulk'

---

.github/workflows/main.yml
.github/workflows/prereleases.yml
.github/workflows/release.yml

Update workflows for maintenance branch to run releases and prereleases

Update workflows for maintenance branch to run releases and prereleases

---

.github/workflows/test-c3.yml

run C3 e2e tests only on internal PRs

---

.github/workflows/main.yml
.github/workflows/prereleases.yml
.github/workflows/release.yml

Customize the title of the release branch Changesets creates for the v2-maintenance branch

[🦋 Changesets] Legacy release branch

---

.changeset/clever-cooks-smell.md
packages/create-cloudflare/package.json
packages/create-cloudflare/src/cli.ts
packages/create-cloudflare/src/common.ts
packages/create-cloudflare/src/frameworks/next/index.ts
packages/create-cloudflare/src/helpers/__tests__/args.test.ts
packages/create-cloudflare/src/helpers/args.ts
packages/create-cloudflare/src/helpers/cli.ts
packages/create-cloudflare/src/helpers/command.ts
packages/create-cloudflare/src/helpers/interactive.ts
packages/create-cloudflare/src/pages.ts
packages/create-cloudflare/src/templateMap.ts
packages/create-cloudflare/src/types.ts
packages/create-cloudflare/src/workers.ts

C3: pass arguments to underlying CLIs

---

.changeset/fuzzy-flowers-kneel.md
fixtures/pages-simple-assets/tests/index.test.ts
packages/wrangler/src/miniflare-cli/assets.ts

Applies #3498 to the v2-maintenance branch.

#3498 on v2

---

.changeset/thin-falcons-yell.md
packages/create-cloudflare/src/cli.ts
packages/create-cloudflare/src/helpers/__tests__/args.test.ts
packages/create-cloudflare/src/helpers/args.ts

C3: Improve arguments handling

---

packages/playground-preview-worker/wrangler.json

An associated secrets change will be made after this PR lands (this is not released yet, and so some downtime is acceptable)

Move internal account

---

packages/edge-preview-authenticated-proxy/package.json
packages/playground-preview-worker/package.json

Change packages to use `vitest run` instead of `vitest`

---

.github/workflows/quick-edit.yml
.npmrc
packages/format-errors/package.json
pnpm-lock.yaml

`pnpm` followup

---

packages/playground-preview-worker/wrangler.json

Update playground preview worker zone

---

.changeset/lazy-beers-return.md

Adding more details to the changeset for Wrangler R2 jurisdiction support.
- [ n/a] Tests
- [ y] Changeset ([Changeset guidelines](https://github.com/cloudflare/workers-sdk/blob/main/CONTRIBUTING.md#changesets))

Update changeset for Wrangler R2 jurisdiction support

---

.github/workflows/release.yml
packages/create-cloudflare/.npmrc
packages/wrangler/.npmrc

Reverts cloudflare/workers-sdk#3943

Revert "Output .npmrc in CI release job"

---

.changeset/cool-baboons-lick.md
packages/wrangler/src/pages/dev.ts

Currently `wrangler pages dev --help` doesn't provide useful/correct information on how to add a DO binding, I think that the yargs description update simply got missed in https://github.com/cloudflare/workers-sdk/pull/1641

update `wrangler pages dev` D1 and DO descriptions

---

.github/workflows/test-c3.yml
packages/create-cloudflare/e2e-tests/pages.test.ts

- fix wrong needs step name used in test-c3 yml
- quarantine c3 remix e2e tests

Fix C3 e2es currently not passing

---

packages/playground-preview-worker/wrangler.json
packages/workers-playground/.env
packages/workers-playground/.gitignore
packages/workers-playground/src/QuickEditor/useDraftWorker.ts

Switch to cloudflarepreviews.com

---

.changeset/shiny-rats-hide.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/config/config.ts
packages/wrangler/src/config/validation.ts

Reverts cloudflare/workers-sdk#3733

Revert "Default local dev server to `*`"

---

packages/wrangler/package.json
pnpm-lock.yaml

2 major version upgrade
changelogs: https://github.com/rivy/js.xdg-app-paths/blob/master/CHANGELOG.mkd

Upgrade XDG package

---

.changeset/nine-stingrays-hammer.md
fixtures/pages-ws-app/package.json
packages/pages-shared/package.json
packages/wrangler/package.json
pnpm-lock.yaml

Bump `miniflare` to 20230922

---

packages/create-cloudflare/e2e-tests/helpers.ts
packages/create-cloudflare/e2e-tests/pages.test.ts

Make gatsby e2e tests pass

---

packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/config/validation.ts
packages/wrangler/src/dev.tsx

Remove obsolete messaging

---

.github/workflows/deploy-pages-project.yml

Fixes a tiny issue where this workflow doesn't have a name in the action list:

Add a name to deploy-pages-project.yml workflow

---

fixtures/service-bindings-app/a/index.ts
fixtures/service-bindings-app/a/wrangler.toml
fixtures/service-bindings-app/b/wrangler.toml
fixtures/service-bindings-app/tests/index.test.ts
packages/wrangler/templates/middleware/middleware-multiworker-dev.ts

use `Fetcher` constructor

---

.github/workflows/issues.yml
.github/workflows/pullrequests.yml

Fixes N/A
**What this PR solves / how to test:** 
This PR updates the workflow for adding items to relevant GH projects:
* Not only do newly opened issues get sorted, but now also newly labeled, unlabeled, or transfered issues do as well. 
* Issues can now be sorted into C3 and Queues projects.
* Opened PRs are assigned to the workers-sdk project. Note: most PRs don't get labeled, so this does not include automatic sorting based on labels for now, but this can be changed.
- Manually pulled down the …

Update issues workflow

---

.github/workflows/pullrequests.yml

Add PRs from forks to GitHub project

---

.changeset/serious-beans-hug.md
.changeset/warm-queens-taste.md
fixtures/pages-ws-app/package.json
packages/pages-shared/package.json
packages/wrangler/package.json
pnpm-lock.yaml

Bump miniflare to `3.20231010.0`

---

.github/workflows/pullrequests.yml

Add repo specifier to "Add to PR" action

---

.changeset/eight-foxes-reply.md
packages/workers-tsconfig/tsconfig.json
packages/wrangler/api-extractor.json
packages/wrangler/e2e/tsconfig.json
packages/wrangler/tsconfig.emit.json

Fix wrangler generated types to match runtime exports

---

.changeset/great-onions-sit.md
fixtures/pages-ws-app/package.json
packages/pages-shared/package.json
packages/wrangler/package.json
pnpm-lock.yaml

chore: bump miniflare to 3.20231016.0

chore: bump `miniflare` to `3.20231016.0`

---

.changeset/dry-days-judge.md
packages/create-cloudflare/e2e-tests/pages.test.ts
packages/create-cloudflare/src/frameworks/angular/index.ts
packages/create-cloudflare/src/frameworks/astro/index.ts
packages/create-cloudflare/src/frameworks/docusaurus/index.ts
packages/create-cloudflare/src/frameworks/gatsby/index.ts
packages/create-cloudflare/src/frameworks/hono/index.ts
packages/create-cloudflare/src/frameworks/next/index.ts
packages/create-cloudflare/src/frameworks/nuxt/index.ts
packages/create-cloudflare/src/frameworks/qwik/index.ts
packages/create-cloudflare/src/frameworks/react/index.ts
packages/create-cloudflare/src/frameworks/remix/index.ts
packages/create-cloudflare/src/frameworks/solid/index.ts
packages/create-cloudflare/src/frameworks/svelte/index.ts
packages/create-cloudflare/src/frameworks/vue/index.ts
packages/create-cloudflare/src/helpers/files.ts
packages/create-cloudflare/src/pages.ts
packages/create-cloudflare/src/types.ts

Fixes the following warning for web applications created by C3:

C3: Set proper compatibility date for web applications

---

packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/standard-pricing.test.ts
packages/wrangler/src/deploy/index.ts
pnpm-lock.yaml

Fixes https://jira.cfdata.org/browse/DEVX-985

Standard Pricing messaging

---

turbo.json

Ensure Turborepo doesn't share cache across OSs

---

package.json

Disable flakey tests

---

.changeset/good-beers-design.md
fixtures/pages-plugin-mounted-on-root-app/tests/index.test.ts
fixtures/pages-ws-app/package.json
packages/pages-shared/package.json
packages/wrangler/package.json
packages/wrangler/src/dev/local.tsx
pnpm-lock.yaml

Bump miniflare version to 20231023

---

packages/wrangler/e2e/c3-integration.test.ts
packages/wrangler/e2e/deploy.test.ts
packages/wrangler/e2e/deployments.test.ts
packages/wrangler/e2e/helpers/account-id.ts
packages/wrangler/e2e/helpers/wrangler-command.ts

Update e2e snapshots for Standard pricing

---

.github/changeset-version.js

In the `changeset-version.js` script, we were replacing version headers in `CHANGELOG.md` but not `Updated dependencies`, meaning there were some dangling references to non-existent `miniflare` versions.
- Tests

fix: ensure `Updated dependencies` version correct in `CHANGELOG.md`s

---

.github/ISSUE_TEMPLATE/bug-template.yaml

Tiny PR to add `Miniflare` as a product in bug reports, now that it lives in `workers-sdk`. 🙂 
- Tests

Add Miniflare to bug report template

---

.changeset/many-islands-roll.md
packages/create-cloudflare/e2e-tests/pages.test.ts
packages/create-cloudflare/src/helpers/command.ts

Sorry for breaking C3 e2e tests on main.

test: fix C3 e2e tests for Angular

---

templates/stream/playback/vidstack/README.md
templates/stream/playback/vidstack/src/index.html

Hey there! I'm the author of Vidstack Player and I'm just updating the stream example because it was outdated. I also fixed a broken link in the README accidentally pointing to the `video.js` example. Hope everything is in order, happy to discuss/fix.

Update Vidstack stream template

---

.changeset/rotten-keys-occur.md
packages/wrangler/src/tail/index.ts

Reverts cloudflare/workers-sdk#4350

Revert "tail: add a --yes flag to bypass the DO prompt"

---

fixtures/external-durable-objects-app/tests/index.test.ts
fixtures/external-service-bindings-app/tests/index.test.ts

Skip flaky tests

---

.changeset/itchy-days-greet.md
packages/create-cloudflare/e2e-tests/cli.test.ts
packages/create-cloudflare/src/helpers/cli.ts
packages/create-cloudflare/src/helpers/command.ts
packages/create-cloudflare/src/templateMap.ts

This reverts commit 5f54f72f15329f47f257f6ae458320a064665347.
We need to do a hot-fix release for Wrangler but we don't want to release this C3 change just yet. After the release, I will unrevert this commit
- Tests

Revert "C3: Change default project type to hello world worker (#4442)"

---

.changeset/flat-hotels-add.md
packages/wrangler/src/__tests__/constellation.test.ts
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/constellation/index.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/index.ts

Run wrangler constellation and see the new warning
- Tests

Deprecate constellation commands and add a warning when using the constellation binding

---

.changeset/brown-moose-deny.md
.changeset/popular-tigers-matter.md
.changeset/rude-walls-sin.md
.changeset/sweet-dots-look.md

This PR cleans up the associated changesets from #4310 to more accurately describe the changes in each package.
- Tests

Clean up changesets from #4310

---

fixtures/dev-env/tests/index.test.ts

Fixes N/A.
**What this PR solves / how to test:** https://github.com/cloudflare/workers-sdk/blob/d031e75a505f2886733d153bd808364866aec2e3/fixtures/dev-env/tests/index.test.ts#L62 notes that it should be removed once internal ticket DEVX-983 is addressed. DEVX-983 was addressed in wrangler v3.19.0, so this PR removes the stale/unnecessary line.
- Tests

Remove unnecessary log assignment

---

packages/format-errors/wrangler.toml

[format-errors] whitespace

---

.changeset/forty-boxes-lay.md
.changeset/slow-trains-confess.md
packages/create-cloudflare/src/frameworks/package.json
packages/create-cloudflare/templates/next/c3.ts
packages/create-cloudflare/templates/next/templates.ts

C3: bump `create-next-app` and handle new `next.config.mjs` defaults

---

packages/playground-preview-worker/src/index.ts
packages/playground-preview-worker/tests/index.test.ts

Previously, we were passing user-controllable token inputs (`X-CF-Token` header, `user` search param, `token` cookie) directly to the `DurableObjectNamespace#idFromString()` function. This validated the token to be a valid Durable Object ID, but threw a reportable `TypeError`, generating a 500 response and increasing the errored request count. This is a user error, so shouldn't be reported. This change wraps calls to `idFromString()` inside `try`/`catch`es, and re-throws non-reportable user errors that generate 4xx responses. We could just validate that the tokens were 64 hex digits before calling `idFromString()`, but this approach ensures the IDs are for the `UserSession` object by validating the signature encoded in the ID too.
I've added some new …

fix: return 4xx error from playground preview worker on invalid tokens

---

.changeset/gentle-chairs-pull.md
packages/miniflare/README.md
packages/miniflare/src/index.ts
packages/miniflare/test/index.spec.ts

expose cf object from Miniflare instances

---

.github/workflows/deploy-pages-projects.yml
packages/quick-edit/README.md
packages/workers-playground/README.md
packages/wrangler-devtools/README.md

docs: updated descriptions and instructions in READMEs and Actions for Pages project in the monorepo

---

.github/changeset-version.js
fixtures/sites-app/package.json
package.json
pnpm-lock.yaml

Fixes broken "Release" CI action in GitHub.
- Tests

Changeset debugging

---

packages/wrangler/CHANGELOG.md

Simple update to the Changelog for Wrangler.

Add missing entry to changelog for Wrangler 3.28.3

---

fixtures/dev-env/tests/index.test.ts
fixtures/get-bindings-proxy/tests/get-bindings-proxy.bindings.test.ts
fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
fixtures/no-bundle-import/src/index.test.ts
fixtures/worker-app/tests/index.test.ts
packages/create-cloudflare/src/__tests__/workers.test.ts
packages/create-cloudflare/src/helpers/__tests__/command.test.ts
packages/edge-preview-authenticated-proxy/tests/index.test.ts
vitest.shared.ts

This PR just hides some of the output that makes the CI logs really messy.

Remove unnecessary stdout from test output

---

.github/ISSUE_TEMPLATE/bug-template.yaml

Fixes N/A.
Adds dropdown item to issue template for kv asset handler.
- Tests

Add dropdown item for kv asset handler to issue template

---

tools/deployments/__tests__/deploy-non-npm-packages.test.ts

test: use the correct afterEach in deploy-non-npm-packages tests

---

.changeset/hungry-cougars-tie.md
.changeset/sour-mugs-rule.md
packages/wrangler/src/__tests__/d1/execute.test.ts
packages/wrangler/src/__tests__/d1/migrate.test.ts
packages/wrangler/src/__tests__/d1/utils.test.ts
packages/wrangler/src/d1/execute.tsx
packages/wrangler/src/d1/migrations/apply.tsx
packages/wrangler/src/d1/migrations/create.tsx
packages/wrangler/src/d1/migrations/helpers.ts
packages/wrangler/src/d1/migrations/list.tsx
packages/wrangler/src/d1/migrations/options.ts

Add a local-first `wrangler d1 execute` to `wrangler@d1`

---

.changeset/seven-taxis-sort.md
packages/create-cloudflare/e2e-tests/frameworks.test.ts
packages/create-cloudflare/templates/solid/c3.ts

Updates the SolidStart template to be compatible with the latest version of `create-solid`
- Tests
- [ x ] Not necessary because: No user facing changes

C3: Update SolidStart template to work with create-solid@0.5.3

---

.github/workflows/README.md
.github/workflows/d1.yml

Was wondering why our preview tag wasn't working any more.

Restore deleted D1 CI pipeline

---

.changeset/hungry-cougars-tie.md
.changeset/sour-mugs-rule.md
packages/wrangler/src/__tests__/d1/execute.test.ts
packages/wrangler/src/__tests__/d1/migrate.test.ts
packages/wrangler/src/__tests__/d1/utils.test.ts
packages/wrangler/src/d1/execute.tsx
packages/wrangler/src/d1/migrations/apply.tsx
packages/wrangler/src/d1/migrations/create.tsx
packages/wrangler/src/d1/migrations/helpers.ts
packages/wrangler/src/d1/migrations/list.tsx
packages/wrangler/src/d1/migrations/options.ts

Publish into `wrangler@d1`

---

.changeset/hungry-flowers-grow.md
packages/workers-playground/welcome/index.py

Rename `fetch` to `on_fetch` in Python workers
- Tests

Rename `fetch` to `on_fetch`

---

.changeset/friendly-jobs-serve.md
packages/create-cloudflare/e2e-tests/frameworks.test.ts
packages/create-cloudflare/package.json

Fixes a malformed changeset.
- Tests

[C3] Fix bad changeset

---

.changeset/bright-hotels-speak.md

Adds changeset for `miniflare`
- Tests

Add miniflare changeset

---

.changeset/silver-frogs-cover.md
packages/create-cloudflare/src/helpers/__tests__/args.test.ts
packages/create-cloudflare/src/helpers/args.ts

[C3] Require arguments for flags that expect them

---

.changeset/proud-flowers-move.md
packages/create-cloudflare/templates/astro/templates/wrangler.toml
packages/create-cloudflare/templates/common/js/wrangler.toml
packages/create-cloudflare/templates/common/ts/wrangler.toml
packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.toml
packages/create-cloudflare/templates/hello-world-durable-object/ts/wrangler.toml
packages/create-cloudflare/templates/hello-world/js/wrangler.toml
packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
packages/create-cloudflare/templates/next/wrangler.toml
packages/create-cloudflare/templates/nuxt/templates/wrangler.toml
packages/create-cloudflare/templates/queues/js/wrangler.toml
packages/create-cloudflare/templates/queues/ts/wrangler.toml
packages/create-cloudflare/templates/qwik/templates/wrangler.toml
packages/create-cloudflare/templates/remix/templates/wrangler.toml
packages/create-cloudflare/templates/scheduled/js/wrangler.toml
packages/create-cloudflare/templates/scheduled/ts/wrangler.toml
packages/create-cloudflare/templates/svelte/js/wrangler.toml
packages/create-cloudflare/templates/svelte/ts/wrangler.toml

Updates the commented out sections of the default `wrangler.toml` in templates to include recent features. Also updates the documentation links to the appropriate section of the bindings docs. 
- Tests

[C3] Update wrangler.toml in templates

---

.changeset/lazy-cherries-build.md

docs: fix typo in changeset

---

fixtures/python-worker/src/index.py
packages/wrangler/e2e/dev.test.ts

follow up fix to https://github.com/cloudflare/workers-sdk/pull/5196

fix python fetch to on_fetch

---

.changeset/breezy-badgers-play.md

fix changesets

---

.changeset/rude-mice-study.md
packages/wrangler/src/user/user.ts

Ignore OPTIONS requests in Oauth server

---

CONTRIBUTING.md
packages/cli/interactive.ts
packages/wrangler/e2e/versions.test.ts

Adding e2e tests for Versions.
Also added a section to CONTRIBUTING.md to explain how to run the e2e tests locally
- Tests

Add e2e tests for Versions

---

.changeset/seven-news-enjoy.md
packages/wrangler/src/__tests__/pages/deploy.test.ts
packages/wrangler/src/api/pages/deploy.tsx
packages/wrangler/src/pages/build.ts
packages/wrangler/src/pages/dev.ts
packages/wrangler/src/pages/functions/buildWorker.ts

Respect --no-bundle when deploying a _worker.js/ directory in a Pages project

---

packages/wrangler/e2e/versions.test.ts

Updates snapshots which were missed in a previously merged PR.
- Tests

update e2e snapshots for versions commands

---

packages/wrangler/e2e/c3-integration.test.ts
packages/wrangler/e2e/deployments.test.ts

I forgot to update e2e snapshots in https://github.com/cloudflare/workers-sdk/pull/5400
- Tests

update e2e snapshots

---

.changeset/big-pumas-count.md
packages/wrangler/src/deploy/deploy.ts
packages/wrangler/src/triggers/deploy.ts
packages/wrangler/src/triggers/index.ts

This PR fixes the changeset grammar and removes some dead code
- Tests

Fix nits from #5426

---

.changeset/rare-toys-wave.md
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/__tests__/r2/helpers.test.ts
packages/wrangler/src/queues/client.ts
packages/wrangler/src/r2/helpers.ts
packages/wrangler/src/r2/index.ts
packages/wrangler/src/r2/notification.ts

Add 'get-bucket-notification-cfg' subcmd for R2

---

.changeset/forgot-a-changeset.md

🤦 Add a changeset for #5470

---

.changeset/kind-lies-beg.md
packages/create-cloudflare/e2e-tests/frameworks.test.ts
packages/create-cloudflare/e2e-tests/workers.test.ts
packages/create-cloudflare/package.json
packages/create-cloudflare/src/help.ts
packages/create-cloudflare/src/helpers/__tests__/args.test.ts
packages/create-cloudflare/src/helpers/args.ts
packages/create-cloudflare/src/helpers/cli.ts
packages/create-cloudflare/src/types.ts
pnpm-lock.yaml

Overhauls the output of c3's --help to improve readability and provide more information.
Uses a custom help implementation rather than the one built into `yargs` which has a number of pitfalls when it comes to formatting multiline text and lists of options.
Before:
After:
- Tests
- [xg] Included

C3: Improve help output

---

.changeset/small-buckets-cheat.md
packages/wrangler/src/__tests__/cloudchamber/create.test.ts
packages/wrangler/src/__tests__/cloudchamber/delete.test.ts
packages/wrangler/src/__tests__/cloudchamber/list.test.ts
packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
packages/wrangler/src/__tests__/helpers/mock-cloudchamber.ts
packages/wrangler/src/cloudchamber/common.ts
packages/wrangler/src/cloudchamber/create.ts
packages/wrangler/src/cloudchamber/delete.ts
packages/wrangler/src/cloudchamber/list.ts
packages/wrangler/src/cloudchamber/modify.ts
packages/wrangler/src/cloudchamber/network/network.ts

Support for Cloudchamber deployment labels

---

.changeset/stale-trainers-suffer.md
packages/wrangler/src/__tests__/hyperdrive.test.ts
packages/wrangler/src/hyperdrive/client.ts
packages/wrangler/src/hyperdrive/create.ts
packages/wrangler/src/hyperdrive/update.ts

wrangler: Fix Hyperdrive caching options in create and update commands

---

.changeset/good-wombats-type.md
packages/wrangler/e2e/dev.test.ts
packages/wrangler/src/__tests__/hyperdrive.test.ts
packages/wrangler/src/hyperdrive/client.ts
packages/wrangler/src/hyperdrive/create.ts
packages/wrangler/src/hyperdrive/update.ts

Reverts cloudflare/workers-sdk#4932

Revert "Add private host option for private networks support in hyperdrive"

---

packages/wrangler/e2e/dev.test.ts

Fix hyperdrive e2e

---

.changeset/sixty-ads-wink.md
packages/wrangler/src/__tests__/d1/create.test.ts
packages/wrangler/src/__tests__/d1/info.test.ts
packages/wrangler/src/d1/constants.ts
packages/wrangler/src/d1/create.tsx
packages/wrangler/src/d1/info.tsx

This PR teaches wrangler about Australia, and fixes up some loose ends.
Fixes #5505 
- Tests

[D1] teach wrangler about Australia

---

.changeset/unlucky-laws-fetch.md
packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
packages/wrangler/src/__tests__/helpers/msw/index.ts
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/r2/helpers.ts
packages/wrangler/src/r2/index.ts

Not exempt from LDW, but I would like to get this reviewed before next week.
Fixes R2-1963
- Tests

Add Wrangler support for R2 storage classes

---

packages/wrangler/e2e/r2.test.ts

fix r2 e2e

---

.changeset/wise-lemons-remain.md
packages/wrangler/e2e/dev.test.ts
packages/wrangler/src/deployment-bundle/find-additional-modules.ts

Fixes EW-8270. Revised version of #5375 ; this PR is separate because they're both done with forks. 
- Tests

Skip comments in requirements and test dependencies

---

.changeset/wise-lemons-remain.md
packages/wrangler/e2e/dev.test.ts
packages/wrangler/src/deployment-bundle/find-additional-modules.ts

This PR actually introduced a broken e2e test. See https://github.com/cloudflare/workers-sdk/pull/5398#issuecomment-2051788913
So I am reverting in order to run the release.
@garrettgu10 please can you fix that and create a new PR to land this.
Reverts cloudflare/workers-sdk#5398

Revert "Skip comments in requirements and test dependencies"

---

.changeset/swift-steaks-cheat.md
.github/workflows/changesets.yml
package.json
pnpm-lock.yaml
tools/deployments/__tests__/validate-changesets.test.ts
tools/deployments/validate-changesets.ts

* fix version bump type of changeset that is broken
* add a changeset format validator to the "Handle Changesets" CI job

Fix changeset and add validation

---

.changeset/serious-socks-grab.md
packages/create-cloudflare/templates/hello-world-durable-object/js/src/index.js
packages/create-cloudflare/templates/hello-world-durable-object/ts/package.json
packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts

Replaces https://github.com/cloudflare/workers-sdk/pull/5624.
- Tests

Change Durable Objects "Hello, World!" template to use RPC methods

---

.changeset/flat-clouds-punch.md
packages/wrangler/package.json
pnpm-lock.yaml

[wrangler] mark `ts-json-schema-generator` as a dev dependency

---

packages/wrangler/src/user/auth-variables.ts

chore: update comment for using staging

---

.changeset/rare-papayas-divide.md
packages/wrangler/src/__tests__/configuration.test.ts
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
packages/wrangler/src/config-cache.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/init.ts
packages/wrangler/src/versions/deploy.ts

fix(wrangler): broken link in cli

---

.github/workflows/prereleases.yml
fixtures/interactive-dev-tests/package.json
pnpm-lock.yaml

1. Make sure `create-cloudflare` beta versions have the right version
2. Update `interactive-dev-tests` to depend on `fixtures-shared`
- Tests

Turborepo fixups

---

.changeset/wicked-donkeys-yell.md
fixtures/get-platform-proxy/.dev.vars.production
fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
fixtures/get-platform-proxy/wrangler.toml
packages/wrangler/src/api/integrations/platform/index.ts
packages/wrangler/src/config/index.ts

[wrangler] feat: add support for environments in `getPlatformProxy`

---

package.json

Make tests run sequentially

---

fixtures/ai-app/tests/index.test.ts

The next workerd version, includes some changes in the ai binding, this pr fixes the tests that will start failing
- Tests

Fix ai binding tests

---

.github/pull_request_template.md

Highlights to PR authors that they should read the contributing guide and discuss complex changes before submitting a PR.

docs: highlight contributing guide in PR template

---

.prettierignore

Ignore changelogs

---

.github/workflows/c3-e2e-dependabot.yml
.github/workflows/c3-e2e-quarantine.yml
.github/workflows/c3-e2e.yml

Fix e2e test naming

---

packages/create-cloudflare/templates/hello-world-durable-object/js/src/index.js
packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts

chore: Fixes typo

---

CODEOWNERS

Since the "Workers Authoring and Testing" team basically own this bit of code now, we should be able to review and approve changes to it.
- Tests

chore: add wrangler team as additional CODEOWNERS of the pages-shared package

---

packages/vitest-pool-workers/package.json
packages/vitest-pool-workers/src/pool/index.ts
packages/vitest-pool-workers/src/worker/index.ts
packages/vitest-pool-workers/test/README.md
packages/vitest-pool-workers/test/chunking.test.ts
packages/vitest-pool-workers/test/console.test.ts
packages/vitest-pool-workers/test/env.d.ts
packages/vitest-pool-workers/test/global-setup.ts
packages/vitest-pool-workers/test/helpers.ts
packages/vitest-pool-workers/test/isolation.test.ts
packages/vitest-pool-workers/test/snapshots.test.ts
packages/vitest-pool-workers/test/validation.test.ts
packages/vitest-pool-workers/test/watch.test.ts
packages/vitest-pool-workers/tsconfig.json
packages/vitest-pool-workers/vitest.config.ts
pnpm-lock.yaml

Implement vitest pool e2e meta tests

---

.changeset/brave-goats-end.md
fixtures/vitest-pool-workers-examples/basics-unit-integration-self/test/fetch-integration-self.test.ts
fixtures/vitest-pool-workers-examples/basics-unit-integration-self/test/scheduled-integration-self.test.ts
fixtures/vitest-pool-workers-examples/hyperdrive/test/echo.test.ts
fixtures/vitest-pool-workers-examples/kv-r2-caches/test/kv.test.ts
fixtures/vitest-pool-workers-examples/pages-functions-unit-integration-self/test/integration-self.test.ts
fixtures/vitest-pool-workers-examples/queues/test/queue-consumer-integration-self.test.ts
fixtures/vitest-pool-workers-examples/queues/test/queue-producer-integration-self.test.ts
fixtures/vitest-pool-workers-examples/request-mocking/test/declarative.test.ts
fixtures/vitest-pool-workers-examples/request-mocking/test/imperative.test.ts
fixtures/vitest-pool-workers-examples/web-assembly/test/add.test.ts
packages/vitest-pool-workers/src/config/index.ts
packages/vitest-pool-workers/src/pool/config.ts
packages/vitest-pool-workers/src/pool/index.ts
packages/vitest-pool-workers/src/worker/lib/cloudflare/test.ts
packages/vitest-pool-workers/test/watch.test.ts

Fixes [#5384](https://github.com/cloudflare/workers-sdk/issues/5384)
- Tests

Vitest pool workers self test without import

---

packages/vitest-pool-workers/src/worker/lib/node/module.ts

Small refactoring to make it easier to debug errors.
Resolves #5390

refactor: improve debuging for a couple internal errors

---

.changeset/dry-buttons-deliver.md
.prettierrc
fixtures/vitest-pool-workers-examples/README.md
fixtures/vitest-pool-workers-examples/package.json
fixtures/vitest-pool-workers-examples/rpc/README.md
fixtures/vitest-pool-workers-examples/rpc/src/env.d.ts
fixtures/vitest-pool-workers-examples/rpc/src/index.ts
fixtures/vitest-pool-workers-examples/rpc/src/tsconfig.json
fixtures/vitest-pool-workers-examples/rpc/test/env.d.ts
fixtures/vitest-pool-workers-examples/rpc/test/integration-self.test.ts
fixtures/vitest-pool-workers-examples/rpc/test/tsconfig.json
fixtures/vitest-pool-workers-examples/rpc/test/unit.test.ts
fixtures/vitest-pool-workers-examples/rpc/tsconfig.json
fixtures/vitest-pool-workers-examples/rpc/vitest.config.ts
fixtures/vitest-pool-workers-examples/rpc/wrangler.toml
packages/vitest-pool-workers/package.json
packages/vitest-pool-workers/scripts/bundle.mjs
packages/vitest-pool-workers/scripts/rtti/query.mjs
packages/vitest-pool-workers/src/pool/index.ts
packages/vitest-pool-workers/src/pool/loopback.ts
packages/vitest-pool-workers/src/worker/durable-objects.ts
packages/vitest-pool-workers/src/worker/entrypoints.ts
packages/vitest-pool-workers/src/worker/index.ts
packages/vitest-pool-workers/src/worker/lib/cloudflare/test-internal.ts
packages/vitest-pool-workers/src/worker/types-ambient.d.ts
packages/vitest-pool-workers/src/worker/types-globals.d.ts
packages/vitest-pool-workers/src/worker/wait-until.ts
packages/vitest-pool-workers/test/validation.test.ts
packages/wrangler/src/api/integrations/platform/index.ts
pnpm-lock.yaml

Fixes #5386 
Fixes #5389
- Tests

feature: add support for JSRPC

---

tools/deployments/__tests__/deploy-non-npm-packages.test.ts
tools/deployments/__tests__/validate-changesets.test.ts

Fix failing tests in `./tools`

---

.changeset/seven-bees-admire.md
packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.toml

Updates DO template entry point
- Tests

fix: Updates DO Template Entry point

---

.changeset/green-turtles-care.md
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/kv/index.ts
tools/deployments/__tests__/deploy-non-npm-packages.test.ts
tools/deployments/__tests__/validate-changesets.test.ts

Update create KV namespace message and test

---

.changeset/gold-squids-give.md
packages/create-cloudflare/e2e-tests/cli.test.ts
packages/create-cloudflare/src/templates.ts
packages/create-cloudflare/templates/hello-world-durable-object/c3.ts

Makes it clearer what a "Durable Object" is. A user using c3 or Cloudflare for the first time will have no idea. I have also moved it down the list so that "web application" (a far more common use-case) is higher. 
- Tests

c3: update DO example

---

packages/wrangler/src/pages/upload.tsx

Fixes https://github.com/cloudflare/workers-sdk/issues/1586 (I think, at least for me).
I checked this helps by modifying my `node_modules` installed version. I'm pretty sure I copied over the edits, but not completely sure. Is there a way to test this? I'm not too familiar with JS and package managers.
- Tests

Batch file uploads to avoid EMFILE

---

.changeset/eleven-cows-marry.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/__tests__/versions/versions.help.test.ts
packages/wrangler/src/index.ts
packages/wrangler/src/kv/index.ts

Rename kv:* commands

---

packages/wrangler/e2e/dev-with-resources.test.ts
packages/wrangler/e2e/helpers/e2e-wrangler-test.ts

update e2e kv command usage

---

.changeset/flat-days-punch.md
fixtures/nodejs-hybrid-app/src/index.ts
fixtures/nodejs-hybrid-app/wrangler.toml
fixtures/unstable_dev/package.json
packages/wrangler/src/deployment-bundle/node-compat.ts
pnpm-lock.yaml

Nodejs hybrid fixups

---

.changeset/fluffy-bees-shout.md
packages/wrangler/src/pages/upload.tsx

Reverts cloudflare/workers-sdk#5632

Revert "Batch file uploads to avoid EMFILE"

---

STYLEGUIDE.md

Will be fixed live in front of a studio audience tomorrow!

Intentional typo for demo

---

STYLEGUIDE.md

Fix typo in STYLEGUIDE.md

---

.github/workflows/c3-e2e-dependabot.yml
.github/workflows/c3-e2e.yml

It is possible that because of this we were not testing C3 against yarn!

ci: fix typos in C3 E2E actions

---

.github/workflows/c3-e2e-quarantine.yml

Let's not run Quarantine tests for PRs at all

don't run quarantine tests on pull requests

---

packages/miniflare/scripts/build.mjs

Fixes https://github.com/cloudflare/workers-sdk/issues/6042
runing `pnpm dev` used to start a watch mode, but I removed that in https://github.com/cloudflare/workers-sdk/pull/6029 because the esbuild watch api was changed. This patch brings it back with the new api.
--
No changeset or e2e tests for this one.

fix: bring back miniflare's watch-and-build

---

.changeset/wise-ravens-mate.md
packages/wrangler/src/r2/index.ts

[r2] Allow Large Uploads in Local Wrangler

---

packages/wrangler/src/__tests__/hybrid-nodejs-compat.test.ts
packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts

Follow up on  https://github.com/cloudflare/workers-sdk/pull/6025 that makes
the code a bit more resilient.
- Tests

fix: node compat v2 handle $ in inject preset

---

.github/workflows/holopin.yml

Whoops! Made a small copy-paste error in #6087. Should have deleted this line.

Fix Holopin GitHub Action

---

packages/wrangler/src/config/environment.ts

Fixes a typo in `environment.ts`
- Tests

Fix typo in environment.ts

---

.changeset/brave-doors-visit.md
packages/wrangler/src/__tests__/helpers/msw/handlers/versions.ts
packages/wrangler/src/__tests__/rollback.test.ts
packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
packages/wrangler/src/__tests__/versions/secrets/put.test.ts
packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
packages/wrangler/src/__tests__/versions/versions.view.test.ts
packages/wrangler/src/versions/api.ts
packages/wrangler/src/versions/rollback/index.ts
packages/wrangler/src/versions/secrets/bulk.ts
packages/wrangler/src/versions/secrets/delete.ts
packages/wrangler/src/versions/secrets/put.ts
packages/wrangler/src/versions/view.ts

Fixes rollback in interactive mode, improves the `versions view` command and small message changes to secret put/delete/bulk.
- Tests

Version followups - fix rollback, version view improvements

---

packages/wrangler/src/cloudchamber/common.ts
packages/wrangler/src/cloudchamber/create.ts

Adds guidance on cloudchamber registry commands

---

packages/wrangler/e2e/versions.test.ts

Fixes versions e2e tests that started failing after we merged #6118
- Tests

fix(wrangler): fix failing versions e2e tests

---

packages/create-cloudflare/e2e-tests/frameworks.test.ts

unquarantine C3 nuxt e2es

---

.prettierrc
fixtures/remix-pages-app/package.json
fixtures/vitest-pool-workers-examples/package.json
package.json
packages/create-cloudflare/templates/common/ts/package.json
packages/create-cloudflare/templates/hello-world-durable-object/ts/package.json
packages/create-cloudflare/templates/hello-world/ts/package.json
packages/create-cloudflare/templates/queues/ts/package.json
packages/create-cloudflare/templates/scheduled/ts/package.json
packages/vitest-pool-workers/package.json
packages/vitest-pool-workers/src/worker/lib/mlly.ts
packages/wrangler/src/versions/secrets/index.ts
pnpm-lock.yaml

Updating this so we can play with isolateDeclarations later
- Tests

update typescript to 5.5.2

---

packages/wrangler/src/__tests__/d1/create.test.ts
packages/wrangler/src/__tests__/d1/info.test.ts
packages/wrangler/src/__tests__/d1/migrate.test.ts
packages/wrangler/src/__tests__/d1/timeTravel.test.ts
packages/wrangler/src/__tests__/fetch-graphql-result.test.ts
packages/wrangler/src/__tests__/helpers/mock-oauth-flow.ts

Resolves https://github.com/cloudflare/workers-sdk/issues/6132

refactor: remove unnecessary use of `mockOAuthFlow()`

---

.changeset/mighty-humans-wink.md
packages/devprod-status-bot/src/index.ts

Add edmund and emily to the DevProdStatusBot

---

packages/pages-shared/README.md
packages/wrangler/src/pages/README.md

Resolves https://jira.cfdata.org/browse/DEVX-1239
- Tests

docs: add notes about extra care when updating Pages code

---

tools/e2e/runIndividualE2EFiles.ts

fixup: Add `--only` to e2e script

---

.github/workflows/README.md

This PR does a simple rewrite of a sentence to make it clearly that ⚠️ denotes a possible expected failure

Reword `.github/workflows/README.md`

---

.changeset/green-sloths-collect.md
packages/wrangler/src/deployments.ts
packages/wrangler/src/init.ts

Run `wrangler init --from-dash <my-d1-worker-here>`, check if the wrangler.toml contains unsafe bindings
Fixes #6253
- Tests

[D1] teach init --from-dash about d1

---

.changeset/soft-eagles-fly.md
packages/wrangler/src/__tests__/hyperdrive.test.ts
packages/wrangler/src/hyperdrive/client.ts
packages/wrangler/src/hyperdrive/create.ts
packages/wrangler/src/hyperdrive/update.ts

Add support for creating Hyperdrive over Access configs

---

packages/wrangler/src/d1/export.ts

Slight tweak to the UI during an export:
https://github.com/cloudflare/workers-sdk/assets/23264/8a3711f3-6be8-43da-9133-b8ea031e7629
Doesn't need a changeset or tests, it's just a bit of polish I've been meaning to do for ages.

Updated D1 export progress to use spinnerWhile

---

packages/wrangler/src/__tests__/init.test.ts

Adds a test for https://github.com/cloudflare/workers-sdk/pull/6255

chore: add test for d1 init from dash

---

packages/wrangler/src/__tests__/pages/pages.test.ts
packages/wrangler/src/pages/secret/index.ts

fix(wrangler): Remove unnecessary command emoji

---

.changeset/few-pumpkins-fetch.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/pages/functions-build.test.ts
packages/wrangler/src/deployment-bundle/find-additional-modules.ts

Provides more info into how much is being uploaded.
- Tests

Log total amount + size of all modules

---

templates/worker-openapi/src/endpoints/taskCreate.ts
templates/worker-openapi/src/endpoints/taskDelete.ts
templates/worker-openapi/src/endpoints/taskFetch.ts
templates/worker-openapi/src/endpoints/taskList.ts

add type to worker-openapi template endpoints handle function

---

.github/actions/run-c3-e2e/action.yml

chore: bump upload-artifact action for C3

---

fixtures/pages-dev-proxy-with-script/tests/index.test.ts
fixtures/shared/src/run-wrangler-long-lived.ts

use --x-dev-env in pages fixtures

---

.changeset/witty-zebras-accept.md
packages/wrangler/src/__tests__/versions/secrets/put.test.ts
packages/wrangler/src/__tests__/versions/secrets/utils.ts
packages/wrangler/src/versions/secrets/index.ts

Fix WASM modules in versions secrets

---

.changeset/lazy-pens-approve.md

fix changeset

---

packages/create-cloudflare/e2e-tests/helpers.ts
packages/create-cloudflare/e2e-tests/workers.test.ts

This mimicks how an actual users would do with a select prompt
- Tests

chore(create-cloudflare): test select prompt from user perspective

---

tools/README.md
tools/turbo.json

Simple change to Turbo configuration.

chore: ensure that changes to package.json files bust the `tools` tests Turbo cache

---

packages/create-cloudflare/src/templates.ts

Python Workers are still in open beta.
- Tests

style(create-cloudflare):  update label on language options

---

.changeset/quiet-lizards-play.md
packages/wrangler/package.json
packages/wrangler/src/dev/miniflare.ts
pnpm-lock.yaml

fix: do not try to load in @cloudflare/workers-shared if not using experimental-assets

---

.changeset/shaggy-insects-jam.md
packages/cli/index.ts
packages/cli/test-util.ts
packages/create-cloudflare/e2e-tests/frameworks.test.ts
packages/create-cloudflare/e2e-tests/workers.test.ts
packages/create-cloudflare/src/__tests__/dialog.test.ts
packages/create-cloudflare/src/cli.ts
packages/create-cloudflare/src/deploy.ts
packages/create-cloudflare/src/dialog.ts
packages/create-cloudflare/vitest.setup.ts

This PR updates both the styles of our welcome message and summary.
Before:
After: 
- Tests

style(create-cloudflare): update welcome and summary message

---

.changeset/honest-deers-work.md
packages/cli/interactive.ts
packages/create-cloudflare/e2e-tests/cli.test.ts
packages/create-cloudflare/e2e-tests/helpers.ts
packages/create-cloudflare/src/templates.ts
packages/create-cloudflare/templates/common/c3.ts
packages/create-cloudflare/templates/hello-world-durable-object/c3.ts
packages/create-cloudflare/templates/hello-world/c3.ts
packages/create-cloudflare/templates/openapi/c3.ts
packages/create-cloudflare/templates/queues/c3.ts
packages/create-cloudflare/templates/scheduled/c3.ts

This PR adds description to each categories and templates with proper text wrapping logic.
- Tests

style(create-cloudflare): add description support to select prompt

---

.changeset/honest-deers-work.md
.changeset/shaggy-insects-jam.md

fix: Update changesets to conform to the recommended format

---

.changeset/pink-socks-tie.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/experimental-assets.ts

https://cflare.co/2364
- Tests

Upload assets as JSON Lines (application/jsonl) rather than NDJSON (application/x-ndjson)

---

packages/wrangler/src/__tests__/d1/insights.test.ts

This PR adds tests for `wrangler d1 insights`.
Closes #6491
- Tests

[D1] add tests for `wrangler d1 insights`

---

.changeset/gold-books-cheat.md
packages/cli/args.ts
packages/cli/index.ts
packages/cli/interactive.ts
packages/create-cloudflare/e2e-tests/cli.test.ts
packages/create-cloudflare/e2e-tests/helpers.ts
packages/create-cloudflare/src/__tests__/templates.test.ts
packages/create-cloudflare/src/cli.ts
packages/create-cloudflare/src/dialog.ts
packages/create-cloudflare/src/helpers/files.ts
packages/create-cloudflare/src/templates.ts

This PRs introduces a "Go back" option to most template related questions so users can go back to the previous question and change the answers.
- Tests

feat(create-cloudflare): allow users to change prompt answer

---

packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/api/pages/create-worker-bundle-contents.ts
packages/wrangler/src/api/startDevWorker/utils.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/deploy/deploy.ts
packages/wrangler/src/deploy/index.ts
packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
packages/wrangler/src/deployment-bundle/worker.ts
packages/wrangler/src/dev.tsx
packages/wrangler/src/dev/remote.tsx
packages/wrangler/src/experimental-assets.ts
packages/wrangler/src/secret/index.ts
packages/wrangler/src/versions/index.ts
packages/wrangler/src/versions/secrets/index.ts
packages/wrangler/src/versions/upload.ts

[WC-2506](https://jira.cfdata.org/browse/WC-2506) - add assets binding
and tacking on:
[WC-2455](https://jira.cfdata.org/browse/WC-2455) - encode file path
- Tests

feat(wrangler) - add assets binding to wrangler deploy

---

.changeset/rich-rocks-own.md
packages/wrangler/src/__tests__/versions/versions.upload.test.ts
packages/wrangler/src/versions/upload.ts

Fixed versions upload printing duplicate bindings

---

.changeset/nice-pants-wash.md
.changeset/soft-turtles-exercise.md

Fixes changeset messages for https://github.com/cloudflare/workers-sdk/pull/6528 and https://github.com/cloudflare/workers-sdk/pull/6532.
- Tests

Add changeset types

---

packages/wrangler-devtools/package.json
pnpm-lock.yaml

Use the workspace version when installing Wrangler in the `wrangler-devtools` package, to fix https://github.com/cloudflare/workers-sdk/actions/runs/10510189953/job/29118539333#step:6:42
- Tests

[devtools] Use Workspace version for Wrangler

---

packages/devprod-status-bot/src/index.ts

Updates internal release announcement message 
- Tests

Update status bot message

---

.changeset/giant-yaks-thank.md
.changeset/slow-ladybugs-heal.md
packages/wrangler/src/__tests__/middleware.scheduled.test.ts
packages/wrangler/src/dev/miniflare.ts
packages/wrangler/templates/middleware/middleware-scheduled.ts

Fixes https://github.com/cloudflare/workers-sdk/issues/4653 and fixes #4859
- Tests

Local dev cron improvements

---

.changeset/tiny-cobras-swim.md
packages/wrangler/package.json
pnpm-lock.yaml

Update unenv to [the latest available version](https://www.npmjs.com/package/unenv-nightly/v/2.0.0-1721912706.b876713?activeTab=versions)
- Tests

[wrangler] update unenv

---

.changeset/hip-jobs-fix.md
packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
packages/wrangler/src/deploy/deploy.ts

Fixes tail consumer + logpush not updating in new deploy path
- Tests

Update non-versioned script settings on deploy

---

fixtures/workers-with-assets/public/about/[fünky].txt
fixtures/workers-with-assets/tests/index.test.ts
packages/miniflare/src/workers/assets/assets-kv.worker.ts
packages/workers-shared/asset-worker/src/assets-manifest.ts
packages/workers-shared/asset-worker/src/index.ts
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/experimental-assets.ts

~Waiting on EWC work, **will break existing deployments!!**~
Fixes #[WC-2597](https://jira.cfdata.org/browse/WC-2597)
Out of scope for this PR: moving duplicated code into shared folder. 
- Tests

fix: allow encoded characters in paths for workers + assets

---

.changeset/poor-books-attack.md
packages/wrangler/src/__tests__/type-generation.test.ts
packages/wrangler/src/type-generation/index.ts

Adds the type [RateLimit](https://github.com/cloudflare/workerd/blob/main/types/defines/ratelimit.d.ts) to wrangler type generation for the beta rate limiter unsafe binding.
Fixes #6529 
- Tests

feat(wrangler): add ratelimit type generation

---

packages/wrangler/README.md

Add note on wrangler v2 support

---

packages/wrangler/src/__tests__/api-dev.test.ts
packages/wrangler/src/__tests__/api-devregistry.test.ts
packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
packages/wrangler/src/__tests__/helpers/teardown.ts
packages/wrangler/src/__tests__/rollback.test.ts

test: remove unwanted logging from Wrangler tests

---

packages/wrangler/README.md

Fixes N/A.
This PR updates the support messaging on the wrangler v2 readme to reflect what was recently added on the main readme with https://github.com/cloudflare/workers-sdk/pull/6639.
- Tests

Update v2 readme

---

packages/wrangler/CHANGELOG.md

Change attribution for pipelines

---

.changeset/purple-bobcats-itch.md
packages/wrangler/src/experimental-assets.ts

Fixes main (red right now because of conflict on merge).
- Tests

Fix asset upload count messaging

---

fixtures/asset-config/package.json
fixtures/asset-config/vitest.config.ts
package.json
packages/workers-shared/package.json
pnpm-lock.yaml

Use workspace vitest version

---

.changeset/popular-snakes-report.md
fixtures/asset-config/html-handling.test.ts
packages/workers-shared/asset-worker/src/handler.ts
packages/workers-shared/asset-worker/src/index.ts
packages/workers-shared/asset-worker/wrangler.toml
packages/workers-shared/router-worker/wrangler.toml
pnpm-lock.yaml

Just a tiny thing. Do not merge before getting in #6631.
- Tests

Rename asset-worker RPC methods as unstable

---

.github/pull_request_template.md
.github/workflows/validate-pr-description.yml
tools/deployments/__tests__/validate-changesets.test.ts
tools/deployments/__tests__/validate-pr-description.test.ts
tools/deployments/validate-changesets.ts
tools/deployments/validate-pr-description.ts

Fixes #5276
Additionally, this PR adds validation of the required PR description format. The label `skip-pr-validation` can be used to skip this validation.
- Tests

Validate changeset type & PR description

---

.changeset/thick-grapes-joke.md
packages/workers-shared/package.json

Use D&C token

---

README.md

Remove references to templates 

---

.changeset/tame-ties-smash.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts

Fixes [WC-2722](https://jira.cfdata.org/browse/WC-2722)
- Tests

fix: upload compat date for static-asset only projects

---

.changeset/tall-needles-marry.md
packages/quick-edit-extension/src/cfs.ts
packages/quick-edit-extension/src/ipc.ts
packages/workers-editor-shared/lib/ipc.ts

Fixes [WC-2199](https://jira.cfdata.org/browse/WC-2199)
- Tests

Allow setting readOnly mode in Quick Editor

---

.changeset/ninety-icons-live.md
packages/wrangler/src/__tests__/hyperdrive.test.ts
packages/wrangler/src/hyperdrive/create.ts
packages/wrangler/src/hyperdrive/update.ts

Fixes [SQC-308](https://jira.cfdata.org/browse/SQC-308) [SQC-309](https://jira.cfdata.org/browse/SQC-309)
- Tests

Fix edge cases in creating and updating Hyperdrive over Access configs

---

.changeset/tame-ties-smash.md

chore: update changeset message

---

pnpm-lock.yaml

See https://github.com/cloudflare/workers-sdk/commit/0d264200090af2dae50ff293a041490aee4becdd#r146847202
Fixes N/A
- Tests

Update lockfile to include catalog

---

.changeset/famous-knives-battle.md
fixtures/nodejs-hybrid-app/src/index.ts
fixtures/nodejs-hybrid-app/tests/index.test.ts
packages/wrangler/package.json
pnpm-lock.yaml

chore: update unenv dependency version

---

.changeset/polite-sheep-sip.md
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/__tests__/r2/helpers.test.ts
packages/wrangler/src/r2/helpers.ts
packages/wrangler/src/r2/index.ts
packages/wrangler/src/r2/notification.ts

Changed notification get->notification list. Modified copy to reflect event notifications changes
Fixes N/A
- Tests

Changed notification get->notification list.

---

.changeset/spotty-colts-peel.md
packages/wrangler/src/__tests__/type-generation.test.ts
packages/wrangler/src/type-generation/index.ts

Fixes [WC-2742](https://jira.cfdata.org/browse/WC-2742)
- Tests

fix: add asset binding to typegen

---

.github/dependabot.yml

chore: skip pr description validation for dependabot

---

.changeset/sour-jars-dance.md
packages/quick-edit/functions/_middleware.ts

Reverts cloudflare/workers-sdk#6558

Revert "fix(quick-edit): disable autosave"

---

packages/wrangler/src/__tests__/dev.test.tsx
packages/wrangler/src/experimental-assets.ts

fix: change 'sites' to 'legacy_assets' in error msg (fixup for #6798)

---

packages/wrangler/e2e/deployments.test.ts

Fixes [WC-2507](https://jira.cfdata.org/browse/WC-2507)
At last 🎉 
- Tests

chore: add workers + assets e2es

---

packages/create-cloudflare/e2e-tests/frameworks.test.ts

skip angular c3 e2e test on bun

---

.changeset/poor-deers-develop.md

Fixes N/A
Re-release Quick Edit to update included workers-types
- Tests

Update workers-types in Quick Edit

---

.changeset/cool-wombats-marry.md
packages/wrangler/src/__tests__/docs.test.ts
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/versions/versions.help.test.ts
packages/wrangler/src/docs/index.ts
packages/wrangler/src/index.ts

Fixes a regression accidentally introduced by #3735.
Fixes #0000
- Tests

fix: the docs command should not crash if given search terms

---

.changeset/yellow-ears-kick.md
packages/create-cloudflare/src/helpers/args.ts
packages/create-cloudflare/src/templates.ts

chore: fix GitHub capitalisation

---

.github/workflows/e2e.yml
packages/wrangler/e2e/dev.test.ts

chore: use wrangler.js as entrypoint

---

.changeset/fluffy-colts-give.md
packages/wrangler/src/__tests__/middleware.test.ts
packages/wrangler/src/deployment-bundle/bundle.ts
pnpm-lock.yaml

fix: enable esbuild's keepNames: true to set .name on functions/classes

---

.github/workflows/semgrep.yml

Description - Adding Semgrep.yml file as part of App&ProdSec team's initiative to onboard Semgrep for Secrets scanning and more.
- Tests

chore: create semgrep.yml

---

.github/workflows/c3-e2e-experimental.yml
.github/workflows/c3-e2e.yml

Skip C3 tests on *.md only changes

---

.changeset/warm-games-brush.md

remove duplicate of cuddly-waves-pump.md

---

CODEOWNERS

Adds Workers KV team to CODEOWNERS for its areas of responsibility:
* source
* test files

Add the Workers KV team to CODEOWNERS for Workers KV resources.

---

.github/workflows/validate-pr-description.yml

Fixes issue with changed files and force pushes
See https://github.com/jitterbit/get-changed-files/issues/11 for context
---
- Tests

Fix head check for PR validation

---

.changeset/violet-ducks-brush.md
packages/wrangler/src/__tests__/pipelines.test.ts
packages/wrangler/src/pipelines/client.ts
packages/wrangler/src/pipelines/index.ts

PIPE-37 Small API restructuring for Worker Pipelines

---

.changeset/green-parrots-lick.md
.changeset/moody-seals-smash.md
.changeset/serious-gifts-thank.md

experimental feats = patch
---
- Tests

fix: update changesets

---

.changeset/lucky-ants-call.md
packages/wrangler/package.json
pnpm-lock.yaml

Fixes N/A
Update unenv to the latest available release
---
- Tests

chore(wrangler): update unenv dependency version

---

packages/wrangler/src/hyperdrive/index.ts

I was fixing the snapshots and accidentally committed some other changes 🙈 
---
- Tests

chore: fixup #7024 

---

CONTRIBUTING.md

Clarify `preview:...` labels

---

.changeset/purple-poets-bow.md
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/r2/create.ts

[R2] Output suggested wrangler.toml changes after creating a bucket

---

packages/devprod-status-bot/src/index.ts

Fixes N/A.
Update team bot
---
- Tests

Update team bot

---

.changeset/hungry-hornets-taste.md
packages/wrangler/src/dev/inspect.ts

Reverts cloudflare/workers-sdk#7099

Revert "Open devtools in default browser"

---

.github/pull_request_template.md

Fixes N/A.
Adds a note to the PR template indicating that the checkboxes need not be completed if the PR only contains changes to .md files
---
- Tests

Add note about .md changes to PR template

---

packages/wrangler/src/metrics/metrics-dispatcher.ts

fix up some unintentionally nested properties
---
- Tests

fix: un-nest properties in telemetry req

---

.changeset/lemon-badgers-rest.md
packages/create-cloudflare/templates/hello-world/ts/test/tsconfig.json

Create a new project using typescript and then run `tsc -p test` to run typechecking on the tests.
- Tests

Fix the included file in tests for the hello world template

---

.changeset/funny-dingos-guess.md

Updates changeset of #7303 
---
- Tests

update changeset #7303

---

packages/wrangler/src/config/config.ts

Fixes #0000
Simple refactor.
---
- Tests

refactor: remove duplicate PagesConfigFields interface

---

.github/pull_request_template.md

adds a comment not to delete the checkboxes.
deleting the checkboxes breaks the checks :(
---
- Tests

chore: add clarifying comment to pr template

---

.changeset/six-coats-rule.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/assets.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/validation.ts

Rename serve_directly to experimental_serve_directly

---

.changeset/smooth-vans-share.md

fix: changeset fix

---

packages/wrangler/src/__tests__/api-dev.test.ts
packages/wrangler/src/__tests__/helpers/worker-scripts/hello-world-worker.js
packages/wrangler/src/__tests__/helpers/worker-scripts/hello-world-wrangler.toml

I don't think these are necessary as we use the hello-world script as a string everywhere else?
---
- Tests

chore: delete test helper worker scripts

---

.changeset/late-phones-stare.md
packages/wrangler/src/cloudchamber/curl.ts

cloudchamber/curl: include response body in API errors

---

packages/wrangler/e2e/dev-with-resources.test.ts

test: try harder to delete Workers Sites KV store in e2e tests

---

.changeset/clean-peas-exist.md

fix: Fix changeset

---

.changeset/afraid-cooks-switch.md
packages/devprod-status-bot/src/index.ts

Limit the repos the status bot can add PRs to

Limit status bot repos

---

.changeset/sour-scissors-teach.md
packages/create-cloudflare/templates-experimental/nuxt/c3.ts
packages/create-cloudflare/templates/nuxt/c3.ts

Bump Nuxt template to Node 18
---
- Tests

Bump Nuxt template to Node 18

---

.changeset/five-poems-own.md
packages/cloudflare-workers-bindings-extension/src/show-bindings.ts
packages/cloudflare-workers-bindings-extension/src/test/suite/extension.test.ts

Fixes [DEVX-1472](https://jira.cfdata.org/browse/DEVX-1472).
This PR updates the bindings view to list all binding types.
---
- Tests

feat(cloudflare-workers-bindings-extension): list all binding types

---

.github/ISSUE_TEMPLATE/bug-template.yaml

Fixes #7609
Fixes the yaml for this issue template so bugs can be easily reported again
---
- Tests

fix: bug issue template

---

fixtures/nodejs-hybrid-app/tests/index.test.ts

cleanup test by factoring code
---
- Tests

test(nodejs-hybrid-app): factor test setup

---

.github/workflows/prereleases.yml
packages/unenv-preset/package.json

Publish beta pre-release of  `@cloudflare/unenv-preset`
/cc @pi0 
---
- Tests

chore(unenv-preset): publish beta pre-release

---

.changeset/nervous-scissors-suffer.md
packages/unenv-preset/build.config.ts
packages/unenv-preset/package.json
pnpm-lock.yaml

Use tsc to compile `@cloudflare/unenv-preset`
/cc @pi0 
---
- Tests

chore(unenv-preset): drop unused .cjs files

---

fixtures/import-npm/turbo.json

ensure that the import-npm fixture's node_modules are cached by turbo

---

.changeset/hungry-llamas-repair.md
packages/wrangler/src/__tests__/config/configuration.test.ts
packages/wrangler/src/config/config.ts
packages/wrangler/src/config/validation-pages.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/d1/execute.ts
packages/wrangler/src/d1/migrations/helpers.ts

Fixes #0000
Related https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/29
---
- Tests

include the top level Worker name in the parsed config structure

---

.changeset/fifty-flies-visit.md
packages/unenv-preset/CHANGELOG.md
packages/unenv-preset/package.json

Prepare the release of `@cloudflare/unenv-preset@1.0.0`
---
- Tests

first initial release of Cloudflare unenv-preset

---

.changeset/fifty-dragons-provide.md

Adds changeset for https://github.com/cloudflare/workers-sdk/pull/7797
---
- Tests

chore: add changeset

---

.changeset/old-panthers-brush.md
package.json
packages/unenv-preset/README.md
packages/unenv-preset/package.json
packages/unenv-preset/tsconfig.json
pnpm-lock.yaml

Misc minor changes
---
- Tests

refactor(unenv-preset): misc minor changes

---

.github/workflows/prereleases.yml

Fixes broken beta pre-release script for the Cloudflare Vite Plugin
See https://github.com/cloudflare/workers-sdk/actions/runs/12866464786/job/35869092491#step:12:1

fix Cloudflare Vite plugin beta release script

---

packages/vite-plugin-cloudflare/README.md

Fixes #000.
Adds additional instructions to quick start guide.
---
- Tests

Improve README quick start

---

.changeset/thick-dots-sit.md

update and fix getPlatformProxy incorrect changeset

---

fixtures/get-platform-proxy/public/test.txt
fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
fixtures/get-platform-proxy/wrangler.toml
packages/wrangler/src/api/integrations/platform/index.ts

Reverts cloudflare/workers-sdk#7816

Revert "add support for assets bindings to `getPlatformProxy`"

---

.changeset/dry-pens-talk.md
packages/cloudflare-workers-bindings-extension/media/main.css
packages/cloudflare-workers-bindings-extension/media/main.js
packages/cloudflare-workers-bindings-extension/media/reset.css
packages/cloudflare-workers-bindings-extension/package.json
packages/cloudflare-workers-bindings-extension/src/extension.ts
packages/cloudflare-workers-bindings-extension/src/home.ts

Fixes DEVX-1546
(slightly out of date screenshot showing this in dark mode)
---
- Tests

feat: add welcome/reference webview to vscode extension

---

packages/cloudflare-workers-bindings-extension/src/home.ts

fix: tiny copy changes to vscode extension

---

.changeset/old-teachers-bow.md
packages/wrangler/src/__tests__/errors.test.ts
packages/wrangler/src/__tests__/metrics.test.ts
packages/wrangler/src/__tests__/parse.test.ts
packages/wrangler/src/assets.ts
packages/wrangler/src/d1/execute.ts
packages/wrangler/src/delete.ts
packages/wrangler/src/deployments.ts
packages/wrangler/src/dialogs.ts
packages/wrangler/src/errors.ts
packages/wrangler/src/index.ts
packages/wrangler/src/metrics/types.ts
packages/wrangler/src/parse.ts
packages/wrangler/src/tail/index.ts
packages/wrangler/telemetry.md

feat: add sanitised error messages to wrangler telemetry collection

---

.changeset/olive-tigers-raise.md

chore: mark changeset as patch

---

packages/wrangler/src/__tests__/utils/retry.test.ts

Fixes #0000
See above 😄 .
---
- Tests

test: quieten the logs on Wrangler retry helper tests

---

.changeset/thin-countries-clean.md
packages/workers-shared/asset-worker/src/utils/kv.ts
packages/workers-shared/asset-worker/tests/kv.test.ts

Update error message for KV to be shorter

---

.changeset/early-grapes-care.md

chore: update changeset

---

packages/workers-shared/asset-worker/src/index.ts

Fix asset-worker analytics not sending on success

---

CODEOWNERS

Fixes https://jira.cfdata.org/browse/DEVX-1583
Wrangler and Miniflare have large install bases and changes to the dependencies they install (and how those dependencies are bundled), can have a big impact. This change intends to add friction to these changes, to allow for a thorough review of the potential impact.

Require admin review on changes to Wrangler & Miniflare dependencies

---

.github/pull_request_template.md

clarify e2e refers to wrangler e2e tests in PR template

---

.changeset/kind-sloths-speak.md
.changeset/stupid-turtles-hammer.md
.changeset/wild-schools-kiss.md

chore: fix up some changesets

---

packages/vite-plugin-cloudflare/playground/__test-utils__/responses.ts
packages/vite-plugin-cloudflare/playground/prisma/__tests__/prisma.spec.ts
packages/vite-plugin-cloudflare/playground/prisma/__tests__/serve.ts
packages/vite-plugin-cloudflare/playground/vitest-setup.ts

Fixes #0000
Turn on skipped tests
---
- Tests

test: turn on Prisma playground tests for Vite plugin

---

fixtures/worker-ts/wrangler.toml
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/deploy/index.ts
packages/wrangler/src/index.ts

refactor: `wrangler deploy` to use`createCommand`

---

.github/ISSUE_TEMPLATE/bug-template.yaml

Add vite plugin to bug report template

---

.changeset/wicked-pets-jump.md
packages/wrangler/src/__tests__/dev.test.ts
packages/wrangler/src/__tests__/metrics.test.ts
packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
packages/wrangler/src/dev.ts
packages/wrangler/src/logger.ts

fix: respect WRANGLER_LOG in dev

---

.changeset/kind-spiders-hunt.md
packages/workers-shared/asset-worker/src/index.ts

WC-3184 
Bump interpolation search method for asset manifest reading to 1%
---
- Tests

Bump interpolation search method for asset manifest reading to 1%

---

package.json
packages/workers-shared/package.json
packages/workers-shared/utils/sentry.ts
patches/toucan-js@4.0.0.patch
pnpm-lock.yaml

Bumps the toucan version in attempt to fix sentry source mappings.
- Tests

Bump toucan version in workers-shared

---

.github/workflows/changesets.yml
.gitignore
packages/devprod-status-bot/src/index.ts
packages/devprod-status-bot/worker-configuration.d.ts
tools/deployments/__tests__/deploy-non-npm-packages.test.ts
tools/deployments/alert-on-error.ts
tools/deployments/deploy-non-npm-packages.ts

Fixes [DEVX-1629](https://jira.cfdata.org/browse/DEVX-1629), [DEVX-1589](https://jira.cfdata.org/browse/DEVX-1589)
Sends an alert to internal chat whenever a release fails
---
- Tests

Send alert to chat on release failure

---

.changeset/loud-ants-prove.md
packages/wrangler/src/__tests__/pages/deploy.test.ts
packages/wrangler/src/pages/deploy.ts

fix: pages deploy fails with git rev-parse error on new repo

---

fixtures/nodejs-hybrid-app/src/index.ts

Refactor/simplify the tests.
I have dropped the custom messages as using assert method is as clear.
I'll need to update those tests for the unenv preset so doing some refactoring first
---
- Tests

refactor nodejs-hybrid-app tests

---

packages/devprod-status-bot/src/index.ts

Fixes N/A
Updates users in status bot
---
- Tests

Update users in status bot

---

.github/workflows/workers-shared-deploy-production.yml
.github/workflows/workers-shared-deploy-staging.yml

WC-000
Makes it easier to go from a adhoc deployment to running it in prod.
---
- Tests

Add job summaries for workers-shared deployments

---

packages/wrangler/e2e/dev.test.ts

Part of EW-9069.
_Recently a regression meant that `print`s stopped showing up for `wrangler dev`, we fixed it and want to add a test to ensure a similar regression doesn't happen. This PR adds this test._
---
- Tests

Adds Python `wrangler dev` test to verify `print` works.

---

packages/wrangler/e2e/dev.test.ts

Follow up to https://github.com/cloudflare/workers-sdk/pull/8195
---
- Tests

Use print in Python console.log test

---

.github/workflows/c3-e2e-quarantine.yml
.github/workflows/c3-e2e.yml
.github/workflows/e2e-project-cleanup.yml
packages/create-cloudflare/e2e-tests/cli.test.ts

chore: use main testing account on c3 e2e tests 

---

.github/workflows/hotfix-release.yml

_Actually_ run hotfix releases

No more `--dry-run`

---

.prettierignore
packages/unenv-preset/src/preset.ts

fix(unenv-preset) add missing json import type

---

packages/unenv-preset/build.config.ts

BEFORE (not bundled)
```ts
// dist/index.mjs
export { cloudflare } from "./preset.mjs";
// dist/preset.mjs
import { version } from "../package.json" with { type: "json" };
const nodeCompatModules = [
"_stream_duplex",
"_stream_passthrough",
// [...]
```
After (bundled)
```ts
// dist/index.mjs
const version = "1.1.2";
const nodeCompatModules = [
"_stream_duplex",
"_stream_passthrough",
"_stream_readable",
// [...]
```
---
- Tests

fix(unenv-preset): bundle index.mjs

---

.changeset/chatty-seas-grin.md
fixtures/asset-config/html-handling.test.ts
fixtures/asset-config/redirects.test.ts
fixtures/asset-config/url-normalization.test.ts
packages/miniflare/src/plugins/assets/index.ts
packages/miniflare/src/plugins/assets/schema.ts
packages/vitest-pool-workers/src/pool/config.ts
packages/workers-shared/asset-worker/src/configuration.ts
packages/workers-shared/asset-worker/src/handler.ts
packages/workers-shared/asset-worker/src/index.ts
packages/workers-shared/asset-worker/tests/handler.test.ts
packages/workers-shared/router-worker/src/configuration.ts
packages/workers-shared/router-worker/src/index.ts
packages/workers-shared/utils/types.ts
packages/wrangler/src/__tests__/assets.test.ts
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/deployments.test.ts
packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
packages/wrangler/src/assets.ts
packages/wrangler/src/config/index.ts
packages/wrangler/src/deploy/deploy.ts
packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
packages/wrangler/src/deployment-bundle/worker.ts
packages/wrangler/src/dev/miniflare.ts
packages/wrangler/src/dev/remote.ts
packages/wrangler/src/sourcemap.ts
packages/wrangler/src/type-generation/runtime/index.ts
packages/wrangler/src/utils/filesystem.ts
packages/wrangler/src/versions/upload.ts

Fixes WC-3248
Uploads Workers Assets metafiles (`_headers` & `_redirects`) as part of creating a new Worker version.
---
- Tests

Upload metafiles for Workers Assets

---

.changeset/new-badgers-create.md
packages/workers-shared/asset-worker/src/index.ts

These were never meant to be part of our public contract. No one will be using them, so let's get them out.
---
- Tests

Removes non-public methods from asset-worker

---

.changeset/happy-pots-explode.md
packages/wrangler/src/__tests__/type-generation.test.ts
packages/wrangler/src/type-generation/index.ts

Add Images binding to wrangler types

---

.changeset/yummy-spies-like.md
packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
packages/create-cloudflare/templates/hello-world/js/package.json
packages/create-cloudflare/templates/hello-world/ts/package.json

chore(create-cloudflare): bump template vitest packages version

---

packages/vite-plugin-cloudflare/playground/dynamic-import-paths/package.json
pnpm-lock.yaml

fix a version error (rebase)
---
- Tests

fix wrangler version in the vite plugin playground

---

packages/workflows-shared/package.json

discussed offline with Pete
---
- Tests

fix `test:ci` should not watch file changes locally

---

packages/unenv-preset/CHANGELOG.md
packages/unenv-preset/package.json

fix outdated files in the dist folder of 2.0.1 release
---
- Tests

fix outdated files in the dist folder of 2.0.1 release

---

packages/vite-plugin-cloudflare/e2e/README.md
packages/vite-plugin-cloudflare/e2e/basic.test.ts
packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
packages/vite-plugin-cloudflare/e2e/global-setup.ts
packages/vite-plugin-cloudflare/e2e/helpers.ts

Reverts cloudflare/workers-sdk#8384

Revert "test: add e2e tests of the build+preview use case"

---

.changeset/deep-owls-travel.md
packages/create-cloudflare/src/__tests__/templates.test.ts
packages/create-cloudflare/src/helpers/__tests__/args.test.ts
packages/create-cloudflare/src/templates.ts
packages/vite-plugin-cloudflare/README.md

- vite-plugin: add .gitignore update to README
- c3: tighten up .gitignore processing
- Tests

.gitignore stuff

---

packages/vite-plugin-cloudflare/playground/multi-worker/__tests__/multi-worker.spec.ts
packages/vite-plugin-cloudflare/playground/multi-worker/worker-a/index.ts
packages/vite-plugin-cloudflare/playground/multi-worker/worker-b/index.ts

Add tests in `vite-plugin` to verify that RPC [promise pipelining](https://developers.cloudflare.com/workers/runtime-apis/rpc/#promise-pipelining) works as expected.
Fixes #000
---
- Tests

chore(vite-plugin): Add tests for promise pipelining

---

packages/miniflare/test/plugins/workflows/index.spec.ts

- `chore: remove console.log in miniflare workflows test`
- `chore: fix "commited" typo in miniflare workflows test`
---
- Tests

Two minor chore fixes in the miniflare workflows test

---

tools/deployments/open-v3-pr.ts

More attempts to improve v3-maintenance

---

.github/workflows/open-v3-maintenance-prs.yml

They're overwriting pre-release comments...

Remove v3 maintenance comments

---

.changeset/mighty-lies-see.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/assets.ts

This is an automatically opened PR to backport patch changes from #8503 to Wrangler v3

Backport #8503 to Wrangler v3

---

packages/miniflare/turbo.json
turbo.json

It doesn't seem to be getting through to Miniflare tests

Add `MINIFLARE_WORKERD_PATH` to more places in turbo

---

.github/workflows/test-and-check.yml
packages/wrangler/e2e/dev-with-resources.test.ts
packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
packages/wrangler/e2e/helpers/normalize.ts
packages/wrangler/e2e/types.test.ts

backport vectorize e2e changes

---

.changeset/cute-pianos-joke.md
packages/wrangler/src/check/commands.ts

backport #8472 to v3

---

.changeset/evil-terms-teach.md
packages/vite-plugin-cloudflare/src/__tests__/fixtures/incorrect-dir-main-wrangler.toml
packages/vite-plugin-cloudflare/src/__tests__/fixtures/index.ts
packages/vite-plugin-cloudflare/src/__tests__/fixtures/non-existing-main-wrangler.toml
packages/vite-plugin-cloudflare/src/__tests__/fixtures/tsconfig.json
packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
packages/vite-plugin-cloudflare/src/workers-configs.ts
packages/vite-plugin-cloudflare/tsconfig.plugin.json

[vite-plugin] add validation for the Wrangler config `main` field

---

.changeset/chubby-bats-start.md
packages/vite-plugin-cloudflare/package.json

Support Wrangler v4 as peer dependency

---

packages/vite-plugin-cloudflare/playground/__test-utils__/responses.ts
packages/vite-plugin-cloudflare/playground/static-mpa/__tests__/assets.spec.ts
packages/vite-plugin-cloudflare/playground/static-mpa/public/_headers
packages/vite-plugin-cloudflare/playground/static-mpa/public/_redirects
packages/vite-plugin-cloudflare/playground/static-mpa/public/text-file.txt
packages/vite-plugin-cloudflare/src/index.ts

Add tests for _headers and _redirects in preview

---

.changeset/loud-crabs-remain.md
.changeset/small-pigs-marry.md
fixtures/nodejs-hybrid-app/src/index.ts
fixtures/nodejs-hybrid-app/tests/index.test.ts
packages/unenv-preset/package.json
packages/unenv-preset/src/preset.ts
packages/unenv-preset/src/runtime/node/tls.ts
pnpm-lock.yaml

`connect` and `TLSSocket` are implemented in workerd 20250310.
See https://github.com/cloudflare/workerd/pull/3594
---
- Tests

Use the native implementation of `node:tls`

---

.changeset/loud-crabs-remain.md
packages/unenv-preset/CHANGELOG.md
packages/unenv-preset/package.json

Release `@cloudflare/unenv-preset@2.1.0`
---
- Tests

Release `@cloudflare/unenv-preset@2.1.0`

---

.changeset/vast-plums-invite.md
packages/wrangler/package.json
packages/wrangler/src/__tests__/deploy.test.ts
pnpm-lock.yaml

Use the native implementation for `node:tls`
---
- Tests
---
This is **part 2 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #8550 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #8547

Bump `@cloudflare/unenv-preset` to 2.2.0

---

packages/vite-plugin-cloudflare/e2e/README.md
packages/vite-plugin-cloudflare/e2e/basic.test.ts
packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
packages/vite-plugin-cloudflare/e2e/global-setup.ts
packages/vite-plugin-cloudflare/e2e/helpers.ts

test: add e2e tests of the build+preview use case (un-revert of #8384)

---

.changeset/real-jobs-own.md
fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
fixtures/workers-with-assets-and-service-bindings/vitest.config.mts
fixtures/workers-with-assets-and-service-bindings/workerA/src/index.ts
fixtures/workers-with-assets-and-service-bindings/workerA/src/workerD.util.ts
fixtures/workers-with-assets-and-service-bindings/workerB-with-default-export/src/index.ts
fixtures/workers-with-assets-and-service-bindings/workerC-with-default-entrypoint/src/index.ts
fixtures/workers-with-assets-and-service-bindings/workerD-with-named-entrypoint/src/index.ts
packages/miniflare/src/index.ts
packages/miniflare/src/plugins/assets/index.ts
packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
packages/wrangler/e2e/assets-multiworker.test.ts

will need some follow-up fixture changes once https://github.com/cloudflare/workerd/pull/3742 lands, but we will do that in a separate PR
Fixes DEVX-1643
---
- Tests

feat(miniflare): Implement Assets RPC Proxy Worker behaviour

---

.changeset/rude-socks-glow.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/__tests__/dev.test.ts
packages/wrangler/src/deployment-bundle/entry.ts

This is an automatically opened PR to backport patch changes from #8534 to Wrangler v3

Backport #8534 to Wrangler v3

---

.changeset/short-hats-add.md
packages/vite-plugin-cloudflare/src/index.ts

[vite-plugin] export `PluginConfig` type

---

packages/vite-plugin-cloudflare/playground/importable-env/vite.config.ts

Duplicate of https://github.com/cloudflare/workers-sdk/pull/8601 for a new fixture

Turn off inspector port in importable-env fixture

---

.changeset/short-dryers-look.md
fixtures/nodejs-hybrid-app/src/index.ts
packages/unenv-preset/package.json
packages/unenv-preset/src/runtime/node/tls.ts
pnpm-lock.yaml

The APIs were
- added in https://github.com/cloudflare/workerd/pull/3754
- released in [v1.20250320.0](https://github.com/cloudflare/workerd/releases/tag/v1.20250320.0)
/cc @anonrig @thomasgauvin 
---
- Tests

add missing native APIs in `node:tls`

---

fixtures/d1-worker-app/vitest.config.mts
fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts

Just some small testing fixups
---
- Tests

Small testing fixups

---

.changeset/legal-camels-dance.md
packages/wrangler/src/__tests__/pages/dev.test.ts
packages/wrangler/src/pages/dev.ts

This is an automatically opened PR to backport patch changes from #8604 to Wrangler v3

Backport #8604 to Wrangler v3

---

.changeset/violet-ravens-draw.md
packages/miniflare/src/plugins/core/modules.ts
packages/miniflare/src/runtime/config/workerd.ts
packages/miniflare/test/fixtures/modules/index.node.cjs
packages/miniflare/test/plugins/core/modules.spec.ts
packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
packages/wrangler/src/deployment-bundle/module-collection.ts
packages/wrangler/src/deployment-bundle/worker.ts

This is a manually opened PR to backport patch changes from https://github.com/cloudflare/workers-sdk/pull/8666 to Wrangler v3

Backport #8666 to Wrangler v3

---

.changeset/sharp-dogs-love.md
packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/index.ts
packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/package.json
packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/vite.config.ts
packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config-for-auxiliary-worker/wrangler.toml
packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config/package.json
packages/vite-plugin-cloudflare/e2e/fixtures/no-wrangler-config/vite.config.ts
packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
packages/vite-plugin-cloudflare/src/__tests__/fixtures/wrangler.toml
packages/vite-plugin-cloudflare/src/__tests__/get-validated-wrangler-config-path.spec.ts
packages/vite-plugin-cloudflare/src/plugin-config.ts
packages/vite-plugin-cloudflare/src/workers-configs.ts

Fixes #8298 
This PR adds some validation for the `configPath`s specified in the plugin's options,
such validation returns helpful error messages that should clearly indicate
the issue to users
---
- Tests

[vite-plugin] add validation for `configPath`s

---

packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts

Update node compat warnings test

---

packages/vite-plugin-cloudflare/e2e/vitest.config.ts
packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts
packages/wrangler/package.json
packages/wrangler/turbo.json
turbo.json

improve turbo settings and vite e2e test config

---

.changeset/lovely-lemons-count.md
packages/wrangler/src/__tests__/cfetch-utils.test.ts
packages/wrangler/src/cfetch/errors.ts
packages/wrangler/src/cfetch/index.ts

include documentation_url in api errors

---

.changeset/easy-pens-lie.md
packages/wrangler/src/__tests__/pages/secret.test.ts
packages/wrangler/src/__tests__/secret.test.ts
packages/wrangler/src/pages/secret/index.ts
packages/wrangler/src/secret/index.ts

backport #8757 (throw error in wrangler secrets bulk)

backport #8757

---

packages/create-cloudflare/e2e-tests/cli.test.ts

unskip c3 + template test

---

pnpm-lock.yaml

rimraf update made the lock file wonky
---
- Tests

update pnpm lock

---

packages/create-cloudflare/templates/astro/workers/templates/ts/wrangler.jsonc

astro template fixup

---

packages/vite-plugin-cloudflare/src/index.ts

Minor followup to #8823 since I missed https://github.com/cloudflare/workers-sdk/pull/8823#issuecomment-2783640028
> [!Note]
> I am not adding a changeset here since the changes in 8823 haven't yet been released anyways
---
- Tests

add `preventAssignment` to `replace` call (to prevent terminal warning)

---

.changeset/slow-roses-create.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/pipelines.test.ts
packages/wrangler/src/index.ts
packages/wrangler/src/pipelines/cli/create.ts
packages/wrangler/src/pipelines/cli/delete.ts
packages/wrangler/src/pipelines/cli/get.ts
packages/wrangler/src/pipelines/cli/update.ts
packages/wrangler/src/pipelines/index.ts
packages/wrangler/src/pipelines/validate.ts

Fixes [PIPE-248](https://jira.cfdata.org/browse/PIPE-248)
Add option to unset all CORS Origin settings for a pipeline. 
---
- Tests

Add options to update pipelines to remove CORS

---

.changeset/eager-dragons-stand.md
packages/create-cloudflare/templates/pre-existing/c3.ts

use latest version of wrangler when using c3 to init from dash

---

packages/wrangler/src/api/integrations/platform/index.ts

fix a comment in wrangler API

---

.changeset/nine-weeks-hug.md
packages/wrangler/src/__tests__/index.test.ts
packages/wrangler/src/__tests__/workflows.test.ts
packages/wrangler/src/workflows/commands/delete.ts
packages/wrangler/src/workflows/commands/describe.ts
packages/wrangler/src/workflows/commands/instances/describe.ts
packages/wrangler/src/workflows/commands/instances/list.ts
packages/wrangler/src/workflows/commands/instances/pause.ts
packages/wrangler/src/workflows/commands/instances/resume.ts
packages/wrangler/src/workflows/commands/instances/terminate-all.ts
packages/wrangler/src/workflows/commands/instances/terminate.ts
packages/wrangler/src/workflows/commands/list.ts
packages/wrangler/src/workflows/commands/trigger.ts
packages/wrangler/src/workflows/index.ts

feat: promote Workflow commands to stable

---

.changeset/sharp-bottles-agree.md
packages/wrangler/src/__tests__/whoami.test.ts
packages/wrangler/src/user/whoami.ts

V3 backport (add hint when no permission to show membership info #8341)

---

.changeset/tiny-ideas-nail.md
packages/wrangler/src/__tests__/pages/pages.test.ts
packages/wrangler/src/pages/build.ts
packages/wrangler/src/pages/index.ts
tools/deployments/__tests__/validate-pr-description.test.ts
tools/deployments/validate-pr-description.ts

V3 backport (Unhide 'wrangler pages functions build' #8795)

---

.changeset/nasty-mice-dance.md
packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-als/als.spec.ts
packages/vite-plugin-cloudflare/playground/node-compat/tsconfig.worker.json
packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-als.ts
packages/vite-plugin-cloudflare/playground/node-compat/worker-als/index.ts
packages/vite-plugin-cloudflare/playground/node-compat/worker-als/wrangler.jsonc
packages/vite-plugin-cloudflare/src/index.ts
packages/vite-plugin-cloudflare/src/node-js-compat.ts
packages/vite-plugin-cloudflare/src/worker-environments-validation.ts

vite-plugin: add support for Node.js ALS compat mode

---

.changeset/tiny-ideas-nail.md
packages/wrangler/src/__tests__/pages/pages.test.ts
packages/wrangler/src/pages/build.ts
packages/wrangler/src/pages/index.ts
tools/deployments/__tests__/validate-pr-description.test.ts
tools/deployments/validate-pr-description.ts

Reverts cloudflare/workers-sdk#8813. This doesn't need to be backport to v3 as discussed internally.

Revert "V3 backport (Unhide 'wrangler pages functions build' #8795)"

---

.changeset/odd-steaks-cheat.md
packages/wrangler/src/__tests__/pages/deploy.test.ts
packages/wrangler/src/config/validation.ts

V3 Backport for #8924

---

.changeset/perfect-geckos-tell.md
packages/create-cloudflare/templates/openapi/ts/.gitignore
packages/create-cloudflare/templates/openapi/ts/package.json
packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskCreate.ts
packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskDelete.ts
packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskFetch.ts
packages/create-cloudflare/templates/openapi/ts/src/endpoints/taskList.ts
packages/create-cloudflare/templates/openapi/ts/src/index.ts
packages/create-cloudflare/templates/openapi/ts/src/types.ts
packages/create-cloudflare/templates/openapi/ts/tsconfig.json

This pr update openapi C3 template to include better ts types and lint command
---
- Tests

feat(create-cloudflare): Update openapi template to include better ts types and lint command

---

.changeset/plenty-beans-enjoy.md
packages/wrangler/src/__tests__/type-generation.test.ts
packages/wrangler/src/type-generation/index.ts

fix version metadata binding type in when generating env type

---

.changeset/tough-bats-live.md
packages/wrangler/src/__tests__/user.test.ts
packages/wrangler/src/user/user.ts

wrangler login put custom callback host and port into the auth URL

---

.changeset/soft-wasps-beg.md
packages/miniflare/src/plugins/core/index.ts
packages/miniflare/test/plugins/core/index.spec.ts

V3 Backport [#9089]: parse pem file with regex

---

.changeset/social-cups-roll.md
packages/wrangler/src/__tests__/d1/execute.test.ts
packages/wrangler/src/d1/execute.ts

Do not report "d1 execute" command file missing error to Sentry

---

.changeset/social-cups-roll.md
packages/wrangler/src/__tests__/d1/execute.test.ts
packages/wrangler/src/d1/execute.ts

V3 backport of #9162
---
- Tests

V3 backport (#9162) Do not report "d1 execute" command file missing error to Sentry

---

.github/workflows/test-and-check.yml

See https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions for details

Support merge queues

---

.changeset/chatty-years-speak.md
.changeset/thin-years-jump.md
packages/miniflare/src/plugins/core/services.ts
packages/miniflare/src/plugins/d1/index.ts
packages/miniflare/src/plugins/do/index.ts
packages/miniflare/src/plugins/kv/index.ts
packages/miniflare/src/plugins/queues/index.ts
packages/miniflare/src/plugins/r2/index.ts
packages/miniflare/src/plugins/shared/index.ts
packages/miniflare/src/plugins/workflows/index.ts
packages/wrangler/src/api/mixedMode/index.ts

Fixes https://jira.cfdata.org/browse/DEVX-1837
---
- Tests

add `mixedModeConnectionString` to the various binding configs

---

.changeset/red-trains-drive.md
.github/workflows/test-and-check.yml
fixtures/mixed-mode-node-test/package.json
fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
fixtures/mixed-mode-node-test/turbo.json
packages/miniflare/src/plugins/ai/index.ts
packages/miniflare/src/plugins/index.ts
packages/miniflare/src/workers/shared/mixed-mode-client.worker.ts
packages/wrangler/src/api/mixedMode/index.ts
packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
pnpm-lock.yaml

Fixes [DEVX-1838](https://jira.cfdata.org/browse/DEVX-1838) & [DEVX-1839](https://jira.cfdata.org/browse/DEVX-1839)
This PR continues the Mixed Mode implementation work by adding a client & server, as well as plumbing through the first binding type, AI.
The Mixed Mode server Worker is deployed using the `startMixedModeSession()` API as a realish preview Worker. It does one thing—proxy requests from binding implementations to the production binding implementation (i.e. from the KV implementation in `workerd` to the underlying KV implementation in production). 
The Mixed Mode client Worker is the immediate target of those requests from bindings. It then massages the requests slightly so they can be sent over the wire (putting the original URL in a header, prefixing original headers so …

Implement Mixed Mode proxy server & client

---

packages/wrangler/src/__tests__/helpers/mock-process.ts

test: hide stdout.write in tests

---

.changeset/lemon-pants-jam.md
fixtures/pages-functions-app/functions/r2/create.ts
fixtures/pages-functions-app/functions/r2/get.ts
fixtures/pages-functions-app/package.json
fixtures/pages-functions-app/tests/index.test.ts
fixtures/pages-workerjs-directory/package.json
fixtures/pages-workerjs-directory/public/_worker.js/index.js
fixtures/pages-workerjs-directory/tests/index.test.ts
packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
packages/wrangler/e2e/pages-dev.test.ts
packages/wrangler/src/__tests__/config/configuration.pages.test.ts
packages/wrangler/src/__tests__/config/configuration.test.ts
packages/wrangler/src/__tests__/helpers/generate-wrangler-config.ts
packages/wrangler/src/__tests__/helpers/msw/handlers/r2.ts
packages/wrangler/src/__tests__/r2.local.test.ts
packages/wrangler/src/__tests__/r2.test.ts
packages/wrangler/src/__tests__/type-generation.test.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/pages/dev.ts
packages/wrangler/src/pipelines/cli/create.ts
packages/wrangler/src/r2/bucket.ts
packages/wrangler/src/r2/helpers.ts

[v3] fix(r2): validate bucket names

---

packages/vite-plugin-cloudflare/src/utils.ts
packages/vite-plugin-cloudflare/src/websockets.ts

Fixes #000.
Always nice to delete some code.
---
- Tests

Use createHeaders util in place of custom function

---

.changeset/thirty-ghosts-argue.md
packages/create-cloudflare/templates/next/workers/c3.ts

Do not pin `create-next-app` for Workers
---
- Tests

[c3] Do not pin create-next-app

---

.changeset/cyan-years-relate.md
packages/miniflare/src/plugins/core/index.ts
packages/miniflare/src/workers/core/strip-cf-connecting-ip.worker.ts
packages/miniflare/test/index.spec.ts
packages/miniflare/turbo.json
packages/wrangler/src/api/startDevWorker/ProxyController.ts
packages/wrangler/src/dev/miniflare.ts

This is an automatically opened PR to backport patch changes from #7914 to Wrangler v3

V3 Backport (fix(wrangler): strip CF-Connecting-IP header from all outbound requests #7914)

---

.changeset/new-clocks-obey.md
fixtures/nodejs-hybrid-app/src/index.ts
fixtures/nodejs-hybrid-app/tests/index.test.ts
packages/unenv-preset/package.json
packages/wrangler/package.json
pnpm-lock.yaml

Thanks @pi0 for unenv 2.0.0-rc.17
@thomasgauvin This will pull debug named exports - should be in wrangler at the end of the week
/cc @anonrig 
---
- Tests
- [] TODO (before merge)
---
This is **part 1 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #9221 
- <kbd>&nbsp;2&nbsp;</kbd> #9220 
- <kbd>&nbsp;1&nbsp;</kbd> #9219 👈

bump unenv to 2.0.0-rc.17

---

.changeset/five-peaches-cough.md
packages/unenv-preset/package.json
packages/unenv-preset/src/preset.ts
packages/unenv-preset/src/runtime/node/async_hooks.ts
packages/unenv-preset/src/runtime/node/tls.ts
packages/unenv-preset/tests/worker/index.ts
pnpm-lock.yaml

This PR supersedes #8939 by @anonrig. The current PR contain the code only, tests will be merged once the preset is bumped into wrangler and are in the follow up PRs.
---
- Tests
---
This is **part 2 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #9221 
- <kbd>&nbsp;2&nbsp;</kbd> #9220 👈 
- <kbd>&nbsp;1&nbsp;</kbd> #9219

Sync unenv-preset with workerd

---

.changeset/nine-ends-train.md
packages/vite-plugin-cloudflare/package.json
pnpm-lock.yaml

[vite] Bump unenv to 2.0.0-rc.17

---

packages/create-cloudflare/e2e-tests/frameworks.test.ts

forgot to run c3 e2e tests on https://github.com/cloudflare/workers-sdk/pull/9244

fix c3 tests

---

.changeset/four-books-heal.md
fixtures/nodejs-hybrid-app/src/index.ts
fixtures/nodejs-hybrid-app/tests/index.test.ts
packages/vite-plugin-cloudflare/package.json
packages/wrangler/package.json
pnpm-lock.yaml

fix a mismatch in unenv version
Partially revert #9219
---
- Tests

fix unenv version mismatch

---

tools/deployments/__tests__/check-v3-backport-status.test.ts
tools/deployments/check-v3-backport-status.ts

chore: accept backport PR with v3-backport branch prefix

---

pnpm-workspace.yaml

docs: add update frequency table to workspace file

---

.changeset/olive-candies-nail.md
fixtures/nodejs-hybrid-app/src/index.ts
fixtures/nodejs-hybrid-app/tests/index.test.ts
packages/unenv-preset/tests/worker/index.ts
packages/vite-plugin-cloudflare/package.json
packages/wrangler/package.json
pnpm-lock.yaml

TODO:
This PR contains the tests from #8939 (including a typo fix mentioned in the original PR)
---
- Tests
---
This is **part 3 of 3 in a stack** made with GitButler:
- <kbd>&nbsp;3&nbsp;</kbd> #9221 👈 
- <kbd>&nbsp;2&nbsp;</kbd> #9220 
- <kbd>&nbsp;1&nbsp;</kbd> #9219

bump `@cloudflare/unenv-preset`

---

fixtures/workers-with-assets-static-routing/package.json
fixtures/workers-with-assets-static-routing/public/_routes.json
fixtures/workers-with-assets-static-routing/public/static/page.html
fixtures/workers-with-assets-static-routing/public/worker/asset.html
fixtures/workers-with-assets-static-routing/public/worker/worker-runs.html
fixtures/workers-with-assets-static-routing/src/index.ts
fixtures/workers-with-assets-static-routing/test/index.test.ts
fixtures/workers-with-assets-static-routing/test/tsconfig.json
fixtures/workers-with-assets-static-routing/tsconfig.json
fixtures/workers-with-assets-static-routing/wrangler.jsonc

Adds a fixture that tests different routing behavior

Add fixture test for _routes.json

---

.changeset/kind-cougars-design.md
packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
packages/wrangler/src/deployment-bundle/worker.ts
packages/wrangler/src/dev/create-worker-preview.ts
packages/wrangler/src/dev/remote.ts

Move the `minimal_mode` flag to `wrangler-session-config`, to match the backend.
---
- Tests

Move minimal mode to session config

---

.changeset/empty-islands-draw.md
packages/miniflare/src/plugins/core/errors/callsite.ts
packages/miniflare/test/index.spec.ts

fix toString() on callsite

---

.changeset/forty-things-beam.md
packages/wrangler/src/__tests__/metrics.test.ts
packages/wrangler/src/metrics/commands.ts

backport #9353 (fix telemetry.md link)

---

.changeset/gold-experts-sniff.md
packages/miniflare/src/index.ts
packages/miniflare/src/shared/dev-registry.ts

refactor(miniflare): dev registry should create a file watcher only when necessary

---

.changeset/yummy-jokes-lose.md
packages/create-cloudflare/templates/hello-world-workflows/ts/wrangler.jsonc

remove erroneous TBD that prevents workflows starter from deploying

---

.github/dependabot.yml

Our CI setup is less constrained now, so let's turn on general dependabot updates.

Turn on dependabot

---

.changeset/shaggy-frogs-tap.md
packages/wrangler/src/__tests__/kv.test.ts
packages/wrangler/src/kv/helpers.ts
packages/wrangler/src/kv/index.ts

Cap the number of errors and warnings for bulk KV put

---

.changeset/warm-shirts-report.md
packages/miniflare/package.json
packages/miniflare/src/plugins/core/errors/index.ts
packages/miniflare/test/plugins/core/errors/index.spec.ts
packages/wrangler/e2e/startWorker.test.ts
pnpm-lock.yaml

Fixes [DEVX-1979](https://jira.cfdata.org/browse/DEVX-1979)
This upgrades Youch to v4, which gives us better error-cause support and a refreshed error UI with light and dark theme:
|![image](https://github.com/user-attachments/assets/bd4494a7-9a9b-4e59-a851-330b0e3df16e)|![image](https://github.com/user-attachments/assets/7a5a2325-aa5c-4a8c-9e44-7dd9504f43f1)|
|-------|--------|
---
- Tests

chore(miniflare): upgrade youch version

---

packages/wrangler/src/environment-variables/factory.ts
packages/wrangler/src/environment-variables/misc-variables.ts
packages/wrangler/src/logger.ts
packages/wrangler/src/metrics/commands.ts
packages/wrangler/src/metrics/metrics-config.ts

Add boolean env var factory

---

fixtures/interactive-dev-tests/multi-containers-app/DockerfileA
fixtures/interactive-dev-tests/multi-containers-app/DockerfileB
fixtures/interactive-dev-tests/multi-containers-app/src/index.ts
fixtures/interactive-dev-tests/multi-containers-app/src/tsconfig.json
fixtures/interactive-dev-tests/multi-containers-app/src/worker-configuration.d.ts
fixtures/interactive-dev-tests/multi-containers-app/wrangler.jsonc
fixtures/interactive-dev-tests/tests/index.test.ts
packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts

Fixes https://jira.cfdata.org/browse/DEVX-2086
---
- Tests

Add some basic smoke tests to check that workers with multiple containers work as expected

---

.changeset/gold-shirts-wash.md
packages/wrangler/src/assets.ts
packages/wrangler/src/deploy/deploy.ts
packages/wrangler/src/deployment-bundle/entry.ts
packages/wrangler/src/dev.ts
packages/wrangler/src/package-manager.ts

https://github.com/cloudflare/workers-sdk/pull/10000 backport

v3 backport: more error telemetry

---

.changeset/clever-wasps-call.md
fixtures/dev-registry/workers/module-worker.ts
packages/miniflare/src/index.ts
packages/miniflare/src/plugins/core/errors/callsite.ts
packages/miniflare/test/dev-registry.spec.ts
packages/vitest-pool-workers/src/worker/index.ts
packages/wrangler/src/sourcemap.ts
pnpm-lock.yaml
pnpm-workspace.yaml

fix(miniflare): service binding fetch over dev registry should work without host header

---

.changeset/c3-frameworks-update-9431.md
packages/create-cloudflare/src/frameworks/package.json
packages/create-cloudflare/templates/angular/pages/c3.ts
packages/create-cloudflare/templates/angular/workers/c3.ts

Update Angular to version 20.
- Tests

chore: update dependencies of "create-cloudflare" package

---

packages/vite-plugin-cloudflare/e2e/helpers.ts
packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts

reduce vite-plugin remote-bindings e2e flakes

---

.changeset/petite-paws-allow.md
fixtures/browser-rendering/src/playwright.ts
fixtures/browser-rendering/src/puppeteer.ts
fixtures/browser-rendering/test/index.spec.ts
packages/miniflare/package.json
packages/miniflare/src/index.ts
packages/miniflare/src/workers/browser-rendering/binding.worker.ts
packages/miniflare/test/plugins/browser/index.spec.ts
pnpm-lock.yaml

Reverts cloudflare/workers-sdk#10220

Revert "chore: implement local browser rendering /v1/session endpoint"

---

.changeset/light-garlics-count.md
packages/miniflare/src/shared/dev-registry.worker.ts
packages/miniflare/test/dev-registry.spec.ts

fix(miniflare): support WebSocket proxying over dev registry

---

.changeset/salty-bats-drop.md
.github/workflows/changesets.yml

The quick editor requires this version for its build step

run changeset versioning and release on Node 22

---

.changeset/poor-hoops-cover.md
packages/containers-shared/src/client/index.ts
packages/containers-shared/src/client/models/Application.ts
packages/containers-shared/src/client/models/ApplicationRolloutActiveGracePeriod.ts
packages/containers-shared/src/client/models/CreateApplicationRequest.ts
packages/containers-shared/src/client/models/ModifyApplicationRequestBody.ts
packages/containers-shared/src/types.ts
packages/wrangler/src/__tests__/config/configuration.test.ts
packages/wrangler/src/__tests__/containers/config.test.ts
packages/wrangler/src/__tests__/containers/deploy.test.ts
packages/wrangler/src/config/environment.ts
packages/wrangler/src/config/validation.ts
packages/wrangler/src/containers/config.ts
packages/wrangler/src/containers/deploy.ts

does what it says on the tin. 
---
- Tests

add rollout_active_grace_period to container config

---

.changeset/hungry-falcons-brush.md
packages/containers-shared/src/types.ts
packages/wrangler/src/__tests__/containers/deploy.test.ts
packages/wrangler/src/containers/config.ts

this should default to 0 if unset.
---
- Tests

set default for rollout_active_grace_period

---

CODEOWNERS

update codeowners for containers-shared

---

packages/wrangler/src/config/environment.ts

v3 backport for #10396

---

.changeset/sixty-chicken-joke.md
packages/vite-plugin-cloudflare/package.json
packages/vite-plugin-cloudflare/src/utils.ts
packages/vite-plugin-cloudflare/src/websockets.ts
pnpm-lock.yaml

packages now live in the @remix-run repo: https://github.com/mjackson/remix-the-web/commit/1258697c35b17830a8ac84aedd206e461fc51edd
---
- Tests

refactor(vite-plugin): update `@mjackson/node-fetch-server` to `@remix-run/node-fetch-server`

---

.changeset/dirty-students-scream.md
.changeset/nervous-goats-sniff.md
packages/playground-preview-worker/package.json
packages/turbo-r2-archive/package.json
packages/wrangler/src/__tests__/experimental-commands-api.test.ts
packages/wrangler/src/__tests__/metrics.test.ts
packages/wrangler/src/experimental-commands-api.ts
packages/wrangler/src/index.ts

Expose global flags from `experimental_getWranglerCommands()`

---

packages/workers-shared/router-worker/tests/index.test.ts

Add tests for `/_image` request blocking in Router Worker - see https://github.com/cloudflare/workers-sdk/pull/10500 for the implementation.
---
- Tests

Add tests for /_image request blocking in Router Worker

---

.changeset/twelve-hands-throw.md
packages/pages-shared/package.json
packages/pages-shared/scripts/build.ts
packages/pages-shared/tsconfig.build.json
packages/pages-shared/turbo.json
pnpm-lock.yaml

Replaces https://github.com/cloudflare/workers-sdk/pull/10495
---
- Tests

Build @cloudflare/pages-shared

---

.changeset/stale-files-cheer.md
fixtures/dev-registry/tests/dev-registry.test.ts
packages/miniflare/src/shared/dev-registry.worker.ts

Fixes n/a.
This also bumps the wait for timeout time from 1s (default) to 10s.
---
- Tests

fix(miniflare): Improve tunnel cleanup in dev registry to reduce connection errors

---

packages/vite-plugin-cloudflare/playground/prisma/.gitignore
packages/vite-plugin-cloudflare/playground/prisma/package.json
packages/vite-plugin-cloudflare/playground/prisma/prisma/schema.prisma
packages/vite-plugin-cloudflare/playground/prisma/src/index.ts
packages/vite-plugin-cloudflare/playground/prisma/wrangler.jsonc
pnpm-lock.yaml

Fixes #000.
Use the latest best practices for Prisma on Cloudflare.
---
- Tests

Update Prisma playground

---

.changeset/rich-hats-chew.md
packages/wrangler/src/cli-hotkeys.ts
packages/wrangler/src/dev.ts
packages/wrangler/src/dev/hotkeys.ts

Fix https://jira.cfdata.org/browse/DEVX-2214
The hotkeys bar was rendering twice in both remote dev and when remote bindings were enabled. To test, pull this branch and run both `wrangler dev --remote` and `wrangler dev` (with a remote binding enabled). You should only see the hotkeys bar rendering once.
---
- Tests

Fix hotkeys double render

---

packages/wrangler/src/__tests__/versions/versions.upload.test.ts

test: do not show unnecessary logging in version upload unit tests

---

packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
packages/wrangler/src/__tests__/cloudchamber/build.test.ts

hide unwanted logging from cloudchamber unit test output

---

.changeset/dark-hairs-build.md
packages/wrangler/src/__tests__/queues/__snapshots__/queues.test.ts.snap
packages/wrangler/src/__tests__/queues/queues-subscription.test.ts
packages/wrangler/src/__tests__/queues/queues.test.ts
packages/wrangler/src/queues/cli/commands/subscription/get.ts
packages/wrangler/src/queues/cli/commands/subscription/list.ts
packages/wrangler/src/queues/cli/commands/subscription/update.ts

fix(wrangler): skip banner when outputing json with queues subscription commands

---

.changeset/hungry-pants-talk.md
.changeset/social-foxes-crash.md
packages/miniflare/src/workers/core/entry.worker.ts
packages/miniflare/test/index.spec.ts
packages/vite-plugin-cloudflare/src/index.ts

Stricter handling of `/cdn-cgi/handler/` routes.

---

.changeset/puny-coins-dream.md
packages/wrangler/src/__tests__/deploy.test.ts
packages/wrangler/src/deploy/deploy.ts

Backport [#10761]: switch zone route warning to an info message

---

packages/wrangler/src/__tests__/deploy.test.ts

This test is already included in the backport PR #10762.

test: add test that was missing in #10761

---

packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
packages/wrangler/src/__tests__/dev/remote-bindings.test.ts
packages/wrangler/src/__tests__/r2/bucket.test.ts
packages/wrangler/src/api/startDevWorker/BaseController.ts
packages/wrangler/src/api/startDevWorker/BundlerController.ts
packages/wrangler/src/api/startDevWorker/ConfigController.ts
packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
packages/wrangler/src/api/startDevWorker/NoOpProxyController.ts
packages/wrangler/src/api/startDevWorker/ProxyController.ts
packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts

investigate configcontroller test flakes
