- .changeset/nasty-melons-camp.md
- fixtures/nodejs-hybrid-app/src/index.ts
- fixtures/nodejs-hybrid-app/tests/index.test.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- pnpm-lock.yaml
> fix: allow `require`ing alias modules

- .github/workflows/README.md
- ISSUE_TRIAGE.md
- packages/create-cloudflare/README.md
- packages/quick-edit/README.md
- packages/workers-playground/README.md
- packages/wrangler-devtools/README.md
Fixes N/A
Fixes instances of incorrect GitHub capitalization in markdown files.
- Tests
> Fix GitHub capitalization

- packages/wrangler/src/__tests__/pages/project-delete.test.ts
- packages/wrangler/src/pages/projects.tsx
Fixes #5559 
To be quite honest, I have no idea why this appeases yargs and the previous state did not.
- Tests
> fix: `pages project delete` should error if project name not specified

- .changeset/cuddly-waves-pump.md
- .changeset/warm-games-brush.md
- packages/wrangler/src/__tests__/pages/project-create.test.ts
- packages/wrangler/src/__tests__/pages/project-delete.test.ts
- packages/wrangler/src/__tests__/pages/project-list.test.ts
- packages/wrangler/src/pages/projects.tsx
Fixes #4947 
Previously `pages project` commands were always using cached accound id values, regardless of what was passed in as an env variable.
- Tests
> fix: respect CLOUDLFARE_ACCOUNT_ID with `wrangler pages project`

- .changeset/famous-camels-leave.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/build-failures.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/alias-external.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/als-external.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/cloudflare-internal.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/config-provider.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/log-build-output.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/standard-url.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/logger.ts
> fix: improve the rendering of build errors when bundling

- .changeset/cyan-cycles-occur.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/index.ts
> Show kv help when run without params

- .changeset/poor-shoes-tickle.md
- packages/workers-shared/router-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/index.ts
- packages/workers-shared/router-worker/src/performance.ts
- packages/workers-shared/router-worker/src/types.ts
- packages/workers-shared/router-worker/wrangler.toml
Fixes #WC-2695
This commit instruments the router worker with analytics such as request time, colo metadata, error, etc, in order for us to have better visibility into the router worker.
These changes were tested using gradual rollouts with a 0% version and a Cloudflare-Workers-Version-Overrides header.
- Tests
> WC-2695 Add better visibility for router-worker

- packages/wrangler/src/cloudchamber/modify.ts
If a user wants to update a deployment to change only the tag of their image, then they must re-enter the entire image URL with the new tag. Instead, we can pre-populate the image field with the existing image URL (including the tag), which means a user can now simply modify the tag without needing to re-enter the full URL themselves.
For example, if the deployment is currently using image "hello-world:1.0" and they want to modify it to use "hello-world:1.1", currently they would need to write the full text "hello-world:1.1". This can be quite cumbersome if the URL of the image is long (which it often is). With this change, the existing URL is pre-populated, so the user needs only to replace "0" with "1".
If a user does not want to modify the image of the deployment then they can continue …
> Pre-populate existing image when modifying a deployment

- .changeset/twenty-grapes-taste.md
- packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/ts/tsconfig.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/tsconfig.json
- packages/create-cloudflare/templates/common/ts/tsconfig.json
- packages/create-cloudflare/templates/hello-world-durable-object/ts/tsconfig.json
- packages/create-cloudflare/templates/hello-world/ts/tsconfig.json
- packages/create-cloudflare/templates/queues/ts/tsconfig.json
- packages/create-cloudflare/templates/scheduled/ts/tsconfig.json
`create-cloudflare` generates unnecessary verbose `tsconfig.json`.
I think it would be better to generate simpler configs not to confuse out users - simpler is better!
The current `tsconfig.json` templates are probably derived from `tsc --init` which does not make a lot of sense because they would be different for different version of TypeScript.
Fixes N/A.
- Tests
- [] Tests included
> refactor: simplify tsconfig templates

- tools/deployments/__tests__/validate-pr-description.test.ts
- tools/deployments/validate-pr-description.ts
The validation expects `/\[x\]/` for checkboxes while github accepts `/\[x\]/i`. This PR then makes the whole regexps case insensitive as case should not matter anyway.
Also removed a bunch a unnecessary snapshots.
I had the description test failed on https://github.com/cloudflare/workers-sdk/pull/6957 because of that.
Fixes N/A.
- Tests
> fix: relax PR description validation

- .changeset/light-wasps-promise.md
- packages/miniflare/src/plugins/queues/index.ts
- packages/miniflare/src/workers/queues/broker.worker.ts
- packages/miniflare/src/workers/queues/schemas.ts
- packages/miniflare/test/plugins/queues/index.spec.ts
- packages/miniflare/test/plugins/queues/retry.spec.ts
- packages/wrangler/src/dev/miniflare.ts
Fixes #MQ-731.
A user on Discord reported that for large retry delays, local queues were not retrying enough. Turns out the queue DO was being terminated. Thanks Samuel and Michael Hart for the assist!
- Tests
> fix(queues): Respect consumer `max_retries` and `retry_delay` properly

- .changeset/curly-jars-kick.md
- .changeset/tasty-chefs-watch.md
- packages/quick-edit/functions/_middleware.ts
- packages/workers-playground/package.json
- packages/workers-playground/src/QuickEditor/EditorPane.tsx
- packages/workers-playground/src/QuickEditor/HTTPTab/HTTPTab.tsx
- packages/workers-playground/src/QuickEditor/PreviewTab/PreviewTab.tsx
- packages/workers-playground/src/QuickEditor/PreviewTab/UrlBar.tsx
- packages/workers-playground/src/QuickEditor/QuickEditor.tsx
- packages/workers-playground/src/QuickEditor/useDraftWorker.ts
- pnpm-lock.yaml
Fixes [DEVX-1410](https://jira.cfdata.org/browse/DEVX-1410).
- Tests
> feat(worker-playground): delay preview environment setup

- fixtures/external-dispatch-namespace-app/dispatchee/index.ts
- fixtures/external-dispatch-namespace-app/outbound/index.ts
- fixtures/external-dispatch-namespace-app/tests/index.test.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dispatch-namespaces/fetcher.ts
- packages/wrangler/templates/middleware/middleware-dispatchee.ts
- packages/wrangler/templates/middleware/middleware-outbound.ts
> Fix headers in wfp dev

- packages/create-cloudflare/e2e-tests/frameworks.test.ts
This PR quarantines the C3 `analog` e2e tests, which started failing since yesterday. After thoroughly debugging together with Pete, we concluded that the breakage is not caused by one particular change in `workers-sdk`, but rather due to some changes in `analog` itself. Specifically, the breakage seems to come from the [latest release](https://github.com/analogjs/analog/blob/v1.9.0/CHANGELOG.md) of analog, aka `v 1.9.0`. Currently C3 has a dependency on analog `^1.8.0`, which ends up pulling `1.9.0`, and results in the failures we're seeing. We attempted to fix the version number of our dependency to `1.8.0`, but unfortunately that still end up pulling ` 1.9.0`, due to how analog internally declares its dependencies. This is something we don't have control over, which is why we …
> fix: quarantine C3 analog e2e tests

- .changeset/kind-tomatoes-smile.md
- packages/create-cloudflare/templates-experimental/astro/templates/wrangler.toml
> fix: use correct main file in wrangler.toml for astro + workers assets template

- .changeset/little-cheetahs-arrive.md
- packages/wrangler/src/__tests__/output.test.ts
- packages/wrangler/src/output.ts
- packages/wrangler/src/pages/deploy.tsx
https://github.com/cloudflare/wrangler-action/issues/300
Adds additional outputs to wrangler's artifact mechanism for pages deploys. This allows wrangler-action to pull from wrangler's artifacts to get info about pages deploys, adding parity to the outputs pages-action provides.
Test by installing the wrangler prerelease in a local pages project, setting WRANGLER_OUTPUT_FILE_DIRECTORY in the local environment, running a pages deploy, and checking the output file.
- Tests
> Add additional output fields to pages deployments

- .changeset/nine-cougars-repeat.md
- packages/wrangler/src/__tests__/delete.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/delete.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/tail/index.ts
> fix: better errors for workers commands in pages projects

- .changeset/early-kangaroos-guess.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/templates.ts
Fixes N/A
This PR adds the ability to go back to the project name prompt, mainly to give users an idea that they can always come back to the previous question when answering the prompt early on.
- Tests
> feat(create-cloudflare): allows user going back to the project name prompt

- .github/pull_request_template.md
- .github/workflows/validate-pr-description.yml
- tools/deployments/__tests__/validate-pr-description.test.ts
- tools/deployments/validate-pr-description.ts
This PR simplifies the PR template by:
- Removing the comment about highlighting PR reviews
- Removing the changesets sections. Instead, the PR validation has been updated to _require_ changesets, which is the right default for the vast majority of cases. This can be bypassed with the `no-changeset-required` label if needed. This should be really clear to developers, as the changeset bot posts a very visible comment with a warning icon when no changesets are found, and the failing PR validation check has clear language about how to fix things.
---
- Tests
> Simplify pull_request_template.md

- .changeset/pink-geckos-peel.md
- packages/quick-edit-extension/scripts/bundle.ts
- packages/quick-edit-extension/src/cfs.ts
Make sure we're loading the .d.ts and not the .ts version of the types. Occasionally the wrong version has been loaded in CI, causing spurious typing errors for users in the playground & quick edit. This PR simplifies the loading, and adds an assertion to make sure builds will fail if the wrong version is loaded. 
---
- Tests
> Try and ensure the `d.ts` types are definitely the ones loaded in `quick-edit-extension`

- .changeset/heavy-taxis-happen.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/index.ts
> Only show dev registry connection status in local dev

- .changeset/serious-gifts-thank.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/pipelines/client.ts
- packages/wrangler/src/pipelines/index.ts
Fixes [PIPE-37](https://jira.cfdata.org/browse/PIPE-37) (Support Authenticated HTTP Source in Worker Pipelines)
- Tests
> PIPE-37 Add authenticated HTTP source options to Worker Pipelines

- .changeset/odd-months-bake.md
- fixtures/pages-dev-proxy-with-script/tests/index.test.ts
- packages/wrangler/src/pages/dev.ts
On Node.js 17+, wrangler will default to fetching only the IPv6 address. With these changes we warn users that the process listening on the port specified via `--proxy` should be configured for IPv6.
Fixes #2244.
---
- Tests
> fix(wrangler):  Show `wrangler pages dev --proxy` warning

- .changeset/quiet-days-eat.md
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/src/d1/execute.tsx
Fixes #6938 
Already does this for remote, just logs a bit of feedback to the user for local as well.
- Tests
> fix: log successful execution of D1 commands locally

- .changeset/tasty-jeans-train.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/r2/helpers.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/notification.ts
Internal Issue: R2-2518
- Tests
> Add jurisdiction option to R2 event notification wrangler actions

- .changeset/hungry-news-own.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
Fixes [WC-2856](https://jira.cfdata.org/browse/WC-2856)
In interactive mode, if someone specifies a worker name that does not yet exist, ask for confirmation before actually creating that worker (e.g. in case it was a typo).
In non-interactive contexts (CI etc.), always create a worker to maintain existing behaviour.
---
- Tests
> fix: ask for confirmation before creating a new worker when uploading secrets

- .changeset/fair-fishes-do.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
> Validate duplicate bindings across all binding types

- .changeset/plenty-garlics-jump.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/notification.ts
Allows user to specify optional description for rule
- Tests
> Adding optional description to event notification rule config

- CODEOWNERS
Adds the newly minted [Deploy & Config team](https://github.com/orgs/cloudflare/teams/deploy-config) as owners of our stuff (asset-worker, router-worker, etc.) :)
---
- Tests
> Adds D&C as owners of workers-shared

- .changeset/polite-numbers-warn.md
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/helpers.ts
Fixes #7021
Reduce the KV bulk upload size from 5_000 to 1_000 to try and help reduce API timeout issues 
---
- Tests
> Reduce KV bulk upload size

- .changeset/smooth-kiwis-clean.md
- packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev.tsx
- pnpm-lock.yaml
Fixes #7025
In `--x-dev-env` we temporarily disable hotkeys while doing account selection. Previously we'd been unconditionally re-enabling them, but this meant that `--remote --show-interactive-dev-session` would eventually show the hotkeys. This PR changes things to only re-enable hotkeys if they'd previously been enabled.
---
- Tests
> Only enable hotkeys after authenticating if hotkeys were previously enabled

- .changeset/grumpy-eggs-rest.md
- packages/wrangler/src/workflows/commands/trigger.ts
Fixes WOR-280
Because the body for the trigger command changed, we also need to change it here. As a consequence we also add an optional `--id` to let users to optionally customize the new instance ID.
> feat: change trigger command to comply with new endpoint

- fixtures/unstable_dev/src/wrangler-dev.mjs
- fixtures/unstable_dev/wrangler.toml
Test to validate that #2389 is no longer an issue
---
- Tests
> Add test for custom build with `unstable_dev()`

- .changeset/early-parents-run.md
- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/vectorize/common.ts
- packages/wrangler/src/vectorize/create.ts
- packages/wrangler/src/vectorize/createMetadataIndex.ts
- packages/wrangler/src/vectorize/delete.ts
- packages/wrangler/src/vectorize/deleteByIds.ts
- packages/wrangler/src/vectorize/deleteMetadataIndex.ts
- packages/wrangler/src/vectorize/get.ts
- packages/wrangler/src/vectorize/getByIds.ts
- packages/wrangler/src/vectorize/index.ts
- packages/wrangler/src/vectorize/info.ts
- packages/wrangler/src/vectorize/insert.ts
- packages/wrangler/src/vectorize/list.ts
- packages/wrangler/src/vectorize/listMetadataIndex.ts
- packages/wrangler/src/vectorize/query.ts
- packages/wrangler/src/vectorize/upsert.ts
Replace the Vectorize Beta banner with the GA Announcement Banner
Also included a note regarding the blocking of legacy Vectorize index creation.
- Tests
> [Vectorize] Announcement Banner for Vectorize GA

- .changeset/empty-lamps-turn.md
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/dev.tsx
- packages/wrangler/src/dev/dev.tsx
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/vectorize/fetcher.ts
> VS-286 Support mixed-mode local bindings for Vectorize in Miniflare

- fixtures/additional-modules/turbo.json
- fixtures/nodejs-als-app/turbo.json
- fixtures/nodejs-hybrid-app/turbo.json
- fixtures/pages-plugin-example/turbo.json
- fixtures/pages-proxy-app/turbo.json
- fixtures/pages-ws-app/turbo.json
- lint-turbo.mjs
- package.json
- packages/cli/turbo.json
- packages/create-cloudflare/turbo.json
- packages/format-errors/turbo.json
- packages/kv-asset-handler/turbo.json
- packages/miniflare/turbo.json
- packages/prerelease-registry/turbo.json
- packages/turbo-r2-archive/turbo.json
- packages/vitest-pool-workers/turbo.json
- packages/workers-editor-shared/turbo.json
- packages/workers-playground/turbo.json
- packages/workers-shared/turbo.json
- packages/workflows-shared/turbo.json
- packages/wrangler/turbo.json
- pnpm-lock.yaml
- tools/turbo.json
- turbo.json
Fixes #6992
The result of running `pnpx @turbo/codemod migrate` from https://turbo.build/blog/turbo-2-0
---
- Tests
> Upgrade to turbo v2

- .changeset/shiny-files-jog.md
- packages/cli/interactive.ts
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/src/helpers/args.ts
Fixes n/a.
Previously, if you provide an invalid project name on the command, c3 will print an error message and **crash the CLI** immediately:
Now, it will prompt user to correct the answer instead. So it behave consistently as if user provide an invalid project name on the prompt.
---
- Tests
> feat(create-cloudflare): prompt user to correct the answer if the arg value is invalid

- .github/actions/install-dependencies/action.yml
Restore turbo loose mode after a change in defaults after Turbo v2: https://turbo.build/blog/turbo-2-0#correctness
(we can investigate strict mode as a follow-up, but this is currently causing our tests to fail and so is an okay bandaid)
---
- Tests
> Restore turbo loose mode

- .changeset/mighty-carrots-report.md
- packages/wrangler/src/__tests__/generate.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/init.ts
Fixes #5701
`wrangler init` simply forwards onto c3 now. It was deprecated, but loads of places/tutorials still mention it, and the warning was just scaring people off. 
new:
old:
---
- Tests
> fix: remove deprecation warnings for `wrangler init`

- .changeset/chilled-apes-repeat.md
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/versions/deploy.ts
In addition to logpush and tail_consumers, patch observability settings
on version deploy. This still doesn't quite match the behavior of
"wrangler deploy", which will disable observability if it is not defined
in wrangler.toml (as of #6776), but at least this is more correct for now.
- Tests
> Synchronize observability settings during versions deploy

- packages/wrangler/e2e/r2.test.ts
Fixes #7092.
This updates the r2 e2e snapshot that is currently broken on main.
---
- Tests
> chore: update r2 e2e snapshot

- .changeset/metal-ladybugs-teach.md
- packages/create-cloudflare/src/__tests__/dialog.test.ts
- packages/create-cloudflare/src/dialog.ts
Fixes DEVX-1388.
Adds a link to c3 message on where to go to file issues.
---
- Tests
> Add guidance to c3 on where to file issues 

- packages/wrangler-devtools/README.md
Fixes #000.
Improves the documentation surrounding our usage and maintenance of the Chrome DevTools patches.
---
- Tests
> chore: Improve readme for devtools package

- .changeset/odd-lions-warn.md
- packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
- packages/wrangler/src/cloudchamber/modify.ts
Depolyment label modification works as expected in non-interactive mode. However, during interactive mode, we do not add the required labels to the final API Request.
Added labels fixture to modification tests as well.
Fixes CC-4451
---
- Tests
> fix: Modify Cloudchamber deployment labels in interactive mode

- .changeset/eleven-cobras-repeat.md
- packages/wrangler/src/__tests__/configuration.pages.test.ts
- packages/wrangler/src/config/validation.ts
Fixes #6266 
The binding name "ASSETS" is used internally by pages projects. If a user had a binding with this name (totally sensible binding name for an r2 bucket for example) it would fail cryptically (see linked issue). 
---
- Tests
> fix: add better error for user binding called ASSETS in pages projects

- .github/workflows/c3-dependabot-versioning-prs.yml
- .github/workflows/changesets.yml
- .github/workflows/create-pullrequest-prerelease.yml
- .github/workflows/d1.yml
- .github/workflows/deploy-pages-previews.yml
- .github/workflows/e2e-project-cleanup.yml
- .github/workflows/holopin.yml
- .github/workflows/miniflare-dependabot-versioning-prs.yml
- .github/workflows/prerelease-workflows.yml
- .github/workflows/prereleases.yml
- .github/workflows/validate-pr-description.yml
- .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
- .github/workflows/write-prerelease-comment.yml
Fixes n/a.
Github updates the `ubuntu-latest` image tag to `ubuntu-24.04` recently which missed a few dependencies that is required for our release setup last week. They [rolled back to `ubuntu-22.04`](https://github.com/actions/runner-images/issues/10636#issuecomment-2417293457) but it is probably safer to lock the version. 
This PR pins the runner image of non test related workflows to `ubuntu-22.04`.
---
- Tests
> chore: pin runner image of non test related workflows to ubuntu-22.04

- .changeset/cool-dragons-brush.md
- packages/devprod-status-bot/wrangler.toml
- packages/edge-preview-authenticated-proxy/wrangler.toml
- packages/format-errors/wrangler.toml
- packages/playground-preview-worker/wrangler.json
Fixes N/A
Sometimes devprod status bot doesn't post, and mostly I just wanted to try out observability.
---
- Tests
> chore: enable observability for infra bots + devprod status bot

- .changeset/friendly-ears-breathe.md
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/init.ts
Fixes [PIPE-124](https://jira.cfdata.org/browse/PIPE-124).
Replaces PR #7100
Recently, Pipelines switched to binding by pipeline names instead of pipeline IDs. This change formalizes that. 
---
- Tests
> Change Pipelines to use name instead of id

- .changeset/selfish-readers-exercise.md
- packages/wrangler/src/__tests__/logout.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/index.ts
Fixes [WO-184](https://jira.cfdata.org/browse/WO-184)
- Tests
> Disable warnings for invalid config in wrangler login & logout

- .changeset/giant-bottles-trade.md
- packages/wrangler/src/secret/index.ts
Moves the banner into the `args` handler like the rest of the commands as this command was printing the banner in the `--help` output.
```
➜  ~ npx wrangler secret delete --help
⛅️ wrangler 3.78.3 (update available 3.81.0)
-------------------------------------------------------
wrangler secret delete <key>
Delete a secret variable from a Worker
POSITIONALS
key  The variable name to be accessible in the Worker  [string] [required]
GLOBAL FLAGS
-j, --experimental-json-config  Experimental: support wrangler.json  [boolean]
-c, --config                    Path to .toml configuration file  [string]
-e, --env                       Environment to use for operations and .env files  [string]
-h, --help                      Show help  [boolean]
-v, --version                   Show version number …
```
> chore: move printWranglerBanner for secret delete into handler

- .changeset/tame-dryers-end.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/r2/helpers.test.ts
- packages/wrangler/src/r2/domain.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
- packages/wrangler/src/r2/notification.ts
Added the ability to list, add, remove, and update R2 bucket custom domains.
---
- Tests
> Added the ability to list, add, remove, and update R2 bucket custom domains

- packages/wrangler/e2e/dev-with-resources.test.ts
Fixes #7134.
The pipeline binding is not ready yet as confirmed with @cmackenzie1. This should resolve the error we currently see on e2e tests.
---
- Tests
> chore: mark pipeline bindings e2e test should fail

- .changeset/sweet-toes-check.md
- packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/__tests__/navigator-user-agent.test.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/dev/local.tsx
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/dev/start-server.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/versions/upload.ts
Fixes #7152 
Correctly pass the `--test-scheduled` flag in `BundleController` when using a custom build. Previously the types for `bundleWorker()` allowed arguments not to be passed—this PR changes that to require an explicit `undefined` to be passed, which should prevent this type of regression happening again.
---
- Tests
> Fix `--test-scheduled` with custom builds & `--x-dev-env`

- .changeset/little-lamps-provide.md
- packages/create-cloudflare/package.json
- packages/create-cloudflare/templates-experimental/solid/c3.ts
- pnpm-lock.yaml
Fix Cloudflare Pages command for Solid. Replaced `./cloudflare-pages` by `cloudflare-pages`
---
- Tests
> Fix Cloudflare Pages command for Solid

- .changeset/famous-chairs-sin.md
- packages/create-cloudflare/templates/astro/templates/wrangler.toml
Fixes n/a.
Our create-cloudflare e2e test has been failing getting the preview running on astro for a while (e.g. [This CI run](https://github.com/cloudflare/workers-sdk/actions/runs/11683132429/job/32531697289#step:4:245)). This PR should fix the issue.
---
- Tests
> fix(create-cloudflare): enable nodejs_compact on astro template

- packages/miniflare/test/plugins/d1/suite.ts
`workerd` has made a change to how multiple D1 statements are treated and some cases that used to be an error are no longer an error. This change adapts Miniflare's test suite to handle both the old and new behaviour, to unblock a `workerd` release.
---
- Tests
> Handle new D1 workerd behaviour in Miniflare's tests

- .changeset/young-lions-type.md
- packages/create-cloudflare/templates-experimental/remix/c3.ts
- packages/create-cloudflare/templates-experimental/remix/templates/public/.assetsignore
- packages/create-cloudflare/templates-experimental/remix/templates/wrangler.toml
Fixes n/a.
This PR updates the experimental remix template to be based on its worker template.
Ref: https://github.com/remix-run/remix/pull/10034
---
- Tests
> feat(create-cloudflare): update experimental remix template to be based on its worker template

- .changeset/large-otters-search.md
- packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
- packages/wrangler/e2e/dev-registry.test.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/logger.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/logger.ts
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/index.ts
Cleans up & clarifies dev registry messaging (mostly in response to https://github.com/cloudflare/workers-sdk/issues/7009#issuecomment-2427012598) cc @isaac-mcfadyen 
- Shift from inscrutable red & green dots to `connected`/`not connected` with an explanation logged the first time
- Remove the "Live workers" warning in local mode, where it doesn't apply
---
- Tests
> Cleanup dev registry messaging

- .changeset/seven-parents-report.md
- packages/workers-shared/asset-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/index.ts
Fixes bug where indexId was never provided to analytics.
---
Hostname was never provided as a param to write, causing indexId to never be set. In addition, small refactor to remove all params from Analytics.write().
- Tests
> Fixes bug where indexId was never provided to analytics

- .changeset/happy-items-buy.md
- packages/create-cloudflare/templates-experimental/svelte/c3.ts
- packages/create-cloudflare/templates/svelte/c3.ts
The name currently displayed in the CLI is `Svelte`. However, all of the options actually create a `SvelteKit` app, and the name `SvelteKit` is also used in the [documentation](https://developers.cloudflare.com/pages/framework-guides/deploy-a-svelte-site/).
- Tests
> Rename the framework name

- .changeset/famous-keys-walk.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/helpers/command.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
Fixes #6510, fixes #4637
Remove the special handling for the `Failed to start ProxyWorker or InspectorProxyWorker` error. The intention of this code was to recover from port conflicts when running `wrangler dev`, but it actually seems to have been causing orphaned `workerd` processes. Because we use `getPort()` when resolving config in `ConfigController`, the only way this code path is hit is if the proxy `workerd` instance fails to start because of a port conflict where the user has _specified_ a port (i.e. with `--port` or `dev.port = `) that conflicts (or is reserved e.g. 80). In those cases, this codepath restarted `workerd` with a different port, but _also_ ended up hitting `throw error;` in `ProxyController`, which ended up with a global uncaught exception that crashed the Wrangler …
> Remove special handling for 'Failed to start ProxyWorker or InspectorProxyWorker'

- .changeset/thin-hairs-explain.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
- packages/wrangler/src/r2/public-dev-url.ts
Added the ability to enable, disable, and get r2.dev public access URLs for R2 buckets.
---
- Tests
> Added the ability to enable, disable, and get r2.dev public access URLs for R2 buckets

- .changeset/famous-birds-remain.md
Fixes N/A.
It was decided that the DevTools work [here](https://github.com/cloudflare/workers-sdk/pull/7137) should be `minor` instead of `patch`.
---
- Tests
> chore: update Wrangler DevTools semver to minor

- .github/workflows/deploy-pages-previews.yml
Fixes N/A.
We already have a PR comment for when you have the `preview:workers-playground` and `preview:wrangler-devtools` labels, but it would also be useful to display a link to the DevTools preview even if the Playground preview has not been requested. 
This PR ensures that the DevTools preview link is displayed in the comment along with some simple instructions of how to test it.
---
- Tests
> chore: add more useful information in the PR coment for previews

- packages/wrangler/e2e/helpers/normalize.ts
- packages/wrangler/e2e/r2.test.ts
Fixes n/a.
https://github.com/cloudflare/workers-sdk/commit/ad51d1d77483bf0b4dc73fd392f5cdefe4ddf5d8 broke a related R2 e2e test, which we didn't see due to the fact that e2es were not run on that PR. This PR fixes the breakage.
---
- Tests
> fix(wrangler): fix failing R2 e2e test

- .changeset/hungry-hornets-taste.md
- packages/wrangler/src/dev/inspect.ts
Fixes #1445 
In the latest version of devtools (#7008), Safari is supported! This means we can finally just use the users default browser when opening a debugger.
Blocked on #7008
---
- Tests
> Open devtools in default browser

- .changeset/smart-drinks-joke.md
- packages/create-cloudflare/src/__tests__/deploy.test.ts
- packages/create-cloudflare/src/deploy.ts
Previously, C3 ran `wrangler deploy` and `wrangler pages deploy` non-interactively. Since this is intended to be an interactive command, this led to various bugs. However, since C3 parsed the output of Wrangler's deploy command (and that's not possible with an interactive spawn), a change was also needed to how C3 figured out what Wrangler did during a deploy. This PR runs the deploy command interactively, after that change to Wrangler's output was made in https://github.com/cloudflare/workers-sdk/pull/6571
Fixes #4915, fixes #4263, fixes #6230
- Tests
> Run deploy interactively in C3

- .changeset/nice-chefs-hang.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/assets.ts
Fixes WC-2707.
Adds support for Tail Consumers with Workers which have Assets
---
- Tests
> Add support for Tail Consumers with Assets

- packages/wrangler-devtools/README.md
Fixes #000.
Adds some documentation surrounding labels and previews for DevTools and Playground, specifically mentioning the PR comment that is created when a preview build completes.
---
- Tests
> docs: better wording on DevTools readme

- .changeset/new-adults-float.md
- packages/wrangler/src/d1/migrations/create.ts
Fixes wrong console output after using `wrangler d1 migrations create`
Before: /home/user/path/{newMigrationName}
After: /home/user/path/0001_migration.sql
---
- Tests
> [D1] fix console output for `wrangler d1 migrations create`

- .changeset/clean-tigers-breathe.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/__tests__/helpers/mock-workers-subdomain.ts
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/deploy/deploy.ts
Many tests had mocks that weren't called, or had false assertions about not updating subdomain routes when they actually were being updated.
Additionally, available_on_subdomain is now unecessary during script-upload, as it is not read there, due to being handled entirely within triggers-deploy. This also saves a double call to get /subdomain in the new-api path.
The get/update subdomain helpers are refactored from deploy/version tests, and unified to standardize default workername and legacyEnv.
I wanted to remove the getSubdomain mock from mockUpload entirely, but there were a bit too many callsites... At least every test now that makes assertions about workers.dev deployments does explicitly reset the mock return value.
Fixes N/A
- Tests
- E2E Tests CI Job required? (Use "e2e" label or …
> improve(wrangler): fix subdomain tests

- .changeset/tame-bobcats-suffer.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
- packages/wrangler/src/r2/info.ts
- packages/wrangler/src/r2/list.ts
Added wrangler r2 bucket info command, improved formatting of output for r2 bucket list command
---
- Tests
> Added wrangler r2 bucket info command, improved formatting of list command

- packages/wrangler/src/docs/index.ts
- packages/wrangler/src/index.ts
> chore: use defineCommand in `wrangler docs`

- .changeset/little-crabs-rule.md
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/metrics/commands.ts
- packages/wrangler/src/metrics/metrics-config.ts
Fixes [DEVX-1480](https://jira.cfdata.org/browse/DEVX-1480)
Adds new `wrangler telemetry disable` and `wrangler telemetry enable` commands which globally toggle telemetry collection across all projects on that machine.
Adds a new `wrangler telemetry status` command which shows the current telemetry setting, resolved to the current project.
With send_metrics set in wrangler.toml
With WRANGLER_SEND_METRICS environment variable set
Without either send_metrics or WRANGLER_SEND_METRICS set
We prioritise env var > wrangler.toml > global setting via command.
NB we're using a feature branch so will add one changeset when we merge that in.
---
- Tests
> feat: add telemetry commands

- .changeset/tricky-bottles-bow.md
- fixtures/unstable_dev/src/wrangler-dev.mjs
- packages/wrangler/e2e/dev-registry.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/dev-registry/file-registry.ts
- packages/wrangler/src/dev.ts
Fixes #6955
Use the file based registry by default. It can still be disabled by setting `--x-registry=false` when running `wrangler dev`
---
- Tests
> Default `--x-registry` to on

- .changeset/shaggy-monkeys-visit.md
- packages/wrangler/src/__tests__/check-fetch.test.ts
- packages/wrangler/src/api/pages/deploy.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/buildFunctions.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
Now that we have the `allow_custom_ports` compatibility flag, we only need to show the fetch warnings when that flag is not enabled.
Fixes #6950
Fixes https://github.com/cloudflare/workerd/issues/2955
- Tests
> fix: only show fetch warning if on old compatibility_date

- .changeset/four-mayflies-smash.md
- packages/create-cloudflare/src/helpers/__tests__/packageManagers.test.ts
- packages/create-cloudflare/src/helpers/packageManagers.ts
Adds support for upcoming `bun.lock` to  `detectPmMismatch ` method. 
https://x.com/jarredsumner/status/1839056611765268651
- Tests
> chore(create-cloudflare): add support for new bun.lock

- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/metrics/commands.ts
Fixes [DEVX-1503](https://jira.cfdata.org/browse/DEVX-1503)
---
- Tests
> feat: add `wrangler metrics` as an alias for `wrangler telemetry`

- .changeset/mighty-beds-grab.md
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/output.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/upload.ts
Fixes #7240
Include the version preview URL from `wrangler versions upload` in Wrangler's output file.
---
- Tests
> Include Version Preview URL in Wrangler output file

- .changeset/shy-seas-wave.md
- packages/wrangler/package.json
- pnpm-lock.yaml
Update unenv
The newer version on unenv uses the native impl of "path/win32" and "path/posix", see the [workerd changes](https://github.com/cloudflare/workerd/releases/tag/v1.20241106.0#:~:text=in%20%232288-,add%20missing,-tests%20for%20node)
/cc @anonrig 
---
- Tests
> chore(wrangler): update unenv dependency version

- .changeset/hip-cycles-explain.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/dialogs.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/index.ts
- packages/wrangler/src/r2/lifecycle.ts
Added r2 bucket lifecycle command (list, add, remove, set)
---
- Tests
> Added r2 bucket lifecycle command (list, add, remove, set)

- .changeset/curly-rice-travel.md
- packages/wrangler/src/__tests__/pages/deployment-list.test.ts
- packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
- packages/wrangler/src/pages/deployment-tails.ts
- packages/wrangler/src/pages/deployments.ts
Adds the --environment flag to `wrangler pages deployment list`, which should allow users to list deployments of a specific type. When the flag it's not provided it will list the latest 25 deployments regardless of type.
Additionally, makes sure we're listing the correct type of deployments when attempting to tail.
Fixes #6234.
Docs PR:
https://github.com/cloudflare/cloudflare-docs/pull/18278
---
- Tests
> wrangler pages deployment (list|tail) env filtering

- .changeset/sixty-news-relax.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
- packages/wrangler/src/__tests__/api/startDevWorker/ConfigController.test.ts
- packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
- packages/wrangler/src/__tests__/find-additional-modules.test.ts
- packages/wrangler/src/__tests__/get-entry.test.ts
- packages/wrangler/src/__tests__/navigator-user-agent.test.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
- packages/wrangler/src/deployment-bundle/resolve-entry.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/versions/index.ts
https://github.com/cloudflare/workers-sdk/pull/6971 introduced a small regression in the `getEntry()` function that meant that `Entry.directory` was always `process.cwd()` rather than relative to the found `wrangler.toml` file. This PR fixes the regression & adds a regression test that fails on `main` but passes prior to #6971.
---
- Tests
> Fix relative project root

- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/metrics/metrics-config.ts
- packages/wrangler/src/metrics/metrics-dispatcher.ts
Fixes [DEVX-1482](https://jira.cfdata.org/browse/DEVX-1482) in 56c4cfaeff287e56121b0994b0a1720b21704718 and 2d654bc2261272fbec4887a3acd285d57ddb1fb6
(link TBD)
Fixes [DEVX-1506](https://jira.cfdata.org/browse/DEVX-1506) in de7ebf222c787e60e8badfa6f5626e37c3be7589
Also adds some basic tests for sendNewEvent in 6b2233853d691315684dc0ee7c811d2898fc5279
Also make sure events are settled before exiting wrangler (with a timeout) 3df6ab18491b6efbf287d017d8c0548ef35e173a
---
- Tests
> feat: add banner to indicate when telemetry is on

- packages/wrangler/src/__tests__/vitest.global.ts
- packages/wrangler/src/__tests__/vitest.setup.ts
- packages/wrangler/vitest.config.mts
Apparently setting `LC_ALL` in `vitest.setup.ts` doesn't work, as this is after the locale settings are read, but it does work in a `globalSetup` file.
This can be observed locally with the Workflows tests:
```
➜  wrangler git:(fix-test-locale) npx vitest run src/__tests__/workflows.test.ts >&/dev/null; echo $?
0
➜  wrangler git:(fix-test-locale) git checkout origin/main vitest.config.mts && LC_ALL=en_UK npx vitest run src/__tests__/workflows.test.ts >&/dev/null; echo $?
Updated 1 path from e1554242a
1
```
---
- Tests
> test: fix system locale override

- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/metrics/metrics-config.ts
- packages/wrangler/src/metrics/metrics-dispatcher.ts
- packages/wrangler/src/metrics/send-event.ts
[DEVX-1512](https://jira.cfdata.org/browse/DEVX-1512) - add argsUsed, argsCombination, isCI and isInteractive
also redact string arg values
---
- Tests
> feat: add some more properties to telemetry events

- .changeset/cyan-laws-mate.md
- fixtures/asset-config/redirects.test.ts
- fixtures/asset-config/url-normalization.test.ts
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
Prevents same-schema redirect attacks by collapsing multiple slashes in the path.
- Tests
> Normalize workers assets path

- .changeset/funny-dingos-guess.md
- packages/workers-shared/asset-worker/vitest.config.mts
- packages/workers-shared/asset-worker/wrangler.toml
- packages/workers-shared/package.json
- packages/workers-shared/router-worker/src/index.ts
- packages/workers-shared/router-worker/tests/index.test.ts
- packages/workers-shared/router-worker/tests/tsconfig.json
- packages/workers-shared/router-worker/vitest.config.mts
- packages/workers-shared/router-worker/wrangler.toml
- packages/workers-shared/tsconfig.json
- packages/workers-shared/utils/types.ts
- pnpm-lock.yaml
This PR provides the option for user worker to run ahead of assets.
- Adds logic to run user-worker ahead of assets
- Moves vitest from worker-shared root into asset-worker
- Creates new vitest unit test suite for router-worker
---
- Tests
> Modify router-worker logic to allow for running user-worker ahead of assets

- pnpm-lock.yaml
https://github.com/cloudflare/workers-sdk/pull/7319 somehow broke the build.
Updated the lock file to fix.
---
- Tests
> fix: missing unenv version in lockfile

- .changeset/famous-dragons-retire.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/constants.ts
Added Oceania (oc) location hint as acceptable choice when creating an R2 bucket.
---
- Tests
> Added Oceania (oc) location hint as acceptable choice when creating an R2 bucket.

- .changeset/six-coats-rule.md
- fixtures/asset-config/html-handling.test.ts
- fixtures/asset-config/redirects.test.ts
- fixtures/asset-config/url-normalization.test.ts
- packages/workers-shared/asset-worker/src/configuration.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
- packages/workers-shared/utils/types.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/assets.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
Provides serve_directly option in asset metadata
- Tests
> Add serve_directly option to assets configuration

- .changeset/metal-flies-cross.md
- packages/workers-shared/asset-worker/src/index.ts
When I was looking through the Asset Worker code I spotted an error:
https://github.com/cloudflare/workers-sdk/blob/afe9850931b7730989e005a612ea74887f5d5e72/packages/workers-shared/asset-worker/src/index.ts#L132-L135
This currently does the opposite of what it should and returns the `MethodNotAllowedResponse` for `GET` and `HEAD` methods. The only reason that the Router Worker is still functioning correctly is because it treats the `MethodNotAllowedResponse` as truthy.
https://github.com/cloudflare/workers-sdk/blob/afe9850931b7730989e005a612ea74887f5d5e72/packages/workers-shared/router-worker/src/index.ts#L60
I've removed method handling from `unstable_canFetch` altogether as I feel that it should only return a boolean. The Asset Worker already returns a `MethodNotAllowedResponse` for …
> Remove incorrect logic in Asset Worker

- packages/workers-shared/package.json
- pnpm-lock.yaml
Fixes n/a.
#7303 used the [`latest` tag to avoid circular dependency error](https://github.com/cloudflare/workers-sdk/pull/7303/files#diff-a985d0d721029f4a3190943f890e0b354a0fbd71185927e9a8d343795b0ad5f3R51) with turborepo (e.g. [this](https://github.com/cloudflare/workers-sdk/actions/runs/12011683817/job/33481232134#step:4:21)). However, this breaks our changesets CI job as it fails to resolve the `latest` tag version. (e.g. [this](https://github.com/cloudflare/workers-sdk/actions/runs/11977329550/job/33394964404#step:6:28)). 
This PR replaces the `latest` tag with a caret version range to avoid the issue above.
---
- Tests
> chore(workers-shared):  use version range instead of tag to avoid issues with changesets CI

- .changeset/config.json
Fixes #7331
In #7331, we replaced the `latest` tag with a caret version range to avoid an issue on changeset which fails to resolve the latest tag version for comparsion. However, it doesn't solve the issue completely as changeset attempts to bump the version in the CI regardless and fails updating the pnpm lockfile with the following error meesage:
```sh
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @cloudflare/vitest-pool-workers@^0.5.32
This error happened while installing a direct dependency of /Users/edmund/Workspace/workers-sdk/packages/workers-shared
The latest release of @cloudflare/vitest-pool-workers is "0.5.31".
If you need the full list of all 97 published versions run "$ pnpm view @cloudflare/vitest-pool-workers versions".
Progress: resolved 231, reused 0, …
```
> chore: restrict changeset version bump to workspace protocol only

- .changeset/six-apes-pull.md
- packages/wrangler/src/__tests__/cloudchamber/common.test.ts
- packages/wrangler/src/__tests__/cloudchamber/create.test.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/cloudchamber/create.ts
- packages/wrangler/src/cloudchamber/modify.ts
Add a default image when using "wrangler cloudchamber create". This image is docker.io/cloudflare/hello-world which is a simple HTTP server that runs on Cloudflare's container platform.
This commit also augments validation to both the `cloudchamber create` and `cloudchamber modify` commands to ensure the provided image contains a tag and adheres to the format in the OCI specification.
Fixes CC-4280.
- Tests
> Add default image for cloudchamber create

- .changeset/six-coats-rule.md
- fixtures/asset-config/html-handling.test.ts
- fixtures/asset-config/redirects.test.ts
- fixtures/asset-config/url-normalization.test.ts
- packages/workers-shared/asset-worker/src/configuration.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
- packages/workers-shared/utils/types.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/assets.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
> Unrevert "Add serve_directly option to assets configuration (#7316)"

- .changeset/hip-penguins-kiss.md
- fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
- packages/vitest-pool-workers/src/worker/fetch-mock.ts
This PR introduces support for `AbortSignal` to fetch-mock, allowing signals to 'abort' requests during tests as they do at actual runtime. This makes it significantly easier to test this behaviour when writing tests that rely on signals and their behaviours.
- Tests
- Unit tests cover changes 
- This not being supported was a little cryptic as it was undocumented but suggested in the discord community to use `AbortSignal` when wanting to time out fetch calls. Supported `AbortSignal` aligns with what is expected of `fetch` in tests reflecting actual usage.
> vitest-pool-workers: Support AbortSignal in fetch-mock

- .changeset/cuddly-chicken-visit.md
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/hyperdrive/create.ts
Fixes #[SQC-348].
This change gives wrangler users a quality of life improvement when creating a Hyperdrive config, giving them a copyable snippet to paste in their `wrangler.toml` file to bind their new Hyperdrive Config to their Worker.
---
- Tests
> Print copyable wrangler.toml text when creating a hyperdrive config

- packages/wrangler/src/user/user.ts
This exposes a new `getOauthToken()` function that can be used to directly retrieve an oauth token for a specific client/scopes. `wrangler login` has been refactored to use this.
---
- Tests
> Refactor login to expose a direct function to retrieve an Oauth token

- .changeset/silly-news-compete.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation/index.ts
Fixes #7346 
`wrangler types` used to fail if an entrypoint was specified in config, but did not exist (e.g. not built yet), because of an assertion inside `getEntry()`
---
- Tests
> fix: allow `wrangler types` when expected entrypoint doesn't exist

- .changeset/seven-eels-reflect.md
- packages/wrangler/e2e/dev-registry.test.ts
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/pages/dev.ts
Fixes #7322
When flipping the `--x-registry` default, we forgot to turn it on for Pages, resulting in Pages and Workers not being able to connect over service bindings unless `--x-registry=false` was specified on the Worker invocation. Our tests didn't catch this because they always specified the `--x-registry` flag (for both the true and false case), and so the defaults weren't being tested. This PR:
- Switches the default to `true` for Pages
- Changes our E2E tests to correctly test the default (i.e. only the false branch has a flag provided)
- Adds additional Pages E2E tests
---
- Tests
> Turn on `--x-registry` for Pages by default

- fixtures/vitest-pool-workers-examples/vitest.global.ts
- fixtures/vitest-pool-workers-examples/vitest.workers.config.ts
Fixes #000.
When running tests locally, the machine's timezone can cause issues with tests that rely on `Date`. This PR pins the timezone to `UTC`, so that it's the same for everyone, whether running locally or in CI.
Before 😞 
After 😄 
- Tests
> test: fix timezone for tests

- .changeset/lucky-carrots-sparkle.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/d1/utils.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/kv/index.ts
Fixes [DEVX-1418](https://jira.cfdata.org/browse/DEVX-1418).
This PR is the first step toward enabling automatic resource provisioning, allowing users to skip specifying resource identifiers in the Wrangler configuration. For now, this is limited to KV, R2, and D1 to keep the scope manageable.
---
- Tests
> feat(wrangler): make resources identifier optional if x-provision flag is enabled

- .changeset/node-compat-v4.md
- fixtures/node-app-pages/tests/index.test.ts
- packages/miniflare/src/plugins/core/node-compat.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/__tests__/config-validation-pages.test.ts
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/pages/deploy.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/build-failures.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/log-build-output.ts
- packages/wrangler/src/deployment-bundle/node-compat.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/type-generation/index.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/upload.ts
- pnpm-lock.yaml
Fixes https://github.com/cloudflare/workers-sdk/issues/1232, fixes #6189
The `--node-compat` flag and `node_compat` config properties are no longer supported as of Wrangler v4. Instead, use the `nodejs_compat` compatibility flag. This includes the functionality from legacy `node_compat` polyfills and natively implemented Node.js APIs. See https://developers.cloudflare.com/workers/runtime-apis/nodejs for more information.
This PR removes support for `node_compat`
---
- Tests
> Remove `node_compat` in Wrangler & Miniflare v4

- packages/wrangler/src/__tests__/configuration.test.ts
Fixes #7377.
This resolves the type error currently on `main`:
https://github.com/cloudflare/workers-sdk/actions/runs/12086612633/job/33706275523
---
- Tests
> chore(wrangler): fix type errors with experimental flags

- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-compat.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/nodejs-plugins.ts
> refactor(wrangler): Explicitely pick node compat plugins for each mode

- .changeset/witty-dolphins-appear.md
- packages/create-cloudflare/templates/angular/c3.ts
- packages/create-cloudflare/templates/angular/templates/src/server.ts
AngularAppEngine class does not have .render method, instead it should be .handle method
https://github.com/cloudflare/workers-sdk/issues/7341
AngularAppEngine class does not have .render method, instead it should be .handle method
changed method name from ".render" to ".handle" as the official doc below
https://angular.dev/api/ssr/AngularAppEngine
---
- Tests
> fix: error in angular c3 template

- packages/wrangler/README.md
Remove warning about v2 from the main README. It's on the v2 README, and now we're over a year from the release of v3 _most_ new users seeing the README won't have heard of v3.
> Remove v2 warning

- .changeset/gorgeous-paws-compare.md
- packages/workers-shared/router-worker/src/index.ts
Fixes N/A
Stops us waiting on asset Worker to return and escalating the errors upwards. We don't need to do this and it currently skews metrics as well.
---
- Tests
> Remove await from user Worker fetch in router-worker

- .changeset/sour-pugs-agree.md
- packages/miniflare/src/workers/queues/schemas.ts
- packages/miniflare/test/plugins/queues/index.spec.ts
Fixes #7398 
[max_batch_timeout](https://developers.cloudflare.com/queues/platform/limits/) seems to have been increased (30s -> 60s), updating miniflare validation schema to match. 
---
- Tests
> fix: update queues max_batch_timeout in miniflare

- fixtures/import-npm/package-lock.json
- packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/find-additional-modules.test.ts
- packages/wrangler/src/__tests__/get-entry.test.ts
- packages/wrangler/src/__tests__/navigator-user-agent.test.ts
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation-pages.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/d1/execute.ts
- packages/wrangler/src/d1/migrations/helpers.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
- packages/wrangler/src/deployment-bundle/module-collection.ts
- packages/wrangler/src/deployment-bundle/resolve-entry.ts
- packages/wrangler/src/dev/use-esbuild.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/versions/index.ts
- packages/wrangler/src/versions/upload.ts
A refactor to move the `projectRoot` field to config (from entry) so that it can be used more flexibly.
> refactor: move projectRoot computation to config validation

- packages/workers-shared/package.json
Super simple. This is only apparent if you disable concurrent tests when running locally.
But if you do that then the whole test run grinds to a halt after this job since it is waiting for further changes rather than exiting and moving on to the next job.
> ci: don't watch for changes on the workers-shared test:ci job

- fixtures/workflow-multiple/package.json
- fixtures/workflow/package.json
- packages/wrangler/src/__tests__/get-entry.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/deployment-bundle/entry.ts
Follow up from https://github.com/cloudflare/workers-sdk/pull/7415#discussion_r1867462290
> refactor: remove missed redundant computation of `projectRoot`

- .changeset/quick-bananas-refuse.md
- packages/create-cloudflare/templates-experimental/solid/c3.ts
- packages/create-cloudflare/templates-experimental/solid/templates/wrangler.toml
Fixes #0000
fix: C3 experimental template for Solid now uses correct preset
- Tests
> fix: C3 experimental template for Solid now uses correct preset

- .changeset/forty-gifts-grab.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/assets.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/triggers/index.ts
- packages/wrangler/src/versions/index.ts
Fixes #0000
We want to allow build tools (e.g. Nuxt/Vite/Next.js etc) to own the `main` and `assets.directory` fields in deployment configuration since they are the ones that generate these files.
In that case it doesn't makes sense for the user to provide them in their user configuration.
The `main` field is already optional from the point of view of the syntax check of the user's configuration file (e.g. wrangler.toml); this PR just makes the `assets.directory` field the same.
It is still an error to attempt to deploy or dev a Worker with an `assets` field but no `assets.directory`.
---
- Tests
> fix: allow the asset directory to be omitted in Wrangler config for commands that don't need it

- .changeset/breezy-cats-matter.md
- packages/wrangler/src/api/integrations/platform/index.ts
In the Vite plugin we are looking at generating `wrangler.json` files as part of the build process. Exporting these utils and types enables us to do this.
- Tests
> Export config types/utils

- .changeset/yellow-cooks-battle.md
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
- packages/wrangler/src/__tests__/versions/secrets/list.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/__tests__/versions/secrets/utils.ts
- packages/wrangler/src/api/pages/deploy.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/core/register-yargs-command.ts
- packages/wrangler/src/pages/build-env.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/deploy.ts
- packages/wrangler/src/pages/secret/index.ts
- packages/wrangler/src/versions/secrets/bulk.ts
- packages/wrangler/src/versions/secrets/delete.ts
- packages/wrangler/src/versions/secrets/list.ts
- packages/wrangler/src/versions/secrets/put.ts
- packages/wrangler/src/versions/upload.ts
- packages/wrangler/src/versions/utils/config.ts
Fixes #0000
Ensures that version secrets commands do not write wrangler config warnings.
This was a regression introduced by https://github.com/cloudflare/workers-sdk/pull/7437.
---
- Tests
> fix: ensure that version secrets commands do not write wrangler config warnings

- .changeset/strong-kings-visit.md
- fixtures/workers-with-assets-serve-directly/README.md
- fixtures/workers-with-assets-serve-directly/package.json
- fixtures/workers-with-assets-serve-directly/public/index.html
- fixtures/workers-with-assets-serve-directly/src/index.ts
- fixtures/workers-with-assets-serve-directly/tests/index.test.ts
- fixtures/workers-with-assets-serve-directly/tests/tsconfig.json
- fixtures/workers-with-assets-serve-directly/tsconfig.json
- fixtures/workers-with-assets-serve-directly/wrangler.toml
- packages/workers-shared/router-worker/tests/index.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/src/assets.ts
- pnpm-lock.yaml
Add support in wrangler dev for invoking user worker ahead of assets via `experimental_serve_directly = false`. Additionally adds several unit, integration, and e2e tests for serve_directly behavior.
- Tests
> Wranger dev support with serve_directly

- .changeset/breezy-cats-matter.md
- .changeset/lemon-panthers-arrive.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/local-mode-tests/tests/module.test.ts
- fixtures/local-mode-tests/tests/ports.test.ts
- fixtures/local-mode-tests/tests/specified-port.test.ts
- fixtures/local-mode-tests/tests/sw.test.ts
- fixtures/no-bundle-import/src/index.test.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/vitest-pool-workers/src/config/pages.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/templates/init-tests/test-vitest-new-worker.ts
Fixes #0000
We use `unstable_` as a prefix for experimental/unstable functions, but we were using just `Unstable` without the underscore as a prefix for types.
This change ensures that all unstable type exports are prefixed with `Unstable_` rather than just `Unstable`.
---
- Tests
> refactor: Ensure that unstable type exports are all prefixed with `Unstable_` rather than just `Unstable`

- .changeset/eighty-lies-sort.md
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Fixes N/A
This PR simply bumps `vitest` in the C3 templates to the latest version currently supported, `2.1.6`. 
---
- Tests
> chore: bump vitest in templates

- .changeset/metal-feet-carry.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
The types, the default and the code in general support an empty object for this config setting.
So it makes sense to avoid erroring when validating the config.
Fixes #0000
---
- Tests
> fix: relax validation of unsafe configuration to allow an empty object

- packages/wrangler/src/versions/upload.ts
fixup a stray await that was missed after making sendMetricsEvent sync
---
- Tests
> fix: remove an unnecessary await for metrics.sendMetricsEvent

- .changeset/thick-nails-switch.md
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/list.ts
- packages/wrangler/src/versions/upload.ts
- packages/wrangler/src/versions/view.ts
`wrangler versions` commands have been GA since Birthday Week—this PR is a minimal change to mark them as stable.
---
- Tests
> Mark `wrangler versions` as stable

- .changeset/lovely-kiwis-grab.md
- packages/create-cloudflare/templates/svelte/c3.ts
One issue that I had creating a Sveltekit project using create-cloudflare was the fact that the playwright configuration file still had its port set to the default of 4173, which would cause the test to hang. I could either change the `webServer.command` property to override the default port that miniflare uses or to change the port to 8788 (which is what I chose).
- Tests
> Changed port in playwright config file

- .changeset/smart-plants-wash.md
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/assets.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/versions/upload.ts
Fixes WC-2971.
Allows Workers for Platforms scripts to bring along static assets.
---
- Tests
> WfP Assets support

- packages/wrangler/src/__tests__/api/startDevWorker/BundleController.test.ts
This test keeps timing out in CI, which is just infuriating. So hopefully doubling the timeout will make it better.
E.g. https://github.com/cloudflare/workers-sdk/actions/runs/12191905934/job/34011610082?pr=7439#step:5:968
> ci: extend the timeout on BundleController.test.ts "custom build" test to reduce CI flakiness

- packages/wrangler/src/api/pages/deploy.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/pages/build-env.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/deploy.ts
- packages/wrangler/src/pages/secret/index.ts
Fixes #000.
The `readConfig` function currently does too much:
- it needs to know about pages config quirks
- it needs to know how to modify config to get python scripts to work
Added to that, the `readConfig` function currently takes a `requirePagesConfig` flag, but actually does more than just checking for its existence - it also does pages-specific normalisation and validation, and changes the behaviour of errors and logs within the function.
This refactor splits up `readConfig` into `readConfig` + `readPagesConfig`.
The goal is to simplify the top level function and make it easier to read and modify in the future.
- Tests
> chore: split readConfig and readPages config to simplify and lower responsibilities

- .changeset/funny-impalas-run.md
- packages/workers-shared/router-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/index.ts
Provides analytic usage for invoke_user_worker_ahead_of_assets
- Tests
> Instrument analytics for invoke_user_worker_ahead_of_assets

- .changeset/funny-pets-punch.md
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/src/__tests__/kv.local.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/r2.local.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/kv/index.ts
- packages/wrangler/src/r2/object.ts
Change `wrangler r2` & `wrangler kv` to use `--local` by default, with the old behaviour available with `--remote`
---
- Tests
> `--local` by default for `wrangler kv` & `wrangler r2`

- .changeset/thirty-turkeys-turn.md
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates-experimental/vue/c3.ts
- packages/create-cloudflare/templates-experimental/vue/templates/wrangler.toml
Fixes #0000
Adds experimental C3 template for Vue (frontend only) framework and updates it to use Workers Assets.
Also moves Vue out of quarantine.
---
- Tests
> update Vue C3 experimental template to work with Worker Assets

- .changeset/angry-apricots-swim.md
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/helpers/mock-console.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
- packages/wrangler/src/cloudchamber/client/models/ModifyApplicationRequestBody.ts
- packages/wrangler/src/cloudchamber/helpers/diff.ts
- packages/wrangler/src/cloudchamber/index.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
container app changes
This command is able to take the [[container-app]] configurations, and deploy them to Cloudchamber.
To render the differences, we are introducing a new dependency with "diff". This was already included in the pnpm lock, however we could consider not rolling out a new dependency into wrangler unless absolutely necessary.
The command is designed to be CI friendly. In the tests there is some example command renders from different kind of configurations.
---
- Tests
> cloudchamber: Start `cloudchamber apply`, the new command to deploy

- .changeset/five-dryers-swim.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/r2/cors.ts
- packages/wrangler/src/r2/helpers.ts
Add r2 bucket cors command (list, set, delete)
---
- Tests
> Add r2 bucket cors command (list, set, delete)

- packages/create-cloudflare/src/wrangler/__tests__/config.test.ts
Currently the assertions in create-cloudflare's `updateWranglerToml` unit tests check for the presence of very specific strings in the output (eg. `expect(newToml).toMatch(`name = "${ctx.project.name}"`)`), but not the output's shape overall. Unfortunately, this has resulted in us not detecting a bug where the updated toml does not contain new lines between the prepended configuration lines
(eg. `name = "test"compatibility_date = "2024-01-17"`).
This PR changes those assertions to test against the output's overall shape. The broken output is fixed by https://github.com/cloudflare/workers-sdk/pull/7457
Fixes #000.
---
- Tests
> chore(create-cloudflare): Make assertions in config tests more exhaustive

- .changeset/large-mails-relax.md
- packages/create-cloudflare/src/wrangler/__tests__/config.test.ts
- packages/create-cloudflare/src/wrangler/config.ts
This PR adds a newline character to the line prepended to wrangler.toml (when `name` or `compatibility_date` is missing in the template).
Without this change, the prepended line would cause a syntax error.
example:
original wrangler.toml (in template)
```toml
main = "index.js"
```
prepended wrangler.toml
```toml
name = "foo"compatibility_date = "2024-11-06"main = "index.js"
```
after this PR:
```toml
name = "foo"
compatibility_date = "2024-11-06"
main = "index.js"
```
---
- Tests
> fix(create-cloudflare): add a newline character to the line prepended to wrangler.toml

- .changeset/smooth-vans-share.md
- packages/create-cloudflare/src/__tests__/dialog.test.ts
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/dialog.ts
This is just to fix that usually bothers me, when I run C3 in experimental mode there is no indication wether it is running or not in such mode, having this confirmation seems quite nice to me since, besides the final output, there is no way for me to double check/confirm that I didn't I mess up (like a simple typo etc..) inputting the `--experimental` flag
Result:
---
- Tests
> feat: notify users when they are running C3 in experimental mode

- .changeset/lovely-fireants-roll.md
- fixtures/import-npm/package-lock.json
- fixtures/workflow/tests/index.test.ts
- packages/workflows-shared/src/engine.ts
Fixes WOR-440.
Fixed a bug in local development where fetching a Workflow instance by ID would return a Workflow status, even if that instance did not exist. This only impacted the `get()` method on the Worker bindings. 
---
- Tests
> Workflows: fix getting a workflow when such workflow was not yet created

- .changeset/happy-ears-cough.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/r2/domain.ts
- packages/wrangler/src/r2/helpers.ts
Add r2 bucket domain get command
---
- Tests
> Add r2 bucket domain get command

- .changeset/khaki-steaks-sniff.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
Fixes #0000
It is an error for the the user to provide an environment name that doesn't match any of the named environments in the Wrangler configuration. But if there are no named environments defined at all in the Wrangler configuration, we special case the top-level environment as though it was a named environment. Previously, when this happens, we would remove all the nonInheritable fields from the configuration (essentially all the bindings) leaving an incorrect configuration. Now we correctly generate a flattened named environment that has the nonInheritable fields, plus correctly applies any transformFn on inheritable fields.
---
- Tests
> fix: ensure that non-inherited fields are not removed when using an inferred named environment

- packages/miniflare/test/index.spec.ts
This test seems to fail on developer machines locally.
Possibly because our WARP setup requires self-signed root CA certificates?
The tests will still run in GitHub so we do not lose test safety. Just the small chance that failures only get picked up at CI test time and not when in development.
> ci: skip Miniflare browser CA certificate tests during local testing

- .changeset/shy-waves-prove.md
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/src/frameworks/index.ts
- packages/create-cloudflare/src/frameworks/package.json
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates-experimental/next/c3.ts
- packages/create-cloudflare/templates/next/README.md
- packages/create-cloudflare/templates/next/app/js/app/api/hello/route.js
- packages/create-cloudflare/templates/next/app/ts/app/api/hello/route.ts
- packages/create-cloudflare/templates/next/c3.ts
This PR is for updating C3 to create a Next.js 15 app in non-experimental mode
However (see comments below) the bump of create-next-app for non-experimental mode currently applies to both the non-experimental and experimental Next.js templates, forcing us to either make sure that both templates can work with Next.js 15 or that we find a way to have each use a different version of create-next-app
---
- Tests
> bump C3's create-next-app to 15.0.3

- .changeset/nervous-jeans-obey.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev.ts
Fixes [SQC-349](https://jira.cfdata.org/browse/SQC-349).
This is a small fix that addresses an issue customers have been facing, when trying to use `wrangler dev --remote` we are throwing errors because the local connection string is not set in the Wrangler file or the environment, when it shouldn't be necessary.
---
- Tests
> Don't require Hyperdrive local connection string when using wrangler dev --remote

- .changeset/swift-bulldogs-repeat.md
- packages/wrangler/e2e/helpers/normalize.ts
- packages/wrangler/e2e/provision.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-kv.ts
- packages/wrangler/src/__tests__/provision.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/d1/create.ts
- packages/wrangler/src/d1/list.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/bindings.ts
- packages/wrangler/src/kv/helpers.ts
Fixes [DEVX-1421](https://jira.cfdata.org/browse/DEVX-1421) and [DEVX-1420](https://jira.cfdata.org/browse/DEVX-1420)
This PR adds the ability to identify draft and inherit bindings by looking up the current binding settings.
---
- Tests
> feat(wrangler): identify draft and inherit bindings and provision draft ones

- .changeset/clean-peas-exist.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/pipelines/client.ts
- packages/wrangler/src/pipelines/index.ts
Fixes https://jira.cfdata.org/browse/PIPE-155
Adds filename prefix options to Pipelines
---
- Tests
> PIPE-155 Add pipelines prefix option

- packages/wrangler/src/cloudchamber/cli/deployments.ts
- packages/wrangler/src/cloudchamber/cli/index.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/cloudchamber/create.ts
We currently only print the full deployment ID when the deployment has an IPv4 address. This commit makes the deployment ID always print, as well as the placement ID. We also move the printing of the IPv4 address (if one exists) to the same place as the IPv6 address so that they are printed together.
There are a few other nit-picky changes as well. I've tried to make capitalization of labels more consistent (there doesn't appear to be a rule on when someone should be capitalized and when it shouldn't be, but I've at least made it more consistent within the subcommands themselves). I also changed the green "SUCCESS" message to only print once at the very end of the `cloudchamber create` command. This is consistent with the flow for creating a Worker.
---
- Tests
- E2E Tests CI Job …
> cloudchamber/create: always print deployment and placement ID

- .changeset/fluffy-rules-listen.md
Fixes #000.
add changeset for Cloudchamber changes introduced in https://github.com/cloudflare/workers-sdk/pull/7523
---
- Tests
> fix: add changeset for Cloudchamber changes

- .changeset/nervous-jeans-obey.md
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/dev.ts
Reverts cloudflare/workers-sdk#7485
Reverting this because the added e2e test fails. It is unclear to me at this moment why the e2es didn't fail on the original PR. The e2e label was correctly added but it seems that the e2es didn't run at all? I will have to investigate that.
The reason the e2e test is failing is because that hyperdrive remote resource does not exist, which is mandatory when running `wrangler dev --remote`.
I attempted to [fix forward](https://github.com/cloudflare/workers-sdk/pull/7536), but turns out that `wrangler hyperdrive create` requires us to specify a DB to connect to, and this cannot be a local db (see this err message 👉 `The database hostname or IP provided is not a publicly resolvable address. Only publicly routable addresses are currently supported.`). I …
> Revert "Don't require Hyperdrive local connection string when using wrangler dev --remote"

- .vscode/launch.json
- packages/cloudflare-workers-bindings-extension/package.json
- packages/cloudflare-workers-bindings-extension/src/extension.ts
Make sure the extension is:
- rendered in the sidebar
- has a debugging task
- has a test command to run via the command palette ("Test Command")
> Add test command for the extension

- packages/wrangler/src/__tests__/versions/deployments/deployments.list.test.ts
- packages/wrangler/src/__tests__/versions/deployments/deployments.status.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/versions/deployments/index.ts
- packages/wrangler/src/versions/deployments/list.ts
- packages/wrangler/src/versions/deployments/status.ts
- packages/wrangler/src/versions/deployments/view.ts
Fixes #000.
Converts `deployments` to `createCommand`.
- Tests
> chore: convert deployments to createCommand

- .changeset/stale-bananas-sort.md
- packages/create-cloudflare/templates-experimental/astro/templates/ts/wrangler.toml
This PR simply removes the extra `_v2` that is not really needed in the Astro C3 experimental template
---
- Tests
> update the astro experimental template not to unnecessarily specify `v2` for `nodejs_compat`

- .changeset/wise-pens-walk.md
- packages/wrangler/src/__tests__/kv.local.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/kv/index.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/2620
This is a non-breaking fix for #2620 that modifies `wrangler kv bulk delete` to additionally accept the output format from `wrangler kv key list`. The (breaking) proposed solution in the issue of modifying `wrangler kv key list` to output an array of strings turned out not to be viable because of the additional metadata added to the output in that command: `expiration` & `metadata`.
---
- Tests
> Accept `{ name: string }[]` in kv bulk delete

- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/versions/rollback/index.ts
Fixes #000.
Converts `rollback` to `createCommand`
- Tests
> chore: convert rollback to createCommand

- .changeset/strange-tips-lick.md
- packages/wrangler/e2e/__snapshots__/dev.test.ts.snap
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
- packages/wrangler/src/dev/create-worker-preview.ts
- packages/wrangler/src/dev/remote.ts
Fixes DEVX-1522
This PR adds remote mode support in `wrangler dev` for Workers + Assets. 
The current implementation will always upload assets to the edge, before deploying the User Worker to Edge Preview (which is what `wrangler dev --remote` already does). This means that for Workers + Assets, the User Worker, Router Worker, Asset Workers, the assets and any other resources all run at the edge (see diagram below).
---
Screenshots
- Worker + Assets only
- Worker + Assets
---
- Tests
> feat(wrangler): Add remote mode support for Workers + Assets

- .changeset/early-baboons-fly.md
- packages/workers-shared/asset-worker/tests/handler.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/triggers/deploy.ts
Fixes [WC-2972](https://jira.cfdata.org/browse/WC-2972).
Allow Workers Assets to be mounted to a wildcard path. We are still limiting unwildcarded paths like `example.com/test` for the minute though.
We will log a warning saying that we will attempt to serve assets along with the asset dir being matched. Also with a note saying unmatched will go to the Worker
Wording TBD here.
---
- Tests
> WC-2972: Allow Workers Assets to be mounted to a path

- packages/wrangler/e2e/dev.test.ts
This commit fixed some e2e tests that started failing after https://github.com/cloudflare/workers-sdk/pull/7476
Fixes #000.
---
- Tests
> chore(wrangler): Fix failing e2e tests

- .changeset/swift-zebras-guess.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/assets.ts
Fixes #0000
Gives guidance on usage of serve_directly in the following cases:
- (Warning) User worker runs first but no assets binding
- (Error) User worker runs first but no user worker provided
- Tests
> Provide validation around experimental_serve_directly usage

- .changeset/lovely-rats-live.md
- packages/wrangler/src/__tests__/configuration.test.ts
- packages/wrangler/src/__tests__/patch-config.test.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/config/config-helpers.ts
- packages/wrangler/src/config/patch-config.ts
> feat: add experimental_patchConfig

- .changeset/quick-wombats-battle.md
- packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
Fixes DEVX-1523
Workers + Assets projects have, in certain situations, a relatively degraded `wrangler dev --remote` developer experience, as opposed to Workers proper projects. This is due to the fact that, for Workers + Assets, we need to make 
extra API calls to:
1. check for asset files changes
2. upload the changed assets, if any
This commit improves the `wrangler dev --remote` DX for Workers + Assets, for use cases when the User Worker/assets change while the API calls for previous changes are still in flight. For such use cases, we have put an exit early strategy in place, that drops the event handler execution of the previous changes, in favour of the handler triggered by the 
new changes.
For `before`/`after` screenshots pls see DEVX-1523 
**How these changes were tested** …
> feat(wrangler): DX optimisations in `wrangler dev --remote`

- .changeset/fuzzy-nails-invent.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/asset-server/handler.ts
Fixes #000
Before fetching the asset, the client may already have the asset contents cached. Let's check `If-None-Match` first.
---
- Tests
> Check If-None-Match before fulfilling preservation cache

- .changeset/tidy-kiwis-arrive.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/assets.ts
Fixes #0000
Provides a warning if using smart placement. Internal discussions still ongoing on whether to hard block on this instead of warn.
- Tests
> Add warning for smart placement w/assets

- .changeset/sharp-crabs-beg.md
The Router Worker and Asset Worker of `workers-shared` are currently in a weird state that prevents us to redeploy them. The current versions of these workers are developer modified due to adding secrets. We want a CI controlled version to safely use these secrets.
This PR performs a dummy `workers-shared` version bump to unlock us from this blocked state.
Fixes #000
---
- Tests
> chore(workers-shared): Dummy `workers-shared` version bump

- .changeset/tender-cats-hammer.md
- packages/cloudflare-workers-bindings-extension/src/add-binding.ts
- packages/cloudflare-workers-bindings-extension/src/show-bindings.ts
validates that binding names are unique and not empty
fixes [DEVX-1547](https://jira.cfdata.org/browse/DEVX-1547)
---
- Tests
> feat: add validation to binding name input in vscode extension 

- .changeset/long-houses-mate.md
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/metrics/metrics-config.ts
- packages/wrangler/src/metrics/metrics-dispatcher.ts
- packages/wrangler/src/metrics/types.ts
Fixes DEVX-1525
During many Workers+Assets conversations, folks have mentioned that we expect usage for assets in remote mode to be fairly small. We should measure accurately what this number is, as it will be a very helpful data point down the road, when more decisions around remote mode will have to be taken.
This PR adds this kind of insight to our telemetry data, by capturing whether the command running is in the context of a Workers + Assets project. 
N.B. With these changes in place we will be capturing the Workers + Assets context for all commands, not just `wrangler dev --remote`.
---
- Tests
> feat(wrangler): Capture Workers with static assets in the telemetry data

- .changeset/chilled-mugs-fail.md
- fixtures/nodejs-hybrid-app/src/index.ts
- fixtures/nodejs-hybrid-app/src/unenv-preset.ts
- fixtures/nodejs-hybrid-app/tests/index.test.ts
- packages/unenv-preset/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
Add tests for the unenv preset
We will need to mobve those tests to the package, see https://github.com/cloudflare/workers-sdk/issues/7579
dns is expected to fail before we upgrade to workerd 20241216
- https://github.com/cloudflare/workers-sdk/pull/7562
- https://github.com/cloudflare/workers-sdk/pull/7566
The second commit speed-up the tests by launching wrangler only once for all the tests. 
/cc @pi0 
edit: this PR does not change the resolution mechanism (which is what broke the wrangler a few days ago).
---
- Tests
> Update unenv preset

- packages/create-cloudflare/templates-experimental/next/c3.ts
The template matches the 0.2.x release 
It will be updated later for 0.3
---
- Tests
> chore: pin `@opennextjs/cloudflare` to 0.2.x

- .github/actions/install-dependencies/action.yml
Fixes #7648
This updates the default node version to the latest patch version of node 18, which is required by our Nuxt c3 tests.
---
- Tests
> chore: update workflow default node version

- .changeset/empty-cars-provide.md
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
Fixes #7611
This more gracefully handles malformed URLs and simply throws a 404 on them instead of the entire Worker throwing an exception.
---
- Tests
> fix: better handler malformed paths

- packages/create-cloudflare/src/helpers/compatDate.ts
Extremely minimal cleanup, just removing an unnecessary nullish coalescing operation noticed by @vicb ([comment](https://github.com/opennextjs/opennextjs-cloudflare/pull/220#discussion_r1900996091)) when I copied this code over to out open-next adapter.
---
- Tests
> cleanup unnecessary nullish coalescing operation

- packages/wrangler/src/api/startDevWorker/ConfigController.ts
An old warning about remote dev with assets snuck in via #7533  and broke e2e tests.
(#7533 didn't need an e2e run, so it wasn't caught there)
---
- Tests
> chore: fix broken e2e tests from merge error

- .changeset/moody-bikes-cross.md
- fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
- packages/vitest-pool-workers/src/worker/fetch-mock.ts
Fixes #7667
Support interception of URLs with repeated key/name in its query params. e.g., `/index.html?a=1&a=2`.
---
- Tests
> fix(vitest-pool-workers) Fix support for query params with repeated keys

- .changeset/chilled-needles-notice.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
Reapply of #7541
The initial PR was reverted by https://github.com/cloudflare/workers-sdk/pull/7583
The root caused was fixed in https://github.com/cloudflare/workers-sdk/pull/7614 (via https://github.com/unjs/unenv/pull/378)
/cc @pi0
---
- Tests
> feat(wrangler): use unenv bulitin dependency resolution

- .changeset/quick-years-run.md
- packages/create-cloudflare/templates-experimental/next/c3.ts
- packages/create-cloudflare/templates-experimental/solid/c3.ts
- packages/create-cloudflare/templates/next/c3.ts
- packages/create-cloudflare/templates/solid/c3.ts
Fixes #7662
Renames the `Solid` and `Next` entries to `SolidStart` and `Next.js` respectively (for clarity and consistency)
---
- Tests
> [C3] Consistently use full official full stack framework names

- fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
- packages/vitest-pool-workers/src/worker/fetch-mock.ts
Fixes n/a.
Tested a few more cases around different query interception as suggested by @Skye-31 on https://github.com/cloudflare/workers-sdk/pull/7668#issuecomment-2574070405
---
- Tests
> chore(vitest-pool-workers): test intercepting fetch with different query pattern

- tools/e2e/__tests__/common.test.ts
- tools/e2e/common.ts
- tools/e2e/e2eCleanup.ts
Fixes https://jira.cfdata.org/browse/DEVX-1537
---
- Tests
> chore: add d1 and kv to e2e cleanup job

- .github/version-script.js
readFileSync returns a `Buffer` if the encoding is not set.
---
- Tests
> refactor(CI): explicitly set encoding when reading package.json

- .changeset/calm-lizards-tell.md
- .changeset/healthy-bags-cry.md
- .changeset/polite-goats-behave.md
- fixtures/vitest-pool-workers-examples/basics-integration-auxiliary/wrangler.toml
- fixtures/vitest-pool-workers-examples/basics-unit-integration-self/wrangler.toml
- fixtures/vitest-pool-workers-examples/d1/wrangler.toml
- fixtures/vitest-pool-workers-examples/durable-objects/wrangler.toml
- fixtures/vitest-pool-workers-examples/external-package-resolution/wrangler.toml
- fixtures/vitest-pool-workers-examples/hyperdrive/wrangler.toml
- fixtures/vitest-pool-workers-examples/internal-module-resolution/wrangler.toml
- fixtures/vitest-pool-workers-examples/kv-r2-caches/wrangler.toml
- fixtures/vitest-pool-workers-examples/misc/wrangler.toml
- fixtures/vitest-pool-workers-examples/multiple-workers/api-service/wrangler.toml
- fixtures/vitest-pool-workers-examples/multiple-workers/auth-service/wrangler.toml
- fixtures/vitest-pool-workers-examples/multiple-workers/database-service/wrangler.toml
- fixtures/vitest-pool-workers-examples/pages-with-config/wrangler.toml
- fixtures/vitest-pool-workers-examples/queues/wrangler.toml
- fixtures/vitest-pool-workers-examples/request-mocking/wrangler.toml
- fixtures/vitest-pool-workers-examples/rpc/wrangler.toml
- fixtures/vitest-pool-workers-examples/web-assembly/wrangler.toml
- fixtures/vitest-pool-workers-examples/workers-assets-only/wrangler.toml
- fixtures/vitest-pool-workers-examples/workers-assets/wrangler.toml
- packages/create-cloudflare/templates/hello-world/js/wrangler.toml
- packages/create-cloudflare/templates/hello-world/ts/wrangler.toml
- packages/vitest-pool-workers/src/pool/index.ts
Fixes #000.
Removes the need to add `nodejs_compat` flag in C3 templates just to use Vitest Pool Workers. Vitest Pool Workers will now inject the flag if it doesn't exist.
- Tests
> Remove node_compat flag from C3 templates that use Vitest Pool Workers

- CONTRIBUTING.md
Fixes #000.
We sometimes get PRs from Cloudflare employees via a forked repo, which makes it difficult to contribute to that PR (we can't push directly to their fork like we can with PRs created from a branch on this repo). 
This PR clarifies the difference in the CONTRIBUTING.md guide to try to avoid the above situation.
- Tests
> docs: clarify difference between external contributors and Cloudflare employees

- .changeset/three-chefs-bathe.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/pipelines/client.ts
- packages/wrangler/src/pipelines/index.ts
Closes https://jira.cfdata.org/browse/PIPE-152
---
- Tests
> Remove defaults for `batch-max-*` pipeline parameters and define value ranges

- .changeset/green-dodos-push.md
- packages/miniflare/src/workers/d1/dumpSql.ts
Fixes #6452
The export logic was corrupting data when a binary value was being converted into HEX strings, and one of the bytes had a leading zero.
Also fixed in the internal version used in production (CFSQL-1166).
---
- Tests
> Fix D1 exports to properly pad HEX strings for binary values

- fixtures/pages-workerjs-with-config-file-app/tests/index.test.ts
Fixes a warning in CI logs.
The warning warns that this will not work with Vitest3
---
- Tests
> test: add missing await

- tools/e2e/__tests__/common.test.ts
- tools/e2e/common.ts
Increasing the max number of resources we could delete each time - I started off with about ~50 resources each run in case it took forever, but it hasn't broken and we have _so many_ d1 databases to delete.
---
- Tests
> chore: delete more orphaned e2e resources

- .changeset/red-lamps-obey.md
- packages/miniflare/src/http/server.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/workers/core/entry.worker.ts
- packages/miniflare/test/index.spec.ts
Fixes CUSTESC-46864, fixes https://github.com/cloudflare/workers-sdk/issues/7588
When deployed, Workers can access the IP of the client that initiated a request using the `CF-Connecting-IP` header. However, this wasn't available locally, and so there was previously no way to know the IP address of a connecting client from a `wrangler dev` session. 
As it turns out, `workerd` injects a `clientIp` (that appears to be of the form `{ip}:{port}`— @danlapid or @kentonv could you confirm the format here?) using the `request.cf` property. Previously, the `request.cf` injected by `workerd` wouldn't make it to a user worker, because Miniflare injects a more fleshed out `request.cf` value that reflects what would be seen in production. As such, this PR extracts the `clientIp` from `workerd`'s …
> Inject `CF-Connecting-IP` from workerd `clientIp`

- fixtures/nodejs-hybrid-app/src/index.ts
- fixtures/nodejs-hybrid-app/tests/index.test.ts
- packages/unenv-preset/package.json
- packages/unenv-preset/tests/index.test.ts
- packages/unenv-preset/tests/worker/index.ts
- packages/unenv-preset/tests/worker/wrangler.json
- pnpm-lock.yaml
Move the tests from nodejs-hybrid-app
The tests are executed with the dev version of `@cloudflare/unenv-preset` and the pkg local version of `workerd` (instead of the pinned versions that will be used by wrangler).
Note that currently wrangler still uses the cloudflare preset from `unjs/unenv` so that is what is tested for now. Once wrangler switches to using `@cloudflare/unenv-preset` the resolution override will be in effect (we are trying to resolve `$clouflare.ts` files that are not in `@cloudflare/unenv-preset`) 
Tests are disabled on Windows as `MINIFLARE_WORKERD_PATH` is [not supported](https://github.com/cloudflare/workers-sdk/blob/773bda8b38d43102c2a66126df92d3bbc7e80861/packages/miniflare/test/index.spec.ts#L2036).
/cc @pi0
---
- Tests
- E2E Tests CI Job required? (Use "e2e" …
> test(unenv-preset): move tests from nodejs-hybrid-app

- .changeset/honest-pillows-tease.md
- packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
Make sure we don't pass on the `CF-Connecting-IP` header to the remote edge preview instance. Without this line, remote previews will fail with `DNS points to prohibited IP`
---
- Tests
> Remove CF-Connecting-IP for requests to the edge preview

- package.json
- packages/miniflare/package.json
- packages/workers-shared/package.json
- packages/workflows-shared/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
Move rimraf to the default catalog.
Notes:
- Using v5 as v6 requires node 20 or >= 22
- `@types` are not needed (only ever executred from `package.json`)
- Ordered catalog alphabetically
---
- Tests
> chore: consolidate to a single rimraf version

- .github/prereleases/3-comment.mjs
Make it easier to find the artifact.
It can be hard to figure out the command without the name:
Compare with the comment on this PR
---
- Tests
> ci: add package name to the PR artifacts

- .changeset/shy-flies-float.md
- packages/unenv-preset/build.config.ts
- packages/unenv-preset/package.json
We do not need .cjs for the runtime files but `wrangler` requires the preset so we need to have a `dist/index.cjs`
---
- Tests
> chore(unenv-preset): Add .cjs output for the preset

- packages/wrangler/e2e/c3-integration.test.ts
Now that C3 generates wrangler.json files, we need to update the wranger <-> c3 integration tests
Fixes #0000
---
- Tests
> test: fix c3 integration test

- .changeset/polite-vans-refuse.md
- packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/js/package.json
- packages/create-cloudflare/templates-experimental/hello-world-durable-object-with-assets/ts/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/py/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
- packages/create-cloudflare/templates/common/js/package.json
- packages/create-cloudflare/templates/common/ts/package.json
- packages/create-cloudflare/templates/hello-world-durable-object/js/package.json
- packages/create-cloudflare/templates/hello-world-durable-object/ts/package.json
- packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/py/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
- packages/create-cloudflare/templates/openapi/ts/package.json
- packages/create-cloudflare/templates/pre-existing/js/package.json
- packages/create-cloudflare/templates/queues/js/package.json
- packages/create-cloudflare/templates/queues/ts/package.json
- packages/create-cloudflare/templates/scheduled/js/package.json
- packages/create-cloudflare/templates/scheduled/ts/package.json
We should probably automate this, but doing it manually for now since it's so behind. 
Fixes #0000
---
- Tests
> chore: update wrangler versions in templates

- .changeset/dull-coins-scream.md
- packages/edge-preview-authenticated-proxy/src/index.ts
- packages/edge-preview-authenticated-proxy/tests/index.test.ts
- packages/playground-preview-worker/src/index.ts
- packages/playground-preview-worker/tests/index.test.ts
Fixes [DEVX-1449](https://jira.cfdata.org/browse/DEVX-1449).
This is the first part of the fixes. It introduces the `X-CF-Http-Method` header that lets our proxy know which HTTP request method the users is sending. This will be utilized by the playground and quick editor in a separate PR to address an issue where OPTIONS raw http request is not handled properly. This change is backward compatible so it should be landed first before we update the implementation on the playground (#7639) and quick editor.
---
- Tests
>  fix(playground-preview-worker,edge-preview-authenticated-proxy): allow overriding raw request method with the X-CF-Http-Method header

- .changeset/dry-numbers-doubt.md
- packages/miniflare/src/plugins/core/index.ts
Use `text` bindings for text values when passing to Miniflare. This gives parity with deployed behaviour.
---
- Tests
> Use TEXT bindings for plain text values in Miniflare

- .changeset/tough-walls-poke.md
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/src/utils/mocks.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
- packages/workers-shared/utils/types.ts
This commit adds Jaeger tracing to asset-worker, in order for us to be able to have better insight into failures from KV.
---
- Tests
> Add jaeger bindings to asset-worker

- .changeset/fifty-flies-visit.md
- package.json
- packages/unenv-preset/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
- Update unenv in wrangler.
- Update the deps of `@cloudflare/unenv-preset` in the same way as in `unjs/unenv`
There are no functionality changes in unen since the last version. Only differencences are deps bump and a TypesScript type fix.
Syncing before we switch to using `@cloudflare/unenv-preset`
---
- Tests
> chore: update unenv depency version

- .changeset/lovely-years-wash.md
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/src/utils/kv.ts
- packages/workers-shared/asset-worker/tests/kv.test.ts
Fixes N/A
On a 404 from KV, we do not want the asset to stay in cache for the normal 1 year TTL. Instead we want to re-insert with a 30s TTL to revalidate and prevent a bad 404 from persisting.
---
- Tests
> On KV 404, re-insert with 60s TTL to avoid long 404 cache HITs

- .changeset/smart-lions-suffer.md
- packages/wrangler/src/__tests__/provision.test.ts
- packages/wrangler/src/d1/list.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/bindings.ts
> feat: pull resource names for provisioning from config if provided 

- .changeset/honest-spies-prove.md
- packages/wrangler/src/index.ts
This should make Sentry errors more actionable, by unwrapping error `cause` (which was causing all the `captureGlobalException` issues)
---
- Tests
> Unwrap SDW errors before sending to Sentry

- .changeset/proud-forks-build.md
- .changeset/unlucky-timers-sort.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation/index.ts
Fixes #5082
This PR does two things:
- one is widening the `vars` types that `wrangler types` generates when the same variables are defined in different environments (basically instead of incorrectly generate something like `MY_VAR: "dev value";` now we could correctly generate `MY_VAR: "dev value" | "prod value";` etc...)
- two is adding a new option (currently called `--strict-vars`) that allows the generated types not to be literals/unions but to be loose/generic ones (e.g. instead of `MY_VAR: "dev value" | "prod value";` it allows the generation of `MY_VAR: string;`), this was added after various feedback and back and forth from the team (the concern being that literal values/unions can be annoying for people if they change their var values often)
For more details please check the …
> widen multi-env `vars` types in `wrangler types` and add `--strict-vars` option to the command

- .changeset/cuddly-pets-smell.md
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- pnpm-lock.yaml
The cloudflare preset was migrated to this mono-repo (`@cloudflare/unenv-preset`)
This PR is switching to using this version
To do before merging:
/cc @petebacondarwin @pi0 @dario-piotrowicz 
---
- Tests
> chore(wrangler): use the unenv preset from `@cloudflare/unenv-preset`

- .changeset/odd-news-invent.md
- packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Fixes [DEVX-1449](https://jira.cfdata.org/browse/DEVX-1449).
This PR utilizes the `X-CF-HTTP-Method` header introduced on #7630 and is **blocked** until the relevant change is released.
You can verify this change on the [preview environment](https://d42f344a.workers-playground.pages.dev/playground) following these steps:
1. Create a worker in the playground with the following code (Or use this [link](https://d42f344a.workers-playground.pages.dev/playground#LYVwNgLglgDghgJwgegGYHsHALQBM4RwDcABAEbogB2+CAngLzbPYDqApmQNJQQBimYACFKNRHQDCVAHLppARQBaqEKy5UAqgEYAXgHkAXCxYduvAVhHVakmXKUq1m3XoCwAKAnoqEdj+wAIlAAzjDowbxQ3gYkGFh4BMQkVHDA7AwARPiEAHQAVsEZpKhQYH6p6VmJ+YUeXj5+ENgAKnQw7DFwMDBgUADGBFFUyHlwAG5wwX0IsBAA1MDouODsHh7sAB5hSCS47Khw4BAkAN7uAJApaTEZAKIbqT3sJACCAAoAkhkANBeEAObBGIAbQym0eZR+JAyXSgUIyCHY …
> fix(workers-playground): sends raw request method through the `X-CF-HTTP-Method` header

- .changeset/heavy-gorillas-punch.md
- packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Reverts cloudflare/workers-sdk#7639
Seems like our prev release of the workers-playground broke things. We are seeing a spike of related errors. We are therefore reverting to undo the breakage, and will handle fixing forward later on
> Revert "fix(workers-playground): sends raw request method through the `X-CF-HTTP-Method` header"

- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/hybrid-nodejs-compat.ts
- pnpm-lock.yaml
Reverts cloudflare/workers-sdk#7720 as it introduced breakage in some of the C3 templates (eg. Nuxt)
**How was this tested**
- create a Nuxt project via `npm create cloudflare@latest` (`2.36.0` at the time of this writing)
- change the wrangler version in the generated project's `package.json` to the wrangler pre-release version of this PR
- `npm i` again
- `npm run preview` - which previously failed
- 🎉  👇 
**Why was this not caught by our C3 e2e tests?**
When our C3 e2e tests run, they (in a nutshell) build C3 out of the `main` branch, and create a starter project (via that previously built executable) for each framework under test. Once the starter project is created, certain assertions are made on it.
A starter project will come with a list of predefined dependencies, necessary for …
> Revert "chore(wrangler): use the unenv preset from `@cloudflare/unenv-preset`"

- .changeset/heavy-parents-switch.md
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/wrangler.toml
Fixes N/A
Fix analytics not being logged for `asset-worker` in the case of a successful request.
---
- Tests
> Fix asset-worker not logging analytics for successful requests

- .changeset/red-comics-sit.md
- packages/unenv-preset/package.json
- packages/unenv-preset/tests/worker/index.ts
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/deploy.test.ts
- pnpm-lock.yaml
unenv@2.0.0-rc.0 is out 🎉
Thanks @pi0
There are only a few changes from the latest `unenv-nightly` and 2 of them are for the `node:timer` module and required to be able to use `mysql` on `workerd`.
One more [change](https://github.com/unjs/unenv/pull/381) in unenv implements stdout, stderr and stdin with node:tty. It explains the added deps in tests.
For now `unenv-preset` pins `unenv` to `2.0.0-rc.0`, later we will switch to "2.x" but we expect backward incompatible changes in the next RCs (thanks Pooya for catching that)
/cc @anonrig
---
- Tests
> chore: update unenv to 2.0.0-rc.0

- .changeset/dry-snakes-deliver.md
- packages/wrangler/src/__tests__/config/configSchema.test.ts
- packages/wrangler/src/config/environment.ts
Fixes #7820
Prior to this PR, the default for i.e. `compatibility_flags` was ``"`[]`"`` while it should be `[]` only. It made the autocomplete of `wrangler.json` and `wrangler.toml` in VSCode wrong (tested with the "Even Better TOML" extension)
On top of removing the backquotes, the PR also remove some comments that were not meant to be displayed.
Note that the formatting of the default value, i.e. `{consumers:[],producers:[]}` does not use the usual formatting because it breaks VSCode syntax highlithing.
---
- Tests
> fix(wrangler): fix schema defaults

- packages/wrangler/src/index.ts
- packages/wrangler/src/tail/index.ts
refactors `wrangler tail` to use the createCommand interface
---
- Tests
> chore: refactor wrangler tail to use createCommand

- .changeset/thick-dots-sit.md
- fixtures/get-platform-proxy/public/test.txt
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/wrangler.toml
- packages/wrangler/src/api/integrations/platform/index.ts
Fixes #7812
this change makes sure that that `getPlatformProxy`, when the input configuration
file contains an assets field, correctly returns the appropriate asset binding proxy
---
- Tests
> add support for assets bindings to `getPlatformProxy`

- packages/wrangler/src/index.ts
- packages/wrangler/src/type-generation/index.ts
refactors `wrangler types` to use the createCommand interface
---
- Tests
> chore: refactor `wrangler types` to use createCommand

- .changeset/twenty-ears-rescue.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/pages/secret.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/user/user.ts
> fix(wrangler): improve multi account error message in non-interactive mode

- CONTRIBUTING.md
Fix invalid link in `CONTRIBUTING.md`
Fixes N/A
---
- Tests
> chore(CONTRIBUTING.md): fixed invalid link

- .changeset/gentle-sloths-eat.md
- packages/wrangler/e2e/multiworker-dev.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/pages/dev.ts
Fixes #5918
As of #7251, Wrangler has supported configuring multiple Workers to run in the same `workerd` instance (with service bindings between them) using multiple `-c` flags. However, this didn't work for Pages.
This PR adds support for Pages, using the same API as for regular Workers: `wrangler pages dev -c wrangler.toml ../other-worker/wrangler.toml`. However, a slight difference with Pages (compared to regular Workers) is that you can't customise the location of the Pages config file. As such, the first `-c` argument _must_ point to the config file for the Pages project, and _must_ be located in the project root. We could've omitted this entirely, but it felt like it would be more confusing to implicitly read a config file that wasn't mentioned—open to dissenting opinions here! …
> Support service bindings from Pages projects to workers in a single `workerd` instance

- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/parse.ts
- packages/wrangler/src/pipelines/index.ts
- packages/wrangler/src/utils/retry.ts
- packages/wrangler/src/versions/upload.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/7714
Previously, `retryOnError()` would retry any thrown errors. Now, it only retries retryable API failures (5xx responses) or `TypeError`s (usually a network disconnection). This doesn't change how Wrangler behaves, but it should remove the ~6s wait that 4xx errors previously had before displaying to the user on a `wrangler deploy`
---
- Tests
> Only retry API failures

- packages/vite-plugin-cloudflare/package.json
- packages/vite-plugin-cloudflare/playground/cloudflare-env/package.json
- packages/vite-plugin-cloudflare/playground/durable-objects/package.json
- packages/vite-plugin-cloudflare/playground/external-durable-objects/package.json
- packages/vite-plugin-cloudflare/playground/external-workflows/package.json
- packages/vite-plugin-cloudflare/playground/hot-channel/package.json
- packages/vite-plugin-cloudflare/playground/module-resolution/package.json
- packages/vite-plugin-cloudflare/playground/multi-worker/package.json
- packages/vite-plugin-cloudflare/playground/node-compat/package.json
- packages/vite-plugin-cloudflare/playground/react-spa/package.json
- packages/vite-plugin-cloudflare/playground/spa-with-api/package.json
- packages/vite-plugin-cloudflare/playground/static-mpa/package.json
- packages/vite-plugin-cloudflare/playground/virtual-modules/package.json
- packages/vite-plugin-cloudflare/playground/websockets/package.json
- packages/vite-plugin-cloudflare/playground/worker/package.json
- packages/vite-plugin-cloudflare/playground/workflows/package.json
- pnpm-lock.yaml
- pnpm-workspace.yaml
We only need the Wrangler peer dependency to be at least 3.101.0,
which is when we added support for the redirected config.
By using the peer dependency range version in the playgrounds, we ensure that
we are testing against what will be used in practice. It will also ensure that this
dependency gets bumped when needed, since the playgrounds might start to fail otherwise.
Fixes #000.
(No changeset required because this is covered by the current changeset for the first release of the plugin)
---
- Tests
> Relax the Wrangler peer dependency for the Vite plugin

- .changeset/green-mice-carry.md
- packages/wrangler/src/__tests__/config/findWranglerConfig.test.ts
- packages/wrangler/src/config/config-helpers.ts
Previously the messaging was rendered as a warning, which implied that the user had done something wrong. Now it is just a regular info message.
Fixes #0000
---
- Tests
> Relax the messaging when Wrangler uses redirected configuration

- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
Adds JSDoc to the `cloudflare` function export.
---
- Tests
> Add JSDoc to cloudflare function

- .prettierrc
- packages/vite-plugin-cloudflare/README.md
Fixes #000.
Two changes to the README:
- Fixes a broken link
- Uses the default prettier config for code examples
---
- Tests
> Vite plugin README updates

- .changeset/beige-lamps-leave.md
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/config/validation.ts
Durable Objects transfer migration validation was previously warning when transfer migrations were specified. 
- Tests
> Fix Durable Objects transfer migration validation

- .changeset/cuddly-radios-rule.md
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/js/test/index.spec.js
- packages/create-cloudflare/templates/hello-world/ts/package.json
> fix(create-cloudflare): bump vitest-pool-workers version on the templates

- packages/cloudflare-workers-bindings-extension/package.json
- packages/create-cloudflare/package.json
- packages/vite-plugin-cloudflare/package.json
It's quite minor but I noticed that almost all packages in the monorepo have a `dev` script for building the package in watch mode with a few exceptions, so for consistency sake I'd also use that script name there
Besides the above, this type of consistency can potentially help with the turborepo setup (e.g. I want to dev multiple packages at once)
<details>
currently if I run `pnpm dev` in the monorepo root I get the following error:
but you get the gist
</details>
---
- Tests
> change `watch` scripts to `dev` in packages for consistency

- .changeset/smart-mice-appear.md
- packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
- packages/vite-plugin-cloudflare/src/runner-worker/index.ts
Fixes https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/59
The plugin validation around the module runner initialization is not properly propagated, the changes here make sure
that it is and that a (hopefully) helpful error message is shown to the user
An easy way to see the different behavior here is to make the `createModuleRunner` function always throw:
and run a playground application, without the changes here it's not clear/surfaced that the runner failed initialization
---
- Tests
> [vite-plugin-cloudflare] make sure that runner initialization is properly validated

- .changeset/eighty-penguins-complain.md
- packages/workers-shared/asset-worker/src/analytics.ts
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/src/types.ts
- packages/workers-shared/router-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/index.ts
- packages/workers-shared/utils/sentry.ts
- packages/workers-shared/utils/types.ts
Fixes N/A
plumb through account ID and Worker ID into the asset-worker and router-worker for use in analytics and error reporting.
---
- Tests
> Plumb through account ID and Worker ID into asset-worker and router-worker

- packages/vite-plugin-cloudflare/package.json
- pnpm-lock.yaml
there is an upstream but in the `tsup` package: https://github.com/egoist/tsup/issues/1245 which prevents our `watch` script to detect file changes, the changes here fix such by pinning the dependency to `8.3.0`
---
- Tests
> [vite-plugin-cloudflare]: fix watch script not working

- .changeset/fifty-pots-nail.md
- packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
- packages/wrangler/src/tail/createTail.ts
- packages/wrangler/src/tail/printing.ts
Fix RPC method invocations showing up as unknown events. Users will now see the following in the case of either a `Service<MyWorkerEntrypoint>` or a DurableObjectNamespace<MyDurableObject>` when invoking either from a worker:
```
MyWorkerEntrypoint.add - Ok @ 1/17/2025, 4:14:15 PM
MyDurableObject.add - Ok @ 1/17/2025, 4:14:16 PM
```
- Tests
> Fix RPC method invocations showing up as unknown events

- .changeset/heavy-otters-cough.md
- packages/create-cloudflare/src/helpers/__tests__/compatDate.test.ts
- packages/create-cloudflare/src/helpers/compatDate.ts
Fixes an issue where deployments would fail when there is a workerd release on the same day due to workerd releases having a date in the future because Workers does not allow using a compat date in the future.
I found this really frustrating that C3 templates fail to deploy if there is a workerd release on the same day:
---
- Tests
> fix(C3): Use today's date for compat date when the latest workerd release date is in the future

- .changeset/clean-carrots-draw.md
- packages/wrangler/e2e/provision.test.ts
- packages/wrangler/src/__tests__/provision.test.ts
- packages/wrangler/src/deploy/index.ts
Make `--x-auto-create` default to `true`, so the flag doesn't need to be provided any more when using `--x-provision`. Interactivity can be restored by setting `--x-auto-create=false`
---
- Tests
> feat: make provisioning non-interactive by default

- fixtures/shared/src/run-wrangler-long-lived.ts
@petebacondarwin this is reverting [one change](https://github.com/cloudflare/workers-sdk/commit/e4716cc87893a0633bd2d00543b351e83e228970) you made a couple weeks ago.
I had CI (and local) that were impossible to debug without this.
I see that you mention that the logs would be printed on timeout anyway... but that's unless your test timeout is less than the timeout in `runLongLivedWrangler` - it is the case with the failures I had (30 vs 50s in updated file).
Adding `stderr` only should hopefully not be too spammy?
---
- Tests
> refactor(wrangler): runWranglerDev always log error

- packages/wrangler/src/deployment-bundle/bundle.ts
Minor change I figured out while exploring metafiles - my idea is to have an options to expose them so that users can get info about their bundle content.
The change:
Before this PR, we had:
```ts
const buildOptions: esbuild.BuildOptions & { metafile: true } = {
// ...
metafile: true,
// ...
};
let result: esbuild.BuildResult<typeof buildOptions>;
```
Because the type of result depends on `typeof buildOptions`, we had to add `& { metafile: true }` so that the metafile specific props are exposed on the result.
This PR switches to:
```ts
const buildOptions = {
// ...
metafile: true,
// ...
} satisfies esbuild.BuildOptions;
```
So that `typeof buildOptions` is not `esbuild.BuildOptions ` but it's actual type and then `metafile: true` is inferred from the actual value.
There are multiple …
> refactor(wrangler): refine the type of buildOptions

- .vscode/settings.json
Hopefully it's not too controversial, but having the `formatOnSave` option in the vscode settings could be rather convenient so that:
- it helps new contributors using vscode making sure that their formatting is correct (avoiding them getting formatting errors in their PRs and needing to go back and fix them)
- if I don't want to set the `formatOnSave` setting generally for my vscode (e.g. I can work with codebases without a formatter setup, etc...), it can still work for this monorepo without needing to switch back and forth between having it on and off
---
- Tests
> add `formatOnSave` option to vscode `settings.json`

- .changeset/nine-rocks-appear.md
- .changeset/popular-pigs-glow.md
- packages/unenv-preset/package.json
- packages/unenv-preset/src/preset.ts
- packages/unenv-preset/tests/worker/index.ts
- pnpm-lock.yaml
We currently implement node:timers and node:net in cloudflare workers. I've opened a similar PR to unenv as well: https://github.com/unjs/unenv/pull/396
---
- Tests
> add node:timers and node:net to unenv-preset

- packages/wrangler/src/__tests__/ai.test.ts
- packages/wrangler/src/__tests__/cert.test.ts
- packages/wrangler/src/__tests__/cloudchamber/create.test.ts
- packages/wrangler/src/__tests__/cloudchamber/curl.test.ts
- packages/wrangler/src/__tests__/cloudchamber/delete.test.ts
- packages/wrangler/src/__tests__/cloudchamber/images.test.ts
- packages/wrangler/src/__tests__/cloudchamber/list.test.ts
- packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
- packages/wrangler/src/__tests__/d1/d1.test.ts
- packages/wrangler/src/__tests__/deployments.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/docs.test.ts
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/__tests__/pubsub.test.ts
- packages/wrangler/src/__tests__/queues.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/__tests__/worker-namespace.test.ts
- packages/wrangler/src/__tests__/workflows.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/index.ts
`--env name` will first look for `.dev.vars.<name>`
---
- Tests
> refactor(wrangler): clarify the --env options

- .changeset/thick-bikes-teach.md
- packages/wrangler/src/__tests__/parse.test.ts
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/config/config-helpers.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/config/patch-config.ts
- packages/wrangler/src/dev/create-worker-preview.ts
- packages/wrangler/src/parse.ts
- packages/wrangler/src/r2/cors.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/type-generation/index.ts
This first started as a PR to relax a constraint on an exception message...
It turned out to be because Node throws different exceptions when `JSON.parse`ing across different version.
So let's use `jsonc-parser` instead that will be consistent across Node versions/runtimes.
One more change is that `parseJSON(c)` are no more parametrized. They returns `unknow` because that's the truth.
Callers can change that with an explicit cast.
(Any JSONC specifics are disabled when parsing JSON).
____
Initial description:
While the test passes on the CI, it fails locally for me:
```
wrangler:test:ci:  FAIL  src/__tests__/versions/secrets/bulk.test.ts > versions secret bulk > should error on invalid json file
wrangler:test:ci: AssertionError: expected [Function] to throw error including 'The contents …
```
> refactor(wrangler): make JSON parsing independent of Node

- .changeset/neat-needles-brush.md
- packages/wrangler/src/__tests__/utils/retry.test.ts
- packages/wrangler/src/pipelines/index.ts
- packages/wrangler/src/utils/retry.ts
Also fixes a regression in pipelines that prevented 401 errors from being retried when waiting for an API token to become active.
---
- Tests
> Fix regression in retryOnAPIFailure preventing any requests from being retried

- .changeset/old-bees-design.md
- packages/vite-plugin-cloudflare/src/index.ts
@jamesopstad this allows unsafe params to pass through the wrangler.json file while using vite as long as unsafe isn't set to an empty object. At least according to the comment, this was done for a reason to prevent empty objects from passing through, but seemed to do it unconditionally (even if not empty).
- Tests
> Allow unsafe param to pass through vite build

- .changeset/late-gorillas-walk.md
- packages/wrangler/src/__tests__/__snapshots__/r2.test.ts.snap
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/bucket.ts
- packages/wrangler/src/r2/helpers.ts
Fixes CUSTESC-48328
Fixes validation for R2 bucket names, the regex was wrongly rejecting buckets starting with a number and the message wasn't as clear as it could be on what was going wrong.
---
- Tests
> Fix R2 bucket name validation error

- packages/wrangler/src/deployment-bundle/bundle-reporter.ts
Minor update...
I found this while looking for something else in wrangler source code.
(And I always wondered by `Total Upload: 8916.85 KiB / gzip: 1645.88 KiB` was red when working on OpenNext)
---
- Tests
> refactor(wrangler): max bundle size is now 3MiB

- packages/create-cloudflare/package.json
- packages/wrangler/package.json
Fixes #0000
This is a simple change to the prepublish scripts for Wrangler and create-cloudflare to avoid building unnecessary packages when deploying.
---
- Tests
> chore: do not build the world when publishing Wrangler and C3

- .changeset/lucky-jeans-relax.md
- packages/wrangler/src/deployment-bundle/bundle.ts
Relates to #7886.
Before this PR:
- The first check `process.env.NODE_ENV` should have checked the runtime value (as done a few lines below)
- This check should only (de)activate `define["process.env.NODE_ENV"]` and not `define` as a whole.
This fix a few points from the linked issue, not all.
Notably there is still an issue when process is imported (`import process from "node:process";`) as "process" will be renamed by the hybrid plugin and not imported!
---
- Tests
> fix(wrangler): handling of `process.env.NODE_ENV` in bundling mode

- .github/workflows/validate-pr-description.yml
- tools/deployments/validate-pr-description.ts
Fixes #0000
Changes the PR description validation so that it only "fails" the CI check if the PR is "ready for review" (i.e. not in draft).
---
- Tests
> chore: don't fail the PR description check for draft PRs

- .github/workflows/test-and-check.yml
Previously we run packages and fixtures as different CI jobs. This meant that we were wasting on average 30s-1m30s building and setting up runners (in particular, `pnpm install` takes a long time even with a warm cache). 
This PR changes it to make packages and fixtures run in the same job, reducing wasted setup time.
---
- Tests
> Collapse CI jobs into one

- .changeset/silver-wombats-bow.md
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/README.md
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/public/binding.html
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/public/index.html
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/src/env.d.ts
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/src/index.ts
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/src/tsconfig.json
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/test/assets.test.ts
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/test/env.d.ts
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/test/tsconfig.json
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/tsconfig.json
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/vitest.config.ts
- fixtures/vitest-pool-workers-examples/workers-assets-run-worker-first/wrangler.toml
- packages/vitest-pool-workers/src/pool/config.ts
> fix: make sure asset routing config is passed to vitest 

- .changeset/gentle-foxes-float.md
- packages/wrangler/src/api/integrations/platform/index.ts
Fixes #7944
when `getPlatformProxy` is called and it retrieves values from `.dev.vars` files, it logs twice a message like: `Using vars defined in .dev.vars`, the changes here make sure that in such cases this log only appears once
(Prerequisite for fixing https://github.com/opennextjs/opennextjs-cloudflare/issues/288)
---
- Tests
> [wrangler] fix: avoid `getPlatformProxy` logging twice that it is using vars defined in `.dev.vars` files

- .github/actions/run-c3-e2e/action.yml
In the `run-c3-e2e` GH Action we compute various things from the inputs. In particular using `experimental` and `quarantine`.
But it seems that these are converted to strings rather than booleans, so we cannot simple check the truthy state of `inputs.quarantine`, for example since this might have the value `"false"`, which is truthy.
> CI: compute the name for artifacts correctly

- .changeset/cyan-suits-move.md
- packages/create-cloudflare/templates-experimental/next/c3.ts
> update experimental Next.js template to work on `@opennextjs/cloudflare@0.4.x`

- .changeset/beige-chicken-sort.md
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/package.json
- packages/wrangler/scripts/deps.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/api/startDevWorker/utils.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/bindings.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/images/fetcher.ts
- packages/wrangler/src/images/local.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/utils/print-bindings.ts
- pnpm-lock.yaml
Fixes #7882.
This was previously merged in #7424 but have to be reverted in #7882 because of missing permission running the e2e tests. This is now resolved and is confirmed on https://github.com/cloudflare/workers-sdk/pull/7958.
```
* Add Images binding
* Add Images remote preview mode
* Plumb images local mode flag through
* Add Images binding local mode
* Add Images E2E test
* Hoist @img packages
This fixes the fixture tests, perhaps because sharp does something unusual with imports, see GH comment: https://github.com/nuxt/image/issues/1210#issuecomment-1904087632
* Add local suffix when printing bindings
* Swap describe/it in E2E test
* Mark sharp as unbundled, rather than hoisting
* Remove zod
* Improve error messages
```
---
- Tests
- E2E Tests CI Job required? (Use "e2e" label or …
> Add support for Images binding

- .changeset/beige-chicken-sort.md
Fixes #7945.
This should be a patch since the image binding is still in private beta.
---
- Tests
> chore: mark changeset as patch

- .changeset/fair-waves-punch.md
- packages/create-cloudflare/src/frameworks/package.json
- pnpm-lock.yaml
Fixes https://github.com/cloudflare/workers-sdk/issues/7905
`create-hono` has now been updated to generate `wrangler.json` instead of `wrangler.toml`. Because `create-hono` points to `main` on the starter instead of a specific version, we need to bump it to ensure the two are in-sync.
- Tests
> Bumps create-hono now that upstream has updated to use wrangler.json

- .changeset/lucky-jeans-relax.md
- packages/wrangler/src/deployment-bundle/bundle.ts
Reverts cloudflare/workers-sdk#7932.
> Revert "fix(wrangler): handling of `process.env.NODE_ENV` in bundling mode"

- .github/workflows/workers-shared-deploy-production.yml
Creates internal workflow to allow us to upload new versions of router-worker and asset-worker without an explicit wrangler release.
- Tests
> Add workflow for uploading asset-worker and router-worker

- .changeset/odd-cougars-matter.md
- packages/workers-playground/src/QuickEditor/HTTPTab/fetchWorker.ts
Fixes #7791.
This PR un-reverts #7791 which was made because of a bug upstream and is now fixed in #7793. ~~We should verify it on the preview playground before merging this PR.~~ I have tested this on the preview environment as described on [this comment](https://github.com/cloudflare/workers-sdk/pull/7936#issuecomment-2622163606).
---
- Tests
> fix(workers-playground): send raw request method through the `X-CF-HTTP-Method` header

- .changeset/long-bulldogs-clean.md
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/config/validation.ts
Fixes N/A
Fixes a regression introduced in Wrangler 3.107.0 in which `[assets]` was not being inherited from the top-level environment.
---
- Tests
> Fix assets inheritance

- .changeset/cuddly-bees-allow.md
- packages/workers-shared/asset-worker/src/utils/kv.ts
We're not logging enough information in the error message we're sending to sentry, to understand why the KV get failed. This commit adds the error message.
- Tests
> Add additional error messaging for errors from KV

- .npmrc
Fixes #0000
This change is useful because it means that you don't have to automatically update your pnpm version as you move from one project to another. This is similar to our Volta configuration.
---
- Tests
> chore: configure pnpm to use the version specified in package.json engines field

- .changeset/early-grapes-care.md
- packages/wrangler/src/__tests__/cloudchamber/build.test.ts
- packages/wrangler/src/cloudchamber/build.ts
- packages/wrangler/src/cloudchamber/index.ts
Add build and push subcommands to cloudchamber that build a docker image and push to the cloudchamber managed registry using a local docker daemon.
---
- Tests
- [] TODO (before merge)
- [] I don't know
> Add build and push subcommands to cloudchamber

- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
Hopefully this will help with debugging C3 e2e tests without having to download the log artifact files.
See https://github.com/cloudflare/workers-sdk/actions/runs/13073993617/job/36481629597?pr=7982#step:5:394
Fixes #0000
---
- Tests
> test: log the C3 e2e log file to the console when a test fails

- .github/workflows/workers-shared-deploy-production.yml
Fixes broken workflow using pnpm deploy instead of pnpm run deploy.
- Tests
> Fix Workers Shared Production deploy workflow

- .vscode/settings.json
- packages/create-cloudflare/e2e-tests/global-setup.ts
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
- packages/create-cloudflare/package.json
- packages/create-cloudflare/turbo.json
- packages/create-cloudflare/vitest-e2e.config.mts
- packages/eslint-config-worker/index.js
- packages/mock-npm-registry/.eslintrc.cjs
- packages/mock-npm-registry/README.md
- packages/mock-npm-registry/package.json
- packages/mock-npm-registry/src/index.ts
- packages/mock-npm-registry/tsconfig.json
- packages/mock-npm-registry/turbo.json
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/test/README.md
- packages/vitest-pool-workers/test/global-setup.ts
- packages/wrangler/package.json
- packages/wrangler/src/__tests__/helpers/run-in-tmp.ts
- pnpm-lock.yaml
- turbo.json
Fixes #7800
This changes how e2e tests (C3 and vitest-pool-workers) make use of local packages.
**Reviewers: it is easier to follow along if you review commit by commit.**
This is achieved by spinning up a local mock npm registry in front of the public npm registry.
Then when you run `pnpm publish` or `pnpm i` it tries to use this local mock registry first.
This makes it easier to test the local versions of these packages, without having to manually set things up, which is error prone and fragile.
---
- Tests
> Implement verdaccio local npm registry for vitest-pool-workers tests

- .changeset/plenty-birds-melt.md
- .changeset/short-kids-hunt.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/pipelines/cli/create.ts
- packages/wrangler/src/pipelines/cli/delete.ts
- packages/wrangler/src/pipelines/cli/list.ts
- packages/wrangler/src/pipelines/cli/show.ts
- packages/wrangler/src/pipelines/cli/update.ts
- packages/wrangler/src/pipelines/client.ts
- packages/wrangler/src/pipelines/index.ts
- packages/wrangler/src/pipelines/validate.ts
**Pipelines is currently in closed beta, renaming these without providing aliases _should_ have limited to zero impact**
Moving each of the subcommand handlers and options for each subcommand into its own file. This also renames many of the parameters to be more specific.
The following parameters have been renamed:
| Previous Name | New Name |
| ---- | ---- |
| access-key-id | r2-access-key-id |
| secret-access-key | r2-secret-access-key |
| transform | transform-worker |
| r2 | r2-bucket |
| prefix | r2-prefix |
| binding | enable-worker-binding |
| http | enable-http |
| authentication | require-http-auth |
| filename | file-template |
| filepath | partition-template |
Adds the following new option for `create` and `update` commands:
```
--cors-origins           CORS origin allowlist …
```
> Refactor pipelines commands into separate files, rename some options

- .changeset/smooth-games-cover.md
- packages/wrangler/src/hyperdrive/client.ts
Fixes SQC-394
This solved an issue for customers that have more than 20 Hyperdrive configs. The Hyperdrive backend has default settings for pagination, and in some cases this would mean that not all Hyperdrive configs would be listed by the CLI.
---
- Tests
> Use fetchPagedListResult when listing Hyperdrive configs from API

- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/secret/index.ts
refactors `wrangler secrets` to use the createCommand interface
---
- Tests
> chore: refactor wrangler secrets commands

- .changeset/spicy-eggs-tan.md
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/js/package.json
- packages/create-cloudflare/templates-experimental/hello-world-with-assets/ts/package.json
- packages/create-cloudflare/templates/hello-world/js/package.json
- packages/create-cloudflare/templates/hello-world/ts/package.json
Fixes n/a.
The vitest team has released [v2.1.9](https://github.com/vitest-dev/vitest/releases/tag/v2.1.9) with critical security patches yesterday. This updates the version in our templates to use v2.1.9 or any future patches through the `~` version range.
---
- Tests
> chore(create-cloudflare): update vitest version in templates

- .changeset/sharp-carrots-deliver.md
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/deprecated-usage-model.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/utils/print-bindings.ts
Fixes DEVX-1588 (sort of).
The reported issue in the ticket (--dry-run not printing bindings) was not a wrangler issue in the end. However, to prevent similar situations happening again, it would be nice to explicitly log something out when there are no bindings found, in case bindings _were_ expected.
---
- Tests
> feat: add some logging when no bindings are found

- packages/unenv-preset/tests/index.test.ts
Fixes #0000
Run the unenv-presets also on Windows
---
- Tests
> test: run unenv-preset tests on Windows

- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/deployments/list.ts
- packages/wrangler/src/versions/deployments/status.ts
- packages/wrangler/src/versions/list.ts
- packages/wrangler/src/versions/rollback/index.ts
- packages/wrangler/src/versions/upload.ts
- packages/wrangler/src/versions/view.ts
A couple of worker name not found errors were showing up in sentry.
---
- Tests
> chore: change some `asserts` to UserErrors so they don't get reported to sentry

- .changeset/light-taxis-move.md
- packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/logger.ts
- packages/wrangler/src/utils/print-bindings.ts
Fixes #000.
In the developer's console output:
- adds "[Simulated Locally]" to local bindings
- adds "[Connected to Remote Resource]" to remote bindings
- adds explanation after Wrangler banner explaining that the resources are simulated locally via Miniflare.
- adds link to doc
add brief explanation of --remote  flag and link to relevant doc.
e.g.
```
⛅️ wrangler 3.102.0
--------------------------------------------------------
Your Worker and resources are simulated locally via Miniflare. For more information, see: https://developers.cloudflare.com/workers/testing/local-development/#develop-using-remote-resources-and-bindings
Your Worker has access to the following bindings:
Durable Objects:
- MY_DO: MyDo [Simulated locally]
KV Namespaces:
- MY_KV: c8dsdfhh258c94d91239ed7nj6f33e163 …
```
> Better messaging in dev console

- packages/miniflare/package.json
- pnpm-lock.yaml
Fixes #000
This pins dependencies of Miniflare to ensure that transitive dependencies don't break Miniflare releases.
- Tests
> chore: pin Miniflare deps

- packages/workers-shared/README.md
Document release process for workers-shared's asset-worker and router worker
- Tests
> Document release process for workers-shared's asset-worker and router-worker

- .changeset/wise-pants-raise.md
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/versions/secrets/bulk.ts
- packages/wrangler/src/versions/secrets/index.ts
- packages/wrangler/src/versions/secrets/put.ts
In cases of `wrangler versions secret put`, we were losing the stable name on asset-worker and router-worker. This passes along the unsafe metadata during these deploys.
- Tests
> Provide unsafe metadata for wrangler versions secret put

- .github/actions/install-dependencies/action.yml
Currently our C3 tests are failing as unimport requires node >= 18.20.6. 
We are currently on 18.20.5 so this shouldn't have much impact.
---
- Tests
> chore: use node 18.20.6 in CI

- .changeset/poor-otters-drop.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/assets/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/wrangler/e2e/multiworker-dev.test.ts
#7251 will allow running multiple workers in one Miniflare instance. Currently we only set up the router/asset worker for the first worker passed to miniflare, assuming this will be the only user worker. This PR will make sure assets works regardless of how many 'user workers' are passed in and at what point.
---
- Tests
> fix: allow assets in multiworker setup

- .changeset/kind-sloths-speak.md
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/__tests__/versions/secrets/utils.ts
- packages/wrangler/src/versions/secrets/index.ts
This commit provides a means of inheriting all known bindings, rather than attempting to rebuild them in the versions secret put call. Some bindings (like DOs and internal bindings) don't have all fields returned. Instead, we can provide a type "inherit" for each known binding-by-name, and the API will carry over the binding from the last version.
- Tests
> Change type to "inherit" for all fetched bindings in versions secret put

- .changeset/wet-glasses-rush.md
- packages/wrangler/src/deployment-bundle/bindings.ts
- packages/wrangler/src/metrics/send-event.ts
Fixes [DEVX-1618]
Sends a new adhoc telemetry event since the dispatcher cannot (currently) be used in command handlers.
---
- Tests
> chore: add metrics event for provisioning

- .changeset/silver-bats-burn.md
- packages/vite-plugin-cloudflare/playground/websockets/__tests__/websockets.spec.ts
- packages/vite-plugin-cloudflare/playground/websockets/src/index.html
- packages/vite-plugin-cloudflare/playground/websockets/src/index.ts
- packages/vite-plugin-cloudflare/src/websockets.ts
Fixes #000.
This fixes a bug where WebSocket messages from the client were always being received as ArrayBuffers in the Worker.
---
- Tests
> Ensure the correct data types are sent in WebSocket messages from the client to the Worker

- .changeset/hip-beans-hug.md
- packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Fixes #[000].
Omit files from public directory in Worker builds
---
- Tests
> Omit files from public directory in Worker builds

- .changeset/fifty-hairs-drum.md
- packages/workers-shared/asset-worker/src/index.ts
WC-3184
Rolls out interpolation search method for 1 / 20,000 requests.
---
- Tests
> Rollout interpolation search for asset manifests (1/20,000)

- .changeset/proud-days-study.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
> fix: hide wrangler banner in `secret list --format=json`

- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/router-worker/src/index.ts
- packages/workers-shared/utils/sentry.ts
Provides the version tag as the sentry release.
---
- Tests
> Pass through version tag as sentry release

- .changeset/orange-rockets-leave.md
- packages/workers-shared/asset-worker/src/assets-manifest.ts
- packages/workers-shared/asset-worker/tests/assets-manifest.test.ts
WC-3184.
There's a case that when comparing extreme manifests, (very high highs and very low lows), we'd encounter a divide by zero error. This fixes that issue by adding early checks before the calculation against what would otherwise be out-of-bounds search operations.
---
- Tests
> Fix interpolation search for extreme manifests

- .changeset/modern-cycles-build.md
- packages/vite-plugin-cloudflare/src/deploy-config.ts
- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
The deploy config file is now written in the `writeBundle` hook rather than `builder.buildApp`. This ensures that the file is still written if other plugins override `builder` in the Vite config.
---
- Tests
> Call `writeDeployConfig` in `writeBundle` rather than `builder.buildApp`

- .changeset/eighty-panthers-rule.md
- packages/workers-shared/utils/sentry.ts
Source maps were not correctly mapping.
See: https://docs.docbase.ai/platforms/node/guides/express/configuration/integrations/pluggable-integrations/#rewriteframes
- Tests
> Add RewriteFrames to correct issue with source mappings

- packages/workers-shared/scripts/upload-sourcemaps.ts
Debug IDs were causing a mismatch with expected release. Since we are creating our own release, we can remove this. Validated in staging:
https://docs.sentry.io/platforms/javascript/sourcemaps/troubleshooting_js/artifact-bundles/
- Tests
> Remove debug ids from upload-sourcemaps.ts

- .changeset/stale-zoos-drop.md
- packages/vite-plugin-cloudflare/playground/hot-channel/vite.config.ts
- packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
This prevents `next` from being called in the dev and preview server middleware. This is for framework compatibility so that we can override middleware provided by the framework.
---
- Tests
> No longer call `next` in server middleware.

- .changeset/few-bobcats-brake.md
- packages/wrangler/src/__tests__/sentry.test.ts
- packages/wrangler/src/sentry/index.ts
Currently, Sentry errors reported by users in Wrangler do _not_ include console output. We made this decision out of an abundance of caution to try and reduce the amount of potential data we were capturing. However, this is causing issues with being able to effectively diagnose reported errors from Wrangler (in particular `MiniflareCoreError [ERR_RUNTIME_FAILURE]` is undiagnosable without console output).
As such, I think we should turn the console integration on. Console output from Wrangler should not include PII—I believe our thinking at this time was that potentially user logs from a local Worker might accidentally include PII? However, users still have to make a active decision to report errors to Sentry, and so I think that gives sufficient opportunity for users to not send specific …
> Enable Sentry Console integration

- .changeset/odd-months-crash.md
- packages/workers-shared/asset-worker/src/analytics.ts
- packages/workers-shared/asset-worker/src/index.ts
WC-3202
The cost of an `await` here is outweighed by the confidence we get in making stable asset-worker releases.
---
- Tests
> Add status code analytics to router-worker

- .changeset/rotten-eyes-boil.md
- packages/workers-shared/asset-worker/src/index.ts
WC-3184
Bumps interpolation search method for reading asset manifests to 50%, up from 1%.
---
- Tests
> Bump interpolation search for asset manifest reads to 50%

- .changeset/slimy-otters-rush.md
- fixtures/vitest-pool-workers-examples/README.md
- fixtures/vitest-pool-workers-examples/pipelines/README.md
- fixtures/vitest-pool-workers-examples/pipelines/src/env.d.ts
- fixtures/vitest-pool-workers-examples/pipelines/src/index.ts
- fixtures/vitest-pool-workers-examples/pipelines/src/tsconfig.json
- fixtures/vitest-pool-workers-examples/pipelines/test/env.d.ts
- fixtures/vitest-pool-workers-examples/pipelines/test/pipeline-send-integration-self.test.ts
- fixtures/vitest-pool-workers-examples/pipelines/test/pipeline-send-unit.test.ts
- fixtures/vitest-pool-workers-examples/pipelines/test/tsconfig.json
- fixtures/vitest-pool-workers-examples/pipelines/tsconfig.json
- fixtures/vitest-pool-workers-examples/pipelines/vitest.config.ts
- fixtures/vitest-pool-workers-examples/pipelines/wrangler.toml
- packages/miniflare/README.md
- packages/miniflare/src/plugins/index.ts
- packages/miniflare/src/plugins/pipelines/index.ts
- packages/miniflare/src/workers/pipelines/pipeline.worker.ts
- packages/miniflare/test/plugins/pipelines/index.spec.ts
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/src/dev/miniflare.ts
Adding support to Miniflare to reference bindings during `wrangler dev` or during tests via vitest.
This binding uses newer JSRPC method instead of propagating changes through `workerd.capnp`.
Fixes https://jira.cfdata.org/browse/PIPE-166
---
- Tests
> Add Worker Pipelines Binding to Miniflare

- packages/workers-shared/package.json
Presently, the tags collide, which will cause issues since the workers do not share the same code.
- Tests
> Provide unique sentry tag+release for asset-worker and routr-worker

- .changeset/tidy-keys-sin.md
- packages/wrangler/src/__tests__/d1/create.test.ts
- packages/wrangler/src/d1/create.ts
Output correct config format from `wrangler d1 create`. Previously, this command would always output TOML, regardless of the config file format
---
- Tests
> Render correct config format from `wrangler d1 create`

- .changeset/wet-starfishes-drum.md
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/metrics/metrics-dispatcher.ts
Include default values for wrangler types --path and --x-include-runtime in telemetry
User provided strings are still left redacted as always.
Note i've also tested this manually for wrangler types
---
- Tests
> feat: allowlist some types defaults

- packages/vite-plugin-cloudflare/playground/package.json
This PR simplified the vite-plugin-cloudflare playground playwright installation by only installing the chromium browser and nothing else.
This should unblock: https://github.com/vitejs/vite-ecosystem-ci/pull/361
<details><summary>Details</summary>
[`playwright install-deps`](https://playwright.dev/docs/browsers#install-system-dependencies) doesn't work great everywhere, for example [it doesn't work on arch linux](https://www.reddit.com/r/linux4noobs/comments/rp76h1/how_can_i_do_playwright_installdeps_on_arch_linux/), the playwright docs are a bit vague on what it installs but it sounds like it might not be generally necessary (as you can also see from the successful CI runs in this PR).
Besides that we only use the chromium browser so only that needs to actually be installed.
</details> …
> [vite-plugin-cloudflare] simplify playground playwright install

- .changeset/wild-kiwis-behave.md
- packages/create-cloudflare/src/wrangler/__tests__/config.test.ts
- packages/create-cloudflare/src/wrangler/config.ts
Fixes #8151
This simply uses tabs for indentation to match the format of most common hello world, etc. templates.
---
- Tests
> fix(create-cloudflare): use tabs for indentation in wrangler.json

- .github/pr-labeler.config.yml
- .github/workflows/README.md
- .github/workflows/c3-e2e-quarantine.yml
- .github/workflows/c3-e2e.yml
To address CI queuing issues (C3 E2E is the most expensive job across the entire Cloudflare org), reduce C3 E2E CI runs to:
* Run normal C3 E2E on VP and PRs with the `c3-e2e` label
* Run C3 E2E quarantine at 3AM every day, when no other jobs are usually running (additionally, this can be manually run on a specific branch if needed)
---
- Tests
> Reduce C3 CI runs

- .github/workflows/test-and-check.yml
Reduce CI concurrency by not spinning up a new runner for tooling tests on Ubuntu—this takes ~40 seconds fully cached because of package installation. Additionally, use (hopefully faster) ARM runners.
---
- Tests
> Reduce CI concurrency

- .changeset/olive-gifts-flash.md
- packages/wrangler/src/__tests__/d1/export.test.ts
- packages/wrangler/src/d1/export.ts
Fixes error handling for CFSQL-1205 (https://www.cloudflarestatus.com/incidents/x2vwc84qvwx3).
When the presigned URLs generated during export are invalid, wrangler was just outputting the broken response into the SQL file.
This change adds a validation that the request was successful before writing it to the file so that users get immediate feedback that it went wrong. Main change is in `packages/wrangler/src/d1/export.ts`.
---
- Tests
> Fix D1 Export error handling when presigned URLs are invalid

- .changeset/twenty-chefs-lick.md
- packages/vitest-pool-workers/src/pool/index.ts
- packages/vitest-pool-workers/src/pool/module-fallback.ts
- packages/vitest-pool-workers/test/global-setup.ts
Fixes #5268, #8064. Close #5913.
Just made a minor tweak from #5913 to fix window support.
---
- Tests
> fix(vitest-pool-workers): support running in directories containing spaces

- .changeset/ninety-phones-tell.md
- packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/vite-plugin-cloudflare/src/node-js-compat.ts
- packages/vite-plugin-cloudflare/src/utils.ts
Fixes #0000.
This is not fixing a bug per-se, except that prior to this change some of the Node.js polyfills would only be processed by the dependency optimizer during/after the first request was made. This meant there was a danger of the dependencies that had been prebundled already becoming stale and the app being in a bad state.
- makes use of the new custom builtin support that @dario-piotrowicz added to Vite recently
- proactively pre-bundles all the Node.js compat polyfill entry-points
- removes the need to use the Vite aliasing mechanism (which is not configurable per environment) and so the problematic virtual modules
- dramatically simplifies the Node.js compat plugin code base
---
- Tests …
> fix: refactor Node.js compat support to ensure all polyfills are pre-bundled before the first request

- .github/pr-labeler.config.yml
- .github/workflows/c3-e2e.yml
- .github/workflows/e2e.yml
Simplifies the E2E setup by only running C3 E2E and Wrangler E2E when the relevant label is applied, and then automatically applying that label to Version Packages. Previously, in some cases E2E tests were running _twice_ on Version Packages (because of the automatic label, and then the override to always run on Version Packages)
Additionally, remove the `skip-pr-description` label from Version Packages, since PR description validation is already skipped on that branch.
> Always use labels for E2E

- packages/vite-plugin-cloudflare/e2e/basic.test.ts
Skips flaky vite-plugin test
---
- Tests
> chore(vite-plugin): skip node_compat test for now due to flakiness

- .changeset/four-mammals-report.md
- packages/create-cloudflare/templates-experimental/next/c3.ts
This change removes a set of flags that get passed to `create-next-app` that force the generated Next.js
application to have specific settings (e.g. typescript, tailwind, src directory, etc...) which are not
actually mandatory/recommended for the use of the open-next Cloudflare adapter
---
- Tests
> fix: remove unnecessary flags passed to `create-next-app` when creating Next.js apps in experimental mode

- .changeset/large-hotels-create.md
- packages/create-cloudflare/src/helpers/poll.ts
This change makes the user facing message C3 displays while waiting for DNS propagation, more friendly/informative. The idea is to inform users that DNS propagation might sometimes take even up to 2 minutes. This will hopefully prevent confusion around whether how long the process will take, or whether the process is stuck, etc.
See https://github.com/cloudflare/workers-sdk/issues/8187
---
- Tests
> fix(create-cloudflare): make DNS poling copy more user friendly

- .changeset/huge-pears-tickle.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/test/index.spec.ts
Fixes #5486.
In `vitest-pool-workers`, we parse the Miniflare options from `poolOptions` upfront before instantiating a Miniflare instance. This creates an issue with `fetchMock`: the Zod schema sets an `outboundService` based on the `fetchMock` option during the initial parse, and then runs again when a Miniflare instance is created. This results in an error because Miniflare does not accept having both `fetchMock` and `outboundService` simultaneously.
This fix removes the `fetchMock` option during the initial parse so that Miniflare only receives the `outboundService`.
---
- Tests
> fix(vitest-pool-workers): fetchMock support on auxiliary worker

- .changeset/quick-shoes-jump.md
- packages/vitest-pool-workers/src/worker/lib/cloudflare/test-runner.ts
- packages/vitest-pool-workers/test/watch.test.ts
> fix(vitest-pool-workers): reset module graphs to ensure module mock works in watch mode

- .changeset/ripe-socks-stay.md
- packages/create-cloudflare/src/cli.ts
- packages/create-cloudflare/src/metrics.ts
Currently C3 does not explicitly exit the process if an error is thrown, or if a "SIGINT" or "SIGTERM" signal is received. This leads to situations when, if `ctrl+C` is pressed while there are still tasks in the stack/microtask queues (think in flight async xhr calls, or polling, or long running
`while` loops), the current process will continue running until all those tasks are run to completion, and the queues are empty.
This commit fixes this by explicitly calling `process.exit()` when an error is thrown (our internal "SIGINT"/"SIGTERM" handlers will throw a `CancelError`), thus ensuring we always exit the process.
Fixes https://github.com/cloudflare/workers-sdk/issues/8187
---
- Tests
- Public …
> fix(create-cloudflare): Ensure we exit the process on "SIGINT" and "SIGTERM"

- .changeset/beige-crews-wash.md
- fixtures/workers-with-assets/public/totallyinvalidextension.greg
- fixtures/workers-with-assets/tests/index.test.ts
- packages/miniflare/src/plugins/assets/index.ts
- packages/miniflare/src/workers/assets/assets-kv.worker.ts
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/src/utils/headers.ts
- packages/workers-shared/utils/helpers.ts
- packages/wrangler/src/assets.ts
Fixes WC-3028.
This isn't quite everything. This makes it work in `wrangler dev` and prepares the asset-worker in production to be able to handle missing contentType metadata. We'll need to land this, then API support, and then follow up with the final piece here.
---
- Tests
> Prepare to omit Content-Type header for files of unknown extension in Workers Assets

- .changeset/silver-flowers-notice.md
- packages/create-cloudflare/src/__tests__/git.test.ts
- packages/create-cloudflare/src/git.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/8065.
If in an existing git repository, don't ask the user if they would like to use git.
---
- Tests
> fixes #8065

- .github/workflows/workers-shared-deploy-production.yml
- .github/workflows/workers-shared-deploy-staging.yml
Fixes the table rendering in prod and we don't actually need it for staging.
---
- Tests
> Fix deployment summary

- .changeset/bitter-teeth-think.md
- packages/vite-plugin-cloudflare/playground/node-compat/worker-basic/index.ts
- packages/vite-plugin-cloudflare/playground/node-compat/worker-basic/wrangler.toml
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/__tests__/same-worker-service-bindings.spec.ts
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/package.json
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/src/index.ts
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/tsconfig.json
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/tsconfig.node.json
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/tsconfig.worker.json
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/turbo.json
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/vite.config.ts
- packages/vite-plugin-cloudflare/playground/same-worker-service-bindings/wrangler.toml
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- pnpm-lock.yaml
Fixes #000
This adds support for binding to named entrypoints in the same Worker.
Additionally, this adds `cloudflare:workers` imports to the `node-compat/worker-basic` playground so that we have tests to confirm that Cloudflare builtins can be used when `nodejs_compat` is enabled.
---
- Tests
> Add support for binding to named entrypoints in the same Worker

- .changeset/good-rooms-sneeze.md
- packages/vite-plugin-cloudflare/playground/custom-build-app/__tests__/custom-build-app.spec.ts
- packages/vite-plugin-cloudflare/playground/custom-build-app/package.json
- packages/vite-plugin-cloudflare/playground/custom-build-app/src/index.ts
- packages/vite-plugin-cloudflare/playground/custom-build-app/tsconfig.json
- packages/vite-plugin-cloudflare/playground/custom-build-app/tsconfig.node.json
- packages/vite-plugin-cloudflare/playground/custom-build-app/tsconfig.worker.json
- packages/vite-plugin-cloudflare/playground/custom-build-app/turbo.json
- packages/vite-plugin-cloudflare/playground/custom-build-app/vite.config.ts
- packages/vite-plugin-cloudflare/playground/custom-build-app/wrangler.toml
- packages/vite-plugin-cloudflare/src/index.ts
- pnpm-lock.yaml
Fixes #000.
Make it possible to override `builder.buildApp` in the user config or prior plugins. As well as allowing users to provide their own `buildApp` function, this also makes framework integrations less dependent on plugin order.
I haven't added a specific playground to test this as it is likely the `buildApp` API might change soon.
---
- Tests
> Make `builder.buildApp` overridable

- .changeset/vast-trains-joke.md
- fixtures/vitest-pool-workers-examples/misc/test/fetch-mock.test.ts
- packages/vitest-pool-workers/src/worker/fetch-mock.ts
> fix(vitest-pool-workers): responses from `fetchMock` should have immutable headers

- .changeset/blue-foxes-notice.md
- .changeset/weak-chairs-tap.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/lifecycle.ts
- packages/wrangler/src/r2/lock.ts
What this PR solves / how to test
Allows user to configure lock configuration on an R2 bucket
---
- Tests
> Adding wrangler commands for R2 bucket lock rule configuration

- .changeset/sixty-spoons-unite.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/templates/pre-existing/c3.ts
- packages/create-cloudflare/templates/pre-existing/js/wrangler.jsonc
Fixes #8188
This was generating broken projects due to the fact there were three (!) separate config files.
---
- Tests
> fix: remove extra config files that are generated by c3 with `--existing-script `

- .changeset/red-rockets-lie.md
- packages/vitest-pool-workers/src/pool/loopback.ts
Fixes #5629
This PRs updated the error message with isolated storage with a link to known issues documented in https://github.com/cloudflare/cloudflare-docs/pull/20033
---
- Tests
> fix(vitest-pool-workers): improve error message with isolated storage

- .changeset/silver-tools-promise.md
- packages/miniflare/src/plugins/core/index.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/core/register-yargs-command.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/experimental-flags.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/versions/upload.ts
Fixes [DEVX-1646](https://jira.cfdata.org/browse/DEVX-1646)
Adds a flag for Assets RPC, usable with `--x-assets-rpc`. This is passed through to Miniflare as `unsafeEnableAssetsRpc`, and is available as `sharedOpts.core.unsafeEnableAssetsRpc` within the `#assembleConfig()` function.
---
- Tests
> Add flag for Assets RPC

- .changeset/five-streets-act.md
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/create-cloudflare/e2e-tests/helpers.ts
- packages/create-cloudflare/src/__tests__/git.test.ts
- packages/create-cloudflare/src/git.ts
Fixes #8264
This fixes a small regression introduced by #8264. In that PR we wanted to avoid running `git init` if there was already a repository in place, but it also resulted in the git commit being skipped in every case.
Even if you are not in a git repo you would see:
Here we fix the regression but also tidy up the code (and unit tests) because there was a lot of unnecessary repeated commands being run, and it was not always clear when values should have been set by.
It also adds in support for testing that the git commit is actually applied in e2e tests, which was not being tested before.
---
- Tests
> C3: ensure that git commits are generated

- .changeset/public-groups-thank.md
- packages/wrangler/src/cloudchamber/cli/deployments.ts
The `--label` arguments were ignored when listing deployments interactively.
---
- Tests
> fix: interactively list Cloudchamber deployments using labels

- packages/wrangler/package.json
- packages/wrangler/templates/pages-dev-pipeline.ts
- packages/wrangler/templates/tsconfig.json
I've noticed that wrangler's `check:type` script is not including the `templates` directory at all, this PR is partially addressing this, here I am still excluding the `startDevWorker` and `middleware` directories since those are quite problematic and potentially time consuming to address (I'm going to create an issue for addressing these separately)
---
- Tests
> chore: include `templates` directory in wrangler"s `check:type` script

- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- tools/e2e/common.ts
- tools/e2e/e2eCleanup.ts
Fixes [DEVX-1624](https://jira.cfdata.org/browse/DEVX-1624)
the e2e tests were trying to delete using the config _name_ not _id_
so now we have 1000 configs
this adds hyperdrive configs to the nightly cleanup
and also fixes that original problem
---
- Tests
> chore: cleanup e2e hyperdrive configs

- packages/unenv-preset/build.config.ts
This PR adds `__filename` which was not defined before:
(The whole `// -- Unbuild CommonJS Shims --` section is added by this PR)
```ts
// -- Unbuild CommonJS Shims --
import __cjs_url__ from 'url';
import __cjs_path__ from 'path';
import __cjs_mod__ from 'module';
const __filename = __cjs_url__.fileURLToPath(import.meta.url);
const __dirname = __cjs_path__.dirname(__filename);
const require = __cjs_mod__.createRequire(import.meta.url);
// [...] 
const cloudflare = {
meta: {
name: "unenv:cloudflare",
version,
url: __filename
},
```
---
- Tests
> fix(unenv-preset): define __filename

- .changeset/itchy-peaches-kneel.md
The main changes for 2.0.0 were implemented in https://github.com/cloudflare/workers-sdk/pull/7915
There are been a few small follow-up PRs to fix minor issues.
The preset is not used yet by wrangler (or the vite plugin) - that will be the next step.
However the latest beta release is validated with wrangler in #8300.
After the preset 2.0.0 is released (hopefully on Tuesday):
- 8300 should be update to use that release, we will verify that there is no pb with Astro, ... The goal is that we use that in wrangler on Thursday release
- The Vite plugin should be update to use 2.0.0
/cc @petebacondarwin @jamesopstad 
---
- Tests
> unenv preset changeset for 2.0.0

- .changeset/small-news-kneel.md
- packages/vitest-pool-workers/src/pool/index.ts
- packages/vitest-pool-workers/test/inspector.test.ts
Fixes #5391
Added step-through debugging support with Vitest.
You can now debug your workers tests by running `vitest --inspect --no-file-parallelism` which opens an inspector on port 9229 by default.
If you are using vscode, you can creates a `.vscode/launch.json` file that contains the following:
```json
{
"configurations": [
{
"type": "node",
"request": "launch",
"name": "Open inspector with Vitest",
"program": "${workspaceRoot}/node_modules/vitest/vitest.mjs",
"console": "integratedTerminal",
"args": ["--inspect=9229", "--no-file-parallelism"]
},
{
"name": "Attach to Workers Runtime",
"type": "node",
"request": "attach",
"port": 9229,
"cwd": "/",
"resolveSourceMapLocations": null,
"attachExistingChildren": false,
"autoAttachChildProcesses": false,
}
],
"compounds": [
{
"name": "Debug …
```
> feat(vitest-pool-workers): step-through debugging

- .changeset/all-sloths-fly.md
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
I was seeing an error like this: `Unexpected error: no match for module path.`. But it wasn't telling me what the path was. On debugging I noticed that it was telling me about the module "path"! Which meant I needed to enable node_compat. This patch just makes the messaging a little clearer.
(Ideally we'd spot that it was a node builtin and recommend turning on node_compat, but I'll leave that to you folks.)
Fixes #0000
---
- Tests
> chore: tweak a couple of error messages in the vite plugin

- .changeset/shiny-zebras-switch.md
- packages/wrangler/src/__tests__/queues.test.ts
- packages/wrangler/src/queues/cli/commands/index.ts
- packages/wrangler/src/queues/cli/commands/pause-resume.ts
- packages/wrangler/src/queues/client.ts
Fixes https://jira.cfdata.org/browse/MQ-846.
Adds new commands to pause and resume message delivery for a Queue.
---
- Tests
> Add Queues commands to pause-delivery and resume-delivery

- .changeset/dry-ends-post.md
- fixtures/workers-with-assets-only/tests/index.test.ts
- fixtures/workers-with-assets-run-worker-first/tests/index.test.ts
- fixtures/workers-with-assets/tests/index.test.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/assets/constants.ts
- packages/miniflare/src/plugins/assets/index.ts
- packages/miniflare/src/plugins/assets/schema.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
- packages/vitest-pool-workers/src/pool/config.ts
- packages/wrangler/e2e/multiworker-dev.test.ts
This PR implements a very basic Proxy Worker skeleton, and wires it in the "pipeline" miniflare creates for assets. This Worker will be incrementally worked on, but for now, the current implementation will forward all incoming requests to the Router Worker, thus leaving the current assets behaviour in local dev, unchanged.
TLDR 👇 
**Why are we doing this?** Because we expect the proxy Worker code to be quite involved, so we don't want to worry at that point whether the wiring works properly or not. We just want to focus on that Worker code
Fixes DEVX-1641, DEVX-1642
---
- Tests
> feat(miniflare): Add assets Proxy Worker skeleton in miniflare

- packages/eslint-config-worker/index.js
- packages/eslint-config-worker/package.json
- packages/eslint-config-worker/react.js
- pnpm-lock.yaml
Fixes n/a.
The dependabot PR on #8340 updated the `eslint-config-turbo` version and runs into an [error](https://github.com/cloudflare/workers-sdk/actions/runs/13653973927/job/38168668476?pr=8340#step:5:141) with eslint. This fix follows the suggestion on https://github.com/vercel/turborepo/pull/9978/files#r1974406494
---
- Tests
> chore: update eslint-config-turbo version

- .changeset/purple-taxis-call.md
- packages/create-cloudflare/e2e-tests/frameworks.test.ts
- packages/miniflare/src/plugins/assets/index.ts
I think this might be all we need to fix the failing E2E tests in the Version Packages PR. The asset-worker has a similar default being set: https://github.com/cloudflare/workers-sdk/pull/8355/files#diff-7ff83250c22d1ffda26334752afe5b193eb685e491960f8ab94adbfe5d608dadR126
---
- Tests
> Add default empty router config for assets in Miniflare

- .changeset/whole-dots-smile.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/r2/lifecycle.ts
- packages/wrangler/src/r2/lock.ts
Change id parameter to name for both bucket lifecycle and r2 bucket lock commands
---
- Tests
> Change id parameter to name for both bucket lifecycle and r2 bucket lock commands

- .changeset/wise-taxes-strive.md
- packages/wrangler/src/assets.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/pages/upload.ts
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/zones.ts
Fixes Follow up to https://github.com/gzuidhof/zarr.js/pull/145
In rare cases, looking up Zone or Route API calls may fail due to transient errors. This change improves the reliability of `wrangler deploy` when these errors occur.
Also fixes a rare issue where concurrent API requests may fail without correctly throwing an error which may cause a deployment to incorrectly appear successful.
I discovered this issue when I noticed that some API calls failed, but the deployment still completed:
https://gist.github.com/jahands/3b71d748c554b971cd99c76783b94c82
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason: TypeError: …
```
> fix: retry zone and route lookup API calls

- .changeset/thirty-emus-find.md
- packages/workers-shared/asset-worker/src/analytics.ts
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/src/utils/final-operations.ts
- packages/workers-shared/asset-worker/src/utils/headers.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
Fixes N/A
Attach a CF-Cache-Status header to asset responses. We currently do not have a way to get this status from KV so we're assuming HIT if it's <= 100 ms. This will mark ~99.5% of requests today as cache HIT which is probably about right.
---
- Tests
> Add `CF-Cache-Status` to Workers Assets

- .changeset/chatty-glasses-drum.md
- packages/wrangler/src/__tests__/kv.local.test.ts
- packages/wrangler/src/kv/index.ts
The bulk put api has an optional "base64" boolean property for each key. Before storing the key, the value should be decoded from base64.
For real (remote) kv, this is handled by the rest api. For local kv, it seems the base64 field was ignored, meaning encoded base64 content was stored locally rather than the raw values.
To fix, we need to decode each value before putting to the local miniflare namespace when base64 is true.
---
- Tests
> fix(wrangler): Make kv bulk put --local respect base64:true

- packages/vite-plugin-cloudflare/e2e/README.md
- packages/vite-plugin-cloudflare/e2e/basic.test.ts
- packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
- packages/vite-plugin-cloudflare/e2e/global-setup.ts
- packages/vite-plugin-cloudflare/e2e/helpers.ts
DEVX-1728: adds missing tests.
---
- Tests
> test: add e2e tests of the build+preview use case

- .github/workflows/open-v3-maintenance-prs.yml
- tools/deployments/open-v3-pr.ts
See https://github.com/cloudflare/workers-sdk/pull/7402 for an example.
This PR adds a workflow that will, for every PR with a Wrangler patch change, open a corresponding PR to the `v3-maintenance` branch (not created yet, but will be after v4 is released). The auto-generated PRs will likely not be perfect, but they should be a good starting point to backporting the fix. Some fixes will not be relevant, and so could just be closed (i.e. a fix for a feature introduced in v4 wouldn't make sense to backport)
> Automatically backport Wrangler patches to v3

- .changeset/fuzzy-regions-post.md
- fixtures/d1-read-replication-app/.gitignore
- fixtures/d1-read-replication-app/README.md
- fixtures/d1-read-replication-app/package.json
- fixtures/d1-read-replication-app/src/index.ts
- fixtures/d1-read-replication-app/tests/index.test.ts
- fixtures/d1-read-replication-app/tests/tsconfig.json
- fixtures/d1-read-replication-app/tsconfig.json
- fixtures/d1-read-replication-app/wrangler.toml
- packages/miniflare/src/workers/d1/database.worker.ts
- pnpm-lock.yaml
Fixes CFSQL-1196.
This change adds the D1 Sessions API bookmark header in the responses from Miniflare, same way as the D1 API returns them to the D1 Binding requests.
This allows the Sessions API to return a proper bookmark in the `getBookmark()` method of the D1 database session.
The main changes are in the `packages/miniflare/src/workers/d1/database.worker.ts` file.
The rest are just changes for testing that change.
This is building ontop of https://github.com/cloudflare/workerd/pull/3568/files that provides local bookmarks for SQLite DOs.
---
- Tests
> CFSQL-1196: Extend D1 local dev experience to work with Sessions API bookmarks

- packages/create-cloudflare/e2e-tests/helpers.ts
> c3: pin C3 e2e tests to use the local version of create-cloudflare rather than latest

- .github/workflows/open-v3-maintenance-prs.yml
- tools/deployments/open-v3-pr.ts
Improves v3 maintenance mechanic by:
- changing the base branch to `v3`, not `v2`
- Adding comments to help PR openers understand the process
> Fix v3 maintenance

- .changeset/wise-points-love.md
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/hyperdrive/client.ts
- packages/wrangler/src/hyperdrive/create.ts
- packages/wrangler/src/hyperdrive/index.ts
- packages/wrangler/src/hyperdrive/list.ts
- packages/wrangler/src/hyperdrive/update.ts
- Add mtls fields to hyperdrive command `ca_certificate_uuid` and `mtls_certificate_uuid`
---
- Tests
> SQC-354 add mtls fields to hyperdrive

- fixtures/worker-app/src/explicit-resource-management.js
- fixtures/worker-app/src/index.js
- fixtures/worker-app/tests/index.test.ts
Fixes WC-000.
With the latest esbuild, we now have bundling support for `using` and native support has landed in v8 and in workerd — we can now get rid of #5501! This just ports over a test in the PR we had to assert `using` works correctly.
---
- Tests
> Add 'using' test

- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
Wrangler has E2E tests that ensure all resources can be accessed from both a local and remote dev session. Typically, these perform some sort of round trip operation on a binding to validate that it's both available and working as expected. For instance, for KV this might include writing a key and then reading it.
Implicitly, this means we're assuming a write operation followed by a read operation will reflect the data from the first wrte operation. This holds up for all bindings (even in practice KV) _except Vectorize_, which is [intentionally asynchronous](https://developers.cloudflare.com/vectorize/reference/client-api/#insert-vectors) here. As such, our Vectorize E2E test waited for the results of the write operation to be available before trying to read. This is _really slow_, and …
> Use a shared Vectorize index for the Vectorize E2E tests

- tools/deployments/open-v3-pr.ts
Fixes n/a
Fix `fatal: Does not point to a valid commit 'v3-maintenance'` error in `open-v3-pr` script (see https://github.com/cloudflare/workers-sdk/actions/runs/13857544424/job/38777668482?pr=8401 for failure)
---
- Tests
> fix: Fix error in `open-v3-pr` script

- .changeset/real-clocks-ask.md
- packages/create-cloudflare/templates-experimental/next/c3.ts
- packages/create-cloudflare/templates-experimental/next/templates/open-next.config.ts
- packages/create-cloudflare/templates-experimental/next/templates/wrangler.jsonc
Update Next.js to ~15.2.2
Also:
- drop minify (for consistency with other templates + code already minified by OpenNext)
- simplify the config
- handle `next.config.ts` which is now generated by the Next CLI in TS mode (similar to what is done for Next on Pages)
---
- Tests
> Update Next.js version in the experimental template

- .github/workflows/e2e.yml
Skip Vite E2E tests on the v3-maintenance branch, because we don't publish the Vite plugin from that branch
> Skip Vite E2E for v3 branch

- .changeset/mighty-lies-see.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/assets.ts
Fixes WC-3357.
Metafiles weren't being picked up when Wrangler was running in a different directory. This fixes that. Thanks for catching that, @petebacondarwin !
---
- Tests
> Fix metafiles in child directory

- .changeset/common-paws-invite.md
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
Right now, container configuration only works on the PUT script path, but this will be fixed in further API changes.
This change makes sure that when container configurations are included in wrangler, it will include the `containers` configuration in wrangler deploy. These changes break `wrangler cloudchamber apply` users, but as the product is in early-stages and private only for now, we consider these breaking changes worth doing. 
---
- Tests
> wrangler deploy: Add containers configuration to PUT script

- .changeset/nasty-bars-sniff.md
- packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Fixes #8511.
Sets `target` in `optimizeDeps.esbuildOptions` to `es2022`. This fixes a bug where the target for prebundled dependencies did not match the build target. This resulted in top-level await not being permitted in dependencies.
---
- Tests
> Set `target` in `optimizeDeps.esbuildOptions`

- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/websockets.ts
Fixes #000.
While investigating improving the WebSocket implementation, I discovered that Miniflare exports a `coupleWebSocket` function. This is similar to our existing implementation but covers some additional edge cases and improves the error handling.
---
- Tests
> Use `coupleWebSocket` function from Miniflare

- .github/pull_request_template.md
- tools/deployments/__tests__/validate-pr-description.test.ts
- tools/deployments/validate-pr-description.ts
Adds v3 back port to our pr checklist
---
- Tests
> chore: add v3 backport to PR checklist

- .github/workflows/c3-e2e.yml
Collapse C3 E2E jobs into a single job for both experimental & non-experimental variants. This should reduce CI contention by reducing the number of runners needed, and reduce CI overall time by removing the pnpm installation time for duplicate runners.
> Collapse C3 E2E jobs

- .changeset/rotten-monkeys-tan.md
- packages/unenv-preset/package.json
- packages/unenv-preset/src/runtime/node/crypto.ts
- pnpm-lock.yaml
Sync with recently implemented crypto APIs
The implementation was tested locally with the child PR.
We need to wait for wrangler to use the updated preset before we can merge the test PR.
---
- Tests
---
This is **part 1 of 2 in a stack** made with GitButler:
- <kbd>&nbsp;2&nbsp;</kbd> #8569 
- <kbd>&nbsp;1&nbsp;</kbd> #8568 👈
> Use the native implementation of crypto APIs

- .changeset/chilled-moons-enjoy.md
- packages/create-cloudflare/templates/hello-world-durable-object/js/src/index.js
- packages/create-cloudflare/templates/hello-world-durable-object/js/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-durable-object/ts/src/index.ts
- packages/create-cloudflare/templates/hello-world-durable-object/ts/wrangler.jsonc
Fixes STOR-4114.
Update the C3 Durable Objects example to use SQLite.
- Tests
> Update the C3 Durable Objects example to use SQLite

- .changeset/lemon-areas-tap.md
- packages/wrangler/src/__tests__/queues.test.ts
- packages/wrangler/src/queues/cli/commands/index.ts
- packages/wrangler/src/queues/cli/commands/purge.ts
- packages/wrangler/src/queues/client.ts
Fixes https://jira.cfdata.org/browse/MQ-851
Adds a new `purge` command to delete all messages in a Queue.
---
- Tests
> Add purge queue command

- .changeset/all-mugs-give.md
- fixtures/asset-config/html-handling.test.ts
- fixtures/asset-config/redirects.test.ts
- fixtures/asset-config/url-normalization.test.ts
- packages/workers-shared/asset-worker/src/analytics.ts
- packages/workers-shared/asset-worker/src/compatibility-flags.ts
- packages/workers-shared/asset-worker/src/configuration.ts
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/tests/compatibility-flags.test.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
- packages/workers-shared/utils/types.ts
Fixes WC-3321.
Implements SPA mode in asset-worker
---
- Tests
> asset-worker support for SPA mode

- .changeset/cold-baths-knock.md
- packages/unenv-preset/package.json
- packages/vite-plugin-cloudflare/package.json
- packages/vite-plugin-cloudflare/src/node-js-compat.ts
- pnpm-lock.yaml
Fixes #0000
This fixes an issue with the latest version of the unenv-preset and updates the vite plugin to use it.
---
- Tests
> vite-plugin: update unenv preset dependency

- .changeset/rude-socks-glow.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/deployment-bundle/entry.ts
> Improve the error messaging when the user provides neither an entry point nor an asset directory

- tools/e2e/runIndividualE2EFiles.ts
This should make it easier to see what is happening in CI.
> test: add console log "grouping" to Wrangler e2e tests

- .changeset/eighty-glasses-talk.md
- packages/vite-plugin-cloudflare/playground/additional-modules/__tests__/additional-modules.spec.ts
- packages/vite-plugin-cloudflare/playground/additional-modules/src/index.ts
- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
This was just a bit of fun while I was waiting for CI. It adds support for `.wasm?init` imports, as documented by Vite (https://vite.dev/guide/features.html#webassembly). Not sure if it's something we should actually include or not so happy to close if you feel it's unnecessary.
---
- Tests
> Add Wasm helper

- .changeset/warm-forks-visit.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/pipelines/cli/update.ts
Allow `wrangler pipelines update <pipelineName> --transform-worker none` to remove transformations from a Pipeline.
Fixes https://jira.cfdata.org/browse/PIPE-232
---
- Tests
> Allow users to specify `none` to remove transformation

- .changeset/swift-beers-battle.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation/index.ts
Adds support for `wrangler types` command to generate the necessary types for Workers Pipelines.
Fixes https://jira.cfdata.org/browse/PIPE-181
---
- Tests
> Support wrangler types for Pipelines

- packages/wrangler/e2e/dev.test.ts
This was reverted in https://github.com/cloudflare/workers-sdk/pull/8252. Recreating to figure out what went wrong.
---
- Tests
----
Tested locally by running:
```
CLOUDFLARE_ACCOUNT_ID=8d783f274e1f82dc46744c297b015a2f CLOUDFLARE_API_TOKEN="foobar" WRANGLER="node --no-warnings $PWD/packages/wrangler/bin/wrangler.js" WRANGLER_IMPORT="$PWD/packages/wrangler/wrangler-dist/cli.js" pnpm --filter wrangler run test:e2e -- packages/wrangler/e2e/dev.test.ts
```
I removed some of the other tests in dev.test.ts, thankfully the above seems to run it without getting caught on other tests that are failing so it allowed me to verify these work locally.
> Adds Python print e2e test again.

- packages/wrangler/src/__tests__/d1/execute.test.ts
- packages/wrangler/src/__tests__/d1/info.test.ts
- packages/wrangler/src/__tests__/d1/list.test.ts
- packages/wrangler/src/__tests__/d1/timeTravel.test.ts
- packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
- packages/wrangler/src/__tests__/tail.test.ts
The wrangler banner is normally [mocked](https://github.com/cloudflare/workers-sdk/blob/82a89371250a1ec3e56fa5a518c685d362bde0ad/packages/wrangler/src/__tests__/vitest.setup.ts#L86) in tests so it isn't included in the console output that we check. However, we do want to test for the _absence_ of the banner when a particular command has a 'json' mode where the output should be json only.
This PR adds/updates tests for d1 and tail commands that have a 'json' option.
There may be some commands that have an _implicit_ guarantee that they output json without a separate flag, but I don't have a good way of identifying those - `secret list` now has tests for it but there may be others?
This should ensure issues like #7487 and #8101 don't happen again 😅 
---
- Tests
- Wrangler E2E Tests CI Job …
> chore: include banner in output of tests for commands with json/pretty mode

- packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-process-populated-env.ts
In all the vite-plugin playground apps we need to set the `inspectorPort` option to `false` otherwise the CI doesn't seem to properly cope, one (from https://github.com/cloudflare/workers-sdk/pull/8489) is missing (simply because https://github.com/cloudflare/workers-sdk/pull/8441 got merged when out of date with `main`) causing the following issue:
https://github.com/cloudflare/workers-sdk/actions/runs/13974580123/job/39124949648?pr=8596
This PR addresses that
---
- Tests
> chore: add missing `inspectorPort: false` in vite-plugin playground app

- packages/vite-plugin-cloudflare/e2e/README.md
- packages/vite-plugin-cloudflare/e2e/basic.test.ts
- packages/vite-plugin-cloudflare/e2e/fixtures/basic/package.json
- packages/vite-plugin-cloudflare/e2e/global-setup.ts
- packages/vite-plugin-cloudflare/e2e/helpers.ts
This is a revert of https://github.com/cloudflare/workers-sdk/pull/8436, because it's consistently causing Vite E2E tests to time out in CI (not locally though)
> Revert Vite E2E

- .changeset/thick-bars-sing.md
- fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/src/index.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/src/workerB.util.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/src/workerC.util.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/src/workerD.util.ts
- fixtures/workers-with-assets-and-service-bindings/workerB-with-default-export/src/index.ts
- fixtures/workers-with-assets-and-service-bindings/workerC-with-default-entrypoint/src/index.ts
- fixtures/workers-with-assets-and-service-bindings/workerD-with-named-entrypoint/src/index.ts
- packages/miniflare/src/workers/assets/rpc-proxy.worker.ts
This PR simplifies the `RpcProxyWorker` even further, and adds further fixture tests that confirm that promise pipelining, nested functions, and property accessors work as expected. Yay!!
Fixes DEVX-1643
---
- Tests
> fix(miniflare): Simplify `RpcProxyWorker` and add more fixture tests

- .changeset/soft-buses-sniff.md
- packages/wrangler/e2e/secrets-store.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/secrets-store.test.ts
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/secrets-store/client.ts
- packages/wrangler/src/secrets-store/commands.ts
- packages/wrangler/src/secrets-store/index.ts
- packages/wrangler/src/user/user.ts
This PR introduces the Secrets Store API to the Wrangler CLI. It adds commands namespaces for `wrangler secrets-store` with sub-namespaces of `wrangler secrets-store store` and `wrangler secrets-store secret` for acting upon store and secret resources respectively. The intent here is to be able to fully manage the stores+secrets for an account's Secret Store, from wrangler. 
Changes:
- Added `wrangler secrets-store store list|create|delete` commands
- Added `wrangler secrets-store secret list|get|create|update|delete|duplicate` commands
- All commands default to local dev, need to pass `--remote` for acting on remote
Todo:
- Will implement local dev version of commands (specifically create/delete secret), in a subsequent change
- Fix e2e test runner, what do I need to do for API tokens to …
> feat(wrangler): Add Secrets Store support

- packages/vite-plugin-cloudflare/playground/vitest.config.e2e.ts
> chore: remove unused `~utils` alias in vite-plugin-cloudflare playground

- .changeset/eight-cars-fall.md
- packages/miniflare/src/workers/core/entry.worker.ts
- packages/vite-plugin-cloudflare/playground/spa-with-api/__tests__/spa-with-api.spec.ts
- packages/vite-plugin-cloudflare/playground/spa-with-api/api/index.ts
- packages/vite-plugin-cloudflare/playground/spa-with-api/wrangler.toml
- packages/vite-plugin-cloudflare/src/asset-workers/asset-worker.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/vite-plugin-cloudflare/src/plugin-config.ts
- packages/vite-plugin-cloudflare/src/utils.ts
- packages/wrangler/src/assets.ts
Fixes WC-3319.
Implements `vite dev` support for Workers Assets' new SPA mode.
---
- Tests
> vite dev support for SPA mode

- .changeset/orange-beans-run.md
- fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
- fixtures/workers-with-assets-only/tests/index.test.ts
- fixtures/workers-with-assets-run-worker-first/tests/index.test.ts
- fixtures/workers-with-assets-spa/tests/index.test.ts
- fixtures/workers-with-assets/tests/index.test.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/assets/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/vitest-pool-workers/src/pool/config.ts
- packages/wrangler/e2e/assets-multiworker.test.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/core/register-yargs-command.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/experimental-flags.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/versions/upload.ts
> feat: Graduate experimental RPC support for Workers with assets in local dev

- packages/miniflare/src/plugins/core/index.ts
Fixes WC-000.
Can be merged after https://github.com/cloudflare/workers-sdk/pull/8618#pullrequestreview-2705925096 lands.
---
- Tests
> Remove assets compat flag gate

- .github/workflows/c3-e2e.yml
This disables C3 E2E tests for bun. Unfortunately, these have proved to be fairly flaky, and in particular have recently started throwing transient errors related to package installation e.g. https://github.com/cloudflare/workers-sdk/actions/runs/13999803837/job/39203491072?pr=8613:
```
Resolving dependencies
error: ConnectionRefused downloading tarball tar@6.2.1
error: ConnectionRefused downloading tarball chownr@2.0.0
error: ConnectionRefused downloading tarball mkdirp@1.0.4
error: ConnectionRefused downloading tarball yallist@4.0.0
error: ConnectionRefused downloading tarball minipass@5.0.0
error: ConnectionRefused downloading tarball minizlib@2.1.2
error: ConnectionRefused downloading tarball minipass@3.3.6
error: ConnectionRefused downloading tarball is-fullwidth-code-point@4.0.0 …
```
> Disable C3 Bun tests

- .changeset/legal-camels-dance.md
- packages/wrangler/src/__tests__/pages/dev.test.ts
- packages/wrangler/src/pages/dev.ts
if users run `wrangler pages dev --env=my-env` they currently get an error saying to use `--branch` instead, the `--branch` option however only applies to `wrangler pages deploy`, so this error message can easily confuse users, the changes here update the error message to simply state that `--env` is not available for local development
Just something very minor I noticed and though I could quickly address
---
- Tests
> Amend `pages dev` error message when an environment is requested

- .changeset/early-maps-make.md
- packages/workers-shared/utils/configuration/parseHeaders.ts
- packages/workers-shared/utils/configuration/parseRedirects.ts
- packages/workers-shared/utils/tests/parseHeaders.valid.test.ts
- packages/workers-shared/utils/tests/parseRedirects.valid.test.ts
Fixes WC-3325.
Allows customizing the limits of Workers Assets metafiles.
---
- Tests
> Support customizing metafile limits

- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/src/index.ts
This has no effect on the deployed Worker in production, but is useful in local development for ensuring that the full request is available when overriding the functions.
---
- Tests
> refactor: pass the request through the asset-worker `exists` and `getByETag` functions

- .changeset/fluffy-icons-pump.md
- packages/create-cloudflare/templates/hello-world-with-assets/js/public/index.html
- packages/create-cloudflare/templates/hello-world-with-assets/py/public/index.html
- packages/create-cloudflare/templates/hello-world-with-assets/ts/public/index.html
Fixes N/A
This improves the default HTML shipped with C3 templates to:
- use `type=button` on the button since it's not a form submission and browsers default to `type=submit`
- use the [`output`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/output) element which is arguably more semantically correct as a result of a user action than the `div`
---
- Tests
> fix(create-cloudflare): improve html semantics from c3 init

- packages/wrangler/src/__tests__/match-tag.test.ts
- packages/wrangler/src/environment-variables/misc-variables.ts
- packages/wrangler/src/match-tag.ts
Fixes CUSTESC-49792
---
- Tests
> Provide more informative error messages for Workers CI tag validation

- .changeset/shy-singers-kiss.md
- packages/vite-plugin-cloudflare/playground/config-changes/__tests__/config-changes.spec.ts
- packages/vite-plugin-cloudflare/playground/config-changes/package.json
- packages/vite-plugin-cloudflare/playground/config-changes/src/index.ts
- packages/vite-plugin-cloudflare/playground/config-changes/tsconfig.json
- packages/vite-plugin-cloudflare/playground/config-changes/tsconfig.node.json
- packages/vite-plugin-cloudflare/playground/config-changes/tsconfig.worker.json
- packages/vite-plugin-cloudflare/playground/config-changes/turbo.json
- packages/vite-plugin-cloudflare/playground/config-changes/vite.config.ts
- packages/vite-plugin-cloudflare/playground/config-changes/wrangler.json
- packages/vite-plugin-cloudflare/playground/external-workflows/__tests__/workflows.spec.ts
- packages/vite-plugin-cloudflare/playground/partyserver/package.json
- packages/vite-plugin-cloudflare/playground/partyserver/src/App.tsx
- packages/vite-plugin-cloudflare/playground/partyserver/src/tailwind.css
- packages/vite-plugin-cloudflare/playground/partyserver/vite.config.ts
- packages/vite-plugin-cloudflare/playground/vitest.config.e2e.ts
- packages/vite-plugin-cloudflare/playground/workflows/__tests__/workflows.spec.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/vite-plugin-cloudflare/src/utils.ts
- packages/vite-plugin-cloudflare/src/websockets.ts
- packages/vite-plugin-cloudflare/src/workers-configs.ts
- pnpm-lock.yaml
Fixes #8646.
This fixes a bug where updating config files would crash the dev server. This occurred because the previous Miniflare instance was not disposed before creating a new one. This would lead to a port collision because of the `inspectorPort` introduced by the new debugging features.
The relevant Vite code, showing that the new server is created before closing the old one is here - https://github.com/vitejs/vite/blob/262b5ec7ae4981208339b7b87fefbd3dd8465851/packages/vite/src/node/server/index.ts#L1187-L1206
I've also added a test for reporting config errors on Worker config changes
---
- Tests
> Fix dev server crashing on config changes

- .changeset/green-donuts-run.md
- fixtures/nodejs-hybrid-app/src/index.ts
- packages/wrangler/package.json
- pnpm-lock.yaml
Use the workerd native implementation of `createSecureContext` and `checkServerIdentity` from `node:tls`. The functions have been implemented in `cloudflare/workerd#3754`.
/cc @anonrig @thomasgauvin 
---
- Tests
> Bump `@cloudflare/unenv-preset` to 2.3.1

- .changeset/chatty-rockets-call.md
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/src/utils/print-bindings.ts
> fix: include asset binding when printing binding summary

- CODEOWNERS
There are two KV groups and wrong team is the code owner, fixing it, then other group can be removed.
- Tests
> Fix Workers KV ownership

- .changeset/loud-worlds-ask.md
- packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts
- packages/vite-plugin-cloudflare/playground/node-compat/package.json
- packages/vite-plugin-cloudflare/playground/node-compat/tsconfig.worker.json
- packages/vite-plugin-cloudflare/playground/node-compat/vite.config.worker-warnings.ts
- packages/vite-plugin-cloudflare/playground/node-compat/worker-warnings/index.ts
- packages/vite-plugin-cloudflare/playground/node-compat/worker-warnings/wrangler.toml
- packages/vite-plugin-cloudflare/playground/package.json
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/node-js-compat.ts
- pnpm-lock.yaml
Fixes #8136 and [DEVX-1755](https://jira.cfdata.org/browse/DEVX-1755)
If `nodejs_compat` is missing in Wrangler config:
```
> vite dev -c vite.config.worker-process.ts
Using vars defined in worker-process/.dev.vars
VITE v6.1.0  ready in 1213 ms
➜  Local:   http://localhost:5173/
➜  Network: use --host to expose
➜  press h + enter to show help
Using vars defined in worker-process/.dev.vars
4:55:44 PM [vite] (worker) Re-optimizing dependencies because vite config has changed
4:55:44 PM [vite] server restarted.
Unexpected Node.js imports for environment "worker". Do you need to enable the "nodejs_compat" compatibility flag?
Refer to https://developers.cloudflare.com/workers/runtime-apis/nodejs/ for more details.
- "node:assert" imported from "worker-process/index.ts"
```
and then without …
> vite-plugin: show warning if the user has forgotten to turn on nodejs_compat 

- .changeset/violet-ravens-draw.md
- packages/miniflare/src/plugins/core/modules.ts
- packages/miniflare/src/runtime/config/workerd.ts
- packages/miniflare/test/fixtures/modules/index.node.cjs
- packages/miniflare/test/plugins/core/modules.spec.ts
- packages/vitest-pool-workers/src/pool/index.ts
- packages/vitest-pool-workers/src/pool/module-fallback.ts
- packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/module-collection.ts
- packages/wrangler/src/deployment-bundle/worker.ts
Fixes n/a
This will soon be removed in `workerd`, and was never fully supported for deployed Workers. As such, it's being entirely removed.
---
- Tests
> Remove `NodeJSCompatModule`

- .changeset/lemon-dragons-glow.md
- packages/wrangler/src/pages/deployments.ts
Fixes N/A
Long time ago I raised [this issue](https://community.cloudflare.com/t/wrangler-delete-deployment/610630) on the forum, but it didn't really get any attention, so I decided to do it myself :smile: 
Basically, with this change here I could at least have a reliable API call chained after `pages deployments list` command. In the current implementation of it I'd need to rely on the `Build` URL but it is neither reliable (there is a TODO to use a url shortener) nor easy to use
I do intend to implement `pages deployments delete <deployment-id>` later, if you agree to have it
---
- Tests
> [wrangler] Wrangler pages deployments list - added ID to output

- .changeset/lemon-dragons-glow.md
- packages/wrangler/src/pages/deployments.ts
Reverts cloudflare/workers-sdk#8641. Accidentally merged minor changes, when only patches are allowed
> Revert "[wrangler] Wrangler pages deployments list - added ID to output"

- .changeset/common-baths-fold.md
- packages/vite-plugin-cloudflare/playground/worker/__tests__/worker.spec.ts
- packages/vite-plugin-cloudflare/playground/worker/src/index.ts
- packages/vite-plugin-cloudflare/src/utils.ts
Fixes #8684.
This sets the `x-forwarded-host` header to the original host in requests. It fixes a bug where libraries such as Clerk would redirect to the workerd host rather than the Vite host.
---
- Tests
> Add X-Forwarded-Host header to requests

- .changeset/metal-shoes-cut.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/common/c3.ts
- packages/create-cloudflare/templates/hello-world-durable-object/c3.ts
- packages/create-cloudflare/templates/hello-world-with-assets/c3.ts
- packages/create-cloudflare/templates/openapi/c3.ts
- packages/create-cloudflare/templates/pre-existing/c3.ts
- packages/create-cloudflare/templates/queues/c3.ts
- packages/create-cloudflare/templates/scheduled/c3.ts
Pretty minor, this simply removes this unneeded category with no entries in C3's experimental mode:
---
- Tests
> remove `Application Starter` option in C3 experimental menu

- .changeset/tangy-camels-write.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/core/teams.d.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/r2/catalog.ts
- packages/wrangler/src/r2/helpers.ts
Fixes IGLOO-10.
This change adds the wrangler commands to manage R2 buckets as iceberg warehouses. The commands would enable users to enable/disable buckets as warehouses as well as fetch and list warehouses by calling the R2 data catalog.
CR-1140509
---
- Tests
> [R2 Data Catalog] Add wrangler commands for R2 Data Catalog

- packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
> chore: fix vite-plugin e2es using non existent `viteCommand` function

- .changeset/five-camels-cheer.md
- .github/workflows/e2e.yml
- packages/vite-plugin-cloudflare/e2e/README.md
- packages/vite-plugin-cloudflare/e2e/basic.test.ts
- packages/vite-plugin-cloudflare/e2e/dynamic.test.ts
- packages/vite-plugin-cloudflare/e2e/fixtures/basic/wrangler.toml
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/package.json
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/src/dynamic.ts
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/src/index.ts
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/tsconfig.json
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/tsconfig.node.json
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/tsconfig.worker.json
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/vite.config.ts
- packages/vite-plugin-cloudflare/e2e/fixtures/dynamic/wrangler.toml
- packages/vite-plugin-cloudflare/e2e/global-setup.ts
- packages/vite-plugin-cloudflare/e2e/helpers.ts
- packages/vite-plugin-cloudflare/e2e/tsconfig.json
- packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
- packages/vite-plugin-cloudflare/playground/node-compat/__tests__/worker-warnings/warnings.spec.ts
- packages/vite-plugin-cloudflare/playground/prisma/__tests__/prisma.spec.ts
- packages/vite-plugin-cloudflare/playground/prisma/__tests__/serve.ts
- packages/vite-plugin-cloudflare/playground/vitest-setup.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/node-js-compat.ts
- packages/vite-plugin-cloudflare/turbo.json
Fixes [DEVX-1769](https://jira.cfdata.org/browse/DEVX-1769)
Previously, these polyfills were only optimized on demand when Vite became aware of them.
This was either because Vite was able to find an import to a polyfill when statically analysing the import tree of the entry-point,
or when a polyfilled module was dynamically imported as part of a executing code to handle a request.
In the second case, the optimizing of the dynamically imported dependency causes a reload of the Vite server, which can break applications that are holding state in modules during the request.
This is the case of most React type frameworks, in particular React Router.
Now, we pre-optimize all the possible Node.js polyfills when the server starts before the first request is handled.
---
- Tests
- Wrangler E2E …
> Ensure that Node.js polyfills are pre-optimized before the first request

- .changeset/hip-parents-shave.md
- .changeset/warm-mammals-invent.md
- packages/vite-plugin-cloudflare/README.md
- packages/vite-plugin-cloudflare/package.json
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/vite-plugin-cloudflare/src/plugin-config.ts
- packages/vite-plugin-cloudflare/src/utils.ts
- pnpm-lock.yaml
Fixes #8670
this change updates the plugin so that if an inspector port is not specified and the
default inspector port (9229) is not available it keeps looking for other available
port instead of crashing
this also makes sure that users can specify `0` to use a random port
---
- Tests
> [vite-plugin] improve inspector port handling

- .changeset/shiny-ghosts-flash.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/wrangler_external_do.jsonc
- fixtures/get-platform-proxy/wrangler_internal_do.jsonc
- packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/deployment-bundle/entry.ts
This is a manually opened PR to backport patch changes from https://github.com/cloudflare/workers-sdk/pull/8697 to Wrangler v3
> V3 Backport #8697: prevent `getPlatformProxy` from crashing with internal DOs

- .changeset/wide-ideas-work.md
- packages/create-cloudflare/e2e-tests/frameworks/framework-test-config.ts
- packages/create-cloudflare/templates/hono/pages/c3.ts
- packages/create-cloudflare/templates/hono/pages/templates/wrangler.jsonc
This snuck through because the preview tests used hono's vite plugin which doesn't care what's in the wrangler config.
---
- Tests
> fix: remove stray main field in Hono Pages template

- .changeset/tangy-badgers-grow.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/catalog.ts
- packages/wrangler/src/r2/helpers.ts
Fixes IGLOO-40.
Summary of changes: 
1. Update the routes for the r2 catalog enable and disable commands
2. Include the warehouse name in the enable and get command responses
3. Handle the "catalog never enabled" case for the disable command
4. Remove the irreversible action message from the disable command
5. Handling of the "catalog never enabled" case suggests the use of the enable command
6. Minor formatting changes.
[CR-1142756](https://jira.cfdata.org/browse/CR-1142756)
---
- Tests
> fix: General improvements for the R2 catalog commands

- packages/vite-plugin-cloudflare/e2e/invalid-worker-env-configs.test.ts
I've applied the following suggested change: https://github.com/cloudflare/workers-sdk/pull/8672#discussion_r2022420432 but forgot to update one instance in which this was being tested, for some reason it seems like we didn't catch that in https://github.com/cloudflare/workers-sdk/pull/8672 😓 
---
- Tests
> fix missing Vite capitalization in vite-pluging e2e test

- fixtures/workers-with-assets-and-service-bindings/tests/index.test.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/src/index.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/src/workerWS.util.ts
- fixtures/workers-with-assets-and-service-bindings/workerA/wrangler.toml
- fixtures/workers-with-assets-and-service-bindings/workerWS/public/busy-bee.html
- fixtures/workers-with-assets-and-service-bindings/workerWS/public/index.html
- fixtures/workers-with-assets-and-service-bindings/workerWS/src/index.ts
- fixtures/workers-with-assets-and-service-bindings/workerWS/wrangler.toml
Fixes n/a
Adds fixture tests for Workers + Assets and WebSockets
---
- Tests
> chore(fixtures): Add fixture tests for Workers + Assets and WebSockets

- .changeset/wet-memes-mix.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/pipelines/cli/create.ts
- packages/wrangler/src/pipelines/cli/update.ts
- packages/wrangler/src/pipelines/client.ts
Transforms are not publicly available yet so we are hiding this from the help output. Private beta users will still be able to provide this flag.
This commit also introduces a new flag `--shard-count` for power users to hand tune their pipeline.
Fixes https://jira.cfdata.org/browse/PIPE-241, https://jira.cfdata.org/browse/PIPE-242
---
- Tests
> Update flags for Pipelines create and update

- .changeset/easy-pens-lie.md
- packages/wrangler/src/__tests__/pages/secret.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/pages/secret/index.ts
- packages/wrangler/src/secret/index.ts
> fix: return actual error in wrangler secrets bulk

- .changeset/better-laws-follow.md
- packages/create-cloudflare/templates/astro/workers/templates/ts/wrangler.jsonc
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/src/__tests__/__snapshots__/kv.test.ts.snap
- packages/wrangler/src/__tests__/kv.local.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/r2.local.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/core/register-yargs-command.ts
- packages/wrangler/src/core/types.ts
- packages/wrangler/src/kv/index.ts
- packages/wrangler/src/r2/object.ts
- packages/wrangler/src/utils/is-local.ts
Added to KV and R2 for now.
skipping d1 since its commands haven't been refactored to use createCommand yet.
Not added to KV list or get commands, since they seem to implicitly expect the relevant values to be returned (e.g. printBanner = false)
replaces #8665 
---
- Tests
> Log whether a command is operating on a local or remote resource

- .changeset/old-guests-smile.md
- packages/vite-plugin-cloudflare/src/__tests__/fixtures/wrangler-with-fields-to-ignore.toml
- packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
- packages/vite-plugin-cloudflare/src/plugin-config.ts
- packages/vite-plugin-cloudflare/src/utils.ts
- packages/vite-plugin-cloudflare/src/workers-configs.ts
Fixes #000.
No longer warn if the user sets `upload_source_maps` in the Worker config.
---
- Tests
> No longer warn if the user sets `upload_source_maps` in the Worker config.

- .changeset/plain-lies-retire.md
- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
Fixes inspector port changes being logged on server restarts. An available inspector port is now found on the initial server start and reused across restarts.
---
- Tests
> Fix inspector port change being logged on server restarts

- .changeset/tricky-eagles-peel.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/catalog.ts
fix: Minor refactor in the R2 data catalog wrangler commands
---
- Tests
- [] TODO (before merge)
> fix: Minor refactor for the R2 catalog commands

- .changeset/bumpy-owls-fry.md
- packages/miniflare/package.json
- pnpm-lock.yaml
Upgrade `youch` to 3.3.4.
Currently Dependabot is alerting a vulnerable version of `cookie` `0.5.0`, which is required by `youch`. Bumping `youch` solves that.
---
- Tests
> Bump `youch` to 3.3.4

- .changeset/shiny-facts-cross.md
- packages/create-cloudflare/templates/react/workers/js/src/App.jsx
- packages/create-cloudflare/templates/react/workers/js/worker/index.js
- packages/create-cloudflare/templates/react/workers/js/wrangler.jsonc
- packages/create-cloudflare/templates/react/workers/ts/src/App.tsx
- packages/create-cloudflare/templates/react/workers/ts/tsconfig.worker.json
- packages/create-cloudflare/templates/react/workers/ts/worker/index.ts
- packages/create-cloudflare/templates/react/workers/ts/wrangler.jsonc
- packages/create-cloudflare/templates/vue/workers/js/server/index.js
- packages/create-cloudflare/templates/vue/workers/js/wrangler.jsonc
- packages/create-cloudflare/templates/vue/workers/ts/server/index.ts
- packages/create-cloudflare/templates/vue/workers/ts/wrangler.jsonc
just removes the fallback ASSETS binding use in the worker
---
- Tests
> 🫧  update for SPA mode in c3 templates

- .github/workflows/changesets.yml
- packages/create-cloudflare/package.json
- packages/wrangler/package.json
- packages/wrangler/scripts/bundle.ts
> Remove sourcemaps from NPM release

- .changeset/tall-donkeys-pull.md
- packages/create-cloudflare/templates/scheduled/ts/src/index.ts
Write a default fetch handler like the JS example: https://github.com/cloudflare/workers-sdk/edit/main/packages/create-cloudflare/templates/scheduled/js/src/index.js
Without it, `npm run start / dev` will point to a browser location that does not exist.
---
- Tests
> Write fetch handler so that `npm run start` works

- .changeset/sharp-bottles-agree.md
- packages/wrangler/src/__tests__/whoami.test.ts
- packages/wrangler/src/user/whoami.ts
This pull request adds a hint to let users know that specific API token permissions might not be granted when Wrangler can't retrieve membership roles. This is similar to the behavior in a case where Wrangler is unable to fetch a user's email.
- Tests
> add hint when no permission to show membership info

- .changeset/fine-cameras-nail.md
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/r2/catalog.ts
We're updating the backend service to use slashes in the catalog URI instead of underscores to separate account id and bucket name. This PR updates the frontend to match that.
- Tests
> IGLOO-45 replace underscore with slashes in catalog URI

- .changeset/sweet-doors-notice.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/inspector-proxy/inspector-proxy-controller.ts
- packages/miniflare/test/plugins/core/inspector-proxy/index.spec.ts
Currently if I use an `inspectorPort` in a miniflare instance and then try to change such
port via `setOptions` such change is not actually applied, this PR fixes that
---
- Tests
> [miniflare] fix: make sure that `miniflare#setOptions` allows the update of inspector ports

- packages/wrangler/e2e/types.test.ts
The type generation changed from using double quotes to single quotes.
> fix types Wrangler e2e test

- .changeset/vast-stars-dig.md
- .github/workflows/test-and-check.yml
- fixtures/vitest-pool-workers-examples/workflows/README.md
- fixtures/vitest-pool-workers-examples/workflows/src/env.d.ts
- fixtures/vitest-pool-workers-examples/workflows/src/index.ts
- fixtures/vitest-pool-workers-examples/workflows/src/tsconfig.json
- fixtures/vitest-pool-workers-examples/workflows/test/env.d.ts
- fixtures/vitest-pool-workers-examples/workflows/test/integration-self.test.ts
- fixtures/vitest-pool-workers-examples/workflows/test/tsconfig.json
- fixtures/vitest-pool-workers-examples/workflows/tsconfig.json
- fixtures/vitest-pool-workers-examples/workflows/vitest.config.ts
- fixtures/vitest-pool-workers-examples/workflows/wrangler.toml
- packages/vitest-pool-workers/src/pool/index.ts
- packages/vitest-pool-workers/src/pool/loopback.ts
- packages/vitest-pool-workers/src/worker/entrypoints.ts
Because `vitest-pool-workers` uses its runner worker as the entrypoint and not the user provided worker. The user provided worker is loaded AFAICT though eval (`vitest-pool-workers` enables eval) so we need, at startup time, to add the required entrypoints and make them dynamically call the user one.
Not only that, if you try to create a workflow instance it would throw a `isolated storage` error - I suspect that is this caused by engine still being active at the end of the test (since workflows are async, not in the request path, and might take undefinite time to complete).
In order to fix this, I've bypassed the isolated storage check for workflows internal DOs. I wonder if there might be collisions between test files if there are any concurrency regarding test files (aka `singleWorker` …
> fix: make vitest-pool-workers not crash with scripts that have Workflows

- .changeset/clever-squids-unite.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/angular/pages/c3.ts
- packages/create-cloudflare/templates/astro/pages/c3.ts
- packages/create-cloudflare/templates/docusaurus/pages/c3.ts
- packages/create-cloudflare/templates/gatsby/pages/c3.ts
- packages/create-cloudflare/templates/hono/pages/c3.ts
- packages/create-cloudflare/templates/next/pages/c3.ts
- packages/create-cloudflare/templates/nuxt/pages/c3.ts
- packages/create-cloudflare/templates/qwik/pages/c3.ts
- packages/create-cloudflare/templates/react/pages/c3.ts
- packages/create-cloudflare/templates/remix/pages/c3.ts
- packages/create-cloudflare/templates/svelte/pages/c3.ts
- packages/create-cloudflare/templates/vue/pages/c3.ts
Fixes [DEVX-1707](https://jira.cfdata.org/browse/DEVX-1707)
---
- Tests
> remove BETA label from Workers+Assets templates and hide Pages templates

- .changeset/tiny-ideas-nail.md
- packages/wrangler/src/__tests__/pages/pages.test.ts
- packages/wrangler/src/pages/build.ts
- packages/wrangler/src/pages/index.ts
- tools/deployments/__tests__/validate-pr-description.test.ts
- tools/deployments/validate-pr-description.ts
Fixes WC-000.
This command is already documented, so this just makes it show up for `wrangler pages --help`. It also deprecates the now long-since unused `--outfile` (in favor of `--outdir`, which can support unbundleable files such as Wasm).
The other (internal and undocumented) `wrangler pages functions ...` commands are hidden to prevent them from showing up for `wrangler pages functions --help`.
Edit: also accepts live docs URLs in the PR description.
---
- Tests
> Unhide 'wrangler pages functions build'

- .changeset/busy-chairs-happen.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/pipelines/cli/create.ts
- packages/wrangler/src/pipelines/cli/get.ts
- packages/wrangler/src/pipelines/cli/update.ts
- packages/wrangler/src/pipelines/index.ts
We are preparing for an open beta and cleaning some things up and improving the output of some of the commands. In short:
- Rename `wrangler pipelines show` to `wrangler pipelines get`
- Replace `--enable-worker-binding` and `--enable-http` with `--source worker` and `--source http` (or `--source http worker` for both)
- Remove `--file-template` and `--partition-template` flags from `wrangler pipelines create|update`
- Add pretty output for `wrangler pipelines get <pipeline>`. Existing output is available using `--format=json`.
Fixes https://jira.cfdata.org/browse/PIPE-248
---
- Tests
> Pipelines CLI Improvements

- .changeset/lemon-deers-speak.md
- packages/vitest-pool-workers/src/worker/index.ts
Checking for `/node_modules/vitest/` does not work with Yarn's pnpm linker, where the path is something like `node_modules/.store/vitest-virtual-ee893ec3ea/`
---
- Tests
> Fix `fromVitest` conditional

- .changeset/big-trees-drum.md
- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
Replace assertion in vite-plugin-cloudflare:nodejs-compat plugin transform hook with early return. This prevents an error from being logged when building with React Router and TailwindCSS.
---
- Tests
> Replace assertion in node-js compat transform hook with early return

- .github/dependabot.yml
This should make life a bit simpler on Mondays and also easier to land updates to workerd in a timely fashion
> chore: run dependabot updates outside of busy times

- .changeset/eleven-papayas-take.md
- fixtures/vitest-pool-workers-examples/workflows/src/index.ts
- packages/vitest-pool-workers/src/worker/entrypoints.ts
This goes way beyond me, but I noticed that I didn't use `patchAndRunWithHandlerContext` in `createWorkflowEntrypointWrapper` but other entrypoints did it - that seems to fix it.
However, I'm not really sure how does `ExecutionContext` relate to our custom `Console` mock. Probably the test runner (which is a worker AFAICT) uses `waitUntil` to write into vitest's stdout?
Fixes #8791 and WOR-605
---
- Tests
> fix: make console.logs not hang vitest-pool-workers when using workflows

- .changeset/common-worms-worry.md
- packages/miniflare/src/workers/kv/constants.ts
- packages/miniflare/src/workers/kv/namespace.worker.ts
- packages/miniflare/test/plugins/kv/index.spec.ts
Fixes #[[KV-1458](https://jira.cfdata.org/browse/KV-1458)].
Adding a small fix for existing errors and adding a ContentTooLarge Error that we did not have before.
---
- Tests
Previous PR: https://github.com/cloudflare/workers-sdk/pull/8623
> KV: get bulk - add content too long error

- CONTRIBUTING.md
Fixes N/A.
Update contributing guide with more detail about types of changes.
---
- Tests
> Update types of changes in contrib guide

- .github/workflows/open-v3-maintenance-prs.yml
> chore: open v3 backport PR only if the current PR targets main

- .changeset/breezy-cats-trade.md
- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/templates/hello-world-assets-only/c3.ts
- packages/create-cloudflare/templates/hello-world-with-assets/c3.ts
> rename c3 options

- .changeset/silver-comics-add.md
- .github/workflows/open-v3-maintenance-prs.yml
- tools/deployments/open-v3-pr.ts
> chore: re-run v3 backport on label changes

- .github/workflows/c3-e2e.yml
- .github/workflows/e2e.yml
- .github/workflows/test-and-check.yml
Adds support for the `every-os` label, to trigger tests runs on multiple operating systems when needed.
---
- Tests
> Add label to run on multiple OSs

- .changeset/nine-weeks-hug.md
Updated changeset as stated in the contributing guide:
> New stable features and new deprecation warnings for future breaking changes are considered 'minor' changes. These changes shouldn't break existing code, but the deprecation warnings should suggest alternate solutions to not trigger the warning.
> chore: update changeset

- .changeset/sour-islands-watch.md
- packages/miniflare/src/workers/core/entry.worker.ts
- packages/wrangler/e2e/dev.test.ts
Only log requests once (fixes regression in 4.9 where we started logging requests to the Wrangler dev server twice)
---
- Tests
> Fix multiple request logging

- .changeset/mean-badgers-battle.md
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/src/assets.ts
Some folks are confused about the "No files to upload. Proceeding with deployment..." message when deploying Workers with Assets, especially when lacking the context that wrangler is diffing the local files with the asset manifest and only uploading the changes. This PR disambiguates this messages to something hopefully more meaningful
Fixes DEVX-1572
---
- Tests
> fix(wrangler): Disambiguate the "No files to upload. Proceeding with deployment..." message

- .changeset/brave-gifts-occur.md
- packages/wrangler/src/__tests__/pages/deploy.test.ts
- packages/wrangler/src/deployment-bundle/esbuild-plugins/alias-external.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Fixes n/a.
Update esbuild version used in Wrangler v4 to avoid user from seeing the [security vulnerabilities](https://github.com/advisories/GHSA-67mh-4wv8-2f99) warning during npm install. (Note: Wrangler is not impacted as it is not using the serve feature.) 
---
- Tests
> Update wrangler esbuild version

- packages/wrangler/src/config/environment.ts
This PR fixes a small docs typo that I noticed while working with the Drizzle ORM's setup guide that points to the wrong URL for compatibility in the docstring
---
- Tests
> docs: fix worker compat URL in docstring

- .changeset/shy-cooks-flow.md
- packages/vitest-pool-workers/package.json
- packages/vitest-pool-workers/src/config/index.ts
- packages/vitest-pool-workers/src/pool/module-fallback.ts
- pnpm-lock.yaml
Fixes n/a
We were pre-bundling `chai` with esbuild to get around an issue with circular `require()`. This is now [fixed](https://github.com/cloudflare/workers-sdk/issues/5367) and so we can drop `esbuild` from the dependencies. Instead, we now pre-bundle `chai` with vite to reduce the number of modules workerd must parse at runtime as an optimization.
---
- Tests
> feat(vitest-pool-workers): pre bundle chai with vite instead of esbuild

- .github/workflows/open-v3-maintenance-prs.yml
- tools/deployments/open-v3-pr.ts
Fixes n/a
This makes sure no comment on the v3 backport status is added if the changeset is not a wrangler patch. I have tested it with a non wrangler patch changeset in https://github.com/cloudflare/workers-sdk/pull/8930/commits/d3d8710a057e9a0204d927f056beb0e1cd93488e (See [CI Job](https://github.com/cloudflare/workers-sdk/actions/runs/14444128966/job/40500683309)).
---
- Tests
> chore: comment on v3 backport status only if it has wrangler patch

- .github/workflows/e2e.yml
Our e2e tests can take a long time (I dont think? its a caching issue? I think we just have a lot of them) and sometimes the job times out.
Also, the vite plugin e2e tests occasionally get stuck so i've added a timeout for that. 
---
- Tests
> ci timeout in e2e tests

- .github/dependabot.yml
Fixes n/a.
It might be safer to run the e2e tests on every os upfront when we are bumping workerd version.
---
- Tests
> chore: run e2e on every os when updating workerd version

- .changeset/cute-carpets-sneeze.md
- fixtures/workers-with-assets-spa/tests/index.test.ts
- packages/miniflare/src/plugins/assets/index.ts
- packages/miniflare/src/workers/core/entry.worker.ts
- packages/workers-shared/asset-worker/src/configuration.ts
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/src/utils/headers.ts
- packages/workers-shared/router-worker/src/configuration.ts
- packages/workers-shared/utils/types.ts
Fixes WC-3442 and fixes #8798
Adds a log message when `Sec-Fetch-Mode: navigate`.
---
- Tests
> Add log message when 'sec-fetch-mode: navigate' is responsible for assets routing decision in 'wrangler dev'

- .changeset/solid-needles-deny.md
- packages/create-cloudflare/src/__tests__/templates.test.ts
- packages/create-cloudflare/src/helpers/__tests__/args.test.ts
- packages/create-cloudflare/src/helpers/args.ts
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/src/types.ts
create-cloudflare uses degit under the hood to clone template git repositories. degit will attempt to download a tar file of the HEAD of a repository if it is served up on one of several allow listed repository hosting services including GitHub. However, the tar support does not support templating from private repositories. To support that, we needed to create the ability to tell degit to use "git" mode to download the template using the user's git credentials.
---
- Tests
> Add --template-mode to create-cloudflare

- packages/create-cloudflare/e2e-tests/cli.test.ts
Fixes #8708.
Looks like the c3 e2e tests might have been missed in the original PR. This should fix the errors.
---
- Tests
> fix(create-cloudflare): update help test snapshot

- .changeset/cute-carpets-sneeze.md
Fixes #8887
`@cloudflare/workers-shared` is still in v0, so it should be a patch even though it is introducing a new feature.
---
- Tests
> chore: update changset

- .changeset/tough-friends-share.md
- packages/create-cloudflare/templates/next/workers/c3.ts
Need to be rebased on #8952 (which fixes the tests)
- Tests
> bump create-next-app to 15.3.0 for the Workers template

- .changeset/salty-ties-find.md
- packages/wrangler/src/__tests__/user.test.ts
- packages/wrangler/src/user/commands.ts
- packages/wrangler/src/user/user.ts
fix issue #5937 by providing option to user to pass ip for the temporary login server, enabling the use of wrangler login command in devcontainers
Fixes #5937.
I would also argue that the default should be '0.0.0.0' for the values, as it is temporary login server, available for a short period. Making DX a lot better than to add --ip '0.0.0.0' every time in devcontainers, but for now PR defaults to localhost as that was the default before.
---
- Tests
- V3 wrangler backport: not necessary because new feature
> feat: :sparkles: introduce ip param for wrangler login command, fixes [5937]

- packages/wrangler/e2e/cert.test.ts
- tools/e2e/common.ts
- tools/e2e/e2eCleanup.ts
Fixes n/a.
This make sure no stale certificates are left after running the e2e tests.
---
- Tests
> chore: cleanup e2e test certs

- .changeset/fancy-cobras-rhyme.md
- packages/create-cloudflare/templates/qwik/workers/c3.ts
Fixes [DEVX-1692](https://jira.cfdata.org/browse/DEVX-1692)
_headers and _redirects are now supported with Static Assets
---
- Tests
> fix(create-cloudflare): keep the default _headers and _redirects files in the qwik workers template

- .changeset/curly-groups-scream.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/core/services.ts
- packages/miniflare/src/runtime/config/workerd.ts
- packages/wrangler/e2e/multiworker-dev.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev/miniflare.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/8558
In `wrangler.toml` you can declare a service binding with props:
```
[[services]]
binding = "MY_SERVICE"
service = "some-worker"
props = { foo = 123, bar = 456 }
```
Unfortunately, it currently doesn't work when wrangler is running different workers in different processes, as `props` cannot be sent to a remote `workerd`. Fixing this would require `workerd` changes, but since we are moving away from the multi-process mode anyway, perhaps it's not worth it.
Note: I used Claude Code to find my way around the codebase. It wrote most of the PR. It was not able to figure out that changes were needed under `packages/miniflare`, and I myself had a pretty hard time figuring out where to edit.
---
- Tests
- Wrangler E2E Tests CI Job …
> Implement support for ctx.props.

- .changeset/cold-aliens-learn.md
- packages/wrangler/src/containers/containers.ts
Provide helpful error message when user lists containers but has none to list instead of an obscure error.
Fixes an error where a user doing:
`wrangler containers list` but had no containers would get an error message like:
"Cannot read properties of undefined..." 
Because the returned applications list was empty.
This adds checks for undefined/null/length 0 and provides a reasonable error message with a link to the containers dash which has pointers to 
---
- Tests
> Add undefined/null checks to containers list

- .changeset/old-ghosts-grin.md
- packages/create-cloudflare/src/templates.ts
remove `await` keywords in non-async function calls in `templates.ts` file
---
- Tests
> feat(create-cloudflare): remove `await` keywords in non-async function calls

- .changeset/fluffy-mice-attack.md
- packages/create-cloudflare/templates/react/workers/c3.ts
- packages/create-cloudflare/templates/react/workers/ts/tsconfig.worker.json
- remove the `await` keyword used when calling non-async function.
- update React workers template to fix type errors
---
- Tests
> feat(create-cloudflare): update react template to fix type errors

- .changeset/plenty-beans-enjoy.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/type-generation/index.ts
Manual backport PR of https://github.com/cloudflare/workers-sdk/pull/8990
> V3 backport[#8990]: Fix version metadata binding type in when generating env type

- .changeset/blue-suns-battle.md
- packages/workers-shared/asset-worker/src/index.ts
- packages/workers-shared/asset-worker/wrangler.toml
- packages/workers-shared/router-worker/wrangler.toml
Fixes n/a.
Adds tracing into asset-worker unstable methods so we can better measure/debug these.
---
- Tests
> Add Jaeger tracing to unstable asset-worker methods

- .changeset/eighty-knives-reply.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/upload.ts
Fixes WOR-637
This PR removes the open-beta disclaimer that is now outdated since Workflows is GA.
---
- Tests
> Removes open-beta disclaimer from workflows commands

- .github/workflows/check-v3-backport-status.yml
- tools/deployments/__tests__/check-v3-backport-status.test.ts
- tools/deployments/check-v3-backport-status.ts
Fixes #8962
After #8962 is merged, I have created #9046 to test the new workflow and realize the new job wasn't triggered which is likely because GitHub will run the workflow on the "base branch" of your pull request instead of the main branch. 
This fixes it by backporting the workflow to the `v3-maintenace` branch. 😅 
Tests:
1. [PR is not merged](https://github.com/cloudflare/workers-sdk/actions/runs/14705662684/job/41265419906?pr=9079) in #9079
2. [PR is merged](https://github.com/cloudflare/workers-sdk/actions/runs/14705782134/job/41265816062?pr=9080#step:4:12) in #9080
---
- Tests
> chore: add v3 maintenance workflow

- .github/workflows/check-v3-backport-status.yml
> chore: skip checking backport status on v3 version release

- .changeset/heavy-sides-shake.md
- packages/create-cloudflare/templates/next/workers/c3.ts
Changes in this PR:
- `@opennextjs/cloudflare` should be installed as a regular dep
- `@cloudflare/workers-types` is already installed and does not need to be explicitly installed (types should be generated soon).
- Tests
> Install `@opennextjs/cloudflare` as regular dependency

- .changeset/wild-boxes-invite.md
- fixtures/worker-app/src/index.js
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/runtime/config/workerd.ts
- packages/miniflare/test/index.spec.ts
- packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/dev-registry.test.ts
- packages/wrangler/e2e/multiworker-dev.test.ts
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/e2e/provision.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/__tests__/provision.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deployment-bundle/bindings.ts
- packages/wrangler/src/dev-registry/index.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/utils/print-bindings.ts
- packages/wrangler/src/versions/upload.ts
- pnpm-lock.yaml
This is a follow up to the work in `workerd` to support Tail Workers locally, and ensures that Tail Workers are supported in Miniflare. Additionally, they're supported in both `wrangler dev` modes (dev registry & single process).
This can be testing be adding a `[[tail_consumer]]` section to a worker's `wrangler.toml` file, and then adding a `tail()` handler to a second worker, and running them both locally.
---
- Tests
> Support Tail Workers in local dev

- .changeset/stupid-paws-slide.md
- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/__tests__/vectorize/vectorize.upsert.test.ts
- packages/wrangler/src/vectorize/common.ts
- packages/wrangler/src/vectorize/create.ts
- packages/wrangler/src/vectorize/deleteByIds.ts
- packages/wrangler/src/vectorize/getByIds.ts
- packages/wrangler/src/vectorize/insert.ts
- packages/wrangler/src/vectorize/query.ts
- packages/wrangler/src/vectorize/upsert.ts
This PR adds logic to validate input files for Vectorize inserts/upserts. Only valid file paths, with non-empty files would be accepted with this change. Since the validation check only checks the file metadata, and does not read/parse the file, it should have no impact on command performance/resource consumption.
Context: As of now, customers can supply invalid/empty files as part of the Vectorize insert/upsert commands in Wrangler. The Vectorize commands display an error while parsing the file, but then proceed with processing an invalid input file (the command then behaves like a no-op). This PR improves user experience by carrying out a validation check before parsing the file, returns an error message on finding an invalid file, and also returns early. 
---
- Tests
- Wrangler / Vite …
> fix: Validate input file for Vectorize inserts

- .changeset/kind-dolls-swim.md
- packages/create-cloudflare/templates/next/workers/templates/wrangler.jsonc
Fetching from the same worker (more generally a worker in the same zone) fails for deployed workers without this flag. Adding this flag makes sense when there is no origin server - probably we should consider adding it for all frameworks?
(note that same worker fetch works with wrangler dev)
Our current workaround is to create a service binding in [wrangler.jsonc](https://opennext.js.org/cloudflare/caching#:~:text=NEXT_TAG_CACHE_D1.%20The-,WORKER_SELF_REFERENCE,-service%20binding%20should) - this PR will allow to simplify the config.
Ref:
- https://github.com/cloudflare/workerd/blob/b85dbe26804b6a534e21c1d2df1cf3775645c0f2/src/workerd/io/compatibility-date.capnp#L476-L510
- https://github.com/cloudflare/cloudflare-docs/pull/22017
- …
> Add `global_fetch_strictly_public` to the Next template for workers

- packages/create-cloudflare/e2e-tests/workers.test.ts
Add tests for https://github.com/cloudflare/workers-sdk/pull/9035
Fixes n/a
- Tests
> chore: add tests for new python DO templates

- .changeset/soft-wasps-beg.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/test/plugins/core/index.spec.ts
Fixes #8415.
The current logic simply split the text content by `--BEGIN` which might end up with a comment block that hold no certs.
---
- Tests
> fix(miniflare): parse pem file with regex

- .changeset/eager-bobcats-agree.md
- packages/vite-plugin-cloudflare/playground/multi-worker/__tests__/multi-worker.spec.ts
- packages/vite-plugin-cloudflare/playground/multi-worker/package.json
- packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/find-additional-modules.test.ts
- packages/wrangler/src/__tests__/navigator-user-agent.test.ts
- packages/wrangler/src/api/startDevWorker/BundlerController.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/deployment-bundle/find-additional-modules.ts
- packages/wrangler/src/pages/functions/buildPlugin.ts
- packages/wrangler/src/pages/functions/buildWorker.ts
- packages/wrangler/src/paths.ts
Previously, if you added modules rules such as `**/*.js` or `**/*.json`, specified `no_bundle: true`, and the entry-point to the Worker was in the project root directory, Wrangler could include files that were not intended, such as `.wrangler/tmp/xxx.js` or the Wrangler config file itself. Now these files are automatically skipped when trying to find additional modules by searching the file tree.
Fixes #8940
Fixes https://github.com/cloudflare/workers-sdk/issues/8911
---
- Tests
> Do not include .wrangler and Wrangler config files in additional modules

- .changeset/violet-planets-march.md
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/core/register-yargs-command.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/experimental-flags.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/versions/upload.ts
- packages/wrangler/src/yargs-types.ts
Fixes [DEVX-1833](https://jira.cfdata.org/browse/DEVX-1833)
Introduction of the `--x-mixed-mode` experimental flag (currently no-op)
---
- Tests
> Add `x-mixed-mode` flag

- .changeset/red-planes-wash.md
- packages/vite-plugin-cloudflare/playground/multi-worker/__tests__/multi-worker.spec.ts
- packages/vite-plugin-cloudflare/playground/multi-worker/worker-a/wrangler.jsonc
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
In Vite, only connect the tail consumers that represent Workers that are defined in the Vite config. Warn that a tail will be omitted otherwise. This _differs from service bindings_ because tail consumers are "optional" in a sense, and shouldn't affect the runtime behaviour of a Worker. 
Fixes issues like https://github.com/getsentry/sentry-mcp/pull/134#issuecomment-2842683985
---
- Tests
> Don't crash on non-existent tails in Vite

- .changeset/young-trainers-do.md
- .github/actions/install-dependencies/action.yml
- .github/workflows/deploy-pages-previews.yml
- .github/workflows/e2e.yml
- .github/workflows/test-and-check.yml
- .github/workflows/test-old-node-error.yml
- fixtures/import-npm/package.json
- packages/miniflare/src/plugins/core/errors/callsite.ts
- packages/wrangler/bin/wrangler.js
- packages/wrangler/src/__tests__/ai.local.test.ts
- packages/wrangler/src/__tests__/test-old-node-version.js
- packages/wrangler/src/sourcemap.ts
- packages/wrangler/src/wrangler-banner.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
Following our [Node.js version support policy](https://developers.cloudflare.com/workers/wrangler/install-and-update/), Wrangler no longer supports running with Node.js 18 now that it's EOL. This PR updates workers-sdk to use `@types/node@20`, run CI against Node 20, and updates Wrangler to fail if run with Node 18.
---
- Tests
> Bump to Node.js 20

- .changeset/spicy-crews-give.md
- fixtures/mixed-mode-node-test/package.json
- fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
- fixtures/mixed-mode-node-test/tsconfig.json
- packages/wrangler/src/api/index.ts
- packages/wrangler/src/api/mixedMode/index.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/templates/mixedMode/proxyServerWorker.ts
- packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
- packages/wrangler/templates/mixedMode/proxyServerWorker/wrangler.jsonc
- pnpm-lock.yaml
Fixes https://jira.cfdata.org/browse/DEVX-1836
Add `experimental_startMixedModeSession` no-op utility
---
- Tests
[^1]: I considered adding some tests to make sure that the values returned by the utility are those that we expect, but I figured that the correctness of the returned value is already guaranteed by the utility's types so I didn't think that adding tests for the utility at this stage would really add any value here
> Add `experimental_startMixedModeSession` no-op utility

- .changeset/deep-symbols-fix.md
- packages/wrangler/src/api/startDevWorker/types.ts
Remove the outdated/inaccurate js-doc comment informing consumers of `unstable_startWorker` that the `entrypoint` value can contain the worker's contents directly:
---
- Tests
> fix: remove outdated js-doc comment for `unstable_startDevWorker`'s `entrypoint`

- .changeset/petite-bags-try.md
- pnpm-lock.yaml
- pnpm-workspace.yaml
Fixes #9078
The source-map handling was changed n 0.25.0 so that it didn't handle generated sources (from `--define` args).
```
WARNING Invalid source URL: first path segment in URL cannot contain colon[invalid-source-url]
.wrangler/tmp/pages-y2j4kS/5bn3vbipm4v.js.map:3:14:
      3 │   "sources": ["<define:__ROUTES__>", "../../../../../../../Users/pb...
╵               ~~~~~~~~~~~~~~~~~~~~~
```
This was fixed in 0.25.4 - https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0254
- Tests
> bump esbuild version to fix regression in 0.25.0

- .changeset/deep-symbols-fix.md
- packages/wrangler/src/api/startDevWorker/types.ts
v3 backport for https://github.com/cloudflare/workers-sdk/pull/9118
> V3 Backport [#9118]:  fix: remove outdated js-doc comment for unstable_startDevWorker's entrypoint

- .changeset/metal-clubs-vanish.md
- fixtures/start-worker-node-test/package.json
- fixtures/start-worker-node-test/src/config-errors.test.js
- fixtures/start-worker-node-test/tsconfig.json
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- pnpm-lock.yaml
Fixes https://jira.cfdata.org/browse/DEVX-1842
This PR makes sure that `unstable_startWorker` can throw configuration related errors when:
- the utility is called
- the worker's `setConfig` is called with the `throwErrors` argument set to `true`
additionally when an error is thrown when `unstable_startWorker` is called it makes sure
that the worker is properly disposed (since, given the fact that it is not returned
by the utility the utility's caller wouldn't have any way to dispose it themselves)
---
- Tests
> make that `unstable_startWorker` can correctly throw configuration errors

- .changeset/cold-emus-jog.md
- packages/vite-plugin-cloudflare/package.json
- packages/vite-plugin-cloudflare/playground/spa-with-api/__tests__/https/spa-with-api.spec.ts
- packages/vite-plugin-cloudflare/playground/spa-with-api/package.json
- packages/vite-plugin-cloudflare/playground/spa-with-api/tsconfig.node.json
- packages/vite-plugin-cloudflare/playground/spa-with-api/vite.config.https.ts
- packages/vite-plugin-cloudflare/playground/streaming/__tests__/base-tests.ts
- packages/vite-plugin-cloudflare/playground/streaming/__tests__/https/streaming.spec.ts
- packages/vite-plugin-cloudflare/playground/streaming/__tests__/streaming.spec.ts
- packages/vite-plugin-cloudflare/playground/streaming/package.json
- packages/vite-plugin-cloudflare/playground/streaming/src/index.ts
- packages/vite-plugin-cloudflare/playground/streaming/tsconfig.json
- packages/vite-plugin-cloudflare/playground/streaming/tsconfig.node.json
- packages/vite-plugin-cloudflare/playground/streaming/tsconfig.worker.json
- packages/vite-plugin-cloudflare/playground/streaming/turbo.json
- packages/vite-plugin-cloudflare/playground/streaming/vite.config.https.ts
- packages/vite-plugin-cloudflare/playground/streaming/vite.config.ts
- packages/vite-plugin-cloudflare/playground/streaming/wrangler.jsonc
- packages/vite-plugin-cloudflare/playground/vitest-setup.ts
- packages/vite-plugin-cloudflare/src/index.ts
- pnpm-lock.yaml
Fixes https://github.com/cloudflare/workers-sdk/issues/9000.
This adds support for HTTPS so that configuring [`server.https`](https://vite.dev/config/server-options#server-https) and/or [`preview.https`](https://vite.dev/config/preview-options#preview-https) in your Vite config now works as expected.
Vite uses HTTP/2 by default when HTTPS is enabled. This was previously broken with our plugin because Undici uses HTTP/1.1 and includes the `transfer-encoding: chunked` header for streamed responses. The presence of this header would cause the dev server to crash. The changes here detect if HTTP/2 is being used and, if so, remove the `transfer-encoding` header.
As part of this PR I've replaced `@hattip/adapter-node` with `@mjackson/node-fetch-server` as it has better compatibility with HTTP/2 …
> Support HTTPS and HTTP/2

- packages/vite-plugin-cloudflare/playground/streaming/package.json
- pnpm-lock.yaml
Fixes #000.
`@cloudflare/workers-types` dependency in new playground didn't match previously merged version update.
---
- Tests
> Fix workers-types version

- .changeset/khaki-plums-clap.md
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/type-generation/helpers.ts
- packages/wrangler/src/type-generation/index.ts
I created this based on some DMs with Cloudflare Team members. Apologies for not creating an issue or discussion.
If extra wrangler configs are provided to `wrangler types` as:
```
wrangler types --service-config path/to/worker-a/wrangler.toml --service-config path/to/worker-b/wrangler.toml
```
This will use those to find the type definitions for the bound service, matching on the service name where it exists.
I took inspiration from the wrangler dev command which already allows passing in multiple wrangler files to then determine the locations of the implementations of each of the bound services on Env.
and I took inspiration from the DurableObject binding code already in the type generation
Now my generated types have all the correct methods attached.
---
- Tests
- Wrangler / Vite E2E …
> wrangler types - Import correct types for bound services

- .changeset/yellow-rabbits-tap.md
- packages/wrangler/src/__tests__/d1/info.test.ts
- packages/wrangler/src/d1/info.ts
- packages/wrangler/src/d1/types.ts
Fixes CFSQL-1287.
Fix d1 info command showing read_replication: [object Object] in the table output, and also add a fallback to unexpected fields to be JSON serialized at least.
v3 backport for https://github.com/cloudflare/workers-sdk/pull/9161
---
- Tests
> V3 Backport [#9161]: Fix d1 info command showing read_replication: [object Object]

- .changeset/happy-avocados-peel.md
- fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
- packages/miniflare/src/plugins/browser-rendering/index.ts
- packages/miniflare/src/plugins/index.ts
- packages/miniflare/src/workers/shared/mixed-mode-client.worker.ts
- packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
Fixes [DEVX-1839](https://jira.cfdata.org/browse/DEVX-1839)
Followup to the Mixed Mode client work, add a Mixed Mode-only browser rendering plugin to Miniflare.
---
- Tests
> Hooke up Mixed Mode client to browser rendering

- packages/wrangler/src/__tests__/deploy.test.ts
Some versions of Node.js and OSes add `charset=utf-8` to File types and some strip this.
- Tests
> test: make asset deploy tests more resilient

- .changeset/lemon-pants-jam.md
- fixtures/pages-functions-app/functions/r2/create.ts
- fixtures/pages-functions-app/functions/r2/get.ts
- fixtures/pages-functions-app/package.json
- fixtures/pages-functions-app/tests/index.test.ts
- fixtures/pages-workerjs-directory/package.json
- fixtures/pages-workerjs-directory/public/_worker.js/index.js
- fixtures/pages-workerjs-directory/tests/index.test.ts
- packages/wrangler/e2e/__snapshots__/pages-dev.test.ts.snap
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/__tests__/config/configuration.pages.test.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/__tests__/helpers/generate-wrangler-config.ts
- packages/wrangler/src/__tests__/r2.local.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/type-generation.test.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/pages/dev.ts
- packages/wrangler/src/pipelines/cli/create.ts
- packages/wrangler/src/r2/bucket.ts
- packages/wrangler/src/r2/helpers.ts
Fixes #9148
Before this PR, bucket names were only validated when creating a bucket (via `wrangler r2 create bucket_name`)
This PR adds validation to:
- wrangler config
- object commands - when trying to put, get, delete an object
- pages dev CLI command
- pipeline config
---
- Tests
> fix(r2): validate bucket names

- .changeset/many-birds-enjoy.md
- packages/create-cloudflare/templates/next/workers/c3.ts
Bump next template to`@opennextjs/cloudflare@^1.0.2` - removing beta releases.
---
- Tests
- Wrangler V3 Backport
> Bump next template to`@opennextjs/cloudflare@^1.0.2`

- .changeset/stupid-files-jog.md
- packages/miniflare/src/plugins/core/proxy/fetch-sync.ts
This was causing running Miniflare in Bun tests to hang indefinitely.
Fixes https://github.com/oven-sh/bun/issues/16240
- Tests
> fix: start transferred MessagePort in fetch-sync worker

- .changeset/cyan-years-relate.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/workers/core/strip-cf-connecting-ip.worker.ts
- packages/miniflare/test/index.spec.ts
- packages/miniflare/turbo.json
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/src/dev/miniflare.ts
Fixes #7835, #7924
Strip the CF-Connecting-IP header from outbound requests.
~This cannot be effectively tested in CI because it interacts badly and in strange ways with bot management and various other protections.~ To test manually:
- Create a hello world worker (or use `fixtures/worker-ts`)
- Add `return fetch("https://www.cloudflare.com", request)` to the Worker
- Run `wrangler dev`
- With this PR, validate that the Cloudflare landing page is returned
- _Without_ this PR (`pnpx wrangler@latest dev`), validate that an error page is returned
---
- Tests
> Strip CF-Connecting-IP header from all outbound requests

- .changeset/old-trainers-camp.md
- fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
- packages/miniflare/src/plugins/ai/index.ts
- packages/miniflare/src/plugins/browser-rendering/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/shared/constants.ts
Continuation of [DEVX-1859](https://jira.cfdata.org/browse/DEVX-1859)
This PR adds support for service bindings to Miniflare's Mixed Mode—both with and without custom entrypoints. Currently only `.fetch()` calls are supported, rather than full JSRPC communication.
---
- Tests
> Support Mixed Mode Service Bindings in Miniflare

- packages/vite-plugin-cloudflare/e2e/helpers.ts
Changes the vite-plugin e2e tests so that they fail if there is a mismatch in a peer dependency.
This is to catch problems with the relationship between vite-plugin and unenv-preset.
> test: fail e2e test if peer dependencies are broken

- .changeset/funny-trees-drop.md
- packages/create-cloudflare/src/templates.ts
fixes the default for `typesPath` in c3 templates
This ensures `compilerOptions.types` in tsconfig is set correctly - previously this would not be able to find `worker-configuration.d.ts`.
---
- Tests
> fix default typesPath in c3 templates

- .changeset/public-cameras-thank.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/test/index.spec.ts
- packages/wrangler/src/__tests__/api/startDevWorker/startWorker.test.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/templates/strip-cf-connecting-ip-header.js
> fix: strips CF-Connecting-IP header within Wrangler

- .changeset/tricky-wolves-cry.md
- packages/miniflare/src/plugins/analytics-engine/index.ts
- packages/miniflare/src/workers/analytics-engine/analytics-engine.worker.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/utils/print-bindings.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/9254
Because AE was available before JSRPC, using JSRPC for it's local simulator causes failures for Workers with a compat date before the JSRPC flag was enabled. Shifting to a Wrapped binding should resolve this. 
Note: AE is still a no-op in local dev—this PR changes no functionality.
---
- Tests
> Move the AE simulator from JSRPC to a Wrapped binding

- .changeset/hip-grapes-lay.md
- packages/wrangler/e2e/dev-mixed-mode.test.ts
- packages/wrangler/src/api/mixedMode/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/utils.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
Fixes https://jira.cfdata.org/browse/DEVX-1853
The changes here make it so that the user can set `remote: true` to some of 
their bindings and such bindings will be run remotely via `startMixedModeSession`
when running `wrangler dev` on a single worker
---
- Tests
> allow wrangler dev to connect to remote mixed-mode bindings

- .changeset/tough-seals-whisper.md
- fixtures/mixed-mode-node-test/tests/startMixedModeSession.test.js
- packages/miniflare/src/plugins/dispatch-namespace/index.ts
- packages/miniflare/src/plugins/index.ts
- packages/miniflare/src/workers/dispatch-namespace/dispatch-namespace.worker.ts
- packages/miniflare/src/workers/shared/mixed-mode-client.worker.ts
- packages/wrangler/templates/mixedMode/proxyServerWorker/index.ts
Continuation of DEVX-1859
Support Dispatch Namespaces in Mixed Mode dev. These are _similar_ to service bindings, but have a synchronous `.get()` method that a user calls first to retrieve the `Fetcher`. As such, they've been special cased so that the `.get()` is implemented as a Wrapped Binding that attaches a special header encoding the `.get()` arguments. The Mixed Mode Server uses that to call `.get()` on the actual Dispatch Namespace binding when the `Fetcher` is used.
---
- Tests
> Support Mixed Mode Dispatch Namespaces

- .changeset/clear-beans-leave.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.ctx.test.ts
- packages/wrangler/src/api/integrations/platform/executionContext.ts
Fixes #9233
I don't think `props` can be meaningfully used with getPlatformProxy? So this just fixes the types issue. 
---
- Tests
> add no-op `ctx.props` to getPlatformProxy to fix types mismatch

- .changeset/public-cameras-thank.md
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/test/index.spec.ts
- packages/wrangler/src/__tests__/api/startDevWorker/startWorker.test.ts
- packages/wrangler/src/deployment-bundle/bundle.ts
- packages/wrangler/templates/strip-cf-connecting-ip-header.js
This is an automatically opened PR to backport patch changes from #9246 to Wrangler v3
> V3 Backport [#9246]: fix: strips CF-Connecting-IP header within Wrangler

- .changeset/social-carpets-start.md
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
Fixes n/a.
This adds a link to the docs in the wrangler config json schema. We don't have an entry in the docs for every individual config so I have only included those I found on https://developers.cloudflare.com/workers/wrangler/configuration
Suggested by @Ankcorn 
---
- Tests
> docs: include links to the docs in the wrangler config schema

- .github/workflows/prereleases.yml
I missed that in https://github.com/cloudflare/workers-sdk/pull/9275
It causes the workflow to error
---
- Tests
> fix the prerelases workflow

- tools/deployments/open-v3-pr.ts
> chore: backport changes to v3 with "v3-backport" branch prefix and label

- .changeset/great-berries-grow.md
- packages/wrangler/e2e/pages-dev.test.ts
- packages/wrangler/src/pages/dev.ts
This is an automatically opened PR to backport patch changes from #9257 to Wrangler v3
> V3 Backport [#9257]: Revert R2 bucket validation for  commands

- packages/wrangler/e2e/dev-mixed-mode.test.ts
This is fixing a windows e2e [failure](https://github.com/cloudflare/workers-sdk/actions/runs/15067356448/job/42355090555?pr=9278#step:5:304) we're seeing in the [VP PR](https://github.com/cloudflare/workers-sdk/pull/9278).
I am not sure why windows is behaving as it is and why this change is needed... if anyone has some suggestions/ideas on it I'm all ears 🙏 
---
- Tests
> fix wrangler mixed-mode windows e2e test failure

- tools/e2e/runIndividualE2EFiles.ts
The e2e tests flake quite often but then resolve on a second pass. 
This runs all the tests twice in each CI job run. The ones that pass will be cached and super fast.
> run Wrangler e2e ci twice to reduce flakes

- .changeset/shaky-planets-feel.md
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/__tests__/vitest.setup.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/triggers/deploy.ts
Fixes #9180
Previously if the array was empty it would just not touch the deployed schedules.
Providing either `triggers: { crons: undefined }` or no `triggers` property in your Wrangler configuration will continue to leave the deployed schedules untouched.
---
- Tests
> fix: setting triggers.crons:[] in Wrangler config should delete deployed cron schedules

- .changeset/six-rockets-show.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-upload-worker.ts
- packages/wrangler/src/__tests__/helpers/mock-workers-subdomain.ts
- packages/wrangler/src/utils/getScriptName.ts
> allow --name and --env args on wrangler deploy

- .changeset/shaky-planets-feel.md
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/metrics.test.ts
- packages/wrangler/src/__tests__/vitest.setup.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/triggers/deploy.ts
This is an automatically opened PR to backport patch changes from #9266 to Wrangler v3
> V3 Backport [#9266]: fix: setting triggers.crons:[] in Wrangler config should delete deployed cron schedules

- .changeset/dull-areas-invent.md
- packages/miniflare/src/plugins/core/index.ts
- packages/wrangler/e2e/dev-mixed-mode.test.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
Fixes https://jira.cfdata.org/browse/DEVX-1854
The changes here make it so that the user can set `remote: true` to some of 
their bindings and such bindings will be run remotely via `startMixedModeSession`
when running `wrangler dev` on a multiple workers
---
- Tests
> Wire up mixed-mode remote bindings for multi-worker `wrangler dev`

- .changeset/clear-beans-leave.md
- fixtures/get-platform-proxy/tests/get-platform-proxy.ctx.test.ts
- packages/wrangler/src/api/integrations/platform/executionContext.ts
This is an automatically opened PR to backport patch changes from #9234 to Wrangler v3
> V3 Backport [#9234]: add no-op  to getPlatformProxy to fix types mismatch

- .changeset/grumpy-baboons-post.md
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
Users want to specify automated or manual rollouts on their container applications.
---
- Tests
> containers: allow users to specify the kind of container rollout they want

- .changeset/curvy-hairs-attend.md
- packages/wrangler/src/__tests__/containers/delete.test.ts
- packages/wrangler/src/containers/containers.ts
Fixes issue where `wrangler containers delete` didn't show a proper error message when the API failed.
---
- Tests
> wrangler containers: Delete should have better error handling

- .github/workflows/run-ci-for-external-forks.yml
> chore: run ci for external forks by commit sha

- .changeset/neat-jokes-prove.md
- packages/vite-plugin-cloudflare/playground/additional-modules/__tests__/additional-modules.spec.ts
- packages/vite-plugin-cloudflare/playground/additional-modules/src/index.ts
- packages/vite-plugin-cloudflare/playground/additional-modules/src/modules/text__example__2.txt
- packages/vite-plugin-cloudflare/src/additional-modules.ts
- packages/vite-plugin-cloudflare/src/shared.ts
There's a regex used to detect if certain files (wasm, .bin, .txt, .html) are being imported at runtime. The current regex looks like this:
```ts
const ADDITIONAL_MODULE_PATTERN = `__CLOUDFLARE_MODULE__(${ADDITIONAL_MODULE_TYPES.join("|")})__(.*?)__`;
```
This means if there are files with `__`s in them, those `__`s will get matched first, rather than the final `__` in the module pattern being matched on.
Add a `$` to the end of the regex so, to anchor to the end of the string.
`pnpm` stores files for packages in locations like this (note the `__`s), which uncovered this.
```
/path/to/project/node_modules/.pnpm/@prisma+client@6.8.2_prisma@6.8.2_typescript@5.8.3__typescript@5.8.3/node_modules/@prisma/client/runtime/query_engine_bg.sqlite.wasm
```
Adding the `$` turned out to break the …
> fix(vite-plugin): Support `__` in additional module IDs

- fixtures/workers-with-assets-static-routing/package.json
- fixtures/workers-with-assets-static-routing/spa-assets/_routes.json
- fixtures/workers-with-assets-static-routing/spa-assets/index.html
- fixtures/workers-with-assets-static-routing/spa.wrangler.jsonc
- fixtures/workers-with-assets-static-routing/src/index.ts
- fixtures/workers-with-assets-static-routing/tests/index.test.ts
- pnpm-lock.yaml
Tests that the behavior for both browser navigations (observed via
the 'Sec-Fetch-Mode: navigate' header) and non-browser navigations is
the same when static routing (via _routes.json) is present.
> Update fixture to test for Sec-Fetch-Mode behavior

- .changeset/tasty-hoops-own.md
- packages/workers-shared/asset-worker/src/configuration.ts
- packages/workers-shared/asset-worker/src/handler.ts
- packages/workers-shared/asset-worker/src/utils/rules-engine.ts
- packages/workers-shared/asset-worker/tests/handler.test.ts
- packages/workers-shared/asset-worker/tests/rules-engine.test.ts
- packages/workers-shared/router-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/configuration.ts
- packages/workers-shared/router-worker/src/index.ts
- packages/workers-shared/router-worker/tests/index.test.ts
- packages/workers-shared/utils/types.ts
For WC-3583
Adds support for static routing (i.e. \_routes.json) to Workers Assets
Implements the proposal noted here https://github.com/cloudflare/workers-sdk/discussions/9143
In brief: when static routing is present for a Worker with assets, routing via those static rules takes precedence. When a request is evaluated in the Router Worker, the request path is first compared to the "exclude" rules. If any match, the request is forwarded directly to the Asset Worker. If instead any "include" rules match, the request is forwarded directly to the User Worker. If neither match (or static routing was not provided), the existing behavior takes over.
As part of this explicit routing, when static routing is present, the check against "Sec-Fetch-Mode: navigate" (to guess if this should serve an …
> Add support for static routing (i.e. \_routes.json) to Workers Assets

- .changeset/shy-beans-warn.md
- fixtures/vitest-pool-workers-examples/basics-integration-auxiliary/vitest.config.ts
- packages/vitest-pool-workers/src/pool/index.ts
It does this by adding the `nodejs_compat_v2` flag (if missing) and removing `no_nodejs_compat_v2` flag (if found).
This does mean that the Vitest tests are running with a slightly different environment to production, but this has always been the case in other ways.
Fixes #8988
---
- Tests
> fix the Vitest integration to support Workers where Node.js compatibility is only v1 in production

- .changeset/violet-hats-guess.md
- packages/create-cloudflare/templates/hello-world-assets-only/templates/public/index.html
- packages/create-cloudflare/templates/hello-world-assets-only/templates/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/public/index.html
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/js/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/public/index.html
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/public/index.html
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/ts/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-with-assets/js/public/index.html
- packages/create-cloudflare/templates/hello-world-with-assets/js/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-with-assets/py/public/index.html
- packages/create-cloudflare/templates/hello-world-with-assets/py/wrangler.jsonc
- packages/create-cloudflare/templates/hello-world-with-assets/ts/public/index.html
- packages/create-cloudflare/templates/hello-world-with-assets/ts/wrangler.jsonc
> c3: add extra information about asset serving to hello-world templates

- .changeset/yummy-dolls-rescue.md
- packages/wrangler/src/__tests__/workflows.test.ts
- packages/wrangler/src/workflows/commands/instances/describe.ts
Fixes WOR-290
For convenience reasons, we default to the latest instance on the `wrangler instances describe <WORKFLOW_NAME>` command. The `id` field becomes optional.
- Tests
> Show latest instance by default

- .changeset/silver-bats-brush.md
- packages/miniflare/src/plugins/kv/index.ts
- packages/miniflare/src/plugins/secret-store/index.ts
- packages/wrangler/e2e/dev-with-resources.test.ts
Fixes #9006.
We were relying on the KV plugin to setup the object and storage service for the internal KV namespaced used by the local sercets store binding. However, this creates an issue when the users have both a KV namespace and secret binding defined with each creating a storage service sharing the same name while having a different persist path.
This decouples kv plugin from the sercets store plugin by copying the implementation in the kv bindings with the service named customzied for the secret store plugin.
---
- Tests
> fix(miniflare): decouple KV plugin from Secrets Store plugin to avoid service name conflicts

- packages/wrangler/e2e/pages-dev.test.ts
Trying to address some e2e flakiness we've been experiencing
---
- Tests
> Try to address e2e Windows flakiness

- .changeset/warm-dingos-lay.md
- fixtures/vitest-pool-workers-examples/multiple-workers/api-service/wrangler.jsonc
- fixtures/vitest-pool-workers-examples/multiple-workers/vitest.config.ts
- packages/vitest-pool-workers/src/pool/config.ts
Fixes #9343 
Apply https://github.com/cloudflare/workers-sdk/pull/9115 to the Vitest integration. This is a bit hacky—once the dev registry is landed and stable in Miniflare I expect we can inject a not found external service for this. cc @edmundhung 
---
- Tests
> Don't crash Vitest when started with a non-existent tail consumer

- .changeset/blue-streets-thank.md
- .changeset/twenty-cats-clap.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/cache/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/d1/index.ts
- packages/miniflare/src/plugins/do/index.ts
- packages/miniflare/src/plugins/kv/index.ts
- packages/miniflare/src/plugins/r2/index.ts
- packages/miniflare/src/plugins/secret-store/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/miniflare/src/plugins/workflows/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/kv/helpers.ts
- packages/wrangler/src/r2/helpers.ts
- packages/wrangler/src/secrets-store/commands.ts
Fixes [DEVX-1828](https://jira.cfdata.org/browse/DEVX-1828)
This introduces a `defaultPersistRoot` setting that, when provided, is used as the base directory for any plugin (i.e. `path.join(defaultPersistRoot, pluginName)`) whose persist option is `undefined` or `true`. Explicit string values for a plugin’s persist path are still honored.
This removes the need for both Wrangler and the Vite plugin to set individual persist options as long as all the miniflare plugins continue to derive the persist path using the `getPersistPath` helper. This will not break existing users as well as the result paths match current settings on both Wrangler / Vite plugin.
Example:
```tsx
// Without `defaultPersistRoot` / Before this change:
new Miniflare({
kvPersist: undefined,       // → "/(tmp)/kv" …
```
> feat: introduce defaultPersistRoot option

- .changeset/yummy-pillows-send.md
- packages/miniflare/README.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/constants.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/core/services.ts
- packages/miniflare/src/plugins/images/index.ts
- packages/miniflare/src/workers/core/constants.ts
- packages/miniflare/test/index.spec.ts
Fixes #000.
Adds support for Node.js style custom handlers for service bindings and outbound services. This makes it easier to integrate Miniflare with existing Node.js middleware and libraries as `req` and `res` objects can be used directly.
```js
new Miniflare({
serviceBindings: {
CUSTOM: {
node: (req, res) => {
res.end(`Hello world`);
},
},
},
});
```
Note: I initially tried implementing this with Claude but the code it produced was quite hacky and confusing so I removed it and started again.
---
- Tests
> Support Node.js style custom handlers for service bindings and outbound services

- packages/miniflare/src/plugins/core/index.ts
Fixes #000.
Fix for changes introduced in https://github.com/cloudflare/workers-sdk/pull/9376. The `ORIGINAL_URL` header isn't needed for custom Node services and leads to unexpected behaviour if it is unintentionally sent back into a Worker.
---
- Tests
> Remove ORIGINAL_URL header from custom Node service

- .changeset/dull-plants-act.md
- .changeset/hot-tips-do.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/shared/log.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
Fixes #000.
With the changes introduced in #9335, the Vite plugin no longer filters `Read on http` etc. logged by Miniflare as the string contains additional characters for colour encoding:
https://github.com/cloudflare/workers-sdk/blob/d9d937ab6f2868271dde5a8da625773085eaec85/packages/miniflare/src/index.ts#L1628
We now explicitly opt out of Miniflare request logging in dev and have modified the filtering in preview.
---
- Tests
> Prevent leaking Miniflare server logs

- packages/miniflare/package.json
- packages/miniflare/test/plugins/email/index.spec.ts
- packages/miniflare/test/test-shared/asserts.ts
This test has failed a couple of times. I think it is either that the binding log hasn't arrived in time, or that the logs are a bit out of order. This change should resolve both of those issues.
> Miniflare: reduce email test flakes

- .changeset/small-toes-give.md
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/utils/print-bindings.ts
Followup to #9335 to improve the display when the terminal is small enough to require wrapping. Additionally, correctly label Vectorive bindings as `not supported`/`remote` depending on the flags provided.
---
- Tests
> Improve wrapped bindings UI

- packages/vite-plugin-cloudflare/e2e/basic.test.ts
- packages/vite-plugin-cloudflare/e2e/dynamic.test.ts
- packages/vite-plugin-cloudflare/e2e/helpers.ts
- packages/vite-plugin-cloudflare/e2e/invalid-worker-env-configs.test.ts
- packages/vite-plugin-cloudflare/e2e/mixed-mode.test.ts
- packages/vite-plugin-cloudflare/e2e/wrangler-configs-validation.test.ts
Fixes the e2e windows failures that have been introduced by https://github.com/cloudflare/workers-sdk/pull/9308
---
- Tests
> Fix Vite plugin e2e windows failures

- packages/wrangler/e2e/dev-mixed-mode.test.ts
- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- packages/wrangler/e2e/seed-files/mixed-mode-workers/local-and-remote-service-bindings.js
- packages/wrangler/e2e/seed-files/mixed-mode-workers/local-service-binding-and-remote-ai.js
- packages/wrangler/e2e/seed-files/mixed-mode-workers/simple-service-binding.js
- packages/wrangler/e2e/wrangler-mixed-mode-resources.test.ts
This PR:
- adds an e2e reload test that I missed in https://github.com/cloudflare/workers-sdk/pull/9231
- removes the e2e dependency from DevProd Testing deployed workers (final part of https://jira.cfdata.org/browse/DEVX-1902)
- (minor) removes an extra unnecessary `await`
Each change is made in its own commit 🙂 
---
- Tests
> improve wrangler dev mixed mode tests

- .changeset/wise-rules-march.md
- packages/miniflare/package.json
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/miniflare/src/plugins/do/index.ts
- packages/miniflare/src/shared/dev-registry.ts
- packages/miniflare/src/shared/external-service.ts
- packages/miniflare/test/dev-registry.spec.ts
- packages/miniflare/test/test-shared/asserts.ts
- pnpm-lock.yaml
Fixes [DEVX-1829](https://jira.cfdata.org/browse/DEVX-1829)
This PR introduces two new Miniflare options to streamline auto-service discovery via the Dev Registry with backward compatibility with the Wrangler implementation:
- `unsafeDevRegistryPath` (`string`): Filesystem path to the Dev Registry directory
- `unsafeDevRegistryDurableObjectProxy` (`boolean`): When enabled, exposes internal Durable Objects to other Dev sessions and allows Workers to connect to external Durable Objects
The implementation of the Miniflare Dev Registry is different from the Wrangler implementation. Instead of restarting the Workers runtime with the config updated based on the worker definition in the registry, this solution will setup a proxy in the loopback server to resolve the address of the external …
> feat(miniflare): add dev registry support

- .changeset/five-ladybugs-sell.md
- .changeset/huge-bats-itch.md
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/analytics-engine/index.ts
- packages/miniflare/src/plugins/browser-rendering/index.ts
- packages/miniflare/src/plugins/dispatch-namespace/index.ts
- packages/miniflare/src/plugins/email/index.ts
- packages/miniflare/src/plugins/ratelimit/index.ts
- packages/miniflare/src/plugins/shared/index.ts
- packages/miniflare/src/plugins/vectorize/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/wrangler/e2e/dev-mixed-mode.test.ts
- packages/wrangler/e2e/wrangler-mixed-mode-resources.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/utils/print-bindings.ts
Fixes DEVX-1879
Implement `remote: true` behaviour & tests for:
- Images
- AI (already partially implemented)
- Vectorize
- Browser
- Dispatch Namespaces
Claude 🤖 helped a bit, but had a tendency to see a test failure and then go off in completely the wrong direction (skipping the test, deleting warnings/errors)
---
- Tests
> Support additional mixed mode resources in Wrangler

- .changeset/mean-news-sell.md
- .changeset/mean-news-throw.md
- packages/vite-plugin-cloudflare/src/__tests__/get-worker-config.spec.ts
- packages/vite-plugin-cloudflare/src/deploy-config.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/plugin-config.ts
- packages/vite-plugin-cloudflare/src/workers-configs.ts
- packages/wrangler/src/config/index.ts
> fix: remove unnecessary remote warnings for mixed mode in the vite plugin

- packages/wrangler/e2e/vitest.config.mts
- packages/wrangler/package.json
I couldn't get Windows to expand the environment variable passed to the Vitest runner; tried various approaches including cross-env and cross-env-shell, in various different places and combinations.
This approach here appears to be robust across all the OSes and is quite simple and straightforward.
> test: fix environment variable expansion of Wrangler e2e tests to work on Windows

- packages/vite-plugin-cloudflare/e2e/basic.test.ts
We disabled these because they seemed to be failing (a lot?) on Windows. But I have run them numerous time locally now and they pass every time.
The mixed mode ones are still disabled though.
Fixes DEVX-1748
---
- Tests
> test: re-enable the Vite plugin basic e2e tests  on Windows

- .changeset/beige-llamas-punch.md
- packages/miniflare/src/workers/core/devalue.ts
- packages/miniflare/test/workers/core/serialize.spec.ts
- packages/vitest-pool-workers/test/filtering.test.ts
add custom serializer for `RegExp` object.
vitest can filter test suites that contain non-ascii chars in its name.
```ts
test("test suite that contains 日本語", ()=>{
expect(1).toBe(1)
})
```
```
npx vitest -t '日本語' # test suites can be filtered by non-ascii strings
```
but with `vitest-pool-workers`, errors are reported:
```
TypeError: Cannot convert argument to a ByteString because the character at index 1404 has a value of 21336 which is greater than 255.
❯ webidl.converters.ByteString ../node_modules/undici/lib/fetch/webidl.js:431:13
❯ Object.record<ByteString, ByteString> ../node_modules/undici/lib/fetch/webidl.js:281:28
❯ webidl.converters.HeadersInit ../node_modules/undici/lib/fetch/headers.js:579:63
❯ Object.RequestInit ../node_modules/undici/lib/fetch/webidl.js:370:17
❯ new Request …
```
> [miniflare] custom serialization for RegExp object

- .changeset/solid-sides-join.md
- fixtures/nodejs-hybrid-app/src/index.ts
- packages/unenv-preset/src/runtime/node/crypto.ts
While investigating bundle size, I noticed that we were using the constants from unenv (>2kB) while they are available in workerd.
Ref:
- [unenv](https://github.com/unjs/unenv/blob/main/src/runtime/node/internal/crypto/constants.ts)
- [workerd](https://github.com/cloudflare/workerd/blob/9329b49451d9fb1822839c5b9687aa078e2b825e/src/node/crypto.ts#L228)
I did check that all the values from unenv are available in workerd.
The test will test unenv until the preset is released and used by workerd and vite at which point it will test the new code path. 
---
- Tests
> [unenv/preset] Use crypto.constants from workerd

- .changeset/empty-shirts-judge.md
- packages/wrangler/src/__tests__/cloudchamber/build.test.ts
- packages/wrangler/src/__tests__/cloudchamber/utils.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/cloudchamber/build.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/cloudchamber/deploy.ts
- packages/wrangler/src/config/environment.ts
Fixes #CC-5270
When building container images during docker build, we'd want to ensure the current docker image can be run under the current account. This enforces an useful check that improves DX without having to be denied during application creation with the specific image.
There is also a fix for stuck container builds in some cases where we were not inheriting the right stdio flags for the node spawn.
---
- Tests
> Consider disk limits when building containers

- .changeset/modern-memes-appear.md
- packages/wrangler/e2e/start-worker-mixed-mode.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
Fixes https://jira.cfdata.org/browse/DEVX-1958
This PR adds an `experimentalMixedMode` dev option to `unstable_startWorker` so that developers
can programmatically start a mixed mode session using startWorker, for more details please see the
changeset
---
- Tests
> add `experimentalMixedMode` dev option to `unstable_startWorker`

- .changeset/quick-snails-follow.md
- packages/create-cloudflare/templates/astro/pages/c3.ts
- packages/create-cloudflare/templates/astro/workers/c3.ts
The Astro cloudflare adaptor requires image processing to be marked with "cloudflare" strategy for it to work with yarn.
- Tests
> c3: use "cloudflare" image processing in astro projects

- fixtures/container-app/package.json
- fixtures/container-app/tests/index.test.ts
- fixtures/container-app/wrangler.enable-containers.jsonc
- fixtures/container-app/wrangler.ignore-containers.jsonc
- fixtures/container-app/wrangler.jsonc
- fixtures/container-app/wrangler.no-containers.jsonc
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/containers/index.ts
- packages/miniflare/src/plugins/containers/service/index.ts
- packages/miniflare/src/plugins/index.ts
- packages/wrangler/src/__tests__/config-validation-pages.test.ts
- packages/wrangler/src/__tests__/config/configuration.pages.test.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/api/dev.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/config/config.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/pages/dev.ts
passes in dockerPath, set by an env var
adds --enable-containers
adds dev.enable_containers in wrangler config
---
- Tests
> add dev.enable_containers and docker_path to miniflare/wrangler

- .changeset/famous-candies-start.md
- .changeset/lemon-laws-mate.md
- packages/miniflare/src/plugins/index.ts
- packages/miniflare/src/plugins/mtls/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/wrangler/e2e/cert.test.ts
- packages/wrangler/e2e/helpers/cert.ts
- packages/wrangler/e2e/miniflare-mixed-mode-resources.test.ts
- packages/wrangler/e2e/seed-files/mixed-mode-workers/mtls.js
- packages/wrangler/src/api/mixedMode/index.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/cli.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/dev/miniflare.ts
- packages/wrangler/src/utils/print-bindings.ts
Fixes https://jira.cfdata.org/browse/DEVX-1900
This PR is adding mTLS support to mixed mode.
As part of this the PR is also adding a `workerName` option to the `startMixedModeSession` API since when starting
the remote preview with an mTLS binding we would normally get the following error:
```
Workers with mTLS bindings need to be deployed before doing edge preview
``` 
having the option to pass the worker's name to `startMixedModeSession` allows us to make the server proxy worker behave like the actual user's worker thus enabling mTLS usage for it (in case the user has already deployed the worker)
---
- Tests
> add mTLS mixed mode support

- packages/vite-plugin-cloudflare/playground/package.json
I think that the only vite-plugin playground tests needing to run sequentially are the build
ones (because of `.wrangler/deploy/config.json`) so I think we can just as well run the dev ones in parallel
to save time
(PS: my only small concern is prebundling since the `node_modules/.vite` directory is still shared across different
variants, but I don't think we ever encountered any issue with that)
---
- Tests
> chore: app option to run the vite-plugin playground serve tests in parallel

- .github/workflows/c3-e2e.yml
- fixtures/node-app-pages/package.json
- fixtures/pages-d1-shim/package.json
- fixtures/pages-dev-proxy-with-script/package.json
- fixtures/pages-functions-app/package.json
- fixtures/pages-functions-wasm-app/package.json
- fixtures/pages-functions-with-config-file-app/package.json
- fixtures/pages-functions-with-routes-app/package.json
- fixtures/pages-nodejs-v2-compat/package.json
- fixtures/pages-plugin-mounted-on-root-app/package.json
- fixtures/pages-simple-assets/package.json
- fixtures/pages-workerjs-and-functions-app/package.json
- fixtures/pages-workerjs-app/package.json
- fixtures/pages-workerjs-directory/package.json
- fixtures/pages-workerjs-wasm-app/package.json
- fixtures/pages-workerjs-with-config-file-app/package.json
- fixtures/pages-workerjs-with-routes-app/package.json
- package.json
- packages/kv-asset-handler/package.json
- packages/miniflare/package.json
- packages/workers-shared/package.json
- packages/workflows-shared/package.json
- packages/wrangler/package.json
Reverts cloudflare/workers-sdk#9451. This was causing C3 E2E failures for React Router on Node.js 20.19.2
> Revert "chore: update node versions in various places"

- packages/wrangler/e2e/deployments.test.ts
Adds e2e tests for run_worker_first static routes.
- Tests
> test: add test cases for run_worker_first routes behaviour

- .changeset/shy-cups-float.md
- packages/vite-plugin-cloudflare/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
`@cloudflare/unenv-preset@2.3.3` pulls `node:crypto` constants from workerd instead of `unenv` (size optimization).
See https://github.com/cloudflare/workers-sdk/blob/main/packages/unenv-preset/CHANGELOG.md#233
---
- Tests
> Bump `@cloudflare/unenv-preset` to 2.3.3

- .changeset/true-cities-try.md
- fixtures/start-worker-node-test/src/config-errors.test.js
- packages/wrangler/e2e/startWorker.test.ts
- packages/wrangler/src/__tests__/api/startDevWorker/LocalRuntimeController.test.ts
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/api/mixedMode/index.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/ProxyController.ts
- packages/wrangler/src/api/startDevWorker/events.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/dev/hotkeys.ts
Fixes https://jira.cfdata.org/browse/DEVX-1861
Allows `startWorker` to accept `inspector: false` to disable the inspector, this can be useful
when callers do not want/need to have an inspector server.
One example of this is `startMixedModeSession` which calls `startWorker` but it not need an
inspector server associated to the worker and prior to these changes it needed to set a random port
for the inspector in order to avoid port collisions.
---
- Tests
> allow `startWorker` to accept `false` as an `inspector` option (to disable the inspector server)

- .changeset/odd-queens-enjoy.md
- packages/vite-plugin-cloudflare/playground/static-mpa/__tests__/static-mpa.spec.ts
- packages/vite-plugin-cloudflare/playground/static-mpa/public-html.html
- packages/vite-plugin-cloudflare/playground/static-mpa/public/public-html.html
- packages/vite-plugin-cloudflare/src/asset-workers/asset-worker.ts
- packages/vite-plugin-cloudflare/src/constants.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/vite-plugin-cloudflare/src/utils.ts
Fixes #9362.
Enable HTML handling for HTML files in the public directory.
HTML files in the public directory are prioritized over those at the root. This is consistent with Vite's internal behaviour, which places the `servePublicMiddleware` first. 
---
- Tests
> Enable HTML handling for HTML files in the public directory

- packages/miniflare/src/plugins/containers/service/index.ts
- packages/wrangler/e2e/containers.dev.test.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/config/environment.ts
we will recommend exposing in dockerfile instead of wrangler config so dev_exposed_ports is unnecessary.
also technically you don't have to call getTCPPort so you don't _have_ to expose ports.
---
- Tests
> warn instead of erroring if no exposed ports. and remove unused dev_exposed_ports

- packages/wrangler/e2e/helpers/e2e-wrangler-test.ts
- tools/e2e/__tests__/common.test.ts
- tools/e2e/common.ts
The d1 e2e tests sometimes timeout but also regularly have the following error/warning:
```
wrangler:test:e2e: [wrangler-smoke-QSaF1q] X [ERROR] Couldn't find DB with name 'e12af046-17a4-49a6-90c5-b33d5f09c633'
```
This is because we were passing the id rather than the name to the d1 delete command.
- Tests
> test: correctly delete test d1 databases

- .changeset/some-cloths-move.md
- .changeset/spotty-worlds-rest.md
- packages/wrangler/src/__tests__/config/findWranglerConfig.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/__tests__/versions/secrets/bulk.test.ts
- packages/wrangler/src/__tests__/versions/secrets/delete.test.ts
- packages/wrangler/src/__tests__/versions/secrets/put.test.ts
- packages/wrangler/src/__tests__/versions/secrets/utils.ts
- packages/wrangler/src/__tests__/versions/versions.deploy.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/config/config-helpers.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/core/register-yargs-command.ts
- packages/wrangler/src/core/types.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/secret/index.ts
- packages/wrangler/src/triggers/index.ts
- packages/wrangler/src/versions/deploy.ts
- packages/wrangler/src/versions/secrets/bulk.ts
- packages/wrangler/src/versions/secrets/delete.ts
- packages/wrangler/src/versions/secrets/put.ts
- packages/wrangler/src/versions/upload.ts
Fixes https://jira.cfdata.org/browse/DEVX-1785.
add warning about env not specified to potentially risky wrangler commands (for more details check the changeset)
---
- Tests
[^1]: The main issue is that this change is built upon the changes made in https://github.com/cloudflare/workers-sdk/pull/8966 (where `createCommand` is being introduced for the various commands) which is not backported, so potentially a different solution would need to be implemented for this in order to do a v3 backport
> add warning about env not specified to potentially risky wrangler commands

- .changeset/some-cloths-move.md
> remove todo comment left in changelog by mistake

- .changeset/thick-ways-visit.md
- packages/wrangler/src/cloudchamber/common.ts
This PR backports the changes introduced by #9628
> V3 backport [#9628]: Remove "Cloudchamber" from user facing error messages

- packages/wrangler/src/__tests__/cloudchamber/build.test.ts
Fixes a test for cc buildAndMaybePush that was failing because runDockerCmd was being called twice.
- Tests
> Correctly mock out getDockerImageDigest for testing buildAndMaybePush

- .changeset/nasty-cameras-poke.md
- packages/containers-shared/package.json
- packages/containers-shared/src/client/models/SchedulingPolicy.ts
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
- packages/wrangler/src/config/environment.ts
Makes default scheduling_policy the default
---
- Tests
> containers: Default scheduling policy should be the default

- .changeset/eleven-fans-smoke.md
- packages/workers-shared/router-worker/src/analytics.ts
- packages/workers-shared/router-worker/src/worker.ts
- packages/workers-shared/router-worker/tests/index.test.ts
Addresses https://github.com/opennextjs/opennextjs-cloudflare/security/advisories/GHSA-rvpw-p7vw-wj3m
This has already been applied in production, this commit keeps the repository in sync.
Images loaded via the /_next/image?url=<some remote image> were vulnerable to SSRF, and particularly if the user loaded the image in a new tab (instead of forcing the browser to treat it as an image). Thus, if request didn't indicate that the browser was going to treat the resource as an image (via the 'Sec-Fetch-Dest: image' header), we block the request when it doesn't return image content.
Fixes WC-3704.
---
- Tests
> Block requests vulnerable to opennext vulnerability

- .changeset/purple-tools-change.md
- packages/unenv-preset/build.config.ts
- packages/unenv-preset/package.json
- packages/unenv-preset/src/preset.ts
- pnpm-lock.yaml
Reverts cloudflare/workers-sdk#9243 because it breaks some CI checks: https://github.com/cloudflare/workers-sdk/actions/runs/15739024501/job/44359340641?pr=9658#step:4:697
> Revert "Migrate from unbuild to obuild"

- packages/vitest-pool-workers/test/bindings.test.ts
Fixes [DEVX-1775](https://jira.cfdata.org/browse/DEVX-1775)
This adds an example smoke test to verify if the local binding works in vitest-pool-workers
---
- Tests
> chore: test hello world binding support in vitest-pool-workers

- .github/workflows/c3-e2e.yml
e2e tests are run on every OS if both the `e2e` and `every-os` labels are set. The same is not true atm for C3 e2e tests. This PR fixes that.
Fixes n/a
---
- Tests
> chore: Run C3 e2e tests on every OS only if both `every-os` and `c3-e2e` labels are applied

- .changeset/better-rings-heal.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/versions/upload.ts
Currently `wrangler deploy --x-remote-bindings` shows incorrect warnings regarding `experimental_remote` fields:
The changes here are addressing this
---
- Tests
> fix: ensure that wrangler deploy and version upload don't override the remote-bindings flag

- .changeset/cuddly-sites-doubt.md
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
Prior to this the dialog was getting printed but auto-confirmed to yes which is confusing to users.
- Tests
> Remove confirmation dialog for cloudchamber apply when not interactive

- fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
Skip the `vitest` fixture for remote bindings if no credentials are available (i.e. on forks)
> Skip authed fixture on forks

- packages/create-cloudflare/e2e-tests/cli.test.ts
- packages/create-cloudflare/e2e-tests/workers.test.ts
Skipping in yarn due to node version resolution conflicts
The Openapi C3 template depends on `chanfana`, which has a dependency on `yargs-parser`. The latest chanfana version (`2.8.1` at the time of this writting) has a dep on `yargs-parser@22` which requires a node version of `20.19.0` or higher. Our CI is currently using node version `20.11.1`. We currently can't bump the CI node version as other tests will fail, therefore skipping for now until we can properly fix
Fixes n/a
---
- Tests
> Temporarily skip Openapi C3 e2e tests

- .changeset/sad-drinks-relate.md
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/__tests__/cloudchamber/create.test.ts
- packages/wrangler/src/__tests__/cloudchamber/modify.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/cloudchamber/create.ts
- packages/wrangler/src/cloudchamber/modify.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
The cloudchamber API already supports setting an instance type. This change will allow users to specify an instance type in wrangler. The specified instance type will be used configure vCPU, memory, and disk.
Implements CC-5418.
---
- Tests
> CC-5418: Set instance_type in wrangler

- .changeset/thick-icons-visit.md
- fixtures/container-app/src/index.ts
- fixtures/container-app/wrangler.registry.jsonc
- packages/containers-shared/src/build.ts
- packages/containers-shared/src/images.ts
- packages/containers-shared/src/knobs.ts
- packages/containers-shared/src/login.ts
- packages/containers-shared/src/types.ts
- packages/containers-shared/src/utils.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
Fixes DEVX-1966.
the first commit adds the pulling functionality, the second just makes manual testing a bit easier. e2e testing will happen in a followup.
---
- Tests
> feat(containers): add support for handling images that link to the CF registry

- .changeset/early-views-pay.md
- fixtures/interactive-dev-tests/Dockerfile
- fixtures/interactive-dev-tests/index.js
- fixtures/interactive-dev-tests/src/container.mjs
- fixtures/interactive-dev-tests/tests/index.test.ts
- fixtures/interactive-dev-tests/wrangler.container.jsonc
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/hotkeys.ts
This prints the hotkeys after the dev env has been set up, so that we can access the config and register hotkeys conditionally based on that. 
Looks like this: 
---
- Tests
> allow printing hotkeys conditionally

- .changeset/social-dryers-feel.md
- packages/containers-shared/src/utils.ts
- packages/wrangler/e2e/containers.dev.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
When containers are configured we want the container and the worker to be updated together (ideally). Failing earlier when we know docker is not installed keeps us from getting into a disjointed state between the worker and container.
- Tests
> Verify docker installation earlier when deploying container

- .changeset/slimy-clocks-matter.md
- packages/wrangler/src/cloudchamber/common.ts
> containers: Do not check scopes if not init

- .changeset/thick-dots-sit.md
- fixtures/get-platform-proxy/public/test.txt
- fixtures/get-platform-proxy/tests/get-platform-proxy.env.test.ts
- fixtures/get-platform-proxy/wrangler.jsonc
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/assets.ts
Backport for https://github.com/cloudflare/workers-sdk/pull/7871
> V3 backport [#7871]: add support for assets bindings to `getPlatformProxy`

- .github/workflows/e2e.yml
E2E tests cannot run on pull requests created from forks due to security concerns. In such cases we require a member of the `workers-sdk` maintainers group to manually run these tests on behalf of the PR.
If a PR from a fork specifically requests running the e2e tests, by applying the `e2e` label, we want CI to fail with a descriptive message, instead of skipping the `e2e-tests` job altogether, which gives the false optics that CI is green. Having 
CI intentionally fail for such use cases will act as a reminder that tests need to be manually run, and will prevent us from accidentally merging fork PRs that are green, but never ran the e2e tests.
Fixes n/a
---
- Tests
- …
> chore: Force fail e2e tests job if fork PR

- .github/workflows/open-v3-maintenance-prs.yml
- tools/deployments/open-v3-pr.ts
Ref the correct branch + ~clarify that the PR should be manually created.~(that was a bug fixed in the follow up commit - we tried to create a PR from the wrong branch using v3-maintenance-... instead of v3-backport-...)
---
- Tests
> Fix the v3 backport message to use v3-backport-PR

- CODEOWNERS
This reverts commit 70903b6b8a126336051fc3d0254b13c8c4c6817c now that the end of quarter LDW is over.
> Revert "temporarily remove all codeowners besides wrangler so that all PRs need the wrangler's team approval to land (#9749)"

- .github/workflows/c3-dependabot-versioning-prs.yml
- .github/workflows/c3-e2e.yml
- .github/workflows/changesets.yml
- .github/workflows/deploy-pages-previews.yml
- .github/workflows/e2e-project-cleanup.yml
- .github/workflows/e2e.yml
- .github/workflows/holopin.yml
- .github/workflows/hotfix-release.yml
- .github/workflows/issues.yml
- .github/workflows/miniflare-dependabot-versioning-prs.yml
- .github/workflows/open-v3-maintenance-prs.yml
- .github/workflows/prerelease.yml
- .github/workflows/run-ci-for-external-forks.yml
- .github/workflows/semgrep.yml
- .github/workflows/test-and-check.yml
- .github/workflows/validate-pr-description.yml
- .github/workflows/worker-playground-preview-testing-env-deploy-and-test.yml
- .github/workflows/workers-shared-deploy-production.yml
- .github/workflows/workers-shared-deploy-staging.yml
Fixes https://github.com/cloudflare/workers-sdk/security/code-scanning/173
update all the github workflows to specify the set of permissions they require, ensuring that each workflow includes the least privileges it required to complete the task
> [!Note]
> Hopefully I got everything right but it's tough to test the changes and be 100% sure (since the changes also only apply after merge), so there is a non zero chance that this might break some workflows, I'll monitor things for a few days after the PR is merged and if something does break I'll fix it right away
---
- Tests
> add permissions to github workflows

- .changeset/fluffy-comics-study.md
- packages/workers-shared/router-worker/src/worker.ts
- packages/workers-shared/router-worker/tests/index.test.ts
> Allow "plain text" images when blocking vulnerable non-image responses

- .changeset/thick-meals-cheat.md
- packages/wrangler/src/__tests__/whoami.test.ts
- packages/wrangler/src/cloudchamber/build.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/user/whoami.ts
Previously, when an authentication error was thrown, Wrangler would print out your Oauth token scopes with the passive message "If scopes are missing, you may need to logout and re-login." However, it was hard for users to know if scopes were missing, because users don't necessarily know what the right set of scopes are. 
As it turns out, Wrangler _does_ know what the set of scopes should be, so now we print out a much more actionable warning:
```
Wrangler is missing some expected Oauth scopes. To fix this, run \`wrangler login\` to refresh your token. The missing scopes are:
- containers:write
```
Additionally, this fixes an issue where auth errors from Containers & Cloudchamber were not handled the same as other auth errors, because of the custom API client that those code paths use. …
> Make Wrangler warn more loudly if you're missing auth scopes

- .github/workflows/e2e.yml
- CONTRIBUTING.md
- packages/wrangler/e2e/cert.test.ts
- packages/wrangler/e2e/deployments.test.ts
- packages/wrangler/e2e/dev-env.test.ts
- packages/wrangler/e2e/dev-remote-bindings.test.ts
- packages/wrangler/e2e/dev-with-resources.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/get-platform-proxy.test.ts
- packages/wrangler/e2e/helpers/wrangler.ts
- packages/wrangler/e2e/miniflare-remote-resources.test.ts
- packages/wrangler/e2e/pages-deploy.test.ts
- packages/wrangler/e2e/provision.test.ts
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/e2e/secrets-store.test.ts
- packages/wrangler/e2e/start-worker-remote-bindings.test.ts
- packages/wrangler/e2e/startWorker.test.ts
- packages/wrangler/e2e/validate-environment.ts
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/e2e/wrangler-remote-resources.test.ts
- tools/e2e/runIndividualE2EFiles.ts
A large number of Wrangler's "E2E" tests actually require no Cloudflare auth tokens. This PR changes our E2E setup to enable running `pnpm test:e2e:wrangler` with no other arguments, which will run all non-API-requiring E2E tests, _including on forks in CI_.
Additionally, you can pass arguments to `pnpm test:e2e:wrangler` in order to configure Vitest. e.g. `pnpm test:e2e:wrangler -u` to update snapshots.
---
- Tests
> Skip remote E2E tests when no auth available

- .changeset/metal-aliens-tell.md
- packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
- packages/wrangler/src/cloudchamber/deploy.ts
It was incorrectly marking the image as un-updated before resulting in being unable to update the image for a container application when using an image URI directly.
Added some basic unit tests to cover this behavior.
- Tests
> Containers: Ensure updating only the image URI updates app config

- packages/wrangler/package.json
wrangler imports files from the containers-shared package (which does not have a build/dev command itself), so the wrangler dev command needs to also watch the containers-shared directory to make sure that changes to files in such directory trigger appropriate wrangler rebuilds
___
- Tests
> update wrangler's `pnpm dev` to also watch the containers-shared src directory

- .changeset/brown-ends-wink.md
- packages/vite-plugin-cloudflare/package.json
Fixes #000.
Set the Wrangler peer dependency to the same version as the direct dependency. This fixes as issue where older versions of Wrangler could override the version used by the plugin.
---
- Tests
> Set the Wrangler peer dependency to the same version as the direct dependency

- .changeset/clever-regions-build.md
- packages/containers-shared/src/build.ts
- packages/containers-shared/src/types.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/cloudchamber/deploy.ts
Fixes [this beta container issue](https://discord.com/channels/595317990191398933/1354872988616364213/1383130425890967624).
Set build context relative to the Dockerfile so that `COPY`s do not break.
Also just cleaning up some duplicated helpers tests
---
- Tests
> Spawn docker build relative to the Dockerfile

- .changeset/fast-webs-know.md
- fixtures/workers-with-assets/tests/index.test.ts
- packages/miniflare/src/plugins/assets/index.ts
> fix: use logger (and log level) from miniflare for asset metadata parsing/loading logs

- .changeset/cool-toes-repair.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/mtls-certificate/cli.ts
- packages/wrangler/src/versions/index.ts
Two Wrangler subcommands (`versions` and `mtls-certificate`) had an extra space between their emoji and description, unlike all of the other subcommands, making them misaligned in the terminal:
- Tests
> remove extraneous double spaces from help output

- .changeset/bumpy-otters-kiss.md
- packages/wrangler/src/__tests__/pages/pages-deployment-tail.test.ts
- packages/wrangler/src/pages/deployment-tails.ts
If not provided with a deployment to tail, Wrangler will try to pull the list of deployments and select the most recently created one. However, we do not check whether this deployment has finished. This is causing intermittent errors for users.
---
- Tests
> [v3] WC-2965 Prevent selecting in-progress deployments when tailing

- .changeset/deep-mirrors-help.md
- packages/pages-shared/__tests__/asset-server/handler.test.ts
- packages/pages-shared/asset-server/handler.ts
- packages/wrangler/src/miniflare-cli/assets.ts
Fixes WC-3619.
- Emit `x-cf-pages-analytics: 1` header when analytics script is added to HTML responses
- Add comprehensive tests covering HTML with/without body, non-HTML responses, and missing analytics config
- Header indicates when analytics injection is attempted regardless of HTMLRewriter success
---
- Tests
> Add `x-cf-pages-analytics` header when Web Analytics token is injected

- .changeset/green-stars-fold.md
- packages/containers-shared/package.json
- packages/containers-shared/src/client/core/OpenAPI.ts
- packages/containers-shared/src/client/core/request.ts
- packages/containers-shared/tsconfig.json
- pnpm-lock.yaml
As far as I can tell undici is un-used anywhere by containers or cloudchamber so is safe to just remove.
- Tests
> Containers-shared: Remove undici dependency

- packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/auxiliary-worker/wrangler.jsonc
- packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/entry-worker/wrangler.jsonc
- packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker-alt/index.js
- packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker-alt/wrangler.jsonc
- packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker/index.js
- packages/vite-plugin-cloudflare/e2e/fixtures/remote-bindings/remote-worker/wrangler.jsonc
- packages/vite-plugin-cloudflare/e2e/helpers.ts
- packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts
The `afterAll()` hooks are run even if `describe.skipIf()` is true, so on forks these tests would likely always fail.
But even on non-forks, the tests were deploying and then deleting Workers with a fixed name, which was shared across the Cloudflare test account.
This could cause flakes if two CI jobs collided with each other.
> clean up the vite e2e remote mode tests to avoid flakes

- .changeset/long-ants-start.md
- packages/wrangler/e2e/versions.test.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/versions/types.ts
- packages/wrangler/src/versions/view.ts
> fix: assets only versions upload should include tag and message

- packages/wrangler/src/__tests__/containers/apply.test.ts
- packages/wrangler/src/cloudchamber/deploy.ts
- packages/wrangler/src/cloudchamber/helpers/diff.ts
- packages/wrangler/src/containers/deploy.ts
- packages/wrangler/src/deploy/deploy.ts
This PR simply copies the content from cloudchamber/apply.ts to containers/deploy.ts, and does the same for the corresponding tests. (also moves some shared diffing code).
Currently, the same code is being reused for both containers and cloudchamber commands, and there is some confusion resulting from this as the wrangler config shapes for each are quite different. Furthermore, the `cloudchamber apply` command has actually been reading config.containers rather than config.cloudchamber (unintentionally according to @gpanders).
Much more substantial changes to containers/deploy.ts will be happening in follow up PRs, but i'm separating these out first asap in order to prevent more unintentional changes to `wrangler cloudchamber apply` (and because i can't keep up with the merge conflicts 😅). …
> refactor containers/cloudchamber config - part 1

- fixtures/workers-with-assets-static-routing/test/index.test.ts
I tried lots of ways to get this statement not to hang locally for me, but to no avail.
Removing it doesn't apprear to have any impact, everything just closes down fine.
> remove call to close the playwright browser in fixture tests as this can cause tests to hang

- .github/dependabot.yml
Fixes n/a.
As suggested in https://github.com/cloudflare/workers-sdk/pull/9912#issuecomment-3055752395:
> The reviewers field in the dependabot.yml file will be removed soon. Please use the code owners file to specify reviewers for Dependabot PRs. For more information, see [this blog post](https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/).
We have proper codeowner in place, so it should be safe to just remove the reviewers field.
---
- Tests
> chore: remove deprecated dependabot reviewers field

- .changeset/wicked-beans-nail.md
- fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
- fixtures/vitest-pool-workers-remote-bindings/run-tests.mjs
- packages/wrangler/e2e/wrangler-remote-resources.test.ts
- packages/wrangler/src/api/remoteBindings/index.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
This was inadvertently changed in https://github.com/cloudflare/workers-sdk/commit/fae8c02bcfb51cb87a01a5185b249f6c5889d0a6
---
- Tests
> Pass worker name & compliance region through correctly

- .changeset/config.json
- package.json
- packages/vite-plugin-cloudflare/package.json
- patches/@changesets__assemble-release-plan.patch
- pnpm-lock.yaml
The `workspace:*` peer dependency of vite-plugin on wrangler meant that every time wrangler had a minor bump, the vite-plugin would get a major bump.
This PR fixes that by moving from `workspace:*` (which corresponds to the exact current version of the dependency) to `workspace:^` which means that it will work with newer versions (up to the next major bump).
It required a small patch to the changesets tool to support this, which we could upstream via PR to their project.
Looks like there is already a PR: https://github.com/changesets/changesets/pull/1291
You can test this locally by checking out this PR and then running:
```
GITHUB_TOKEN=ghp_xxxx node .github/changeset-version.js
```
replacing the GITHUB_TOKEN value with one you have created.
> It is possible we could achieve the same …
> avoid a major bump to vite-plugin when its peer dependency (wrangler) gets a minor bump

- packages/workers-shared/asset-worker/src/assets-manifest.ts
- packages/workers-shared/asset-worker/tests/assets-manifest.test.ts
Moving `compare` to the tests where it is used.
We do not need `compare` in production code as it is only used in the tests.
@GregBrimble I had that change in my initial PR but didn't pay attention that it was re-introduced in https://github.com/cloudflare/workers-sdk/pull/9908. I don't think it belongs there and we need to embed that code in the worker but feel free to close the PR if you did that on purpose.
---
- Tests
> refactor: move compare to the tests

- .changeset/clean-colts-vanish.md
- packages/wrangler/src/__tests__/cloudchamber/deploy.test.ts
- packages/wrangler/src/__tests__/config/configuration.test.ts
- packages/wrangler/src/config/validation.ts
Fixes CC-5480
- validates types for all fields
- warns for unexpected fields
- warns on deprecated fields
---
- Tests
> add more validation to containers config

- .changeset/gold-shirts-wash.md
- packages/wrangler/src/assets.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/entry.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/init.ts
- packages/wrangler/src/package-manager.ts
- packages/wrangler/src/utils/print-bindings.ts
Just adding telemetry to some miscellaneous errors.
---
- Tests
> add more (sanitised) user errors to telemetry

- fixtures/interactive-dev-tests/tests/index.test.ts
I've had this test fail many times locally.
@emily-shen suggested the problem was the fetch can hang.
So hopefully this change will make the test a bit more reliable.
> reduce flakes on interactive-dev fixture tests

- packages/wrangler/e2e/helpers/setup.ts
Paralellize file operations
---
- Tests
> refactor asynchronous code

- .changeset/orange-donkeys-check.md
- packages/vite-plugin-cloudflare/playground/worker/__tests__/worker.spec.ts
- packages/vite-plugin-cloudflare/src/index.ts
Fixes #000.
This transforms the Worker entry file to inject an HMR boundary. By providing an HMR boundary at the root, we ensure that the full module graph is not invalidated on code changes. Ideally, frameworks should be adding server HMR code at route boundaries but React Router does not currently do this. This follows discussion with the Vite team and they have also merged a PR to update the docs (https://github.com/vitejs/vite/pull/20401).
From feedback gathered from users, it appears this change fixes the issues experienced in https://github.com/cloudflare/workers-sdk/issues/9518. I believe this may be because HMR updates are queued (https://github.com/vitejs/vite/blob/3e81af38a80c7617aba6bf3300d8b4267570f9cf/packages/vite/src/module-runner/hmrHandler.ts#L25) whereas full reloads are …
> Inject HMR code in Worker entry file

- .changeset/poor-days-add.md
- fixtures/browser-rendering/package.json
- fixtures/browser-rendering/src/index.ts
- fixtures/browser-rendering/src/playwright.ts
- fixtures/browser-rendering/src/puppeteer.ts
- fixtures/browser-rendering/test/index.spec.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/workers/browser-rendering/binding.worker.ts
- packages/miniflare/test/plugins/browser/index.spec.ts
- pnpm-lock.yaml
Playwright relies on a WebSocket close event that is never triggered in local dev. As a workaround, we poll miniflare to check if the browser is still up and running, otherwise we close the websocket explictly.
Fixes: #9945
- Tests
> fix: polls miniflare to check browser process

- .changeset/late-taxis-switch.md
- fixtures/interactive-dev-tests/multi-workers-containers-app/tsconfig.json
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerA/Dockerfile
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerA/index.ts
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerA/worker-configuration.d.ts
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerA/wrangler.jsonc
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerB/Dockerfile
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerB/index.ts
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerB/worker-configuration.d.ts
- fixtures/interactive-dev-tests/multi-workers-containers-app/workerB/wrangler.jsonc
- fixtures/interactive-dev-tests/tests/index.test.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
- packages/wrangler/src/dev.ts
- packages/wrangler/src/dev/hotkeys.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/9933
Fixes https://jira.cfdata.org/browse/DEVX-2088
currently when running `wrangler dev` with different workers (meaning that the `-c|--config` flag is used multiple times) containers are not being included, meaning that trying to interact with them at runtime would not work and cause errors instead. The changes here address the above making wrangler correctly detect and wire up the containers.
---
- Tests
> add support for containers in wrangler multiworker dev

- .github/ISSUE_TEMPLATE/bug-template.yaml
> Add `npx envinfo` to issue template

- .changeset/deep-onions-move.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/index.ts
- packages/wrangler/src/deployment-bundle/run-custom-build.ts
Interactively handle `wrangler deploy`s that are probably assets-only, where there is **no config file found** and flags are incorrect or missing.
For example:
`npx wrangler deploy ./public` will now ask if you meant to deploy an folder of assets only, ask for a name, set the compat date and then ask to write your choices out to `wrangler.json` for subsequent deployments.
`npx wrangler deploy --assets=./public` will now ask for a name, set the compat date and then ask to write your choices out to `wrangler.json` for subsequent deployments.
In non-interactive contexts, we will error as we currently do.
Out of scope (for this PR) are worker or worker and asset deploys.
---
- Tests
> feat: interactively handle wonky asset deploy commands

- packages/create-cloudflare/e2e/tests/frameworks/test-config.ts
A recent bump to`vercel` (44.5.4) has broken next-on-pages, where we don't pin the version of `vercel` and `next`, just the version of`create-next-app`. A fix is incoming, but in the meantime, let's skip these tests.
---
- Tests
> Quarantine next on pages c3 tests

- .changeset/spotty-pants-jog.md
- packages/vitest-pool-workers/src/pool/index.ts
Fixes WOR-760.
A user can define a Workflow binding where the `script_name` is the same as the name of the Worker on which the binding is defined. Although redundant, it should be supported.
`vitest-pool-workers` breaks because it does not use the user's Worker as the test entrypoint. It uses its own runner worker, which has a different name generated before execution. This leads to a mismatch between the `script_name` in the binding and the Worker that will run.
To fix this, the code now checks it a workflow binding's  `script_name` matches its own Worker's name. When it does, `script_name` is removed, making it default to the current worker.
---
- Tests
> [vitest-pool-workers] Fix Workflow binding's script_name when it matches its own Worker name

- .changeset/blue-clubs-bake.md
- packages/miniflare/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
I'm creating this to unblock https://github.com/cloudflare/workers-sdk/pull/10015 which needs a newer version of workerd (and I thought it'd be cleaner to bumpo workerd in its own separate PR)
> [v3-maintenance] chore: update workerd dependency to latest

- .changeset/quick-cycles-send.md
- packages/unenv-preset/package.json
- packages/unenv-preset/src/index.ts
- packages/unenv-preset/src/preset.ts
- packages/unenv-preset/src/runtime/node/http.ts
- packages/unenv-preset/src/runtime/node/https.ts
- packages/unenv-preset/src/runtime/polyfill/performance.ts
- packages/wrangler/e2e/unenv-preset/preset.test.ts
- packages/wrangler/e2e/unenv-preset/worker/index.ts
- pnpm-lock.yaml
The preset now returns a different polyfill whether or not http modules are enabled.
Notes:
- `workerd` peer dep is bumped to `^1.20250722.0` where clients side http feature are enable
- the [server http APIs](https://github.com/cloudflare/workerd/pull/4591) are not available yet, so the PR still uses `unenv`
/cc @anonrig @jamesopstad @petebacondarwin 
---
- Tests
> [preset] add support for the native http modules

- packages/wrangler/e2e/unenv-preset/worker/index.ts
The test used to `import("@cloudflare/unenv-preset/npm/debug")`, it now just `import("debug")`
This also test that `debug` is actually aliased to `@cloudflare/unenv-preset/npm/debug` (i.e. the package polyfill is in place).
---
- Tests
> import debug instead of the alias

- .changeset/afraid-experts-take.md
- packages/vite-plugin-cloudflare/src/index.ts
- packages/wrangler/src/dev/hotkeys.ts
Fixes DEVX-2052
Adds logs, when a Worker has Containers configured, providing information about container build status, and how to rebuild containers during local development.
`dev`
`preview`
---
- Tests
> feat(vite-plugin): Add Containers-related info logs

- .changeset/great-terms-roll.md
- fixtures/interactive-dev-tests/tests/index.test.ts
- packages/containers-shared/src/utils.ts
- packages/vite-plugin-cloudflare/playground/containers/src/index.ts
- packages/vite-plugin-cloudflare/src/containers.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/wrangler/e2e/containers.dev.test.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/MultiworkerRuntimeController.ts
- packages/wrangler/src/dev/hotkeys.ts
previously these methods were async so we could not call them from `process.on('exit')`. by using synchronous apis instead to run docker commands, we can actually do cleanup from that hook, which simplifies a lot of the vite plugin cleanup code and also ensures proper cleanup if you run and stop wrangler programmatically (e.g. using something like `concurrently`). 
Vite manual testing:
I don't think we can test this with the vite plugin because we start and stop the vite server in vitest's global setup hook, which runs after test hooks like `afterAll`.
You can manually test this by:
1. running vite dev in `container-app` in the vite playground
2. hit `/start` 
3. verify a container is running with `docker ps`
4. stop the vite dev session
5. run `docker ps` again to verify no containers …
> Clean up containers started by local dev during process exit hook instead

- .changeset/eight-buckets-bathe.md
- .changeset/icy-lands-build.md
- fixtures/dev-registry/assets/example.txt
- fixtures/dev-registry/tests/dev-registry.test.ts
- fixtures/dev-registry/vite.worker-entrypoint-b.config.ts
- fixtures/dev-registry/wrangler.service-worker.jsonc
- fixtures/dev-registry/wrangler.worker-entrypoint-a.jsonc
- fixtures/dev-registry/wrangler.worker-entrypoint-b.jsonc
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/core/index.ts
- packages/vite-plugin-cloudflare/src/constants.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
- packages/vite-plugin-cloudflare/src/vite-proxy-worker/index.ts
- packages/vite-plugin-cloudflare/tsup.config.ts
Fixes [DEVX-2120](https://jira.cfdata.org/browse/DEVX-2120)
This adds an asset proxy worker in front of the user worker when registering the worker in the dev registry which route the request through the vite dev server for assets.
---
- Tests
> fix(vite-plugin-cloudflare): ensure cross-process service bindings route through asset worker

- pnpm-lock.yaml
- tools/e2e/runIndividualE2EFiles.ts
- tools/package.json
`tools/e2e/runIndividualE2EFiles.ts` was missing test files in nested directories.
That before the PR the top level `test:e2e:wrangler` was not testing the same as `test:e2e` from the wrangler package (the former would miss nested folders).
I also updated the file so that it can be executed from anywhere by using `__dirname` rather than relying on the cwd.
Do we want to update wrangler's `test:e2e` to also use `runIndividualE2EFiles`? (that's how I originally miss that the behavior was not correct on CI)
Nested tests are now executed:
---
- Tests
> make sure we run wrangler e2e tests in nested folders

- .changeset/happy-streets-leave.md
- packages/wrangler/e2e/unenv-preset/preset.test.ts
- packages/wrangler/src/__tests__/r2/bucket.test.ts
- packages/wrangler/src/r2/bucket.ts
Fixes #9433
Adds a `--json` flag to the `wrangler r2 bucket info` command, returning the bucket info in clean JSON format.
The current output is not machine-readable.  
Adding this flag makes the output usable in scripts and consistent with D1 commands that already support `--json`.  
- Adds a `--json` flag to `r2 bucket info`
- Omits verbose output when `--json` is passed
- Suppresses the Wrangler banner when `--json` is used
- Adds a unit test verifying valid JSON output
- Linting fixed with `pnpm fix`
- Added a changeset as per contribution guidelines
- ✅ `pnpm exec vitest run packages/wrangler/src/__tests__/r2/bucket.test.ts` passed
- ✅ Manual output verified
- ✅ Verified that banner is suppressed when `--json` is passed
```bash
$ wrangler r2 bucket info my-bucket-name --json
{ …
```
> [wrangler] Add --json flag to r2 bucket info command

- .changeset/hip-sites-camp.md
- packages/wrangler/src/__tests__/delete.test.ts
- packages/wrangler/src/delete.ts
EWC changes add the new "pages_function" boolean field to the service reference API when a pages function has a service binding to this worker, and requires "force=true" when deleting
WC-3776
- Tests
> WC-3776 Require confirm for delete when Pages project binds to worker

- .changeset/evil-loops-eat.md
- fixtures/vitest-pool-workers-examples/container-app/Dockerfile
- fixtures/vitest-pool-workers-examples/container-app/README.md
- fixtures/vitest-pool-workers-examples/container-app/container/simple-node-app.js
- fixtures/vitest-pool-workers-examples/container-app/src/index.ts
- fixtures/vitest-pool-workers-examples/container-app/src/tsconfig.json
- fixtures/vitest-pool-workers-examples/container-app/test/container.test.ts
- fixtures/vitest-pool-workers-examples/container-app/test/container.unit.test.ts
- fixtures/vitest-pool-workers-examples/container-app/test/env.d.ts
- fixtures/vitest-pool-workers-examples/container-app/test/tsconfig.json
- fixtures/vitest-pool-workers-examples/container-app/tsconfig.json
- fixtures/vitest-pool-workers-examples/container-app/vitest.config.ts
- fixtures/vitest-pool-workers-examples/container-app/wrangler.jsonc
- fixtures/vitest-pool-workers-examples/package.json
- packages/vitest-pool-workers/src/pool/config.ts
- packages/wrangler/src/api/integrations/platform/index.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/dev/miniflare/index.ts
- pnpm-lock.yaml
This doesn't actually enable testing, but it stops vitest breaking entirely at least. also fixes enable_containers with the vite plugin.
todo: document enable_containers
---
- Tests
> stop vitest pool workers breaking when containers are present 

- .changeset/sdw-auth.md
- .changeset/whole-masks-sniff.md
- packages/wrangler/e2e/dev-env.test.ts
- packages/wrangler/e2e/start-worker-auth-opts.test.ts
- packages/wrangler/src/api/remoteBindings/index.ts
- packages/wrangler/src/api/startDevWorker/LocalRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/RemoteRuntimeController.ts
- packages/wrangler/src/api/startDevWorker/types.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/dev/create-worker-preview.ts
- packages/wrangler/src/dev/remote.ts
Fixes https://jira.cfdata.org/browse/DEVX-1857
---
- Tests
> fix `startWorker` not respecting `auth` options for remote bindings

- .changeset/blue-seas-visit.md
- .changeset/pink-heads-help.md
- packages/containers-shared/src/client/core/OpenAPI.ts
- packages/containers-shared/src/client/core/request.ts
- packages/containers-shared/src/types.ts
- packages/wrangler/src/__tests__/containers/delete.test.ts
- packages/wrangler/src/cloudchamber/common.ts
- packages/wrangler/src/containers/containers.ts
Fixes CC-5810.
Previously we'd see `DELETE method not allowed for the oauth_token authentication scheme` when you try and do something like `wrangler containers images delete <container-name>`, because `<container-name>` didn't look like an ID to API gateway and it would get confused.
Also, added container API calls to the output of `WRANGLER_LOG=debug`, since I wanted to see that when i was debugging.
---
- Tests
> validate id in `wrangler containers delete` and also include container API calls in WRANGLER_LOG=debug

- .changeset/moody-rings-ask.md
- packages/wrangler/src/__tests__/workflows.test.ts
- packages/wrangler/src/config/validation-helpers.ts
- packages/wrangler/src/config/validation.ts
Fixes WOR-795
Users should not be allowed to define multiple workflows with the same "name" property within a single Wrangler jsonc/toml file. If duplicate names are allowed, only the last-defined workflow would be active, as it would overwrite any earlier workflows with the same name.
To fix this, the code now includes a check for duplicate "name" properties within the workflows array.
---
- Tests
> [wrangler] fix: prevent multiple workflows definition with same name

- .changeset/calm-gifts-hear.md
- fixtures/get-platform-proxy-remote-bindings/tests/index.test.ts
- packages/wrangler/e2e/dev.test.ts
- packages/wrangler/e2e/helpers/fetch-text.ts
- packages/wrangler/e2e/remote-binding/wrangler-remote-resources.test.ts
- packages/wrangler/src/api/remoteBindings/index.ts
Fixes https://jira.cfdata.org/browse/DEVX-2152
Fixes https://github.com/cloudflare/workers-sdk/issues/9568
---
- Tests
> ensure that `maybeStartOrUpdateRemoteProxySession` considers the potential account_id from the users' wrangler config

- .changeset/famous-coats-chew.md
- packages/containers-shared/src/types.ts
- packages/wrangler/src/__tests__/containers/config.test.ts
- packages/wrangler/src/containers/config.ts
- packages/wrangler/src/containers/deploy.ts
Fixes CC-5818
Adds the option to allow all tiers when creating a container application.
---
- Tests
> containers: add option to allow all tiers

- .changeset/nine-moose-decide.md
- packages/miniflare/scripts/build.mjs
- packages/miniflare/src/index.ts
- packages/miniflare/src/shared/dev-registry.ts
- packages/miniflare/src/shared/dev-registry.worker.ts
- packages/miniflare/test/dev-registry.spec.ts
Fixes n/a.
This PR moves the address lookup logic from the loopback server to a new proxy server running in a worker thread to workaround a deadlock situation with the node bindings locking the main thread when waiting for a response from the runtime while the runtime is also waiting for a response from the loopback server on the address of the other workerd process. 😅 
---
- Tests
> feat(miniflare): support node bindings over dev registry

- .changeset/crazy-experts-wonder.md
- packages/devprod-status-bot/src/index.ts
> fix security alerts to avoid being in the same notification thread

- packages/miniflare/test/plugins/core/errors/index.spec.ts
This test is brittle to changes to the workerd codebase that just result in source-code line changes.
> test: relax the pretty-print error test

- .changeset/lucky-hornets-listen.md
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/versions/upload.ts
Updates generatePreviewAlias to truncate long branch names with hash suffixes when they exceed DNS label constraints, instead of returning undefined. This allows preview deployments for branches with longer descriptive names.
Fixes #WC-3840
- Tests
> feat(wrangler): support long branch names in preview alias generation

- packages/wrangler/e2e/pages-dev.test.ts
Occasionally this test flaked because the dev process output the bindings twice. I believe this is a timings issue around watching for file changes, triggering a second update and printing of the bindings
So now we only extract the first bindings list and clean it up to make it resilient to flaking
- Tests
> test: reduce flakes on pages-dev e2e tests

- .changeset/bright-snails-knock.md
- packages/create-cloudflare/templates/svelte/pages/templates/wrangler.jsonc
- packages/create-cloudflare/templates/svelte/workers/templates/wrangler.jsonc
Recent sveltekit versions rely on `node:async_hooks` to access `AsyncLocalStorage`
See https://github.com/sveltejs/kit/issues/13668 for the report.
---
- Tests
> Add the nodejs_als flag for the svelte template

- .changeset/brown-knives-sort.md
- packages/wrangler/src/deployment-bundle/guess-worker-format.ts
Simple change that modifies a warning output by wrangler slightly.
---
- Tests
> Remove mention of cf-requirements when Python Worker is enabled

- packages/miniflare/test/plugins/browser/index.spec.ts
This test is constantly flaking on Windows, so we will skip it for now.
@ruifigueira - can you look into re-enabling this as part of your other work on Browser rendering?
> skip flaky browser render test on Windows

- .changeset/chatty-pens-sniff.md
- .github/workflows/c3-e2e.yml
- packages/miniflare/test/plugins/email/index.spec.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
- packages/wrangler/src/triggers/deploy.ts
Fixes #[MQ-861](https://jira.cfdata.org/browse/MQ-861)
Removed a call to putQueue when deploying a worker with a queue producer binding. 
This is needed because a worker should not be able to affect queue level settings. Additionally, when having multiple producers, the settings will be determined by the last deployed producer which also leads to issues.
---
- Tests
> fix(wrangler) remove putQueue call when deploying a worker with queue producer binding

- .changeset/empty-chefs-tan.md
https://github.com/cloudflare/workers-sdk/actions/runs/16915588716/job/47928545181 job failed to release `quick-edit`. https://github.com/cloudflare/workers-sdk/pull/10336 is meant to fix the root cause of why the job failed. This PR adds a dummy changeset so that we can run another release of `quick-edit`
---
- Tests
> chore: dummy quick-edit release  due to changeset job failure

- .changeset/giant-ghosts-flow.md
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/versions/upload.ts
Bugfix: updates regex to allow for longer branch names. This was previously failing the regex check, even though we later truncate the branch name if it's too long.
- Tests
> Bugfix: Update regex for valid branch names

- .changeset/yummy-parents-remain.md
- packages/wrangler/src/__tests__/startup-profiling.test.ts
- packages/wrangler/src/check/commands.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/9818 and fixes https://github.com/cloudflare/workers-sdk/issues/9985
Ignore sourcemaps when loading a Worker for startup profiling
---
- Tests
> Fix startup profiling with sourcemaps enabled

- packages/wrangler/e2e/remote-binding/remote-bindings-api.test.ts
- packages/wrangler/src/api/remoteBindings/index.ts
Fixes https://jira.cfdata.org/browse/DEVX-2147
Fixes https://jira.cfdata.org/browse/DEVX-2146
---
- Tests
> Add e2e tests for programmatic remote bindings api

- packages/vite-plugin-cloudflare/e2e/basic.test.ts
- packages/vite-plugin-cloudflare/e2e/helpers.ts
- packages/vite-plugin-cloudflare/e2e/remote-bindings.test.ts
Fixes https://jira.cfdata.org/browse/DEVX-1953
---
- Tests
> re-enable vite-plugin remote bindings e2e tests for dev mode

- .changeset/petite-paws-allow.md
- fixtures/browser-rendering/src/playwright.ts
- fixtures/browser-rendering/src/puppeteer.ts
- fixtures/browser-rendering/test/index.spec.ts
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/browser-rendering/index.ts
- packages/miniflare/src/workers/browser-rendering/binding.worker.ts
- packages/miniflare/test/plugins/browser/index.spec.ts
Fixes: BRAPI-393
Implements browser rendering [/v1/sessions](https://developers.cloudflare.com/browser-rendering/platform/playwright/#list-open-sessions) endpoint in local dev mode.
---
- Tests
> chore: implement local browser rendering /v1/session endpoint

- packages/wrangler/e2e/pages-dev.test.ts
Backport of #10280 
Occasionally this test flaked because the dev process output the bindings twice. I believe this is a timings issue around watching for file changes, triggering a second update and printing of the bindings
So now we only extract the first bindings list and clean it up to make it resilient to flaking
- Tests
> Backport of 10280 - test: reduce flakes on pages-dev e2e tests

- packages/wrangler/src/config/environment.ts
Fixes #10168
This refers to the deprecated service environments, not wrangler environments, so hiding it to reduce confusion. 
---
- Tests
> hide and mark `service.environments` as deprecated

- .changeset/ten-yaks-teach.md
- packages/wrangler/e2e/r2.test.ts
- packages/wrangler/src/__tests__/__snapshots__/kv.test.ts.snap
- packages/wrangler/src/__tests__/__snapshots__/r2.test.ts.snap
- packages/wrangler/src/__tests__/d1/create.test.ts
- packages/wrangler/src/__tests__/hyperdrive.test.ts
- packages/wrangler/src/__tests__/kv.test.ts
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/__tests__/update-config-file.test.ts
- packages/wrangler/src/__tests__/vectorize/vectorize.test.ts
- packages/wrangler/src/config/index.ts
- packages/wrangler/src/d1/create.ts
- packages/wrangler/src/deployment-bundle/bindings.ts
- packages/wrangler/src/dialogs.ts
- packages/wrangler/src/hyperdrive/create.ts
- packages/wrangler/src/kv/index.ts
- packages/wrangler/src/pipelines/cli/create.ts
- packages/wrangler/src/r2/bucket.ts
- packages/wrangler/src/vectorize/create.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/9730
When running a resource creation command (like `wrangler kv namespace create NAME`), Wrangler will now offer to update your config file for you. Some notes:
- This does not work for preview KV namespaces, as we don't know the right main KV ID to use
- This _does_ work for environments, and will update the relevant resource field in the given environment (i.e. `--env test`)
- Wrangler will prompt with 3 options: Yes, Yes but change the binding name (which will then present a second dialog to choose the binding name), or No
- This will not work in non-interactive contexts like CI
- This will not work when running Wrangler in a context that can't find a config file
- Updating the config file only works for jsonc format
---
- Tests
- …
> Update config after creation commands

- .changeset/yummy-parents-remain.md
- packages/wrangler/src/__tests__/startup-profiling.test.ts
- packages/wrangler/src/check/commands.ts
This is an automatically opened PR to backport patch changes from #9990 to Wrangler v3
> V3 Backport [#9990]: Fix startup profiling with sourcemaps enabled

- packages/wrangler/e2e/unenv-preset/worker/index.ts
It looks like `nodejs.org` added a DNS record which break the e2e tests.
Records are now:
- `google-site-verification=v0MKccGKHVIlJbu0s9K45qnPGB7EBWnKzjpsd010r4E` (added)
- `v=spf1 include:aspmx.googlemail.com -all`
This PR updates the test to expect one or more record and at least one starting with `v=spf1`
---
- Tests
> make dns test more robust

- .changeset/green-bugs-shout.md
- packages/wrangler/src/__tests__/dev.test.ts
- packages/wrangler/src/config/dot-env.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/7042
This PR reintroduces the changes made in https://github.com/cloudflare/workers-sdk/pull/7272 that were incorrectly removed in https://github.com/cloudflare/workers-sdk/pull/9914
---
- Tests
> Simplify ENOENT debug logs for `.env` files

- .changeset/shiny-maps-type.md
- packages/create-cloudflare/templates/remix/pages/c3.ts
- packages/create-cloudflare/templates/remix/workers/c3.ts
It looks like the Remix team has updated their main branch for the new Remix v3 ([`main`](https://github.com/remix-run/remix/tree/main)). This causes C3, which fetches the workers/pages template, to fail when trying to create new Remix applications. Thankfully the Remix team also kept the pre-existing templates in the [`main-prev` branch](https://github.com/remix-run/remix/tree/main-prev), so here I am updating C3 to use that instead.
> [!Note]
> Long term we should discuss and see if we should just not support Remix in C3 anymore, and if that would necessarily constitute a breaking change
---
- Tests
> fix outdated Remix template url being used

- .changeset/small-things-poke.md
- packages/miniflare/package.json
- packages/vitest-pool-workers/package.json
- pnpm-lock.yaml
Fixes n/a.
Updated devalue version to address https://github.com/sveltejs/devalue/security/advisories/GHSA-vj54-72f3-p5jv
---
- Tests
> chore: bump devalue to 5.3.2

- .changeset/loud-insects-drive.md
- packages/wrangler/src/__tests__/deploy/config-diffs.test.ts
- packages/wrangler/src/cloudchamber/helpers/diff.ts
Fixes #10362
Example diff log when the current config removed a variable set in the dashboard:
| Before | After |
|--------|--------|
| <img width="503" height="174" alt="Screenshot 2025-08-18 at 16 58 16" src="https://github.com/user-attachments/assets/ca1a5903-da59-440e-9fca-ed3aee5e7f43" /> | <img width="444" height="173" alt="Screenshot 2025-08-18 at 16 54 42" src="https://github.com/user-attachments/assets/ecc04bc6-fe29-4d58-ba51-e96ed95c1a44" /> 
Notice how the `+` line is weirdly positioned, making the diff much less readable | All the `-` lines are now together making the diff much cleaner and more readable |
---
- Tests
> improve diff lines ordering in remote deploy config diffing logic

- .changeset/real-bottles-report.md
- packages/containers-shared/src/client/models/ApplicationAffinities.ts
- packages/containers-shared/src/client/models/ApplicationAffinityHardwareGeneration.ts
- packages/containers-shared/src/types.ts
- packages/wrangler/src/__tests__/cloudchamber/apply.test.ts
- packages/wrangler/src/__tests__/containers/config.test.ts
- packages/wrangler/src/__tests__/containers/deploy.test.ts
- packages/wrangler/src/cloudchamber/apply.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/containers/config.ts
- packages/wrangler/src/containers/deploy.ts
Fixes CC-5971.
Allow setting container affinities on container creation and modification.
---
- Tests
> Support setting container affinities

- .changeset/great-singers-poke.md
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/pyproject.toml
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/uv.lock
- packages/create-cloudflare/templates/hello-world-durable-object/py/pyproject.toml
- packages/create-cloudflare/templates/hello-world-durable-object/py/uv.lock
- packages/create-cloudflare/templates/hello-world-with-assets/py/pyproject.toml
- packages/create-cloudflare/templates/hello-world-with-assets/py/uv.lock
- packages/create-cloudflare/templates/hello-world/py/pyproject.toml
- packages/create-cloudflare/templates/hello-world/py/uv.lock
I also renamed the project from `"<TBD>"` to `"TBD"` because otherwise we get errors like:
```
Using CPython 3.12.9
error: Failed to parse `uv.lock`
Caused by: TOML parse error at line 4, column 1
|
4 | [[package]]
| ^^^^^^^^^^^
Not a valid package or extra name: "<TBD>". Names must start and end with a letter or digit and may only contain -, _, ., and alphanumeric characters.
```
- Tests
> Python templates: include pywrangler dev dep in pyproject.toml

- .changeset/lemon-boxes-flow.md
- packages/unenv-preset/package.json
- packages/vite-plugin-cloudflare/package.json
- packages/wrangler/package.json
- pnpm-lock.yaml
Pulls [a fix for `node:tty` default export](https://github.com/unjs/unenv/pull/513)
Thanks @pi0 for the `unenv` release
/cc @jasnell 
---
- Tests
> Bump `unenv` to 2.0.0-rc.20

- packages/wrangler/e2e/unenv-preset/preset.test.ts
workerd >= 20250901 was required to test a compatibility date of 20250901 locally.
workerd was updated in https://github.com/cloudflare/workers-sdk/pull/10535
---
- Tests
> refactor unenv e2e tests now that workerd >= 20250901

- .changeset/three-toys-feel.md
- packages/wrangler/src/__tests__/versions/versions.help.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/versions/upload.ts
Fixes #10512
regression from when we refactored this command in https://github.com/cloudflare/workers-sdk/pull/7437 (10 months ago 🫠 )
---
- Tests
> fix versions upload positional arg

- .changeset/bumpy-garlics-call.md
- packages/vite-plugin-cloudflare/playground/worker/__tests__/worker.spec.ts
- packages/vite-plugin-cloudflare/playground/worker/src/a.ts
- packages/vite-plugin-cloudflare/playground/worker/src/b.ts
- packages/vite-plugin-cloudflare/playground/worker/src/index.ts
- packages/vite-plugin-cloudflare/src/cloudflare-environment.ts
Fixes #10213.
Sets `preserveEntrySignatures: "strict"` for Worker environments. This ensures that no additional exports are added to the entry module.
---
- Tests
>  Set `preserveEntrySignatures: "strict"` for Worker environments

- packages/wrangler/e2e/provision.test.ts
- packages/wrangler/e2e/versions.test.ts
Fixes #10478.
Wrangler preview urls now default to disabled and a few wrangler e2e tests should be updated.
need to be updated.
---
- Tests
> fix version upload e2e test

- .changeset/orange-signs-lose.md
- packages/cli/interactive.ts
- packages/cli/package.json
- tools/deployments/__tests__/validate-changesets.test.ts
Fixes CC-5962.
Include the cursor in text prompts.
**Before:**
**After:**
- Tests
> Include cursor in text prompts

- .changeset/stupid-pandas-think.md
- fixtures/unbound-durable-object/package.json
- fixtures/unbound-durable-object/src/index.ts
- fixtures/unbound-durable-object/tests/index.test.ts
- fixtures/unbound-durable-object/tests/tsconfig.json
- fixtures/unbound-durable-object/tsconfig.json
- fixtures/unbound-durable-object/wrangler.jsonc
- packages/miniflare/src/index.ts
- packages/miniflare/src/plugins/do/index.ts
- packages/wrangler/e2e/remote-binding/dev-remote-bindings.test.ts
- packages/wrangler/src/dev/miniflare/index.ts
- pnpm-lock.yaml
> Add Miniflare & Wrangler support for unbound Durable Objects

- packages/vite-plugin-cloudflare/src/runner-worker/index.ts
- packages/wrangler/e2e/remote-binding/start-worker-remote-bindings.test.ts
- packages/wrangler/e2e/start-worker-auth-opts.test.ts
- packages/wrangler/e2e/startWorker.test.ts
Just a very simple change to the type parameters to avoid future issues when workers-types locks down its Env types
> Fix up vite-plugin runner type params

- .changeset/swift-buses-design.md
- packages/wrangler/e2e/remote-binding/wrangler-remote-resources.test.ts
- packages/wrangler/src/dev.ts
Fixes #10635
When the `--local`  flag is provided, turn off remote bindings.
---
- Tests
> Disable remote bindings with the `--local` flag

- .changeset/bumpy-islands-slide.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/environments/index.ts
Refs #10546.
This PR fixes an issue where Workers were not being tagged appropriately when a top-level name was not present in Wrangler configuration.
---
- Tests
> fix: skip service tagging when no top-level name configured

- .changeset/red-wasps-kick.md
- fixtures/worker-logs/tests/index.test.ts
- packages/unenv-preset/package.json
- packages/unenv-preset/src/runtime/node/process.ts
- packages/wrangler/e2e/unenv-preset/preset.test.ts
- packages/wrangler/e2e/unenv-preset/worker/index.ts
- pnpm-lock.yaml
This PR enabled using workerd `node:process` v2 when it is enabled (by flag or date).
It depends on the implemntation being available:
- implemented in https://github.com/cloudflare/workerd/pull/4960
- releases in [workerd v1.20250904.0](https://github.com/cloudflare/workerd/releases/tag/v1.20250904.0)
- depends on https://github.com/cloudflare/workerd/pull/5040  released in https://github.com/cloudflare/workerd/releases/tag/v1.20250911.0
- depends on https://github.com/cloudflare/workerd/pull/5024 released in https://github.com/cloudflare/workerd/releases/tag/v1.20250912.0
---
Outdated comment:
<details>
A few notes:
This PR still fails the remote tests as the v2 changes have not reached production yet.
Some of [the v2 APIs are `undefined`](https://github.com/cloudflare/workerd/blob/e8aad …
> Use workerd `node:process` v2 when available

- .changeset/free-pants-jump.md
- packages/vite-plugin-cloudflare/playground/custom-build-app/vite.config.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/output-config.ts
Fixes #10650.
This fixes an issue that can occur if the same Worker environment is built twice.
---
- Tests
>  Avoid mutating the Worker config during build.

- .changeset/soft-flies-search.md
- packages/miniflare/src/plugins/email/index.ts
- packages/miniflare/src/workers/email/send_email.worker.ts
- packages/miniflare/test/plugins/email/index.spec.ts
- packages/wrangler/src/__tests__/init.test.ts
- packages/wrangler/src/__tests__/versions/versions.view.test.ts
- packages/wrangler/src/config/environment.ts
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/deployment-bundle/worker.ts
- packages/wrangler/src/utils/map-worker-metadata-bindings.ts
- packages/wrangler/src/utils/print-bindings.ts
- packages/wrangler/src/versions/view.ts
Fixes EMAIL-1228.
Added new attribute called "allowed_sender_addresses" to send_email binding. This allows the binding to be restricted in the possible values for the sender of emails.
---
- Tests
> Add new attribute allowed_sender_addresses

- .changeset/giant-cherries-shake.md
- packages/wrangler/src/dev/miniflare/index.ts
- packages/wrangler/src/utils/print-bindings.ts
Fixes two minor display bugs:
- Browser bindings incorrectly showed a warning about not supporting local mode
- KV/R2/D1 bindings did not respect the REMOTE_BINDINGS flag when displaying their remote/local status
---
- Tests
> Fix remote/local display

- .changeset/brave-memes-raise.md
- packages/wrangler/src/__tests__/pipelines.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/pipelines/cli/setup.ts
- packages/wrangler/src/pipelines/cli/sinks/create.ts
- packages/wrangler/src/pipelines/cli/sinks/utils.ts
- packages/wrangler/src/pipelines/cli/streams/utils.ts
- packages/wrangler/src/pipelines/defaults.ts
- packages/wrangler/src/pipelines/types.ts
- packages/wrangler/src/r2/catalog.ts
Updated catalog compaction enable argument from targetSizeMb to target-size. Small fixes for pipelines commands, defaults.
---
- Tests
- [] Cloudflare docs PR(s):
> Updated catalog compaction arg, small pipelines fixes

- package.json
- pnpm-lock.yaml
The `@actions/artifact` package (https://github.com/actions/toolkit/tree/main/packages/artifact) is a dependency of the upload-artifact action (https://github.com/actions/upload-artifact) that we use for C3, but as far as I can tell it does not need to be installed in the repository for it to work (you can indeed see the upload-artifact action working as intended in the C3 workflows here).
So I don't think we actually need the `@actions/artifact` dependency, nor it look to me like we use it for anything, so here I am removing it (all the CI checks passing should hopefully be proof that we don't need it).
---
- Tests
> remove unused `@actions/artifact` dependency

- .changeset/warm-clowns-visit.md
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/secret/index.ts
URL encode the secret names before being sent to the API, should allow users to delete secrets with complex names. Change is still compatible with older Wrangler versions thanks to the optional query param flag `url_encoded`.
Tracking internally: https://jira.cfdata.org/browse/WC-3991
URL encode all secret names in the `DELETE .../secrets/:secret` call, should allow the deletion of secrets with complex names.
---
- Tests
---
Docs have new query param `url_encoded`:
https://developers.cloudflare.com/api/resources/workers/subresources/scripts/subresources/secrets/methods/delete/
> wrangler: fix: support the deletion of secrets with complex names

- .changeset/modern-bobcats-tie.md
- packages/wrangler/src/config/validation.ts
- packages/wrangler/src/deployment-bundle/create-worker-upload-form.ts
- packages/wrangler/src/utils/map-worker-metadata-bindings.ts
Turns out it's `worker_loader` not `worker-loader`
---
- Tests
> Fix Worker Loader binding type

- fixtures/workers-with-assets-run-worker-first/README.md
- fixtures/workers-with-assets-spa/README.md
- fixtures/workers-with-assets/README.md
For some reason we had quotes in the README title (eg. see: https://github.com/cloudflare/workers-sdk/tree/main/fixtures/workers-with-assets-run-worker-first). Removed for 3 fixtures I saw.
- Tests
> Fix README title text

- .changeset/bitter-banks-teach.md
- packages/wrangler/src/__tests__/index.test.ts
- packages/wrangler/src/__tests__/secrets-store.test.ts
- packages/wrangler/src/secrets-store/commands.ts
- packages/wrangler/src/secrets-store/index.ts
Fix #10566.
The "Secrets Store" description in the CLI still shows [alpha], but the command is already [open-beta].
I've updated it accordingly and also updated the tests.
---
- Tests
> fix: update Secrets Store status from alpha to open-beta

- packages/workers-shared/asset-worker/src/types.ts
- packages/workers-shared/asset-worker/wrangler.jsonc
- packages/workers-shared/router-worker/src/types.ts
- packages/workers-shared/router-worker/wrangler.jsonc
tracked internally as WC-3962
- Tests
> feat(workers-shared): add fed configs for assets workers

- packages/wrangler/src/__tests__/dev/remote-bindings.test.ts
- packages/wrangler/src/__tests__/vitest.setup.ts
- packages/wrangler/src/api/startDevWorker/ConfigController.ts
- packages/wrangler/src/environment-variables/factory.ts
- packages/wrangler/src/environment-variables/misc-variables.ts
Previously we blocked config watching based on the existence of the `vitest` global. But this made it difficult to override in the tests where we actually needed config file changes to trigger reloads.
Turning on config watching for all tests proved to cause a bunch of tests that don't care about config file changes to become flaky.
So now we are guarding config watching once again but now with the more configurable `process.env.VITEST`.
---
- Tests
> test: only watch config files in ConfigController when not testing

- .changeset/new-lizards-check.md
- packages/create-cloudflare/templates/hello-world-durable-object-with-assets/py/.gitignore
- packages/create-cloudflare/templates/hello-world-durable-object/py/.gitignore
- packages/create-cloudflare/templates/hello-world-with-assets/py/.gitignore
- packages/create-cloudflare/templates/hello-world/py/.gitignore
Just a simple change to add some folders that should be ignored in Python workers
---
- Tests
> Add python-specific git ignores to Python templates

- .changeset/pink-coins-switch.md
- packages/create-cloudflare/templates/react-router/c3.ts
See https://github.com/remix-run/react-router-templates/pull/161
---
- Tests
> pin the URL for the react-router template since it was deleted from their project

- .changeset/red-keys-clean.md
- packages/wrangler/package.json
- packages/wrangler/src/containers/containers.ts
- pnpm-lock.yaml
Fixes CC-6043.
Uses `YAML` to stringify the application rather than our own stringification which handles nested objects natively.
Before:
```
      │ rollout_active_grace_period: 0
      │ health:
      │   errors: [object Object],[object Object],[object Object],[object
Object],[object Object]
      │   instances:
      │     healthy: 7
      │     failed: 0
      │     scheduling: 0
      ╰     starting: 0
```
After:
```
      │ rollout_active_grace_period: 0
      │ health:
      │   errors:
      │     - instance_id: d03f26f0-225e-4d57-86d6-2b96e24d0e52
      │       event:
      │         id: 38120b2c-e759-41e8-a47f-555bede6ba02
      │         time: 2025-09-09T03:53:20.232090368Z
      │         type: Info
      │         name: VMStopped
      │         message: the vm stopped …
```
> fix(wrangler): Nested object rendering in Containers list/info commands

- .changeset/some-singers-sit.md
- packages/create-cloudflare/src/templates.ts
The pyproject.toml and uv.lock files were ending up with names generated in them that had no quotes which resulted in errors.
---
- Tests
> Fixes pyproject.toml/uv.lock not including quotes

- .changeset/popular-moons-knock.md
- fixtures/ratelimit-app/tsconfig.json
- fixtures/worker-ts/wrangler.jsonc
- packages/containers-shared/src/build.ts
- packages/containers-shared/src/error.ts
- packages/containers-shared/src/images.ts
- packages/containers-shared/src/inspect.ts
- packages/containers-shared/src/login.ts
- packages/containers-shared/src/utils.ts
- packages/containers-shared/tests/docker-context.test.ts
- packages/edge-preview-authenticated-proxy/tests/tsconfig.json
- packages/miniflare/src/index.ts
- packages/miniflare/src/runtime/index.ts
- packages/miniflare/src/shared/error.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- packages/wrangler/src/d1/execute.ts
- packages/wrangler/src/dev/miniflare/stdio.ts
- packages/wrangler/src/index.ts
- Wrangler uses a lot of code from `@cloudflare/containers-shared`. Sometimes, that code throws an error. Previously, it threw a plain `Error` class, which Wrangler treated as a _system_ error, allowing users to report it to Sentry. However, pretty much all of those errors should actually have been treated as _user_ errors, which don't get reported to Sentry. As such, `@cloudflare/containers-shared` now has it's own `UserError` class which Wrangler will recognise as well.
- Miniflare previously reported all startup errors as `ERR_RUNTIME_FAILED`. Now, we distinguish between user and system errors, and report the common case of "Address in use" errors as a user error
- D1 previously threw an `Error` class when something went wrong querying SQL—that's now a `UserError`
---
- Tests
- Public …
> Mark more errors as `UserError`

- .changeset/moody-hands-sort.md
- packages/create-cloudflare/e2e/tests/cli/cli.test.ts
- packages/create-cloudflare/e2e/tests/frameworks/test-config.ts
- packages/create-cloudflare/src/frameworks/package.json
- packages/create-cloudflare/src/templates.ts
- packages/create-cloudflare/templates/waku/c3.ts
- packages/create-cloudflare/templates/waku/wrangler.jsonc
Fixes #7594.
Adding a C3 template for Waku, a minimal React framework. https://waku.gg/
- Tests
> feat: add Waku to C3

- .changeset/spotty-knives-roll.md
- packages/wrangler/e2e/secrets-store.test.ts
- packages/wrangler/src/__tests__/cfetch-utils.test.ts
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/pages/functions-build.test.ts
- packages/wrangler/src/__tests__/pages/pages-build-env.test.ts
- packages/wrangler/src/__tests__/pages/pages-download-config.test.ts
- packages/wrangler/src/__tests__/pages/secret.test.ts
- packages/wrangler/src/__tests__/r2.test.ts
- packages/wrangler/src/__tests__/secret.test.ts
- packages/wrangler/src/api/startDevWorker/DevEnv.ts
- packages/wrangler/src/dev/remote.ts
- packages/wrangler/src/index.ts
- packages/wrangler/src/logger.ts
- packages/wrangler/src/utils/isAbortError.ts
Fixes [DEVX-2213](https://jira.cfdata.org/browse/DEVX-2213)
Previously, the `formatMessage` utility was heavily used across the Wrangler codebase to nicely format `ParseError`-style error messages. This led to nice display, but had two problems:
- It was used via `logger.log(formatMessage(...))`, which meant that a large chunk of Wrangler's error messages were shoing up in stdout rather than stderr
- It needed to be used intentionally, which meant that in various places we logged out a potentional `ParseError` without applying the formatting (leading to hard to understand stack traces being shown to users when e.g. a preview session failed)
Now, `logger.error()` will automatically apply `formatMessage()` when the first argument is a `ParseError`
---
- Tests
- …
> Improve error logging

- .changeset/silly-parks-fall.md
- packages/create-cloudflare/src/__tests__/templates.test.ts
- packages/create-cloudflare/src/templates.ts
Previously we only looked for `.env*` in the `gitignore` but now we cover more cases such as:
- `.env`
- `.env\*`
- `.env.<local|production|staging>`
- `.env\*.<local|production|staging>`
Fixes https://github.com/cloudflare/workers-sdk/issues/10749
---
- Tests
> Do not override any `.env` settings in `.gitignore` files

- .changeset/tangy-donuts-jog.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/__tests__/helpers/mock-workers-subdomain.ts
- packages/wrangler/src/__tests__/utils/retry.test.ts
- packages/wrangler/src/__tests__/versions/versions.upload.test.ts
- packages/wrangler/src/cfetch/index.ts
- packages/wrangler/src/cfetch/internal.ts
- packages/wrangler/src/triggers/deploy.ts
- packages/wrangler/src/utils/retry.ts
We were seeing some flakes in CI such as https://github.com/cloudflare/workers-sdk/actions/runs/18130487486/job/51595708301?pr=10766#step:6:9893
I discussed with the D&C team and they identified that this is a problem internally but there is not a clear fix at this stage.
They confirmed that an acceptable mitigation would be to retry (a few times) the request if it fails with a 500 response.
---
Notable aspects of this PR:
- the utility function was writing messages to `console.log()` when retrying but this seems wrong, since the user shouldn't care about this - these logs have been moved to `console.debug()`.
- the utility function only retried 5xx errors but the `fetchRequest()` helper did not provide the response status to the new `APIError` so these were not being retried - this has …
> retry subdomain requests to be more resilient to flakes

- .changeset/puny-coins-dream.md
- packages/wrangler/src/__tests__/deploy.test.ts
- packages/wrangler/src/deploy/deploy.ts
> switch zone route warning to an info message

- .changeset/polite-paths-raise.md
- fixtures/workflow/src/index.ts
- fixtures/workflow/tests/index.test.ts
- packages/workflows-shared/src/binding.ts
Fixes WOR-929.
Issue: https://github.com/cloudflare/workers-sdk/issues/10806
Creating an instance and immediately after calling a Response redirect (that will call that instance) in local dev causes the instance to not be found, because it is actually never created.
Simplified code:
```typescript
if (path === "/trigger-with-redirect") {
const workflow = await env.TEST_WORKFLOW.create();
return Response.redirect(
new URL(`/status?id=${workflow.id}`, url).toString(),
302
);
}
if (path === "/status") {
const id = url.searchParams.get("id"); 
const instance = await env.TEST_WORKFLOW.get(id); // BREAKS HERE -> instance.not_found
const status = await instance.status();
}
```
Because in local dev our `create()` method does not await for anything. `create()` calls the Engine DO `init()` that will …
> [Workflows] Fix Workflows failure with redirect after creation

- .changeset/mean-parks-take.md
- fixtures/worker-logs/tests/index.test.ts
- packages/wrangler/src/dev/miniflare/stdio.ts
Fixes https://github.com/cloudflare/workers-sdk/issues/10690
The changes in https://github.com/cloudflare/workers-sdk/pull/10004 made sure that wrangler prints logs at the correct log level.
This however caused `console.debug` logs not to be printed anymore at the default info level. Users also cannot get their debug logs (via `--log-level=debug`) without also getting all the noisy Wrangler logs.
So it's been decided that for the time being wrangler should log `console.debug` logs at the info level so that users keep getting them as they are used to. Then in the next major wrangler release we should update wrangler to print those logs in the debug level instead but also introduce some mechanism for allowing users to opt-out/in to the wrangler noisy debug logs.
---
- Tests
- Public …
> Wrangler: fix `console.debug` logs not being logged at the `info` level (as users expect)

- .changeset/neat-eyes-roll.md
- packages/vite-plugin-cloudflare/playground/containers/entry.wrangler.jsonc
- packages/vite-plugin-cloudflare/playground/containers/src/entry.ts
- packages/vite-plugin-cloudflare/playground/containers/vite.config.ts
- packages/vite-plugin-cloudflare/src/containers.ts
- packages/vite-plugin-cloudflare/src/index.ts
- packages/vite-plugin-cloudflare/src/miniflare-options.ts
Fixes #10178 & DEVX-2159
Support containers on Vite auxiliary Workers
---
- Tests
> Support containers on Vite auxiliary Workers

- .changeset/little-numbers-report.md
- packages/unenv-preset/package.json
- packages/unenv-preset/src/preset.ts
- packages/unenv-preset/src/runtime/node/process.ts
- packages/wrangler/e2e/unenv-preset/worker/index.ts
- pnpm-lock.yaml
Fixes https://github.com/cloudflare/workers-sdk/issues/10855
Astro detects Node with:
```ts
const isNode = typeof process !== "undefined" && Object.prototype.toString.call(process) === "[object process]";
```
With `unenv` process would `toString` as `[object Object]` and `isNode` is `false`.
The the v2 implementation from @guybedford it `toString` as `[object process]` to match the Node implementation (this is correct) so `isNode` becomes `true`
However, when Node is detected, Astro construct a response from an `AsyncIterable`:
```ts
if (streaming) {
if (isNode && !isDeno) {
const nodeBody = await renderToAsyncIterable(
result,
componentFactory,
props,
children,
true,
route
);
body = nodeBody;
} else {
body = await renderToReadableStream(result, componentFactory, props, children, true, …
```
> Revert 10805 (Drop process polyfill when v2 is available)

- .changeset/mean-parks-take.md
- fixtures/worker-logs/tests/index.test.ts
- packages/wrangler/src/dev/miniflare/stdio.ts
> V3 backport #10757

- packages/wrangler/src/__tests__/cert.test.ts
- packages/wrangler/src/__tests__/mtls-certificates.test.ts
The snapshots in the cert.test.ts were originally "dynamic" with the current date being inserted.
When we bumped the snapshots (as is normal) these dynamic bits got blown away and we froze the dates at the point in time we did the bump (e.g. yesterday). So now they fail today.
This fixes the problem by hard coding dates in to the tests overall so that the snapshots are stable.
> test: fix snapshots for certificate tests

- .changeset/blue-dancers-cry.md
- .github/workflows/deploy-pages-previews.yml
- packages/workers-playground/src/QuickEditor/VSCodeEditor.tsx
This is causing 522 errors, because fetching a Workers preview (on workers.dev) doesn't seem to be a cross-zone fetch in the way fetching a Pages preview is. This needs more investigation.
> Revert "Use updated VSCode"
